// Supplemental schema probe generated from disposable PostgreSQL; application RPCs use canonical Database types.
import type { Json } from "../supabase/database.types";
export type PartnerFoundationTables = {
 partner_benefit_reviews: {
  id: string;
  provider_id: string;
  revision_id: string;
  state: string;
  actor_id: string;
  request_id: string;
  created_at: string;
 };
 partner_benefit_revisions: {
  id: string;
  provider_id: string;
  source_id: string;
  source_revision: number;
  contract_id: string;
  category: string;
  title: string;
  public_description: string;
  member_terms: string;
  exclusions: string;
  country: string;
  region: string;
  market_id: string | null;
  product_id: string;
  minimum_tier: string;
  fulfillment: string;
  starts_at: string;
  ends_at: string;
  source_digest: string;
  created_at: string;
 };
 partner_benefit_sources: {
  id: string;
  provider_id: string;
  external_id: string;
  current_revision: number;
  current_digest: string | null;
  status: string;
  last_verified_at: string | null;
 };
 partner_catalog_snapshots: {
  id: string;
  provider_id: string;
  expected_items: number;
  status: string;
  created_by: string;
  created_at: string;
 };
 partner_commission_policies: {
  id: string;
  provider_id: string;
  contract_id: string;
  revision: number;
  currency: string;
  basis: string;
  fixed_minor: number | null;
  rate_ppm: number | null;
  recognition_condition: string;
  starts_at: string;
  ends_at: string;
  created_by: string;
  created_at: string;
 };
 partner_config_revisions: {
  id: string;
  provider_id: string;
  revision: number;
  module_id: string;
  method: string;
  capabilities: string[];
  credential_reference: string | null;
  credentials_ready: boolean;
  operational: boolean;
  full_withdraw_missing: boolean;
  max_stale_seconds: number;
  starts_at: string;
  ends_at: string | null;
  created_by: string;
  created_at: string;
 };
 partner_contract_events: {
  id: string;
  provider_id: string;
  contract_id: string;
  state: string;
  actor_id: string;
  approval_reference: string;
  request_id: string;
  created_at: string;
 };
 partner_contract_revisions: {
  id: string;
  provider_id: string;
  revision: number;
  document_reference: string;
  rights_holder_reference: string;
  countries: string[];
  categories: string[];
  methods: string[];
  product_id: string;
  minimum_tier: string;
  display_rights: boolean;
  caching_rights: boolean;
  branding_rules: string;
  attribution_rules: string;
  sharing_fields: string[];
  retention_days: number;
  refund_policy_reference: string;
  starts_at: string;
  ends_at: string;
  created_by: string;
  created_at: string;
 };
 partner_import_quarantine: {
  id: string;
  run_id: string;
  item_index: number;
  external_id: string | null;
  category: string;
  created_at: string;
 };
 partner_import_runs: {
  id: string;
  provider_id: string;
  feed_sequence: number;
  kind: string;
  synthetic: boolean;
  digest: string;
  accepted: number;
  quarantined: number;
  withdrawn: number;
  actor_id: string;
  request_id: string;
  created_at: string;
  snapshot_id: string | null;
 };
 partner_provider_events: {
  id: string;
  provider_id: string;
  state: string;
  actor_id: string;
  reason: string;
  request_id: string;
  created_at: string;
 };
 partner_providers: {
  id: string;
  key: string;
  name: string;
  legal_reference: string | null;
  support_reference: string | null;
  state: string;
  version: number;
  synthetic: boolean;
  created_by: string;
  created_at: string;
 };
 partner_snapshot_items: {
  snapshot_id: string;
  source_id: string;
  run_id: string;
 };
 partner_territories: {
  id: string;
  provider_id: string;
  contract_id: string;
  country: string;
  region: string;
  market_id: string | null;
  status: string;
  starts_at: string;
  ends_at: string;
  created_by: string;
  created_at: string;
 };
 partner_transaction_events: {
  id: string;
  provider_id: string;
  transaction_id: string;
  external_event_id: string;
  kind: string;
  adjustment_minor: number;
  corrects_event_id: string | null;
  evidence_reference: string;
  actor_id: string;
  request_id: string;
  created_at: string;
 };
 partner_transaction_sources: {
  id: string;
  provider_id: string;
  external_id: string;
  benefit_revision_id: string;
  policy_id: string;
  currency: string;
  eligible_minor: number;
  attributed_person_id: string | null;
  native_sales_lead_id: string | null;
  synthetic: boolean;
  occurred_at: string;
  evidence_reference: string;
  created_by: string;
  created_at: string;
 };
};
export type PartnerFoundationFunctions = {
 boss_partners_directory: { Args: Record<string, never>; Returns: Json };
 boss_partners_mutate: { Args: { command: Json }; Returns: Json };
 boss_partners_read: { Args: { query: Json }; Returns: Json };
};
