begin;
set local statement_timeout='8s';
\ir phase6e/fixture.sql

select pg_temp.check('canonical Phase 6C athlete honor reused','CANONICAL',(select count(*)=1 from public.athlete_achievements where profile_id=pg_temp.pe_id('profile')and definition_revision_id is not null));
select pg_temp.check('complete canonical milestone qualifies once','MILESTONE',(select count(*)=1 and bool_and(state='current')from public.achievement_recognitions where profile_id=pg_temp.pe_id('profile')));
select pg_temp.check('source provenance names summary IDs','PROVENANCE',(select source_type='stat_summary'and source_manifest?'sources'and organization_id=pg_temp.f('org')and team_id=pg_temp.f('falcons')from public.achievement_recognitions where profile_id=pg_temp.pe_id('profile')));
select pg_temp.check('new showcase display defaults hidden','CONSENT',not exists(select 1 from public.achievement_display_choices where show_on_showcase));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.pe_evaluate('career_one');select pg_temp.pe_evaluate('career_one',true);
reset role;
select pg_temp.check('evaluation and rebuild never duplicate earned honor','IDEMPOTENCY',(select count(*)=1 from public.athlete_achievements where profile_id=pg_temp.pe_id('profile')));
select pg_temp.check('rebuild retains identical immutable history','REBUILD',(select count(*)=1 from public.achievement_history));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.pe_definition('career_half',pg_temp.pe_rule('career_half','{"threshold":0.5,"tier":"bronze"}'));
select pg_temp.pe_evaluate('career_half');
select pg_temp.pe_definition('career_two',pg_temp.pe_rule('career_two','{"threshold":2,"tier":"silver"}'));
select pg_temp.pe_evaluate('career_two');
reset role;
select pg_temp.check('distinct legitimate thresholds remain distinct','MULTIPLE_THRESHOLD',(select count(*)=2 from public.achievement_recognitions where profile_id=pg_temp.pe_id('profile')));
select pg_temp.check('uncrossed threshold does not create honor','MILESTONE',not exists(select 1 from public.achievement_recognitions r join public.achievement_definition_revisions d on d.id=r.definition_revision_id where d.threshold=2));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.pe('award.nominate',jsonb_build_object('definition_id',pg_temp.pe_id('manual_mvp'),'organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'profile_id',pg_temp.pe_id('profile'),'achieved_at',clock_timestamp(),'note','Synthetic private issuer rationale'),'mvp');
reset role;
select pg_temp.check('nomination is not award approval','APPROVAL',(select state='nominated'and recognition_id is null from public.award_nominations where id=pg_temp.pe_id('mvp')));
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.denied('coach role cannot infer approval',format('select public.boss_achievement_mutate(%L::jsonb)',jsonb_build_object('action','award.approve','request_id',gen_random_uuid(),'input',jsonb_build_object('nomination_id',pg_temp.pe_id('mvp'),'expected_version',1,'note','Forbidden'))),'PT403');
select pg_temp.actor('admin');select pg_temp.pe('award.approve',jsonb_build_object('nomination_id',pg_temp.pe_id('mvp'),'expected_version',1,'note','Synthetic authorized approval'));
reset role;
select pg_temp.check('manual fact labeled organization verified','MANUAL',(select verification_level='organization_verified'from public.athlete_achievements where title='Synthetic MVP'));
select pg_temp.check('approved canonical decision is immutable','AUDIT',(select count(*)=2 from public.award_decisions where nomination_id=pg_temp.pe_id('mvp')));
select pg_temp.denied('cannot rewrite award note',format('update public.award_decisions set private_note=''rewrite''where nomination_id=%L',pg_temp.pe_id('mvp')),'23514');
update public.guardian_relationships set can_manage_profile=true where id=pg_temp.f('guardian-child1');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('family sees child honors only','FAMILY',jsonb_array_length(public.boss_achievement_read(jsonb_build_object('profile_id',pg_temp.pe_id('profile')))->'recognitions')=3);
select pg_temp.check('family projection excludes issuer notes','PRIVACY',public.boss_achievement_read(jsonb_build_object('profile_id',pg_temp.pe_id('profile')))::text not like'%private issuer rationale%');
select pg_temp.actor('admin');select pg_temp.pe('award.revoke',jsonb_build_object('nomination_id',pg_temp.pe_id('mvp'),'expected_version',2,'note','Synthetic wrong award corrected'));
reset role;
select pg_temp.check('revoke keeps historical honor row','REVOCATION',(select count(*)=1 from public.athlete_achievements where title='Synthetic MVP'));
select pg_temp.check('revoke changes current presentation','REVOCATION',(select state='revoked'from public.achievement_recognitions where source_id=pg_temp.pe_id('mvp')));
set local role authenticated;select pg_temp.actor('admin');select pg_temp.pe('award.restore',jsonb_build_object('nomination_id',pg_temp.pe_id('mvp'),'expected_version',3,'note','Synthetic restoration'));
select pg_temp.pe('definition.revise',jsonb_build_object('definition_id',pg_temp.pe_id('career_two'),'expected_version',1,'revision',pg_temp.pe_rule('Revised threshold','{"threshold":3}')));
reset role;
select pg_temp.check('threshold revision preserves old meaning','VERSION',(select array_agg(threshold order by revision)=array[2,3]::numeric[]from public.achievement_definition_revisions where definition_id=pg_temp.pe_id('career_two')));
select pg_temp.denied('definition history cannot be rewritten',format('update public.achievement_definition_revisions set threshold=100 where definition_id=%L',pg_temp.pe_id('career_one')),'23514');
-- Manual award dates may precede definition activation: the explicit decision is the source.
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.pe_definition('manual_current_policy',pg_temp.pe_rule('Same-day selected award','{"category":"sportsmanship","source_kind":"organization_decision","metric_key":null,"threshold":null,"historical_evaluation":false}')-array['metric_key','threshold']);
select pg_temp.pe('award.nominate',jsonb_build_object('definition_id',pg_temp.pe_id('manual_current_policy'),'organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'profile_id',pg_temp.pe_id('profile'),'achieved_at',clock_timestamp()-interval'1 minute','note','Synthetic earlier same-day award'),'current-policy-award');
select pg_temp.pe('award.approve',jsonb_build_object('nomination_id',pg_temp.pe_id('current-policy-award'),'expected_version',1,'note','Synthetic explicit selection'));
reset role;
select pg_temp.check('same-day manual decision creates its canonical honor','MANUAL_TIMING',(select n.state='awarded'and r.state='current'and aa.verification_level='organization_verified'from public.award_nominations n join public.achievement_recognitions r on r.id=n.recognition_id join public.athlete_achievements aa on aa.id=r.athlete_achievement_id where n.id=pg_temp.pe_id('current-policy-award')));
select pg_temp.check('manual decision preserves explicit earlier achievement date','MANUAL_TIMING',(select r.achieved_at=n.achieved_at and r.achieved_at<d.effective_at from public.award_nominations n join public.achievement_recognitions r on r.id=n.recognition_id join public.achievement_definition_revisions d on d.id=n.definition_revision_id where n.id=pg_temp.pe_id('current-policy-award')));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.pe_definition('automatic_current_policy',pg_temp.pe_rule('No implicit retroactive milestone',jsonb_build_object('historical_evaluation',false,'effective_at',clock_timestamp()+interval'100 years')));
select pg_temp.pe_evaluate('automatic_current_policy');
reset role;
select pg_temp.check('automatic effective-date policy remains enforced','EFFECTIVE_POLICY',not exists(select 1 from public.achievement_recognitions r join public.achievement_definition_revisions d on d.id=r.definition_revision_id where d.definition_id=pg_temp.pe_id('automatic_current_policy')));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.pe_definition('manual_closed_profile',pg_temp.pe_rule('Closed recipient award','{"category":"sportsmanship","source_kind":"organization_decision","metric_key":null,"threshold":null,"historical_evaluation":false}')-array['metric_key','threshold']);
select pg_temp.pe('award.nominate',jsonb_build_object('definition_id',pg_temp.pe_id('manual_closed_profile'),'organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'profile_id',pg_temp.pe_id('profile'),'achieved_at',clock_timestamp(),'note','Synthetic recipient closure race'),'closed-profile-award');
reset role;update public.athlete_profiles set status='archived'where id=pg_temp.pe_id('profile');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.denied('closed recipient cannot silently approve an empty award',format('select public.boss_achievement_mutate(%L::jsonb)',jsonb_build_object('action','award.approve','request_id',gen_random_uuid(),'input',jsonb_build_object('nomination_id',pg_temp.pe_id('closed-profile-award'),'expected_version',1,'note','Synthetic no longer available recipient'))),'PT409');
reset role;
select pg_temp.check('failed approval retains nominated decision baseline','MANUAL_ATOMICITY',(select state='nominated'and version=1 and recognition_id is null from public.award_nominations where id=pg_temp.pe_id('closed-profile-award'))and(select count(*)=1 from public.award_decisions where nomination_id=pg_temp.pe_id('closed-profile-award')));
update public.athlete_profiles set status='active'where id=pg_temp.pe_id('profile');
-- Real canonical correction: remove the source from official qualification.
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.game_op('game.reopen','ranking-game','{"reason":"Synthetic achievement source correction"}');
select public.boss_stat_competition_classify(pg_temp.ff_game('ranking-game'),'excluded','Synthetic excluded achievement source',gen_random_uuid());
select pg_temp.game_op('game.finalize','ranking-game');
reset role;
select pg_temp.check('dirty canonical selector cannot appear current','FRESHNESS',(select bool_and(boss_private.achievement_live_state(r)<>'current')from public.achievement_recognitions r join public.achievement_definition_revisions d on d.id=r.definition_revision_id where d.source_kind='athlete_career'));
select boss_private.stat_refresh(pg_temp.ff_game('ranking-game'));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.pe_evaluate('career_one');select pg_temp.pe_evaluate('career_half');
reset role;
select pg_temp.check('canonical correction invalidates milestone','CORRECTION',(select bool_and(r.state='corrected')from public.achievement_recognitions r join public.achievement_definition_revisions d on d.id=r.definition_revision_id where d.source_kind='athlete_career'));
select pg_temp.check('corrected history retained','HISTORY',(select count(*)>=2 from public.achievement_history h join public.achievement_recognitions r on r.id=h.recognition_id where r.definition_revision_id=(select current_revision_id from public.achievement_definitions where id=pg_temp.pe_id('career_one'))));
select pg_temp.check('notification source carries no note','NOTIFICATIONS',not exists(select 1 from public.notification_events where source_type='achievement_history'and safe_data::text like'%rationale%'));
select count(*)passed_assertions from pg_temp.phase5a_assertions;
rollback;
