begin;
\ir phase5f/fixture.sql
set local role authenticated;select pg_temp.actor('admin');select pg_temp.dd_create('security');select pg_temp.dd_create('foreign');
select pg_temp.denied('legacy summary cannot bypass Diamond','select pg_temp.game_op(''game.score.set'',''security'',''{"primary_score":99,"opponent_score":0}'')','PT409');
select pg_temp.denied('legacy roster cannot bypass frozen Diamond roster','select pg_temp.game_op(''game.roster.snapshot'',''security'')','PT403');
select pg_temp.denied('premature final','select pg_temp.game_op(''game.finalize'',''security'')','PT409');
select pg_temp.denied('forged same-tenant other-game athlete',format('select pg_temp.dd_op(''diamond.pa.start'',''security'',%L::jsonb)',jsonb_build_object('payload',jsonb_build_object('kind','pa_start','key',gen_random_uuid(),'batter',pg_temp.ff_roster('foreign','primary',1)))),'PT403');
select pg_temp.denied('opposite-side athlete',format('select pg_temp.dd_op(''diamond.pa.start'',''security'',%L::jsonb)',jsonb_build_object('payload',jsonb_build_object('kind','pa_start','key',gen_random_uuid(),'batter',pg_temp.ff_roster('security','opponent',1)))),'PT403');
select pg_temp.denied('forged extra team input','select pg_temp.dd_op(''diamond.pa.start'',''security'',''{"team_id":"11111111-1111-4111-8111-111111111111","payload":{"kind":"pa_start","key":"11111111-1111-4111-8111-111111111112","batter":null}}'')','PT422');
select pg_temp.denied('client cannot fabricate pitch coverage','select pg_temp.dd_op(''diamond.pa.start'',''security'',''{"payload":{"kind":"pa_start","key":"11111111-1111-4111-8111-111111111112","batter":null,"pitch_tracking":true}}'')','PT422');
select pg_temp.dd_pa('security','secpa1');
select pg_temp.denied('disabled pitch detail','select pg_temp.dd_op(''diamond.pitch.add'',''security'',''{"payload":{"kind":"pitch","outcome":"ball"}}'')','PT403');
create temp table dd_retry(command jsonb);grant select,insert on dd_retry to authenticated;
insert into dd_retry values(pg_temp.game_command('diamond.play.add','security',jsonb_build_object('sport_key','baseball','payload',jsonb_build_object('kind','play','result','single','moves',jsonb_build_array(pg_temp.dd_move(0,1))))));
select public.boss_games_mutate(pg_temp.f('dd-request'),command)from dd_retry;
select public.boss_games_mutate(pg_temp.f('dd-request'),command)from dd_retry;
select pg_temp.check('retry one hit and one PA','RECEIPT',pg_temp.dd_stats('security','primary')@>'{"pa":1,"hits":1,"ab":1}');
select pg_temp.denied('same id conflicting input','select public.boss_games_mutate(pg_temp.f(''dd-request''),command||jsonb_build_object(''input'',command->''input''||''{"expected_version":1}''))from dd_retry','PT409');
select pg_temp.actor('parent');select pg_temp.denied('guardian not operator','select pg_temp.dd_pa(''security'',''guardian-pa'')','PT403');
select pg_temp.actor('household-only');select pg_temp.denied('household not operator','select pg_temp.dd_pa(''security'',''household-pa'')','PT403');
select pg_temp.actor('other-admin');select pg_temp.denied('cross-tenant operation','select pg_temp.game_op(''diamond.pa.start'',''security'',''{"sport_key":"baseball","payload":{"kind":"pa_start","key":"11111111-1111-4111-8111-111111111112","batter":null}}'')','PT403');
reset role;
update pg_temp.phase5a_games f set version=g.version from public.games g where g.id=pg_temp.ff_game(f.label);
select pg_temp.check('raw RLS all five tables','RLS',(select count(*)=5 and bool_and(c.relrowsecurity)from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'and c.relkind='r'and c.relname like'game_diamond_%'));
select pg_temp.check('raw ACL no client read or write','ACL',not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'and c.relkind='r'and c.relname like'game_diamond_%'and(has_table_privilege('authenticated',c.oid,'SELECT,INSERT,UPDATE,DELETE')or has_table_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,DELETE'))));
select pg_temp.check('private helper ACL no direct client call','ACL',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='boss_private'and p.proname like'diamond_%'and(has_function_privilege('authenticated',p.oid,'EXECUTE')or has_function_privilege('anon',p.oid,'EXECUTE'))));
select pg_temp.check('no new permission mapping','ACL',(select count(*)=21 from public.roles WHERE key <> 'competition_manager')and(select count(*)=59 from public.permissions WHERE key NOT IN ('competition.view','competition.manage','competition.policy_manage','standings.view','standings.manage','standings.rebuild','leaderboard.view','leaderboard.manage','leaderboard.rebuild','records.view','records.manage','records.rebuild','athlete_profiles.view','athlete_profiles.manage','athlete_profiles.verify','recruiting_showcases.view','recruiting_showcases.manage','recruiting_showcases.publish','achievement_definitions.manage','awards.issue','awards.approve','fundraising.view','fundraising.create','fundraising.manage','fundraising.publish','fundraising.financial_view','money_board.view','money_board.manage','boss_bucks.view','boss_bucks.manage','boss_bucks.financial_view','boss_bucks.policy_manage'))and(select count(*)=446 from public.role_permissions rp JOIN public.permissions p ON p.id=rp.permission_id WHERE p.key NOT IN ('competition.view','competition.manage','competition.policy_manage','standings.view','standings.manage','standings.rebuild','leaderboard.view','leaderboard.manage','leaderboard.rebuild','records.view','records.manage','records.rebuild','athlete_profiles.view','athlete_profiles.manage','athlete_profiles.verify','recruiting_showcases.view','recruiting_showcases.manage','recruiting_showcases.publish','achievement_definitions.manage','awards.issue','awards.approve','fundraising.view','fundraising.create','fundraising.manage','fundraising.publish','fundraising.financial_view','money_board.view','money_board.manage','boss_bucks.view','boss_bucks.manage','boss_bucks.financial_view','boss_bucks.policy_manage')));
select pg_temp.denied('PA cannot disappear by delete',format('delete from public.game_diamond_plate_appearances where game_id=%L::uuid',pg_temp.ff_game('security')),'23514');
select pg_temp.denied('raw facts cannot rewrite',format('update public.game_diamond_events set payload=''{}''where game_id=%L::uuid',pg_temp.ff_game('security')),'23514');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.game_op('game.operator.assign','security',jsonb_build_object('person_id',pg_temp.f('scorer'),'role_assignment_id',pg_temp.f('role-scorer'),'function_key','scorekeeper','team_id',pg_temp.f('falcons'),'ends_at',clock_timestamp()+interval '1 hour'));
select pg_temp.actor('scorer');select pg_temp.dd_pa('security','scorer-pa');
select pg_temp.denied('operator cannot manage tracking defaults',format('select public.boss_games_mutate(gen_random_uuid(),pg_temp.cmd(''tracking.profile.set'',%L::jsonb))',jsonb_build_object('sport_key','baseball','scope_type','game','organization_id',pg_temp.f('org'),'game_id',pg_temp.ff_game('security'),'side','primary','expected_profile_version',1,'expected_game_version',100,'preset','full','reason','Synthetic denied profile')),'PT403');
reset role;
update public.game_operator_assignments set status='inactive'where person_id=pg_temp.f('scorer');
set local role authenticated;select pg_temp.actor('scorer');select pg_temp.denied('revoked operator cannot submit signed stale input','select pg_temp.dd_play(''security'',''single'',jsonb_build_array(pg_temp.dd_move(1,2),pg_temp.dd_move(0,1)))','PT403');
reset role;
update public.organization_modules set configuration=configuration||'{"baseball_live_scoring":false}'where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='sports');
set local role authenticated;select pg_temp.actor('admin');select pg_temp.denied('disable does not restore manual score','select pg_temp.game_op(''game.score.set'',''security'',''{"primary_score":99,"opponent_score":0}'')','PT409');
reset role;
select count(*)passed_assertions from pg_temp.phase5a_assertions;
rollback;
