\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase7e/fixture.sql
create function pg_temp.card(n integer,key text default 'card_id',label text default 'batch')returns text language sql stable as $$select pg_temp.dr(label)->'one_time_cards'->(n-1)->>key$$;
grant execute on function pg_temp.card(integer,text,text)to authenticated;
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.dm('batch','batch.create',jsonb_build_object('revision_id',pg_temp.did('card90','revision_id'),'organization_id',pg_temp.f('org'),'owner_type','organization','name','SYNTHETIC bounded batch','quantity',4,'controlled',true));
select pg_temp.dm('print','cards.print',jsonb_build_object('organization_id',pg_temp.f('org'),'card_ids',jsonb_build_array(pg_temp.card(1),pg_temp.card(2),pg_temp.card(3),pg_temp.card(4))));
select pg_temp.dm('assign','cards.assign',jsonb_build_object('organization_id',pg_temp.f('org'),'campaign_id',pg_temp.fid('campaign'),'fundraiser_id',pg_temp.fid('fundraiser'),'card_ids',jsonb_build_array(pg_temp.card(1))));
select pg_temp.conflict('card cannot be assigned twice',format('select pg_temp.dm(''double-assign'',''cards.assign'',%L)',jsonb_build_object('organization_id',pg_temp.f('org'),'campaign_id',pg_temp.fid('campaign'),'fundraiser_id',pg_temp.fid('fundraiser'),'card_ids',jsonb_build_array(pg_temp.card(1)))));
select pg_temp.denied('unrelated organization cannot take card',format('select pg_temp.dm(''other-assignment'',''cards.assign'',%L)',jsonb_build_object('organization_id',pg_temp.f('other-org'),'campaign_id',pg_temp.fid('campaign'),'card_ids',jsonb_build_array(pg_temp.card(2)))),'PT422');
select pg_temp.actor('parent');
select pg_temp.denied('serial alone grants no activation',format('select pg_temp.dm(''serial-only'',''card.claim'',%L)',jsonb_build_object('serial',pg_temp.card(1,'serial'),'activation_secret',repeat('a',64))),'PT404');
select pg_temp.dm('activation','card.claim',jsonb_build_object('serial',pg_temp.card(1,'serial'),'activation_secret',pg_temp.card(1,'activation_secret')));
select pg_temp.dm('activation','card.claim',jsonb_build_object('serial',pg_temp.card(1,'serial'),'activation_secret',pg_temp.card(1,'activation_secret')));
select pg_temp.check('same claim replay uses original member','IDEMPOTENCY',pg_temp.dr('activation')->'replayed'='true'::jsonb);
select pg_temp.check('ninety day trial starts on activation','TRIAL',pg_temp.dr('activation')->'effective'->>'state'='trial');
select pg_temp.actor('household-only');
select pg_temp.denied('second account cannot claim same card',format('select pg_temp.dm(''second-claim'',''card.claim'',%L)',jsonb_build_object('serial',pg_temp.card(1,'serial'),'activation_secret',pg_temp.card(1,'activation_secret'))),'PT404');
select pg_temp.actor('admin');
select pg_temp.dm('replace','card.replace',jsonb_build_object('card_id',pg_temp.card(1),'replacement_card_id',pg_temp.card(2),'reason','lost'));
select pg_temp.actor('parent');
select pg_temp.denied('old replaced credential cannot replay activation',format('select pg_temp.dm(''activation'',''card.claim'',%L)',jsonb_build_object('serial',pg_temp.card(1,'serial'),'activation_secret',pg_temp.card(1,'activation_secret'))));
select pg_temp.denied('new staff authority never implied by card claim',format('select pg_temp.dm(''parent-void'',''cards.void'',%L)',jsonb_build_object('organization_id',pg_temp.f('org'),'card_ids',jsonb_build_array(pg_temp.card(3)))));
reset role;
select pg_temp.check('replacement retains persistent identity','REPLACEMENT',(select membership_id=pg_temp.did('activation')and claimed_at=(select claimed_at from public.discount_physical_cards where id=pg_temp.card(1)::uuid)from public.discount_physical_cards where id=pg_temp.card(2)::uuid));
select pg_temp.check('replacement creates no second trial','REPLACEMENT',(select count(*)=1 from public.discount_member_sources where membership_id=pg_temp.did('activation')));
select pg_temp.check('replacement preserves original serial history','HISTORY',exists(select 1 from public.discount_card_history where card_id=pg_temp.card(1)::uuid and action='replaced'));
select pg_temp.check('trial exact activation anchor','TRIAL',exists(select 1 from public.discount_member_sources s join public.discount_physical_cards c on s.source_key='card-trial:'||c.id where s.starts_at=c.claimed_at and s.ends_at=c.claimed_at+interval'90 days'));
select pg_temp.check('assignment is not payment','SEPARATION',not exists(select 1 from public.discount_orders));
select pg_temp.check('activation secret absent from audit and receipts','PRIVACY',not exists(select 1 from public.audit_events where after_data::text like'%'||pg_temp.card(1,'activation_secret')||'%')and not exists(select 1 from boss_private.discount_requests where result::text like'%'||pg_temp.card(1,'activation_secret')||'%'));
select pg_temp.check('stored card secret is only digest','PRIVACY',(select digest<>pg_temp.card(1,'activation_secret')and digest=encode(sha256(convert_to(pg_temp.card(1,'activation_secret'),'UTF8')),'hex')from boss_private.discount_card_secrets where card_id=pg_temp.card(1)::uuid));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.dm('assign-return','cards.assign',jsonb_build_object('organization_id',pg_temp.f('org'),'campaign_id',pg_temp.fid('campaign'),'card_ids',jsonb_build_array(pg_temp.card(3))));
select pg_temp.dm('return','cards.return',jsonb_build_object('organization_id',pg_temp.f('org'),'card_ids',jsonb_build_array(pg_temp.card(3))));
reset role;
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.revision('platform-stock','physical','{"organization_id":null,"term_days":null,"trial_days":90,"gift_enabled":false,"sale_channels":[],"settlement_policy_id":null,"organization_credit_minor":null,"platform_retained_minor":null,"product_cost_minor":null,"fulfillment_type":"pickup","validity_anchor":"activation","card_validity_days":180}');
select pg_temp.dm('platform-stock-batch','batch.create',jsonb_build_object('revision_id',pg_temp.did('platform-stock','revision_id'),'owner_type','platform','name','SYNTHETIC unassigned platform stock','quantity',1,'controlled',true));
select pg_temp.actor('parent');
select pg_temp.denied('unassigned platform stock grants no trial authority',format('select pg_temp.dm(''unassigned-claim'',''card.claim'',%L)',jsonb_build_object('serial',pg_temp.card(1,'serial','platform-stock-batch'),'activation_secret',pg_temp.card(1,'activation_secret','platform-stock-batch'))),'PT404');
select pg_temp.actor('admin');
select pg_temp.dm('platform-stock-print','cards.print',jsonb_build_object('organization_id',pg_temp.f('org'),'card_ids',jsonb_build_array(pg_temp.card(1,'card_id','platform-stock-batch'))));
select pg_temp.dm('platform-stock-assign','cards.assign',jsonb_build_object('organization_id',pg_temp.f('org'),'campaign_id',pg_temp.fid('campaign'),'card_ids',jsonb_build_array(pg_temp.card(1,'card_id','platform-stock-batch'))));
reset role;
select pg_temp.check('platform stock assignment has exact destination provenance','OWNERSHIP',(select organization_id=pg_temp.f('org')and campaign_id=pg_temp.fid('campaign')and state='assigned'from public.discount_physical_cards where id=pg_temp.card(1,'card_id','platform-stock-batch')::uuid));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.dm('platform-stock-return','cards.return',jsonb_build_object('organization_id',pg_temp.f('org'),'card_ids',jsonb_build_array(pg_temp.card(1,'card_id','platform-stock-batch'))));
select pg_temp.actor('other-admin');
select pg_temp.check('organization inventory cannot see unassigned platform stock','ISOLATION',not exists(select 1 from jsonb_array_elements(public.boss_discounts_read(jsonb_build_object('mode','organization','organization_id',pg_temp.f('other-org')))->'cards')c where c->>'id'=pg_temp.card(1,'card_id','platform-stock-batch')));
reset role;
select pg_temp.check('returned platform stock restores unassigned ownership','OWNERSHIP',(select organization_id is null and campaign_id is null and fundraiser_id is null and state='inventory'from public.discount_physical_cards where id=pg_temp.card(1,'card_id','platform-stock-batch')::uuid));
set constraints all immediate;
select count(*)passed_assertions,'Phase 7E physical inventory'::text suite from phase5a_assertions;
rollback;
