-- Bounded formats, elapsed/display/playing coordinates, lineup policy and honesty.
begin;
\ir phase5c/fixture.sql
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.sc_link('format','external');
do $$declare field text;value jsonb;base jsonb:='{"regulation_segments":4,"segment_seconds":120,"extra_time_segments":2,"extra_time_seconds":60,"lineup_size":1,"enforce_lineup":false,"allow_reentry":true,"max_substitutions":null}';begin
 for field,value in select * from(values('regulation_segments','3'::jsonb),('segment_seconds','59'::jsonb),('segment_seconds','5401'::jsonb),('extra_time_segments','1'::jsonb),('extra_time_seconds','59'::jsonb),('extra_time_seconds','1801'::jsonb),('lineup_size','0'::jsonb),('lineup_size','12'::jsonb),('enforce_lineup','"true"'::jsonb),('allow_reentry','"false"'::jsonb),('max_substitutions','-1'::jsonb),('max_substitutions','101'::jsonb),('segment_seconds','60.5'::jsonb))v(field,value)loop
  perform pg_temp.conflict('bounded Soccer format rejects '||field||'/'||value::text,format('select public.boss_games_mutate(%L,%L)',pg_temp.f('bad-sc-format-'||field||value::text),pg_temp.game_command('soccer.configure','format',base||jsonb_build_object(field,value))));
 end loop;
end$$;
select pg_temp.sc_op('soccer.configure','format','{"regulation_segments":4,"segment_seconds":120,"extra_time_segments":2,"extra_time_seconds":60,"lineup_size":1,"enforce_lineup":false,"allow_reentry":true,"max_substitutions":null}');
select pg_temp.check('explicit four quarters and small-side untracked format','FORMAT',pg_temp.sc_detail('format')->>'regulation_segments'='4' and pg_temp.sc_detail('format')->>'lineup_size'='1' and not(pg_temp.sc_detail('format')->>'enforce_lineup')::boolean);
reset role;
do $$declare flag text;command jsonb:=pg_temp.game_command('game.start','format');begin
 foreach flag in array array['soccer_live_scoring','soccer_stats','game_operations']loop
  update public.organization_modules set configuration=configuration||jsonb_build_object(flag,false)where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='sports');
  set local role authenticated;perform pg_temp.actor('admin');
  perform pg_temp.denied('disabled '||flag||' denies retained Soccer start',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-disabled-start-'||flag),command),'PT403');
  perform pg_temp.check('disabled '||flag||' hides Start capability','FEATURE',not(select(g->'capabilities'->>'start')::boolean from jsonb_array_elements(public.boss_games_read(pg_temp.query('format'))->'games')g));
  reset role;
  perform pg_temp.check('disabled '||flag||' leaves pregame/version unchanged','FEATURE',(select started_at is null and version=(command->'input'->>'expected_version')::bigint from public.games where id=pg_temp.sc_game('format')));
  update public.organization_modules set configuration=configuration||jsonb_build_object(flag,true)where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='sports');
 end loop;
end$$;
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.game_op('game.start','format');select pg_temp.sc_op('soccer.segment.start','format');
select pg_temp.sc_op('soccer.clock.start','format');
select pg_temp.denied('running Soccer clock rejects duplicate Start',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-clock-running-start'),pg_temp.game_command('soccer.clock.start','format')),'PT409');
select pg_temp.denied('clock correction must first stop running clock',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-clock-running-set'),pg_temp.game_command('soccer.clock.set','format','{"clock_ms":30000,"reason":"Synthetic forbidden running correction"}')),'PT409');
select pg_sleep(0.025);
select pg_temp.check('server elapsed clock advances from anchor','CLOCK',(pg_temp.sc_detail('format')->>'clock_running')::boolean and(pg_temp.sc_detail('format')->>'clock_ms')::bigint between 1 and 119999);
select pg_temp.game_op('game.transition','format','{"status":"paused"}');
create temp table sc_pause(ms bigint);grant select,insert on sc_pause to authenticated;
insert into sc_pause select(pg_temp.sc_detail('format')->>'clock_ms')::bigint;
select pg_sleep(0.025);
select pg_temp.check('canonical pause freezes authoritative elapsed clock','CLOCK',not(pg_temp.sc_detail('format')->>'clock_running')::boolean and(select ms=(pg_temp.sc_detail('format')->>'clock_ms')::bigint from sc_pause));
select pg_temp.state_denied('paused game rejects new goal',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-paused-goal'),pg_temp.game_command('soccer.event.add','format','{"event_type":"goal","side":"primary"}')));
reset role;
do $$declare flag text;command jsonb:=pg_temp.game_command('game.transition','format','{"status":"live"}');begin
 foreach flag in array array['soccer_live_scoring','soccer_stats','game_operations']loop
  update public.organization_modules set configuration=configuration||jsonb_build_object(flag,false)where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='sports');
  set local role authenticated;perform pg_temp.actor('admin');
  perform pg_temp.denied('disabled '||flag||' denies retained Soccer resume',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-disabled-resume-'||flag),command),'PT403');
  perform pg_temp.check('disabled '||flag||' hides Resume capability','FEATURE',not(select(g->'capabilities'->>'resume')::boolean from jsonb_array_elements(public.boss_games_read(pg_temp.query('format'))->'games')g));
  reset role;update public.organization_modules set configuration=configuration||jsonb_build_object(flag,true)where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='sports');
 end loop;
end$$;
set local role authenticated;select pg_temp.actor('admin');select pg_temp.game_op('game.transition','format','{"status":"live"}');
select pg_temp.check('resume leaves clock stopped until operator Start','CLOCK',not(pg_temp.sc_detail('format')->>'clock_running')::boolean);
select pg_temp.sc_clock('format',120000);
select pg_temp.conflict('elapsed beyond nominal needs explicit allowance',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-clock-large'),pg_temp.game_command('soccer.clock.set','format','{"clock_ms":120001,"reason":"Synthetic too large"}')));
select pg_temp.sc_op('soccer.added_time.set','format','{"added_time_seconds":30,"reason":"Synthetic explicit stoppage allowance"}');
select pg_temp.sc_clock('format',150000);
select pg_temp.conflict('allowance cannot shrink below elapsed coordinate',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-allowance-short'),pg_temp.game_command('soccer.added_time.set','format','{"added_time_seconds":0,"reason":"Synthetic forbidden shrink"}')));
select pg_temp.sc_op('soccer.segment.end','format');
select pg_temp.sc_op('soccer.segment.start','format');
select pg_temp.check('display and actual playing coordinates differ after added time','CLOCK',pg_temp.sc_detail('format')->>'clock_ms'='0' and pg_temp.sc_detail('format')->>'display_clock_ms'='120000' and pg_temp.sc_detail('format')->>'playing_ms'='150000');
do $$declare n int;begin
 for n in 3..4 loop
  perform pg_temp.sc_end('format',120000);perform pg_temp.sc_op('soccer.segment.start','format');
  perform pg_temp.check('quarter advances sequentially '||n,'SEGMENT',pg_temp.sc_detail('format')->>'segment_number'=n::text and pg_temp.sc_detail('format')->>'clock_ms'='0');
 end loop;
end$$;
select pg_temp.sc_end('format',120000);select pg_temp.sc_op('soccer.segment.start','format');
select pg_temp.check('optional extra time starts explicit configured segment','SEGMENT',pg_temp.sc_detail('format')->>'segment_number'='5' and pg_temp.sc_detail('format')->>'extra_time_number'='1');
select pg_temp.sc_end('format');
select pg_temp.state_denied('partly started extra time cannot finalize',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-half-extra-final'),pg_temp.game_command('game.finalize','format')));
select pg_temp.sc_op('soccer.segment.start','format');select pg_temp.sc_end('format');select pg_temp.game_op('game.finalize','format');
select pg_temp.check('draw after complete optional extra time is allowed','FORMAT',pg_temp.sc_detail('format')->>'segment_number'='6');
select pg_temp.sc_create('untracked','internal',true,2,false,1);
select pg_temp.sc_event('untracked','goal','primary',1);
select pg_temp.sc_event('untracked','shot_saved','opponent',1,'untracked-save',null,0);
select pg_temp.sc_finish('untracked');select pg_temp.game_op('game.finalize','untracked');
reset role;
select pg_temp.check('untracked player minutes remain NULL','HONESTY',(select bool_and(minutes is null)from boss_private.soccer_totals(pg_temp.sc_game('untracked'))where roster_id is not null));
select pg_temp.check('untracked keeper GA and individual clean sheet remain NULL','HONESTY',(select bool_and(goals_allowed is null and clean_sheet is null)from boss_private.soccer_totals(pg_temp.sc_game('untracked'))where roster_id is not null));
select pg_temp.check('team clean sheet still follows final score','HONESTY',(select clean_sheet from boss_private.soccer_totals(pg_temp.sc_game('untracked'))where side='primary'and roster_id is null)and not(select clean_sheet from boss_private.soccer_totals(pg_temp.sc_game('untracked'))where side='opponent'and roster_id is null));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.sc_create('no-reentry','internal',true,2,true,7,0,false,1);
select pg_temp.sc_clock('no-reentry',30000);
select pg_temp.sc_op('soccer.substitute','no-reentry',jsonb_build_object('side','primary','out_roster_id',pg_temp.sc_roster('no-reentry','primary',7),'in_roster_id',pg_temp.sc_roster('no-reentry','primary',8)));
select pg_temp.state_denied('no re-entry returns fail closed',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-reentry'),pg_temp.game_command('soccer.substitute','no-reentry',jsonb_build_object('side','primary','out_roster_id',pg_temp.sc_roster('no-reentry','primary',8),'in_roster_id',pg_temp.sc_roster('no-reentry','primary',7)))));
select pg_temp.state_denied('configured substitution maximum is enforced',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-max-sub'),pg_temp.game_command('soccer.substitute','no-reentry',jsonb_build_object('side','primary','out_roster_id',pg_temp.sc_roster('no-reentry','primary',6),'in_roster_id',pg_temp.sc_roster('no-reentry','primary',9)))));
select pg_temp.sc_create('reentry','internal',true,2,true,9,0,true,null);
select pg_temp.sc_clock('reentry',10000);select pg_temp.sc_op('soccer.substitute','reentry',jsonb_build_object('side','primary','out_roster_id',pg_temp.sc_roster('reentry','primary',9),'in_roster_id',pg_temp.sc_roster('reentry','primary',10)));
select pg_temp.sc_clock('reentry',20000);select pg_temp.sc_op('soccer.substitute','reentry',jsonb_build_object('side','primary','out_roster_id',pg_temp.sc_roster('reentry','primary',10),'in_roster_id',pg_temp.sc_roster('reentry','primary',9)));
select pg_temp.sc_event('reentry','red_card','primary',12,'bench-red');
select pg_temp.check('bench dismissal does not reduce active field size','CARDS',(select jsonb_array_length(l->'roster_ids')=9 from jsonb_array_elements(pg_temp.sc_detail('reentry')->'lineups')l where l->>'side'='primary'));
select pg_temp.state_denied('dismissed bench athlete cannot enter lineup',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-dismissed-bench'),pg_temp.game_command('soccer.substitute','reentry',jsonb_build_object('side','primary','out_roster_id',pg_temp.sc_roster('reentry','primary',9),'in_roster_id',pg_temp.sc_roster('reentry','primary',12)))));
select pg_temp.sc_finish('reentry');select pg_temp.game_op('game.finalize','reentry');
reset role;
select pg_temp.check('re-entry interval minutes sum exact independent bounds','MINUTES',(select minutes=110000/60000.0 from boss_private.soccer_totals(pg_temp.sc_game('reentry'))where roster_id=pg_temp.sc_roster('reentry','primary',9))and(select minutes=10000/60000.0 from boss_private.soccer_totals(pg_temp.sc_game('reentry'))where roster_id=pg_temp.sc_roster('reentry','primary',10)));
select pg_temp.check('whole-match reliable keeper has individual clean sheet','MINUTES',(select clean_sheet and goals_allowed=0 and minutes=2 from boss_private.soccer_totals(pg_temp.sc_game('reentry'))where roster_id=pg_temp.sc_roster('reentry','primary',1)));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.sc_create('backward','internal');select pg_temp.sc_clock('backward',30000);select pg_temp.sc_clock('backward',20000);
select pg_temp.sc_finish('backward');select pg_temp.game_op('game.finalize','backward');
reset role;
select pg_temp.check('backward correction marks participation basis incomplete','HONESTY',(select bool_and(minutes is null and goals_allowed is null and clean_sheet is null)from boss_private.soccer_totals(pg_temp.sc_game('backward'))where roster_id is not null));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.sc_link('optional-keeper');
select pg_temp.sc_op('soccer.configure','optional-keeper','{"regulation_segments":2,"segment_seconds":60,"extra_time_segments":0,"extra_time_seconds":60,"lineup_size":3,"enforce_lineup":true,"allow_reentry":true,"max_substitutions":null}');
select pg_temp.sc_op('soccer.lineup.set','optional-keeper',pg_temp.sc_lineup('optional-keeper','primary',3,0));
select pg_temp.sc_op('soccer.lineup.set','optional-keeper',pg_temp.sc_lineup('optional-keeper','opponent',3,0));
select pg_temp.game_op('game.start','optional-keeper');select pg_temp.sc_op('soccer.segment.start','optional-keeper');
select pg_temp.check('omitted keeper reference preserves complete athlete lineup','KEEPER',(select jsonb_array_length(l->'roster_ids')=3 and l->'goalkeeper_roster_id'='null'::jsonb from jsonb_array_elements(pg_temp.sc_detail('optional-keeper')->'lineups')l where l->>'side'='primary'));
select pg_temp.sc_finish('optional-keeper');select pg_temp.game_op('game.finalize','optional-keeper');
reset role;
select pg_temp.check('optional keeper inserts explicit false designation','KEEPER',(select count(*)=6 and bool_and(not goalkeeper and goalkeeper is not null)from public.game_soccer_lineups where game_id=pg_temp.sc_game('optional-keeper')));
select pg_temp.check('known athlete minutes do not fabricate unknown keeper GA','KEEPER',(select minutes=2 and goals_allowed is null and clean_sheet is null from boss_private.soccer_totals(pg_temp.sc_game('optional-keeper'))where roster_id=pg_temp.sc_roster('optional-keeper','primary',1)));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.sc_create('keeper-history');
select pg_temp.sc_clock('keeper-history',10000);select pg_temp.sc_event('keeper-history','shot_saved','opponent',2,'historical-save',null,1);
select pg_temp.sc_clock('keeper-history',20000);select pg_temp.sc_op('soccer.keeper.set','keeper-history',jsonb_build_object('side','primary','goalkeeper_roster_id',pg_temp.sc_roster('keeper-history','primary',2)));
select pg_temp.state_denied('later keeper cannot replace original historical save attribution',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('later-keeper-forgery'),pg_temp.game_command('soccer.event.correct','keeper-history',jsonb_build_object('event_id',pg_temp.sc_event_id('keeper-history','historical-save'),'event_type','penalty_saved','side','opponent','roster_id',pg_temp.sc_roster('keeper-history','opponent',2),'goalkeeper_roster_id',pg_temp.sc_roster('keeper-history','primary',2),'reason','Synthetic wrong historical keeper'))));
select pg_temp.sc_op('soccer.event.correct','keeper-history',jsonb_build_object('event_id',pg_temp.sc_event_id('keeper-history','historical-save'),'event_type','penalty_saved','side','opponent','roster_id',pg_temp.sc_roster('keeper-history','opponent',2),'goalkeeper_roster_id',pg_temp.sc_roster('keeper-history','primary',1),'reason','Synthetic valid historical outcome correction'));
select pg_temp.sc_event('keeper-history','goal','primary',0,'team-goal');
select pg_temp.sc_event('keeper-history','assist','primary',3,'known-assist-to-team-goal',pg_temp.sc_event_id('keeper-history','team-goal'));
reset role;
select pg_temp.check('historical save remains with original goalkeeper','KEEPER',(select saves=1 from boss_private.soccer_totals(pg_temp.sc_game('keeper-history'))where roster_id=pg_temp.sc_roster('keeper-history','primary',1))and(select saves=0 from boss_private.soccer_totals(pg_temp.sc_game('keeper-history'))where roster_id=pg_temp.sc_roster('keeper-history','primary',2)));
select pg_temp.check('known assister may link an accepted unattributed team goal','ASSIST',(select goals=1 and assists=1 from boss_private.soccer_totals(pg_temp.sc_game('keeper-history'))where side='primary'and roster_id is null)and(select assists=1 from boss_private.soccer_totals(pg_temp.sc_game('keeper-history'))where roster_id=pg_temp.sc_roster('keeper-history','primary',3)));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.sc_create('team-cards');select pg_temp.sc_event('team-cards','yellow_card','primary',0);select pg_temp.sc_event('team-cards','red_card','primary',0);
select pg_temp.check('unattributed team red does not invent a dismissed athlete','CARDS',(select jsonb_array_length(l->'roster_ids')=11 and jsonb_array_length(l->'dismissed_roster_ids')=0 from jsonb_array_elements(pg_temp.sc_detail('team-cards')->'lineups')l where l->>'side'='primary'));
select pg_temp.sc_finish('team-cards');select pg_temp.game_op('game.finalize','team-cards');
reset role;
select pg_temp.check('unattributed team cards count without fabricated player stats','CARDS',(select yellow_cards=1 and red_cards=1 from boss_private.soccer_totals(pg_temp.sc_game('team-cards'))where side='primary'and roster_id is null)and(select bool_and(yellow_cards=0 and red_cards=0 and minutes is null)from boss_private.soccer_totals(pg_temp.sc_game('team-cards'))where roster_id is not null));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.sc_create('non-tied-extra','internal',true,2,false,1,2);
select pg_temp.sc_event('non-tied-extra','goal','primary',0);select pg_temp.sc_finish('non-tied-extra');
select pg_temp.sc_op('soccer.segment.start','non-tied-extra');select pg_temp.sc_end('non-tied-extra');
select pg_temp.state_denied('non-tied match still must finish both started extra segments',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sc-nontied-half-extra'),pg_temp.game_command('game.finalize','non-tied-extra')));
select pg_temp.sc_op('soccer.segment.start','non-tied-extra');select pg_temp.sc_end('non-tied-extra');select pg_temp.game_op('game.finalize','non-tied-extra');
reset role;
select pg_temp.check('optional extra-time format imposes no tied-entry competition rule','FORMAT',(select status='final'and primary_score=1 and opponent_score=0 from public.games where id=pg_temp.sc_game('non-tied-extra'))and(select segment_number=4 from public.game_soccer_states where game_id=pg_temp.sc_game('non-tied-extra')));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.sc_link('zero-time-keeper');
select pg_temp.sc_op('soccer.configure','zero-time-keeper','{"regulation_segments":2,"segment_seconds":60,"extra_time_segments":0,"extra_time_seconds":60,"lineup_size":3,"enforce_lineup":true,"allow_reentry":true,"max_substitutions":null}');
select pg_temp.sc_op('soccer.lineup.set','zero-time-keeper',pg_temp.sc_lineup('zero-time-keeper','primary',3,0));
select pg_temp.sc_op('soccer.lineup.set','zero-time-keeper',pg_temp.sc_lineup('zero-time-keeper','opponent',3,1));
select pg_temp.game_op('game.start','zero-time-keeper');select pg_temp.sc_op('soccer.segment.start','zero-time-keeper');
select pg_temp.sc_event('zero-time-keeper','goal','opponent',2);select pg_temp.sc_event('zero-time-keeper','own_goal','primary',2);
select pg_temp.sc_op('soccer.keeper.set','zero-time-keeper',jsonb_build_object('side','primary','goalkeeper_roster_id',pg_temp.sc_roster('zero-time-keeper','primary',1)));
select pg_temp.sc_finish('zero-time-keeper');select pg_temp.game_op('game.finalize','zero-time-keeper');
reset role;
select pg_temp.check('zero-time undetermined keeper is not assigned earlier conceded goals','KEEPER',(select minutes=2 and goals_allowed is null and clean_sheet is null from boss_private.soccer_totals(pg_temp.sc_game('zero-time-keeper'))where roster_id=pg_temp.sc_roster('zero-time-keeper','primary',1)));
select pg_temp.check('unknown zero-duration keeper interval preserves canonical score','KEEPER',(select primary_score=0 and opponent_score=2 from public.games where id=pg_temp.sc_game('zero-time-keeper'))and(select goals_allowed=2 and not clean_sheet from boss_private.soccer_totals(pg_temp.sc_game('zero-time-keeper'))where side='primary'and roster_id is null));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.sc_create('instant-known-keeper');
select pg_temp.sc_event('instant-known-keeper','goal','opponent',2,'goal-before-instant-handoff');
select pg_temp.sc_op('soccer.keeper.set','instant-known-keeper',jsonb_build_object('side','primary','goalkeeper_roster_id',pg_temp.sc_roster('instant-known-keeper','primary',2)));
select pg_temp.sc_finish('instant-known-keeper');select pg_temp.game_op('game.finalize','instant-known-keeper');
reset role;
select pg_temp.check('zero-duration original keeper retains conceded goal and outfield minutes','KEEPER',(select minutes=2 and goals_allowed=1 and clean_sheet is null from boss_private.soccer_totals(pg_temp.sc_game('instant-known-keeper'))where roster_id=pg_temp.sc_roster('instant-known-keeper','primary',1)));
select pg_temp.check('duration-full later keeper never receives a false individual clean sheet','KEEPER',(select minutes=2 and goals_allowed=0 and clean_sheet is null from boss_private.soccer_totals(pg_temp.sc_game('instant-known-keeper'))where roster_id=pg_temp.sc_roster('instant-known-keeper','primary',2)));
select pg_temp.check('instant keeper handoff preserves final team clean-sheet oracle','KEEPER',(select goals_allowed=1 and not clean_sheet from boss_private.soccer_totals(pg_temp.sc_game('instant-known-keeper'))where side='primary'and roster_id is null)and(select goals_allowed=0 and clean_sheet from boss_private.soccer_totals(pg_temp.sc_game('instant-known-keeper'))where side='opponent'and roster_id is null));
select pg_temp.check('shootout attempts are not introduced into regulation event catalog','SCOPE',not exists(select 1 from information_schema.tables where table_schema='public'and table_name like 'game_soccer_shootout%'));
select count(*)as passed_assertions,category from pg_temp.phase5a_assertions group by category order by category;
rollback;
