begin;
set local statement_timeout='8s';
\ir phase6c/fixture.sql
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('guardian reads canonical child profile','AUTHORIZATION',(public.boss_athlete_profile_read(pg_temp.pc_id('profile'),null)->'profile'->'profile'->>'person_id')::uuid=pg_temp.f('child1'));
select pg_temp.check('guardian sees immutable origin history','IDENTITY',jsonb_array_length(public.boss_athlete_profile_read(pg_temp.pc_id('profile'),null)->'profile'->'origins')>=1);
select pg_temp.check('profile completeness remains informational','PRESENTATION',(public.boss_athlete_profile_read(pg_temp.pc_id('profile'),null)->'profile'->'profile'->'completeness'->>'possible')::int=6);
select pg_temp.pc('consent.grant',jsonb_build_object('showcase_id',pg_temp.pc_id('showcase'),'showcase_revision_id',pg_temp.pc_id('showcase-revision'),'approved_categories',jsonb_build_array('overview','sports','statistics','measurables','achievements','history','media'),'expires_at',clock_timestamp()+interval'1 hour'),'consent');
select pg_temp.pc('showcase.publish',jsonb_build_object('showcase_id',pg_temp.pc_id('showcase'),'expected_version',3));
select pg_temp.pc('share.create',jsonb_build_object('showcase_id',pg_temp.pc_id('showcase'),'token_digest','0f007385b6f9d4b7eeb2748605afe1a984a0a3bfa3f014d09e2a784ce9e5cd1a','token_prefix','AAAAAAAA','expires_at',clock_timestamp()+interval'1 hour'),'share');
reset role;
select pg_temp.check('valid share returns bounded showcase','SHARE',public.boss_recruiting_showcase_read('0f007385b6f9d4b7eeb2748605afe1a984a0a3bfa3f014d09e2a784ce9e5cd1a')->>'available'='true');
select pg_temp.check('share exposes no contact metadata','PRIVACY',not(public.boss_recruiting_showcase_read('0f007385b6f9d4b7eeb2748605afe1a984a0a3bfa3f014d09e2a784ce9e5cd1a')::text~*'(email|phone|guardian|household|date_of_birth|address)'));
select pg_temp.check('malformed share denied','SHARE',public.boss_recruiting_showcase_read('bad')->>'available'='false');
select pg_temp.check('guessed share denied','SHARE',public.boss_recruiting_showcase_read(repeat('b',64))->>'available'='false');
set local role authenticated;select pg_temp.actor('household-only');
select pg_temp.denied('household membership grants no profile access',format('select public.boss_athlete_profile_read(%L,null)',pg_temp.pc_id('profile')),'PT403');
select pg_temp.actor('child1');
select pg_temp.check('athlete sees own canonical profile','AUTHORIZATION',public.boss_athlete_profile_read(pg_temp.pc_id('profile'),null)->'profile'->'authority'->>'relationship'='self');
select pg_temp.denied('authenticated minor self cannot infer profile publication authority',format('select public.boss_athlete_profile_mutate(%L::jsonb)',jsonb_build_object('action','profile.revise','request_id',gen_random_uuid(),'input',jsonb_build_object('profile_id',pg_temp.pc_id('profile'),'expected_version',1,'safe_fields',jsonb_build_object('display_name','Forbidden self publish')))),'PT403');
select pg_temp.actor('parent');select pg_temp.pc('share.revoke',jsonb_build_object('share_link_id',pg_temp.pc_id('share')));
reset role;
select pg_temp.check('revoked share denied immediately','SHARE',public.boss_recruiting_showcase_read('0f007385b6f9d4b7eeb2748605afe1a984a0a3bfa3f014d09e2a784ce9e5cd1a')->>'available'='false');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.conflict('stale profile revision rejected',format('select public.boss_athlete_profile_mutate(%L::jsonb)',jsonb_build_object('action','profile.revise','request_id',gen_random_uuid(),'input',jsonb_build_object('profile_id',pg_temp.pc_id('profile'),'expected_version',99,'safe_fields',jsonb_build_object('display_name','Stale')))));
select pg_temp.denied('forged profile rejected',format('select public.boss_athlete_profile_read(%L,null)',gen_random_uuid()),'PT403');
reset role;
select pg_temp.check('one profile preserves participant identity','IDENTITY',(select count(*)=1 from public.athlete_profiles where participant_id=pg_temp.f('participant-child1')and person_id=pg_temp.f('child1')));
select pg_temp.check('profile revisions are immutable history','HISTORY',(select count(*)=1 from public.athlete_profile_revisions where profile_id=pg_temp.pc_id('profile')));
select pg_temp.check('raw share token never stored','SECURITY',not exists(select 1 from public.recruiting_share_links where token_digest=repeat('A',43)or token_prefix=repeat('A',43)));
select count(*)passed_assertions from pg_temp.phase5a_assertions;
rollback;
