begin;
\ir phase5f/fixture.sql
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.dd_create('oracle');
select pg_temp.dd_pa('oracle','pa1');
select pg_temp.dd_play('oracle','single',jsonb_build_array(pg_temp.dd_move(0,1)));
select pg_temp.dd_pa('oracle','pa2');
select pg_temp.dd_play('oracle','double',jsonb_build_array(pg_temp.dd_move(1,3),pg_temp.dd_move(0,2)));
select pg_temp.dd_pa('oracle','pa3');
select pg_temp.dd_play('oracle','home_run',jsonb_build_array(pg_temp.dd_move(3,4),pg_temp.dd_move(2,4),pg_temp.dd_move(0,4)));
select pg_temp.check('literal batting 3AB 3H 3R HR1 2B1 RBI3','ORACLE',pg_temp.dd_stats('oracle','primary')@>'{"pa":3,"ab":3,"hits":3,"runs":3,"home_runs":1,"doubles":1,"rbi":3}');
select pg_temp.check('pitcher three batters 3H 3R HR1 no outs','ORACLE',pg_temp.dd_stats('oracle','opponent',4)@>'{"batters_faced":3,"hits_allowed":3,"runs_allowed":3,"home_runs_allowed":1,"outs_pitched":0}');
select pg_temp.check('untracked pitches not measured through API','COVERAGE',(select t->'stats'->'pitches'@>'{"recorded_value":null,"coverage":"not_tracked"}'from jsonb_array_elements(public.boss_games_read(pg_temp.query('oracle'))->'games')g cross join lateral jsonb_array_elements(g->'diamond'->'teams')t where t->>'side'='opponent'));
select pg_temp.dd_pa('oracle','pa4');select pg_temp.dd_play('oracle','strikeout',jsonb_build_array(pg_temp.dd_move(0,null,'advance_on_play',false,true)));
select pg_temp.dd_pa('oracle','pa5');select pg_temp.dd_play('oracle','other_out',jsonb_build_array(pg_temp.dd_move(0,null,'advance_on_play',false,true)));
select pg_temp.dd_pa('oracle','pa6');select pg_temp.dd_play('oracle','other_out',jsonb_build_array(pg_temp.dd_move(0,null,'advance_on_play',false,true)));
select pg_temp.dd_op('diamond.half.start','oracle','{"payload":{"kind":"half_start"}}');
select pg_temp.dd_pa('oracle','pa7');select pg_temp.dd_play('oracle','other_out',jsonb_build_array(pg_temp.dd_move(0,null,'advance_on_play',false,true)));
select pg_temp.dd_pa('oracle','pa8');select pg_temp.dd_play('oracle','other_out',jsonb_build_array(pg_temp.dd_move(0,null,'advance_on_play',false,true)));
select pg_temp.dd_pa('oracle','pa9');select pg_temp.dd_play('oracle','strikeout',jsonb_build_array(pg_temp.dd_move(0,null,'advance_on_play',false,true)));
select pg_temp.game_op('game.finalize','oracle');
reset role;
select pg_temp.check('canonical score3-0','FINAL',exists(select 1 from public.games where id=pg_temp.ff_game('oracle')and status='final'and primary_score=3 and opponent_score=0));
select pg_temp.check('nine persistent PA starts','PA',(select count(*)=9 from public.game_diamond_plate_appearances where game_id=pg_temp.ff_game('oracle')));
select pg_temp.check('one Diamond seal and two coverage seals','SEAL',(select count(*)=1 from public.game_diamond_finalizations where game_id=pg_temp.ff_game('oracle'))and(select count(*)=2 from public.game_finalization_tracking_seals where game_id=pg_temp.ff_game('oracle')));
select pg_temp.check('replay exact','REPLAY',pg_temp.dd_state('oracle')=boss_private.diamond_rebuild(pg_temp.ff_game('oracle')));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('guardian existing history returns Diamond','HISTORY',jsonb_array_length(public.boss_athlete_history_read(jsonb_build_object('child_person_id',pg_temp.f('child1'),'sport_key','baseball'))->'records')=1);
select pg_temp.actor('household-only');select pg_temp.denied('household does not authorize history',format('select public.boss_athlete_history_read(%L::jsonb)',jsonb_build_object('child_person_id',pg_temp.f('child1'),'sport_key','baseball')));
-- The same Diamond player seal remains attached after a real membership transfer.
reset role;
create temp table diamond_before_transfer as select * from public.game_diamond_final_stats where game_id=pg_temp.ff_game('oracle');
update public.team_memberships set status='inactive',ends_at=clock_timestamp() where person_id=pg_temp.f('child1');
insert into public.team_memberships(organization_id,team_id,person_id,participant_id,membership_type,starts_at)
values(pg_temp.f('other-org'),pg_temp.f('other-team'),pg_temp.f('child1'),pg_temp.f('participant-child1'),'athlete',clock_timestamp());
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('Diamond guardian seal survives same-identity team transfer','TRANSFER',jsonb_array_length(public.boss_athlete_history_read(jsonb_build_object('child_person_id',pg_temp.f('child1'),'sport_key','baseball'))->'records')=1);
select pg_temp.check('Diamond transfer retains original team and participant provenance','PROVENANCE',(select bool_and(r->>'team_id'=pg_temp.f('falcons')::text and r->>'participant_id'=pg_temp.f('participant-child1')::text and r->>'engine_version'='diamond-v1')from jsonb_array_elements(public.boss_athlete_history_read(jsonb_build_object('child_person_id',pg_temp.f('child1'),'sport_key','baseball'))->'records')r));
select pg_temp.actor('child1');select pg_temp.check('Diamond athlete self seal survives transfer','TRANSFER',jsonb_array_length(public.boss_athlete_history_read('{"sport_key":"baseball"}')->'records')=1);
select pg_temp.actor('other-admin');select pg_temp.denied('Diamond new organization staff inherit no private prior-team history',format('select public.boss_athlete_history_read(%L::jsonb)',jsonb_build_object('child_person_id',pg_temp.f('child1'),'sport_key','baseball')));
select pg_temp.denied('Diamond new organization staff inherit no correction or reopen authority','select pg_temp.game_op(''game.reopen'',''oracle'',''{"reason":"Synthetic new-team authority denial"}'')');
reset role;select pg_temp.check('Diamond immutable player seal unchanged by transfer','IMMUTABLE',not exists(select 1 from diamond_before_transfer p left join public.game_diamond_final_stats n on n.id=p.id where to_jsonb(p)is distinct from to_jsonb(n)));
set local role authenticated;
select pg_temp.actor('admin');select pg_temp.dd_create('softball','softball');select pg_temp.dd_pa('softball','sbpa1');select pg_temp.dd_play('softball','home_run',jsonb_build_array(pg_temp.dd_move(0,4)));
select pg_temp.check('Softball same path score1','SOFTBALL',pg_temp.dd_state('softball')->>'primary_score'='1');
select pg_temp.denied('wrong sport command fails closed',format('select pg_temp.game_op(''diamond.pa.start'',''softball'',%L::jsonb)',jsonb_build_object('sport_key','baseball','payload',jsonb_build_object('kind','pa_start','key',gen_random_uuid(),'batter',pg_temp.ff_roster('softball','primary',2)))),'PT403');
reset role;
select count(*)passed_assertions from pg_temp.phase5a_assertions;
rollback;
