begin;
set local statement_timeout='8s';
\ir phase6b/fixture.sql
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.rb('definition.create',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'source_organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'product','leaderboard','source_kind','athlete_season','name','Synthetic home runs','metric_key','home_runs','metric_kind','count','direction','high','qualification','{}'::jsonb),'count-definition');
select pg_temp.rb('ranking.rebuild',pg_temp.rb_q('leaderboard','count-definition'),'count-scope');
select pg_temp.check('counting leader exact one home run','LEADERBOARD',public.boss_ranking_read(pg_temp.rb_q('leaderboard','count-definition'))->'rows'->0 @>'{"rank":1,"value":1,"qualification_state":"qualified"}');
select pg_temp.check('known child source identity retained','PROVENANCE',public.boss_ranking_read(pg_temp.rb_q('leaderboard','count-definition'))->'rows'->0->>'person_id'=pg_temp.f('child1')::text);
select pg_temp.rb('definition.create',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'source_organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'product','leaderboard','source_kind','athlete_season','name','Synthetic qualified AVG','metric_key','avg','metric_kind','rate','direction','high','qualification','{"thresholds":[{"type":"min_pa","value":5}]}'::jsonb),'rate-definition');
select pg_temp.rb('ranking.rebuild',pg_temp.rb_q('leaderboard','rate-definition'));
select pg_temp.check('explicit minimum prevents qualified leader','QUALIFICATION',not exists(select 1 from jsonb_array_elements(public.boss_ranking_read(pg_temp.rb_q('leaderboard','rate-definition'))->'rows')r where r->>'qualification_state'='qualified'));
select pg_temp.check('below-minimum state visible','QUALIFICATION',exists(select 1 from jsonb_array_elements(public.boss_ranking_read(pg_temp.rb_q('leaderboard','rate-definition'))->'rows')r where r->>'qualification_state'='below_minimum'and r->>'rank'is null));
select pg_temp.rb('definition.create',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'source_organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'product','records','source_kind','athlete_season','name','Synthetic season home-run record','metric_key','home_runs','metric_kind','count','direction','high','qualification','{}'::jsonb),'record-definition');
select pg_temp.rb('ranking.rebuild',pg_temp.rb_q('records','record-definition'),'record-scope');
select pg_temp.check('record exact canonical value','RECORD',public.boss_ranking_read(pg_temp.rb_q('records','record-definition'))->'rows'->0 @>'{"value":1,"current_holder":true,"rank":1}');
select pg_temp.check('immutable recognition returned','RECORD',public.boss_ranking_read(pg_temp.rb_q('records','record-definition','{"history":true}'))->'rows'->0->>'event_type'='recognized');
reset role;
create temp table rb_record_before as select *from public.record_events where definition_id=pg_temp.rb_id('record-definition');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.rb('ranking.rebuild',pg_temp.rb_q('records','record-definition'));
reset role;
select pg_temp.check('repeat record rebuild no duplicate recognition','IDEMPOTENCY',(select count(*)=1 from public.record_events where definition_id=pg_temp.rb_id('record-definition')));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.rb('ranking.rebuild',pg_temp.rb_q('leaderboard','count-definition'));
select pg_temp.actor('coach');
select pg_temp.check('exact-team coach private leaderboard allowed','PRIVACY',public.boss_ranking_read(pg_temp.rb_q('leaderboard','count-definition'))->>'freshness'='current');
select pg_temp.denied('scoring is not rank management',format('select public.boss_ranking_mutate(%L::jsonb)',jsonb_build_object('action','ranking.rebuild','request_id',gen_random_uuid(),'input',pg_temp.rb_q('leaderboard','count-definition'))),'PT403');
select pg_temp.actor('parent');
select pg_temp.denied('guardian relationship is not peer ranking audience',format('select public.boss_ranking_read(%L::jsonb)',pg_temp.rb_q('leaderboard','count-definition')),'PT403');
select pg_temp.denied('guardian cannot get comparative record rank',format('select public.boss_ranking_read(%L::jsonb)',pg_temp.rb_q('records','record-definition')),'PT403');
select pg_temp.actor('child1');
select pg_temp.denied('self statistics are not private peer ranking',format('select public.boss_ranking_read(%L::jsonb)',pg_temp.rb_q('leaderboard','count-definition')),'PT403');
select pg_temp.actor('other-admin');
select pg_temp.denied('unrelated organization athlete comparison denied',format('select public.boss_ranking_read(%L::jsonb)',pg_temp.rb_q('leaderboard','count-definition')),'PT403');
select pg_temp.actor('admin');
select pg_temp.game_op('game.reopen','ranking-game','{"reason":"Synthetic record source correction"}');
select public.boss_stat_competition_classify(pg_temp.ff_game('ranking-game'),'excluded','Synthetic corrected source eligibility',gen_random_uuid());
select pg_temp.game_op('game.finalize','ranking-game');
select pg_temp.check('dirty known record returns no current rows','FRESHNESS',public.boss_ranking_read(pg_temp.rb_q('records','record-definition'))->>'freshness'<>'current'and jsonb_array_length(public.boss_ranking_read(pg_temp.rb_q('records','record-definition'))->'rows')=0);
select pg_temp.rb('ranking.rebuild',pg_temp.rb_q('records','record-definition'));
reset role;
select pg_temp.check('correction invalidates old recognition','CORRECTION',(select count(*)=1 from public.record_events where definition_id=pg_temp.rb_id('record-definition')and event_type='invalidated_by_source_correction'));
select pg_temp.check('no orphan current holder after source removal','CORRECTION',not exists(select 1 from public.record_current_holders where definition_id=pg_temp.rb_id('record-definition')));
select pg_temp.check('historical recognition byte-identical','HISTORY',(select to_jsonb(old)=to_jsonb(current)from rb_record_before old join public.record_events current on current.id=old.id));
select pg_temp.denied('recognition update impossible',format('update public.record_events set value=999 where definition_id=%L',pg_temp.rb_id('record-definition')),'23514');
select pg_temp.check('separate canonical sport ERA conventions','ERA',(select sport_key='baseball'from public.competition_editions where id=pg_temp.rb_id('edition')));
select count(*)passed_assertions from pg_temp.phase5a_assertions;
rollback;
