-- Synthetic rollback-only Phase 4B volunteer authorization, isolation and integrity.
BEGIN;
CREATE TEMP TABLE phase4b_vol_assertions(label text primary key,category text not null) ON COMMIT DROP;
CREATE TEMP TABLE phase4b_vol_results(label text primary key,result jsonb not null) ON COMMIT DROP;
GRANT SELECT,INSERT,UPDATE ON pg_temp.phase4b_vol_assertions,pg_temp.phase4b_vol_results TO authenticated,anon;
CREATE FUNCTION pg_temp.f(label text) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$SELECT md5('boss-phase4b-volunteers:'||label)::uuid$$;
CREATE FUNCTION pg_temp.check(label text,category text,ok boolean) RETURNS void LANGUAGE plpgsql AS $$BEGIN IF ok IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL [%] %',category,label;END IF;INSERT INTO pg_temp.phase4b_vol_assertions VALUES(label,category);END$$;
CREATE FUNCTION pg_temp.act(label text) RETURNS void LANGUAGE plpgsql AS $$BEGIN PERFORM set_config('request.jwt.claim.sub','',true);PERFORM set_config('request.jwt.claim','',true);PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('auth-'||label),'role','authenticated','is_anonymous',false,'session_id',pg_temp.f('session-'||label),'user_metadata',jsonb_build_object('role','platform_administrator'))::text,true);END$$;
CREATE FUNCTION pg_temp.cmd(op text,i jsonb) RETURNS jsonb LANGUAGE sql AS $$SELECT jsonb_build_object('operation',op,'input',i)$$;
CREATE FUNCTION pg_temp.ok(label text,cat text,c jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$DECLARE r jsonb;BEGIN r:=public.boss_volunteers_mutate(pg_temp.f('request-'||label),c);PERFORM pg_temp.check(label,cat,r->>'request_id'=pg_temp.f('request-'||label)::text AND jsonb_typeof(r)='object');INSERT INTO pg_temp.phase4b_vol_results VALUES(label,r);RETURN r;END$$;
CREATE FUNCTION pg_temp.rid(label text) RETURNS uuid LANGUAGE sql AS $$SELECT (result->>'resource_id')::uuid FROM pg_temp.phase4b_vol_results WHERE phase4b_vol_results.label=$1$$;
CREATE FUNCTION pg_temp.deny(label text,cat text,c jsonb,states text[] DEFAULT ARRAY['PT403'],request_label text DEFAULT NULL) RETURNS void LANGUAGE plpgsql AS $$DECLARE denied boolean:=false;BEGIN BEGIN PERFORM public.boss_volunteers_mutate(pg_temp.f('request-'||coalesce(request_label,label)),c);EXCEPTION WHEN OTHERS THEN IF SQLSTATE=ANY(states) THEN denied:=true;ELSE RAISE EXCEPTION 'FAIL % unexpected state %: %',label,SQLSTATE,SQLERRM;END IF;END;PERFORM pg_temp.check(label,cat,denied);END$$;
CREATE FUNCTION pg_temp.read_deny(label text,q jsonb) RETURNS void LANGUAGE plpgsql AS $$DECLARE denied boolean:=false;BEGIN BEGIN PERFORM public.boss_volunteers_read(q);EXCEPTION WHEN SQLSTATE 'PT403' THEN denied:=true;END;PERFORM pg_temp.check(label,'ISOLATION',denied);END$$;
CREATE FUNCTION pg_temp.query(label text DEFAULT NULL) RETURNS jsonb LANGUAGE sql AS $$SELECT jsonb_strip_nulls(jsonb_build_object('organization_id',pg_temp.f('org-a'),'shift_id',CASE WHEN label IS NOT NULL THEN pg_temp.rid(label) END))$$;
CREATE FUNCTION pg_temp.shift(label text,scope text DEFAULT 'team',target text DEFAULT 'team-a',cap integer DEFAULT 2,extra jsonb DEFAULT '{}') RETURNS jsonb LANGUAGE sql AS $$SELECT pg_temp.cmd('shift.upsert',jsonb_build_object('organization_id',pg_temp.f('org-a'),'role_id',pg_temp.rid('role'),'title','Synthetic shift '||label,'scope_type',scope,'scope_id',pg_temp.f(target),'start_at',now()+interval '2 days','end_at',now()+interval '2 days 2 hours','capacity',cap,'status','open','visibility','members')||extra)$$;
CREATE FUNCTION pg_temp.edit(label text,changes jsonb) RETURNS jsonb LANGUAGE sql AS $$SELECT pg_temp.cmd('shift.upsert',(SELECT command->'input' FROM boss_private.volunteer_operation_receipts WHERE actor_person_id=pg_temp.f('admin') AND request_id=pg_temp.f('request-'||label))||jsonb_build_object('shift_id',pg_temp.rid(label),'expected_version',(SELECT version FROM public.volunteer_shifts WHERE id=pg_temp.rid(label)))||changes)$$;
-- Test-only edit helper reads fixture state as owner, never exposed outside temp schema.
ALTER FUNCTION pg_temp.edit(text,jsonb) SECURITY DEFINER;
DO $$DECLARE f record;BEGIN FOR f IN SELECT p.oid::regprocedure f FROM pg_proc p WHERE p.pronamespace=pg_my_temp_schema() LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',f.f);EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated,anon',f.f);END LOOP;END$$;
DO $$DECLARE t text;f record;BEGIN
 FOREACH t IN ARRAY ARRAY['volunteer_role_definitions','volunteer_shifts','volunteer_assignments','volunteer_assignment_history'] LOOP
 PERFORM pg_temp.check(t||' RLS','SECURITY',(SELECT relrowsecurity FROM pg_class WHERE oid=('public.'||t)::regclass));
 PERFORM pg_temp.check(t||' authenticated rawclosed','SECURITY',NOT has_table_privilege('authenticated','public.'||t,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE'));
 PERFORM pg_temp.check(t||' anon rawclosed','SECURITY',NOT has_table_privilege('anon','public.'||t,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE'));
 PERFORM pg_temp.check(t||' service rawclosed','SECURITY',NOT has_table_privilege('service_role','public.'||t,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE'));END LOOP;
 FOR f IN SELECT p.oid::regprocedure id,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='boss_private' AND p.proname IN('volunteer_permission','volunteer_person_eligible','volunteer_guardian','volunteer_can_view_shift','volunteer_notification_recipient','volunteer_command') LOOP PERFORM pg_temp.check(f.proname||' privateclosed','SECURITY',NOT has_function_privilege('authenticated',f.id,'EXECUTE') AND NOT has_function_privilege('anon',f.id,'EXECUTE'));END LOOP;
 PERFORM pg_temp.check('public invoker wrappers','SECURITY',NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname LIKE 'boss_volunteers_%' AND p.prosecdef));
 PERFORM pg_temp.check('anon RPCclosed','SECURITY',NOT has_function_privilege('anon','public.boss_volunteers_read(jsonb)','EXECUTE') AND NOT has_function_privilege('anon','public.boss_volunteers_mutate(uuid,jsonb)','EXECUTE'));
END$$;
INSERT INTO auth.users(id,email,email_confirmed_at) SELECT pg_temp.f('auth-'||p),p||'@phase4b-volunteers.example.invalid',now()-interval '1 day' FROM unnest(ARRAY['platform','admin','admin-b','coach','assistant','coordinator','unit','parent','parent2','household','expired-guardian','outsider','minor','unknown','expired-role'])p;
INSERT INTO auth.sessions(id,user_id) SELECT pg_temp.f('session-'||p),pg_temp.f('auth-'||p) FROM unnest(ARRAY['platform','admin','admin-b','coach','assistant','coordinator','unit','parent','parent2','household','expired-guardian','outsider','minor','unknown','expired-role'])p;
INSERT INTO public.people(id,display_name,date_of_birth) SELECT pg_temp.f(p),'Synthetic volunteer '||p,CASE WHEN p IN('child','child2','minor') THEN current_date-interval '12 years' WHEN p='unknown' THEN NULL ELSE date '1980-01-01' END FROM unnest(ARRAY['platform','admin','admin-b','coach','assistant','coordinator','unit','parent','parent2','household','expired-guardian','outsider','minor','unknown','expired-role','child','child2'])p;
INSERT INTO public.user_accounts(auth_user_id,person_id,account_status) SELECT pg_temp.f('auth-'||p),pg_temp.f(p),'active' FROM unnest(ARRAY['platform','admin','admin-b','coach','assistant','coordinator','unit','parent','parent2','household','expired-guardian','outsider','minor','unknown','expired-role'])p;
INSERT INTO public.organizations(id,name,slug) VALUES(pg_temp.f('org-a'),'Synthetic volunteer A','phase4b-vol-a'),(pg_temp.f('org-b'),'Synthetic volunteer B','phase4b-vol-b');
INSERT INTO public.organization_units(id,organization_id,name,slug,unit_type,parent_unit_id) VALUES(pg_temp.f('unit-a'),pg_temp.f('org-a'),'Synthetic volunteer unit','unit-a','sport',NULL),(pg_temp.f('unit-sibling'),pg_temp.f('org-a'),'Synthetic sibling','unit-sibling','sport',NULL),(pg_temp.f('unit-descendant'),pg_temp.f('org-a'),'Synthetic descendant','unit-descendant','program',pg_temp.f('unit-a'));
INSERT INTO public.teams(id,organization_id,parent_unit_id,name,slug) VALUES(pg_temp.f('team-a'),pg_temp.f('org-a'),pg_temp.f('unit-a'),'Synthetic Falcons','falcons'),(pg_temp.f('team-b'),pg_temp.f('org-a'),pg_temp.f('unit-sibling'),'Synthetic Tigers','tigers'),(pg_temp.f('team-child'),pg_temp.f('org-a'),pg_temp.f('unit-descendant'),'Synthetic descendant','descendant'),(pg_temp.f('team-other'),pg_temp.f('org-b'),NULL,'Synthetic other','other');
UPDATE public.teams SET status='active' WHERE organization_id IN(pg_temp.f('org-a'),pg_temp.f('org-b'));
INSERT INTO public.organization_modules(organization_id,module_id,status,starts_at,configuration) SELECT pg_temp.f(org),m.id,'active',now()-interval '1 day',CASE WHEN m.key='volunteers' THEN '{"volunteers":true,"self_signup":true,"reminders":true,"head_coach_management":false,"assistant_management":false,"minimum_signup_age":18}'::jsonb ELSE '{}'::jsonb END FROM public.modules m CROSS JOIN unnest(ARRAY['org-a','org-b'])org WHERE m.key IN('calendar','volunteers');
INSERT INTO public.role_assignments(person_id,role_id,scope_type,scope_id,organization_id,starts_at,ends_at) SELECT pg_temp.f(p),r.id,scope,CASE WHEN target IS NOT NULL THEN pg_temp.f(target) END,CASE WHEN org IS NOT NULL THEN pg_temp.f(org) END,now()-interval '2 days',CASE WHEN p='expired-role' THEN now()-interval '1 day' END FROM(VALUES('platform','platform_administrator','platform',NULL,NULL),('admin','organization_administrator','organization','org-a','org-a'),('admin-b','organization_administrator','organization','org-b','org-b'),('coach','head_coach','team','team-a','org-a'),('assistant','assistant_coach','team','team-a','org-a'),('coordinator','volunteer_coordinator','team','team-a','org-a'),('unit','program_administrator','organization_unit','unit-a','org-a'),('expired-role','volunteer_coordinator','team','team-a','org-a'))v(p,role,scope,target,org) JOIN public.roles r ON r.key=v.role;
INSERT INTO public.organization_memberships(organization_id,person_id,starts_at) SELECT pg_temp.f('org-a'),pg_temp.f(p),now()-interval '1 day' FROM unnest(ARRAY['admin','coach','assistant','coordinator','unit','minor','unknown','child','child2','expired-role'])p;
INSERT INTO public.organization_memberships(organization_id,person_id,starts_at) VALUES(pg_temp.f('org-b'),pg_temp.f('outsider'),now()-interval '1 day'),(pg_temp.f('org-b'),pg_temp.f('admin-b'),now()-interval '1 day');
INSERT INTO public.participants(id,person_id,participant_type) VALUES(pg_temp.f('participant'),pg_temp.f('child'),'athlete'),(pg_temp.f('participant2'),pg_temp.f('child2'),'athlete');
INSERT INTO public.team_memberships(organization_id,team_id,person_id,participant_id,membership_type,starts_at) VALUES(pg_temp.f('org-a'),pg_temp.f('team-a'),pg_temp.f('child'),pg_temp.f('participant'),'athlete',now()-interval '1 day'),(pg_temp.f('org-a'),pg_temp.f('team-b'),pg_temp.f('child2'),pg_temp.f('participant2'),'athlete',now()-interval '1 day');
INSERT INTO public.team_memberships(organization_id,team_id,person_id,membership_type,starts_at) SELECT pg_temp.f('org-a'),pg_temp.f('team-a'),pg_temp.f(p),'staff',now()-interval '1 day' FROM unnest(ARRAY['coach','assistant','coordinator','expired-role','minor','unknown'])p;
INSERT INTO public.guardian_relationships(id,guardian_person_id,dependent_person_id,authority_status,verified_at,starts_at,ends_at) VALUES(pg_temp.f('guardian'),pg_temp.f('parent'),pg_temp.f('child'),'active',now()-interval '1 day',now()-interval '1 day',NULL),(pg_temp.f('guardian2'),pg_temp.f('parent2'),pg_temp.f('child'),'active',now()-interval '1 day',now()-interval '1 day',NULL),(pg_temp.f('expired-guardian-row'),pg_temp.f('expired-guardian'),pg_temp.f('child'),'active',now()-interval '2 days',now()-interval '2 days',now()-interval '1 day');
INSERT INTO public.households(id,name) VALUES(pg_temp.f('household'),'Synthetic volunteer household');
INSERT INTO public.household_memberships(household_id,person_id,starts_at) SELECT pg_temp.f('household'),pg_temp.f(p),now()-interval '1 day' FROM unnest(ARRAY['parent','child','household'])p;
-- Canonical Calendar occurrence identity requires whole-second event times.
INSERT INTO public.events(id,organization_id,title,event_type_key,start_at,end_at,timezone,status,visibility,created_by_person_id,updated_by_person_id,recurrence) VALUES(pg_temp.f('event'),pg_temp.f('org-a'),'Synthetic volunteer event','practice',date_trunc('second',now())+interval '2 days',date_trunc('second',now())+interval '2 days 2 hours','UTC','scheduled','member',pg_temp.f('admin'),pg_temp.f('admin'),NULL),(pg_temp.f('recurring-event'),pg_temp.f('org-a'),'Synthetic recurring event','practice',date_trunc('second',now())+interval '3 days',date_trunc('second',now())+interval '3 days 2 hours','UTC','scheduled','member',pg_temp.f('admin'),pg_temp.f('admin'),'{"frequency":"daily","count":3}');
INSERT INTO public.event_targets(event_id,organization_id,target_type,target_id) VALUES(pg_temp.f('event'),pg_temp.f('org-a'),'team',pg_temp.f('team-a')),(pg_temp.f('recurring-event'),pg_temp.f('org-a'),'team',pg_temp.f('team-a'));
SET LOCAL ROLE authenticated;SELECT pg_temp.act('admin');
SELECT pg_temp.ok('role','A',pg_temp.cmd('role.upsert',jsonb_build_object('organization_id',pg_temp.f('org-a'),'name','Synthetic concessions','description','Synthetic configurable duty')));
SELECT pg_temp.ok('event-shift','A',pg_temp.shift('event','team','team-a',2,jsonb_build_object('event_id',pg_temp.f('event'))));
SELECT pg_temp.ok('open-shift','A',pg_temp.shift('open'));
SELECT pg_temp.ok('sibling-shift','A',pg_temp.shift('sibling','team','team-b'));
SELECT pg_temp.ok('unit-shift','A',pg_temp.shift('unit','unit','unit-a'));
SELECT pg_temp.ok('descendant-shift','A',pg_temp.shift('descendant','team','team-child'));
SELECT pg_temp.ok('staff-shift','A',pg_temp.shift('staff','team','team-a',2,'{"visibility":"staff"}'));
SELECT pg_temp.ok('deadline-shift','DEADLINE',pg_temp.shift('deadline','team','team-a',2,jsonb_build_object('signup_deadline',now()-interval '1 hour')));
SELECT pg_temp.check('read operations retain finite staff and own actions','PROJECTION',public.boss_volunteers_read(pg_temp.query())->'operations'@>'["role.upsert","volunteers.configure","shift.upsert","reminders.prepare","assignment.signup","assignment.cancel"]'::jsonb);
SELECT pg_temp.deny('forged team in other organization','ISOLATION',pg_temp.shift('forged','team','team-other'));
SELECT pg_temp.deny('forged event occurrence','OCCURRENCE',pg_temp.shift('forged-key','team','team-a',2,jsonb_build_object('event_id',pg_temp.f('event'),'occurrence_key','2000-01-01T00:00:00')));
SELECT pg_temp.deny('sibling event target mismatches shift','OCCURRENCE',pg_temp.shift('wrong-target','team','team-b',2,jsonb_build_object('event_id',pg_temp.f('event'))));
SELECT pg_temp.deny('occurrence without event','OCCURRENCE',pg_temp.shift('key-only','team','team-a',2,'{"occurrence_key":"2000-01-01T00:00:00"}'),ARRAY['PT422']);
SELECT pg_temp.deny('recurrence requires specific occurrence','OCCURRENCE',pg_temp.shift('series','team','team-a',2,jsonb_build_object('event_id',pg_temp.f('recurring-event'))));
SELECT pg_temp.ok('recurring-shift-1','OCCURRENCE',pg_temp.shift('series-first','team','team-a',2,jsonb_build_object('event_id',pg_temp.f('recurring-event'),'occurrence_key',to_char((date_trunc('second',now())+interval '3 days') at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS'))));
SELECT pg_temp.ok('recurring-shift-2','OCCURRENCE',pg_temp.shift('series-second','team','team-a',2,jsonb_build_object('event_id',pg_temp.f('recurring-event'),'occurrence_key',to_char((date_trunc('second',now())+interval '4 days') at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS'))));
SELECT pg_temp.check('recurring shifts retain separate occurrence identity','OCCURRENCE',public.boss_volunteers_read(pg_temp.query('recurring-shift-1'))->'detail'->>'occurrence_key'<>public.boss_volunteers_read(pg_temp.query('recurring-shift-2'))->'detail'->>'occurrence_key');
SELECT pg_temp.deny('unsafe capacity override field','CAPACITY',pg_temp.shift('override','team','team-a',2,'{"override_capacity":true}'),ARRAY['PT422']);
SELECT pg_temp.deny('unbounded reminder window rejected','REMINDER',pg_temp.cmd('reminders.prepare',jsonb_build_object('organization_id',pg_temp.f('org-a'),'window_start',now(),'window_end',now()+interval '8 days')),ARRAY['PT422']);
SELECT pg_temp.deny('minimum age cannot enable minors','MINOR',pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org-a'),'configuration','{"minimum_signup_age":12}'::jsonb)),ARRAY['PT422']);
SELECT pg_temp.deny('malformed minimum age rejected','MINOR',pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org-a'),'configuration','{"minimum_signup_age":null}'::jsonb)),ARRAY['PT422']);
SELECT pg_temp.act('parent');
SELECT pg_temp.ok('parent-signup','B',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('open-shift'))));
SELECT pg_temp.check('own commitment family projection','M',jsonb_array_length(public.boss_volunteers_read(pg_temp.query()||'{"view":"family"}')->'commitments')=1);
SELECT pg_temp.check('family commitment preserves exact team label','M',public.boss_volunteers_read(pg_temp.query()||'{"view":"family"}')->'commitments'->0->>'scope_label'='Synthetic Falcons');
SELECT pg_temp.check('guardian not given otherperson roster','ISOLATION',NOT public.boss_volunteers_read(pg_temp.query('open-shift'))::text LIKE '%assignments%');
SELECT pg_temp.check('filled and unfilled summary','L',(public.boss_volunteers_read(pg_temp.query('open-shift'))->'detail'->>'filled')::integer=1 AND(public.boss_volunteers_read(pg_temp.query('open-shift'))->'detail'->>'unfilled')::integer=1);
DO $$DECLARE r jsonb;BEGIN r:=public.boss_volunteers_mutate(pg_temp.f('request-parent-signup'),pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('open-shift'))));PERFORM pg_temp.check('exact retry same commitment','D',r->>'resource_id'=pg_temp.rid('parent-signup')::text);END$$;
SELECT pg_temp.ok('parent-fresh-retry','D',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('open-shift'))));
SELECT pg_temp.check('fresh duplicate same resource','D',pg_temp.rid('parent-fresh-retry')=pg_temp.rid('parent-signup'));
SELECT pg_temp.deny('self cannot inject another person','OWNERSHIP',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('open-shift'),'person_id',pg_temp.f('parent2'))),ARRAY['PT422']);
SELECT pg_temp.deny('parent cannot assign another','G',pg_temp.cmd('assignment.assign',jsonb_build_object('shift_id',pg_temp.rid('open-shift'),'person_id',pg_temp.f('parent2'))));
SELECT pg_temp.deny('deadline rejects new selfsignup','DEADLINE',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('deadline-shift'))));
SELECT pg_temp.read_deny('unrelated team shift inaccessible',pg_temp.query('sibling-shift'));
SELECT pg_temp.read_deny('forged cross tenant query',pg_temp.query()||jsonb_build_object('organization_id',pg_temp.f('org-b')));
SELECT pg_temp.read_deny('forged sibling unit filter',pg_temp.query()||jsonb_build_object('unit_id',pg_temp.f('unit-sibling')));
SELECT pg_temp.read_deny('staff visibility denies parent without commitment',pg_temp.query('staff-shift'));
SELECT pg_temp.act('household');SELECT pg_temp.deny('household alone cannot signup','FAMILY',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('open-shift'))));SELECT pg_temp.read_deny('household alone cannot read private needs',pg_temp.query('open-shift'));
SELECT pg_temp.act('expired-guardian');SELECT pg_temp.deny('expired guardian cannot signup','FAMILY',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('open-shift'))));
SELECT pg_temp.act('outsider');SELECT pg_temp.deny('other tenant cannot signup','ISOLATION',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('open-shift'))));
SELECT pg_temp.act('minor');SELECT pg_temp.deny('minor self signup failclosed','MINOR',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('unit-shift'))));
SELECT pg_temp.act('unknown');SELECT pg_temp.deny('unknown age self signup failclosed','MINOR',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('unit-shift'))));
SELECT pg_temp.act('coach');
SELECT pg_temp.check('own team needs view','H',public.boss_volunteers_read(pg_temp.query('open-shift'))->'detail'->>'id'=pg_temp.rid('open-shift')::text);
SELECT pg_temp.check('disabled coach manage absent targets','H',jsonb_array_length(public.boss_volunteers_read(pg_temp.query())->'targets')=0);
SELECT pg_temp.deny('coach manage disabled','H',pg_temp.shift('coach-disabled'));
SELECT pg_temp.read_deny('coach cannot read sibling team',pg_temp.query('sibling-shift'));
SELECT pg_temp.deny('coach cannot create orgwide needs','H',pg_temp.shift('orgwide','organization','org-a'));
SELECT pg_temp.act('admin');SELECT pg_temp.ok('enable-coach','POLICY',pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org-a'),'configuration','{"head_coach_management":true}'::jsonb)));
SELECT pg_temp.act('coach');SELECT pg_temp.ok('coach-shift','H',pg_temp.shift('coach-enabled'));
SELECT pg_temp.check('coach exact team management target','H',jsonb_array_length(public.boss_volunteers_read(pg_temp.query())->'targets')=1 AND(public.boss_volunteers_read(pg_temp.query())->'targets'->0->>'scope_id')::uuid=pg_temp.f('team-a'));
SELECT pg_temp.deny('coach no manual assignment capability','G',pg_temp.cmd('assignment.assign',jsonb_build_object('shift_id',pg_temp.rid('coach-shift'),'person_id',pg_temp.f('parent2'))));
SELECT pg_temp.deny('enabled coach still sibling denied','H',pg_temp.shift('coach-other','team','team-b'));
SELECT pg_temp.act('assistant');SELECT pg_temp.deny('assistant management default disabled','POLICY',pg_temp.shift('assistant'));
SELECT pg_temp.act('coordinator');SELECT pg_temp.ok('coordinator-shift','I',pg_temp.shift('coordinator'));
SELECT pg_temp.deny('coordinator sibling scope denied','I',pg_temp.shift('coordinator-other','team','team-b'));
SELECT pg_temp.deny('coordinator org scope denied','I',pg_temp.shift('coordinator-org','organization','org-a'));
SELECT pg_temp.deny('coordinator rolecatalog is orgonly','I',pg_temp.cmd('role.upsert',jsonb_build_object('organization_id',pg_temp.f('org-a'),'name','Denied orgwide role')));
SELECT pg_temp.act('unit');SELECT pg_temp.ok('unit-own-team','SCOPE',pg_temp.shift('unit-own-team'));
SELECT pg_temp.deny('unit sibling team denied','SCOPE',pg_temp.shift('unit-sibling','team','team-b'));
SELECT pg_temp.deny('unit descendant inheritance denied','SCOPE',pg_temp.shift('unit-descendant','team','team-child'));
SELECT pg_temp.act('expired-role');SELECT pg_temp.deny('expired role cannot manage','SCOPE',pg_temp.shift('expired-role'));
SELECT pg_temp.act('admin-b');SELECT pg_temp.deny('other tenant admin cannot manage','ISOLATION',pg_temp.shift('other-admin'));
SELECT pg_temp.act('admin');
SELECT pg_temp.ok('assign-parent2','G',pg_temp.cmd('assignment.assign',jsonb_build_object('shift_id',pg_temp.rid('open-shift'),'person_id',pg_temp.f('parent2'))));
SELECT pg_temp.deny('assign unrelated outsider denied','G',pg_temp.cmd('assignment.assign',jsonb_build_object('shift_id',pg_temp.rid('open-shift'),'person_id',pg_temp.f('outsider'))));
SELECT pg_temp.deny('assign minor denied','MINOR',pg_temp.cmd('assignment.assign',jsonb_build_object('shift_id',pg_temp.rid('unit-shift'),'person_id',pg_temp.f('minor'))));
SELECT pg_temp.act('coordinator');SELECT pg_temp.deny('full capacity rejects third eligible adult','C',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('open-shift'))),ARRAY['PT409']);SELECT pg_temp.act('admin');
SELECT pg_temp.deny('cannot shrink capacity below commitments','CAPACITY',pg_temp.edit('open-shift','{"capacity":1}'),ARRAY['PT409']);
SELECT pg_temp.deny('cannot move active commitments to sibling team','CAPACITY',pg_temp.edit('open-shift',jsonb_build_object('scope_id',pg_temp.f('team-b'))),ARRAY['PT409']);
SELECT pg_temp.ok('staff-assigned-private','G',pg_temp.cmd('assignment.assign',jsonb_build_object('shift_id',pg_temp.rid('staff-shift'),'person_id',pg_temp.f('parent2'))));
SELECT pg_temp.act('parent2');SELECT pg_temp.check('assigned volunteer own staffvisibility commitment readable','M',public.boss_volunteers_read(pg_temp.query('staff-shift'))->'detail'->>'id'=pg_temp.rid('staff-shift')::text);
SELECT pg_temp.act('admin');SELECT pg_temp.ok('close-staff-shift','POLICY',pg_temp.edit('staff-shift',jsonb_build_object('status','closed','signup_deadline',now()-interval '1 day')));
SELECT pg_temp.act('parent2');SELECT pg_temp.ok('own-cancel-closed-pastdeadline','E',pg_temp.cmd('assignment.cancel',jsonb_build_object('assignment_id',pg_temp.rid('staff-assigned-private'),'expected_version',1)));
SELECT pg_temp.act('parent');SELECT pg_temp.deny('parent cannot cancel another household volunteer','F',pg_temp.cmd('assignment.cancel',jsonb_build_object('assignment_id',pg_temp.rid('assign-parent2'),'expected_version',1)));
SELECT pg_temp.act('admin');SELECT pg_temp.ok('disable-new-signups','POLICY',pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org-a'),'configuration','{"self_signup":false}'::jsonb)));
SELECT pg_temp.act('parent');SELECT pg_temp.ok('own-cancel','E',pg_temp.cmd('assignment.cancel',jsonb_build_object('assignment_id',pg_temp.rid('parent-signup'),'expected_version',1)));
SELECT pg_temp.check('own cancellation frees capacity','L',(public.boss_volunteers_read(pg_temp.query('open-shift'))->'detail'->>'unfilled')::integer=1);
SELECT pg_temp.deny('self signup disabled enforced','POLICY',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('event-shift'))));
SELECT pg_temp.act('admin');SELECT pg_temp.ok('reenable-signup','POLICY',pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org-a'),'configuration','{"self_signup":true}'::jsonb)));
SELECT pg_temp.ok('reassign-staff','REASSIGN',pg_temp.cmd('assignment.reassign',jsonb_build_object('assignment_id',pg_temp.rid('assign-parent2'),'expected_version',1,'person_id',pg_temp.f('parent'))));
SELECT pg_temp.check('reassignment reuses historical exactperson row','REASSIGN',pg_temp.rid('reassign-staff')=pg_temp.rid('parent-signup'));
SELECT pg_temp.ok('change-shift','K',pg_temp.edit('open-shift','{"location":"Synthetic changed location"}'));
SELECT pg_temp.ok('audit-replacement-role','AUDIT',pg_temp.cmd('role.upsert',jsonb_build_object('organization_id',pg_temp.f('org-a'),'name','Synthetic alternate duty')));
SELECT pg_temp.ok('audit-shift','AUDIT',pg_temp.shift('audit'));
SELECT pg_temp.ok('audit-role-capacity-change','AUDIT',pg_temp.edit('audit-shift',jsonb_build_object('capacity',3,'role_id',pg_temp.rid('audit-replacement-role'))));
SELECT pg_temp.ok('audit-title-change','AUDIT',pg_temp.edit('audit-shift',jsonb_build_object('capacity',3,'role_id',pg_temp.rid('audit-replacement-role'),'title','Synthetic reviewed duty')));
SELECT pg_temp.ok('audit-capacity-only-change','AUDIT',pg_temp.edit('audit-shift',jsonb_build_object('capacity',4,'role_id',pg_temp.rid('audit-replacement-role'),'title','Synthetic reviewed duty')));
SELECT pg_temp.deny('stale shift version denied','VERSION',pg_temp.cmd('shift.upsert',(pg_temp.shift('open')->'input')||jsonb_build_object('shift_id',pg_temp.rid('open-shift'),'expected_version',1)),ARRAY['PT409']);
SELECT pg_temp.ok('event-signup','EVENT',pg_temp.cmd('assignment.assign',jsonb_build_object('shift_id',pg_temp.rid('event-shift'),'person_id',pg_temp.f('parent2'))));
RESET ROLE;
UPDATE public.events SET start_at=start_at+interval '1 hour',end_at=end_at+interval '1 hour',version=version+1 WHERE id=pg_temp.f('event');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('parent');
SELECT pg_temp.check('material event context change visible','EVENT',public.boss_volunteers_read(pg_temp.query('event-shift'))->'detail'->'event_context_changed'='true'::jsonb);
SELECT pg_temp.deny('material event change closes stale shift signup','EVENT',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('event-shift'))));
SELECT pg_temp.act('admin');
-- Staff review refreshes material context while preserving the previously validated single-event occurrence anchor.
SELECT pg_temp.ok('review-event-shift','EVENT',pg_temp.edit('event-shift',jsonb_build_object('occurrence_key',(public.boss_volunteers_read(pg_temp.query('event-shift'))->'detail'->>'occurrence_key'))));
SELECT pg_temp.check('event review retains active commitment','EVENT',EXISTS(SELECT 1 FROM jsonb_array_elements(public.boss_volunteers_read(pg_temp.query('event-shift'))->'detail'->'assignments') a WHERE a->>'id'=pg_temp.rid('event-signup')::text AND a->>'status'='active'));
RESET ROLE;
SELECT pg_temp.check('duplicate retry preserves one history','D',(SELECT count(*)=1 FROM public.volunteer_assignment_history WHERE assignment_id=pg_temp.rid('parent-signup') AND action='signup'));
SELECT pg_temp.check('reassignment current filled count one','L',(SELECT count(*)=1 FROM public.volunteer_assignments WHERE shift_id=pg_temp.rid('open-shift') AND status='active'));
SELECT pg_temp.check('reassignment old cancellation retained','REASSIGN',(SELECT status='canceled' AND version=2 FROM public.volunteer_assignments WHERE id=pg_temp.rid('assign-parent2')));
SELECT pg_temp.check('role and shift identity same tenant','A',(SELECT count(*)=1 FROM public.volunteer_role_definitions WHERE id=pg_temp.rid('role') AND organization_id=pg_temp.f('org-a')));
SELECT pg_temp.check('minimal safe audit no instructions/body/DOB','AUDIT',NOT EXISTS(SELECT 1 FROM public.audit_events WHERE organization_id=pg_temp.f('org-a') AND(action LIKE 'volunteers.%') AND(after_data?'instructions' OR after_data?'date_of_birth' OR after_data?'body')));
SELECT pg_temp.check('shift creation audits initial capacity and role','AUDIT',EXISTS(SELECT 1 FROM public.audit_events WHERE request_id=pg_temp.f('request-audit-shift') AND action='volunteers.shift.upsert' AND after_data@>jsonb_build_object('prior_capacity',NULL,'capacity',2,'prior_role_id',NULL,'role_id',pg_temp.rid('role'))));
SELECT pg_temp.check('shift update audits prior and current capacity and role','AUDIT',EXISTS(SELECT 1 FROM public.audit_events WHERE request_id=pg_temp.f('request-audit-role-capacity-change') AND action='volunteers.shift.upsert' AND after_data@>jsonb_build_object('prior_capacity',2,'capacity',3,'prior_role_id',pg_temp.rid('role'),'role_id',pg_temp.rid('audit-replacement-role'))));
SELECT pg_temp.check('role change marks volunteer duties materially changed','K',EXISTS(SELECT 1 FROM public.audit_events WHERE request_id=pg_temp.f('request-audit-role-capacity-change') AND after_data->'material_change'='true'::jsonb));
SELECT pg_temp.check('title change marks volunteer duties materially changed','K',EXISTS(SELECT 1 FROM public.audit_events WHERE request_id=pg_temp.f('request-audit-title-change') AND after_data->'material_change'='true'::jsonb));
SELECT pg_temp.check('capacity only change audited without volunteer change alert','K',EXISTS(SELECT 1 FROM public.audit_events WHERE request_id=pg_temp.f('request-audit-capacity-only-change') AND after_data->'material_change'='false'::jsonb AND after_data@>jsonb_build_object('prior_capacity',3,'capacity',4)));
SELECT pg_temp.check('unsafe capacity override records no successful change','AUDIT',NOT EXISTS(SELECT 1 FROM public.audit_events WHERE request_id=pg_temp.f('request-unsafe capacity override field') AND action='volunteers.shift.upsert'));
SELECT pg_temp.check('shift change audit material marker','K',EXISTS(SELECT 1 FROM public.audit_events WHERE request_id=pg_temp.f('request-change-shift') AND after_data->'material_change'='true'::jsonb));
SELECT pg_temp.check('event currentstamp review recorded','EVENT',(SELECT event_context_stamp=boss_private.volunteer_event_stamp(event_id,occurrence_key) FROM public.volunteer_shifts WHERE id=pg_temp.rid('event-shift')));
UPDATE public.guardian_relationships SET authority_status='inactive',ends_at=now() WHERE id=pg_temp.f('guardian');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('parent');
SELECT pg_temp.read_deny('revoked guardian historical commitment does not open shift',pg_temp.query('open-shift'));
SELECT pg_temp.deny('revoked guardian stale signup denied','FAMILY',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('open-shift'))),ARRAY['PT403'],'parent-signup');
SELECT pg_temp.ok('revoked owner can safely cancel own commitment','E',pg_temp.cmd('assignment.cancel',jsonb_build_object('assignment_id',pg_temp.rid('parent-signup'),'expected_version',3)));
RESET ROLE;
UPDATE public.team_memberships SET status='inactive',ends_at=now() WHERE person_id=pg_temp.f('coordinator');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('coordinator');SELECT pg_temp.deny('coordinator role alone without current team denied','I',pg_temp.shift('inactive-coordinator'));
RESET ROLE;
UPDATE public.events SET status='canceled',version=version+1 WHERE id=pg_temp.f('event');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('parent2');SELECT pg_temp.deny('canceled event closes volunteer signup','EVENT',pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.rid('event-shift'))));
RESET ROLE;
DO $$DECLARE t text;denied boolean;BEGIN FOREACH t IN ARRAY ARRAY['volunteer_role_definitions','volunteer_shifts','volunteer_assignments','volunteer_assignment_history'] LOOP denied:=false;BEGIN EXECUTE format('delete from public.%I',t);EXCEPTION WHEN OTHERS THEN denied:=true;END;PERFORM pg_temp.check(t||' retains history','HISTORY',denied);END LOOP;END$$;
SET LOCAL ROLE authenticated;SELECT pg_temp.act('admin');
DO $$DECLARE denied boolean:=false;BEGIN BEGIN INSERT INTO public.volunteer_assignments(organization_id,shift_id,person_id,source,assigned_by_person_id) VALUES(pg_temp.f('org-a'),pg_temp.rid('open-shift'),pg_temp.f('outsider'),'staff',pg_temp.f('admin'));EXCEPTION WHEN insufficient_privilege THEN denied:=true;END;PERFORM pg_temp.check('direct raw mutation denied','N',denied);END$$;
SELECT pg_temp.ok('feature-off','POLICY',pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org-a'),'configuration','{"volunteers":false}'::jsonb)));
SELECT pg_temp.check('disabled orgmanager sees onlyconfiguration','POLICY',public.boss_volunteers_read(pg_temp.query())->'operations'='["volunteers.configure"]'::jsonb AND public.boss_volunteers_read(pg_temp.query())->'shifts'='[]'::jsonb);
SELECT pg_temp.check('disabled onlyauthorized organization hides navigation','POLICY',public.boss_volunteers_read(pg_temp.query())->'navigation_available'='false'::jsonb);
SELECT pg_temp.read_deny('disabled feature closes evenadmin shiftprojection',pg_temp.query('open-shift'));
SELECT pg_temp.act('platform');
SELECT pg_temp.check('another authorized enabled organization retains navigation','POLICY',public.boss_volunteers_read(pg_temp.query())->'navigation_available'='true'::jsonb AND public.boss_volunteers_read(pg_temp.query())->'features'->'volunteers'='false'::jsonb);
SELECT pg_temp.act('admin');
SELECT pg_temp.ok('feature-on','POLICY',pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org-a'),'configuration','{"volunteers":true}'::jsonb)));
RESET ROLE;
-- Bounded pickers never substitute for authorization of an explicitly selected context.
INSERT INTO public.organizations(id,name,slug) SELECT pg_temp.f('bounded-'||n),'Synthetic bounded '||lpad(n::text,3,'0'),'phase4b-vol-bounded-'||n FROM generate_series(1,100)n;
INSERT INTO public.organization_modules(organization_id,module_id,status,starts_at,configuration) SELECT pg_temp.f('bounded-'||n),m.id,'active',now()-interval '1 day','{"volunteers":false}' FROM generate_series(1,100)n CROSS JOIN public.modules m WHERE m.key='volunteers';
INSERT INTO public.teams(id,organization_id,parent_unit_id,name,slug,status) SELECT pg_temp.f('bounded-team-'||n),pg_temp.f('org-a'),pg_temp.f('unit-a'),'Synthetic bounded team '||lpad(n::text,3,'0'),'phase4b-vol-bounded-'||n,'active' FROM generate_series(1,100)n;
SET LOCAL ROLE authenticated;SELECT pg_temp.act('platform');
SELECT pg_temp.check('organization picker reports bounded options','BOUNDING',public.boss_volunteers_read()->'options_limited'='true'::jsonb AND jsonb_array_length(public.boss_volunteers_read()->'organizations')=100);
SELECT pg_temp.check('explicit authorized context outside picker remains available','BOUNDING',public.boss_volunteers_read(pg_temp.query())->>'organizationId'=pg_temp.f('org-a')::text AND jsonb_array_length(public.boss_volunteers_read(pg_temp.query())->'organizations')=101);
SELECT pg_temp.check('navigation detects enabled context beyond bounded picker','BOUNDING',public.boss_volunteers_read()->'navigation_available'='true'::jsonb AND public.boss_volunteers_read()->'features'->'volunteers'='false'::jsonb);
SELECT pg_temp.check('management targets remain bounded','BOUNDING',jsonb_array_length(public.boss_volunteers_read(pg_temp.query())->'targets')=100);
SELECT pg_temp.check('selected manageable detail outside scope picker retained','BOUNDING',jsonb_array_length(public.boss_volunteers_read(pg_temp.query('unit-shift'))->'targets')=101 AND EXISTS(SELECT 1 FROM jsonb_array_elements(public.boss_volunteers_read(pg_temp.query('unit-shift'))->'targets') target WHERE target->>'scope_type'='unit' AND target->>'scope_id'=pg_temp.f('unit-a')::text));
SELECT pg_temp.check('exact team filter refines management options','BOUNDING',public.boss_volunteers_read(pg_temp.query()||jsonb_build_object('team_id',pg_temp.f('team-a')))->'targets'=jsonb_build_array(jsonb_build_object('scope_type','team','scope_id',pg_temp.f('team-a'),'label','Synthetic Falcons')));
RESET ROLE;
SELECT count(*) AS passed_assertions FROM pg_temp.phase4b_vol_assertions;
SELECT count(*) AS assertions,category FROM pg_temp.phase4b_vol_assertions GROUP BY category ORDER BY category;
ROLLBACK;
