begin;
set local statement_timeout='8s';
create temp table rb_assertions(label text primary key);
create function pg_temp.ok(label text,condition boolean)returns void language plpgsql as $$begin if condition is distinct from true then raise exception 'FAIL Phase6B %',label;end if;insert into rb_assertions values(label);end$$;
create function pg_temp.policy(sport text default'basketball',rules jsonb default'[]')returns jsonb language sql immutable as $$select jsonb_build_object('template',sport,'order_by','win_percentage','tie_weight',0.5,'allow_ties',true,'tiebreaks',rules)$$;
create function pg_temp.source(c jsonb,coverage jsonb,confirmed boolean default true,basis int default null)returns jsonb language sql immutable as $$select jsonb_build_object('components',c,'coverage',coverage,'participation',jsonb_build_object('confirmed',confirmed),'era_basis_innings',basis)$$;
select pg_temp.ok('six finite sport policies valid:'||s,boss_private.ranking_validate_policy(pg_temp.policy(s)))from unnest(array['basketball','soccer','football','volleyball','baseball','softball'])s;
select pg_temp.ok('invalid template denied',not boss_private.ranking_validate_policy(pg_temp.policy('unreviewed')));
select pg_temp.ok('missing required template denied',not boss_private.ranking_validate_policy(pg_temp.policy()-'template'));
select pg_temp.ok('null required type denied:'||k,not boss_private.ranking_validate_policy(jsonb_set(pg_temp.policy(),array[k],'null')))from unnest(array['template','order_by','tie_weight','allow_ties','tiebreaks'])k;
select pg_temp.ok('null optional type denied:'||k,not boss_private.ranking_validate_policy(pg_temp.policy()||jsonb_build_object(k,null)))from unnest(array['win_points','tie_points','loss_points','mini_table_restart','allow_manual_resolution','forfeit_score'])k;
select pg_temp.ok('unknown formula denied',not boss_private.ranking_validate_policy(pg_temp.policy()||'{"sql":"select 1"}'));
select pg_temp.ok('unapproved manual resolution denied',not boss_private.ranking_validate_policy(pg_temp.policy('soccer','[{"type":"administrative"}]')));
select pg_temp.ok('null cap denied',not boss_private.ranking_validate_policy(pg_temp.policy('soccer','[{"type":"capped_differential","cap":null}]')));
select pg_temp.ok('negative cap denied',not boss_private.ranking_validate_policy(pg_temp.policy('soccer','[{"type":"capped_differential","cap":-1}]')));
select pg_temp.ok('forged group denied',not boss_private.ranking_validate_policy(pg_temp.policy('soccer','[{"type":"conference_percentage","group_id":"--------0000-0000-0000-000000000000"}]')));
select pg_temp.ok('explicit finite minimum valid',boss_private.ranking_validate_qualification('{"thresholds":[{"type":"min_attempts","metric":"fga","value":5}]}',true));
select pg_temp.ok('rate requires policy',not boss_private.ranking_validate_qualification('{}',true));
select pg_temp.ok('counting has no invented minimum',boss_private.ranking_validate_qualification('{}',false));
select pg_temp.ok('null minimum denied',not boss_private.ranking_validate_qualification('{"thresholds":[{"type":"min_games","value":null}]}',true));
select pg_temp.ok('null threshold array denied',not boss_private.ranking_validate_qualification('{"thresholds":null}',false));
select pg_temp.ok('null threshold metric denied',not boss_private.ranking_validate_qualification('{"thresholds":[{"type":"min_attempts","value":5,"metric":null}]}',true));
select pg_temp.ok('no fabricated zero',boss_private.ranking_measure('basketball',jsonb_build_array(pg_temp.source('{"points":null}','{"points":"not_tracked"}')),'points','count','{}',false,1) @>'{"state":"incomplete","value":null}');
select pg_temp.ok('tracked zero qualified',boss_private.ranking_measure('basketball',jsonb_build_array(pg_temp.source('{"points":0}','{"points":"tracked"}')),'points','count','{}',false,1) @>'{"state":"qualified","value":0}');
select pg_temp.ok('unused participant unqualified',boss_private.ranking_measure('basketball',jsonb_build_array(pg_temp.source('{"points":0}','{"points":"tracked"}',false)),'points','count','{}',false,1)->>'state'='unqualified');
select pg_temp.ok('partial default incomplete',boss_private.ranking_measure('basketball',jsonb_build_array(pg_temp.source('{"points":12}','{"points":"partially_tracked"}')),'points','count','{}',false,1)->>'state'='incomplete');
select pg_temp.ok('explicit observed basis disclosed',boss_private.ranking_measure('basketball',jsonb_build_array(pg_temp.source('{"points":12}','{"points":"partially_tracked"}')),'points','count','{}',true,1) @>'{"state":"qualified","value":12,"coverage":{"partial_allowed":true}}');
select pg_temp.ok('unequal denominators never average game percentages',abs((boss_private.ranking_measure('basketball',jsonb_build_array(pg_temp.source('{"fgm":1,"fga":1}','{"fgm":"tracked","fga":"tracked"}'),pg_temp.source('{"fgm":0,"fga":9}','{"fgm":"tracked","fga":"tracked"}')),'fg_percentage','rate','{"thresholds":[{"type":"min_attempts","metric":"fga","value":10}]}',false,2)->>'value')::numeric-10)<0.00001);
select pg_temp.ok('below minimum stays unranked',boss_private.ranking_measure('basketball',jsonb_build_array(pg_temp.source('{"fgm":1,"fga":2}','{"fgm":"tracked","fga":"tracked"}')),'fg_percentage','rate','{"thresholds":[{"type":"min_attempts","metric":"fga","value":5}]}',false,1)->>'state'='below_minimum');
select pg_temp.ok('incompatible numerator denominator cohort incomplete',boss_private.ranking_measure('basketball',jsonb_build_array(pg_temp.source('{"fgm":1,"fga":2}','{"fgm":"tracked","fga":"not_tracked"}')),'fg_percentage','rate','{"thresholds":[{"type":"min_attempts","metric":"fga","value":1}]}',false,1)->>'state'='incomplete');
select pg_temp.ok('missing rate policy not official leader',boss_private.ranking_measure('basketball',jsonb_build_array(pg_temp.source('{"fgm":1,"fga":2}','{"fgm":"tracked","fga":"tracked"}')),'fg_percentage','rate','{}',false,1)->>'state'='no_policy');
select pg_temp.ok('integer outs produce baseball ERA',boss_private.ranking_measure('baseball',jsonb_build_array(pg_temp.source('{"earned_runs":2,"outs_pitched":6}','{"earned_runs":"tracked","outs_pitched":"tracked"}',true,9)),'era','rate','{"thresholds":[{"type":"min_innings_equivalent","value":2}]}',false,1) @>'{"state":"qualified","value":9}');
select pg_temp.ok('mixed ERA conventions unavailable',boss_private.ranking_measure('baseball',jsonb_build_array(pg_temp.source('{"earned_runs":2,"outs_pitched":6}','{"earned_runs":"tracked","outs_pitched":"tracked"}',true,9),pg_temp.source('{"earned_runs":1,"outs_pitched":3}','{"earned_runs":"tracked","outs_pitched":"tracked"}',true,7)),'era','rate','{"thresholds":[{"type":"min_outs","value":3}]}',false,2)->>'value'is null);
select pg_temp.ok('twelve exact capability keys',cardinality(boss_private.ranking_permission_keys())=12);
select pg_temp.ok('no scorer management expansion',not exists(select 1 from public.roles r join public.role_permissions rp on rp.role_id=r.id join public.permissions p on p.id=rp.permission_id where r.key in('scorekeeper','statistician','guardian','athlete')and p.key=any(boss_private.ranking_permission_keys())));
select count(*)passed_assertions from rb_assertions;
rollback;
