\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase7c/fixture.sql
select pg_temp.success('longer-life',4000);
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.bm('policy.create',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'mode','percentage','basis_points',10000,'currency','USD','channels',jsonb_build_array('direct_support'),'expiry_seconds',3600));reset role;
select pg_temp.success('earlier-expiry',3000);
set constraints all immediate;set constraints all deferred;
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.denied('mixed-case UUID cannot disguise duplicate Bucks charge',format('select pg_temp.bm(''payment.spend'',%L)',jsonb_build_object('wallet_id',pg_temp.w(),'organization_id',pg_temp.f('org'),'currency','USD','amount_minor',2000,'allocations',jsonb_build_array(jsonb_build_object('charge_id',pg_temp.f('charge-camp')::text,'amount_minor',1000),jsonb_build_object('charge_id',upper(pg_temp.f('charge-camp')::text),'amount_minor',1000)))),'PT422');
insert into payment_results values('partial',pg_temp.bm('payment.spend',pg_temp.spend_input(1500),pg_temp.f('spend-partial')));
select pg_temp.check('partial receipt uses true internal payment method','RECEIPT',(select result->'receipt'->>'method'='boss_bucks'and result->'receipt'->>'amount_minor'='1500'from payment_results where label='partial'));
select pg_temp.check('receipt preserves unpaid balance','RECEIPT',(select result->'receipt'->'charges'->0->>'remaining_minor'='8500'from payment_results where label='partial'));
select pg_temp.check('same signed spend replay','IDEMPOTENCY',pg_temp.bm('payment.spend',pg_temp.spend_input(1500),pg_temp.f('spend-partial'))->>'replayed'='true');
select pg_temp.conflict('same key changed amount denied',format('select pg_temp.bm(''payment.spend'',%L,%L)',pg_temp.spend_input(1501),pg_temp.f('spend-partial')));
reset role;
set constraints all immediate;set constraints all deferred;
select pg_temp.check('FEFO consumes sooner-expiring grant','ORDER',exists(select 1 from public.boss_bucks_consumptions c join public.boss_bucks_grants g on g.id=c.grant_id join public.fundraising_success_evidence e on e.id=g.evidence_id where e.source_reference='earlier-expiry'and c.amount_minor=1500));
select pg_temp.check('replay creates one debit and payment','IDEMPOTENCY',(select count(*)=1 from public.payments where method='boss_bucks')and(select count(*)=1 from public.boss_bucks_journals where kind='spend'));
select pg_temp.check('wallet rebuild includes spending','REBUILD',boss_private.bucks_available(pg_temp.w())=3500 and boss_private.bucks_rebuild(pg_temp.w())->0->>'available_minor'='3500');
select pg_temp.check('canonical balance is partial','CHARGE',boss_private.registration_charge_balance(pg_temp.f('charge-camp'))->>'balance_due_minor'='8500'and boss_private.registration_charge_balance(pg_temp.f('charge-camp'))->>'payment_status'='partially_paid');
set local role authenticated;select pg_temp.actor('parent');
insert into payment_results values('multi',pg_temp.bm('payment.spend',jsonb_build_object('wallet_id',pg_temp.w(),'organization_id',pg_temp.f('org'),'currency','USD','amount_minor',2000,'allocations',jsonb_build_array(jsonb_build_object('charge_id',pg_temp.f('charge-gear'),'amount_minor',1000),jsonb_build_object('charge_id',pg_temp.f('charge-travel'),'amount_minor',1000)))));
reset role;set constraints all immediate;set constraints all deferred;
select pg_temp.check('one multi-charge canonical payment','ALLOCATIONS',(select count(*)=2 and sum(a.amount_minor)=2000 from public.payment_allocations a where payment_id=(select(result->'receipt'->>'payment_id')::uuid from payment_results where label='multi')));
select pg_temp.check('multi-grant slices conserve debit','LEDGER',(select sum(amount_minor)=3500 from public.boss_bucks_consumptions)and boss_private.bucks_available(pg_temp.w())=1500);
select pg_temp.check('balanced redemption clearing','LEDGER',(select sum(p.amount_minor)=3500 from public.boss_bucks_postings p join public.boss_bucks_accounts a on a.id=p.account_id where a.kind='redemption'));
select pg_temp.check('source grants retain immutable provenance','LINEAGE',(select count(*)=2 and sum(amount_minor)=5000 from public.boss_bucks_grants));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.denied('mixed-case UUID cannot disguise duplicate offline charge',format('select public.boss_registration_mutate(gen_random_uuid(),%L)',jsonb_build_object('operation','payment.record_offline','input',jsonb_build_object('organization_id',pg_temp.f('org'),'method','cash','amount_minor',2000,'currency','USD','payer_person_id',pg_temp.f('parent'),'received_at',now(),'allocations',jsonb_build_array(jsonb_build_object('charge_id',pg_temp.f('charge-gear')::text,'amount_minor',1000),jsonb_build_object('charge_id',upper(pg_temp.f('charge-gear')::text),'amount_minor',1000))))),'PT422');
select public.boss_registration_mutate(pg_temp.f('cash-after-bucks'),jsonb_build_object('operation','payment.record_offline','input',jsonb_build_object('organization_id',pg_temp.f('org'),'method','cash','amount_minor',8500,'currency','USD','payer_person_id',pg_temp.f('parent'),'received_at',now(),'allocations',jsonb_build_array(jsonb_build_object('charge_id',pg_temp.f('charge-camp'),'amount_minor',8500)))));
reset role;
select pg_temp.check('cash completes same canonical obligation','SPLIT',boss_private.registration_charge_balance(pg_temp.f('charge-camp'))->>'balance_due_minor'='0'and boss_private.registration_charge_balance(pg_temp.f('charge-camp'))->>'payment_status'='paid');
select pg_temp.check('cash leaves wallet unchanged','SPLIT',boss_private.bucks_available(pg_temp.w())=1500);
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.conflict('overpayment denied',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1)));
select pg_temp.conflict('overdraft denied',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1501,'church')));
select pg_temp.denied('unrelated child denied',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'unrelated-child')));
select pg_temp.denied('wrong currency denied',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'currency')));
select pg_temp.denied('wrong originating organization denied',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'other')));
select pg_temp.denied('forged wallet denied',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'church')||jsonb_build_object('wallet_id',pg_temp.f('missing'))));
select pg_temp.denied('forged charge denied',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'missing')));
select pg_temp.denied('caller grant selection rejected',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'church')||jsonb_build_object('grant_ids',jsonb_build_array(pg_temp.f('missing')))),'PT422');
select pg_temp.denied('caller household rejected',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'church')||jsonb_build_object('household_id',pg_temp.f('household'))),'PT422');
select pg_temp.denied('allocation amount sum forgery rejected',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'church')||jsonb_build_object('amount_minor',2)),'PT422');
select pg_temp.denied('zero amount rejected',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(0,'church')),'PT422');
select pg_temp.denied('negative amount rejected',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(-1,'church')),'PT422');
select pg_temp.actor('household-only');select pg_temp.denied('household alone cannot pay',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'church')));
select pg_temp.actor('admin');select pg_temp.denied('admin role alone cannot family spend',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'church')));
select pg_temp.actor('coach');select pg_temp.denied('coach cannot spend family value',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'church')));
reset role;
update public.guardian_relationships set can_manage_payments=false where id=pg_temp.f('guardian-child1');
set local role authenticated;select pg_temp.actor('parent');select pg_temp.denied('wallet capability without payment guardian denied',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'church')));
select pg_temp.denied('stale signed spend replay denied after revocation',format('select pg_temp.bm(''payment.spend'',%L,%L)',pg_temp.spend_input(1500),pg_temp.f('spend-partial')));
reset role;update public.guardian_relationships set can_manage_payments=true,can_manage_boss_bucks=false where id=pg_temp.f('guardian-child1');
set local role authenticated;select pg_temp.actor('parent');select pg_temp.denied('payment guardian without wallet authority denied',format('select pg_temp.bm(''payment.spend'',%L)',pg_temp.spend_input(1,'church')));reset role;
select pg_temp.check('failed requests leave money movement unchanged','ATOMICITY',(select count(*)=2 from public.payments where method='boss_bucks')and boss_private.bucks_available(pg_temp.w())=1500);
select pg_temp.check('all journals balanced','LEDGER',not exists(select journal_id from public.boss_bucks_postings group by journal_id having count(*)<>2 or sum(amount_minor)<>0));
set constraints all immediate;
select count(*)passed_assertions,'Phase 7C payments' suite from phase5a_assertions;rollback;
