-- Phase 4A communications: synthetic records, actual client roles, no passwords,
-- tokens, private file bytes or remote connections. Transaction rollback retains
-- production history guards and discards all synthetic activity.
BEGIN;
CREATE TEMP TABLE phase4a_comm_assertions(label text primary key,category text not null) ON COMMIT DROP;
CREATE TEMP TABLE phase4a_comm_results(label text primary key,result jsonb not null) ON COMMIT DROP;
GRANT SELECT,INSERT,UPDATE ON pg_temp.phase4a_comm_assertions,pg_temp.phase4a_comm_results TO authenticated,anon;
CREATE FUNCTION pg_temp.f(label text) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$SELECT md5('boss-phase4a-communications:'||label)::uuid$$;
CREATE FUNCTION pg_temp.check(label text,category text,ok boolean) RETURNS void LANGUAGE plpgsql AS $$BEGIN IF ok IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL [%] %',category,label;END IF;INSERT INTO pg_temp.phase4a_comm_assertions VALUES(label,category);END$$;
CREATE FUNCTION pg_temp.act(label text) RETURNS void LANGUAGE plpgsql AS $$BEGIN PERFORM set_config('request.jwt.claim.sub','',true);PERFORM set_config('request.jwt.claim','',true);PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('auth-'||label),'role','authenticated','is_anonymous',false,'session_id',pg_temp.f('session-'||label),'user_metadata',jsonb_build_object('role','platform_administrator'))::text,true);END$$;
CREATE FUNCTION pg_temp.cmd(op text,i jsonb) RETURNS jsonb LANGUAGE sql AS $$SELECT jsonb_build_object('operation',op,'input',i)$$;
CREATE FUNCTION pg_temp.ok(label text,category text,c jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$DECLARE r jsonb;BEGIN r:=public.boss_communications_mutate(pg_temp.f('request-'||label),c);PERFORM pg_temp.check(label,category,jsonb_typeof(r)='object');INSERT INTO pg_temp.phase4a_comm_results VALUES(label,r);RETURN r;END$$;
CREATE FUNCTION pg_temp.rid(label text) RETURNS uuid LANGUAGE sql AS $$SELECT (result->>'resource_id')::uuid FROM pg_temp.phase4a_comm_results WHERE phase4a_comm_results.label=$1$$;
CREATE FUNCTION pg_temp.deny(label text,category text,c jsonb,states text[] DEFAULT ARRAY['PT403'],request_label text DEFAULT NULL) RETURNS void LANGUAGE plpgsql AS $$DECLARE denied boolean:=false;BEGIN BEGIN PERFORM public.boss_communications_mutate(pg_temp.f('request-'||coalesce(request_label,label)),c);EXCEPTION WHEN OTHERS THEN IF SQLSTATE=ANY(states) THEN denied:=true;ELSE RAISE EXCEPTION 'FAIL % unexpected state %: %',label,SQLSTATE,SQLERRM;END IF;END;PERFORM pg_temp.check(label,category,denied);END$$;
CREATE FUNCTION pg_temp.read_deny(label text,q jsonb) RETURNS void LANGUAGE plpgsql AS $$DECLARE denied boolean:=false;BEGIN BEGIN PERFORM public.boss_communications_read(q);EXCEPTION WHEN SQLSTATE 'PT403' THEN denied:=true;END;PERFORM pg_temp.check(label,'ISOLATION',denied);END$$;
CREATE FUNCTION pg_temp.query(thread_label text DEFAULT NULL) RETURNS jsonb LANGUAGE sql AS $$SELECT jsonb_strip_nulls(jsonb_build_object('organization_id',pg_temp.f('org-a'),'thread_id',CASE WHEN thread_label IS NOT NULL THEN pg_temp.rid(thread_label) END))$$;
CREATE FUNCTION pg_temp.thread(kind text,scope_type text,scope_label text,members jsonb DEFAULT NULL) RETURNS jsonb LANGUAGE sql AS $$SELECT pg_temp.cmd('thread.create',jsonb_strip_nulls(jsonb_build_object('organization_id',pg_temp.f('org-a'),'title','Synthetic controlled '||kind,'kind',kind,'scope_type',scope_type,'scope_id',pg_temp.f(scope_label),'members',members)))$$;
CREATE FUNCTION pg_temp.announcement(target text DEFAULT 'team-a',typ text DEFAULT 'team') RETURNS jsonb LANGUAGE sql AS $$SELECT pg_temp.cmd('announcement.send',jsonb_build_object('organization_id',pg_temp.f('org-a'),'title','Synthetic announcement','body','Synthetic controlled announcement content','targets',jsonb_build_array(jsonb_build_object('scope_type',typ,'scope_id',pg_temp.f(target)))))$$;
DO $$DECLARE f record;BEGIN FOR f IN SELECT p.oid::regprocedure f FROM pg_proc p WHERE p.pronamespace=pg_my_temp_schema() LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',f.f);EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated,anon',f.f);END LOOP;END$$;
-- ACL assertions include the arbitrary-recipient helper boundary.
DO $$DECLARE tab text;f record;BEGIN
 FOREACH tab IN ARRAY ARRAY['communication_threads','communication_thread_members','communication_audiences','communication_messages','communication_message_revisions','communication_read_state','communication_attachments','communication_reports'] LOOP
 PERFORM pg_temp.check(tab||' RLS','SECURITY',(SELECT relrowsecurity FROM pg_class WHERE oid=('public.'||tab)::regclass));
 PERFORM pg_temp.check(tab||' no authenticated raw access','SECURITY',NOT has_table_privilege('authenticated','public.'||tab,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE'));
 PERFORM pg_temp.check(tab||' no anon raw access','SECURITY',NOT has_table_privilege('anon','public.'||tab,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE'));END LOOP;
 FOR f IN SELECT p.oid::regprocedure id,p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='boss_private' AND p.proname IN('comm_person_active','comm_permission','comm_guardian','comm_thread_can_view','comm_message_can_view') LOOP
 PERFORM pg_temp.check(f.proname||' private recipient helper','SECURITY',NOT has_function_privilege('authenticated',f.id,'EXECUTE') AND NOT has_function_privilege('anon',f.id,'EXECUTE'));END LOOP;
 PERFORM pg_temp.check('public RPCs invoker','SECURITY',NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname LIKE 'boss_communications_%' AND p.prosecdef));
 PERFORM pg_temp.check('anon RPC closed','SECURITY',NOT has_function_privilege('anon','public.boss_communications_read(jsonb)','EXECUTE') AND NOT has_function_privilege('anon','public.boss_communications_mutate(uuid,jsonb)','EXECUTE'));
END$$;
INSERT INTO auth.users(id,email,email_confirmed_at,is_anonymous) SELECT pg_temp.f('auth-'||p),p||'@phase4a.example.invalid',now()-interval '1 day',false FROM unnest(ARRAY['platform','admin-a','admin-b','coach','assistant','unit','guardian','receive-only','household-only','outsider','child','child2','unknown','expired','finance'])p;
INSERT INTO auth.sessions(id,user_id) SELECT pg_temp.f('session-'||p),pg_temp.f('auth-'||p) FROM unnest(ARRAY['platform','admin-a','admin-b','coach','assistant','unit','guardian','receive-only','household-only','outsider','child','child2','unknown','expired','finance'])p;
INSERT INTO public.people(id,display_name,date_of_birth) SELECT pg_temp.f(p),'Synthetic Phase4A '||p,CASE WHEN p IN('child','child2') THEN current_date-interval '12 years' WHEN p='unknown' THEN NULL ELSE date '1980-01-01' END FROM unnest(ARRAY['platform','admin-a','admin-b','coach','assistant','unit','guardian','receive-only','household-only','outsider','child','child2','unknown','expired','finance'])p;
INSERT INTO public.user_accounts(auth_user_id,person_id,account_status) SELECT pg_temp.f('auth-'||p),pg_temp.f(p),'active' FROM unnest(ARRAY['platform','admin-a','admin-b','coach','assistant','unit','guardian','receive-only','household-only','outsider','child','child2','unknown','expired','finance'])p;
INSERT INTO public.organizations(id,name,slug) VALUES(pg_temp.f('org-a'),'Synthetic Phase4A A','phase4a-a'),(pg_temp.f('org-b'),'Synthetic Phase4A B','phase4a-b');
INSERT INTO public.organization_units(id,organization_id,name,slug,unit_type,parent_unit_id) VALUES(pg_temp.f('unit-a'),pg_temp.f('org-a'),'Synthetic A','a','sport',NULL),(pg_temp.f('unit-sibling'),pg_temp.f('org-a'),'Synthetic sibling','sibling','sport',NULL),(pg_temp.f('unit-child'),pg_temp.f('org-a'),'Synthetic descendant','child','program',pg_temp.f('unit-a'));
INSERT INTO public.teams(id,organization_id,parent_unit_id,name,slug) VALUES(pg_temp.f('team-a'),pg_temp.f('org-a'),pg_temp.f('unit-a'),'Synthetic Falcons','a'),(pg_temp.f('team-b'),pg_temp.f('org-a'),pg_temp.f('unit-a'),'Synthetic Owls','b'),(pg_temp.f('team-sibling'),pg_temp.f('org-a'),pg_temp.f('unit-sibling'),'Synthetic sibling','sibling'),(pg_temp.f('team-child'),pg_temp.f('org-a'),pg_temp.f('unit-child'),'Synthetic descendant','child'),(pg_temp.f('other-team'),pg_temp.f('org-b'),NULL,'Synthetic other tenant','other');
UPDATE public.teams SET status='active' WHERE organization_id IN(pg_temp.f('org-a'),pg_temp.f('org-b'));
INSERT INTO public.organization_modules(organization_id,module_id,status,starts_at,configuration) SELECT pg_temp.f(org),m.id,'active',now()-interval '1 day','{"communications":true,"announcements":true,"team_chat":true,"direct_messaging":true,"attachments":true,"moderation":true,"staff_send":false}' FROM public.modules m CROSS JOIN unnest(ARRAY['org-a','org-b'])org WHERE m.key='messaging';
INSERT INTO public.role_assignments(person_id,role_id,scope_type,scope_id,organization_id,starts_at,ends_at)
SELECT pg_temp.f(p),r.id,scope,CASE WHEN target IS NOT NULL THEN pg_temp.f(target) END,CASE WHEN org IS NOT NULL THEN pg_temp.f(org) END,now()-interval '2 days',CASE WHEN p='expired' THEN now()-interval '1 day' END
FROM(VALUES('platform','platform_administrator','platform',NULL,NULL),('admin-a','organization_administrator','organization','org-a','org-a'),('admin-b','organization_administrator','organization','org-b','org-b'),('coach','head_coach','team','team-a','org-a'),('assistant','assistant_coach','team','team-a','org-a'),('unit','program_administrator','organization_unit','unit-a','org-a'),('expired','head_coach','team','team-a','org-a'),('finance','organization_finance','organization','org-a','org-a'))v(p,role,scope,target,org) JOIN public.roles r ON r.key=v.role;
INSERT INTO public.organization_memberships(organization_id,person_id,starts_at) SELECT pg_temp.f('org-a'),pg_temp.f(p),now()-interval '1 day' FROM unnest(ARRAY['admin-a','coach','assistant','unit','guardian','receive-only','household-only','child','child2','unknown','expired','finance'])p;
INSERT INTO public.organization_memberships(organization_id,person_id,starts_at) VALUES(pg_temp.f('org-b'),pg_temp.f('admin-b'),now()-interval '1 day'),(pg_temp.f('org-b'),pg_temp.f('outsider'),now()-interval '1 day');
INSERT INTO public.participants(id,person_id,participant_type) VALUES(pg_temp.f('participant'),pg_temp.f('child'),'athlete'),(pg_temp.f('participant2'),pg_temp.f('child2'),'athlete'),(pg_temp.f('unknown-participant'),pg_temp.f('unknown'),'athlete');
INSERT INTO public.team_memberships(organization_id,team_id,person_id,participant_id,membership_type,starts_at) VALUES(pg_temp.f('org-a'),pg_temp.f('team-a'),pg_temp.f('child'),pg_temp.f('participant'),'athlete',now()-interval '1 day'),(pg_temp.f('org-a'),pg_temp.f('team-b'),pg_temp.f('child2'),pg_temp.f('participant2'),'athlete',now()-interval '1 day'),(pg_temp.f('org-a'),pg_temp.f('team-a'),pg_temp.f('unknown'),pg_temp.f('unknown-participant'),'athlete',now()-interval '1 day');
INSERT INTO public.team_memberships(organization_id,team_id,person_id,membership_type,starts_at) SELECT pg_temp.f('org-a'),pg_temp.f('team-a'),pg_temp.f(p),'coach',now()-interval '1 day' FROM unnest(ARRAY['coach','assistant','expired'])p;
INSERT INTO public.guardian_relationships(id,guardian_person_id,dependent_person_id,authority_status,verified_at,starts_at,can_receive_communications,can_send_communications,can_register)
VALUES(pg_temp.f('guardian-relation'),pg_temp.f('guardian'),pg_temp.f('child'),'active',now()-interval '1 day',now()-interval '1 day',true,true,true),(pg_temp.f('receive-relation'),pg_temp.f('receive-only'),pg_temp.f('child'),'active',now()-interval '1 day',now()-interval '1 day',true,false,true),(pg_temp.f('other-relation'),pg_temp.f('guardian'),pg_temp.f('child2'),'active',now()-interval '1 day',now()-interval '1 day',false,false,true);
INSERT INTO public.households(id,name) VALUES(pg_temp.f('household'),'Synthetic Phase4A household');
INSERT INTO public.household_memberships(household_id,person_id,starts_at) SELECT pg_temp.f('household'),pg_temp.f(p),now()-interval '1 day' FROM unnest(ARRAY['guardian','child','household-only'])p;
SET LOCAL ROLE authenticated;
SELECT pg_temp.act('admin-a');
SELECT pg_temp.ok('org-announcement','A',pg_temp.announcement('org-a','organization'));
SELECT pg_temp.ok('role-announcement','ROLE-AUDIENCE',pg_temp.cmd('announcement.send',jsonb_build_object('organization_id',pg_temp.f('org-a'),'title','Synthetic coaches only','body','Synthetic exact-role message','targets',jsonb_build_array(jsonb_build_object('scope_type','team','scope_id',pg_temp.f('team-a'),'role_key','head_coach')))));
SELECT pg_temp.deny('role audience incompatible scope','ROLE-AUDIENCE',pg_temp.cmd('announcement.send',jsonb_build_object('organization_id',pg_temp.f('org-a'),'title','Synthetic denied scope','body','Synthetic denied role','targets',jsonb_build_array(jsonb_build_object('scope_type','organization','scope_id',pg_temp.f('org-a'),'role_key','head_coach')))),ARRAY['PT422']);
SELECT pg_temp.ok('team-chat','CHAT',pg_temp.thread('team_chat','team','team-a'));
SELECT pg_temp.ok('other-team-chat','CHAT',pg_temp.thread('team_chat','team','team-b'));
SELECT pg_temp.ok('assistant-group','DM-SCOPE',pg_temp.thread('group','team','team-a',jsonb_build_array(pg_temp.f('assistant'))));
SELECT pg_temp.ok('first-message','CHAT',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Synthetic message for guardian')));
SELECT pg_temp.ok('multi-team-announcement','J',pg_temp.cmd('announcement.send',jsonb_build_object('organization_id',pg_temp.f('org-a'),'title','Synthetic two-team announcement','body','Synthetic shared announcement','targets',jsonb_build_array(jsonb_build_object('scope_type','team','scope_id',pg_temp.f('team-a')),jsonb_build_object('scope_type','team','scope_id',pg_temp.f('team-b'))))));
SELECT pg_temp.act('coach');
SELECT pg_temp.check('coach exact role audience readable','ROLE-AUDIENCE',jsonb_array_length(public.boss_communications_read(pg_temp.query('role-announcement'))->'detail'->'messages')=1);
SELECT pg_temp.ok('coach-announcement','B',pg_temp.announcement());
SELECT pg_temp.deny('coach unrelated team announcement','C',pg_temp.announcement('team-b'));
SELECT pg_temp.deny('coach organization announcement','C',pg_temp.announcement('org-a','organization'));
SELECT pg_temp.deny('coach organization DM creation denied','DM-SCOPE',pg_temp.thread('direct','organization','org-a',jsonb_build_array(pg_temp.f('admin-a'))));
SELECT pg_temp.ok('coach-message','CHAT',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Synthetic coach message')));
SELECT pg_temp.act('assistant');
SELECT pg_temp.deny('assistant explicit group still cannot send disabledstaff','DM-SCOPE',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('assistant-group'),'body','Synthetic denied staff bypass')));
SELECT pg_temp.check('assistant own-team view','CHAT',jsonb_array_length(public.boss_communications_read(pg_temp.query('team-chat'))->'detail'->'messages')=2);
SELECT pg_temp.deny('assistant DM staff_send disabled','DM-SCOPE',pg_temp.thread('direct','team','team-a',jsonb_build_array(pg_temp.f('coach'))));
SELECT pg_temp.deny('assistant staff_send disabled','POLICY',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Denied staff message')));
SELECT pg_temp.act('unit');
SELECT pg_temp.deny('program sibling unit announcement','D',pg_temp.announcement('unit-sibling','unit'));
SELECT pg_temp.deny('program descendant inheritance denied','D',pg_temp.announcement('unit-child','unit'));
SELECT pg_temp.ok('exact-unit-announcement','D',pg_temp.announcement('unit-a','unit'));
SELECT pg_temp.act('guardian');
SELECT pg_temp.read_deny('role audience hides coach-only announcement from parent',pg_temp.query('role-announcement'));
SELECT pg_temp.check('guardian receives team announcement','E',jsonb_array_length(public.boss_communications_read(pg_temp.query('coach-announcement'))->'detail'->'messages')=1);
SELECT pg_temp.check('guardian receives chat','E',jsonb_array_length(public.boss_communications_read(pg_temp.query('team-chat'))->'detail'->'messages')=2);
SELECT pg_temp.ok('guardian-message','GUARDIAN',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Synthetic guardian reply')));
SELECT pg_temp.deny('parent cannot broadcast','GUARDIAN',pg_temp.announcement());
SELECT pg_temp.read_deny('unrelated-child team read denied',pg_temp.query('other-team-chat'));
SELECT pg_temp.ok('guardian-read','UNREAD',pg_temp.cmd('read.thread',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'through_sequence',2)));
SELECT pg_temp.check('self-authored message not unread','UNREAD',(public.boss_communications_read(pg_temp.query('team-chat'))->'detail'->'thread'->>'unread_count')::int=0);
SELECT pg_temp.deny('forged read watermark denied','UNREAD',pg_temp.cmd('read.thread',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'through_sequence',999)),ARRAY['PT422']);
SELECT pg_temp.act('receive-only');
SELECT pg_temp.check('receive capability permits read','GUARDIAN',jsonb_array_length(public.boss_communications_read(pg_temp.query('team-chat'))->'detail'->'messages')=3);
SELECT pg_temp.deny('receive capability cannot send','GUARDIAN',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Denied receive-only')));
SELECT pg_temp.act('household-only');
SELECT pg_temp.read_deny('household alone no child channel',pg_temp.query('team-chat'));
SELECT pg_temp.act('child');SELECT pg_temp.read_deny('participant disabled blocks chat',pg_temp.query('team-chat'));
SELECT pg_temp.act('unknown');SELECT pg_temp.read_deny('unknown-age participant blocked',pg_temp.query('team-chat'));
SELECT pg_temp.act('finance');SELECT pg_temp.read_deny('finance no private chat',pg_temp.query('team-chat'));
SELECT pg_temp.act('admin-b');SELECT pg_temp.read_deny('other tenant cannot read forged thread',pg_temp.query('team-chat'));SELECT pg_temp.deny('other tenant target injection', 'U',pg_temp.announcement());
SELECT pg_temp.act('expired');SELECT pg_temp.read_deny('expired staff cannot read chat',pg_temp.query('team-chat'));
SELECT pg_temp.act('guardian');
SELECT pg_temp.ok('report-message','X',pg_temp.cmd('report.create',jsonb_build_object('message_id',pg_temp.rid('first-message'),'reason','other','detail','Synthetic report only')));
SELECT pg_temp.deny('parent moderation denied','X',pg_temp.cmd('report.moderate',jsonb_build_object('report_id',pg_temp.rid('report-message'),'status','actioned','reason','Denied moderation','remove',true)));
SELECT pg_temp.act('admin-a');
SELECT pg_temp.ok('pin-message','PIN',pg_temp.cmd('message.pin',jsonb_build_object('message_id',pg_temp.rid('first-message'),'expected_version',1,'pinned',true)));
SELECT pg_temp.ok('moderate-message','X',pg_temp.cmd('report.moderate',jsonb_build_object('report_id',pg_temp.rid('report-message'),'status','actioned','reason','Synthetic controlled moderation','remove',true)));
SELECT pg_temp.check('moderated content suppressed','X',NOT public.boss_communications_read(pg_temp.query('team-chat'))::text LIKE '%Synthetic message for guardian%');
SELECT pg_temp.ok('edit-message','EDIT',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Synthetic original edit')));
SELECT pg_temp.ok('edit-save','EDIT',pg_temp.cmd('message.edit',jsonb_build_object('message_id',pg_temp.rid('edit-message'),'expected_version',1,'body','Synthetic revised edit')));
SELECT pg_temp.deny('stale edit conflict','EDIT',pg_temp.cmd('message.edit',jsonb_build_object('message_id',pg_temp.rid('edit-message'),'expected_version',1,'body','Synthetic stale edit')),ARRAY['PT409']);
SELECT pg_temp.ok('direct-chat','DM',pg_temp.thread('direct','organization','org-a',jsonb_build_array(pg_temp.f('coach'))));
SELECT pg_temp.ok('direct-message','DM',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('direct-chat'),'body','Synthetic private direct message')));
SELECT pg_temp.deny('cross-tenant recipient injection','U',pg_temp.thread('group','organization','org-a',jsonb_build_array(pg_temp.f('outsider'))));
SELECT pg_temp.deny('minor direct blocked','MINOR',pg_temp.thread('direct','organization','org-a',jsonb_build_array(pg_temp.f('child'))));
SELECT pg_temp.deny('minor group disabled','MINOR',pg_temp.thread('group','organization','org-a',jsonb_build_array(pg_temp.f('child'),pg_temp.f('guardian'))));
SELECT pg_temp.deny('unknown age direct blocked','MINOR',pg_temp.thread('direct','organization','org-a',jsonb_build_array(pg_temp.f('unknown'))));
SELECT pg_temp.ok('enable-minor-policy','MINOR',pg_temp.cmd('communications.configure',jsonb_build_object('organization_id',pg_temp.f('org-a'),'configuration',jsonb_build_object('participant_messaging',true,'minor_groups',true,'guardian_visibility',true,'minimum_participant_age',10,'staff_send',true))));
SELECT pg_temp.ok('minor-guardian-group','G',pg_temp.thread('group','organization','org-a',jsonb_build_array(pg_temp.f('child'),pg_temp.f('guardian'))));
SELECT pg_temp.deny('minor group without copied guardian','G',pg_temp.thread('group','organization','org-a',jsonb_build_array(pg_temp.f('child'))));
SELECT pg_temp.deny('minor DM still denied with policy enabled','MINOR',pg_temp.thread('direct','organization','org-a',jsonb_build_array(pg_temp.f('child'))));
SELECT pg_temp.deny('unknown age group still denied','MINOR',pg_temp.thread('group','organization','org-a',jsonb_build_array(pg_temp.f('unknown'),pg_temp.f('guardian'))));
SELECT pg_temp.deny('unsafe minor policy configuration','MINOR',pg_temp.cmd('communications.configure',jsonb_build_object('organization_id',pg_temp.f('org-a'),'configuration',jsonb_build_object('guardian_visibility',false))),ARRAY['PT422']);
SELECT pg_temp.act('platform');
SELECT pg_temp.ok('guardian-disable-capability','GUARDIAN-COMMAND',pg_temp.cmd('guardian.configure',jsonb_build_object('guardian_relationship_id',pg_temp.f('receive-relation'),'can_receive_communications',false)));
SELECT pg_temp.ok('guardian-restore-capability','GUARDIAN-COMMAND',pg_temp.cmd('guardian.configure',jsonb_build_object('guardian_relationship_id',pg_temp.f('receive-relation'),'can_receive_communications',true)));
SELECT pg_temp.read_deny('platform not invited cannot read DM',pg_temp.query('direct-chat'));
SELECT pg_temp.act('child');SELECT pg_temp.check('permitted minor group readable','G',public.boss_communications_read(pg_temp.query('minor-guardian-group'))->'detail'->'thread'->>'id'=pg_temp.rid('minor-guardian-group')::text);
SELECT pg_temp.act('guardian');SELECT pg_temp.ok('family-chat','FAMILY',pg_temp.thread('family','organization','org-a',jsonb_build_array(pg_temp.f('child')))||jsonb_build_object('input',(pg_temp.thread('family','organization','org-a',jsonb_build_array(pg_temp.f('child')))->'input')||jsonb_build_object('household_id',pg_temp.f('household'))));
SELECT pg_temp.act('assistant');SELECT pg_temp.ok('staff-send-enabled','POLICY',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Synthetic staff enabled reply')));
SELECT pg_temp.act('admin-a');
SELECT pg_temp.ok('attachment-intent','W',pg_temp.cmd('attachment.intent',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'file_name','synthetic.pdf','mime_type','application/pdf','size_bytes',100,'content_sha256',repeat('a',64))));
SELECT pg_temp.ok('announcement-attachment-intent','W',pg_temp.cmd('attachment.intent',jsonb_build_object('thread_id',pg_temp.rid('org-announcement'),'file_name','synthetic-itinerary.pdf','mime_type','application/pdf','size_bytes',100,'content_sha256',repeat('b',64))));
RESET ROLE;
SELECT pg_temp.check('multi-team has separate target rows','J',(SELECT count(*)=2 FROM public.communication_audiences WHERE thread_id=pg_temp.rid('multi-team-announcement')));
SELECT pg_temp.check('announcement did not merge private chat','J',(SELECT count(*)=0 FROM public.communication_thread_members WHERE thread_id=pg_temp.rid('multi-team-announcement')));
SELECT pg_temp.check('guardian configure did not alter verification/window','GUARDIAN-COMMAND',(SELECT authority_status='active' AND verified_at=now()-interval '1 day' AND starts_at=now()-interval '1 day' AND ends_at IS NULL FROM public.guardian_relationships WHERE id=pg_temp.f('receive-relation')));
SELECT pg_temp.check('one message per multi-team announcement','J',(SELECT count(*)=1 FROM public.communication_messages WHERE thread_id=pg_temp.rid('multi-team-announcement')));
SELECT pg_temp.check('removed body history retained privately','X',(SELECT body='Synthetic message for guardian' AND status='removed' FROM public.communication_messages WHERE id=pg_temp.rid('first-message')));
SELECT pg_temp.check('revision evidence retained','EDIT',(SELECT count(*)=1 FROM public.communication_message_revisions WHERE message_id=pg_temp.rid('edit-message')));
SELECT pg_temp.check('audit avoids private content','AUDIT',NOT EXISTS(SELECT 1 FROM public.audit_events WHERE organization_id=pg_temp.f('org-a') AND (coalesce(after_data::text,'') LIKE '%Synthetic private direct message%' OR coalesce(after_data::text,'') LIKE '%Synthetic revised edit%')));
-- Exact operation and metadata parity, including revoked authority on existing lease.
SELECT set_config('storage.operation','object.upload',true);
SET LOCAL ROLE authenticated;SELECT pg_temp.act('admin-a');
SELECT pg_temp.check('exact upload preflight accepts contentLength','W',boss_private.comm_storage_insert('boss-communication-attachments',(SELECT result->>'object_name' FROM pg_temp.phase4a_comm_results WHERE label='attachment-intent'),'{"mimetype":"application/pdf","contentLength":100}'));
SELECT pg_temp.check('forged size denied','W',NOT boss_private.comm_storage_insert('boss-communication-attachments',(SELECT result->>'object_name' FROM pg_temp.phase4a_comm_results WHERE label='attachment-intent'),'{"mimetype":"application/pdf","contentLength":101}'));
SELECT pg_temp.check('conflicting metadata denied','W',NOT boss_private.comm_storage_insert('boss-communication-attachments',(SELECT result->>'object_name' FROM pg_temp.phase4a_comm_results WHERE label='attachment-intent'),'{"mimetype":"application/pdf","contentLength":100,"size":99}'));
SELECT set_config('storage.operation','object.sign',true);
SELECT pg_temp.check('signed upload forbidden','W',NOT boss_private.comm_storage_insert('boss-communication-attachments',(SELECT result->>'object_name' FROM pg_temp.phase4a_comm_results WHERE label='attachment-intent'),'{"mimetype":"application/pdf","size":100}'));
RESET ROLE;
INSERT INTO storage.objects(bucket_id,name,metadata) SELECT 'boss-communication-attachments',result->>'object_name','{"mimetype":"application/pdf","size":100}' FROM pg_temp.phase4a_comm_results WHERE label IN('attachment-intent','announcement-attachment-intent');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('admin-a');
SELECT pg_temp.ok('announcement-attachment-complete','W',pg_temp.cmd('attachment.complete',jsonb_build_object('attachment_id',pg_temp.rid('announcement-attachment-intent'))));
SELECT pg_temp.check('announcement attachment complete links original content','W',jsonb_array_length(public.boss_communications_read(pg_temp.query('org-announcement'))->'detail'->'messages'->0->'attachments')=1);
SELECT pg_temp.ok('attachment-complete','W',pg_temp.cmd('attachment.complete',jsonb_build_object('attachment_id',pg_temp.rid('attachment-intent'))));
DO $$DECLARE r jsonb;BEGIN r:=public.boss_communications_mutate(pg_temp.f('request-attachment-intent'),pg_temp.cmd('attachment.intent',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'file_name','synthetic.pdf','mime_type','application/pdf','size_bytes',100,'content_sha256',repeat('a',64))));PERFORM pg_temp.check('lost completion response recovers same ready attachment','REPLAY',r->'completed'='true'::jsonb AND r->>'status'='ready' AND (r->>'resource_id')::uuid=pg_temp.rid('attachment-intent'));END$$;
SELECT set_config('storage.operation','object.upload',true);
SELECT pg_temp.check('completed replay creates no upload grant','REPLAY',NOT boss_private.comm_storage_insert('boss-communication-attachments',(SELECT result->>'object_name' FROM pg_temp.phase4a_comm_results WHERE label='attachment-intent'),'{"mimetype":"application/pdf","size":100}'::jsonb));
SELECT pg_temp.ok('attached-message','W',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Synthetic attachment message','attachment_ids',jsonb_build_array(pg_temp.rid('attachment-intent')))));
SELECT pg_temp.act('guardian');SELECT pg_temp.ok('attachment-access','W',pg_temp.cmd('attachment.access',jsonb_build_object('attachment_id',pg_temp.rid('attachment-intent'))));
SELECT set_config('storage.operation','object.get_authenticated',true);
SELECT pg_temp.check('exact leased authenticated bytes permitted','W',boss_private.comm_storage_select('boss-communication-attachments',(SELECT result->>'object_name' FROM pg_temp.phase4a_comm_results WHERE label='attachment-intent')));
SELECT set_config('storage.operation','object.get_authenticated_info',true);
SELECT pg_temp.check('exact leased authenticated info permitted','W',boss_private.comm_storage_select('boss-communication-attachments',(SELECT result->>'object_name' FROM pg_temp.phase4a_comm_results WHERE label='attachment-intent')));
DO $$DECLARE op text;BEGIN FOREACH op IN ARRAY ARRAY['object.sign','object.sign_many','object.list','object.get_public','object.copy','object.head',''] LOOP PERFORM set_config('storage.operation',op,true);PERFORM pg_temp.check('leased operation denied '||op,'W',NOT boss_private.comm_storage_select('boss-communication-attachments',(SELECT result->>'object_name' FROM pg_temp.phase4a_comm_results WHERE label='attachment-intent')));END LOOP;END$$;
SELECT pg_temp.act('household-only');SELECT pg_temp.deny('household attachment access denied','W',pg_temp.cmd('attachment.access',jsonb_build_object('attachment_id',pg_temp.rid('attachment-intent'))));
SELECT pg_temp.act('guardian');
SELECT pg_temp.check('safe read excludes private paths and DOB','SECURITY',NOT public.boss_communications_read(pg_temp.query('team-chat'))::text LIKE '%object_name%' AND NOT public.boss_communications_read(pg_temp.query('team-chat'))::text LIKE '%date_of_birth%');
RESET ROLE;
UPDATE public.organization_units SET status='inactive' WHERE id=pg_temp.f('unit-a');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('guardian');SELECT pg_temp.read_deny('inactive unit closes exact team context',pg_temp.query('team-chat'));
RESET ROLE;
UPDATE public.organization_units SET status='active' WHERE id=pg_temp.f('unit-a');
UPDATE public.guardian_relationships SET can_receive_communications=false,can_send_communications=false WHERE id=pg_temp.f('guardian-relation');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('guardian');
SELECT pg_temp.read_deny('revoked guardian loses historical team chat',pg_temp.query('team-chat'));
SELECT pg_temp.read_deny('revoked copied guardian closes minor group',pg_temp.query('minor-guardian-group'));
SELECT pg_temp.read_deny('revoked guardian loses family',pg_temp.query('family-chat'));
SELECT set_config('storage.operation','object.get_authenticated',true);
SELECT pg_temp.check('existing lease cannot survive guardian revoke','W',NOT boss_private.comm_storage_select('boss-communication-attachments',(SELECT result->>'object_name' FROM pg_temp.phase4a_comm_results WHERE label='attachment-intent')));
SELECT pg_temp.deny('retry rechecks revoked guardian','REPLAY',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Synthetic guardian reply')),ARRAY['PT403'],'guardian-message');
RESET ROLE;
UPDATE public.guardian_relationships SET can_receive_communications=true,can_send_communications=true WHERE id=pg_temp.f('guardian-relation');
UPDATE public.household_memberships SET status='inactive',ends_at=now() WHERE household_id=pg_temp.f('household') AND person_id=pg_temp.f('guardian');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('guardian');SELECT pg_temp.read_deny('family membership removal loses history',pg_temp.query('family-chat'));
RESET ROLE;
UPDATE public.team_memberships SET status='inactive',ends_at=now() WHERE team_id=pg_temp.f('team-a') AND person_id=pg_temp.f('child');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('guardian');SELECT pg_temp.read_deny('removed child roster loses guardian chat',pg_temp.query('team-chat'));
SELECT pg_temp.act('coach');SELECT pg_temp.deny('cannot attach already linked file twice','W',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Synthetic duplicate attachment','attachment_ids',jsonb_build_array(pg_temp.rid('attachment-intent')))));
DO $$DECLARE denied boolean;BEGIN BEGIN INSERT INTO public.communication_threads(organization_id,kind,title,scope_type,scope_id,created_by_person_id) VALUES(pg_temp.f('org-a'),'organization_staff','Direct denied','organization',pg_temp.f('org-a'),pg_temp.f('coach'));EXCEPTION WHEN insufficient_privilege THEN denied:=true;END;PERFORM pg_temp.check('direct authenticated writes denied','Z',denied);END$$;
RESET ROLE;
-- Disabled availability cannot survive through the organization selector.
CREATE TEMP TABLE phase4a_comm_feature_baseline AS SELECT id,configuration FROM public.organization_modules WHERE organization_id=pg_temp.f('org-a') AND module_id=(SELECT id FROM public.modules WHERE key='messaging');
UPDATE public.organization_modules SET configuration=jsonb_set(configuration,'{communications}','false'::jsonb) WHERE id IN(SELECT id FROM phase4a_comm_feature_baseline);
SET LOCAL ROLE authenticated;SELECT pg_temp.act('admin-a');
DO $$DECLARE r jsonb;BEGIN r:=public.boss_communications_read('{"view":"summary"}');PERFORM pg_temp.check('disabled communications summary has no organization thread or control','POLICY',jsonb_array_length(r->'organizations')=0 AND jsonb_array_length(r->'threads')=0 AND jsonb_array_length(r->'operations')=0);END$$;
SELECT pg_temp.read_deny('disabled communications explicit organization denied',jsonb_build_object('organization_id',pg_temp.f('org-a'),'view','summary'));
RESET ROLE;
UPDATE public.organization_modules m SET configuration=b.configuration FROM phase4a_comm_feature_baseline b WHERE m.id=b.id;
DROP TABLE phase4a_comm_feature_baseline;
-- One bounded fixture verifies the public error boundary without 30 RPC calls.
WITH advanced AS (UPDATE public.communication_threads SET next_sequence=next_sequence+30 WHERE id=pg_temp.rid('team-chat') RETURNING id,organization_id,next_sequence)
INSERT INTO public.communication_messages(organization_id,thread_id,author_person_id,body,sequence_number)
SELECT t.organization_id,t.id,pg_temp.f('admin-a'),'Synthetic rate-limit fixture',t.next_sequence-30+n FROM advanced t CROSS JOIN generate_series(1,30)n;
SET LOCAL ROLE authenticated;SELECT pg_temp.act('admin-a');
SELECT pg_temp.deny('rate-limit preserves public PT429','RATE',pg_temp.cmd('message.send',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'body','Synthetic rate-limited message')),ARRAY['PT429']);
RESET ROLE;
UPDATE public.organization_modules SET configuration=jsonb_set(configuration,'{moderation}','false'::jsonb) WHERE organization_id=pg_temp.f('org-a') AND module_id=(SELECT id FROM public.modules WHERE key='messaging');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('admin-a');
SELECT pg_temp.deny('moderator removal closes with disabled feature','POLICY',pg_temp.cmd('message.remove',jsonb_build_object('message_id',pg_temp.rid('coach-message'),'expected_version',1,'reason','Synthetic disabled-feature moderation')));
SELECT pg_temp.ok('announcement-own-removal','W',pg_temp.cmd('message.remove',jsonb_build_object('message_id',public.boss_communications_read(pg_temp.query('org-announcement'))->'detail'->'messages'->0->>'id','expected_version',1)));
SELECT pg_temp.deny('removed announcement cannot acquire orphan upload','W',pg_temp.cmd('attachment.intent',jsonb_build_object('thread_id',pg_temp.rid('org-announcement'),'file_name','synthetic-removed.pdf','mime_type','application/pdf','size_bytes',100,'content_sha256',repeat('c',64))));
RESET ROLE;
UPDATE public.role_assignments SET status='inactive',ends_at=now() WHERE person_id=pg_temp.f('admin-a') AND organization_id=pg_temp.f('org-a');
SET LOCAL ROLE authenticated;SELECT pg_temp.act('admin-a');
SELECT pg_temp.deny('completed intent replay rechecks removed authority','REPLAY',pg_temp.cmd('attachment.intent',jsonb_build_object('thread_id',pg_temp.rid('team-chat'),'file_name','synthetic.pdf','mime_type','application/pdf','size_bytes',100,'content_sha256',repeat('a',64))),ARRAY['PT403'],'attachment-intent');
RESET ROLE;
DO $$DECLARE k text;p text;BEGIN FOREACH k IN ARRAY ARRAY['communications.view','communications.send','communications.manage','announcements.send','team_chat.view','team_chat.send','moderation.manage'] LOOP
 PERFORM pg_temp.check('finance lacks '||k,'PERMISSIONS',NOT EXISTS(SELECT 1 FROM public.role_permissions rp JOIN public.roles r ON r.id=rp.role_id JOIN public.permissions perm ON perm.id=rp.permission_id WHERE r.key IN('finance','organization_finance') AND perm.key=k));END LOOP;END$$;
SELECT category,count(*) AS passed_assertions FROM pg_temp.phase4a_comm_assertions GROUP BY category ORDER BY category;
SELECT count(*) AS passed_assertions FROM pg_temp.phase4a_comm_assertions;
ROLLBACK;
