\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase8a/fixture.sql
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.denied('missing profile version cannot bypass concurrency','select pg_temp.mm(''missing-version'',''merchant.edit'',pg_temp.mi(''{"name":"FORGED"}''))','PT422');
select pg_temp.actor('coach');
select pg_temp.denied('missing location version cannot bypass concurrency','select pg_temp.mm(''missing-location-version'',''location.edit'',pg_temp.mi(jsonb_build_object(''location_id'',pg_temp.mid(''loc-a''),''status'',''paused'')))','PT422');
select pg_temp.actor('parent');
select pg_temp.denied('forged revision from another resource unavailable','select pg_temp.mm(''foreign-rev'',''intent.create'',pg_temp.mi(jsonb_build_object(''location_id'',pg_temp.mid(''loc-a''),''revision_id'',pg_temp.mid(''loc-a''),''capability'',pg_temp.proof(''foreign''))))','PT404');
select pg_temp.denied('forged merchant cannot borrow published revision','select pg_temp.mm(''foreign-merchant'',''intent.create'',jsonb_build_object(''merchant_id'',pg_temp.mid(''merchant-other'',''merchant_id''),''location_id'',pg_temp.mid(''loc-a''),''revision_id'',pg_temp.mid(''offer''),''capability'',pg_temp.proof(''foreign-m'')))','PT404');
select pg_temp.actor('admin');
select pg_temp.denied('control character persisted through direct signed RPC rejected','select pg_temp.mm(''control'',''merchant.edit'',pg_temp.mi(jsonb_build_object(''expected_version'',3,''name'',''bad''||chr(1))))','PT422');
select pg_temp.mm('category','category.configure','{"key":"synthetic_added","name":"Synthetic configured category","status":"active"}');
select pg_temp.check('configured category available from safe directory','CATEGORY',(public.boss_merchants_directory('{}')->'categories')::text like'%synthetic_added%');
select pg_temp.mm('no-loc','staff.grant',pg_temp.mi(jsonb_build_object('person_id',pg_temp.f('director'),'role','support_reviewer')));
select pg_temp.actor('director');
select pg_temp.check('exact support reviewer can see assigned merchant','REVIEW',(public.boss_merchants_read(pg_temp.mi('{"mode":"portal"}'))->'merchant'->>'id')=pg_temp.mid('merchant','merchant_id')::text);
select pg_temp.denied('support reviewer cannot edit business profile','select pg_temp.mm(''reviewer-profile'',''merchant.edit'',pg_temp.mi(''{"expected_version":3,"name":"FORGED"}''))');
select pg_temp.denied('reviewer has no unrelated merchant access','select public.boss_merchants_read(jsonb_build_object(''mode'',''portal'',''merchant_id'',pg_temp.mid(''merchant-other'',''merchant_id'')))');
select pg_temp.actor('admin');select pg_temp.mm('end-reviewer','staff.end',pg_temp.mi(jsonb_build_object('assignment_id',pg_temp.mid('no-loc'))));
select pg_temp.actor('director');select pg_temp.denied('ended staff reviewer cannot read stale portal','select public.boss_merchants_read(pg_temp.mi(''{"mode":"portal"}''))');
reset role;update public.roles set status='inactive'where key='redemption_clerk';
select pg_temp.check('inactive role removes capability','CATALOG',not boss_private.merchant_can(pg_temp.f('staff'),'merchant_redemptions.manage',pg_temp.mid('merchant','merchant_id'),pg_temp.mid('loc-a')));
update public.roles set status='active'where key='redemption_clerk';update public.permissions set status='inactive'where key='merchant_redemptions.manage';
select pg_temp.check('inactive permission removes capability','CATALOG',not boss_private.merchant_can(pg_temp.f('staff'),'merchant_redemptions.manage',pg_temp.mid('merchant','merchant_id'),pg_temp.mid('loc-a')));
update public.permissions set status='active'where key='merchant_redemptions.manage';update auth.users set banned_until=clock_timestamp()+interval'1 day'where id=pg_temp.f('auth-staff');
select pg_temp.check('banned Auth identity cannot exercise merchant grant','IDENTITY',not boss_private.merchant_can(pg_temp.f('staff'),'merchant_redemptions.manage',pg_temp.mid('merchant','merchant_id'),pg_temp.mid('loc-a')));
update auth.users set banned_until=null where id=pg_temp.f('auth-staff');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.mo('shared','{"location_policy":"all_current"}');
select pg_temp.actor('scorer');select pg_temp.denied('local offer editor cannot mutate multi-location corporate revision','select pg_temp.mm(''scope-escalation'',''offer.status'',pg_temp.mi(jsonb_build_object(''location_id'',pg_temp.mid(''loc-a''),''revision_id'',pg_temp.mid(''shared''),''state'',''paused'')))');
select pg_temp.check('portal default link retains exact location','SCOPE',(public.boss_merchants_read('{"mode":"portal"}')->'merchants'->0->>'preferred_location_id')=pg_temp.mid('loc-a')::text);
select pg_temp.actor('parent');
select pg_temp.mm('pause','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('offer'),'state','paused')));
select pg_temp.mm('resubmit','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('offer'),'state','pending_review')));
select pg_temp.actor('admin');select pg_temp.mm('resume','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('offer'),'state','published','reason','Independent reviewed resume of existing terms')));
reset role;
select pg_temp.check('reviewed resume preserves family and usage policy','CONTINUITY',boss_private.merchant_offer_state(pg_temp.mid('offer'))='published'and(select usage_limit=2 from public.merchant_offer_families where id=pg_temp.mid('family')));
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.mm('pause-local','offer.local',pg_temp.mi(jsonb_build_object('family_id',pg_temp.mid('family'),'location_id',pg_temp.mid('loc-a'),'paused',true,'presentation_note','Synthetic local presentation')));
select pg_temp.actor('parent');select pg_temp.mo('corporate-no-pause','{"allow_local_pause":false}');
select pg_temp.mm('no-pause-submit','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('corporate-no-pause'),'state','pending_review')));
select pg_temp.actor('admin');select pg_temp.mm('no-pause-publish','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('corporate-no-pause'),'state','published','reason','Reviewed corporate policy disables local pause')));
select pg_temp.actor('coach');
select pg_temp.denied('archived local policy grants no override on current revision','select pg_temp.mm(''old-policy'',''offer.local'',pg_temp.mi(jsonb_build_object(''family_id'',pg_temp.mid(''family''),''location_id'',pg_temp.mid(''loc-a''),''paused'',true)))');
reset role;
select pg_temp.check('corporate policy controls old local configuration residue','POLICY',boss_private.merchant_available(pg_temp.mid('corporate-no-pause'),pg_temp.mid('loc-a')));
select pg_temp.check('private selector helper closed','ACL',not has_function_privilege('anon','boss_merchants_public.options(jsonb)','EXECUTE'));
set constraints all immediate;
select count(*)passed_assertions,'Phase 8A current role source resource review and stale-version denial'::text suite from phase5a_assertions;rollback;
