\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase8b1/fixture.sql
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.feed('repeat-new-request',1,'delta',(select jsonb_build_array(item)from partner_payloads));
select pg_temp.check('feed replay has one result','IDEMPOTENCY',(select result->>'resource_id'from partner_results where label='feed')=(select result->>'resource_id'from partner_results where label='repeat-new-request'));
select pg_temp.denied('changed feed same sequence conflict',format('select pg_temp.feed(''conflict'',1,''delta'',%L)',jsonb_build_array(pg_temp.item('other'))),'PT409');
select pg_temp.denied('old feed cannot replace current',format('select pg_temp.feed(''old-feed'',0,''delta'',%L)','[]'::jsonb),'PT409');
select pg_temp.feed('partial',2,'full',jsonb_build_array(pg_temp.item('valid-2'),pg_temp.item('invalid-2',1,'{"category":"forged"}')));
reset role;
select pg_temp.check('valid item survives invalid peer','IMPORT',(select accepted=1 and quarantined=1 and withdrawn=0 from public.partner_import_runs where id=pg_temp.pid('partial')));
select pg_temp.check('invalid full does not withdraw omitted source','IMPORT',(select status='available'from public.partner_benefit_sources where id=pg_temp.pid('source')));
select pg_temp.check('quarantine holds no raw body or terms','PRIVACY',not exists(select 1 from information_schema.columns where table_name='partner_import_quarantine'and column_name in('payload','raw_body','member_terms')));
select pg_temp.check('provider namespace unique','NAMESPACE',(select count(*)=1 from public.partner_benefit_sources where provider_id=pg_temp.pid('provider')and external_id='benefit-1'));
set local role authenticated;
select pg_temp.feed('higher',3,'delta',(select jsonb_build_array(item||'{"source_revision":2,"member_terms":"Synthetic changed immutable terms"}')from partner_payloads));
select pg_temp.feed('older',4,'delta',(select jsonb_build_array(item)from partner_payloads));
select pg_temp.feed('same-revision-conflict',5,'delta',(select jsonb_build_array(item||'{"source_revision":2,"member_terms":"Conflicting synthetic terms"}')from partner_payloads));
reset role;
select pg_temp.check('two immutable revisions','REVISION',(select count(*)=2 from public.partner_benefit_revisions where source_id=pg_temp.pid('source')));
select pg_temp.check('old terms survive','REVISION',(select member_terms='Synthetic private ten percent terms'from public.partner_benefit_revisions where id=pg_temp.pid('benefit')));
select pg_temp.check('out of order quarantined','REVISION',(select category='out_of_order'from public.partner_import_quarantine where run_id=pg_temp.pid('older')));
select pg_temp.check('same revision conflict quarantined','REVISION',(select category='revision_conflict'from public.partner_import_quarantine where run_id=pg_temp.pid('same-revision-conflict')));
select pg_temp.check('higher revision blocks old reviewed visibility','REVISION',not(boss_private.partner_decision(pg_temp.f('parent'),pg_temp.pid('benefit'),pg_temp.mid('market','market_id'))->>'catalog_available')::boolean);
set local role authenticated;select pg_temp.feed('empty-delta',6,'delta','[]');reset role;
select pg_temp.check('delta omission retained','FEED',(select status='available'from public.partner_benefit_sources where id=pg_temp.pid('source')));
set local role authenticated;select pg_temp.pm('snapshot','catalog.snapshot.begin',pg_temp.pi('{"expected_items":2}'));
select pg_temp.pm('page-1','catalog.import',pg_temp.pi(jsonb_build_object('feed_sequence',7,'kind','full','synthetic',true,'snapshot_id',pg_temp.pid('snapshot'),'items',jsonb_build_array(pg_temp.item('page-1')))));
select pg_temp.denied('unfinished snapshot cannot withdraw',format('select pg_temp.pm(''early-complete'',''catalog.snapshot.complete'',%L)',pg_temp.pi(jsonb_build_object('snapshot_id',pg_temp.pid('snapshot')))),'PT409');
select pg_temp.denied('delta cannot interleave unfinished snapshot',format('select pg_temp.feed(''interleave'',8,''delta'',%L)','[]'::jsonb),'PT409');
select pg_temp.pm('page-2','catalog.import',pg_temp.pi(jsonb_build_object('feed_sequence',8,'kind','full','synthetic',true,'snapshot_id',pg_temp.pid('snapshot'),'items',jsonb_build_array(pg_temp.item('page-2')))));
select pg_temp.pm('complete','catalog.snapshot.complete',pg_temp.pi(jsonb_build_object('snapshot_id',pg_temp.pid('snapshot'))));reset role;
select pg_temp.check('paged completion withdraws omitted only','FEED',(select status='withdrawn'from public.partner_benefit_sources where id=pg_temp.pid('source')));
select pg_temp.check('completed pages retained','FEED',(select count(*)=2 from public.partner_benefit_sources where provider_id=pg_temp.pid('provider')and status='available'));
set local role authenticated;select pg_temp.pm('bad-snapshot','catalog.snapshot.begin',pg_temp.pi('{"expected_items":1}'));
select pg_temp.pm('bad-page','catalog.import',pg_temp.pi(jsonb_build_object('feed_sequence',9,'kind','full','synthetic',true,'snapshot_id',pg_temp.pid('bad-snapshot'),'items',jsonb_build_array(pg_temp.item('bad-page',1,'{"country":"forged"}')))));
select pg_temp.denied('all-invalid snapshot cannot complete',format('select pg_temp.pm(''bad-complete'',''catalog.snapshot.complete'',%L)',pg_temp.pi(jsonb_build_object('snapshot_id',pg_temp.pid('bad-snapshot')))),'PT409');
select pg_temp.pm('abort','catalog.snapshot.abort',pg_temp.pi(jsonb_build_object('snapshot_id',pg_temp.pid('bad-snapshot'))));
select pg_temp.feed('empty-full',10,'full','[]');reset role;
select pg_temp.check('explicit full empty withdraws all','FEED',not exists(select 1 from public.partner_benefit_sources where provider_id=pg_temp.pid('provider')and status='available'));
select pg_temp.check('historical terms retained after withdrawal','HISTORY',(select count(*)=5 from public.partner_benefit_revisions where provider_id=pg_temp.pid('provider')));
update public.partner_benefit_sources set status='available',last_verified_at=clock_timestamp()-interval'2 days'where id=pg_temp.pid('source');
select pg_temp.check('stale catalog fails closed','FRESHNESS',not(boss_private.partner_decision(pg_temp.f('parent'),pg_temp.pid('benefit'),pg_temp.mid('market','market_id'))->>'catalog_available')::boolean);
select pg_temp.denied('history deletion forbidden','delete from public.partner_providers','23514');
set constraints all immediate;
select count(*)passed_assertions,'Phase 8B1 catalog ingestion/revisions/freshness'::text suite from phase5a_assertions;rollback;
