begin;
\ir phase5f/fixture.sql
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.dd_create('aggregate','baseball','essential');
select public.boss_stat_competition_classify(pg_temp.ff_game('aggregate'),'official','Synthetic controlled disposable official fixture',md5('phase6a-classify')::uuid);
-- One complete inning each side, no runs; real Diamond final seals.
do $$declare half int;i int;begin
perform pg_temp.dd_pa('aggregate','agg-home-run');perform pg_temp.dd_play('aggregate','home_run',jsonb_build_array(pg_temp.dd_move(0,4)));
for half in 1..2 loop
for i in 1..3 loop perform pg_temp.dd_pa('aggregate','agg-'||half||'-'||i);perform pg_temp.dd_play('aggregate','other_out',jsonb_build_array(pg_temp.dd_move(0,null,'advance_on_play',false,true)));end loop;
if half=1 then perform pg_temp.dd_op('diamond.half.start','aggregate','{"payload":{"kind":"half_start"}}');end if;end loop;
perform pg_temp.game_op('game.finalize','aggregate');end$$;
reset role;
select boss_private.stat_refresh(pg_temp.ff_game('aggregate'));
select pg_temp.check('current final contributes exactly once','EPOCH',(select count(*)=1 from public.stat_game_selections where game_id=pg_temp.ff_game('aggregate')and finalization_id is not null));
select pg_temp.check('official classification bound to epoch in same transaction','CLASSIFICATION',(select bool_and(classification='official')from public.stat_game_contributions where game_id=pg_temp.ff_game('aggregate')));
select pg_temp.check('both sealed team rows retained','SOURCE',(select count(*)=2 from public.stat_game_contributions where game_id=pg_temp.ff_game('aggregate')and roster_id is null));
select pg_temp.check('season from canonical game','SEASON',(select bool_and(c.season_id is not distinct from g.season_id)from public.stat_game_contributions c join public.games g on g.id=c.game_id where g.id=pg_temp.ff_game('aggregate')));
select pg_temp.check('confirmed PA player GP','GP',(select (participation->>'confirmed')::boolean from public.stat_game_contributions where game_id=pg_temp.ff_game('aggregate')and roster_id=pg_temp.ff_roster('aggregate','primary',1)));
select pg_temp.check('unused bench not fabricated GP','GP',(select not(participation->>'confirmed')::boolean from public.stat_game_contributions where game_id=pg_temp.ff_game('aggregate')and roster_id=pg_temp.ff_roster('aggregate','primary',5)));
select pg_temp.check('team scoring measured zero','ZERO',(select (summary->'metrics'->'scoring_against'->>'complete_value')::numeric=0 from public.stat_origin_summaries where team_id=pg_temp.f('falcons')and person_id is null and sport_key='baseball'));
select pg_temp.check('repeat refresh no generation increment','REPLAY',(select generation=1 from public.stat_origin_summaries where team_id=pg_temp.f('falcons')and person_id is null and sport_key='baseball'));
select boss_private.stat_refresh(pg_temp.ff_game('aggregate'));
select pg_temp.check('repeat refresh no double count','REPLAY',(select(summary->>'source_game_count')::int=1 from public.stat_origin_summaries where team_id=pg_temp.f('falcons')and person_id is null and sport_key='baseball'));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.game_op('game.reopen','aggregate','{"reason":"Synthetic aggregate reopen"}');
reset role;select boss_private.stat_refresh(pg_temp.ff_game('aggregate'));
select pg_temp.check('reopen removes selected epoch','EPOCH',(select finalization_id is null from public.stat_game_selections where game_id=pg_temp.ff_game('aggregate')));
select pg_temp.check('reopen removes current aggregate','EPOCH',(select(summary->>'source_game_count')::int=0 from public.stat_origin_summaries where team_id=pg_temp.f('falcons')and person_id is null and sport_key='baseball'));
select pg_temp.check('old contribution remains immutable history','HISTORY',(select count(*)>0 from public.stat_game_contributions where game_id=pg_temp.ff_game('aggregate')));
set local role authenticated;select pg_temp.actor('admin');select pg_temp.game_op('game.finalize','aggregate');reset role;
select boss_private.stat_refresh(pg_temp.ff_game('aggregate'));
select pg_temp.check('new epoch replaces sole current contribution','EPOCH',(select(summary->>'source_game_count')::int=1 from public.stat_origin_summaries where team_id=pg_temp.f('falcons')and person_id is null and sport_key='baseball'));
select pg_temp.check('two immutable contribution epochs','HISTORY',(select count(distinct epoch)=2 from public.stat_game_contributions where game_id=pg_temp.ff_game('aggregate')));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('guardian authorized career','AUTH',(public.boss_athlete_career_read(jsonb_build_object('person_id',pg_temp.f('child1'),'sport_key','baseball'))->'summary'->>'source_game_count')::int=1);
select pg_temp.denied('unrelated child denied','select public.boss_athlete_career_read(jsonb_build_object(''person_id'',pg_temp.f(''child2''),''sport_key'',''baseball''))','PT403');
reset role;
reset role;
select pg_temp.denied('sealed season cannot be silently reassigned',format('update public.games set season_id=null where id=%L',pg_temp.ff_game('aggregate')),'23514');
select pg_temp.denied('immutable contribution cannot be edited',format('update public.stat_game_contributions set components=''{}'' where game_id=%L',pg_temp.ff_game('aggregate')),'23514');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.denied('finalized classification requires refinalization',format('select public.boss_stat_competition_classify(%L,''excluded'',''Synthetic forbidden finalized change'',gen_random_uuid())',pg_temp.ff_game('aggregate')),'PT409');
reset role;
select pg_temp.check('administrator has no private child history override','PRIVACY',(select not boss_private.games_person_related(pg_temp.f('admin'),pg_temp.f('child1'))));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.denied('administrator private career bypass denied','select public.boss_athlete_career_read(jsonb_build_object(''person_id'',pg_temp.f(''child1''),''sport_key'',''baseball''))','PT403');
reset role;
create temp table rebuild_before as select summary from public.stat_origin_summaries where team_id=pg_temp.f('falcons')and person_id is null and sport_key='baseball';
set local role authenticated;select pg_temp.actor('admin');
select public.boss_stat_rebuild(jsonb_build_object('organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'sport_key','baseball'),'team_season');
reset role;
select pg_temp.check('rebuild equals incremental summary','REBUILD',(select summary=(select summary from rebuild_before)from public.stat_origin_summaries where team_id=pg_temp.f('falcons')and person_id is null and sport_key='baseball'));
-- Explicit originating slices never authorize an all-team career projection.
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.check('origin administrator exact athlete team-season allowed','AUTH',(public.boss_athlete_season_read(jsonb_build_object('organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'person_id',pg_temp.f('child1'),'sport_key','baseball'))->'summary'->>'source_game_count')::int=1);
select pg_temp.denied('new organization receives no prior-origin aggregate',format('select public.boss_athlete_season_read(%L::jsonb)',jsonb_build_object('organization_id',pg_temp.f('other-org'),'team_id',pg_temp.f('other-team'),'season_id',pg_temp.f('season'),'person_id',pg_temp.f('child1'),'sport_key','baseball')),'PT403');
select pg_temp.denied('forged rebuild cursor denied',format('select public.boss_stat_rebuild(%L::jsonb,''team_season'',%L)',jsonb_build_object('organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'sport_key','baseball'),gen_random_uuid()),'PT422');
reset role;
-- Ending a child's membership does not mutate source identity or guardian history.
update public.team_memberships set status='inactive',ends_at=clock_timestamp()where person_id=pg_temp.f('child1')and team_id=pg_temp.f('falcons');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('guardian aggregate survives membership end','TRANSFER',(public.boss_athlete_career_read(jsonb_build_object('person_id',pg_temp.f('child1'),'sport_key','baseball'))->'summary'->>'confirmed_gp')::int=1);
reset role;
update public.events set visibility='private'where id=(select event_id from public.games where id=pg_temp.ff_game('aggregate'));
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.denied('origin team cannot bypass private source-game visibility',format('select public.boss_team_season_read(%L::jsonb)',jsonb_build_object('organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'sport_key','baseball')),'PT403');
reset role;
update public.organization_modules set configuration=jsonb_set(configuration,'{baseball_stats}','false')where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='sports');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.denied('disabled sport statistics cannot be bypassed by team aggregate',format('select public.boss_team_season_read(%L::jsonb)',jsonb_build_object('organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'sport_key','baseball')),'PT403');
reset role;
update public.organization_modules set configuration=jsonb_set(configuration,'{baseball_stats}','true')where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='sports');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.denied('null rebuild kind rejected before work',format('select public.boss_stat_rebuild(%L::jsonb,null)',jsonb_build_object('organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'sport_key','baseball')),'PT422');
reset role;
select count(*)passed_assertions from pg_temp.phase5a_assertions;
rollback;
