\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase7a/fixture.sql
set local role anon;
select pg_temp.check('leaderboards disabled by default','PRIVACY',public.boss_fundraising_public(pg_temp.fpath('share'))->'leaderboard'='[]');reset role;
update public.fundraising_campaigns set leaderboard_visibility='public'where id=pg_temp.fid('campaign');
set local role anon;
select pg_temp.check('organization enable never substitutes for guardian opt-in','PRIVACY',not exists(select 1 from jsonb_array_elements(public.boss_fundraising_public(pg_temp.fpath('share'))->'leaderboard')x where x->>'kind'='participant'));reset role;
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.fm('fundraiser.accept',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'fundraiser_id',pg_temp.fid('fundraiser'),'display_name','Approved synthetic name','leaderboard_opt_in',true));reset role;
set local role anon;
select pg_temp.check('approved opt-in leaderboard finite','PRIVACY',exists(select 1 from jsonb_array_elements(public.boss_fundraising_public(pg_temp.fpath('share'))->'leaderboard')x where x->>'name'='Approved synthetic name')and(public.boss_fundraising_public(pg_temp.fpath('share'))->'leaderboard')::text!~'(_id|email|household|date_of_birth)');reset role;
update public.guardian_relationships set can_manage_fundraising=false where id=pg_temp.f('guardian-child1');
select pg_temp.check('revoked guardian removes public leaderboard name','PRIVACY',not exists(select 1 from jsonb_array_elements(boss_private.fundraising_leaderboard(pg_temp.fid('campaign')))x where x->>'kind'='participant'));
update public.guardian_relationships set can_manage_fundraising=true where id=pg_temp.f('guardian-child1');
set local role authenticated;select pg_temp.actor('program');
select pg_temp.check('exact program campaign filter usable','SCOPE',jsonb_array_length(public.boss_fundraising_read(jsonb_build_object('organization_id',pg_temp.f('org'),'unit_id',pg_temp.f('unit')))->'campaigns')=0);
select pg_temp.denied('unrelated program denied',format('select public.boss_fundraising_read(%L::jsonb)',jsonb_build_object('organization_id',pg_temp.f('org'),'unit_id',pg_temp.f('sibling-unit'))),'PT403');
select pg_temp.actor('coach');
select pg_temp.check('team leader can choose only exact team scope','SCOPE',(public.boss_fundraising_read(jsonb_build_object('organization_id',pg_temp.f('org'),'scopes_only',true))->'catalog'->'teams')=jsonb_build_array(jsonb_build_object('id',pg_temp.f('falcons'),'name','Synthetic Falcons')));
select pg_temp.denied('team leader raw extra board fields rejected',format('select public.boss_fundraising_mutate(%L::jsonb)',jsonb_build_object('action','share.create','request_id',gen_random_uuid(),'input',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'fundraiser_id',pg_temp.fid('fundraiser'),'amount_minor',1))),'PT422');
reset role;set local role anon;
select public.boss_fundraising_support(jsonb_build_object('action','reserve','request_id',gen_random_uuid(),'input',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',1,'capability',repeat('d',64))));
select public.boss_fundraising_support(jsonb_build_object('action','intent','request_id',gen_random_uuid(),'input',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',1,'capability',repeat('d',64),'display_name','Synthetic monthly supporter','months',6)));
select public.boss_fundraising_support(jsonb_build_object('action','release','request_id',gen_random_uuid(),'input',jsonb_build_object('path',pg_temp.fpath('share'),'capability',repeat('d',64))));reset role;
select pg_temp.check('release cancels planned monthly commitment without value','RECURRING',(select bool_and(status='canceled')from public.fundraising_recurring_commitments)and not exists(select 1 from public.fundraising_success_evidence));
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.fm('board.configure',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'board_id',pg_temp.fid('board'),'expected_version',3,'title','Updated synthetic board','goal_minor',100000,'start_minor',500,'increment_minor',500,'tile_count',100001,'reservation_seconds',480,'visibility','public'));
select pg_temp.check('tested size is not a product cap; generation bounded','GENERATION',(public.boss_fundraising_read(jsonb_build_object('organization_id',pg_temp.f('org')))->'campaigns'->0->'fundraisers'->0->'board'->>'generated_count')::int=10000);
select pg_temp.conflict('partial generation cannot be published',format('select public.boss_fundraising_mutate(%L::jsonb)',jsonb_build_object('action','board.publish','request_id',gen_random_uuid(),'input',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'board_id',pg_temp.fid('board'),'expected_version',4))));
select pg_temp.fm('board.generate',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'board_id',pg_temp.fid('board'),'expected_version',4));
reset role;
select pg_temp.check('same generation extended not regenerated','GENERATION',(select count(*)=2 from public.money_board_generations where board_id=pg_temp.fid('board'))and(select count(*)=20000 from public.money_board_tiles where generation_id=(select id from public.money_board_generations where board_id=pg_temp.fid('board')order by generation desc limit 1)));
set local role anon;
select public.boss_fundraising_support(jsonb_build_object('action','intent','request_id',pg_temp.f('revoked-source-request'),'input',jsonb_build_object('path',pg_temp.fpath('share'),'capability',repeat('c',64),'display_name','Synthetic supporter','amount_minor',2501)));reset role;
update public.fundraising_fundraisers set status='ended'where id=pg_temp.fid('fundraiser');
select pg_temp.denied('trusted success cannot use ended participation',format('select boss_private.fundraising_ingest_success(%L::uuid,%L,%L,2501,%L,%L::timestamptz)',(select id from public.fundraising_intents where request_id=pg_temp.f('revoked-source-request')),'disposable','revoked','USD',clock_timestamp()),'PT409');
select pg_temp.check('denied trusted evidence creates no value','PROVENANCE',not exists(select 1 from public.fundraising_success_evidence where intent_id=(select id from public.fundraising_intents where request_id=pg_temp.f('revoked-source-request'))));
select count(*)passed_assertions from pg_temp.phase5a_assertions;rollback;
