-- Pure reducer oracle and tracking contract. Disposable PostgreSQL only.
begin;
\ir phase5a/fixture.sql
create temp table vv_state(c jsonb,s jsonb);
insert into vv_state(c)values('{"best_of":3,"normal_target":3,"deciding_target":2,"win_by_two":true,"court_size":2,"strict_rotation":true,"enforce_lineup":true,"allow_reentry":false,"libero_enabled":false,"libero_can_serve":false,"substitution_limit":1}');
update vv_state set s=boss_private.volleyball_initial(c);
update vv_state set s=boss_private.volleyball_transition(c,s,'lineup_set','primary','{"roster_ids":["p1","p2"]}');
update vv_state set s=boss_private.volleyball_transition(c,s,'lineup_set','opponent','{"roster_ids":["o1","o2"]}');
update vv_state set s=boss_private.volleyball_transition(c,s,'set_start','primary','{}');
update vv_state set s=boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"kill","roster_id":"p2"}');
select pg_temp.check('known strict server supports team-only service fact','ORACLE',(select boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"ace"}')->>'primary_points'='2'from vv_state));
select pg_temp.check('first kill one point','ORACLE',(select s->>'primary_points'='1'and s->>'serving_side'='primary'from vv_state));
update vv_state set s=boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"attack_error","roster_id":"p2"}');
select pg_temp.check('sideout rotates receiving winner','ORACLE',(select s->'lineups'->'opponent'='["o2","o1"]'and s->>'serving_side'='opponent'from vv_state));
select pg_temp.denied('wrong server','select boss_private.volleyball_transition(c,s,''rally'',''opponent'',''{"outcome":"ace","roster_id":"o1"}'')from vv_state','PT409');
update vv_state set s=boss_private.volleyball_transition(c,s,'rally','opponent','{"outcome":"service_error","roster_id":"o2"}');
update vv_state set s=boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"ace","roster_id":"p2"}');
select pg_temp.check('set winner 3-1 preserved','ORACLE',(select s->'sets'='[{"number":1,"primary_points":3,"opponent_points":1,"winner":"primary","deciding":false}]'and s->>'primary_sets'='1'and s->>'set_status'='completed'from vv_state));
select pg_temp.denied('completed set cannot accept another rally','select boss_private.volleyball_transition(c,s,''rally'',''primary'',''{"outcome":"team_point"}'')from vv_state','PT409');
update vv_state set s=boss_private.volleyball_transition(c,s,'set_start','opponent','{}');
update vv_state set s=boss_private.volleyball_transition(c,s,'rally','opponent','{"outcome":"team_point"}');
update vv_state set s=boss_private.volleyball_transition(c,s,'rally','opponent','{"outcome":"team_point"}');
update vv_state set s=boss_private.volleyball_transition(c,s,'rally','opponent','{"outcome":"team_point"}');
update vv_state set s=boss_private.volleyball_transition(c,s,'set_start','primary','{}');
update vv_state set s=boss_private.volleyball_transition(c,s,'substitution','primary','{"out_roster_id":"p2","in_roster_id":"p3"}');
select pg_temp.denied('substitution limit','select boss_private.volleyball_transition(c,s,''substitution'',''primary'',''{"out_roster_id":"p1","in_roster_id":"p4"}'')from vv_state','PT409');
update vv_state set s=boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"team_point"}');
update vv_state set s=boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"team_point"}');
select pg_temp.check('deciding target 2 and match sets 2-1','ORACLE',(select s->>'set_status'='match_complete'and s->>'primary_sets'='2'and s->>'opponent_sets'='1'and jsonb_array_length(s->'sets')=3 and s->'sets'->2->>'deciding'='true'from vv_state));
select pg_temp.denied('match cannot start fourth set','select boss_private.volleyball_transition(c,s,''set_start'',''primary'',''{}'')from vv_state','PT409');
select pg_temp.denied('null kind fails closed','select boss_private.volleyball_transition(c,s,null,''primary'',''{}'')from vv_state','PT422');
select pg_temp.denied('null side fails closed','select boss_private.volleyball_transition(c,s,''rally'',null,''{}'')from vv_state','PT422');
select pg_temp.check('no attempt hitting null','ORACLE',boss_private.volleyball_stat_projection('{"kills":0,"attack_errors":0,"attack_attempts":0}')->'hitting_percentage'='null');
select pg_temp.check('hitting literal oracle','ORACLE',boss_private.volleyball_stat_projection('{"kills":5,"attack_errors":2,"attack_attempts":10}')->>'hitting_percentage'='0.300000');
select pg_temp.check('required survive score only','PROFILE',(boss_private.tracking_selection('volleyball','score_only')->'enabled')?'rally');
select pg_temp.check('custom dependency closure','PROFILE',(boss_private.tracking_selection('volleyball','custom','["assists"]')->'enabled')?&array['assists','kills','attack_attempts']);
select pg_temp.check('quick order','PROFILE',boss_private.tracking_selection('volleyball','custom','["kills","digs"]','["digs","kills"]')->'quick'='["digs","kills"]');
select pg_temp.denied('wrong-sport tracking key','select boss_private.tracking_selection(''volleyball'',''custom'',''["passing_yards"]'')','PT422');
select pg_temp.denied('unavailable advanced metric','select boss_private.tracking_selection(''volleyball'',''custom'',''["passing_rating"]'')','PT422');
select pg_temp.denied('disabled quick','select boss_private.tracking_selection(''volleyball'',''score_only'',''[]'',''["digs"]'')','PT422');
select pg_temp.denied('duplicate quick','select boss_private.tracking_selection(''volleyball'',''custom'',''["digs"]'',''["digs","digs"]'')','PT422');
-- Literal format/policy outcomes beyond the main best-of-three oracle.
do $$declare c jsonb;s jsonb;side text;j int;i int;begin
 c:='{ "best_of":5,"normal_target":3,"deciding_target":2,"win_by_two":true,"court_size":2,"strict_rotation":false,"enforce_lineup":false,"allow_reentry":false,"libero_enabled":false,"libero_can_serve":false}';
 s:=boss_private.volleyball_initial(c);
 for j in 1..5 loop side:=case when j in(2,4)then'opponent'else'primary'end;s:=boss_private.volleyball_transition(c,s,'set_start',side,'{}');
 for i in 1..case when j=5 then 2 else 3 end loop s:=boss_private.volleyball_transition(c,s,'rally',side,'{"outcome":"team_point"}');end loop;
 perform pg_temp.check('best5 set '||j||' ends exactly','FORMAT',s->>'set_status'=case when j=5 then'match_complete'else'completed'end);
 end loop;
 perform pg_temp.check('best5 deciding score3-2','FORMAT',s->>'primary_sets'='3'and s->>'opponent_sets'='2'and s->'sets'->4->>'primary_points'='2');
 c:=c||'{"best_of":3,"score_cap":4}';s:=boss_private.volleyball_initial(c);s:=boss_private.volleyball_transition(c,s,'set_start','primary','{}');
 for i in 1..3 loop s:=boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"team_point"}');s:=boss_private.volleyball_transition(c,s,'rally','opponent','{"outcome":"team_point"}');end loop;
 perform pg_temp.check('3-3 win2 remains active','CAP',s->>'set_status'='active');s:=boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"team_point"}');
 perform pg_temp.check('explicit cap ends4-3','CAP',s->>'set_status'='completed'and s->'sets'->0->>'opponent_points'='3');
 c:=(c-'score_cap')||'{"win_by_two":false}';s:=boss_private.volleyball_initial(c);s:=boss_private.volleyball_transition(c,s,'set_start','primary','{}');
 for i in 1..2 loop s:=boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"team_point"}');s:=boss_private.volleyball_transition(c,s,'rally','opponent','{"outcome":"team_point"}');end loop;
 s:=boss_private.volleyball_transition(c,s,'rally','primary','{"outcome":"team_point"}');perform pg_temp.check('win1 ends3-2','FORMAT',s->>'set_status'='completed');
end$$;
create temp table vv_libero(c jsonb,s jsonb);
insert into vv_libero(c)values('{"best_of":3,"normal_target":25,"deciding_target":15,"win_by_two":true,"court_size":2,"strict_rotation":true,"enforce_lineup":true,"allow_reentry":false,"libero_enabled":true,"libero_can_serve":false}');
update vv_libero set s=boss_private.volleyball_initial(c);
update vv_libero set s=boss_private.volleyball_transition(c,s,'lineup_set','primary','{"roster_ids":["p1","p2"],"libero_roster_id":"p1"}');
update vv_libero set s=boss_private.volleyball_transition(c,s,'lineup_set','opponent','{"roster_ids":["o1","o2"]}');
update vv_libero set s=boss_private.volleyball_transition(c,s,'set_start','primary','{}');
select pg_temp.denied('libero cannot kill','select boss_private.volleyball_transition(c,s,''rally'',''primary'',''{"outcome":"kill","roster_id":"p1"}'')from vv_libero','PT409');
select pg_temp.denied('libero cannot block assist','select boss_private.volleyball_transition(c,s,''rally'',''primary'',''{"outcome":"assisted_block","blocker_roster_ids":["p1","p2"]}'')from vv_libero','PT409');
select pg_temp.denied('libero cannot serve by configured policy','select boss_private.volleyball_transition(c,s,''rally'',''primary'',''{"outcome":"ace","roster_id":"p1"}'')from vv_libero','PT409');
select pg_temp.denied('libero cannot silently transfer designation','select boss_private.volleyball_transition(c,s,''substitution'',''primary'',''{"out_roster_id":"p1","in_roster_id":"p3"}'')from vv_libero','PT409');
select pg_temp.denied('active lineup locked','select boss_private.volleyball_transition(c,s,''lineup_set'',''primary'',''{"roster_ids":["p1","p3"]}'')from vv_libero','PT409');
update vv_libero set s=boss_private.volleyball_transition(c,s,'substitution','primary','{"out_roster_id":"p2","in_roster_id":"p3"}');
select pg_temp.denied('reentry policy enforced','select boss_private.volleyball_transition(c,s,''substitution'',''primary'',''{"out_roster_id":"p3","in_roster_id":"p2"}'')from vv_libero','PT409');
select pg_temp.check('libero defense allowed','PARTICIPATION',(select boss_private.volleyball_transition(c,s,'dig','primary','{"roster_id":"p1"}')=s from vv_libero));
select count(*)passed_assertions from pg_temp.phase5a_assertions;
rollback;
