\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase8a/fixture.sql
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.mm('same-state-market','market.create','{"country":"US","region":"VA","market":"SYNTHETIC SECOND VIRGINIA MARKET"}');
select pg_temp.mm('same-state-loc','location.create',pg_temp.mi(jsonb_build_object('market_id',pg_temp.mid('same-state-market','market_id'),'name','SYNTHETIC second VA location','address','7 Synthetic Street','city','Synthetic City','postal_code','00000','timezone','America/New_York')));
select pg_temp.mo('network','{"location_policy":"all_current"}');
select pg_temp.mm('network-submit','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('network'),'state','pending_review')));
select pg_temp.mm('network-publish','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('network'),'state','published','reason','Reviewed synthetic all-location structured terms')));
select pg_temp.actor('parent');
select pg_temp.check('local membership excludes other VA market','GEOGRAPHY',jsonb_array_length(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('same-state-market','market_id')))->'offers')=0);
select pg_temp.check('outside coverage distinct from no membership','STATE',(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('same-state-market','market_id')))->>'availability')='outside_membership_coverage');
select pg_temp.product_order('purchase-base');reset role;
select boss_private.rails_dispatch(pg_temp.did('purchase-base','checkout_id'));select pg_temp.product_receive('purchase-base','captured');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.product_order('upgrade','upgrade-state','card',1,jsonb_build_object('base_source_id',pg_temp.product_source('purchase-base')));reset role;
select boss_private.rails_dispatch(pg_temp.did('upgrade','checkout_id'));select pg_temp.product_receive('upgrade','captured');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('paid current state upgrade covers second VA market','GEOGRAPHY',jsonb_array_length(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('same-state-market','market_id')))->'offers')=1);
select pg_temp.check('state membership excludes NC','GEOGRAPHY',jsonb_array_length(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('market-other','market_id')))->'offers')=0);
reset role;select boss_private.discount_revoke(pg_temp.product_source('upgrade'),'revoked',null,pg_temp.f('admin'));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.product_order('national-upgrade','upgrade-national','card',1,jsonb_build_object('base_source_id',pg_temp.product_source('purchase-base')));reset role;
select boss_private.rails_dispatch(pg_temp.did('national-upgrade','checkout_id'));select pg_temp.product_receive('national-upgrade','captured');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('nationwide covers active NC market','GEOGRAPHY',jsonb_array_length(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('market-other','market_id')))->'offers')=1);
select pg_temp.check('US nationwide never implies Canada','GEOGRAPHY',jsonb_array_length(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('market-ca','market_id')))->'offers')=0);
select pg_temp.actor('household-only');
select pg_temp.check('household membership alone has no personal offer authority','ISOLATION',jsonb_array_length(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('market','market_id')))->'offers')=0);
select pg_temp.check('missing membership explicit coarse state','STATE',(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('market','market_id')))->>'availability')='membership_required');
select pg_temp.actor('admin');
select pg_temp.revision('hh','digital','{"subject_type":"household","claim_policy":"household_primary_contact","gift_enabled":false}');
select pg_temp.dm('hh-binding','campaign.configure',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'revision_id',pg_temp.did('hh','revision_id'),'trial_enabled',true,'gift_enabled',false,'sale_enabled',false));
reset role;update public.household_memberships set is_primary_contact=true where person_id=pg_temp.f('parent')and household_id=pg_temp.f('household');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.dm('hh-trial','trial.start',jsonb_build_object('revision_id',pg_temp.did('hh','revision_id'),'path',pg_temp.fpath('share'),'household_id',pg_temp.f('household')));
select pg_temp.actor('household-only');
select pg_temp.check('explicit household discount source respects canonical shared benefit policy','HOUSEHOLD',jsonb_array_length(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('market','market_id')))->'offers')=2);
select pg_temp.mm('hh-intent','intent.create',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'revision_id',pg_temp.mid('network'),'capability',pg_temp.proof('hh'))));
reset role;update public.household_memberships set status='inactive'where household_id=pg_temp.f('household')and person_id=pg_temp.f('household-only');
set local role authenticated;select pg_temp.actor('staff');
select pg_temp.denied('ended household relation invalidates existing redemption intent','select pg_temp.mm(''hh-stale'',''token.redeem'',pg_temp.mi(jsonb_build_object(''location_id'',pg_temp.mid(''loc-a''),''capability'',pg_temp.proof(''hh''))))','PT409');
reset role;set constraints all immediate;
select count(*)passed_assertions,'Phase 8A canonical local state nationwide and household eligibility'::text suite from phase5a_assertions;rollback;
