-- Independent Phase 4B integration acceptance. Synthetic rollback-only fixtures.
-- Run after all Phase 4B migrations. No provider calls or real object contents.
-- All fixtures and operation receipts are rolled back.
begin;
set local timezone='UTC';
create temp table phase4b_integration_assertions(label text primary key,category text not null) on commit drop;
grant select,insert on phase4b_integration_assertions to authenticated,anon;
create function pg_temp.f(label text) returns uuid language sql immutable as $$select md5('boss-phase4b-integration:'||label)::uuid$$;
create function pg_temp.check(label text,category text,ok boolean) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL [%] %',category,label;end if;insert into phase4b_integration_assertions values(label,category);end$$;
create function pg_temp.actor(label text) returns void language plpgsql as $$begin perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.f('auth-'||label),'role','authenticated','is_anonymous',false,'session_id',pg_temp.f('session-'||label))::text,true);end$$;
create function pg_temp.denied(label text,statement text,expected text default 'PT403') returns void language plpgsql as $$declare denied boolean:=false;begin begin execute statement;exception when others then if sqlstate=expected then denied:=true;else raise exception 'FAIL % unexpected %: %',label,sqlstate,sqlerrm;end if;end;perform pg_temp.check(label,'DENIAL',denied);end$$;
create function pg_temp.key(event_name text,n int default 0) returns text language sql as $$select to_char((date_trunc('day',now())+interval '10 days 18 hours'+n*interval '1 day') at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS')$$;
create function pg_temp.cmd(op text,input jsonb) returns jsonb language sql as $$select jsonb_build_object('operation',op,'input',input)$$;
create function pg_temp.respond(event_name text,person_name text,participant_name text,status text default 'attending',ver int default 0,n int default 0) returns jsonb language sql as $$select pg_temp.cmd('response.set',jsonb_build_object('event_id',pg_temp.f(event_name),'occurrence_key',pg_temp.key(event_name,n),'person_id',pg_temp.f(person_name),'participant_id',case when participant_name is null then null else pg_temp.f(participant_name) end,'subject_kind',case when participant_name is null then 'staff' else 'participant' end,'status',status,'expected_version',ver))$$;
create function pg_temp.configure(event_name text,ver int default 0,deadline_policy text default 'lock',change_policy text default 'needs_reconfirmation',deadline timestamptz default null) returns jsonb language sql as $$select pg_temp.cmd('event.configure',jsonb_build_object('event_id',pg_temp.f(event_name),'expected_version',ver,'rsvp_mode','required','deadline_policy',deadline_policy,'change_policy',change_policy,'audience',jsonb_build_array('participants','staff'),'response_deadline_at',case when deadline is null then null else to_char(deadline at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"') end,'deadline_offset_minutes',null))$$;
create function pg_temp.query(view_name text default 'family',event_name text default null) returns jsonb language sql as $$select jsonb_build_object('organization_id',pg_temp.f('org'),'view',view_name,'from',to_char(now() at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"'),'to',to_char((now()+interval '30 days') at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"'))||case when event_name is null then '{}'::jsonb else jsonb_build_object('event_id',pg_temp.f(event_name)) end$$;
revoke all on function pg_temp.f(text),pg_temp.check(text,text,boolean),pg_temp.actor(text),pg_temp.denied(text,text,text),pg_temp.key(text,int),pg_temp.cmd(text,jsonb),pg_temp.respond(text,text,text,text,int,int),pg_temp.configure(text,int,text,text,timestamptz),pg_temp.query(text,text) from public;
grant execute on function pg_temp.f(text),pg_temp.check(text,text,boolean),pg_temp.actor(text),pg_temp.denied(text,text,text),pg_temp.key(text,int),pg_temp.cmd(text,jsonb),pg_temp.respond(text,text,text,text,int,int),pg_temp.configure(text,int,text,text,timestamptz),pg_temp.query(text,text) to authenticated,anon;
insert into public.people(id,display_name,date_of_birth) select pg_temp.f(label),'Synthetic attendance '||label,case when label='unknown-age' then null when label in ('child1','child2','child3','minor') then '2014-01-01'::date else '1990-01-01'::date end from unnest(array['admin','other-admin','coach','assistant','program','parent','household-only','child1','child2','child3','adult','minor','unknown-age','staff'])label;
insert into auth.users(id,email,email_confirmed_at) select pg_temp.f('auth-'||label),label||'@phase4b.example.invalid',now()-interval '2 days' from unnest(array['admin','other-admin','coach','assistant','program','parent','household-only','adult','minor','unknown-age','staff'])label;
insert into auth.sessions(id,user_id) select pg_temp.f('session-'||label),pg_temp.f('auth-'||label) from unnest(array['admin','other-admin','coach','assistant','program','parent','household-only','adult','minor','unknown-age','staff'])label;
insert into public.user_accounts(person_id,auth_user_id,account_status) select pg_temp.f(label),pg_temp.f('auth-'||label),'active' from unnest(array['admin','other-admin','coach','assistant','program','parent','household-only','adult','minor','unknown-age','staff'])label;
insert into public.organizations(id,name,slug) values(pg_temp.f('org'),'Synthetic attendance tenant','synthetic-phase4b-integration'),(pg_temp.f('other-org'),'Synthetic attendance other tenant','synthetic-phase4b-integration-other');
insert into public.organization_units(id,organization_id,unit_type,name,slug) values(pg_temp.f('unit'),pg_temp.f('org'),'program','Synthetic unit','att-unit'),(pg_temp.f('sibling-unit'),pg_temp.f('org'),'program','Synthetic sibling unit','att-sibling');
insert into public.teams(id,organization_id,parent_unit_id,name,slug,status) values(pg_temp.f('team'),pg_temp.f('org'),pg_temp.f('unit'),'Synthetic Falcons','att-team','active'),(pg_temp.f('second-team'),pg_temp.f('org'),pg_temp.f('unit'),'Synthetic Wildcats','att-second','active'),(pg_temp.f('sibling-team'),pg_temp.f('org'),pg_temp.f('sibling-unit'),'Synthetic Tigers','att-sibling','active'),(pg_temp.f('other-team'),pg_temp.f('other-org'),null,'Synthetic other tenant team','att-other','active');
insert into public.participants(id,person_id) select pg_temp.f('participant-'||label),pg_temp.f(label) from unnest(array['child1','child2','child3','adult','minor','unknown-age'])label;
insert into public.team_memberships(organization_id,team_id,person_id,participant_id,membership_type,starts_at,created_at) select pg_temp.f('org'),pg_temp.f(case when label='child2' then 'second-team' when label='child3' then 'sibling-team' else 'team' end),pg_temp.f(label),pg_temp.f('participant-'||label),'athlete',now()-interval '2 days',now()-interval '2 days' from unnest(array['child1','child2','child3','adult','minor','unknown-age'])label;
insert into public.team_memberships(organization_id,team_id,person_id,membership_type,starts_at,created_at) select pg_temp.f('org'),pg_temp.f('team'),pg_temp.f(label),case when label='coach' then 'head_coach' when label='assistant' then 'assistant_coach' else 'staff' end,now()-interval '2 days',now()-interval '2 days' from unnest(array['coach','assistant','staff'])label;
insert into public.guardian_relationships(id,guardian_person_id,dependent_person_id,authority_status,verified_at,starts_at,created_at,can_respond_attendance) select pg_temp.f('guardian-'||label),pg_temp.f('parent'),pg_temp.f(label),'active',now()-interval '2 days',now()-interval '2 days',now()-interval '2 days',true from unnest(array['child1','child2'])label;
insert into public.households(id,name) values(pg_temp.f('household'),'Synthetic attendance household');
insert into public.household_memberships(household_id,person_id,relationship_type,starts_at) select pg_temp.f('household'),pg_temp.f(label),'member',now()-interval '1 day' from unnest(array['household-only','parent','child1'])label;
insert into public.role_assignments(person_id,role_id,scope_type,scope_id,organization_id,starts_at,created_at) select pg_temp.f(label),role.id,case when label in ('coach','assistant') then 'team' when label='program' then 'organization_unit' else 'organization' end,pg_temp.f(case when label in ('coach','assistant') then 'team' when label='program' then 'unit' when label='other-admin' then 'other-org' else 'org' end),pg_temp.f(case when label='other-admin' then 'other-org' else 'org' end),now()-interval '2 days',now()-interval '2 days' from unnest(array['admin','other-admin','coach','assistant','program'])label join public.roles role on role.key=case when label='coach' then 'head_coach' when label='assistant' then 'assistant_coach' when label='program' then 'program_administrator' else 'organization_administrator' end;
insert into public.organization_modules(organization_id,module_id,status,configuration,starts_at) select pg_temp.f(label),m.id,'active','{}',now()-interval '2 days' from unnest(array['org','other-org'])label cross join public.modules m where m.key='calendar';
insert into public.events(id,organization_id,title,event_type_key,start_at,end_at,timezone,status,visibility,rsvp_mode,recurrence,created_by_person_id,updated_by_person_id) select pg_temp.f(label),pg_temp.f(case when label='other-event' then 'other-org' else 'org' end),'Synthetic attendance '||label,'practice',date_trunc('day',now())+interval '10 days 18 hours',date_trunc('day',now())+interval '10 days 19 hours','UTC','scheduled','member','required',case when label='recurring' then '{"frequency":"daily","interval":1,"count":3}'::jsonb else null end,pg_temp.f(case when label='other-event' then 'other-admin' else 'admin' end),pg_temp.f(case when label='other-event' then 'other-admin' else 'admin' end) from unnest(array['event','second-event','sibling-event','other-event','recurring','keep-event','multi-event'])label;
insert into public.event_targets(event_id,organization_id,target_type,target_id) select pg_temp.f(label),pg_temp.f(case when label='other-event' then 'other-org' else 'org' end),'team',pg_temp.f(case when label='second-event' then 'second-team' when label='sibling-event' then 'sibling-team' when label='other-event' then 'other-team' else 'team' end) from unnest(array['event','second-event','sibling-event','other-event','recurring','keep-event','multi-event'])label;
insert into public.event_targets(event_id,organization_id,target_type,target_id) values(pg_temp.f('multi-event'),pg_temp.f('org'),'team',pg_temp.f('sibling-team'));
-- Temporary RPC results contain only synthetic IDs and synthetic storage paths.
-- They are never selected into the runner output and disappear on rollback.
create temp table phase4b_integration_results(label text primary key,value jsonb not null) on commit drop;
grant select,insert,update on phase4b_integration_results to authenticated;
create function pg_temp.save(label text,value jsonb) returns void language sql as $$insert into phase4b_integration_results values(label,value) on conflict(label) do update set value=excluded.value$$;
create function pg_temp.result(label text) returns jsonb language sql stable as $$select value from phase4b_integration_results where phase4b_integration_results.label=$1$$;
create function pg_temp.id(label text) returns uuid language sql stable as $$select coalesce(pg_temp.result(label)->>'resource_id',pg_temp.result(label)->>'attachment_id')::uuid$$;
create function pg_temp.iso(p_at timestamptz) returns text language sql stable as $$select to_char(p_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"')$$;
create function pg_temp.notifications(category text) returns jsonb language sql stable as $$select public.boss_notifications_read(jsonb_build_object('category',category,'limit',50))$$;
create function pg_temp.attendance_prepare(kind text) returns jsonb language sql stable as $$select pg_temp.cmd('reminders.prepare',jsonb_build_object('organization_id',pg_temp.f('org'),'from',pg_temp.iso(now()),'to',pg_temp.iso(now()+interval '30 days'),'kind',kind))$$;
create function pg_temp.volunteer_prepare() returns jsonb language sql stable as $$select pg_temp.cmd('reminders.prepare',jsonb_build_object('organization_id',pg_temp.f('org'),'window_start',pg_temp.iso(now()-interval '1 hour'),'window_end',pg_temp.iso(now()+interval '1 day')))$$;
create function pg_temp.thread_query() returns jsonb language sql stable as $$select jsonb_build_object('organization_id',pg_temp.f('org'),'thread_id',pg_temp.id('announcement'),'view','announcements')$$;
revoke all on function pg_temp.save(text,jsonb),pg_temp.result(text),pg_temp.id(text),pg_temp.iso(timestamptz),pg_temp.notifications(text),pg_temp.attendance_prepare(text),pg_temp.volunteer_prepare(),pg_temp.thread_query() from public;
grant execute on function pg_temp.save(text,jsonb),pg_temp.result(text),pg_temp.id(text),pg_temp.iso(timestamptz),pg_temp.notifications(text),pg_temp.attendance_prepare(text),pg_temp.volunteer_prepare(),pg_temp.thread_query() to authenticated;
insert into public.organization_modules(organization_id,module_id,status,configuration,starts_at)
select pg_temp.f('org'),id,'active',case key when 'messaging' then '{"communications":true,"announcements":true,"guardian_visibility":true,"attachments":true,"in_app_notifications":true,"email_notifications":false}'::jsonb else '{}'::jsonb end,now()-interval '2 days'
from public.modules where key in('messaging','volunteers');
insert into public.events(id,organization_id,title,event_type_key,start_at,end_at,timezone,status,visibility,rsvp_mode,created_by_person_id,updated_by_person_id)
select pg_temp.f('dual-event'),organization_id,'Synthetic two-child attendance integration',event_type_key,start_at,end_at,timezone,status,visibility,rsvp_mode,created_by_person_id,updated_by_person_id from public.events where id=pg_temp.f('event');
insert into public.event_targets(event_id,organization_id,target_type,target_id) values
(pg_temp.f('dual-event'),pg_temp.f('org'),'team',pg_temp.f('team')),
(pg_temp.f('dual-event'),pg_temp.f('org'),'team',pg_temp.f('second-team'));

-- A current dedicated attendance guardian receives one ordinary notification
-- for two exact child/team contexts; no legacy communications capability needed.
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.save('attendance-enable',public.boss_attendance_mutate(pg_temp.cmd('attendance.configure',jsonb_build_object('organization_id',pg_temp.f('org'),'configuration','{"attendance":true,"rsvp":true,"guardian_rsvp":true,"attendance_reminders":true,"head_coach_management":true}'::jsonb)),pg_temp.f('attendance-enable')));
select pg_temp.save('dual-config1',public.boss_attendance_mutate(pg_temp.configure('dual-event'),pg_temp.f('dual-config1')));
reset role;
select pg_temp.check('requested source generated by event configure','ATTENDANCE',(select count(*)=1 from public.attendance_requests where event_id=pg_temp.f('dual-event') and kind='requested'));
select pg_temp.check('requested source expanded by shared pipeline','ATTENDANCE',(select count(*)=1 from public.notification_events e join public.attendance_requests r on r.id=e.source_id where r.event_id=pg_temp.f('dual-event') and e.event_type='attendance.requested' and e.source_type='attendance_request' and e.status='complete'));
select pg_temp.check('dual child recipient deduplicated','ATTENDANCE',(select count(*)=1 from public.notifications n join public.notification_events e on e.id=n.notification_event_id join public.attendance_requests r on r.id=e.source_id where r.event_id=pg_temp.f('dual-event') and e.event_type='attendance.requested' and n.recipient_person_id=pg_temp.f('parent')));
select pg_temp.check('dual child exact team contexts retained','ATTENDANCE',(select count(distinct c->>'team_id')=2 from public.notifications n join public.notification_events e on e.id=n.notification_event_id join public.attendance_requests r on r.id=e.source_id cross join lateral jsonb_array_elements(n.contexts)c where r.event_id=pg_temp.f('dual-event') and n.recipient_person_id=pg_temp.f('parent') and c?'team_id'));
select pg_temp.check('attendance guardian legacy flags remain false','ATTENDANCE',not exists(select 1 from public.guardian_relationships where guardian_person_id=pg_temp.f('parent') and(can_receive_communications or can_register or can_manage_payments)));
select pg_temp.check('household and unrelated tenant never recipients','ISOLATION',not exists(select 1 from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.source_type='attendance_request' and n.recipient_person_id in(pg_temp.f('household-only'),pg_temp.f('other-admin'))));
select pg_temp.save('attendance-notification',jsonb_build_object('resource_id',(select n.id from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.event_type='attendance.requested' and n.recipient_person_id=pg_temp.f('parent') limit 1)));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('requested notification reaches generic inbox','ATTENDANCE',(select count(*)=1 from jsonb_array_elements(pg_temp.notifications('attendance')->'notifications')n where n->>'event_type'='attendance.requested'));
select pg_temp.check('attendance destination has exact event and original occurrence','ATTENDANCE',(select bool_and(n->>'destination' like '/app/attendance?org=%' and position(pg_temp.f('dual-event')::text in n->>'destination')>0 and position('occurrence=' in n->>'destination')>0) from jsonb_array_elements(pg_temp.notifications('attendance')->'notifications')n));
select pg_temp.save('attendance-read',public.boss_notifications_mutate(pg_temp.f('attendance-read'),pg_temp.cmd('notification.read',jsonb_build_object('id',pg_temp.id('attendance-notification')))));
select pg_temp.check('generic unread state reflects attendance read','ATTENDANCE',(select bool_and(n->>'read_at' is not null) from jsonb_array_elements(pg_temp.notifications('attendance')->'notifications')n where n->>'id'=pg_temp.id('attendance-notification')::text));
select pg_temp.actor('admin');
select pg_temp.save('dual-config2',public.boss_attendance_mutate(pg_temp.configure('dual-event',1,'allow_late','needs_reconfirmation',now()+interval '1 hour'),pg_temp.f('dual-config2')));
select pg_temp.save('deadline1',public.boss_attendance_mutate(pg_temp.attendance_prepare('deadline'),pg_temp.f('deadline1')));
select pg_temp.save('deadline2',public.boss_attendance_mutate(pg_temp.attendance_prepare('deadline'),pg_temp.f('deadline2')));
reset role;
select pg_temp.check('deadline source is idempotent across different requests','ATTENDANCE',(select count(*)=1 from public.attendance_requests where event_id=pg_temp.f('dual-event') and kind='deadline'));
select pg_temp.check('events without deadlines never create deadline requests','ATTENDANCE',not exists(select 1 from public.attendance_requests where kind='deadline' and event_id<>pg_temp.f('dual-event')));
select pg_temp.check('deadline delivery recipient deduplicated','ATTENDANCE',(select count(*)=1 from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.event_type='attendance.deadline' and n.recipient_person_id=pg_temp.f('parent')));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('deadline appears in ordinary inbox','ATTENDANCE',(select count(*)=1 from jsonb_array_elements(pg_temp.notifications('attendance')->'notifications')n where n->>'event_type'='attendance.deadline'));
select pg_temp.actor('admin');
select pg_temp.save('dual-config3',public.boss_attendance_mutate(pg_temp.configure('dual-event',2,'allow_late','needs_reconfirmation',now()-interval '1 hour'),pg_temp.f('dual-config3')));
select pg_temp.save('no-response1',public.boss_attendance_mutate(pg_temp.attendance_prepare('no_response'),pg_temp.f('no-response1')));
select pg_temp.save('no-response2',public.boss_attendance_mutate(pg_temp.attendance_prepare('no_response'),pg_temp.f('no-response2')));
reset role;
select pg_temp.check('no-response source deduplicated','ATTENDANCE',(select count(*)=1 from public.attendance_requests where event_id=pg_temp.f('dual-event') and kind='no_response'));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('no-response notification visible while children pending','ATTENDANCE',(select count(*)=1 from jsonb_array_elements(pg_temp.notifications('attendance')->'notifications')n where n->>'event_type'='attendance.no_response'));
select pg_temp.save('child1-response',public.boss_attendance_mutate(pg_temp.respond('dual-event','child1','participant-child1'),pg_temp.f('child1-response')));
select pg_temp.check('one remaining child keeps no-response notification visible','ATTENDANCE',(select count(*)=1 from jsonb_array_elements(pg_temp.notifications('attendance')->'notifications')n where n->>'event_type'='attendance.no_response'));
select pg_temp.save('child2-response',public.boss_attendance_mutate(pg_temp.respond('dual-event','child2','participant-child2','not_attending'),pg_temp.f('child2-response')));
select pg_temp.check('answered children remove current no-response projection','ATTENDANCE',not exists(select 1 from jsonb_array_elements(pg_temp.notifications('attendance')->'notifications')n where n->>'event_type' in('attendance.deadline','attendance.no_response')));
reset role;
update public.events set start_at=start_at+interval '2 hours',end_at=end_at+interval '2 hours',version=version+1 where id=pg_temp.f('dual-event');
select pg_temp.check('material change marks both child responses','ATTENDANCE',(select count(*)=2 and bool_and(needs_reconfirmation) from public.attendance_responses where event_id=pg_temp.f('dual-event')));
select pg_temp.check('material change queues one generic reconfirmation source','ATTENDANCE',(select count(*)=1 from public.attendance_requests where event_id=pg_temp.f('dual-event') and kind='context_changed'));
select pg_temp.check('reconfirmation deduplicates parent after two child changes','ATTENDANCE',(select count(*)=1 from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.event_type='attendance.context_changed' and n.recipient_person_id=pg_temp.f('parent')));
select pg_temp.save('reconfirm-notification',jsonb_build_object('resource_id',(select n.id from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.event_type='attendance.context_changed' and n.recipient_person_id=pg_temp.f('parent'))));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('generic inbox projects current reconfirmation only','ATTENDANCE',(select count(*)=1 and bool_and(n->>'event_type'='attendance.context_changed') from jsonb_array_elements(pg_temp.notifications('attendance')->'notifications')n));
select pg_temp.check('notification exact original key resolves rescheduled occurrence','ATTENDANCE',(select jsonb_array_length(q->'occurrences')=1 and q->'occurrences'->0->>'occurrence_key'=pg_temp.key('dual-event') from(select public.boss_attendance_read(jsonb_build_object('organization_id',pg_temp.f('org'),'event_id',pg_temp.f('dual-event'),'occurrence_key',pg_temp.key('dual-event')))q)projection));
select pg_temp.save('reconfirm-read',public.boss_notifications_mutate(pg_temp.f('reconfirm-read'),pg_temp.cmd('notification.read',jsonb_build_object('id',pg_temp.id('reconfirm-notification')))));
reset role;
update public.guardian_relationships set can_respond_attendance=false,can_receive_communications=true,can_register=true,can_manage_payments=true where guardian_person_id=pg_temp.f('parent');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('current guardian flag revocation closes generic attendance inbox','REVOCATION',jsonb_array_length(pg_temp.notifications('attendance')->'notifications')=0);
select pg_temp.denied('legacy flags cannot read attendance notification',format('select public.boss_notifications_mutate(%L,%L)',pg_temp.f('read-revoked-reconfirm'),pg_temp.cmd('notification.read',jsonb_build_object('id',pg_temp.id('reconfirm-notification')))));
select pg_temp.denied('stale successful attendance read reauthorizes current flags',format('select public.boss_notifications_mutate(%L,%L)',pg_temp.f('reconfirm-read'),pg_temp.cmd('notification.read',jsonb_build_object('id',pg_temp.id('reconfirm-notification')))));
select pg_temp.denied('obsolete context read receipt remains inaccessible',format('select public.boss_notifications_mutate(%L,%L)',pg_temp.f('attendance-read'),pg_temp.cmd('notification.read',jsonb_build_object('id',pg_temp.id('attendance-notification')))));
select pg_temp.actor('household-only');
select pg_temp.check('household membership produces no attendance inbox','ISOLATION',jsonb_array_length(pg_temp.notifications('attendance')->'notifications')=0);
select pg_temp.denied('household cannot forge notification ID',format('select public.boss_notifications_mutate(%L,%L)',pg_temp.f('household-forged'),pg_temp.cmd('notification.read',jsonb_build_object('id',pg_temp.id('reconfirm-notification')))));
select pg_temp.actor('other-admin');
select pg_temp.denied('unrelated tenant cannot query attendance organization',format('select public.boss_notifications_read(%L)',jsonb_build_object('organization_id',pg_temp.f('org'),'category','attendance')));
select pg_temp.check('unrelated tenant default attendance inbox empty','ISOLATION',jsonb_array_length(pg_temp.notifications('attendance')->'notifications')=0);
reset role;
update public.guardian_relationships set can_respond_attendance=true,can_receive_communications=false,can_register=false,can_manage_payments=false where guardian_person_id=pg_temp.f('parent');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.save('attendance-pref-off',public.boss_notifications_mutate(pg_temp.f('attendance-pref-off'),pg_temp.cmd('preference.set',jsonb_build_object('organization_id',pg_temp.f('org'),'category','attendance','channel','in_app','enabled',false))));
select pg_temp.actor('admin');
select pg_temp.save('dual-config4',public.boss_attendance_mutate(pg_temp.configure('dual-event',3,'allow_late','needs_reconfirmation'),pg_temp.f('dual-config4')));
reset role;
select pg_temp.check('attendance category preference suppresses new delivery','PREFERENCES',exists(select 1 from public.notification_deliveries d join public.notifications n on n.id=d.notification_id join public.notification_events e on e.id=n.notification_event_id join public.attendance_requests r on r.id=e.source_id where n.recipient_person_id=pg_temp.f('parent') and r.event_id=pg_temp.f('dual-event') and r.kind='requested' and r.revision like '4:%' and d.channel='in_app' and d.status='suppressed' and d.failure_category='preference'));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.save('attendance-pref-on',public.boss_notifications_mutate(pg_temp.f('attendance-pref-on'),pg_temp.cmd('preference.set',jsonb_build_object('organization_id',pg_temp.f('org'),'category','attendance','channel','in_app','enabled',true))));
select pg_temp.actor('admin');
select pg_temp.save('dual-config5',public.boss_attendance_mutate(pg_temp.configure('dual-event',4,'allow_late','needs_reconfirmation'),pg_temp.f('dual-config5')));
reset role;
select pg_temp.check('attendance preference reenables only new delivery','PREFERENCES',exists(select 1 from public.notification_deliveries d join public.notifications n on n.id=d.notification_id join public.notification_events e on e.id=n.notification_event_id join public.attendance_requests r on r.id=e.source_id where n.recipient_person_id=pg_temp.f('parent') and r.event_id=pg_temp.f('dual-event') and r.kind='requested' and r.revision like '5:%' and d.channel='in_app' and d.status='sent'));
select pg_temp.check('attendance pipeline never enables email provider','PROVIDERS',not exists(select 1 from public.notification_deliveries d join public.notifications n on n.id=d.notification_id join public.notification_events e on e.id=n.notification_event_id where e.source_type='attendance_request' and d.channel='email' and d.status='sent'));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.save('post-reschedule-requested',public.boss_attendance_mutate(pg_temp.attendance_prepare('requested'),pg_temp.f('post-reschedule-requested')));
select pg_temp.save('post-reschedule-requested-repeat',public.boss_attendance_mutate(pg_temp.attendance_prepare('requested'),pg_temp.f('post-reschedule-requested-repeat')));
reset role;
select pg_temp.check('rescheduled requested sources use the pinned original key context','ATTENDANCE',(select count(*)=1 and bool_and(occurrence_key=pg_temp.key('dual-event') and revision='5:'||context_fingerprint) from public.attendance_requests where event_id=pg_temp.f('dual-event') and kind='requested' and revision like '5:%'));

-- Add one synthetic adult guardian volunteer only after attendance assertions.
insert into public.people(id,display_name,date_of_birth) values(pg_temp.f('parent2'),'Synthetic integration second adult','1990-01-01');
insert into auth.users(id,email,email_confirmed_at) values(pg_temp.f('auth-parent2'),'parent2@phase4b-integration.example.invalid',now()-interval '2 days');
insert into auth.sessions(id,user_id) values(pg_temp.f('session-parent2'),pg_temp.f('auth-parent2'));
insert into public.user_accounts(person_id,auth_user_id,account_status) values(pg_temp.f('parent2'),pg_temp.f('auth-parent2'),'active');
insert into public.guardian_relationships(id,guardian_person_id,dependent_person_id,authority_status,verified_at,starts_at,created_at)
values(pg_temp.f('guardian-parent2'),pg_temp.f('parent2'),pg_temp.f('child1'),'active',now()-interval '2 days',now()-interval '2 days',now()-interval '2 days');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.save('volunteers-enable',public.boss_volunteers_mutate(pg_temp.f('volunteers-enable'),pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org'),'configuration','{"volunteers":true,"self_signup":true,"reminders":true,"head_coach_management":true,"minimum_signup_age":18}'::jsonb))));
select pg_temp.save('volunteer-role',public.boss_volunteers_mutate(pg_temp.f('volunteer-role'),pg_temp.cmd('role.upsert',jsonb_build_object('organization_id',pg_temp.f('org'),'name','Synthetic refreshments'))));
select pg_temp.save('shift-command',pg_temp.cmd('shift.upsert',jsonb_build_object('organization_id',pg_temp.f('org'),'role_id',pg_temp.id('volunteer-role'),'title','Synthetic integration Falcons shift','scope_type','team','scope_id',pg_temp.f('team'),'start_at',pg_temp.iso(now()+interval '2 days'),'end_at',pg_temp.iso(now()+interval '2 days 1 hour'),'capacity',3,'status','open','visibility','members','reminder_minutes_before',2880)));
select pg_temp.save('shift',public.boss_volunteers_mutate(pg_temp.f('shift-create'),pg_temp.result('shift-command')));
select pg_temp.actor('parent');
select pg_temp.save('parent-signup',public.boss_volunteers_mutate(pg_temp.f('parent-signup'),pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.id('shift')))));
reset role;
select pg_temp.check('actual signup audit creates confirmation source','VOLUNTEERS',(select count(*)=1 from public.notification_events where source_type='volunteer_assignment' and source_id=pg_temp.id('parent-signup') and event_type='volunteer.confirmed' and status='complete'));
select pg_temp.check('confirmation goes only to current assignment owner','VOLUNTEERS',(select count(*)=1 and bool_and(n.recipient_person_id=pg_temp.f('parent')) from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.source_id=pg_temp.id('parent-signup') and e.event_type='volunteer.confirmed'));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('volunteer confirmation uses generic inbox','VOLUNTEERS',(select count(*)=1 from jsonb_array_elements(pg_temp.notifications('volunteers')->'notifications')n where n->>'event_type'='volunteer.confirmed'));
select pg_temp.actor('coach');
select pg_temp.save('reminders-first',public.boss_volunteers_mutate(pg_temp.f('reminders-first'),pg_temp.volunteer_prepare()));
reset role;
select pg_temp.save('parent-reminder',jsonb_build_object('resource_id',(select id from public.notification_events where source_type='volunteer_assignment' and source_id=pg_temp.id('parent-signup') and event_type='volunteer.reminder')));
select pg_temp.save('reminder-context',jsonb_build_object('value',boss_private.volunteer_reminder_context(pg_temp.id('shift'))));
select pg_temp.check('reminder is per assignment not shift','REMINDERS',(select count(*)=1 and bool_and(source_id=pg_temp.id('parent-signup') and source_type='volunteer_assignment' and safe_data->>'source_version'='1' and source_revision='assignment:1:'||boss_private.volunteer_reminder_context(pg_temp.id('shift'))) from public.notification_events where event_type='volunteer.reminder'));
select pg_temp.check('due reminder delivers ordinary in-app notification','REMINDERS',exists(select 1 from public.notifications n join public.notification_deliveries d on d.notification_id=n.id where n.notification_event_id=pg_temp.id('parent-reminder') and n.recipient_person_id=pg_temp.f('parent') and d.channel='in_app' and d.status='sent'));
set local timezone='Pacific/Honolulu';
select pg_temp.check('reminder schedule context stable across timezone','REMINDERS',boss_private.volunteer_reminder_context(pg_temp.id('shift'))=pg_temp.result('reminder-context')->>'value');
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.save('reminders-zone',public.boss_volunteers_mutate(pg_temp.f('reminders-zone'),pg_temp.volunteer_prepare()));
reset role;
select pg_temp.check('timezone request does not duplicate existing reminder','REMINDERS',(select count(*)=1 from public.notification_events where source_id=pg_temp.id('parent-signup') and event_type='volunteer.reminder'));
set local timezone='UTC';
set local role authenticated;select pg_temp.actor('parent2');
select pg_temp.save('parent2-signup',public.boss_volunteers_mutate(pg_temp.f('parent2-signup'),pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.id('shift')))));
select pg_temp.actor('coach');
select pg_temp.save('reminders-other-signup',public.boss_volunteers_mutate(pg_temp.f('reminders-other-signup'),pg_temp.volunteer_prepare()));
reset role;
select pg_temp.check('other signup preserves first reminder visibility','REMINDERS',(select boss_private.notification_source_visible(e,pg_temp.f('parent')) from public.notification_events e where e.id=pg_temp.id('parent-reminder')));
select pg_temp.check('other signup does not reissue first reminder','REMINDERS',(select count(*)=1 from public.notification_events where source_id=pg_temp.id('parent-signup') and event_type='volunteer.reminder'));
select pg_temp.check('new volunteer receives their own reminder','REMINDERS',(select count(*)=1 from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.event_type='volunteer.reminder' and e.source_id=pg_temp.id('parent2-signup') and n.recipient_person_id=pg_temp.f('parent2')));
set local role authenticated;select pg_temp.actor('parent2');
select pg_temp.save('parent2-cancel',public.boss_volunteers_mutate(pg_temp.f('parent2-cancel'),pg_temp.cmd('assignment.cancel',jsonb_build_object('assignment_id',pg_temp.id('parent2-signup'),'expected_version',1))));
reset role;
select pg_temp.check('actual cancellation generates audit-bound source','VOLUNTEERS',(select count(*)=1 from public.notification_events where source_id=pg_temp.id('parent2-signup') and event_type='volunteer.cancellation' and source_revision like 'audit:%'));
select pg_temp.check('cancellation source dates current assignment episode','VOLUNTEERS',(select e.occurred_at>=a.updated_at from public.notification_events e join public.volunteer_assignments a on a.id=e.source_id where e.source_id=pg_temp.id('parent2-signup') and e.event_type='volunteer.cancellation'));
select pg_temp.check('cancellation owner and current exact coordinator receive','VOLUNTEERS',(select count(distinct n.recipient_person_id)=2 from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.source_id=pg_temp.id('parent2-signup') and e.event_type='volunteer.cancellation' and n.recipient_person_id in(pg_temp.f('parent2'),pg_temp.f('coach'))));
select pg_temp.check('ordinary volunteers and team staff do not receive cancellation','VOLUNTEERS',not exists(select 1 from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.source_id=pg_temp.id('parent2-signup') and e.event_type='volunteer.cancellation' and n.recipient_person_id in(pg_temp.f('parent'),pg_temp.f('staff'),pg_temp.f('household-only'),pg_temp.f('other-admin'))));
select pg_temp.check('other cancellation preserves first reminder context','REMINDERS',(select boss_private.notification_source_visible(e,pg_temp.f('parent')) and e.source_revision='assignment:1:'||boss_private.volunteer_reminder_context(pg_temp.id('shift')) from public.notification_events e where e.id=pg_temp.id('parent-reminder')));
select pg_temp.check('canceled volunteer reminder immediately invisible','REMINDERS',not exists(select 1 from public.notification_events e where e.source_id=pg_temp.id('parent2-signup') and e.event_type='volunteer.reminder' and boss_private.notification_source_visible(e,pg_temp.f('parent2'))));
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.save('reminders-after-cancel',public.boss_volunteers_mutate(pg_temp.f('reminders-after-cancel'),pg_temp.volunteer_prepare()));
reset role;
select pg_temp.check('other cancellation does not reissue surviving reminder','REMINDERS',(select count(*)=1 from public.notification_events where source_id=pg_temp.id('parent-signup') and event_type='volunteer.reminder'));
select pg_temp.check('confirmation visibility revokes on canceled assignment','VOLUNTEERS',not exists(select 1 from public.notification_events e where e.source_id=pg_temp.id('parent2-signup') and e.event_type='volunteer.confirmed' and boss_private.notification_source_visible(e,pg_temp.f('parent2'))));
select pg_temp.save('cancellation-notification',jsonb_build_object('resource_id',(select n.id from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.source_id=pg_temp.id('parent2-signup') and e.event_type='volunteer.cancellation' and n.recipient_person_id=pg_temp.f('parent2'))));
set local role authenticated;select pg_temp.actor('parent2');
select pg_temp.save('cancellation-read',public.boss_notifications_mutate(pg_temp.f('cancellation-read'),pg_temp.cmd('notification.read',jsonb_build_object('id',pg_temp.id('cancellation-notification')))));
reset role;
update public.guardian_relationships set authority_status='inactive' where id=pg_temp.f('guardian-parent2');
select pg_temp.check('current relationship revokes cancellation owner visibility','VOLUNTEERS',not exists(select 1 from public.notification_events e where e.source_id=pg_temp.id('parent2-signup') and e.event_type='volunteer.cancellation' and boss_private.notification_source_visible(e,pg_temp.f('parent2'))));
set local role authenticated;select pg_temp.actor('parent2');
select pg_temp.denied('cancellation read receipt reauthorizes current relationship',format('select public.boss_notifications_mutate(%L,%L)',pg_temp.f('cancellation-read'),pg_temp.cmd('notification.read',jsonb_build_object('id',pg_temp.id('cancellation-notification')))));
reset role;
update public.guardian_relationships set authority_status='active' where id=pg_temp.f('guardian-parent2');
-- Schedule and offset changes produce a new commitment context. Capacity
-- versions and other people's commitments above never produce that change.
select pg_temp.save('offset-update',pg_temp.result('shift-command')||jsonb_build_object('input',pg_temp.result('shift-command')->'input'||jsonb_build_object('shift_id',pg_temp.id('shift'),'expected_version',(select version from public.volunteer_shifts where id=pg_temp.id('shift')),'reminder_minutes_before',2881)));
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.save('offset-changed',public.boss_volunteers_mutate(pg_temp.f('offset-changed'),pg_temp.result('offset-update')));
select pg_temp.save('reminders-new-offset',public.boss_volunteers_mutate(pg_temp.f('reminders-new-offset'),pg_temp.volunteer_prepare()));
select pg_temp.save('reminders-new-offset-repeat',public.boss_volunteers_mutate(pg_temp.f('reminders-new-offset-repeat'),pg_temp.volunteer_prepare()));
reset role;
select pg_temp.check('offset change invalidates old assignment reminder','REMINDERS',not(select boss_private.notification_source_visible(e,pg_temp.f('parent')) from public.notification_events e where e.id=pg_temp.id('parent-reminder')));
select pg_temp.check('new offset reminder is current and delivered once','REMINDERS',(select count(*)=1 from public.notification_events e join public.notifications n on n.notification_event_id=e.id join public.notification_deliveries d on d.notification_id=n.id where e.source_id=pg_temp.id('parent-signup') and e.event_type='volunteer.reminder' and boss_private.notification_source_visible(e,pg_temp.f('parent')) and n.recipient_person_id=pg_temp.f('parent') and d.channel='in_app' and d.status='sent'));
select pg_temp.check('offset retry leaves exactly two historical reminder contexts','REMINDERS',(select count(*)=2 from public.notification_events where source_id=pg_temp.id('parent-signup') and event_type='volunteer.reminder'));
select pg_temp.save('schedule-update',pg_temp.result('offset-update')||jsonb_build_object('input',pg_temp.result('offset-update')->'input'||jsonb_build_object('expected_version',(select version from public.volunteer_shifts where id=pg_temp.id('shift')),'start_at',pg_temp.iso(now()+interval '2 days 1 hour'),'end_at',pg_temp.iso(now()+interval '2 days 2 hours'))));
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.save('schedule-changed',public.boss_volunteers_mutate(pg_temp.f('schedule-changed'),pg_temp.result('schedule-update')));
select pg_temp.save('reminders-new-schedule',public.boss_volunteers_mutate(pg_temp.f('reminders-new-schedule'),pg_temp.volunteer_prepare()));
reset role;
select pg_temp.check('schedule change retains history but only one current reminder','REMINDERS',(select count(*)=3 and count(*) filter(where boss_private.notification_source_visible(e,pg_temp.f('parent')))=1 from public.notification_events e where e.source_id=pg_temp.id('parent-signup') and e.event_type='volunteer.reminder'));
select pg_temp.check('future rescheduled reminder remains queued until due','REMINDERS',(select count(*)=1 and bool_and(e.status='queued' and e.scheduled_at>now()) from public.notification_events e where e.source_id=pg_temp.id('parent-signup') and e.event_type='volunteer.reminder' and boss_private.notification_source_visible(e,pg_temp.f('parent'))));

-- A distinct linked event exercises the signed Calendar audit source, rather
-- than manufacturing an audit row or invoking notification helpers directly.
insert into public.events(id,organization_id,title,event_type_key,start_at,end_at,timezone,status,visibility,rsvp_mode,created_by_person_id,updated_by_person_id)
values(pg_temp.f('linked-event'),pg_temp.f('org'),'Synthetic linked volunteer event','practice',date_trunc('second',now()+interval '3 days'),date_trunc('second',now()+interval '3 days 1 hour'),'UTC','scheduled','member','not_required',pg_temp.f('admin'),pg_temp.f('admin'));
insert into public.event_targets(event_id,organization_id,target_type,target_id) values(pg_temp.f('linked-event'),pg_temp.f('org'),'team',pg_temp.f('team'));
select pg_temp.save('linked-key',jsonb_build_object('value',(select to_char(start_at at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS') from public.events where id=pg_temp.f('linked-event'))));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.save('volunteer-pref-off',public.boss_notifications_mutate(pg_temp.f('volunteer-pref-off'),pg_temp.cmd('preference.set',jsonb_build_object('organization_id',pg_temp.f('org'),'category','volunteers','channel','in_app','enabled',false))));
select pg_temp.actor('admin');
select pg_temp.save('linked-shift-command',pg_temp.cmd('shift.upsert',jsonb_build_object('organization_id',pg_temp.f('org'),'role_id',pg_temp.id('volunteer-role'),'title','Synthetic event-linked shift','scope_type','team','scope_id',pg_temp.f('team'),'event_id',pg_temp.f('linked-event'),'occurrence_key',pg_temp.result('linked-key')->>'value','start_at',pg_temp.iso(now()+interval '3 days'),'end_at',pg_temp.iso(now()+interval '3 days 1 hour'),'capacity',3,'status','open','visibility','members','reminder_minutes_before',4320)));
select pg_temp.save('linked-shift',public.boss_volunteers_mutate(pg_temp.f('linked-shift'),pg_temp.result('linked-shift-command')));
select pg_temp.actor('parent');
select pg_temp.save('linked-signup',public.boss_volunteers_mutate(pg_temp.f('linked-signup'),pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.id('linked-shift')))));
reset role;
select pg_temp.check('volunteer-specific preference suppresses actual confirmation','PREFERENCES',exists(select 1 from public.notifications n join public.notification_events e on e.id=n.notification_event_id join public.notification_deliveries d on d.notification_id=n.id where e.source_id=pg_temp.id('linked-signup') and e.event_type='volunteer.confirmed' and n.recipient_person_id=pg_temp.f('parent') and d.channel='in_app' and d.status='suppressed' and d.failure_category='preference'));
select pg_temp.check('volunteer preference does not suppress attendance category','PREFERENCES',(select boss_private.notification_preference(pg_temp.f('parent'),pg_temp.f('org'),null,'in_app','attendance',false)));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.save('volunteer-pref-on',public.boss_notifications_mutate(pg_temp.f('volunteer-pref-on'),pg_temp.cmd('preference.set',jsonb_build_object('organization_id',pg_temp.f('org'),'category','volunteers','channel','in_app','enabled',true))));
select pg_temp.actor('coach');
select pg_temp.save('linked-reminder-prepare',public.boss_volunteers_mutate(pg_temp.f('linked-reminder-prepare'),pg_temp.volunteer_prepare()));
reset role;
select pg_temp.save('linked-reminder',jsonb_build_object('resource_id',(select id from public.notification_events where source_type='volunteer_assignment' and source_id=pg_temp.id('linked-signup') and event_type='volunteer.reminder')));
select pg_temp.check('volunteer preference restoration permits new linked reminder','PREFERENCES',exists(select 1 from public.notifications n join public.notification_deliveries d on d.notification_id=n.id where n.notification_event_id=pg_temp.id('linked-reminder') and n.recipient_person_id=pg_temp.f('parent') and d.channel='in_app' and d.status='sent'));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.save('calendar-linked-update',public.boss_calendar_mutate(pg_temp.cmd('event.update',jsonb_build_object('organization_id',pg_temp.f('org'),'event_id',pg_temp.f('linked-event'),'expected_version',1,'title','Synthetic rescheduled linked volunteer event','event_type_key','practice','start_at',pg_temp.iso(now()+interval '3 days 2 hours'),'end_at',pg_temp.iso(now()+interval '3 days 3 hours'),'timezone','UTC','status','scheduled','visibility','member','rsvp_mode','not_required','targets',jsonb_build_array(jsonb_build_object('target_type','team','target_id',pg_temp.f('team'))))),pg_temp.f('calendar-linked-update')));
reset role;
select pg_temp.check('signed Calendar mutation produces volunteer event source','LINKED_EVENT',(select count(*)=1 and bool_and(source_revision like 'event:%' and status='complete') from public.notification_events where source_type='volunteer_event' and source_id=pg_temp.f('linked-event') and event_type='volunteer.changed'));
select pg_temp.check('linked event source delivers only current exact volunteer','LINKED_EVENT',(select count(*)=1 and bool_and(n.recipient_person_id=pg_temp.f('parent')) from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.source_type='volunteer_event' and e.source_id=pg_temp.f('linked-event')));
select pg_temp.check('linked source projection preserves canonical event and exact team','LINKED_EVENT',(select count(*)=1 and bool_and(boss_private.notification_destination(e)='/app/volunteers?org='||pg_temp.f('org')::text||'&event='||pg_temp.f('linked-event')::text and n.contexts @> jsonb_build_array(jsonb_build_object('team_id',pg_temp.f('team')))) from public.notifications n join public.notification_events e on e.id=n.notification_event_id where e.source_type='volunteer_event' and e.source_id=pg_temp.f('linked-event')));
select pg_temp.check('linked Calendar reschedule immediately invalidates old reminder','LINKED_EVENT',not(select boss_private.notification_source_visible(e,pg_temp.f('parent')) from public.notification_events e where e.id=pg_temp.id('linked-reminder')));
select pg_temp.save('linked-review-command',pg_temp.result('linked-shift-command')||jsonb_build_object('input',pg_temp.result('linked-shift-command')->'input'||jsonb_build_object('shift_id',pg_temp.id('linked-shift'),'expected_version',(select version from public.volunteer_shifts where id=pg_temp.id('linked-shift')),'start_at',pg_temp.iso(now()+interval '3 days 2 hours'),'end_at',pg_temp.iso(now()+interval '3 days 3 hours'))));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('generic volunteers read reports current Calendar change','LINKED_EVENT',public.boss_volunteers_read(jsonb_build_object('organization_id',pg_temp.f('org'),'shift_id',pg_temp.id('linked-shift')))->'detail'->'event_context_changed'='true'::jsonb);
select pg_temp.actor('coach');
select pg_temp.save('linked-review',public.boss_volunteers_mutate(pg_temp.f('linked-review'),pg_temp.result('linked-review-command')));
select pg_temp.save('linked-reminder-new-context',public.boss_volunteers_mutate(pg_temp.f('linked-reminder-new-context'),pg_temp.volunteer_prepare()));
select pg_temp.save('linked-reminder-new-context-repeat',public.boss_volunteers_mutate(pg_temp.f('linked-reminder-new-context-repeat'),pg_temp.volunteer_prepare()));
reset role;
select pg_temp.check('review preserves original linked occurrence identity','LINKED_EVENT',(select occurrence_key=pg_temp.result('linked-key')->>'value' and event_context_stamp=boss_private.volunteer_event_stamp(event_id,occurrence_key) from public.volunteer_shifts where id=pg_temp.id('linked-shift')));
select pg_temp.check('reviewed Calendar-change notification ceases current visibility','LINKED_EVENT',not exists(select 1 from public.notification_events e where e.source_type='volunteer_event' and e.source_id=pg_temp.f('linked-event') and boss_private.notification_source_visible(e,pg_temp.f('parent'))));
select pg_temp.check('review emits one replacement reminder context while retaining history','LINKED_EVENT',(select count(*)=2 and count(*) filter(where boss_private.notification_source_visible(e,pg_temp.f('parent')))=1 from public.notification_events e where e.source_id=pg_temp.id('linked-signup') and e.event_type='volunteer.reminder'));
select pg_temp.check('replacement linked reminder remains future queued','LINKED_EVENT',(select count(*)=1 and bool_and(status='queued' and scheduled_at>now()) from public.notification_events e where e.source_id=pg_temp.id('linked-signup') and e.event_type='volunteer.reminder' and boss_private.notification_source_visible(e,pg_temp.f('parent'))));

-- A selected-volunteer announcement is a regular private Messaging thread.
-- The generic read, receipt and private Storage paths must all reauthorize.
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.save('announcement',public.boss_volunteers_mutate(pg_temp.f('announcement'),pg_temp.cmd('shift.announce',jsonb_build_object('shift_id',pg_temp.id('shift'),'title','Synthetic volunteer notice','body','Synthetic controlled integration content'))));
select pg_temp.check('coach generic Messaging read succeeds before policy change','ANNOUNCEMENT',jsonb_array_length(public.boss_communications_read(pg_temp.thread_query())->'detail'->'messages')=1);
select pg_temp.save('coach-thread-read',public.boss_communications_mutate(pg_temp.f('coach-thread-read'),pg_temp.cmd('read.thread',jsonb_build_object('thread_id',pg_temp.id('announcement'),'through_sequence',1))));
select pg_temp.save('attachment',public.boss_communications_mutate(pg_temp.f('attachment-intent'),pg_temp.cmd('attachment.intent',jsonb_build_object('thread_id',pg_temp.id('announcement'),'file_name','synthetic-empty.pdf','mime_type','application/pdf','size_bytes',100,'content_sha256',repeat('a',64)))));
reset role;
insert into storage.objects(bucket_id,name,metadata) values('boss-communication-attachments',pg_temp.result('attachment')->>'object_name','{"mimetype":"application/pdf","size":100}'::jsonb);
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.save('attachment-complete',public.boss_communications_mutate(pg_temp.f('attachment-complete'),pg_temp.cmd('attachment.complete',jsonb_build_object('attachment_id',pg_temp.id('attachment')))));
select pg_temp.save('coach-attachment-access',public.boss_communications_mutate(pg_temp.f('coach-attachment-access'),pg_temp.cmd('attachment.access',jsonb_build_object('attachment_id',pg_temp.id('attachment')))));
select set_config('storage.operation','object.get_authenticated',true);
select pg_temp.check('coach synthetic private object read allowed before change','ATTACHMENT',(select count(*)=1 from storage.objects where bucket_id='boss-communication-attachments' and name=pg_temp.result('attachment')->>'object_name'));
select pg_temp.actor('parent');
select pg_temp.check('selected guardian volunteer reads normal Messaging without legacy flags','ANNOUNCEMENT',jsonb_array_length(public.boss_communications_read(pg_temp.thread_query())->'detail'->'messages')=1);
select pg_temp.save('parent-thread-read',public.boss_communications_mutate(pg_temp.f('parent-thread-read'),pg_temp.cmd('read.thread',jsonb_build_object('thread_id',pg_temp.id('announcement'),'through_sequence',1))));
select pg_temp.save('parent-attachment-access',public.boss_communications_mutate(pg_temp.f('parent-attachment-access'),pg_temp.cmd('attachment.access',jsonb_build_object('attachment_id',pg_temp.id('attachment')))));
select pg_temp.check('selected volunteer reads synthetic attachment metadata only','ATTACHMENT',(select count(*)=1 from storage.objects where bucket_id='boss-communication-attachments' and name=pg_temp.result('attachment')->>'object_name'));
select pg_temp.check('selected announcement reaches generic notification inbox','ANNOUNCEMENT',(select count(*)=1 from jsonb_array_elements(pg_temp.notifications('communications')->'notifications')n where n->>'event_type'='communication.announcement'));
select pg_temp.actor('staff');
select pg_temp.denied('same team staff without active assignment cannot read selected thread',format('select public.boss_communications_read(%L)',pg_temp.thread_query()));
select pg_temp.denied('same team staff cannot forge selected attachment',format('select public.boss_communications_mutate(%L,%L)',pg_temp.f('staff-attachment'),pg_temp.cmd('attachment.access',jsonb_build_object('attachment_id',pg_temp.id('attachment')))));
select pg_temp.actor('parent2');
select pg_temp.denied('canceled volunteer cannot read selected thread',format('select public.boss_communications_read(%L)',pg_temp.thread_query()));
select pg_temp.actor('other-admin');
select pg_temp.denied('other tenant administrator cannot read selected thread',format('select public.boss_communications_read(%L)',pg_temp.thread_query()));
reset role;
select pg_temp.check('selected audience remains private exact shift only','ANNOUNCEMENT',(select t.kind='announcement' and t.visibility='private' and count(a.id)=1 and bool_and(a.volunteer_shift_id=pg_temp.id('shift') and a.scope_type='team' and a.scope_id=pg_temp.f('team')) from public.communication_threads t join public.communication_audiences a on a.thread_id=t.id where t.id=pg_temp.id('announcement') group by t.kind,t.visibility));
select pg_temp.check('selected announcement notification excludes unrelated team members','ANNOUNCEMENT',not exists(select 1 from public.notifications n join public.notification_events e on e.id=n.notification_event_id join public.communication_messages m on m.id=e.source_id where m.thread_id=pg_temp.id('announcement') and n.recipient_person_id in(pg_temp.f('staff'),pg_temp.f('parent2'),pg_temp.f('household-only'),pg_temp.f('other-admin'))));
-- now() is fixed in a rollback-only transaction. Give the later commitment a
-- synthetic one-microsecond ordering boundary to represent a subsequent signup
-- transaction without sleeping, committing fixtures or rewriting source rows.
set local role authenticated;select pg_temp.actor('parent2');
select pg_temp.save('post-announcement-signup',public.boss_volunteers_mutate(pg_temp.f('post-announcement-signup'),pg_temp.cmd('assignment.signup',jsonb_build_object('shift_id',pg_temp.id('shift')))));
reset role;
update public.volunteer_assignments set updated_at=now()+interval '1 microsecond' where id=pg_temp.id('post-announcement-signup');
select pg_temp.check('post-source assignment excluded from historical announcement visibility','SOURCE_DATED',not exists(select 1 from public.notification_events e join public.communication_messages m on m.id=e.source_id where m.thread_id=pg_temp.id('announcement') and boss_private.notification_source_visible(e,pg_temp.f('parent2'))));
select pg_temp.check('post-source assignment excluded from historical candidate seek','SOURCE_DATED',not exists(select 1 from public.notification_events e join public.communication_messages m on m.id=e.source_id cross join lateral boss_private.notification_candidates(e,null,100)c where m.thread_id=pg_temp.id('announcement') and c.person_id=pg_temp.f('parent2')));
select pg_temp.check('existing volunteer retains source-dated announcement visibility','SOURCE_DATED',exists(select 1 from public.notification_events e join public.communication_messages m on m.id=e.source_id where m.thread_id=pg_temp.id('announcement') and boss_private.notification_source_visible(e,pg_temp.f('parent'))));
select pg_temp.check('historical announcement creates no retroactive recipient row','SOURCE_DATED',not exists(select 1 from public.notifications n join public.notification_events e on e.id=n.notification_event_id join public.communication_messages m on m.id=e.source_id where m.thread_id=pg_temp.id('announcement') and n.recipient_person_id=pg_temp.f('parent2')));
set local role authenticated;select pg_temp.actor('parent2');
select pg_temp.check('current selected volunteer may read current thread after joining','SOURCE_DATED',jsonb_array_length(public.boss_communications_read(pg_temp.thread_query())->'detail'->'messages')=1);
reset role;
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.save('coach-management-off',public.boss_volunteers_mutate(pg_temp.f('coach-management-off'),pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org'),'configuration','{"head_coach_management":false}'::jsonb))));
reset role;
select pg_temp.check('coordinator notification reauthorizes current management policy','VOLUNTEERS',not exists(select 1 from public.notification_events e where e.source_id=pg_temp.id('parent2-signup') and e.event_type='volunteer.cancellation' and boss_private.notification_source_visible(e,pg_temp.f('coach'))));
set local role authenticated;
select pg_temp.actor('coach');
select pg_temp.denied('disabled coach policy closes generic selected-thread read',format('select public.boss_communications_read(%L)',pg_temp.thread_query()));
select pg_temp.denied('disabled coach policy closes stale generic read receipt',format('select public.boss_communications_mutate(%L,%L)',pg_temp.f('coach-thread-read'),pg_temp.cmd('read.thread',jsonb_build_object('thread_id',pg_temp.id('announcement'),'through_sequence',1))));
select pg_temp.denied('disabled coach policy closes stale attachment request',format('select public.boss_communications_mutate(%L,%L)',pg_temp.f('coach-attachment-access'),pg_temp.cmd('attachment.access',jsonb_build_object('attachment_id',pg_temp.id('attachment')))));
select pg_temp.check('disabled coach policy closes existing private storage lease','ATTACHMENT',(select count(*)=0 from storage.objects where bucket_id='boss-communication-attachments' and name=pg_temp.result('attachment')->>'object_name'));
select pg_temp.actor('parent');
select pg_temp.check('coach policy change preserves selected volunteer audience','ANNOUNCEMENT',jsonb_array_length(public.boss_communications_read(pg_temp.thread_query())->'detail'->'messages')=1);
select pg_temp.actor('admin');
select pg_temp.save('volunteers-off',public.boss_volunteers_mutate(pg_temp.f('volunteers-off'),pg_temp.cmd('volunteers.configure',jsonb_build_object('organization_id',pg_temp.f('org'),'configuration','{"volunteers":false}'::jsonb))));
select pg_temp.actor('parent');
select pg_temp.denied('volunteer feature disable closes generic selected-thread read',format('select public.boss_communications_read(%L)',pg_temp.thread_query()));
select pg_temp.denied('volunteer feature disable closes successful read receipt',format('select public.boss_communications_mutate(%L,%L)',pg_temp.f('parent-thread-read'),pg_temp.cmd('read.thread',jsonb_build_object('thread_id',pg_temp.id('announcement'),'through_sequence',1))));
select pg_temp.denied('volunteer feature disable closes stale attachment request',format('select public.boss_communications_mutate(%L,%L)',pg_temp.f('parent-attachment-access'),pg_temp.cmd('attachment.access',jsonb_build_object('attachment_id',pg_temp.id('attachment')))));
select pg_temp.check('volunteer feature disable closes existing storage lease','ATTACHMENT',(select count(*)=0 from storage.objects where bucket_id='boss-communication-attachments' and name=pg_temp.result('attachment')->>'object_name'));
select pg_temp.check('volunteer feature disable removes current volunteer inbox','REVOCATION',jsonb_array_length(pg_temp.notifications('volunteers')->'notifications')=0);
select pg_temp.check('volunteer feature disable removes selected announcement inbox','REVOCATION',jsonb_array_length(pg_temp.notifications('communications')->'notifications')=0);
reset role;
select pg_temp.check('no real document contents or provider material used','CLEANUP',(select count(*)=1 and bool_and(metadata='{"mimetype":"application/pdf","size":100}'::jsonb) from storage.objects where name=pg_temp.result('attachment')->>'object_name') and not exists(select 1 from public.notification_deliveries d join public.notifications n on n.id=d.notification_id where n.organization_id=pg_temp.f('org') and d.channel='email' and d.status='sent'));
do $$begin if (select count(*) from phase4b_integration_assertions)<>100 then raise exception 'Unexpected Phase 4B integration assertion count';end if;end$$;
select category,count(*) as assertions from phase4b_integration_assertions group by category order by category;
select count(*) as passed_assertions from phase4b_integration_assertions;
rollback;
