begin;
set local statement_timeout='8s';
\ir phase6b/fixture.sql
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.rb('definition.create',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'source_organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'product','leaderboard','source_kind','athlete_season','name','Synthetic restricted ranking','metric_key','home_runs','metric_kind','count','direction','high','qualification','{}'::jsonb),'definition');
select pg_temp.rb('access.grant',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'person_id',pg_temp.f('household-only'),'ends_at',clock_timestamp()+interval'1 hour'),'manager');
select pg_temp.rb('edition.create',jsonb_build_object('competition_id',pg_temp.rb_id('competition'),'sport_key','baseball','name','Synthetic unassigned edition','cross_organization',true,'team_result_audience','entry_teams'),'other-edition');
select pg_temp.rb('entry.create',jsonb_build_object('edition_id',pg_temp.rb_id('other-edition'),'team_id',pg_temp.f('other-team')),'foreign-entry');
reset role;
select pg_temp.check('foreign entry requires source owner approval','CONSENT',(select status='pending'and approved_by_person_id is null from public.competition_entries where id=pg_temp.rb_id('foreign-entry')));
select pg_temp.check('manager bridge creates no organization membership','ISOLATION',not exists(select 1 from public.organization_memberships where person_id=pg_temp.f('household-only')));
set local role authenticated;select pg_temp.actor('household-only');
select pg_temp.check('exact manager native edition available','AUTHORIZATION',public.boss_ranking_read(jsonb_build_object('edition_id',pg_temp.rb_id('edition')))->>'can_manage'='true');
select pg_temp.check('bridge-only manager appears in native navigation','AUTHORIZATION',public.boss_ranking_read('{"view":"navigation"}')->>'navigation_available'='true');
select pg_temp.denied('manager has no neighboring edition authority',format('select public.boss_ranking_read(%L::jsonb)',jsonb_build_object('edition_id',pg_temp.rb_id('other-edition'))),'PT403');
select pg_temp.denied('competition manager has no athlete peer authority',format('select public.boss_ranking_read(%L::jsonb)',pg_temp.rb_q('leaderboard','definition')),'PT403');
select pg_temp.denied('competition manager cannot create private athlete product',format('select public.boss_ranking_mutate(%L::jsonb)',jsonb_build_object('action','definition.create','request_id',gen_random_uuid(),'input',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'source_organization_id',pg_temp.f('org'),'product','leaderboard','source_kind','athlete_season','name','Forbidden','metric_key','home_runs','metric_kind','count','direction','high','qualification','{}'::jsonb))),'PT403');
select pg_temp.denied('manager cannot delegate broader authority',format('select public.boss_ranking_mutate(%L::jsonb)',jsonb_build_object('action','access.grant','request_id',gen_random_uuid(),'input',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'person_id',pg_temp.f('parent'),'ends_at',clock_timestamp()+interval'1 hour'))),'PT403');
select pg_temp.rb('policy.activate',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'configuration',pg_temp.rb_policy(),'reason','Exact synthetic competition manager'),'manager-policy');
select pg_temp.actor('admin');
select pg_temp.rb('access.end',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'assignment_id',pg_temp.rb_id('manager')));
select pg_temp.actor('household-only');
select pg_temp.denied('revoked manager cannot read resource merely by knowing id',format('select public.boss_ranking_read(%L::jsonb)',pg_temp.rb_q()),'PT403');
select pg_temp.denied('stale manager mutation denied after revocation',format('select public.boss_ranking_mutate(%L::jsonb)',jsonb_build_object('action','policy.activate','request_id',gen_random_uuid(),'input',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'configuration',pg_temp.rb_policy(),'reason','Forbidden stale manager'))),'PT403');
select pg_temp.actor('other-admin');
select pg_temp.rb('entry.approve',jsonb_build_object('edition_id',pg_temp.rb_id('other-edition'),'entry_id',pg_temp.rb_id('foreign-entry')));
select pg_temp.check('foreign source owner gets safe TEAM audience','ISOLATION',jsonb_array_length(public.boss_ranking_read(jsonb_build_object('edition_id',pg_temp.rb_id('other-edition')))->'entries')=1);
select pg_temp.denied('foreign owner cannot manage competition policy',format('select public.boss_ranking_mutate(%L::jsonb)',jsonb_build_object('action','policy.activate','request_id',gen_random_uuid(),'input',jsonb_build_object('edition_id',pg_temp.rb_id('other-edition'),'configuration',pg_temp.rb_policy(),'reason','Forbidden cross-org management'))),'PT403');
select pg_temp.denied('safe TEAM audience gives no cross-org private athletes',format('select public.boss_ranking_read(%L::jsonb)',pg_temp.rb_q('leaderboard','definition')),'PT403');
select pg_temp.actor('scorer');
select pg_temp.denied('scorekeeper is not competition manager',format('select public.boss_ranking_mutate(%L::jsonb)',jsonb_build_object('action','group.create','request_id',gen_random_uuid(),'input',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'name','Forbidden','kind','pool'))),'PT403');
select pg_temp.actor('admin');
select pg_temp.denied('forged edition denied',format('select public.boss_ranking_read(%L::jsonb)',jsonb_build_object('edition_id',gen_random_uuid(),'product','standings')),'PT403');
select pg_temp.denied('forged definition denied',format('select public.boss_ranking_read(%L::jsonb)',pg_temp.rb_q('leaderboard',null,jsonb_build_object('definition_id',gen_random_uuid()))),'PT403');
select pg_temp.denied('wrong edition definition denied',format('select public.boss_ranking_read(%L::jsonb)',jsonb_build_object('edition_id',pg_temp.rb_id('other-edition'),'product','leaderboard','definition_id',pg_temp.rb_id('definition'))),'PT403');
select pg_temp.denied('cross-edition group forged rebuild denied',format('select public.boss_ranking_mutate(%L::jsonb)',jsonb_build_object('action','ranking.rebuild','request_id',gen_random_uuid(),'input',jsonb_build_object('edition_id',pg_temp.rb_id('other-edition'),'product','standings','group_id',pg_temp.rb_id('division')))),'PT422');
select pg_temp.actor('parent');
select pg_temp.denied('guardian-only receipt cannot rebuild private leaderboard',format('select public.boss_ranking_mutate(%L::jsonb)',jsonb_build_object('action','ranking.rebuild','request_id',gen_random_uuid(),'input',pg_temp.rb_q('leaderboard','definition'))),'PT403');
reset role;
select count(*)passed_assertions from pg_temp.phase5a_assertions;
rollback;
