#!/usr/bin/env bash
# Nine real two-connection Phase 6E races on the private disposable socket.
set -euo pipefail
umask 077
: "${PG_BINDIR:?Disposable runner required}" "${PGHOST:?Disposable runner required}" "${PGPORT:?Disposable runner required}" "${PGDATABASE:?Disposable runner required}" "${PGUSER:?Disposable runner required}"
if [[ "$PGHOST" != /tmp/boss-db-test.*/socket || ! -S "$PGHOST/.s.PGSQL.5432" || "$PGPORT" != 5432 || "$PGDATABASE" != postgres || "$PGUSER" != postgres ]];then printf '%s\n' 'Phase6E races require the private disposable runner socket.' >&2;exit 1;fi
test_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd);race_dir=${PGHOST%/socket}
psql_cmd=("$PG_BINDIR/psql" --no-psqlrc --no-password --host "$PGHOST" --port "$PGPORT" --username "$PGUSER" --dbname "$PGDATABASE" --set ON_ERROR_STOP=1 --set VERBOSITY=verbose --quiet --no-align --tuples-only)
writer_pid='';contender_pid='';input_open=false;race_count=0
cleanup(){ local result=$?;trap - EXIT INT TERM;if [[ "$input_open" == true ]];then exec 9>&-;fi;for pid in "$writer_pid" "$contender_pid";do [[ -z "$pid" ]]||{ kill "$pid" >/dev/null 2>&1||true;wait "$pid" >/dev/null 2>&1||true;};done;exit "$result";};trap cleanup EXIT;trap 'exit 130' INT;trap 'exit 143' TERM
fail(){ printf 'Phase6E concurrency invariant failed: %s\n' "$1" >&2;exit 1; }
assert_sql(){ [[ $("${psql_cmd[@]}" --command "$2") == t ]]||fail "$1"; }
await_state(){ local app=$1 expected=$2 pid=$3 deadline=$((SECONDS+7)) query;if [[ "$expected" == ready ]];then query="select count(*) from pg_stat_activity where application_name='$app'and state='idle in transaction'and query like'%phase6e-writer-ready%'";else query="select count(*) from pg_stat_activity where application_name='$app'and wait_event_type='Lock'";fi;while((SECONDS<deadline));do kill -0 "$pid" >/dev/null 2>&1||return 1;[[ $("${psql_cmd[@]}" --command "$query") == 1 ]]&&return 0;sleep .025;done;return 1; }
race(){ local label=$1 writer_sql=$2 contender_sql=$3 expected=$4;local fifo="$race_dir/phase6e-$label.stdin" rc=0;mkfifo -m 600 "$fifo";"${psql_cmd[@]}" <"$fifo" >"$race_dir/$label-w.out" 2>"$race_dir/$label-w.err"&writer_pid=$!;exec 9>"$fifo";input_open=true;printf '%s\n' "set application_name='boss_phase6e_${label}_writer';set statement_timeout='8s';begin;$writer_sql select 1 /* phase6e-writer-ready */;" >&9;await_state "boss_phase6e_${label}_writer" ready "$writer_pid"||{ head -n 8 "$race_dir/$label-w.err" >&2;fail "$label writer readiness";};"${psql_cmd[@]}" --command "set application_name='boss_phase6e_${label}_contender';set statement_timeout='8s';begin;$contender_sql commit;" >"$race_dir/$label-c.out" 2>"$race_dir/$label-c.err"&contender_pid=$!;await_state "boss_phase6e_${label}_contender" waiting "$contender_pid"||fail "$label contender did not block";printf '%s\n' 'commit;' >&9;exec 9>&-;input_open=false;wait "$writer_pid"||fail "$label writer";writer_pid='';if wait "$contender_pid";then rc=0;else rc=$?;fi;contender_pid='';if [[ "$expected" == success && "$rc" != 0 ]];then fail "$label contender";fi;if [[ "$expected" != success ]]&&{ [[ "$rc" == 0 ]]||! grep -Fq "$expected" "$race_dir/$label-c.err";};then fail "$label expected $expected";fi;race_count=$((race_count+1)); }
snapshot_race(){ local label=$1 writer_sql=$2 read_sql=$3 post_assert=$4;local fifo="$race_dir/phase6e-$label.stdin";mkfifo -m 600 "$fifo";"${psql_cmd[@]}" <"$fifo" >"$race_dir/$label-w.out" 2>"$race_dir/$label-w.err"&writer_pid=$!;exec 9>"$fifo";input_open=true;printf '%s\n' "set application_name='boss_phase6e_${label}_writer';set statement_timeout='8s';begin;$writer_sql select 1 /* phase6e-writer-ready */;" >&9;await_state "boss_phase6e_${label}_writer" ready "$writer_pid"||{ head -n 8 "$race_dir/$label-w.err" >&2;fail "$label writer readiness";};"${psql_cmd[@]}" --command "set statement_timeout='8s';$read_sql" >"$race_dir/$label-read.out" 2>"$race_dir/$label-read.err"||fail "$label snapshot read";printf '%s\n' 'commit;' >&9;exec 9>&-;input_open=false;wait "$writer_pid"||fail "$label writer";writer_pid='';assert_sql "$label post-commit" "$post_assert";race_count=$((race_count+1)); }
auth(){ printf '%s' "set local role authenticated;select set_config('request.jwt.claims',jsonb_build_object('sub',md5('boss-phase6e-race-base:auth-$1')::uuid,'role','authenticated','is_anonymous',false,'session_id',md5('boss-phase6e-race-base:session-$1')::uuid)::text,true);"; }
mutate(){ printf '%s' "$(auth "$1")select public.boss_achievement_mutate(jsonb_build_object('action','$2','request_id',gen_random_uuid(),'input',$3));reset role;"; }
# Flatten only synthetic fixture includes into an independent committed namespace.
sed -e 's/boss-phase5a-test:/boss-phase6e-race-base:/g' -e 's/phase5a.example.invalid/phase6e-race.example.invalid/g' -e 's/synthetic-phase5a-/synthetic-phase6e-race-/g' "$test_dir/phase5a/fixture.sql" >"$race_dir/phase6e-fixture.sql"
awk '$0!="\\ir ../phase5a/fixture.sql" {gsub(/boss-phase5d-test:/,"boss-phase6e-race-roster:");print}' "$test_dir/phase5d/fixture.sql" >>"$race_dir/phase6e-fixture.sql"
for item in 'phase5f phase5d' 'phase6b phase5f' 'phase6d phase6b' 'phase6e phase6d';do read -r phase parent <<<"$item";awk '$0 !~ /^\\ir / {print}' "$test_dir/$phase/fixture.sql" >>"$race_dir/phase6e-fixture.sql";done
cat >"$race_dir/phase6e-setup.sql" <<SQL
begin;set local statement_timeout='8s';\ir '$race_dir/phase6e-fixture.sql'
update public.guardian_relationships set can_manage_profile=true where id=pg_temp.f('guardian-child1');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.pe('award.nominate',jsonb_build_object('definition_id',pg_temp.pe_id('manual_mvp'),'organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'season_id',pg_temp.f('season'),'profile_id',pg_temp.pe_id('profile'),'achieved_at',clock_timestamp(),'note','Synthetic race decision'),'nomination');
select pg_temp.rb('definition.create',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'source_organization_id',pg_temp.f('org'),'season_id',pg_temp.f('season'),'product','records','source_kind','athlete_season','name','Synthetic race record','metric_key','home_runs','metric_kind','count','direction','high','qualification','{}'::jsonb,'competition_only',false),'record');
select pg_temp.rb('ranking.rebuild',pg_temp.rb_q('records','record'));
select pg_temp.pe_definition('race_record',jsonb_build_object('name','Synthetic race record badge','subject_type','athlete','category','record','source_kind','record','sport_key','baseball','ranking_definition_id',pg_temp.rb_id('record'),'historical_evaluation',true));select pg_temp.pe_evaluate('race_record');
select pg_temp.pe_definition('race_champion',jsonb_build_object('name','Synthetic race champion','subject_type','team','category','tournament','source_kind','tournament','sport_key','baseball','bracket_id',pg_temp.td_id('bracket'),'placement',1,'historical_evaluation',true));select pg_temp.pe_evaluate('race_champion');
reset role;
insert into pg_temp.phase6d_ids select'semi1',id from public.tournament_matches where bracket_id=pg_temp.td_id('bracket')and round_number=1 and match_number=1;
insert into pg_temp.phase6d_ids select'semi2',id from public.tournament_matches where bracket_id=pg_temp.td_id('bracket')and round_number=1 and match_number=2;
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.td('ruling.create',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'match_id',pg_temp.td_id('semi1'),'expected_version',1,'kind','forfeit','winner_entry_id',pg_temp.rb_id('falcons-entry'),'loser_entry_id',pg_temp.rb_id('wildcats-entry'),'reason','Synthetic first semifinal'));
select pg_temp.td('ruling.create',jsonb_build_object('edition_id',pg_temp.rb_id('edition'),'match_id',pg_temp.td_id('semi2'),'expected_version',1,'kind','forfeit','winner_entry_id',pg_temp.rb_id('hawks-entry'),'loser_entry_id',pg_temp.rb_id('eagles-entry'),'reason','Synthetic second semifinal'));
select pg_temp.pe_evaluate('career_one');
reset role;
insert into pg_temp.phase6e_ids select'honor',athlete_achievement_id from public.achievement_recognitions where definition_revision_id=(select current_revision_id from public.achievement_definitions where id=pg_temp.pe_id('career_one'));
set local role authenticated;select pg_temp.actor('parent');
select(public.boss_athlete_profile_mutate(jsonb_build_object('action','showcase.create','request_id',gen_random_uuid(),'input',jsonb_build_object('profile_id',pg_temp.pe_id('profile'))))->>'showcase_id')::uuid race_showcase \gset
insert into pg_temp.phase6e_ids values('showcase',:'race_showcase');
select public.boss_athlete_profile_mutate(jsonb_build_object('action','showcase.revise','request_id',gen_random_uuid(),'input',jsonb_build_object('showcase_id',pg_temp.pe_id('showcase'),'expected_version',1,'profile_revision_id',public.boss_athlete_profile_read(pg_temp.pe_id('profile'),null)->'profile'->'profile'->>'current_revision_id','sport_keys',jsonb_build_array('baseball'),'visible_categories',jsonb_build_array('overview','achievements'),'stat_metric_keys','[]'::jsonb,'presentation','{}'::jsonb)));
select public.boss_athlete_profile_mutate(jsonb_build_object('action','consent.grant','request_id',gen_random_uuid(),'input',jsonb_build_object('showcase_id',pg_temp.pe_id('showcase'),'showcase_revision_id',public.boss_athlete_profile_read(pg_temp.pe_id('profile'),null)->'profile'->'showcase'->>'current_revision_id','approved_categories',jsonb_build_array('overview','achievements'),'expires_at',clock_timestamp()+interval'1 hour')));
select pg_temp.pe('display.set',jsonb_build_object('achievement_id',pg_temp.pe_id('honor'),'show_on_profile',true,'show_on_showcase',true));
select public.boss_athlete_profile_mutate(jsonb_build_object('action','showcase.publish','request_id',gen_random_uuid(),'input',jsonb_build_object('showcase_id',pg_temp.pe_id('showcase'),'expected_version',3)));
select public.boss_athlete_profile_mutate(jsonb_build_object('action','share.create','request_id',gen_random_uuid(),'input',jsonb_build_object('showcase_id',pg_temp.pe_id('showcase'),'token_digest',repeat('f',64),'token_prefix','synthetic','expires_at',clock_timestamp()+interval'1 hour')));
reset role;commit;
SQL
if ! "${psql_cmd[@]}" --file "$race_dir/phase6e-setup.sql" >"$race_dir/setup6e.out" 2>"$race_dir/setup6e.err";then head -n 5 "$race_dir/setup6e.err" >&2;fail setup;fi
lookup(){ "${psql_cmd[@]}" --command "$1"; }
org="md5('boss-phase6e-race-base:org')::uuid";child="md5('boss-phase6e-race-base:child1')::uuid";falcons="md5('boss-phase6e-race-base:falcons')::uuid";wildcats="md5('boss-phase6e-race-base:wildcats')::uuid"
profile=$(lookup "select id from public.athlete_profiles where person_id=$child");definition=$(lookup "select id from public.achievement_definitions where organization_id=$org and definition_key='career_one'");revision=$(lookup "select current_revision_id from public.achievement_definitions where id='$definition'");honor=$(lookup "select athlete_achievement_id from public.achievement_recognitions where definition_revision_id='$revision'");nomination=$(lookup "select id from public.award_nominations where profile_id='$profile'");guardian=$(lookup "select id from public.guardian_relationships where dependent_person_id=$child");scope=$(lookup "select id from public.ranking_scopes where definition_id=(select ranking_definition_id from public.achievement_definition_revisions where definition_id=(select id from public.achievement_definitions where organization_id=$org and definition_key='race_record'))");record_definition=$(lookup "select id from public.achievement_definitions where organization_id=$org and definition_key='race_record'");champion_definition=$(lookup "select id from public.achievement_definitions where organization_id=$org and definition_key='race_champion'");final=$(lookup "select id from public.tournament_matches where bracket_id=(select bracket_id from public.achievement_definition_revisions where definition_id='$champion_definition')and label='Round 2 · Match 1'");edition=$(lookup "select edition_id from public.tournament_matches where id='$final'");winner=$(lookup "select id from public.competition_entries where edition_id='$edition'and team_id=$falcons");loser=$(lookup "select id from public.competition_entries where edition_id='$edition'and team_id=md5('boss-phase6e-race-base:hawks')::uuid")
showcase=$(lookup "select id from public.recruiting_showcases where profile_id='$profile'")
eval_input="jsonb_build_object('definition_id','$definition')"
# 1. Two real evaluations serialize on the definition/work fence; one honor remains.
race simultaneous_evaluations "$(mutate admin definition.rebuild "$eval_input")" "$(mutate admin definition.evaluate "$eval_input")" success
assert_sql 'no duplicate milestone' "select count(*)=1 from public.achievement_recognitions where definition_revision_id='$revision'"
# 2. Record generation invalidation blocks badge evaluation and prevents stale current status.
race record_badge "update public.ranking_scopes set target_generation=target_generation+1,state='pending'where id='$scope';" "$(mutate admin definition.evaluate "jsonb_build_object('definition_id','$record_definition')")" success
assert_sql 'record unavailable while generation pending' "select bool_and(boss_private.achievement_live_state(r)<>'current')from public.achievement_recognitions r where definition_revision_id=(select current_revision_id from public.achievement_definitions where id='$record_definition')"
# 3. Approval and revocation cannot both accept the same optimistic version.
race approval_revoke "$(mutate admin award.approve "jsonb_build_object('nomination_id','$nomination','expected_version',1,'note','Synthetic approved')")" "$(mutate admin award.revoke "jsonb_build_object('nomination_id','$nomination','expected_version',1,'note','Synthetic revoked')")" PT409
# 4. Guardian badge publication waits behind correction; public output never trusts stale state.
snapshot_race publication_correction "update public.stat_origin_summaries set is_current=false where person_id=$child and sport_key='baseball';" "begin;$(auth parent)select public.boss_athlete_profile_mutate(jsonb_build_object('action','showcase.publish','request_id',gen_random_uuid(),'input',jsonb_build_object('showcase_id','$showcase','expected_version',4)));commit;" "select jsonb_array_length(public.boss_recruiting_showcase_read(repeat('f',64))->'achievements')=0"
"${psql_cmd[@]}" --command "update public.stat_origin_summaries set is_current=true where person_id=$child and sport_key='baseball'" >/dev/null
# 5. Canonical championship ruling and the worker contend on work generation.
race tournament_worker "$(auth admin)select public.boss_tournament_mutate(jsonb_build_object('action','ruling.create','request_id',gen_random_uuid(),'input',jsonb_build_object('edition_id','$edition','match_id','$final','expected_version',3,'kind','forfeit','winner_entry_id','$winner','loser_entry_id','$loser','reason','Synthetic championship race')));reset role;" "$(mutate admin definition.evaluate "jsonb_build_object('definition_id','$champion_definition')")" success
# 6. Revised thresholds retain the old immutable earned meaning.
race revision_evaluation "$(mutate admin definition.revise "jsonb_build_object('definition_id','$definition','expected_version',1,'revision',jsonb_build_object('name','Synthetic revised milestone','subject_type','athlete','category','statistical_milestone','source_kind','athlete_career','sport_key','baseball','team_id',$falcons,'metric_key','home_runs','threshold',2,'historical_evaluation',true,'showcase_eligible',true))")" "$(mutate admin definition.evaluate "$eval_input")" success
assert_sql 'old definition history retained' "select threshold=1 from public.achievement_definition_revisions where id='$revision'"
# 7. Revoked guardian cannot complete a blocked display/publication operation.
race guardian_publication "update public.guardian_relationships set authority_status='inactive'where id='$guardian';" "$(mutate parent display.set "jsonb_build_object('achievement_id','$honor','show_on_profile',true,'show_on_showcase',true)")" PT403
"${psql_cmd[@]}" --command "update public.guardian_relationships set authority_status='active'where id='$guardian'" >/dev/null
# 8. Membership end and staff read are snapshot coherent; no post-commit prior-origin authority.
snapshot_race transfer_read "update public.team_memberships set status='inactive',ends_at=clock_timestamp()where participant_id=(select participant_id from public.athlete_profiles where id='$profile')and team_id=$falcons;" "begin;$(auth coach)select public.boss_achievement_read(jsonb_build_object('profile_id','$profile'));commit;" "select not boss_private.athlete_staff_origin(md5('boss-phase6e-race-base:coach')::uuid,'athlete_profiles.view','$profile',$org,$falcons)"
# 9. A source correction invalidates work before a blocked rebuild can publish.
race rebuild_correction "update public.stat_origin_summaries set is_current=false where person_id=$child and sport_key='baseball';" "$(mutate admin definition.rebuild "$eval_input")" success
assert_sql 'rebuild cannot publish dirty source' "select state='unavailable'from public.achievement_refresh_work where definition_revision_id=(select current_revision_id from public.achievement_definitions where id='$definition')"
printf 'Phase6E coordinated races passed: %s\n' "$race_count"
