\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase7d/fixture.sql
set local role authenticated;select pg_temp.actor('parent');
insert into payment_results values('ach-split',public.boss_payments_mutate(jsonb_build_object('action','checkout.prepare','request_id',pg_temp.f('ach-split-request'),'input',jsonb_build_object('organization_id',pg_temp.f('org'),'routing_id',pg_temp.f('rails-route'),'method','ach','currency','USD','bucks_minor',3000,'wallet_id',pg_temp.w(),'allocations',jsonb_build_array(jsonb_build_object('charge_id',pg_temp.f('charge-camp'),'amount_minor',10000,'bucks_minor',3000))))));reset role;
insert into payment_results select 'ach-claim',boss_private.rails_worker_claim((select(result->>'checkout_id')::uuid from payment_results where label='ach-split'));
select boss_private.rails_worker_finish((select(result->>'checkout_id')::uuid from payment_results where label='ach-split'),(select(result->>'operation_id')::uuid from payment_results where label='ach-claim'),(select(result->>'generation')::timestamptz from payment_results where label='ach-claim'),'{"state":"ach_pending","transaction_reference":"LOCAL-ACH-SPLIT","amount_minor":"7000","currency":"USD"}','ach-split-pending',repeat('a',64));
select pg_temp.check('ACH split pending creates no payment or permanent wallet debit','ACH SPLIT',not exists(select 1 from public.payments)and not exists(select 1 from public.boss_bucks_consumptions));
select pg_temp.check('ACH split retains both grant and charge reservations','ACH SPLIT',boss_private.bucks_available(pg_temp.w())=2000 and boss_private.registration_charge_balance(pg_temp.f('charge-camp'))->>'balance_due_minor'='10000'and boss_private.rails_charge_reserved(pg_temp.f('charge-camp'))=10000);
select pg_temp.check('pending ACH replay claims original operation without redispatch','ACH SPLIT',boss_private.rails_worker_claim((select(result->>'checkout_id')::uuid from payment_results where label='ach-split'))->>'first_dispatch'='false');
select boss_private.rails_worker_finish((select(result->>'checkout_id')::uuid from payment_results where label='ach-split'),(select(result->>'operation_id')::uuid from payment_results where label='ach-claim'),(select(result->>'generation')::timestamptz from payment_results where label='ach-claim'),'{"state":"settled","transaction_reference":"LOCAL-ACH-SPLIT","amount_minor":"7000","currency":"USD"}','ach-split-final',repeat('b',64));
select boss_private.rails_worker_finish((select(result->>'checkout_id')::uuid from payment_results where label='ach-split'),(select(result->>'operation_id')::uuid from payment_results where label='ach-claim'),(select(result->>'generation')::timestamptz from payment_results where label='ach-claim'),'{"state":"settled","transaction_reference":"LOCAL-ACH-SPLIT","amount_minor":"7000","currency":"USD"}','ach-split-final',repeat('b',64));
select pg_temp.check('approved ACH split final success creates one external and one Bucks tender','ACH SPLIT',(select count(*)=2 from public.payments)and(select count(*)=1 from public.external_payment_tenders)and(select count(*)=1 from public.boss_bucks_tenders)and boss_private.registration_charge_balance(pg_temp.f('charge-camp'))->>'balance_due_minor'='0');
select boss_private.rails_worker_finish((select(result->>'checkout_id')::uuid from payment_results where label='ach-split'),(select(result->>'operation_id')::uuid from payment_results where label='ach-claim'),(select(result->>'generation')::timestamptz from payment_results where label='ach-claim'),'{"state":"returned","transaction_reference":"LOCAL-ACH-SPLIT","amount_minor":"7000","currency":"USD"}','ach-split-return',repeat('c',64));
select pg_temp.check('authoritative ACH return reverses only the original external leg','ACH SPLIT',(select count(*)=1 from public.payments where status='reversed'and method='ach'and amount_minor=7000)and boss_private.bucks_available(pg_temp.w())=2000 and boss_private.registration_charge_balance(pg_temp.f('charge-camp'))->>'balance_due_minor'='7000');
do $$declare p uuid;a uuid;begin
 select payment_id into p from public.boss_bucks_tenders where original_payment_id is null;
 select id into a from public.payment_allocations where payment_id=p and status='applied';perform pg_temp.actor('admin');
 perform public.boss_bucks_mutate(jsonb_build_object('action','payment.reverse','request_id',pg_temp.f('ach-split-bucks-return'),'input',jsonb_build_object('payment_id',p,'reason','Synthetic explicit separate Bucks leg','allocations',jsonb_build_array(jsonb_build_object('allocation_id',a,'amount_minor',3000)))));
end$$;
select pg_temp.check('explicit original Bucks return restores original value independently','ACH SPLIT',boss_private.bucks_available(pg_temp.w())=5000 and boss_private.registration_charge_balance(pg_temp.f('charge-camp'))->>'balance_due_minor'='10000');
select pg_temp.check('ACH split reversal retains complete immutable original-tender chronology','ACH SPLIT',(select count(*)=2 from public.payments where status='recorded')and(select count(*)=2 from public.payments where status='reversed')and not exists(select 1 from public.boss_bucks_restorations r join public.boss_bucks_consumptions c on c.id=r.consumption_id join public.boss_bucks_journals j on j.id=r.journal_id where j.grant_id<>c.grant_id));
-- Recovery rehearsal uses an actual active module row and its version-owning
-- trigger. Synthetic baseline/activation/restoration remain rollback-only.
do $$declare g jsonb;h jsonb;at_time timestamptz:=clock_timestamp();old_end timestamptz:=clock_timestamp()-interval'1 day';begin
 perform pg_temp.check('administrator-first recovery verification remains valid','CLEANUP',boss_private.rails_role(pg_temp.f('admin'),'settlements.view',pg_temp.f('org')));
 update public.guardian_relationships set authority_status='inactive',can_manage_payments=false,ends_at=old_end where id=pg_temp.f('guardian-child1');
 update public.household_memberships set status='inactive',ends_at=old_end where household_id=pg_temp.f('household')and person_id in(pg_temp.f('parent'),pg_temp.f('child1'));
 select to_jsonb(x)-'updated_at' into g from public.guardian_relationships x where id=pg_temp.f('guardian-child1');
 select jsonb_agg(to_jsonb(x)-'updated_at'order by id)into h from public.household_memberships x where household_id=pg_temp.f('household')and person_id in(pg_temp.f('parent'),pg_temp.f('child1'));
 update public.guardian_relationships set authority_status='active',can_manage_payments=true,ends_at=at_time+interval'30 minutes'where id=pg_temp.f('guardian-child1');
 update public.household_memberships set status='active',ends_at=at_time+interval'30 minutes'where household_id=pg_temp.f('household')and person_id in(pg_temp.f('parent'),pg_temp.f('child1'));
 update public.guardian_relationships set authority_status='inactive',can_manage_payments=false,ends_at=old_end where id=pg_temp.f('guardian-child1');
 update public.household_memberships set status='inactive',ends_at=old_end where household_id=pg_temp.f('household')and person_id in(pg_temp.f('parent'),pg_temp.f('child1'));
 perform pg_temp.check('controlled relationship restoration equals the exact selected baseline','CLEANUP',g=(select to_jsonb(x)-'updated_at'from public.guardian_relationships x where id=pg_temp.f('guardian-child1'))and h=(select jsonb_agg(to_jsonb(x)-'updated_at'order by id)from public.household_memberships x where household_id=pg_temp.f('household')and person_id in(pg_temp.f('parent'),pg_temp.f('child1'))));
 update public.organization_modules set status='inactive',configuration='{}',ends_at=clock_timestamp()where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='payments');
 perform pg_temp.check('active temporary module is explicitly ended using trigger-owned revisioning','CLEANUP',exists(select 1 from public.organization_modules where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='payments')and status='inactive'and configuration='{}'::jsonb and ends_at<=clock_timestamp()));
end$$;
set constraints all immediate;
select count(*)passed_assertions,'Phase 7D ACH fee split and explicit original-tender return' suite from phase5a_assertions;rollback;
