-- One-time/recurring identity and Calendar material changes through actual RPCs.
begin;
\ir phase5a/fixture.sql
create temp table phase5a_calendar_commands(label text primary key,command jsonb not null) on commit drop;
grant select on phase5a_calendar_commands to authenticated;
create function pg_temp.capture_calendar(label text,event_label text,extra jsonb default '{}') returns void language plpgsql as $$begin
 insert into pg_temp.phase5a_calendar_commands values(label,
 (select pg_temp.cmd('event.update',jsonb_build_object('organization_id',e.organization_id,'event_id',e.id,'expected_version',e.version,'title',e.title,'description',e.description,'event_type_key',e.event_type_key,'start_at',e.start_at,'end_at',e.end_at,'timezone',e.timezone,'all_day',e.all_day,'arrival_at',e.arrival_at,'status',e.status,'visibility',e.visibility,'publication_state',e.publication_state,'venue_id',e.venue_id,'resource_id',e.resource_id,'instructions',e.instructions,'rsvp_mode',e.rsvp_mode,'audience',to_jsonb(e.audience),'recurrence',e.recurrence,
 'targets',(select jsonb_agg(jsonb_build_object('target_type',t.target_type,'target_id',t.target_id)) from public.event_targets t where t.event_id=e.id),'reminders','[]'::jsonb,
 'game',(select jsonb_build_object('opponent_team_id',d.opponent_team_id,'external_opponent_name',d.external_opponent_name,'home_away',d.home_away,'game_status',d.game_status) from public.event_game_details d where d.event_id=e.id))||extra) from public.events e where e.id=pg_temp.f('event-'||event_label)));
end$$;
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.create_game('calendar','calendar');
select pg_temp.create_game('recurring-first','recurring');
select pg_temp.create_game('recurring-second','recurring','falcons','basketball',1);
select pg_temp.game_op('game.roster.snapshot','calendar');
select pg_temp.game_op('game.operator.assign','calendar',jsonb_build_object('person_id',pg_temp.f('admin'),'role_assignment_id',pg_temp.f('role-admin'),'function_key','game_administrator','team_id',pg_temp.f('falcons'),'ends_at',now()+interval '1 hour'));
reset role;
select pg_temp.check('recurring occurrences each own distinct canonical game','RECURRENCE',(select count(*)=2 and count(distinct occurrence_key)=2 from public.games where event_id=pg_temp.f('event-recurring')));
select pg_temp.check('singleton original key has no dependency on attendance rows','CALENDAR',not exists(select 1 from public.attendance_responses where event_id=pg_temp.f('event-calendar')) and not exists(select 1 from public.attendance_checkins where event_id=pg_temp.f('event-calendar')));
select pg_temp.capture_calendar('move-single','calendar',jsonb_build_object('start_at',date_trunc('day',now())+interval '20 days 19 hours','end_at',date_trunc('day',now())+interval '20 days 21 hours'));
set local role authenticated;
select public.boss_calendar_mutate((select command from phase5a_calendar_commands where label='move-single'),pg_temp.f('calendar-move-single'));
select pg_temp.check('Game Center presents moved singleton schedule','CALENDAR',(select (g->>'start_at')::timestamptz=date_trunc('day',now())+interval '20 days 19 hours' and g->>'id'=(select id::text from pg_temp.phase5a_games where label='calendar') from jsonb_array_elements(public.boss_games_read(pg_temp.query('calendar'))->'games')g));
select pg_temp.conflict('stale game operation rejected after Calendar context change',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('stale-calendar-start'),pg_temp.game_command('game.start','calendar')));
reset role;
select pg_temp.check('reschedule retains singleton game id and original identity key','CALENDAR',(select count(*)=1 and bool_and(occurrence_key=pg_temp.key()) from public.games where event_id=pg_temp.f('event-calendar')));
update pg_temp.phase5a_games saved set version=current.version from public.games current where saved.id=current.id;
select pg_temp.capture_calendar('wrong-type','calendar','{"event_type_key":"practice","game":null}');
set local role authenticated;
select pg_temp.actor('parent');
select pg_temp.denied('known linked event edit denies before competitive identity errors',format('select public.boss_calendar_mutate(%L,%L)',(select command from phase5a_calendar_commands where label='wrong-type'),pg_temp.f('calendar-forged-parent-type')));
select pg_temp.actor('other-admin');
select pg_temp.denied('cross-tenant linked event edit denies before competitive identity errors',format('select public.boss_calendar_mutate(%L,%L)',(select command from phase5a_calendar_commands where label='wrong-type'),pg_temp.f('calendar-forged-other-type')));
select pg_temp.actor('admin');
select pg_temp.conflict('linked game cannot silently become practice',format('select public.boss_calendar_mutate(%L,%L)',(select command from phase5a_calendar_commands where label='wrong-type'),pg_temp.f('calendar-wrong-type')));
reset role;
select pg_temp.capture_calendar('changed-opponent','calendar','{"game":{"opponent_team_id":null,"external_opponent_name":"Synthetic Different Opponent","home_away":"home","game_status":"scheduled"}}');
set local role authenticated;
select pg_temp.actor('parent');
select pg_temp.denied('known linked matchup edit denies before opponent integrity errors',format('select public.boss_calendar_mutate(%L,%L)',(select command from phase5a_calendar_commands where label='changed-opponent'),pg_temp.f('calendar-forged-parent-opponent')));
select pg_temp.actor('admin');
select pg_temp.conflict('linked matchup cannot silently rewrite opponent',format('select public.boss_calendar_mutate(%L,%L)',(select command from phase5a_calendar_commands where label='changed-opponent'),pg_temp.f('calendar-opponent')));
select pg_temp.game_op('game.start','calendar');
reset role;
select pg_temp.capture_calendar('postpone-live','calendar','{"status":"postponed"}');
set local role authenticated;
select public.boss_calendar_mutate((select command from phase5a_calendar_commands where label='postpone-live'),pg_temp.f('calendar-postpone-live'));
reset role;
select pg_temp.check('Calendar postponement suspends an already-started game','CALENDAR',(select status='suspended' and schedule_status='postponed' and started_at is not null from public.games where id=(select id from pg_temp.phase5a_games where label='calendar')));
update pg_temp.phase5a_games saved set version=current.version from public.games current where saved.id=current.id;
set local role authenticated;
select pg_temp.state_denied('postponed Calendar occurrence blocks suspended game scoring',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('postponed-score'),pg_temp.game_command('game.score.set','calendar','{"primary_score":1,"opponent_score":0}')));
reset role;
select pg_temp.capture_calendar('restore-live-schedule','calendar','{"status":"scheduled"}');
set local role authenticated;
select public.boss_calendar_mutate((select command from phase5a_calendar_commands where label='restore-live-schedule'),pg_temp.f('calendar-restore-live'));
reset role;
update pg_temp.phase5a_games saved set version=current.version from public.games current where saved.id=current.id;
set local role authenticated;
select pg_temp.game_op('game.transition','calendar','{"status":"live"}');
reset role;
select pg_temp.check('rescheduled suspended game resumes through explicit live transition','CALENDAR',(select status='live' and schedule_status='scheduled' and (select count(*)=1 from public.game_operations where game_id=games.id and operation='game.start') from public.games where id=(select id from pg_temp.phase5a_games where label='calendar')));
select pg_temp.capture_calendar('cancel-live','calendar','{"status":"canceled"}');
set local role authenticated;
select public.boss_calendar_mutate((select command from phase5a_calendar_commands where label='cancel-live'),pg_temp.f('calendar-cancel-live'));
reset role;
update pg_temp.phase5a_games saved set version=current.version from public.games current where saved.id=current.id;
select pg_temp.check('Calendar cancellation consistently stops live game','CALENDAR',(select status='canceled' from public.games where id=(select id from pg_temp.phase5a_games where label='calendar')));
select pg_temp.check('Calendar cancellation leaves roster and operation history','CALENDAR',exists(select 1 from public.game_roster_snapshots where game_id=(select id from pg_temp.phase5a_games where label='calendar')) and exists(select 1 from public.game_operations where game_id=(select id from pg_temp.phase5a_games where label='calendar')));
set local role authenticated;
select pg_temp.state_denied('canceled scheduled context cannot resume live scoring',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('cancel-score'),pg_temp.game_command('game.score.set','calendar','{"primary_score":1,"opponent_score":0}')));
reset role;
create temp table phase5a_exception_command as select pg_temp.cmd('event.exception',jsonb_build_object('event_id',id,'expected_version',version,'occurrence_key',pg_temp.key(),'override_start_at',start_at+interval '2 hours','override_end_at',end_at+interval '2 hours')) command from public.events where id=pg_temp.f('event-recurring');
grant select on phase5a_exception_command to authenticated;
set local role authenticated;
select public.boss_calendar_mutate((select command from phase5a_exception_command),pg_temp.f('calendar-recurring-move'));
select pg_temp.check('moved recurrence retains exact original game identity','RECURRENCE',(select (g->>'start_at')::timestamptz=date_trunc('day',now())+interval '20 days 20 hours' and g->>'occurrence_key'=pg_temp.key() and g->>'id'=(select id::text from pg_temp.phase5a_games where label='recurring-first') from jsonb_array_elements(public.boss_games_read(pg_temp.query('recurring-first'))->'games')g));
reset role;
truncate phase5a_exception_command;
insert into phase5a_exception_command select pg_temp.cmd('event.exception',jsonb_build_object('event_id',id,'expected_version',version,'occurrence_key',pg_temp.key(1),'status','canceled')) from public.events where id=pg_temp.f('event-recurring');
set local role authenticated;
select public.boss_calendar_mutate((select command from phase5a_exception_command),pg_temp.f('calendar-recurring-cancel'));
reset role;
select pg_temp.check('cancel only selected recurring game','RECURRENCE',(select status='canceled' from public.games where id=(select id from pg_temp.phase5a_games where label='recurring-second')) and (select status='scheduled' from public.games where id=(select id from pg_temp.phase5a_games where label='recurring-first')));
select pg_temp.capture_calendar('reset-series','recurring',jsonb_build_object('start_at',date_trunc('day',now())+interval '20 days 19 hours','end_at',date_trunc('day',now())+interval '20 days 21 hours','reset_exceptions',true));
set local role authenticated;
select pg_temp.conflict('series reset cannot orphan linked competitive occurrence',format('select public.boss_calendar_mutate(%L,%L)',(select command from phase5a_calendar_commands where label='reset-series'),pg_temp.f('calendar-series-reset')));
select pg_temp.conflict('game list refuses unbounded date horizon',format('select public.boss_games_read(%L)',pg_temp.query(null,jsonb_build_object('to',now()+interval '2 years'))));
select pg_temp.conflict('unknown generic engine state cannot be injected',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('engine-inject'),pg_temp.game_command('game.transition','calendar','{"status":"live","balls":4,"clock_running":true}')));
reset role;
select pg_temp.check('bounded games indexes include organization schedule','PERFORMANCE',exists(select 1 from pg_indexes where schemaname='public' and tablename='games' and indexdef like '%organization_id%' and (indexdef like '%scheduled_start_at%' or indexdef like '%scheduled_start%')));
select pg_temp.check('old canonical occurrences retained after failed series rewrite','RECURRENCE',(select count(*)=2 from public.games where event_id=pg_temp.f('event-recurring')) and (select count(*)=2 from public.event_occurrence_exceptions where event_id=pg_temp.f('event-recurring') and is_active));
set local role authenticated;
select pg_temp.create_game('sealed-calendar','history');
select pg_temp.game_op('game.roster.snapshot','sealed-calendar');
select pg_temp.game_op('game.operator.assign','sealed-calendar',jsonb_build_object('person_id',pg_temp.f('admin'),'role_assignment_id',pg_temp.f('role-admin'),'function_key','game_administrator','team_id',pg_temp.f('falcons'),'ends_at',now()+interval '1 hour'));
select pg_temp.game_op('game.start','sealed-calendar');
select pg_temp.game_op('game.score.set','sealed-calendar','{"primary_score":6,"opponent_score":2}');
select pg_temp.game_op('game.finalize','sealed-calendar');
reset role;
select pg_temp.capture_calendar('cancel-final','history','{"status":"canceled"}');
set local role authenticated;
select public.boss_calendar_mutate((select command from phase5a_calendar_commands where label='cancel-final'),pg_temp.f('calendar-cancel-final'));
reset role;
select pg_temp.check('Calendar cancellation preserves finalized competition state','FINAL',(select status='final' and schedule_status='canceled' and final_primary_score=6 and final_opponent_score=2 and roster_revision=1 and finalization_count=1 from public.games where id=(select id from pg_temp.phase5a_games where label='sealed-calendar')));
select pg_temp.check('Calendar cancellation preserves immutable sealed scores and roster','FINAL',(select count(*)=1 and bool_and(primary_score=6 and opponent_score=2 and roster_revision=1) from public.game_finalizations where game_id=(select id from pg_temp.phase5a_games where label='sealed-calendar')) and (select count(*)=1 from public.game_roster_snapshots where game_id=(select id from pg_temp.phase5a_games where label='sealed-calendar')));
select count(*) as passed_assertions,category from pg_temp.phase5a_assertions group by category order by category;
rollback;
