\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase8a/fixture.sql
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.mm('intent1','intent.create',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'revision_id',pg_temp.mid('offer'),'capability',pg_temp.proof('one'))));
select pg_temp.check('intent replay is idempotent','REPLAY',(pg_temp.mm('intent1','intent.create',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'revision_id',pg_temp.mid('offer'),'capability',pg_temp.proof('one'))))->>'replayed')::boolean);
select pg_temp.actor('staff');
select pg_temp.check('safe clerk verification','VERIFY',(pg_temp.mm('verify1','token.verify',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'capability',pg_temp.proof('one'))))->>'valid')::boolean);
select pg_temp.denied('wrong location cannot verify',format('select pg_temp.mm(''wrong-loc'',''token.verify'',%L)',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-b'),'capability',pg_temp.proof('one')))));
select pg_temp.mm('redeem1','token.redeem',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'capability',pg_temp.proof('one'))));
select pg_temp.check('same submission returns receipt without use','REPLAY',(pg_temp.mm('redeem1','token.redeem',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'capability',pg_temp.proof('one'))))->>'replayed')::boolean);
select pg_temp.denied('new request consumed token denied',format('select pg_temp.mm(''consumed'',''token.redeem'',%L)',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'capability',pg_temp.proof('one')))),'PT409');
select pg_temp.denied('stale verification receipt cannot assert consumed token valid',format('select pg_temp.mm(''verify1'',''token.verify'',%L)',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'capability',pg_temp.proof('one')))),'PT409');
reset role;set constraints all immediate;
select pg_temp.check('one immutable evidence row','ATOMIC',(select count(*)=1 from public.merchant_redemptions));
select pg_temp.check('digest only persisted','PRIVACY',(select bool_and(capability_digest<>pg_temp.proof('one'))from boss_private.merchant_redemption_intents));
select pg_temp.check('no receipt plaintext capability','PRIVACY',not exists(select 1 from boss_private.merchant_receipts where result::text like'%'||pg_temp.proof('one')||'%'));
select pg_temp.check('rebuild one use','USAGE',boss_private.merchant_usage(pg_temp.f('parent'),pg_temp.mid('family'),'lifetime')=1);
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.mm('intent2','intent.create',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'revision_id',pg_temp.mid('offer'),'capability',pg_temp.proof('two'))));
select pg_temp.mm('intent3','intent.create',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'revision_id',pg_temp.mid('offer'),'capability',pg_temp.proof('three'))));
select pg_temp.actor('assistant');select pg_temp.mm('redeem2','token.redeem',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'capability',pg_temp.proof('two'))));
select pg_temp.actor('staff');select pg_temp.denied('final use exhausted','select pg_temp.mm(''final-use'',''token.redeem'',pg_temp.mi(jsonb_build_object(''location_id'',pg_temp.mid(''loc-a''),''capability'',pg_temp.proof(''three''))))','PT409');
select pg_temp.actor('parent');select pg_temp.denied('new intent after limit denied','select pg_temp.mm(''exhausted-intent'',''intent.create'',pg_temp.mi(jsonb_build_object(''location_id'',pg_temp.mid(''loc-a''),''revision_id'',pg_temp.mid(''offer''),''capability'',pg_temp.proof(''four''))))','PT409');
select pg_temp.actor('admin');
select pg_temp.mm('correct1','redemption.correct',pg_temp.mi(jsonb_build_object('redemption_id',pg_temp.mr('redeem1')->>'redemption_id','reason','Reviewed synthetic redemption recorded in error','restore_allowance',true)));
reset role;
select pg_temp.check('explicit reviewed correction restores once','USAGE',boss_private.merchant_usage(pg_temp.f('parent'),pg_temp.mid('family'),'lifetime')=1);
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.denied('second correction cannot double restore',format('select pg_temp.mm(''correct2'',''redemption.correct'',%L)',pg_temp.mi(jsonb_build_object('redemption_id',pg_temp.mr('redeem1')->>'redemption_id','reason','Duplicate synthetic correction request','restore_allowance',true))),'23505');
select pg_temp.mm('end-clerk','access.end',pg_temp.mi(jsonb_build_object('assignment_id',pg_temp.mid('clerk'))));
select pg_temp.actor('staff');select pg_temp.denied('revoked clerk cannot replay receipt',format('select pg_temp.mm(''redeem1'',''token.redeem'',%L)',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'capability',pg_temp.proof('one')))));
select pg_temp.actor('parent');select pg_temp.mm('intent4','intent.create',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'revision_id',pg_temp.mid('offer'),'capability',pg_temp.proof('four'))));
reset role;update boss_private.merchant_redemption_intents set expires_at=created_at+interval'1 microsecond'where id=pg_temp.mid('intent4','intent_id');
set local role authenticated;select pg_temp.actor('assistant');select pg_temp.denied('expired business proof denied',format('select pg_temp.mm(''expired'',''token.redeem'',%L)',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'capability',pg_temp.proof('four')))),'PT409');
select pg_temp.actor('parent');select pg_temp.mm('intent5','intent.create',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'revision_id',pg_temp.mid('offer'),'capability',pg_temp.proof('five'))));
reset role;select boss_private.discount_revoke(source_id,'revoked',null,pg_temp.f('admin'))from boss_private.merchant_redemption_intents where id=pg_temp.mid('intent5','intent_id');
set local role authenticated;select pg_temp.actor('assistant');select pg_temp.denied('membership revoked while screen stale denied',format('select pg_temp.mm(''revoked-member'',''token.redeem'',%L)',pg_temp.mi(jsonb_build_object('location_id',pg_temp.mid('loc-a'),'capability',pg_temp.proof('five')))),'PT409');
reset role;
select pg_temp.check('redemption has no retail payment linkage','SEPARATION',not exists(select 1 from information_schema.columns where table_name='merchant_redemptions'and column_name in('payment_id','wallet_id','purchase_minor')));
select pg_temp.denied('redemption evidence cannot delete','delete from public.merchant_redemptions','23514');
select pg_temp.denied('correction cannot rewrite','update public.merchant_redemption_corrections set restore_allowance=false','23514');
select count(*)passed_assertions,'Phase 8A atomic redemption replay limits correction expiry'::text suite from phase5a_assertions;rollback;
