-- Canonical game lifecycle, immutable evidence, history and explicit operations.
begin;
\ir phase5a/fixture.sql
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.create_game('internal','internal');
select pg_temp.create_game('external','external');
select pg_temp.create_game('neutral','neutral');
select pg_temp.create_game('history','history');
select pg_temp.check('same input request replay returns same identity','IDEMPOTENCY',
 public.boss_games_mutate(pg_temp.f('request-create-internal'),pg_temp.create_command('internal'))->>'game_id'=(select id::text from pg_temp.phase5a_games where label='internal'));
select pg_temp.conflict('another request cannot create duplicate canonical game',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('duplicate-game'),pg_temp.create_command('internal')));
select pg_temp.conflict('request id cannot change payload',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('request-create-internal'),pg_temp.create_command('external')));
select pg_temp.conflict('practice cannot become competitive game',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('request-practice'),pg_temp.create_command('practice')));
select pg_temp.conflict('unknown sport is not inferred',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('request-sport'),pg_temp.create_command('denial','falcons','unknown_sport')));
select pg_temp.game_op('game.operator.assign','internal',jsonb_build_object('person_id',pg_temp.f('admin'),'role_assignment_id',pg_temp.f('role-admin'),'function_key','game_administrator','team_id',pg_temp.f('falcons'),'ends_at',now()+interval '1 hour'));
select pg_temp.conflict('start requires explicit roster readiness',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('request-no-roster'),pg_temp.game_command('game.start','internal')));
select pg_temp.game_op('game.roster.snapshot','internal');
select pg_temp.game_op('game.roster.snapshot','external');
select pg_temp.game_op('game.roster.snapshot','history');
select pg_temp.game_op('game.operator.assign','internal',jsonb_build_object('person_id',pg_temp.f('scorer'),'role_assignment_id',pg_temp.f('role-scorer'),'function_key','scorekeeper','team_id',pg_temp.f('falcons'),'ends_at',now()+interval '1 hour'));
select pg_temp.game_op('game.operator.assign','external',jsonb_build_object('person_id',pg_temp.f('admin'),'role_assignment_id',pg_temp.f('role-admin'),'function_key','game_administrator','team_id',pg_temp.f('falcons'),'ends_at',now()+interval '1 hour'));
select pg_temp.game_op('game.operator.assign','history',jsonb_build_object('person_id',pg_temp.f('admin'),'role_assignment_id',pg_temp.f('role-admin'),'function_key','game_administrator','team_id',pg_temp.f('falcons'),'ends_at',now()+interval '1 hour'));
select pg_temp.game_op('game.transition','external','{"status":"delayed"}');
select pg_temp.conflict('delayed transition cannot bypass explicit first game start',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('delayed-first-live'),pg_temp.game_command('game.transition','external','{"status":"live"}')));
select pg_temp.game_op('game.start','external');
reset role;
select pg_temp.check('one Calendar event links one internal game','IDENTITY',(select count(*)=1 from public.games where event_id=pg_temp.f('event-internal')));
select pg_temp.check('internal canonical sides and explicit sport','IDENTITY',(select primary_team_id=pg_temp.f('falcons') and opponent_team_id=pg_temp.f('wildcats') and external_opponent_name is null and sport_key='basketball' and home_away='home' from public.games where id=(select id from pg_temp.phase5a_games where label='internal')));
select pg_temp.check('external opponent does not create tenant or team','IDENTITY',(select external_opponent_name='Synthetic External Opponent' and opponent_team_id is null from public.games where id=(select id from pg_temp.phase5a_games where label='external')) and (select count(*)=2 from public.organizations where slug like 'synthetic-phase5a-%') and (select count(*)=4 from public.teams where organization_id in(pg_temp.f('org'),pg_temp.f('other-org'))));
select pg_temp.check('neutral tournament shares same core identity','IDENTITY',(select home_away='neutral' and competition_type='tournament' from public.games where id=(select id from pg_temp.phase5a_games where label='neutral')));
select pg_temp.check('internal snapshot preserves both canonical participant identities','ROSTER',(select count(*)=2 and bool_and(participant_id in(pg_temp.f('participant-child1'),pg_temp.f('participant-child2'))) from public.game_roster_snapshots where game_id=(select id from pg_temp.phase5a_games where label='internal')));
select pg_temp.check('external snapshot contains Boss athlete only','ROSTER',(select count(*)=1 and bool_and(participant_id=pg_temp.f('participant-child1')) from public.game_roster_snapshots where game_id=(select id from pg_temp.phase5a_games where label='external')));
update public.team_memberships set jersey_number='99',position_label='Changed current position' where id=pg_temp.f('membership-child1');
select pg_temp.check('current jersey change cannot rewrite game snapshot','ROSTER',(select bool_and(jersey_number='12' and position_label='Synthetic position') from public.game_roster_snapshots where game_id=(select id from pg_temp.phase5a_games where label='history')));
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.game_op('game.roster.snapshot','history');
reset role;
select pg_temp.check('new pregame snapshot appends another revision','ROSTER',(select count(distinct revision)=2 from public.game_roster_snapshots where game_id=(select id from pg_temp.phase5a_games where label='history')));
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.check('authorized prestart roster refresh capability is exposed','LIFECYCLE',(select (g->'capabilities'->>'roster_snapshot')::boolean from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g));
select pg_temp.game_op('game.start','internal','{}','start-internal');
select pg_temp.check('same start request replays safely','IDEMPOTENCY',(public.boss_games_mutate(pg_temp.f('start-internal'),pg_temp.game_command('game.start','internal','{}',(select version-1 from pg_temp.phase5a_games where label='internal')))->>'replayed')::boolean);
select pg_temp.conflict('another start cannot create second live session',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('start-again'),pg_temp.game_command('game.start','internal')));
select pg_temp.actor('scorer');
select pg_temp.game_op('game.score.set','internal','{"primary_score":12,"opponent_score":8}','score-original');
select pg_temp.game_op('game.transition','internal','{"status":"delayed"}');
select pg_temp.check('started delayed game exposes resume but no first-start or roster refresh','LIFECYCLE',(select (g->'capabilities'->>'resume')::boolean and not(g->'capabilities'->>'start')::boolean and not(g->'capabilities'->>'roster_snapshot')::boolean from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g));
select pg_temp.actor('admin');
select pg_temp.check('administrator cannot refresh a started delayed roster','LIFECYCLE',(select (g->'capabilities'->>'manage')::boolean and not(g->'capabilities'->>'roster_snapshot')::boolean from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g));
select pg_temp.actor('scorer');
select pg_temp.conflict('started delayed game cannot reset to scheduled',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('started-reset-scheduled'),pg_temp.game_command('game.transition','internal','{"status":"scheduled"}')));
select pg_temp.conflict('started delayed game cannot reset to pregame',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('started-reset-pregame'),pg_temp.game_command('game.transition','internal','{"status":"pregame"}')));
select pg_temp.game_op('game.transition','internal','{"status":"live"}');
select pg_temp.game_op('game.transition','internal','{"status":"paused"}');
select pg_temp.game_op('game.transition','internal','{"status":"live"}');
select pg_temp.denied('normal scorekeeper cannot finalize',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('scorer-final'),pg_temp.game_command('game.finalize','internal')));
select pg_temp.denied('normal scorekeeper cannot reopen',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('scorer-reopen'),pg_temp.game_command('game.reopen','internal','{"reason":"Synthetic correction"}')));
reset role;
select pg_temp.check('score summary has append history','LEDGER',(select primary_score=12 and opponent_score=8 from public.games where id=(select id from pg_temp.phase5a_games where label='internal')) and exists(select 1 from public.game_operations where game_id=(select id from pg_temp.phase5a_games where label='internal') and operation='game.score.set'));
create temp table phase5a_original_score as select id from public.game_operations where game_id=(select id from pg_temp.phase5a_games where label='internal') and operation='game.score.set';
grant select on phase5a_original_score to authenticated;
create temp table phase5a_admin_operator as select id from public.game_operator_assignments where game_id=(select id from pg_temp.phase5a_games where label='internal') and person_id=pg_temp.f('admin') and status='active';
grant select on phase5a_admin_operator to authenticated;
set local role authenticated;
select pg_temp.actor('scorer');
select pg_temp.denied('ordinary scorekeeper cannot reverse even their own score operation',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('scorer-reverse'),pg_temp.game_command('game.score.reverse','internal',jsonb_build_object('operation_id',(select id from phase5a_original_score)))));
select pg_temp.actor('admin');
select pg_temp.game_op('game.operator.end','internal',jsonb_build_object('assignment_id',(select id from phase5a_admin_operator)));
select pg_temp.check('elevated correction authority remains distinct from live operator authority','CORRECTION',(select (g->'capabilities'->>'correct')::boolean and not(g->'capabilities'->>'operate')::boolean from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g));
select pg_temp.game_op('game.score.reverse','internal',jsonb_build_object('operation_id',(select id from phase5a_original_score)));
reset role;
select pg_temp.check('reversal preserves original and links corrective operation','LEDGER',exists(select 1 from public.game_operations where game_id=(select id from pg_temp.phase5a_games where label='internal') and correction_of=(select id from phase5a_original_score)) and exists(select 1 from public.game_operations where id=(select id from phase5a_original_score)) and (select primary_score=0 and opponent_score=0 from public.games where id=(select id from pg_temp.phase5a_games where label='internal')));
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.conflict('reversing the same operation twice fails closed',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('reverse-twice'),pg_temp.game_command('game.score.reverse','internal',jsonb_build_object('operation_id',(select id from phase5a_original_score)))));
select pg_temp.denied('elevated correction permission cannot substitute for a score operator assignment',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('corrector-unassigned-score'),pg_temp.game_command('game.score.set','internal','{"primary_score":20,"opponent_score":15}')));
select pg_temp.actor('scorer');
select pg_temp.game_op('game.score.set','internal','{"primary_score":20,"opponent_score":15}');
select pg_temp.actor('admin');
select pg_temp.game_op('game.finalize','internal');
select pg_temp.state_denied('final blocks ordinary score changes',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('final-score'),pg_temp.game_command('game.score.set','internal','{"primary_score":21,"opponent_score":15}')));
select pg_temp.state_denied('final blocks ordinary lifecycle restart',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('final-live'),pg_temp.game_command('game.transition','internal','{"status":"live"}')));
select pg_temp.state_denied('final blocks roster replacement',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('final-roster'),pg_temp.game_command('game.roster.snapshot','internal')));
select pg_temp.conflict('reopen requires a reason',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('reopen-empty'),pg_temp.game_command('game.reopen','internal','{"reason":""}')));
reset role;
select pg_temp.check('final retains score winner roster and timestamp','FINAL',(select status='final' and final_primary_score=20 and final_opponent_score=15 and winner_side='primary' and not tied and finalized_at is not null and finalized_by_person_id=pg_temp.f('admin') and roster_revision>0 from public.games where id=(select id from pg_temp.phase5a_games where label='internal')));
select pg_temp.check('first finalization seals history','FINAL',(select count(*)=1 from public.game_finalizations where game_id=(select id from pg_temp.phase5a_games where label='internal')));
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.game_op('game.reopen','internal','{"reason":"Synthetic score correction"}');
select pg_temp.actor('scorer');
select pg_temp.game_op('game.score.set','internal','{"primary_score":20,"opponent_score":20}');
select pg_temp.actor('admin');
select pg_temp.game_op('game.finalize','internal');
reset role;
select pg_temp.check('refinalization preserves both immutable final seals','FINAL',(select count(*)=2 from public.game_finalizations where game_id=(select id from pg_temp.phase5a_games where label='internal')));
select pg_temp.check('tie and later final score are canonical','FINAL',(select status='final' and final_primary_score=20 and final_opponent_score=20 and winner_side is null and tied and finalization_count=2 from public.games where id=(select id from pg_temp.phase5a_games where label='internal')));
update public.team_memberships set status='inactive',ends_at=now() where id=pg_temp.f('membership-child1');
update public.role_assignments set status='inactive',ends_at=now() where id=pg_temp.f('role-coach');
update public.seasons set status='archived' where id=pg_temp.f('season');
select pg_temp.check('departure and season archive cannot erase final facts','HISTORY',(select status='final' and final_primary_score=20 and final_opponent_score=20 from public.games where id=(select id from pg_temp.phase5a_games where label='internal')) and (select count(*)=2 from public.game_roster_snapshots where game_id=(select id from pg_temp.phase5a_games where label='internal')) and (select count(*)=2 from public.game_finalizations where game_id=(select id from pg_temp.phase5a_games where label='internal')));
set local role authenticated;
select pg_temp.actor('child1');
select pg_temp.denied('historical roster does not create current participant authority',format('select public.boss_games_read(%L)',pg_temp.query('internal')));
select pg_temp.actor('parent');
select pg_temp.denied('guardian loses game access when dependent current team relation ends',format('select public.boss_games_read(%L)',pg_temp.query('internal','{"view":"family"}')));
reset role;
select pg_temp.check('ledger sequencing is contiguous without missing actions','LEDGER',(select count(*)=max(sequence) and min(sequence)=1 and count(*)=count(distinct sequence) from public.game_operations where game_id=(select id from pg_temp.phase5a_games where label='internal')));
select pg_temp.check('every consequential operation links canonical audit','AUDIT',(select bool_and(audit_event_id is not null and exists(select 1 from public.audit_events a where a.id=operations.audit_event_id)) from public.game_operations operations where game_id=(select id from pg_temp.phase5a_games where label='internal')));
select pg_temp.denied('ledger UPDATE cannot erase original action','update public.game_operations set operation=operation where game_id=(select id from pg_temp.phase5a_games where label=''internal'')','23514');
select pg_temp.denied('finalization DELETE cannot erase prior seal','delete from public.game_finalizations where game_id=(select id from pg_temp.phase5a_games where label=''internal'')','23514');
select pg_temp.denied('captured roster UPDATE cannot rewrite prior history','update public.game_roster_snapshots set jersey_number=''1'' where game_id=(select id from pg_temp.phase5a_games where label=''internal'')','23514');
select pg_temp.denied('game occurrence identity cannot be rewritten','update public.games set occurrence_key=''2026-12-31T18:00:00'' where id=(select id from pg_temp.phase5a_games where label=''internal'')','23514');
select count(*) as passed_assertions,category from pg_temp.phase5a_assertions group by category order by category;
rollback;
