\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase8a/fixture.sql
select pg_temp.check('local matching membership source','GEOGRAPHY',boss_private.merchant_membership_source(pg_temp.f('parent'),pg_temp.mid('loc-a'))is not null);
select pg_temp.check('local does not grant other state','GEOGRAPHY',boss_private.merchant_membership_source(pg_temp.f('parent'),pg_temp.mid('loc-other'))is null);
select pg_temp.check('US local cannot grant Canada','GEOGRAPHY',boss_private.merchant_membership_source(pg_temp.f('parent'),pg_temp.mid('loc-ca'))is null);
select pg_temp.check('member is not merchant owner by membership alone','SCOPE',not boss_private.merchant_can(pg_temp.f('household-only'),'merchants.manage',pg_temp.mid('merchant','merchant_id')));
set local role anon;
select pg_temp.check('public directory excludes economics','PRIVACY',public.boss_merchants_directory(jsonb_build_object('market_id',pg_temp.mid('market','market_id')))::text!~'discount_bps|capability|claim_state|staff|terms|person_id');
reset role;set local role authenticated;select pg_temp.actor('household-only');
select pg_temp.check('insufficient member gets no terms','PRIVACY',jsonb_array_length(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('market','market_id')))->'offers')=0);
select pg_temp.actor('parent');
select pg_temp.check('eligible member reads structured terms','TERMS',(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('market','market_id')))->'offers'->0->'terms'->>'discount_bps')::integer=1000);
select pg_temp.mm('favorite','favorite.set',pg_temp.mi('{"favorite":true}'));
select pg_temp.check('favorites filter does not broaden access','FAVORITES',jsonb_array_length(public.boss_merchants_read(jsonb_build_object('market_id',pg_temp.mid('market','market_id'),'favorites',true))->'offers')=1);
select pg_temp.actor('admin');
select pg_temp.denied('invalid percentage rejected','select pg_temp.mo(''bad-percent'',''{"discount_bps":10001}''::jsonb)','23514');
select pg_temp.denied('mixed fixed and percentage rejected','select pg_temp.mo(''mixed-terms'',''{"currency":"USD","amount_minor":100}''::jsonb)','23514');
select pg_temp.denied('unreviewed HTML rejected','select pg_temp.mo(''html'',''{"title":"<script>"}''::jsonb)','PT422');
select pg_temp.denied('invalid timezone rejected','select pg_temp.mm(''bad-zone'',''family.create'',pg_temp.mi(''{"reset_period":"lifetime","usage_timezone":"Made/Up"}''))','23514');
select pg_temp.mm('family-all','family.create',pg_temp.mi('{"reset_period":"lifetime","usage_timezone":"America/New_York"}'));
select pg_temp.mo('offer-all',jsonb_build_object('family_id',pg_temp.mid('family-all'),'location_policy','all_current','include_future',false));
select pg_temp.mm('all-submit','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('offer-all'),'state','pending_review')));
select pg_temp.mm('all-publish','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('offer-all'),'state','published','reason','Reviewed all current location snapshot')));
select pg_temp.mm('loc-future','location.create',pg_temp.mi(jsonb_build_object('market_id',pg_temp.mid('market','market_id'),'name','SYNTHETIC Future','address','5 Synthetic Street','city','Synthetic City','postal_code','00000','timezone','America/New_York')));
reset role;
select pg_temp.check('all current snapshot frozen','LOCATIONS',not boss_private.merchant_available(pg_temp.mid('offer-all'),pg_temp.mid('loc-future')));
select pg_temp.check('selected excludes sibling','LOCATIONS',not boss_private.merchant_available(pg_temp.mid('offer'),pg_temp.mid('loc-b')));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.mm('family-dst','family.create',pg_temp.mi('{"usage_limit":13,"reset_period":"weekly","usage_timezone":"America/New_York"}'));
select pg_temp.mo('dst',jsonb_build_object('family_id',pg_temp.mid('family-dst'),'starts_at','2026-01-01T00:00:00Z','ends_at','2027-12-31T00:00:00Z','weekdays',jsonb_build_array(0),'local_start','01:00','local_end','02:00','weekly_special',true));
select pg_temp.mm('dst-submit','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('dst'),'state','pending_review')));
select pg_temp.mm('dst-publish','offer.status',pg_temp.mi(jsonb_build_object('revision_id',pg_temp.mid('dst'),'state','scheduled','reason','Reviewed DST wall clock recurrence')));
reset role;
select pg_temp.check('fall back first local hour available','DST',boss_private.merchant_available(pg_temp.mid('dst'),pg_temp.mid('loc-a'),'2026-11-01T05:30Z'));
select pg_temp.check('fall back second local hour same offer','DST',boss_private.merchant_available(pg_temp.mid('dst'),pg_temp.mid('loc-a'),'2026-11-01T06:30Z'));
select pg_temp.check('end local time exclusive','DST',not boss_private.merchant_available(pg_temp.mid('dst'),pg_temp.mid('loc-a'),'2026-11-01T07:00Z'));
select pg_temp.check('fallback has one allowance window','DST',(select boss_private.merchant_window(f,'2026-11-01T05:30Z')=boss_private.merchant_window(f,'2026-11-01T06:30Z')from public.merchant_offer_families f where id=pg_temp.mid('family-dst')));
select pg_temp.check('spring forward missing hour creates no recurrence','DST',not boss_private.merchant_available(pg_temp.mid('dst'),pg_temp.mid('loc-a'),'2026-03-08T07:30Z'));
select pg_temp.check('custom usage integer 13 retained','USAGE',(select usage_limit=13 from public.merchant_offer_families where id=pg_temp.mid('family-dst')));
set local role authenticated;select pg_temp.actor('coach');
select pg_temp.mm('local-pause','offer.local',pg_temp.mi(jsonb_build_object('family_id',pg_temp.mid('family-all'),'location_id',pg_temp.mid('loc-a'),'paused',true,'presentation_note','Location note only')));
select pg_temp.actor('parent');select pg_temp.mm('corporate-pause','family.status',pg_temp.mi(jsonb_build_object('family_id',pg_temp.mid('family-all'),'status','paused')));
select pg_temp.actor('coach');select pg_temp.mm('local-unpause','offer.local',pg_temp.mi(jsonb_build_object('family_id',pg_temp.mid('family-all'),'location_id',pg_temp.mid('loc-a'),'paused',false)));
reset role;
select pg_temp.check('local unpause cannot bypass corporate pause','PAUSE',not boss_private.merchant_available(pg_temp.mid('offer-all'),pg_temp.mid('loc-a')));
set constraints all immediate;
select count(*)passed_assertions,'Phase 8A offers geography locations schedules and DST'::text suite from phase5a_assertions;rollback;
