-- Independent potential-capability, live-relationship and closed-raw boundaries.
begin;
\ir phase5a/fixture.sql
do $$declare tab record;fn record;client text;r text;actual text[];expected text[];
 keys text[]:=array['games.correct','games.create','games.finalize','games.manage','games.operate','games.publish','games.view'];
begin
 perform pg_temp.check('only seven finite game permissions','CATALOG',(select array_agg(key order by key)=keys from public.permissions where key like 'games.%'));
 perform pg_temp.check('Sports reused without new module or broad role','CATALOG',(select count(*)=14 from public.modules where key <> 'payments') and (select count(*)=21 from public.roles WHERE key not in('competition_manager','merchant_owner','merchant_admin','location_manager','offer_editor','redemption_clerk','sales_rep','regional_manager','support_reviewer')));
 for r in select key from public.roles order by key loop
  expected:=case
   when r in('super_administrator','platform_administrator','organization_owner','organization_administrator') then keys
   when r='athletic_director' then array['games.correct','games.create','games.finalize','games.manage','games.operate','games.view']
   when r in('program_administrator','sport_administrator') then array['games.create','games.finalize','games.manage','games.operate','games.view']
   when r in('team_administrator','head_coach') then array['games.manage','games.view']
   when r='scorekeeper' then array['games.operate','games.view']
   when r in('assistant_coach','team_staff','livestream_operator') then array['games.view']
   else array[]::text[] end;
  select coalesce(array_agg(p.key order by p.key),array[]::text[]) into actual from public.roles role join public.role_permissions rp on rp.role_id=role.id join public.permissions p on p.id=rp.permission_id where role.key=r and p.key like 'games.%';
  perform pg_temp.check('minimum role permission mapping '||r,'CATALOG',actual=expected);
 end loop;
 for tab in select c.oid,n.nspname schema_name,c.relname,c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind='r' and n.nspname in('public','boss_private') and (c.relname='games' or c.relname='sports' or c.relname like 'game_%') loop
  perform pg_temp.check(tab.schema_name||'.'||tab.relname||' RLS enabled','RLS',tab.relrowsecurity);
  foreach client in array array['anon','authenticated','service_role'] loop
   perform pg_temp.check(tab.schema_name||'.'||tab.relname||' raw closed '||client,'RLS',not has_table_privilege(client,tab.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'));
  end loop;
 end loop;
 for fn in select p.oid,n.nspname schema_name,p.proname,p.prosecdef,p.proconfig,p.proacl,p.proowner,p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname='boss_private' and p.proname like 'game%') or (n.nspname='public' and p.proname in('boss_games_read','boss_games_mutate')) loop
  perform pg_temp.check(fn.signature||' has fixed empty search path','RPC',coalesce('search_path=""'=any(fn.proconfig),false));
  perform pg_temp.check(fn.signature||' PUBLIC execute closed','RPC',not exists(select 1 from aclexplode(coalesce(fn.proacl,acldefault('f',fn.proowner)))a where a.grantee=0 and a.privilege_type='EXECUTE'));
  perform pg_temp.check(fn.signature||' anonymous and service execute closed','RPC',not has_function_privilege('anon',fn.oid,'EXECUTE') and not has_function_privilege('service_role',fn.oid,'EXECUTE'));
  if fn.schema_name='public' then perform pg_temp.check(fn.signature||' invoker entry authenticated only','RPC',not fn.prosecdef and has_function_privilege('authenticated',fn.oid,'EXECUTE'));
  elsif fn.proname not in('games_read','games_mutate','game_read','game_mutate') then perform pg_temp.check(fn.signature||' private helper closed','RPC',not has_function_privilege('authenticated',fn.oid,'EXECUTE'));end if;
 end loop;
end$$;
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.create_game('internal','internal');
select pg_temp.create_game('external','external');
select pg_temp.create_game('wildcats','wildcats','wildcats');
select pg_temp.create_game('sibling','sibling','tigers');
select pg_temp.game_op('game.roster.snapshot','internal');
select pg_temp.game_op('game.operator.assign','internal',jsonb_build_object('person_id',pg_temp.f('scorer'),'role_assignment_id',pg_temp.f('role-scorer'),'function_key','scorekeeper','team_id',pg_temp.f('falcons'),'ends_at',now()+interval '1 hour'));
select pg_temp.denied('cannot link forged event UUID',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('forged-event'),pg_temp.create_command('external')||jsonb_build_object('input',(pg_temp.create_command('external')->'input')||jsonb_build_object('event_id',pg_temp.f('missing-event')))));
select pg_temp.denied('cannot link cross-tenant event',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('cross-event'),pg_temp.create_command('other','other-team')));
select pg_temp.state_denied('cannot forge primary team outside Calendar target',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('forged-team'),pg_temp.create_command('denial','tigers')));
select pg_temp.conflict('syntactically valid key does not create occurrence',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('forged-occurrence'),pg_temp.create_command('denial','falcons','basketball',2)));
select pg_temp.denied('cannot assign operator using different actor role',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('wrong-person-role'),pg_temp.game_command('game.operator.assign','internal',jsonb_build_object('person_id',pg_temp.f('scorer'),'role_assignment_id',pg_temp.f('role-coach'),'function_key','scorekeeper','team_id',pg_temp.f('falcons'),'ends_at',now()+interval '1 hour'))));
select pg_temp.denied('livestream role grants no score operator function',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('streamer-assign'),pg_temp.game_command('game.operator.assign','internal',jsonb_build_object('person_id',pg_temp.f('streamer'),'role_assignment_id',pg_temp.f('role-streamer'),'function_key','scorekeeper','team_id',pg_temp.f('falcons'),'ends_at',now()+interval '1 hour'))));
select pg_temp.denied('missing operator assignment cannot be ended',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('missing-operator-end'),pg_temp.game_command('game.operator.end','internal',jsonb_build_object('assignment_id',pg_temp.f('missing-operator')))));
reset role;
create temp table phase5a_existing_operator as select id from public.game_operator_assignments where game_id=(select id from pg_temp.phase5a_games where label='internal') and person_id=pg_temp.f('scorer');
grant select on phase5a_existing_operator to authenticated;
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.denied('knowing another game assignment ID creates no end authority',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('forged-operator-end'),pg_temp.game_command('game.operator.end','external',jsonb_build_object('assignment_id',(select id from phase5a_existing_operator)))));
select pg_temp.actor('scorer');
select pg_temp.check('explicit exact-game operator gets operation capability','OPERATOR',exists(select 1 from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g where (g->'capabilities'->>'operate')::boolean));
select pg_temp.check('game operator authority alone reveals no private athlete roster','PROJECTION',(select jsonb_array_length(g->'roster')=0 from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g));
select pg_temp.game_op('game.start','internal');
select pg_temp.game_op('game.score.set','internal','{"primary_score":3,"opponent_score":2}','score-revocation-proof');
select pg_temp.denied('team role alone cannot operate another Falcons game',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('unassigned-own'),pg_temp.game_command('game.start','external')));
select pg_temp.denied('Falcons operator cannot operate Wildcats game',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('unrelated-team'),pg_temp.game_command('game.start','wildcats')));
select pg_temp.denied('Falcons operator cannot operate sibling program',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('sibling-team'),pg_temp.game_command('game.start','sibling')));
select pg_temp.denied('UUID knowledge cannot reveal sibling private game',format('select public.boss_games_read(%L)',pg_temp.query('sibling')));
select pg_temp.denied('UUID knowledge cannot reveal unrelated organization',format('select public.boss_games_read(%L)',pg_temp.query(null,jsonb_build_object('organization_id',pg_temp.f('other-org')))));
select pg_temp.actor('coach');
select pg_temp.check('Falcons coach can manage its external game under enabled feature policy','TEAM_SCOPE',(select (g->'capabilities'->>'manage')::boolean and (g->'capabilities'->>'roster_snapshot')::boolean and not(g->'capabilities'->>'operate')::boolean from jsonb_array_elements(public.boss_games_read(pg_temp.query('external'))->'games')g));
select pg_temp.check('one-side coach can view matchup but cannot manage other Boss competitor','TEAM_SCOPE',(select not(g->'capabilities'->>'manage')::boolean and not(g->'capabilities'->>'roster_snapshot')::boolean and jsonb_array_length(g->'roster')=1 and g->'roster'->0->>'team_id'=pg_temp.f('falcons')::text from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g));
select pg_temp.denied('one-side coach cannot snapshot both internal competitor rosters',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('coach-internal-rosters'),pg_temp.game_command('game.roster.snapshot','internal')));
select pg_temp.denied('head coach is not automatically live operator',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('coach-operate'),pg_temp.game_command('game.score.set','internal','{"primary_score":10,"opponent_score":2}')));
select pg_temp.actor('streamer');
select pg_temp.check('livestream role reads safe matchup without operating or roster privileges','PROJECTION',(select not(g->'capabilities'->>'operate')::boolean and not(g->'capabilities'->>'manage')::boolean and jsonb_array_length(g->'roster')=0 and jsonb_array_length(g->'operators')=0 from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g));
select pg_temp.denied('livestream role cannot mutate score even by known game UUID',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('streamer-known-score'),pg_temp.game_command('game.score.set','internal','{"primary_score":1,"opponent_score":0}')));
select pg_temp.actor('program');
select pg_temp.check('exact program role manages both participating teams in its own unit','TEAM_SCOPE',(select (g->'capabilities'->>'manage')::boolean from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g));
select pg_temp.denied('exact program does not inherit sibling unit',format('select public.boss_games_read(%L)',pg_temp.query('sibling')));
reset role;
update public.organization_memberships set status='inactive' where organization_id=pg_temp.f('org') and person_id in(pg_temp.f('program'),pg_temp.f('director'));
set local role authenticated;
select pg_temp.actor('program');
select pg_temp.denied('unit role loses authority when actual organization membership ends',format('select public.boss_games_read(%L)',pg_temp.query('internal')));
select pg_temp.actor('director');
select pg_temp.denied('organization role loses authority when actual organization membership ends',format('select public.boss_games_read(%L)',pg_temp.query('internal')));
reset role;
update public.organization_memberships set status='active' where organization_id=pg_temp.f('org') and person_id in(pg_temp.f('program'),pg_temp.f('director'));
update public.organization_modules set configuration=configuration||'{"attendance":true,"attendance_rsvp":true,"attendance_guardian_rsvp":true,"attendance_checkin":true}' where organization_id=pg_temp.f('org') and module_id=(select id from public.modules where key='calendar');
update public.guardian_relationships set can_respond_attendance=true where id=pg_temp.f('guardian-child1');
insert into public.attendance_responses(organization_id,event_id,occurrence_key,person_id,participant_id,subject_kind,occurrence_mode,status,responder_person_id,guardian_relationship_id,reason,note,context_fingerprint)
 values(pg_temp.f('org'),pg_temp.f('event-external'),pg_temp.key(),pg_temp.f('child1'),pg_temp.f('participant-child1'),'participant','single','attending',pg_temp.f('parent'),pg_temp.f('guardian-child1'),'Synthetic private RSVP reason','Synthetic private attendance note',repeat('a',64));
insert into public.attendance_checkins(organization_id,event_id,occurrence_key,person_id,participant_id,subject_kind,occurrence_mode,state,actor_person_id)
 values(pg_temp.f('org'),pg_temp.f('event-external'),pg_temp.key(),pg_temp.f('child1'),pg_temp.f('participant-child1'),'participant','single','checked_in',pg_temp.f('admin'));
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.game_op('game.roster.snapshot','external');
select pg_temp.actor('parent');
select pg_temp.check('current guardian Attendance authority permits finite captured availability','ATTENDANCE',(select g->'roster'->0->>'availability'='attending' and g->'roster'->0->>'checkin_state'='checked_in' from jsonb_array_elements(public.boss_games_read(pg_temp.query('external','{"view":"family"}'))->'games')g));
select pg_temp.check('Games projection never copies private RSVP reason or note','ATTENDANCE',(select not(g->'roster'->0?'reason') and not(g->'roster'->0?'note') from jsonb_array_elements(public.boss_games_read(pg_temp.query('external','{"view":"family"}'))->'games')g));
reset role;
update public.guardian_relationships set can_respond_attendance=false where id=pg_temp.f('guardian-child1');
set local role authenticated;
select pg_temp.actor('parent');
select pg_temp.check('guardian Attendance flag removal masks captured state but retains family roster','ATTENDANCE',(select jsonb_array_length(g->'roster')=1 and g->'roster'->0->>'availability'='unknown' and g->'roster'->0->'checkin_state'='null'::jsonb from jsonb_array_elements(public.boss_games_read(pg_temp.query('external','{"view":"family"}'))->'games')g));
reset role;
update public.organization_modules set configuration=configuration||'{"attendance":false}' where organization_id=pg_temp.f('org') and module_id=(select id from public.modules where key='calendar');
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.check('Attendance feature revocation masks captured state for roster staff','ATTENDANCE',(select g->'roster'->0->>'availability'='unknown' and g->'roster'->0->'checkin_state'='null'::jsonb from jsonb_array_elements(public.boss_games_read(pg_temp.query('external'))->'games')g));
reset role;
select pg_temp.check('Attendance revocation does not rewrite the immutable captured facts','ATTENDANCE',(select availability='attending' and checkin_state='checked_in' from public.game_roster_snapshots where game_id=(select id from phase5a_games where label='external') and person_id=pg_temp.f('child1')));
set local role authenticated;
select pg_temp.actor('parent');
select pg_temp.check('guardian sees dependent matchup without scoring controls','FAMILY',exists(select 1 from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal','{"view":"family"}'))->'games')g where not (g->'capabilities'->>'operate')::boolean and not (g->'capabilities'->>'finalize')::boolean));
select pg_temp.check('guardian receives only own dependent roster row','FAMILY',(select jsonb_array_length(g->'roster')=1 and (g->'roster'->0->>'person_id')=pg_temp.f('child1')::text from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal','{"view":"family"}'))->'games')g));
select pg_temp.denied('guardian cannot mutate scores',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('parent-operate'),pg_temp.game_command('game.score.set','internal','{"primary_score":10,"opponent_score":2}')));
select pg_temp.denied('guardian cannot view unrelated child game',format('select public.boss_games_read(%L)',pg_temp.query('wildcats','{"view":"family"}')));
select pg_temp.actor('child1');
select pg_temp.check('participant sees own team with no operation controls','FAMILY',exists(select 1 from jsonb_array_elements(public.boss_games_read(pg_temp.query('internal'))->'games')g where not (g->'capabilities'->>'operate')::boolean and jsonb_array_length(g->'roster')=1));
select pg_temp.actor('household-only');
select pg_temp.denied('household membership alone does not grant game visibility',format('select public.boss_games_read(%L)',pg_temp.query('internal','{"view":"family"}')));
reset role;
insert into public.organization_memberships(organization_id,person_id,starts_at) values(pg_temp.f('org'),pg_temp.f('household-only'),now()-interval '1 day');
set local role authenticated;
select pg_temp.actor('household-only');
select pg_temp.denied('household plus organization membership cannot substitute for guardian authority',format('select public.boss_games_read(%L)',pg_temp.query('internal','{"view":"family"}')));
select pg_temp.denied('household cannot forge a dependent child filter',format('select public.boss_games_read(%L)',pg_temp.query(null,jsonb_build_object('view','family','child_person_id',pg_temp.f('child1')))));
select set_config('request.jwt.claims',(current_setting('request.jwt.claims')::jsonb||'{"user_metadata":{"is_admin":true,"games.operate":true}}')::text,true);
select pg_temp.denied('editable JWT metadata cannot create game authority',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('metadata-operate'),pg_temp.game_command('game.start','external')));
reset role;
update public.role_assignments set status='inactive' where id=pg_temp.f('role-scorer');
set local role authenticated;
select pg_temp.actor('scorer');
select pg_temp.denied('role removal denies stale signed operation',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('role-ended-score'),pg_temp.game_command('game.score.set','internal','{"primary_score":4,"opponent_score":2}')));
select pg_temp.denied('revoked role also denies same-request replay',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('score-revocation-proof'),pg_temp.game_command('game.score.set','internal','{"primary_score":3,"opponent_score":2}',(select version-1 from pg_temp.phase5a_games where label='internal'))));
reset role;
update public.role_assignments set status='active' where id=pg_temp.f('role-scorer');
update public.team_memberships set status='inactive' where id=pg_temp.f('membership-scorer');
set local role authenticated;
select pg_temp.actor('scorer');
select pg_temp.denied('ended actual team relationship denies operation',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('membership-ended'),pg_temp.game_command('game.score.set','internal','{"primary_score":4,"opponent_score":2}')));
reset role;
update public.team_memberships set status='active' where id=pg_temp.f('membership-scorer');
update public.game_operator_assignments set status='inactive' where person_id=pg_temp.f('scorer');
set local role authenticated;
select pg_temp.actor('scorer');
select pg_temp.denied('ended operator assignment denies operation',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('operator-ended'),pg_temp.game_command('game.score.set','internal','{"primary_score":4,"opponent_score":2}')));
reset role;
update public.organization_modules set configuration=configuration||'{"game_center":false}' where organization_id=pg_temp.f('org') and module_id=(select id from public.modules where key='sports');
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.denied('disabled Game Center denies private reads',format('select public.boss_games_read(%L)',pg_temp.query('internal')));
select pg_temp.denied('disabled feature denies previously valid request replay',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('request-create-internal'),pg_temp.create_command('internal')));
reset role;
update public.organization_modules set configuration=configuration||'{"game_center":true,"game_operations":false,"live_scoring":true,"stats":true,"livestream":true}' where organization_id=pg_temp.f('org') and module_id=(select id from public.modules where key='sports');
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.check('future flags do not activate generic operations','FEATURE',not (public.boss_games_read(pg_temp.query('external'))->'features'->>'game_operations')::boolean);
select pg_temp.denied('operations disabled cannot start',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('ops-disabled'),pg_temp.game_command('game.start','external')));
reset role;
update public.organization_modules set status='inactive' where organization_id=pg_temp.f('org') and module_id=(select id from public.modules where key='calendar');
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.denied('inactive Calendar module closes linked game reads',format('select public.boss_games_read(%L)',pg_temp.query('internal')));
select pg_temp.denied('inactive Calendar module closes corrections',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('calendar-disabled-correct'),pg_temp.game_command('game.reopen','internal','{"reason":"Synthetic revoked module"}')));
reset role;
update public.organization_modules set status='active' where organization_id=pg_temp.f('org') and module_id=(select id from public.modules where key='calendar');
update auth.users set email_confirmed_at=null where id=pg_temp.f('auth-admin');
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.denied('unverified authenticated user denied before game projection',format('select public.boss_games_read(%L)',pg_temp.query('internal')),'PT401');
reset role;
update auth.users set email_confirmed_at=now()-interval '3 days',banned_until=now()+interval '1 hour' where id=pg_temp.f('auth-admin');
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.denied('banned authenticated user denied before game mutation',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('banned-game-request'),pg_temp.game_command('game.start','external')),'PT401');
reset role;
update auth.users set banned_until=null where id=pg_temp.f('auth-admin');
update auth.sessions set not_after=now()-interval '1 second' where id=pg_temp.f('session-admin');
set local role authenticated;
select pg_temp.actor('admin');
select pg_temp.denied('expired signed session denies reads',format('select public.boss_games_read(%L)',pg_temp.query('internal')),'PT401');
select pg_temp.denied('expired signed session denies mutations',format('select public.boss_games_mutate(%L,%L)',pg_temp.f('session-ended'),pg_temp.game_command('game.start','external')),'PT401');
select pg_temp.denied('authenticated direct raw write closed','update public.games set status=''live''','42501');
reset role;
set local role anon;
select pg_temp.denied('anonymous game RPC closed','select public.boss_games_read()','42501');
select pg_temp.denied('anonymous raw game read closed','select * from public.games','42501');
reset role;
select count(*) as passed_assertions,category from pg_temp.phase5a_assertions group by category order by category;
rollback;
