#!/usr/bin/env bash
# Real two-connection Phase 7B transaction races on the private disposable socket.
set -euo pipefail
umask 077
: "${PG_BINDIR:?Disposable runner required}" "${PGHOST:?Disposable runner required}" "${PGPORT:?Disposable runner required}" "${PGDATABASE:?Disposable runner required}" "${PGUSER:?Disposable runner required}"
if [[ "$PGHOST" != /tmp/boss-db-test.*/socket || ! -S "$PGHOST/.s.PGSQL.5432" || "$PGPORT" != 5432 || "$PGDATABASE" != postgres || "$PGUSER" != postgres ]];then printf '%s\n' 'Phase7B races require the private disposable runner socket.' >&2;exit 1;fi
test_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd);race_dir=${PGHOST%/socket}
psql_cmd=("$PG_BINDIR/psql" --no-psqlrc --no-password --host "$PGHOST" --port "$PGPORT" --username "$PGUSER" --dbname "$PGDATABASE" --set ON_ERROR_STOP=1 --set VERBOSITY=verbose --quiet --no-align --tuples-only)
writer_pid='';contender_pid='';input_open=false;race_count=0
cleanup(){ local result=$?;trap - EXIT INT TERM;if [[ "$input_open" == true ]];then exec 9>&-;fi;for pid in "$writer_pid" "$contender_pid";do [[ -z "$pid" ]]||{ kill "$pid" >/dev/null 2>&1||true;wait "$pid" >/dev/null 2>&1||true;};done;exit "$result";};trap cleanup EXIT;trap 'exit 130' INT;trap 'exit 143' TERM
fail(){ printf 'Phase7B concurrency invariant failed: %s\n' "$1" >&2;exit 1; }
assert_sql(){ [[ $("${psql_cmd[@]}" --command "$2") == t ]]||fail "$1"; }
await_state(){ local app=$1 expected=$2 pid=$3 deadline=$((SECONDS+7)) query;if [[ "$expected" == ready ]];then query="select count(*) from pg_stat_activity where application_name='$app'and state='idle in transaction'and query like'%phase7b-writer-ready%'";else query="select count(*) from pg_stat_activity where application_name='$app'and wait_event_type='Lock'";fi;while((SECONDS<deadline));do kill -0 "$pid" >/dev/null 2>&1||return 1;[[ $("${psql_cmd[@]}" --command "$query") == 1 ]]&&return 0;sleep .025;done;return 1; }
race(){ local label=$1 writer_sql=$2 contender_sql=$3 expected=$4;local fifo="$race_dir/phase7b-$label.stdin" rc=0;mkfifo -m 600 "$fifo";"${psql_cmd[@]}" <"$fifo" >"$race_dir/$label-w.out" 2>"$race_dir/$label-w.err"&writer_pid=$!;exec 9>"$fifo";input_open=true;printf '%s\n' "set application_name='boss_phase7b_${label}_writer';set statement_timeout='8s';begin;$writer_sql select 1 /* phase7b-writer-ready */;" >&9;await_state "boss_phase7b_${label}_writer" ready "$writer_pid"||{ head -n 8 "$race_dir/$label-w.err" >&2;fail "$label writer readiness";};"${psql_cmd[@]}" --command "set application_name='boss_phase7b_${label}_contender';set statement_timeout='8s';begin;$contender_sql commit;" >"$race_dir/$label-c.out" 2>"$race_dir/$label-c.err"&contender_pid=$!;await_state "boss_phase7b_${label}_contender" waiting "$contender_pid"||fail "$label contender did not block";printf '%s\n' 'commit;' >&9;exec 9>&-;input_open=false;wait "$writer_pid"||fail "$label writer";writer_pid='';if wait "$contender_pid";then rc=0;else rc=$?;fi;contender_pid='';if [[ "$expected" == success && "$rc" != 0 ]];then fail "$label contender";fi;if [[ "$expected" != success ]]&&{ [[ "$rc" == 0 ]]||! grep -Fq "$expected" "$race_dir/$label-c.err";};then fail "$label expected $expected";fi;race_count=$((race_count+1)); }
snapshot_race(){ local label=$1 writer_sql=$2 read_sql=$3 post_assert=$4;local fifo="$race_dir/phase7b-$label.stdin";mkfifo -m 600 "$fifo";"${psql_cmd[@]}" <"$fifo" >"$race_dir/$label-w.out" 2>"$race_dir/$label-w.err"&writer_pid=$!;exec 9>"$fifo";input_open=true;printf '%s\n' "set application_name='boss_phase7b_${label}_writer';set statement_timeout='8s';begin;$writer_sql select 1 /* phase7b-writer-ready */;" >&9;await_state "boss_phase7b_${label}_writer" ready "$writer_pid"||{ head -n 8 "$race_dir/$label-w.err" >&2;fail "$label writer readiness";};"${psql_cmd[@]}" --command "set statement_timeout='8s';$read_sql" >"$race_dir/$label-read.out" 2>"$race_dir/$label-read.err"||fail "$label snapshot read";printf '%s\n' 'commit;' >&9;exec 9>&-;input_open=false;wait "$writer_pid"||fail "$label writer";writer_pid='';assert_sql "$label post-commit" "$post_assert";race_count=$((race_count+1)); }
auth(){ printf '%s' "set local role authenticated;select set_config('request.jwt.claims',jsonb_build_object('sub',md5('boss-phase7b-race:auth-$1')::uuid,'role','authenticated','is_anonymous',false,'session_id',md5('boss-phase7b-race:session-$1')::uuid)::text,true);"; }
# No wallet provision during setup: first independent grants must contend on uniqueness.
sed -e 's/boss-phase7b-test:/boss-phase7b-race:/g' -e 's/phase7b.example.invalid/phase7b-race.example.invalid/g' -e 's/synthetic-phase7b-/synthetic-phase7b-race-/g' -e "/insert into wallet_ids select 'wallet'/d" "$test_dir/phase7b/fixture.sql" >"$race_dir/phase7b-fixture.sql"
printf '%s\n' 'begin;' "\\ir '$race_dir/phase7b-fixture.sql'" 'commit;' >"$race_dir/phase7b-setup.sql"
if ! "${psql_cmd[@]}" --file "$race_dir/phase7b-setup.sql" >"$race_dir/setup7b.out" 2>"$race_dir/setup7b.err";then head -n 6 "$race_dir/setup7b.err" >&2;fail setup;fi
lookup(){ "${psql_cmd[@]}" --command "$1"; }
org="md5('boss-phase7b-race:org')::uuid";household="md5('boss-phase7b-race:household')::uuid";guardian="md5('boss-phase7b-race:guardian-child1')::uuid"
campaign=$(lookup "select id from public.fundraising_campaigns where organization_id=$org")
fundraiser=$(lookup "select id from public.fundraising_fundraisers where campaign_id='$campaign'")
path=$(lookup "select path from public.fundraising_shares where fundraiser_id='$fundraiser'")
"${psql_cmd[@]}" --command "insert into public.fundraising_campaigns(id,organization_id,name,currency,goal_minor,starts_at,ends_at,status,scope,channels,public_visible,created_by)select md5('boss-phase7b-race:campaign2')::uuid,organization_id,'Synthetic race campaign 2',currency,goal_minor,starts_at,ends_at,status,scope,channels,public_visible,created_by from public.fundraising_campaigns where id='$campaign';insert into public.fundraising_fundraisers(id,organization_id,campaign_id,participant_id,person_id,unit_id,team_id,household_id,status,starts_at)select md5('boss-phase7b-race:fundraiser2')::uuid,organization_id,md5('boss-phase7b-race:campaign2')::uuid,participant_id,person_id,unit_id,team_id,household_id,status,starts_at from public.fundraising_fundraisers where id='$fundraiser';insert into public.boss_bucks_fundraiser_bindings select md5('boss-phase7b-race:fundraiser2')::uuid,household_id,authorized_by,guardian_relationship_id,clock_timestamp()from public.boss_bucks_fundraiser_bindings where fundraiser_id='$fundraiser';insert into public.boss_bucks_policy_revisions(campaign_id,organization_id,revision,mode,basis_points,currency,channels,created_by,request_id)select md5('boss-phase7b-race:campaign2')::uuid,organization_id,1,mode,basis_points,currency,channels,created_by,gen_random_uuid()from public.boss_bucks_policy_revisions where campaign_id='$campaign';insert into public.fundraising_shares(fundraiser_id,authorized_by)select md5('boss-phase7b-race:fundraiser2')::uuid,authorized_by from public.fundraising_shares where fundraiser_id='$fundraiser';update public.organization_modules set configuration=configuration||'{\"fundraising_issuance\":false}'::jsonb where organization_id=$org and module_id in(select id from public.modules where key='boss_bucks');" >/dev/null
path2=$(lookup "select path from public.fundraising_shares where fundraiser_id=md5('boss-phase7b-race:fundraiser2')::uuid")
source(){ local label=$1 link=$2 req;req=$(lookup 'select gen_random_uuid()');"${psql_cmd[@]}" --command "begin;set local role anon;select public.boss_fundraising_support(jsonb_build_object('action','intent','request_id','$req','input',jsonb_build_object('path','$link','capability',md5('$label')||md5('$label-2'),'display_name','Synthetic race supporter','anonymous',true,'amount_minor',1000)));reset role;select boss_private.fundraising_ingest_success((select id from public.fundraising_intents where request_id='$req'),'disposable-race','$label',1000,'USD',clock_timestamp());commit;" >"$race_dir/source-$label.out";lookup "select id from public.fundraising_success_evidence where source_reference='$label'"; }
e1=$(source first1 "$path");e2=$(source first2 "$path2");e3=$(source duplicate "$path");e4=$(source reversal "$path");e5=$(source policy "$path");e6=$(source correction "$path");e7=$(source rebuild "$path")
"${psql_cmd[@]}" --command "update public.organization_modules set configuration=configuration||'{\"fundraising_issuance\":true}'::jsonb where organization_id=$org and module_id in(select id from public.modules where key='boss_bucks')" >/dev/null
race first_wallet "select boss_private.bucks_issue('$e1');" "select boss_private.bucks_issue('$e2');" success
assert_sql 'one wallet under independent first grants' "select count(*)=1 from public.boss_bucks_wallets where household_id=$household"
wallet=$(lookup "select id from public.boss_bucks_wallets where household_id=$household")
"${psql_cmd[@]}" --command "insert into public.boss_bucks_access(wallet_id,person_id,guardian_relationship_id,organization_id,access_kind)values('$wallet',md5('boss-phase7b-race:parent')::uuid,$guardian,$org,'manager')" >/dev/null
race duplicate_source "select boss_private.bucks_issue('$e3');" "select boss_private.bucks_issue('$e3');" success
assert_sql 'one grant per source' "select count(*)=1 from public.boss_bucks_grants where evidence_id='$e3'"
race grant_reversal "select boss_private.bucks_issue('$e4');" "select boss_private.bucks_reverse_source('$e4','Synthetic reversal');" success
assert_sql 'termination once' "select count(*)=1 from public.boss_bucks_journals j join public.boss_bucks_grants g on g.id=j.grant_id where evidence_id='$e4'and kind='reversal'"
race reversal_replay "select boss_private.bucks_reverse_source('$e4','Synthetic reversal');" "select boss_private.bucks_reverse_source('$e4','Synthetic reversal');" success
race policy_grant "select id from public.fundraising_campaigns where id='$campaign'for update;insert into public.boss_bucks_policy_revisions(campaign_id,organization_id,revision,mode,basis_points,currency,channels,created_by,request_id)values('$campaign',$org,2,'percentage',10000,'USD',array['direct_support'],md5('boss-phase7b-race:admin')::uuid,gen_random_uuid());" "select boss_private.bucks_issue('$e5');" success
assert_sql 'source snapshot retains earlier policy' "select amount_minor=500 from public.boss_bucks_grants where evidence_id='$e5'"
race guardian_read "update public.guardian_relationships set can_manage_boss_bucks=false where id=$guardian;" "$(auth parent)select public.boss_bucks_read(jsonb_build_object('wallet_id','$wallet'));" PT403
"${psql_cmd[@]}" --command "update public.guardian_relationships set can_manage_boss_bucks=true where id=$guardian" >/dev/null
race correction_grant "insert into public.fundraising_intent_events(intent_id,state,source_reference)select intent_id,'refunded','Synthetic correction'from public.fundraising_success_evidence where id='$e6';" "select boss_private.bucks_issue('$e6');" PT409
assert_sql 'invalid post-wait source never issued' "select count(*)=0 from public.boss_bucks_grants where evidence_id='$e6'"
race posting_rebuild "select boss_private.bucks_issue('$e7');" "select boss_private.bucks_rebuild('$wallet');" success
assert_sql 'rebuild fresh after posting commit' "select boss_private.bucks_available('$wallet')=2500"
# Explicit expiration races with a coherent wallet read and reconstruction.
"${psql_cmd[@]}" --command "insert into public.boss_bucks_policy_revisions(campaign_id,organization_id,revision,mode,basis_points,currency,channels,expiry_seconds,created_by,request_id)values('$campaign',$org,3,'percentage',10000,'USD',array['direct_support'],1,md5('boss-phase7b-race:admin')::uuid,gen_random_uuid());update public.organization_modules set configuration=configuration||'{\"fundraising_issuance\":false}'::jsonb where organization_id=$org and module_id in(select id from public.modules where key='boss_bucks')" >/dev/null
e8=$(source expiring "$path")
"${psql_cmd[@]}" --command "update public.organization_modules set configuration=configuration||'{\"fundraising_issuance\":true}'::jsonb where organization_id=$org and module_id in(select id from public.modules where key='boss_bucks');select boss_private.bucks_issue('$e8');select pg_sleep(1.1)" >/dev/null
race expiration_read "select boss_private.bucks_expire();" "$(auth parent)select public.boss_bucks_read(jsonb_build_object('wallet_id','$wallet'));" success
race expiration_rebuild "select id from public.boss_bucks_wallets where id='$wallet'for update;select boss_private.bucks_expire();" "select boss_private.bucks_rebuild('$wallet');" success
assert_sql 'no negative available or duplicate expiry' "select boss_private.bucks_available('$wallet')=2500 and(select count(*)=1 from public.boss_bucks_journals j join public.boss_bucks_grants g on g.id=j.grant_id where g.evidence_id='$e8'and kind='expiration')"
race restriction_mutation "select id from public.boss_bucks_grants where evidence_id='$e1'for update;" "update public.boss_bucks_grants set organization_id=md5('boss-phase7b-race:other-org')::uuid where evidence_id='$e1';" 23514
assert_sql 'immutable original organization' "select organization_id=$org from public.boss_bucks_grants where evidence_id='$e1'"
printf 'PASS Phase 7B: %s observed concurrency races.\n' "$race_count"
