\set ON_ERROR_STOP on
begin;set local statement_timeout='8s';
\ir phase7e/fixture.sql
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.product_order('purchase-base');reset role;
select boss_private.rails_dispatch(pg_temp.did('purchase-base','checkout_id'));
select pg_temp.product_receive('purchase-base','authorized');
select pg_temp.check('authorization does not fulfill membership','PAYMENT',not exists(select 1 from public.discount_member_sources));
select pg_temp.product_receive('purchase-base','captured');
select pg_temp.check('capture creates exact canonical product source','PAYMENT',exists(select 1 from public.discount_order_items oi join public.discount_member_sources s on s.id=oi.source_id where oi.order_id=pg_temp.did('purchase-base','order_id')and s.kind='direct_purchase'and s.ends_at=s.starts_at+interval'120 days'));
select pg_temp.check('capture before settlement is active membership','PAYMENT',(select state='fulfilled'from public.discount_orders where id=pg_temp.did('purchase-base','order_id'))and not exists(select 1 from public.provider_event_evidence where kind='settled'));
select pg_temp.product_receive('purchase-base','captured');
select pg_temp.check('capture replay creates no duplicate source','IDEMPOTENCY',(select count(*)=1 from public.discount_member_sources));
select pg_temp.check('purchase never adds wallet grant','SEPARATION',(select count(*)=1 from public.boss_bucks_grants));
select pg_temp.check('membership payment uses shared rails','LINEAGE',exists(select 1 from public.discount_orders o join public.external_payment_tenders t on t.payment_id=o.payment_id and t.checkout_id=o.checkout_id where o.id=pg_temp.did('purchase-base','order_id')and t.purpose='products'));
select pg_temp.product_receive('purchase-base','settled');
select boss_private.rails_settlement_match(o.payment_id,e.id,0)from public.discount_orders o join public.provider_event_evidence e on e.event_reference='purchase-base-settled'where o.id=pg_temp.did('purchase-base','order_id');
select pg_temp.check('frozen product economics attribute exact org credit','SETTLEMENT',exists(select 1 from public.settlement_events e join public.discount_orders o on o.payment_id=e.payment_id where o.id=pg_temp.did('purchase-base','order_id')and e.kind='settled'and e.amount_minor=1750));
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.product_order('upgrade','upgrade-state','card',1,jsonb_build_object('base_source_id',pg_temp.product_source('purchase-base')));reset role;
select boss_private.rails_dispatch(pg_temp.did('upgrade','checkout_id'));select pg_temp.product_receive('upgrade','captured');
select pg_temp.check('upgrade co-terminates without replacing base','UPGRADE',exists(select 1 from public.discount_member_sources s join public.discount_member_sources b on b.id=s.base_source_id where s.kind='tier_upgrade'and s.ends_at=b.ends_at and s.membership_id=b.membership_id));
select pg_temp.check('upgrade is current state coverage','UPGRADE',(boss_private.discount_effective((select membership_id from public.discount_member_sources where kind='tier_upgrade'))->>'tier')='state');
set local role authenticated;select pg_temp.actor('household-only');
select pg_temp.conflict('forged other person upgrade base denied',format('select pg_temp.product_order(''forged-upgrade'',''upgrade-state'',''card'',1,%L)',jsonb_build_object('base_source_id',pg_temp.product_source('purchase-base'))));
select pg_temp.product_order('ach','base30','ach');reset role;
select boss_private.rails_dispatch(pg_temp.did('ach','checkout_id'));select pg_temp.product_receive('ach','ach_pending');
select pg_temp.check('ACH pending does not fulfill','ACH',(select payment_id is null and state='payment_pending'from public.discount_orders where id=pg_temp.did('ach','order_id')));
select pg_temp.product_receive('ach','settled');
select pg_temp.check('final ACH settlement fulfills once','ACH',(select state='fulfilled'and payment_id is not null from public.discount_orders where id=pg_temp.did('ach','order_id')));
set local role authenticated;select pg_temp.actor('parent');select pg_temp.product_order('unknown');reset role;
select boss_private.rails_dispatch(pg_temp.did('unknown','checkout_id'));select pg_temp.product_receive('unknown','unknown');
select pg_temp.check('unknown preserves original pending hold','UNKNOWN',boss_private.rails_hold(pg_temp.did('unknown','checkout_id'))and(select payment_id is null from public.discount_orders where id=pg_temp.did('unknown','order_id')));
select boss_private.rails_dispatch(pg_temp.did('unknown','checkout_id'));
select pg_temp.check('unknown retry preserves one provider operation','UNKNOWN',(select count(*)=1 from public.provider_operations where checkout_id=pg_temp.did('unknown','checkout_id')));
select pg_temp.product_receive('unknown','captured');
select pg_temp.check('unknown resolved capture fulfills original once','UNKNOWN',(select state='fulfilled'from public.discount_orders where id=pg_temp.did('unknown','order_id')));
set local role authenticated;select pg_temp.actor('parent');select pg_temp.product_order('canceled');select pg_temp.dm('cancel','order.cancel',jsonb_build_object('order_id',pg_temp.did('canceled','order_id')));reset role;
select pg_temp.conflict('canceled order cannot be dispatched',format('select boss_private.rails_dispatch(%L)',pg_temp.did('canceled','checkout_id')));
select pg_temp.check('cancellation creates no payment','CANCEL',(select payment_id is null and state='canceled'from public.discount_orders where id=pg_temp.did('canceled','order_id')));
insert into public.payment_routing_revisions(id,organization_id,account_id,purpose,currency,scope_type,scope_id,revision,starts_at,created_by)
values(pg_temp.f('campaign-product-route'),pg_temp.f('org'),pg_temp.f('rails-account'),'products','USD','campaign',pg_temp.fid('campaign'),1,clock_timestamp()-interval'1 minute',pg_temp.f('admin'));
insert into public.payment_routing_events(routing_id,state,actor_id)values(pg_temp.f('product-route'),'disabled',pg_temp.f('admin')),(pg_temp.f('campaign-product-route'),'active',pg_temp.f('admin'));
grant all on discount_test_results to anon;
set local role anon;
select pg_temp.check('campaign-only product route is offered in its exact public catalog','ROUTING',exists(select 1 from jsonb_array_elements(public.boss_discounts_catalog(null,pg_temp.fpath('share')))p where p->>'revision_id'=pg_temp.did('base30','revision_id')::text and(p->>'payment_available')::boolean));
reset role;select pg_temp.actor('parent');
select pg_temp.product_order('campaign-routed','base30','card',1,jsonb_build_object('path',pg_temp.fpath('share')));
select pg_temp.check('product checkout keeps exact campaign routing','ROUTING',(select routing_id=pg_temp.f('campaign-product-route')from public.payment_checkouts where id=pg_temp.did('campaign-routed','checkout_id')));
select boss_private.rails_dispatch(pg_temp.did('campaign-routed','checkout_id'));select pg_temp.product_receive('campaign-routed','captured');
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.check('organization credit retains canonical currency','CURRENCY',public.boss_discounts_read(jsonb_build_object('mode','organization','organization_id',pg_temp.f('org')))->'statistics'->'fundraising_credits'@>'[{"currency":"USD"}]'::jsonb);
reset role;
set constraints all immediate;
select count(*)passed_assertions,'Phase 7E product payments and upgrades'::text suite from phase5a_assertions;rollback;
