\set ON_ERROR_STOP on
begin;
set local statement_timeout='8s';
\ir phase7a/fixture.sql
create function pg_temp.fs(a text,i jsonb,req uuid default gen_random_uuid())returns jsonb language sql as $$select public.boss_fundraising_support(jsonb_build_object('action',a,'request_id',req,'input',i))$$;
grant execute on function pg_temp.fs(text,jsonb,uuid)to anon,authenticated;
select pg_temp.check('campaign canonical context','CORE',(select organization_id=pg_temp.f('org')and status='active'and goal_minor=10000 from public.fundraising_campaigns where id=pg_temp.fid('campaign')));
select pg_temp.check('one fundraiser stable participant','CORE',(select count(*)=1 and bool_and(participant_id=pg_temp.f('participant-child1')and person_id=pg_temp.f('child1'))from public.fundraising_fundraisers where campaign_id=pg_temp.fid('campaign')));
select pg_temp.check('new capability false for other guardians','AUTH',(select count(*)=0 from public.guardian_relationships where id<>pg_temp.f('guardian-child1')and can_manage_fundraising));
select pg_temp.check('50 deterministic unique tiles','BOARD',(select count(*)=50 and count(distinct amount_minor)=50 and min(amount_minor)=100 and max(amount_minor)=5000 and sum(amount_minor)=127500 from public.money_board_tiles where board_id=pg_temp.fid('board')));
do $$declare t record;begin for t in select ordinal,amount_minor from public.money_board_tiles where board_id=pg_temp.fid('board')loop perform pg_temp.check('tile amount '||t.ordinal,'BOARD',t.amount_minor=100+(t.ordinal-1)*100);end loop;end$$;
select pg_temp.check('raw tables RLS and closed','ACL',not exists(select 1 from pg_class where relnamespace='public'::regnamespace and relkind='r'and(relname like'fundraising_%'or relname like'money_board_%')and not relrowsecurity));
do $$declare t record;r text;begin for t in select oid,relname from pg_class where relnamespace='public'::regnamespace and relkind='r'and(relname like'fundraising_%'or relname like'money_board_%')loop foreach r in array array['anon','authenticated','service_role']loop perform pg_temp.check('closed '||r||' '||t.relname,'ACL',not has_table_privilege(r,t.oid,'SELECT,INSERT,UPDATE,DELETE'));end loop;end loop;end$$;
select pg_temp.check('closed success boundary','ACL',not has_function_privilege('authenticated','boss_private.fundraising_ingest_success(uuid,text,text,bigint,text,timestamptz)','execute')and not has_function_privilege('anon','boss_private.fundraising_ingest_success(uuid,text,text,bigint,text,timestamptz)','execute')and not has_function_privilege('service_role','boss_private.fundraising_ingest_success(uuid,text,text,bigint,text,timestamptz)','execute'));
set local role anon;
select pg_temp.check('public no internal identifiers','PUBLIC',public.boss_fundraising_public(pg_temp.fpath('share'))::text!~'(_id|date_of_birth|household|email|mobile)');
select pg_temp.check('public pending not raised','PUBLIC',public.boss_fundraising_public(pg_temp.fpath('share'))->'campaign'->>'raised_minor'='0');
select pg_temp.check('public board sum preview','PUBLIC',public.boss_fundraising_public(pg_temp.fpath('share'))->'board'->>'all_claimed_minor'='127500');
select pg_temp.check('minor shares not indexable','PUBLIC',public.boss_fundraising_public(pg_temp.fpath('share'))->'campaign'->>'indexable'='false');
select pg_temp.denied('guessed share unavailable',format('select public.boss_fundraising_public(%L)',repeat('0',48)),'PT404');
select pg_temp.denied('raw donor read unavailable','select * from public.fundraising_donors','42501');
select pg_temp.denied('guest management denied',format('select public.boss_fundraising_mutate(%L::jsonb)',jsonb_build_object('action','campaign.status','request_id',gen_random_uuid(),'input',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'expected_version',2,'status','paused'))),'42501');
select pg_temp.check('one reservation succeeds','RESERVE',pg_temp.fs('reserve',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',25,'capability',repeat('a',64)))->>'state'='reserved');
select pg_temp.check('reservation no raised total','RESERVE',public.boss_fundraising_public(pg_temp.fpath('share'))->'campaign'->>'raised_minor'='0');
select pg_temp.denied('same tile competing reservation',format('select pg_temp.fs(%L,%L::jsonb)','reserve',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',25,'capability',repeat('b',64))),'PT409');
select pg_temp.denied('forged tile ordinal',format('select pg_temp.fs(%L,%L::jsonb)','reserve',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',999,'capability',repeat('b',64))),'PT404');
select pg_temp.denied('forged participant rejected',format('select pg_temp.fs(%L,%L::jsonb)','intent',jsonb_build_object('path',pg_temp.fpath('share'),'capability',repeat('c',64),'amount_minor',100,'display_name','Synthetic','participant_id',pg_temp.f('participant-child2'))),'PT422');
select pg_temp.check('reserved intent derives amount','INTENT',pg_temp.fs('intent',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',25,'amount_minor',1,'capability',repeat('a',64),'display_name','Synthetic anonymous donor','email','donor@phase7a.example.invalid','anonymous',true,'fee_cover',true,'months',6,'source','qr'))->>'amount_minor'='2500');
select pg_temp.check('intent no raised total','INTENT',public.boss_fundraising_public(pg_temp.fpath('share'))->'campaign'->>'raised_minor'='0');
select pg_temp.check('intent payment unavailable','INTENT',public.boss_fundraising_public(pg_temp.fpath('share'))->>'payment_available'='false');
reset role;
select pg_temp.check('monthly six occurrences unpaid','RECURRING',(select count(*)=6 and bool_and(amount_minor=2500)from public.fundraising_recurring_occurrences));
select pg_temp.check('amount and QR immutable provenance','PROVENANCE',(select amount_minor=2500 and source_kind='qr'and provenance->>'participant_id'=pg_temp.f('participant-child1')::text and provenance->>'team_id'=pg_temp.f('falcons')::text and fee_cover from public.fundraising_intents where tile_id is not null));
select pg_temp.check('timeout within 8 to 10 minutes','RESERVE',(select bool_and(expires_at-starts_at between interval'8 minutes'and interval'10 minutes 1 second')from public.money_board_reservations));
insert into fundraising_ids select 'paid-intent',id,null from public.fundraising_intents where tile_id is not null;
select boss_private.fundraising_ingest_success(pg_temp.fid('paid-intent'),'disposable_fixture','synthetic-tile-25',2500,'USD',clock_timestamp());
select pg_temp.check('strict 25 not qualified','REWARD',(select not qualified and status='not_qualified'and trial_days=60 from public.fundraising_reward_qualifications));
select pg_temp.check('raised only trusted success','SUCCESS',boss_private.fundraising_raised(pg_temp.fid('campaign'))=2500);
select pg_temp.denied('success evidence immutable',format('update public.fundraising_success_evidence set amount_minor=1 where intent_id=%L',pg_temp.fid('paid-intent')),'23514');
set local role anon;
select pg_temp.check('paid tile claimed permanently','SUCCESS',public.boss_fundraising_public(pg_temp.fpath('share'))->'board'->'tiles'->24->>'state'='claimed');
select pg_temp.check('anonymous public presentation','PUBLIC',public.boss_fundraising_public(pg_temp.fpath('share'))->'supporters'->0->>'display_name'='Anonymous');
select pg_temp.denied('paid tile reservation denial',format('select pg_temp.fs(%L,%L::jsonb)','reserve',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',25,'capability',repeat('d',64))),'PT409');
select pg_temp.fs('intent',jsonb_build_object('path',pg_temp.fpath('share'),'amount_minor',2501,'capability',repeat('e',64),'display_name','Synthetic public donor','anonymous',false,'fee_cover',false));reset role;
insert into fundraising_ids select 'gift-intent',id,null from public.fundraising_intents where amount_minor=2501;
select boss_private.fundraising_ingest_success(pg_temp.fid('gift-intent'),'disposable_fixture','synthetic-direct-2501',2501,'USD',clock_timestamp());
select pg_temp.check('strict 25.01 gift pending','REWARD',(select qualified and status='gift_pending'from public.fundraising_reward_qualifications q join public.fundraising_success_evidence e on e.id=q.evidence_id where e.intent_id=pg_temp.fid('gift-intent')));
select pg_temp.check('total exact settled evidence','SUCCESS',boss_private.fundraising_raised(pg_temp.fid('campaign'))=5001);
select pg_temp.check('one fundraiser goal milestone','NOTIFY',(select count(*)=1 from public.fundraising_history where campaign_id=pg_temp.fid('campaign')and action='goal.reached'and fundraiser_id=pg_temp.fid('fundraiser')));
select pg_temp.check('no reservation notifications','NOTIFY',not exists(select 1 from public.notification_events e join public.fundraising_history h on h.id=e.source_id where e.source_type='fundraising_history'and h.action like'supporter.%'));
set local role authenticated;select pg_temp.actor('admin');
select pg_temp.denied('paid board regeneration denied',format('select pg_temp.fm(%L,%L::jsonb)','board.generate',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'board_id',pg_temp.fid('board'),'expected_version',3)),'PT409');
select pg_temp.check('organization dashboard settled','READ',public.boss_fundraising_read(jsonb_build_object('organization_id',pg_temp.f('org')))->'campaigns'->0->>'raised_minor'='5001');
select pg_temp.actor('coach');
select pg_temp.check('exact team progress','AUTH',jsonb_array_length(public.boss_fundraising_read(jsonb_build_object('organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons')))->'campaigns')=1);
select pg_temp.denied('coach organization scope denied',format('select public.boss_fundraising_read(%L::jsonb)',jsonb_build_object('organization_id',pg_temp.f('org'))),'PT403');
select pg_temp.denied('coach unrelated team denied',format('select public.boss_fundraising_read(%L::jsonb)',jsonb_build_object('organization_id',pg_temp.f('org'),'team_id',pg_temp.f('wildcats'))),'PT403');
select pg_temp.denied('coach private donor finance denied',format('select public.boss_fundraising_read(%L::jsonb)',jsonb_build_object('organization_id',pg_temp.f('org'),'team_id',pg_temp.f('falcons'),'financial',true)),'PT403');
select pg_temp.actor('parent');
select pg_temp.check('family guardian Child1','FAMILY',jsonb_array_length(public.boss_fundraising_read('{"mode":"family"}')->'campaigns')=1);
select pg_temp.denied('unrelated child family denied',format('select public.boss_fundraising_read(%L::jsonb)',jsonb_build_object('mode','family','child_id',pg_temp.f('child2'))),'PT403');
select pg_temp.actor('household-only');
select pg_temp.check('household membership gives no family authority','FAMILY',jsonb_array_length(public.boss_fundraising_read('{"mode":"family"}')->'campaigns')=0);
select pg_temp.actor('other-admin');
select pg_temp.denied('cross tenant campaign read denied',format('select public.boss_fundraising_read(%L::jsonb)',jsonb_build_object('organization_id',pg_temp.f('org'),'campaign_id',pg_temp.fid('campaign'))),'PT403');
reset role;
update public.guardian_relationships set can_manage_fundraising=false where id=pg_temp.f('guardian-child1');
set local role authenticated;select pg_temp.actor('parent');
select pg_temp.check('revoked capability removes family view','AUTH',jsonb_array_length(public.boss_fundraising_read('{"mode":"family"}')->'campaigns')=0);
select pg_temp.denied('stale guardian share command denied',format('select pg_temp.fm(%L,%L::jsonb)','share.reset',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'fundraiser_id',pg_temp.fid('fundraiser'))),'PT403');
set local role anon;select pg_temp.denied('public child share suspended with guardian revoke',format('select public.boss_fundraising_public(%L)',pg_temp.fpath('share')),'PT404');reset role;
update public.guardian_relationships set can_manage_fundraising=true where id=pg_temp.f('guardian-child1');
set local role anon;select pg_temp.fs('reserve',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',1,'capability',repeat('f',64)));reset role;
update public.money_board_reservations set starts_at=clock_timestamp()-interval'20 minutes',expires_at=clock_timestamp()-interval'10 minutes'where tile_id=(select id from public.money_board_tiles where board_id=pg_temp.fid('board')and ordinal=1);
set local role anon;
select pg_temp.check('expired unpaid tile available','EXPIRY',public.boss_fundraising_public(pg_temp.fpath('share'))->'board'->'tiles'->0->>'state'='available');
select pg_temp.denied('stale expired reservation intent denied',format('select pg_temp.fs(%L,%L::jsonb)','intent',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',1,'capability',repeat('f',64),'display_name','Synthetic')),'PT409');
select pg_temp.fs('reserve',jsonb_build_object('path',pg_temp.fpath('share'),'ordinal',1,'capability',repeat('9',64)));select pg_temp.fs('release',jsonb_build_object('path',pg_temp.fpath('share'),'capability',repeat('9',64)));
select pg_temp.check('released available and history retained','EXPIRY',public.boss_fundraising_public(pg_temp.fpath('share'))->'board'->'tiles'->0->>'state'='available');reset role;
select pg_temp.check('expiry retains attempts','HISTORY',(select count(*)=2 from public.money_board_reservations where tile_id=(select id from public.money_board_tiles where board_id=pg_temp.fid('board')and ordinal=1)));
set local role authenticated;select pg_temp.actor('parent');select pg_temp.fm('share.reset',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'fundraiser_id',pg_temp.fid('fundraiser')),'new-share');
set local role anon;select pg_temp.denied('rotated old share unavailable',format('select public.boss_fundraising_public(%L)',pg_temp.fpath('share')),'PT404');reset role;
select pg_temp.check('historical share attribution retained','PROVENANCE',(select share_id=(select id from public.fundraising_shares where path=pg_temp.fpath('share'))from public.fundraising_intents where id=pg_temp.fid('paid-intent')));
update public.organization_modules set status='inactive'where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='fundraising');
set local role anon;select pg_temp.denied('disabled module public denial',format('select public.boss_fundraising_public(%L)',pg_temp.fpath('new-share')),'PT404');reset role;
update public.organization_modules set status='active'where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='fundraising');
set local role authenticated;select pg_temp.actor('admin');select pg_temp.fm('campaign.status',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'expected_version',2,'status','paused'));
set local role anon;select pg_temp.denied('paused campaign public denial',format('select public.boss_fundraising_public(%L)',pg_temp.fpath('new-share')),'PT404');
set local role authenticated;select pg_temp.actor('admin');select pg_temp.fm('campaign.status',jsonb_build_object('campaign_id',pg_temp.fid('campaign'),'expected_version',3,'status','archived'));reset role;
select pg_temp.check('archive ends controlled relationships','CLEANUP',not exists(select 1 from public.fundraising_fundraisers where campaign_id=pg_temp.fid('campaign')and status in('pending','active')));
select pg_temp.check('archive revokes shares','CLEANUP',not exists(select 1 from public.fundraising_shares where fundraiser_id=pg_temp.fid('fundraiser')and status='active'));
select pg_temp.check('archive removes active reservation','CLEANUP',not exists(select 1 from public.money_board_reservations where released_at is null));
select pg_temp.check('archive retains success provenance','CLEANUP',boss_private.fundraising_raised(pg_temp.fid('campaign'))=5001);
select count(*)passed_assertions from pg_temp.phase5a_assertions;
rollback;
