import type { Metadata } from "next";
import { requireSession } from "@/lib/auth/session";
import { loadAdminView } from "@/lib/admin/data";
import { loadFundraising } from "@/lib/fundraising/data";
import { fundraisingQuery } from "@/lib/fundraising/input";
import { FundraisingConsole } from "@/components/fundraising/console";
export const metadata: Metadata = { title: "Fundraising & Digital Money Board" };
export const dynamic = "force-dynamic";
export default async function FundraisingPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { await requireSession("/app/fundraising"); const input = await searchParams, admin = await loadAdminView("home", input.org), organizationId = typeof input.org === "string" ? input.org : admin.organizationId, query = fundraisingQuery({ ...input, org: organizationId ?? undefined }, input.view === "family"); if (!query) return <p role="status">Review the organization and fundraising filters.</p>; if (query.mode === "organization" && !query.team_id && !query.unit_id) query.scopes_only = true; const data = await loadFundraising(query); return <><h1>Fundraising</h1><form method="get" className="fundraising-filters"><label>Organization<select name="org" defaultValue={organizationId ?? ""}><option value="">Choose organization</option>{admin.organizations.map(org => <option value={org.id} key={org.id}>{org.label}</option>)}</select></label><label>Team<select name="team" defaultValue={typeof input.team === "string" ? input.team : ""}><option value="">All authorized teams</option>{data.catalog?.teams.map(team => <option value={team.id} key={team.id}>{team.name}</option>)}</select></label><label>Program<select name="unit" defaultValue={typeof input.unit === "string" ? input.unit : ""}><option value="">All authorized programs</option>{data.catalog?.units.map(unit => <option value={unit.id} key={unit.id}>{unit.name}</option>)}</select></label><label>View<select name="view" defaultValue={input.view === "family" ? "family" : "organization"}><option value="organization">Organization / team</option><option value="family">Whole Family</option></select></label><button className="button button-outline">Apply filters</button></form><FundraisingConsole data={data} organizationId={organizationId} family={query.mode === "family"} /></>; }
