"use client";
import Link from "next/link";
import type { AthleteProfileData } from "@/lib/athlete-profiles/contracts";
import { AthleteProfileActionForm } from "./action-form";
const text = (value: unknown) => typeof value === "string" ? value : "";
const number = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value : 0;
export function AthleteProfileHub({ data }: { data: AthleteProfileData }) {
  const view = data.profile, profile = view?.profile, showcase = view?.showcase, revision = showcase?.revision;
  return <div className="athlete-profile-hub">
    <nav className="athlete-profile-subjects" aria-label="Athlete profiles">{data.subjects.map(subject => <Link key={subject.profile_id} href={`/app/athletes?profile=${subject.profile_id}`}>{subject.display_name}</Link>)}</nav>
    {!view && <section className="athlete-profile-panel"><h2>Create a canonical profile</h2><p>Use an existing participant ID. This creates presentation data for the same person and participant identity.</p><AthleteProfileActionForm label="Create profile" build={fields => ({ action: "profile.create", input: { participant_id: text(fields.get("participant_id")), visibility: "athlete_guardian", safe_fields: { display_name: text(fields.get("display_name")) } } })}><label className="form-field"><span>Participant ID</span><input name="participant_id" required /></label><label className="form-field"><span>Display name</span><input name="display_name" required maxLength={100} /></label></AthleteProfileActionForm></section>}
    {view && profile && <>
      <section className="athlete-profile-hero"><div><p className="eyebrow">Persistent athlete profile</p><h2>{text(profile.fields.display_name) || "Athlete profile"}</h2><p>{text(profile.fields.bio) || "Verified history and approved recruiting presentation in one profile."}</p></div><div className="athlete-completeness"><strong>{profile.completeness.completed}/{profile.completeness.possible}</strong><span>profile sections ready</span><small>Completeness does not change visibility.</small></div></section>
      <section className="athlete-profile-grid"><article className="athlete-profile-panel"><h3>Sports and origins</h3>{view.origins.length ? <ul>{view.origins.map((origin, index) => <li key={`${origin.team_id}-${origin.starts_at}-${index}`}><strong>{origin.team}</strong><span>{origin.organization}{origin.position ? ` · ${origin.position}` : ""}</span><small>{origin.current ? "Current relationship" : "Historical origin retained"}</small></li>)}</ul> : <p>No authorized origins are available.</p>}</article>
      <article className="athlete-profile-panel"><h3>Verified statistics</h3>{view.statistics.length ? <ul>{view.statistics.map((stat, index) => <li key={index}><strong>{text(stat.sport_key)}</strong><span>{text(stat.freshness)}</span><small>Generation {number(stat.generation)}</small></li>)}</ul> : <p>No current verified summaries are available. Missing coverage is never shown as zero.</p>}</article>
      <article className="athlete-profile-panel"><h3>Measurables</h3>{view.measurables.length ? <ul>{view.measurables.map((item, index) => <li key={text(item.id) || index}><strong>{text(item.metric_key)}</strong><span>{String(item.value ?? "")} {text(item.unit)}</span><small>{text(item.provenance).replaceAll("_", " ")}</small></li>)}</ul> : <p>No measurements have been added.</p>}</article>
      <article className="athlete-profile-panel"><h3>Achievements and records</h3>{view.achievements.length ? <ul>{view.achievements.map((item, index) => <li key={text(item.id) || index}><strong>{text(item.title)}</strong><span>{text(item.achievement_type).replaceAll("_", " ")}</span><small>{text(item.verification_level).replaceAll("_", " ")}</small></li>)}</ul> : <p>No approved achievements are available.</p>}</article></section>
      {view.authority.can_manage && <section className="athlete-profile-panel"><h3>Profile presentation</h3><AthleteProfileActionForm label="Save new profile revision" build={fields => ({ action: "profile.revise", input: { profile_id: profile.id, expected_version: profile.version, visibility: profile.visibility, safe_fields: { display_name: text(fields.get("display_name")), bio: text(fields.get("bio")), positions: text(fields.get("positions")).split(",").map(v => v.trim()).filter(Boolean), goals: text(fields.get("goals")) } } })}><label className="form-field"><span>Display name</span><input name="display_name" defaultValue={text(profile.fields.display_name)} maxLength={100} required /></label><label className="form-field"><span>Positions</span><input name="positions" defaultValue={Array.isArray(profile.fields.positions) ? profile.fields.positions.join(", ") : ""} /></label><label className="form-field"><span>Short bio</span><textarea name="bio" defaultValue={text(profile.fields.bio)} maxLength={1200} /></label><label className="form-field"><span>Athletic goals</span><textarea name="goals" defaultValue={text(profile.fields.goals)} maxLength={800} /></label></AthleteProfileActionForm></section>}
      <section className="athlete-profile-panel"><h3>Recruiting showcase</h3><p>Unlisted by default. Publication requires a current, field-scoped guardian consent.</p>{!showcase && view.authority.can_manage_showcase && <AthleteProfileActionForm label="Create draft showcase" build={() => ({ action: "showcase.create", input: { profile_id: profile.id } })} />}{showcase && <><dl className="athlete-showcase-status"><div><dt>State</dt><dd>{showcase.state}</dd></div><div><dt>Revision</dt><dd>{number(revision?.revision) || "Not drafted"}</dd></div><div><dt>Active links</dt><dd>{showcase.links.filter(link => link.status === "active").length}</dd></div></dl>{view.authority.can_manage_showcase && <AthleteProfileActionForm label="Save showcase revision" build={fields => ({ action: "showcase.revise", input: { showcase_id: showcase.id, expected_version: showcase.version, profile_revision_id: profile.current_revision_id, sport_keys: text(fields.get("sports")).split(",").map(v => v.trim()).filter(Boolean), visible_categories: ["overview", "sports", "statistics", "measurables", "achievements", "history", "media"], stat_metric_keys: text(fields.get("metrics")).split(",").map(v => v.trim()).filter(Boolean), presentation: { headline: text(fields.get("headline")) } } })}><label className="form-field"><span>Headline</span><input name="headline" maxLength={160} defaultValue={text(revision?.presentation && typeof revision.presentation === "object" ? (revision.presentation as Record<string, unknown>).headline : "")} /></label><label className="form-field"><span>Sports</span><input name="sports" placeholder="football, basketball" defaultValue={Array.isArray(revision?.sport_keys) ? revision.sport_keys.join(", ") : ""} /></label><label className="form-field"><span>Verified metric keys</span><input name="metrics" placeholder="passing_yards, touchdowns" defaultValue={Array.isArray(revision?.stat_metric_keys) ? revision.stat_metric_keys.join(", ") : ""} /></label></AthleteProfileActionForm>}
      {view.authority.relationship === "guardian" && showcase.current_revision_id && !showcase.current_consent_id && <AthleteProfileActionForm label="Approve current showcase" build={() => ({ action: "consent.grant", input: { showcase_id: showcase.id, showcase_revision_id: showcase.current_revision_id!, approved_categories: ["overview", "sports", "statistics", "measurables", "achievements", "history", "media"], expires_at: new Date(Date.now() + 365 * 86400000).toISOString() } })} />}
      {view.authority.can_manage_showcase && showcase.current_consent_id && showcase.state !== "active" && <AthleteProfileActionForm label="Publish approved showcase" build={() => ({ action: "showcase.publish", input: { showcase_id: showcase.id, expected_version: showcase.version } })} />}
      {view.authority.can_manage_showcase && showcase.state === "active" && <AthleteProfileActionForm label="Create 30-day private link" build={() => ({ action: "share.create", input: { showcase_id: showcase.id, expires_at: new Date(Date.now() + 30 * 86400000).toISOString() } })} />}
      {showcase.links.map(link => <div className="athlete-share-row" key={link.id}><span>{link.token_prefix}... · {link.status}</span>{link.status === "active" && view.authority.can_manage_showcase && <AthleteProfileActionForm label="Revoke" build={() => ({ action: "share.revoke", input: { share_link_id: link.id } })} />}</div>)}
      {showcase.state === "active" && view.authority.can_manage_showcase && <AthleteProfileActionForm label="Disable recruiting showcase" build={() => ({ action: "showcase.disable", input: { showcase_id: showcase.id } })} />}</>}</section>
    </>}
  </div>;
}
