import Image from "next/image";
import Link from "next/link";
import ApprovedHeader from "@/components/ApprovedHeader";
import ApprovedFooter from "@/components/ApprovedFooter";
import home from "../approvedHome.module.css";
import s from "./organizations.module.css";
export const metadata={title:"Who It’s For | The Boss Ecosystem",description:"Fundraising and connection for schools, sports teams, churches, nonprofits, community groups and camps. Find the Boss tools that fit your people and purpose."};
function Art({crop,alt}:{crop:string;alt:string}){return <svg viewBox={crop} preserveAspectRatio="xMidYMid slice" role="img" aria-label={alt}><image href="/design/organizations-approved.png" width="787" height="1997"/></svg>}
function Icon({kind}:{kind:string}){return <svg viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='fundraise'?<><path d="m5 13 20-8v21L5 19v-6Zm20-8 3-2v25l-3-2M7 20l3 9h6l-3-7M2 13v6"/></>:kind==='home'?<><path d="m2 15 14-12 14 12M6 13v16h20V13M12 29V18h8v11"/></>:<><circle cx="16" cy="9" r="4"/><path d="M9 28v-8c0-7 14-7 14 0v8H9Z"/><circle cx="5" cy="11" r="3"/><circle cx="27" cy="11" r="3"/><path d="M2 27v-8h4m24 8v-8h-4"/></>}</svg>}
const audiences=[['Schools & student programs','Support classrooms, bands, clubs and student opportunities.','21 548 242 182','Marching band students in BOSS uniforms with brass instruments'],['Sports teams & leagues','Raise for seasons, equipment and travel while keeping teams connected.','275 548 237 182','A female coach with teenage volleyball players in BOSS jerseys'],['Churches & ministries','Bring support to youth, kids, camps and outreach.','524 548 242 182','Youth ministry volunteers and adult leaders packing outreach supplies'],['Nonprofits','Connect supporters with the work that matters.','21 817 364 194','Two adult volunteers working together on a community service project'],['Community groups & camps','Fund shared experiences and keep your community involved.','402 817 364 194','A camp counselor helping young children with an outdoor activity']];
export default function Page(){return <div className={home.home}><a href="#main-content" className={home.skipLink}>Skip to content</a><ApprovedHeader/><main id="main-content" className={s.page}>
<section className={s.hero} aria-labelledby="organizations-title"><Image src="/images/approved/organizations-hero.png" alt="Adult and teenage volunteers in BOSS shirts packing food donations outside a community center" fill priority sizes="100vw" className={s.heroPhoto}/><div className={s.heroCopy}><p className={s.eyebrow}>WHO IT’S FOR</p><h1 id="organizations-title">Your people.<br/>Your purpose.<br/><span>One Boss<br/>ecosystem.</span></h1><p className={s.heroLead}>Fundraising and connection for the organizations that bring people together.</p><div className={s.actions}><a href="#find-your-fit" className={s.button}>Find Your Fit</a><Link href="/fundraising" className={s.outline}>Explore Fundraising</Link></div></div></section>
<section id="find-your-fit" className={s.audiences} aria-labelledby="audiences-title"><h2 id="audiences-title">Different missions. <span>More possibilities.</span></h2><div className={s.audienceGrid}>{audiences.map(([title,copy,crop,alt])=><article key={title}><Art crop={crop} alt={alt}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className={s.platform} aria-labelledby="platform-title"><figure><Art crop="15 1101 445 300" alt="Illustrative Boss Organization Hub dashboard with fundraising, calendar, messages and programs"/><figcaption>Illustrative product preview.</figcaption></figure><div><h2 id="platform-title">Start with what you need.<br/><span>Add more as you grow.</span></h2><p>Choose the Boss tools that fit your people and your goals.</p><ul>{['Fundraise for your next goal','Keep teams and programs connected','Bring families into the picture'].map(title=><li key={title}><b aria-hidden="true">✓</b><h3>{title}</h3></li>)}</ul></div></section>
<section className={s.ecosystem} aria-labelledby="ecosystem-title"><h2 id="ecosystem-title">One connected <span>Boss ecosystem.</span></h2><div className={s.ecosystemGrid}>{[['fundraise','Fundraise Like a Boss.','Boss Bucks cards and the Digital Money Board.','Explore Fundraising','/fundraising'],['people','Engage Like a Boss.','Schedules, communication and team organization.','Explore Boss Engage','/engage'],['home','Keep it all together.','One family view across kids, teams and organizations.','Explore Family Hub','/family-hub']].map(([kind,title,copy,label,href])=><article key={kind}><div className={s.circle}><Icon kind={kind}/></div><h3>{title}</h3><p>{copy}</p><Link href={href}>{label} <span aria-hidden="true">›</span></Link></article>)}</div><p className={s.vision}>Platform vision. Features and availability vary by program.</p></section>
<section className={s.finalCta}><h2>Tell us about your organization.</h2><p>Let’s find the right starting point for your people and your purpose.</p><Link href="/fundraising/get-started" className={s.button}>Get Started <span aria-hidden="true">›</span></Link></section>
</main><ApprovedFooter/></div>}
