import NetlifyForm from "@/components/NetlifyForm";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import s from "../get-started/start.module.css";
export const metadata={title:"Become a Merchant Partner"};
export default function Page(){return <main className={s.page}><SiteHeader/><section className={s.intro}><div className={s.eyebrow}>MERCHANT PARTNER</div><h1>Bring your business into Boss Bucks.</h1><p>Tell us about your business and the value you would like to offer Boss Bucks members.</p></section><section className={s.formWrap}><NetlifyForm name="boss-merchant-partner"><p className={s.hidden}><label>Do not fill this out: <input name="bot-field"/></label></p><div className={s.grid}>
<label>First name<input name="firstName" required/></label><label>Last name<input name="lastName" required/></label><label>Title<input name="title"/></label><label>Phone<input name="phone" required type="tel"/></label><label className={s.full}>Email<input name="email" required type="email"/></label>
<label>Business name<input name="businessName" required/></label><label>Business category<input name="category" required/></label><label>Website<input name="website" type="url" placeholder="https://"/></label><label>Number of locations<input name="locations" inputMode="numeric"/></label><label>City<input name="city" required/></label><label>State<input name="state" required/></label>
<label>Business reach<select name="reach" required defaultValue=""><option value="" disabled>Select one</option><option>One Location</option><option>Local Multi-location</option><option>Metro</option><option>Regional</option><option>Statewide</option><option>Nationwide</option></select></label><label>Offer type<select name="offerType" required defaultValue=""><option value="" disabled>Select one</option><option>Percent Off</option><option>Dollar Off</option><option>BOGO</option><option>Free Item</option><option>Special Price</option><option>Other</option></select></label>
<label className={s.full}>Proposed offer<input name="proposedOffer" required placeholder="Example: 15% off one entrée"/></label><label className={s.full}>Restrictions or details<textarea name="restrictions" rows={4}/></label>
<label>Use frequency<select name="useFrequency" defaultValue=""><option value="">Not sure</option><option>Unlimited</option><option>Limited</option></select></label><label>Interest<select name="interest" required defaultValue=""><option value="" disabled>Select one</option><option>List My Business</option><option>Learn More</option><option>Become Featured</option><option>Sponsorship / Team Partnership</option></select></label>
</div><input type="hidden" name="leadType" value="Merchant Partner"/><input type="hidden" name="source" value="website-merchant-intake"/><button type="submit">Submit Merchant Interest →</button><p className={s.note}>Submission does not guarantee acceptance into the Boss Bucks merchant network.</p></NetlifyForm></section></main>}
