"use client";
import Link from "next/link";
import type { AttendanceData, AttendanceOccurrence, AttendanceQuery, AttendanceSubject } from "@/lib/attendance/contracts";
import { attendanceFeatureKeys, attendanceStatuses, checkinStates } from "@/lib/attendance/contracts";
import { localDateTime, localToInstant } from "@/lib/calendar/temporal";
import { CoordinationForm, CoordinationField, fieldInteger, fieldNullable, fieldText } from "@/components/coordination/action-form";
import { CoordinationFilters, coordinationHref, displayInstant, humanize } from "@/components/coordination/presentation";

export function AttendanceConsole({ data, query: requestedQuery }: { data: AttendanceData; query: AttendanceQuery }) {
  const query = { ...requestedQuery, from: data.range.from, to: data.range.to, ...(data.organization_id ? { organization_id: data.organization_id } : {}) };
  return <div className="coordination-console"><div className="page-heading"><p className="eyebrow muted">Availability and RSVP</p><h1>Attendance.</h1><p>Respond for yourself or an authorized child. Your current event relationships determine the available actions.</p></div>
    {data.unavailable ? <p className="form-notice" role="status">Attendance is temporarily unavailable. Refresh to try again.</p> : <>
      {data.options_limited && <p className="form-notice">Organization choices are limited. Keep a specific authorized organization selected to refine this view.</p>}
      <CoordinationFilters resource="attendance" query={query} organizations={data.organizations} teams={data.teams} units={data.units} children={data.children.map(child => ({ id: child.person_id, label: child.display_name }))} />
      {data.features.attendance !== true && !data.occurrences.length ? <p className="empty-state">Attendance is not enabled in your current context.</p> : <>
        <div className="coordination-tabs" aria-label="Attendance views"><Link href={coordinationHref("attendance", query, { view: "family" })} aria-current={query.view === "family" ? "page" : undefined}>Family and personal</Link>{data.occurrences.some(occurrence => occurrence.capabilities.view_summary || occurrence.capabilities.manage || occurrence.capabilities.checkin) && <Link href={coordinationHref("attendance", query, { view: "staff" })} aria-current={query.view === "staff" ? "page" : undefined}>Team attendance</Link>}{query.event_id && query.view === "history" && <span aria-current="page">History</span>}</div>
        {query.view === "family" && <p className="coordination-hint">Choose a child to narrow the view. Household membership alone does not authorize an RSVP.</p>}
        <div className="coordination-list">{data.occurrences.map(occurrence => <AttendanceCard key={`${occurrence.event_id}:${occurrence.occurrence_key}`} occurrence={occurrence} checkinEnabled={data.features.attendance === true && data.features.checkin === true} rsvpEnabled={data.features.attendance === true && data.features.rsvp === true} />)}</div>
        {query.view === "history" && <div className="coordination-list">{data.history.map(entry => <article className="coordination-card" key={entry.id}><h2>{humanize(entry.status)}</h2><p>{humanize(entry.subject_kind)} response · Version {entry.version} · {humanize(entry.change_kind)}</p><p><time dateTime={entry.created_at}>{displayInstant(entry.created_at)} UTC</time></p><p>Occurrence: {entry.occurrence_key}</p>{entry.needs_reconfirmation && <p>Reconfirmation required after an event change.</p>}</article>)}</div>}{!data.occurrences.length && !data.history.length && <p className="empty-state">No authorized events are available for these filters.</p>}
      </>}
      {data.capabilities.configure && data.organization_id && <details className="coordination-editor"><summary>Attendance configuration</summary><CoordinationForm key={JSON.stringify(data.features)} resource="attendance" label="Save attendance configuration" build={form => ({ operation: "attendance.configure", input: { organization_id: data.organization_id!, configuration: Object.fromEntries(attendanceFeatureKeys.map(key => [key, key === "minimum_self_response_age" ? Number(fieldText(form, key)) : form.get(key) === "on"])) } })}><div className="coordination-fields">{attendanceFeatureKeys.filter(key => key !== "minimum_self_response_age").map(key => <label className="calendar-check" key={key}><input type="checkbox" name={key} defaultChecked={data.features[key] === true} />{humanize(key)}</label>)}<CoordinationField name="minimum_self_response_age" label="Minimum participant self-response age" type="number" min={18} max={100} value={typeof data.features.minimum_self_response_age === "number" ? data.features.minimum_self_response_age : 18} required /></div></CoordinationForm></details>}
      {data.features.attendance_reminders === true && data.capabilities.configure && data.organization_id && <details className="coordination-editor"><summary>Prepare attendance reminders</summary><p className="coordination-hint">Only currently eligible recipients receive a deduplicated update. Process prepared work through Notifications.</p><CoordinationForm resource="attendance" label="Prepare reminders" build={form => ({ operation: "reminders.prepare", input: { organization_id: data.organization_id!, from: query.from, to: query.to, kind: fieldText(form, "kind") } })}><label className="form-field"><span>Reminder type</span><select name="kind"><option value="requested">RSVP requested</option><option value="deadline">Deadline approaching</option><option value="no_response">Missing response</option></select></label></CoordinationForm></details>}
    </>}
  </div>;
}
export function AttendanceCard({ occurrence, checkinEnabled = false, rsvpEnabled = false, compact = false }: { occurrence: AttendanceOccurrence; checkinEnabled?: boolean; rsvpEnabled?: boolean; compact?: boolean }) {
  const responseOpen = ["scheduled", "confirmed"].includes(occurrence.status) && Date.parse(occurrence.end_at) > Date.now(), checkinOpen = ["scheduled", "confirmed", "completed"].includes(occurrence.status), staff = occurrence.capabilities.view_summary;
  return <article className="coordination-card"><header><div><p className="eyebrow muted">{occurrence.rsvp_mode === "required" ? "Response required" : humanize(occurrence.rsvp_mode)}</p><h2>{occurrence.title}</h2><p><time dateTime={occurrence.start_at}>{displayInstant(occurrence.start_at, occurrence.timezone)}</time> · {occurrence.timezone}</p></div><span className="status-pill">{humanize(occurrence.status)}</span></header>
    {(occurrence.settings.effective_deadline_at ?? occurrence.settings.response_deadline_at) && <p className="coordination-deadline">Respond by {displayInstant((occurrence.settings.effective_deadline_at ?? occurrence.settings.response_deadline_at)!, occurrence.timezone)}. {occurrence.settings.deadline_policy === "allow_late" ? "Late responses are marked." : "Responses lock after the deadline."}</p>}
    {!responseOpen && <p className="form-notice">This event does not request a new attendance response.</p>}
    {staff && <AttendanceSummary occurrence={occurrence} />}
    {!compact && <div className="coordination-subjects">{occurrence.subjects.map(subject => <SubjectRow key={`${subject.subject_kind}:${subject.person_id}:${subject.response?.version ?? 0}:${subject.checkin?.version ?? 0}`} occurrence={occurrence} subject={subject} rsvpEnabled={rsvpEnabled && responseOpen} checkinEnabled={checkinEnabled && checkinOpen} />)}</div>}
    {compact && <Link className="card-link" href={coordinationHref("attendance", { view: staff ? "staff" : "family", from: occurrence.start_at, to: new Date(Date.parse(occurrence.end_at) + 86_400_000).toISOString(), organization_id: occurrence.organization_id, event_id: occurrence.event_id, occurrence_key: occurrence.occurrence_key })}>Review attendance</Link>}
    {!compact && occurrence.capabilities.manage && <EventSettings key={occurrence.settings.version} occurrence={occurrence} />}{!compact && staff && <Link className="card-link" href={coordinationHref("attendance", { view: "history", organization_id: occurrence.organization_id, event_id: occurrence.event_id, from: new Date(Date.now() - 30 * 86_400_000).toISOString(), to: new Date(Date.now() + 86_400_000).toISOString() })}>Attendance response history</Link>}
  </article>;
}
export function AttendanceSummary({ occurrence }: { occurrence: AttendanceOccurrence }) {
  return <dl className="coordination-summary" aria-label="Attendance summary">{[["attending", "Attending"], ["not_attending", "Not attending"], ["maybe", "Maybe"], ["pending", "Pending / no response"], ["unknown", "Unknown"], ["needs_reconfirmation", "Reconfirm"], ["total", "Total"]].map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{occurrence.summary[key as keyof AttendanceOccurrence["summary"]]}</dd></div>)}</dl>;
}
function SubjectRow({ occurrence, subject, rsvpEnabled, checkinEnabled }: { occurrence: AttendanceOccurrence; subject: AttendanceSubject; rsvpEnabled: boolean; checkinEnabled: boolean }) {
  const response = subject.response, target = { event_id: occurrence.event_id, occurrence_key: occurrence.occurrence_key, person_id: subject.person_id, participant_id: subject.participant_id, subject_kind: subject.subject_kind };
  return <section className="coordination-subject"><div className="record-heading"><h3>{subject.display_name}</h3><span className="status-pill">{response ? humanize(response.status) : "No response"}</span></div><p className="coordination-hint">{humanize(subject.subject_kind)}{response?.is_late ? " · Late response" : ""}{response?.needs_reconfirmation ? " · Please reconfirm after the event change" : ""}</p>
    {response && subject.capabilities.view_private_notes && (response.reason || response.note) && <details className="coordination-private-note"><summary>Private response details</summary>{response.reason && <p>Reason: {response.reason}</p>}{response.note && <p>{response.note}</p>}</details>}
    {rsvpEnabled && (subject.capabilities.respond || subject.capabilities.manage) && <details className="coordination-editor" open={response === null || response.needs_reconfirmation}><summary>Respond for {subject.display_name}</summary><CoordinationForm resource="attendance" label={response?.needs_reconfirmation ? "Reconfirm response" : "Save response"} build={form => ({ operation: "response.set", input: { ...target, status: fieldText(form, "status"), expected_version: response?.version ?? 0, reason: fieldNullable(form, "reason"), note: fieldNullable(form, "note"), arrival_difference_minutes: fieldInteger(form, "arrival_difference_minutes"), departure_difference_minutes: fieldInteger(form, "departure_difference_minutes"), ...(subject.capabilities.manage ? { override_deadline: form.get("override_deadline") === "on" } : {}) } })}><div className="coordination-fields"><label className="form-field"><span>Response</span><select name="status" defaultValue={response?.status ?? "attending"}>{attendanceStatuses.map(status => <option value={status} key={status}>{humanize(status)}</option>)}</select></label><CoordinationField name="reason" label="Private reason (optional)" value={response?.reason} /><label className="form-field"><span>Private note (optional)</span><textarea name="note" maxLength={500} defaultValue={response?.note ?? ""} /></label><CoordinationField name="arrival_difference_minutes" label="Arrival difference in minutes (optional)" type="number" min={-1440} max={1440} value={response?.arrival_difference_minutes} /><CoordinationField name="departure_difference_minutes" label="Departure difference in minutes (optional)" type="number" min={-1440} max={1440} value={response?.departure_difference_minutes} /></div><p className="coordination-hint">Timing differences and absence details remain private to the authorized response context. Positive minutes mean later than the event time.</p>{subject.capabilities.manage && <label className="calendar-check"><input name="override_deadline" type="checkbox" />Override a passed deadline. This decision is audited.</label>}</CoordinationForm></details>}
    {checkinEnabled && subject.capabilities.checkin && <CoordinationForm resource="attendance" label="Save check-in" build={form => ({ operation: "checkin.set", input: { ...target, state: fieldText(form, "state"), expected_version: subject.checkin?.version ?? 0 } })}><label className="form-field"><span>Check-in for {subject.display_name}</span><select name="state" defaultValue={subject.checkin?.state ?? "expected"}>{checkinStates.map(state => <option key={state} value={state}>{humanize(state)}</option>)}</select></label></CoordinationForm>}
  </section>;
}
function EventSettings({ occurrence }: { occurrence: AttendanceOccurrence }) {
  const settings = occurrence.settings;
  return <details className="coordination-editor"><summary>Event RSVP settings</summary><CoordinationForm resource="attendance" label="Save RSVP settings" build={form => { const fixed = fieldText(form, "response_deadline_at"), deadline = fixed ? localToInstant(fixed, occurrence.timezone) : null; if (fixed && !deadline) return null; return { operation: "event.configure", input: { event_id: occurrence.event_id, expected_version: settings.version, rsvp_mode: fieldText(form, "rsvp_mode"), deadline_policy: fieldText(form, "deadline_policy"), change_policy: fieldText(form, "change_policy"), audience: form.getAll("audience").map(String), response_deadline_at: deadline, deadline_offset_minutes: fieldInteger(form, "deadline_offset_minutes") } }; }}><div className="coordination-fields"><label className="form-field"><span>RSVP requirement</span><select name="rsvp_mode" defaultValue={occurrence.rsvp_mode}><option value="not_required">Not required</option><option value="optional">Optional</option><option value="required">Required</option></select></label><label className="form-field"><span>After deadline</span><select name="deadline_policy" defaultValue={settings.deadline_policy}><option value="lock">Lock responses</option><option value="allow_late">Allow and mark late responses</option></select></label><label className="form-field"><span>Material event change</span><select name="change_policy" defaultValue={settings.change_policy}><option value="keep">Keep prior response</option><option value="needs_reconfirmation">Require reconfirmation</option></select></label><CoordinationField name="response_deadline_at" label={`Fixed deadline (${occurrence.timezone}, optional)`} type="datetime-local" value={settings.deadline_offset_minutes === null && settings.response_deadline_at ? localDateTime(settings.response_deadline_at, occurrence.timezone) : ""} /><CoordinationField name="deadline_offset_minutes" label="Or minutes before each occurrence" type="number" min={0} max={44640} value={settings.deadline_offset_minutes} /></div><p className="coordination-hint">Set a fixed deadline or an occurrence offset. An offset follows each recurring event occurrence.</p><fieldset className="coordination-choice-group"><legend>Response audience</legend>{["participants", "staff"].map(audience => <label className="calendar-check" key={audience}><input type="checkbox" name="audience" value={audience} defaultChecked={settings.audience.length ? settings.audience.includes(audience as "participants" | "staff") : true} />{humanize(audience)}</label>)}</fieldset></CoordinationForm></details>;
}
