"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef } from "react";
import type { RegistrationData, RegistrationQuery, RegistrationRow } from "@/lib/registration/contracts";
import { text, number, object, rows, money } from "@/lib/registration/contracts";
import { RegistrationActionForm as Action, Field, Select, Check, Disclosure, Textarea, formText, formNullable, formNumber } from "./action-form";
import { OfferingEditor, OfferingRequirements } from "./offering-editor";
import { RegistrationForm } from "./form-engine";
import { EmergencySection, PrivateDownload, PrivateUpload, SensitivePanel } from "./private-data";
import { FeesSection } from "./fees";
const has=(row:RegistrationRow,op:string)=>Array.isArray(row.operations)&&row.operations.includes(op);
const statuses=["draft","submitted","under_review","approved","denied","waitlisted","withdrawn","canceled","archived"];
const words=(value:string)=>value.replaceAll("_"," ");
const stateKeys=[['status','Registration'],['form_status','Forms'],['waiver_status','Signatures'],['document_status','Documents'],['payment_status','Payment'],['eligibility_status','Eligibility'],['approval_status','Approval'],['roster_status','Team assignment']] as const;
function url(query:RegistrationQuery,patch:Record<string,string|undefined>){const params=new URLSearchParams({view:query.view});for(const [key,value]of[["org",query.organization_id],["offering",query.offering_id],["registration",query.registration_id],["status",query.status],["q",query.query]])if(value)params.set(key!,value);for(const[key,value]of Object.entries(patch)){if(value)params.set(key,value);else params.delete(key);}return "/app/registrations?"+params.toString();}

export function RegistrationConsole({data,query}:{data:RegistrationData;query:RegistrationQuery}){
 const router=useRouter();const detailRef=useRef<HTMLHeadingElement>(null);useEffect(()=>{if(data.detail)detailRef.current?.focus();},[data.detail]);
 const selected=query.offering_id?data.offerings.find(row=>text(row,"id")===query.offering_id):undefined;
 return <div className="registration-console"><div className="registration-heading"><p className="eyebrow">The Boss platform</p><h1>{query.view==="admin"?"Registration workspace":"My registrations"}</h1><p>One family, many programs. Keep forms, signatures, documents, fees and team assignment in view.</p></div>
 <nav className="registration-tabs" aria-label="Registration views"><Link href={url(query,{view:"family",registration:undefined})} aria-current={query.view==="family"?"page":undefined}>My registrations</Link><Link href={url(query,{view:"admin",registration:undefined})} aria-current={query.view==="admin"?"page":undefined}>Staff workspace</Link></nav>
 <form className="registration-filter" action="/app/registrations" method="get"><input type="hidden" name="view" value={query.view}/><Select name="org" label="Organization" value={query.organization_id??""} options={[{value:"",label:"All available organizations"},...data.organizations.map(row=>({value:text(row,"id"),label:text(row,"label")}))]} /><Select name="status" label="Registration status" value={query.status??""} options={[{value:"",label:"All statuses"},...statuses.map(value=>({value,label:words(value)}))]} /><Field name="q" label="Search participant or offering" value={query.query??""} maxLength={100}/><button className="button button-outline" type="submit">Apply filters</button></form>
 {data.unavailable?<div className="registration-notice" role="status">These registration records are unavailable or outside your access. Select an available organization or return to your registrations.</div>:<>
 {data.operations.includes("registration.configure")&&data.organizationId&&<Disclosure title="Registration feature controls"><Action name="Registration features" label="Save feature controls" build={fd=>({operation:"registration.configure",input:{organization_id:data.organizationId!,features:Object.fromEntries(Object.keys(data.features).map(key=>[key,fd.has(key)]))}})}><div className="registration-fields">{Object.entries(data.features).map(([key,enabled])=><Check name={key} label={words(key)} checked={enabled} key={key}/>)}</div></Action></Disclosure>}
 {query.view==="admin"&&data.operations.includes("offering.upsert")&&!selected&&<OfferingEditor data={data}/>}
 {selected&&<section className="registration-selection"><div className="registration-card-heading"><h2>{text(selected,"title")}</h2><Link className="button button-outline" href={url(query,{offering:undefined,registration:undefined})}>All offerings</Link></div><p>{text(selected,"description")}</p>{query.view==="admin"&&has(selected,"offering.upsert")&&<OfferingEditor key={number(selected,"version")} data={data} offering={selected}/>} {query.view==="admin"&&<OfferingRequirements data={data} offering={selected}/>}</section>}
 {!data.detail&&<><section className="registration-section"><h2>{query.view==="admin"?"Registration records":"Family registrations"}</h2>{data.registrations.length===0?<p>No registrations match these filters.</p>:<div className="registration-grid">{data.registrations.map(registration=><article className="registration-card" key={text(registration,"id")}><p className="eyebrow">{text(registration,"participant_label","Participant")}</p><h3>{text(registration,"offering_title")}</h3><p className="registration-helper">Created {text(registration,"created_at")}{text(registration,"household_name")?" · "+text(registration,"household_name"):""}</p><StatusFacts registration={registration}/><Link className="button button-outline" href={url(query,{registration:text(registration,"id"),offering:undefined})}>View registration</Link></article>)}</div>}</section><section className="registration-section"><h2>Available registration offerings</h2>{data.offerings.length===0?<p>No offerings are available in this view. Organization administrators can activate Registration in their module settings.</p>:<div className="registration-grid">{data.offerings.map(offering=><article className="registration-card" key={text(offering,"id")}><div className="registration-card-heading"><h3>{text(offering,"title")}</h3><span className="registration-badge">{words(text(offering,"status"))}</span></div><p>{text(offering,"description")}</p>{text(offering,"event_title")&&<p>Event: {text(offering,"event_title")}</p>}<p className="registration-helper">{text(offering,"registration_type")} · {text(offering,"scope_type")} scope{typeof offering.capacity==="number"?" · Capacity "+number(offering,"capacity"):""}</p><ul>{rows(offering.fees).map(fee=><li key={text(fee,"id")}>{text(fee,"title")} · {money(number(fee,"amount_minor"),text(fee,"currency","USD"))}</li>)}</ul>{query.view==="admin"&&has(offering,"offering.upsert")&&<Link className="button button-outline" href={url(query,{org:text(offering,"organization_id"),offering:text(offering,"id"),registration:undefined})}>Configure offering</Link>}{has(offering,"offering.publish")&&offering.status==="draft"&&<Action name={"Publish "+text(offering,"title")} label="Publish offering" build={()=>({operation:"offering.publish",input:{offering_id:text(offering,"id"),expected_version:number(offering,"version")}})}><p>Open this offering to eligible participants after reviewing its requirements.</p></Action>}{has(offering,"registration.start")&&<StartRegistration data={data} offering={offering} onStarted={id=>router.push(url(query,{org:text(offering,"organization_id"),registration:id,offering:undefined}))}/>}</article>)}</div>}</section></>}
 {data.detail&&<RegistrationDetail key={text(data.detail,"id")+number(data.detail,"version")} data={data} query={query} headingRef={detailRef}/>}
 </>}</div>;
}
function StatusFacts({registration}:{registration:RegistrationRow}){return <dl className="registration-facts">{stateKeys.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{words(text(registration,key,"Not visible"))}</dd></div>)}{typeof registration.waitlist_position==="number"&&<div><dt>Waitlist position</dt><dd>{number(registration,"waitlist_position")}</dd></div>}</dl>;}
function StartRegistration({data,offering,onStarted}:{data:RegistrationData;offering:RegistrationRow;onStarted:(id:string)=>void}){
 const choices=data.participants.filter(row=>row.can_register===true&&row.participant_type===offering.participant_type);
 if(!choices.length)return <p className="registration-helper">No eligible participant with current registration authority is available.</p>;
 return <Disclosure title="Start family registration"><Action name={"Start "+text(offering,"title")} label="Save new draft" onSaved={result=>onStarted(text(result,"resource_id"))} build={fd=>({operation:"registration.start",input:{offering_id:text(offering,"id"),participant_id:formText(fd,"participant_id"),household_id:formNullable(fd,"household_id"),context:{...(formNumber(fd,"grade")===null?{}:{grade:formNumber(fd,"grade")}),travel_team_selected:fd.has("travel_team_selected"),payment_plan_selected:fd.has("payment_plan_selected")}}})}><Select name="participant_id" label="Participant" required options={choices.map(row=>({value:text(row,"id"),label:text(row,"label")}))}/><Select name="household_id" label="Household" options={[{value:"",label:"No shared household selected"},...data.households.map(row=>({value:text(row,"id"),label:text(row,"label")}))]}/><Field name="grade" label="Grade (when required)" type="number" min={0} max={20}/><Check name="travel_team_selected" label="Travel team participation"/>{data.features.payment_plans&&<Check name="payment_plan_selected" label="Request a payment plan"/>}<p className="registration-helper">Existing participant and family information is reused. This draft does not create team membership.</p></Action></Disclosure>;
}
function RegistrationDetail({data,query,headingRef}:{data:RegistrationData;query:RegistrationQuery;headingRef:React.RefObject<HTMLHeadingElement|null>}){
 const reg=data.detail!;const id=text(reg,"id");const participant=object(reg.participant_snapshot);const offering=object(object(reg.offering_snapshot).offering);const age=participantAge(text(participant,"date_of_birth"));const documents=rows(reg.documents);const emergencyTeams=rows(reg.emergency_teams);
 const enhancedForm=(form:RegistrationRow):RegistrationRow=>({...form,document_references:documents.filter(doc=>text(doc,"uploaded_at")).map(doc=>({id:text(doc,"id"),label:text(doc,"title")})),emergency_references:text(reg,"emergency_record_id")?[{id:text(reg,"emergency_record_id"),label:"Saved emergency information"}]:[]});
 const chargeStatus=rows(reg.charges);let payment="Not visible";if(chargeStatus.length){const balances=chargeStatus.map(charge=>object(charge.balance));payment=balances.every(balance=>["paid","waived","canceled"].includes(text(balance,"payment_status")))?"paid":balances.some(balance=>balance.payment_status==="overdue")?"overdue":balances.some(balance=>number(balance,"applied_amount_minor")>0)?"partially_paid":"unpaid";}else if(data.features.fees===false)payment="not_required";
 return <section className="registration-detail"><div className="registration-card-heading"><div><p className="eyebrow">{text(participant,"label",text(participant,"display_name","Participant"))}</p><h2 ref={headingRef} tabIndex={-1}>{text(offering,"title","Registration details")}</h2></div><Link href={url(query,{registration:undefined})} className="button button-outline">Back to registrations</Link></div><StatusFacts registration={{...reg,payment_status:payment}}/><p className="registration-helper">{text(object(reg.family_snapshot),"household_name")&&"Household: "+text(object(reg.family_snapshot),"household_name")+" · "}Submitted {text(reg,"submitted_at","Not yet")} · Canonical participant identity reused{age!==undefined?" · Age "+age:""}</p>{text(offering,"event_id")&&<Link href={`/app/calendar?org=${text(reg,"organization_id")}`}>Open linked event organization calendar</Link>}
 {has(reg,"registration.save")&&<Disclosure title="Save draft details"><Action name="Save draft" label="Save draft" build={fd=>({operation:"registration.save",input:{registration_id:id,expected_version:number(reg,"version"),context:{...(formNumber(fd,"grade")===null?{}:{grade:formNumber(fd,"grade")}),travel_team_selected:fd.has("travel_team_selected"),payment_plan_selected:fd.has("payment_plan_selected")}}})}><Field name="grade" label="Grade" type="number" min={0} max={20} value={typeof object(reg.context).grade==="number"?number(object(reg.context),"grade"):""}/><Check name="travel_team_selected" label="Travel team participation" checked={object(reg.context).travel_team_selected===true}/>{data.features.payment_plans&&<Check name="payment_plan_selected" label="Payment plan requested" checked={object(reg.context).payment_plan_selected===true}/>}</Action></Disclosure>}
 {rows(reg.forms).length>0&&<section className="registration-section"><h3>Forms</h3>{rows(reg.forms).map(form=><article className="registration-card" key={text(form,"form_version_id")}><h4>{text(form,"title")}</h4><p>{words(text(form,"status"))} · {form.required?"required":"optional"}</p>{form.needs_sensitive_access===true?<>{has(form,"form.access")?<SensitivePanel command={{operation:"form.access",input:{registration_id:id,form_version_id:text(form,"form_version_id")}}} form={enhancedForm(form)} participantAge={age} context={object(reg.context)}/>:<p>Restricted answers require document permission.</p>}</>:<RegistrationForm registrationId={id} form={enhancedForm(form)} participantAge={age} context={object(reg.context)}/>}</article>)}</section>}
 {rows(reg.waivers).length>0&&<section className="registration-section"><h3>Waivers and signatures</h3>{rows(reg.waivers).map(waiver=><article className="registration-card" key={text(waiver,"waiver_version_id")}><h4>{text(waiver,"title")} · version {number(waiver,"version_number")}</h4><p className="registration-long-copy">{text(waiver,"body")}</p>{rows(waiver.signatures).length?rows(waiver.signatures).map(signature=><p key={text(signature,"id")||text(signature,"signed_at")}>Signed {text(signature,"signed_at")} {text(signature,"signer_name")&&"by "+text(signature,"signer_name")} · Accepted version {number(object(signature.version_snapshot),"version_number",number(waiver,"version_number"))}</p>):has(reg,"waiver.sign")?<Action name={"Sign "+text(waiver,"title")} label="Accept and sign waiver" build={fd=>({operation:"waiver.sign",input:{registration_id:id,waiver_version_id:text(waiver,"waiver_version_id"),name:formText(fd,"name"),consent:fd.has("consent")}})}><Field name="name" label="Typed signer name" required/><label className="registration-check"><input name="consent" type="checkbox" required/>I have read this version and explicitly consent to sign it electronically.</label></Action>:<p>Signature pending from an authorized signer.</p>}</article>)}</section>}
 {documents.length>0&&<section className="registration-section"><h3>Private documents</h3>{documents.map(doc=><article className="registration-card" key={text(doc,"id")}><h4>{text(doc,"title")}</h4><p>{words(text(doc,"status"))} · {doc.required?"required":"optional"}{text(doc,"expires_on")?" · Expires "+text(doc,"expires_on"):""}{text(doc,"renewal_due_on")?" · Renew by "+text(doc,"renewal_due_on"):""}</p>{text(doc,"review_reason")&&<p>Review: {text(doc,"review_reason")}</p>}{has(doc,"document.intent")&&<PrivateUpload document={doc}/>} {has(doc,"document.access")&&<PrivateDownload document={doc} teamId={doc.access_purpose==="emergency"&&emergencyTeams.length?text(emergencyTeams[0],"id"):undefined}/>} {has(doc,"document.review")&&<Disclosure title="Review document"><Action name={"Review "+text(doc,"title")} label="Record document review" build={fd=>({operation:"document.review",input:{document_id:text(doc,"id"),expected_version:number(doc,"version"),status:formText(fd,"status"),reason:formText(fd,"reason"),expires_on:formNullable(fd,"expires_on"),renewal_due_on:formNullable(fd,"renewal_due_on")}})}><Select name="status" label="Review status" options={["under_review","approved","rejected","waived"].map(value=>({value,label:words(value)}))}/><Textarea name="reason" label="Review reason" required maxLength={2000}/><div className="registration-fields"><Field name="expires_on" label="Expiration date" type="date" value={text(doc,"expires_on")}/><Field name="renewal_due_on" label="Renewal due date" type="date" value={text(doc,"renewal_due_on")}/></div></Action></Disclosure>}</article>)}</section>}
 {(has(reg,"emergency.access")||has(reg,"emergency.save"))&&<EmergencySection registration={reg}/>}<FeesSection registration={reg} data={data}/>
 {has(reg,"registration.submit")&&<section className="registration-card"><h3>Submit registration</h3><p>Complete required forms and signatures first. Submission reserves capacity or joins the waitlist. It creates any required fee charges and leaves documents, eligibility, payment and roster assignment separate.</p><Action name="Submit registration" label="Submit registration" build={fd=>({operation:"registration.submit",input:{registration_id:id,expected_version:number(reg,"version"),...(formText(fd,"coupon_code")?{coupon_code:formText(fd,"coupon_code")}:{})}})}>{data.features.coupons&&<Field name="coupon_code" label="Coupon code (optional)" maxLength={40}/>}</Action></section>}
 {(has(reg,"registration.decision")||has(reg,"registration.eligibility")||has(reg,"registration.assign_team"))&&<StaffDecisions data={data} registration={reg}/>}
 {has(reg,"registration.withdraw")&&reg.roster_status!=="assigned"&&<Disclosure title="Withdraw registration"><Action name="Withdraw registration" label="Withdraw registration" build={fd=>({operation:"registration.withdraw",input:{registration_id:id,expected_version:number(reg,"version"),reason:formNullable(fd,"reason")}})}><Textarea name="reason" label="Withdrawal reason" maxLength={2000}/></Action></Disclosure>}
 </section>;
}
function participantAge(value:string){if(!value)return undefined;const date=new Date(value);if(Number.isNaN(date.valueOf()))return undefined;const now=new Date();return now.getFullYear()-date.getUTCFullYear()-(now.getMonth()<date.getUTCMonth()||now.getMonth()===date.getUTCMonth()&&now.getDate()<date.getUTCDate()?1:0);}
function StaffDecisions({data,registration:reg}:{data:RegistrationData;registration:RegistrationRow}){const base={registration_id:text(reg,"id"),expected_version:number(reg,"version")};return <section className="registration-card"><h3>Staff review and team assignment</h3>{has(reg,"registration.decision")&&<Action name="Registration decision" label="Record registration decision" build={fd=>({operation:"registration.decision",input:{...base,decision:formText(fd,"decision"),reason:formNullable(fd,"reason")}})}><Select name="decision" label="Decision" options={["under_review","approve","deny","waitlist","promote","cancel","archive"].map(value=>({value,label:words(value)}))}/><Textarea name="reason" label="Decision reason" maxLength={2000}/></Action>}{has(reg,"registration.eligibility")&&<Action name="Eligibility review" label="Record eligibility decision" build={fd=>({operation:"registration.eligibility",input:{...base,status:formText(fd,"status"),reason:formText(fd,"reason")}})}><Select name="status" label="Eligibility status" options={["pending","eligible","ineligible","waived"].map(value=>({value,label:value}))}/><Textarea name="reason" label="Eligibility reason" required maxLength={2000}/></Action>}{has(reg,"registration.assign_team")&&reg.roster_status!=="assigned"&&<Action name="Assign participant to team" label="Assign team" build={fd=>({operation:"registration.assign_team",input:{...base,team_id:formText(fd,"team_id")}})}><Select name="team_id" label="Team" required options={[{value:"",label:"Select authorized team"},...data.teams.map(team=>({value:text(team,"id"),label:text(team,"label")}))]}/><p className="registration-helper">The server checks this team's roster authority and the offering's configured prerequisites.</p></Action>}{has(reg,"registration.remove_team")&&reg.roster_status==="assigned"&&<Action name="Remove assigned team" label="Remove assignment" build={fd=>({operation:"registration.remove_team",input:{...base,reason:formText(fd,"reason")}})}><Textarea name="reason" label="Removal reason" required maxLength={2000}/></Action>}</section>;}
