"use client";
import { useState } from "react";
import type { RegistrationData, RegistrationRow } from "@/lib/registration/contracts";
import { object, rows, text, number, money } from "@/lib/registration/contracts";
import { RegistrationActionForm as Action, Field, Textarea, Select, Disclosure, formText, formNullable, formNumber } from "./action-form";
const has=(row:RegistrationRow,op:string)=>Array.isArray(row.operations)&&row.operations.includes(op);

export function FeesSection({ registration, data }: { registration: RegistrationRow; data: RegistrationData }) {
  const charges=rows(registration.charges);const org=text(registration,"organization_id");const participant=object(registration.participant_snapshot);
  const submitter = text(registration,"submitted_by_person_id",text(object(registration.family_snapshot),"submitter_person_id"));
  const payerOptions = [...(submitter ? [{value:submitter,label:text(registration,"submitted_by_name",text(object(registration.family_snapshot),"submitter_name","Submitting person"))}] : []), ...(text(participant,"person_id") && text(participant,"person_id") !== submitter ? [{value:text(participant,"person_id"),label:text(participant,"label",text(participant,"display_name","Participant"))}] : [])];
  return <section className="registration-card"><h3>Fees and payment applications</h3>{charges.length===0&&<p>No visible charges have been created for this registration.</p>}{charges.map(charge=>{const balance=object(charge.balance);const currency=text(balance,"currency","USD");return <article className="registration-charge" key={text(charge,"id")}><div className="registration-card-heading"><h4>{text(charge,"title")}</h4><span className="registration-badge">{text(balance,"payment_status").replaceAll("_"," ")}</span></div><dl className="registration-facts"><div><dt>Original charge</dt><dd>{money(number(balance,"original_amount_minor"),currency)}</dd></div><div><dt>Adjustments</dt><dd>{money(number(balance,"adjustment_amount_minor"),currency)}</dd></div><div><dt>Applied payments</dt><dd>{money(number(balance,"applied_amount_minor"),currency)}</dd></div><div><dt>Balance due</dt><dd>{money(number(balance,"balance_due_minor"),currency)}</dd></div><div><dt>Due date</dt><dd>{text(charge,"due_on","Not scheduled")}</dd></div></dl><ul>{rows(charge.allocations).map(allocation=><li key={text(allocation,"id")}>{text(allocation,"method")} · {money(number(allocation,"amount_minor"),currency)} · {text(allocation,"received_at").slice(0,10)} {text(allocation,"reference")}</li>)}{rows(charge.adjustments).map(adjustment=><li key={text(adjustment,"id")}>{text(adjustment,"adjustment_type")} · {money(number(adjustment,"amount_minor"),currency)} · {text(adjustment,"reason")}</li>)}</ul>
    {has(registration,"payment.record_offline")&&data.features.offline_payments&&number(balance,"balance_due_minor")>0&&<Disclosure title="Record offline partial payment"><Action name={"Offline payment: "+text(charge,"title")} label="Record offline payment" build={fd=>({operation:"payment.record_offline",input:{organization_id:org,method:formText(fd,"method"),amount_minor:formNumber(fd,"amount_minor"),currency,payer_person_id:formText(fd,"payer_person_id"),received_at:new Date(formText(fd,"received_at")).toISOString(),reference:formNullable(fd,"reference"),note:formNullable(fd,"note"),allocations:[{charge_id:text(charge,"id"),amount_minor:formNumber(fd,"amount_minor")}]}})}><div className="registration-fields"><Select name="method" label="Offline method" options={[{value:"cash",label:"Cash"},{value:"check",label:"Check (recorded offline)"}]} /><Field name="amount_minor" label="Received amount in cents" type="number" min={1} max={number(balance,"balance_due_minor")} required /><Select name="payer_person_id" label="Payer" options={payerOptions} required /><Field name="received_at" label="Received at (local time)" type="datetime-local" required /><Field name="reference" label="Reference or check number" /></div><Textarea name="note" label="Payment note" /><p className="registration-helper">This records an actual cash or check receipt and applies it to this charge. The change is audited.</p></Action></Disclosure>}
    {has(registration,"charge.adjust")&&<Disclosure title="Apply authorized charge adjustment"><Action name="Charge adjustment" label="Record adjustment" build={fd=>({operation:"charge.adjust",input:{charge_id:text(charge,"id"),amount_minor:formNumber(fd,"amount_minor"),adjustment_type:formText(fd,"adjustment_type"),reason:formText(fd,"reason")}})}><div className="registration-fields"><Field name="amount_minor" label="Adjustment in cents (negative reduces charge)" type="number" required /><Select name="adjustment_type" label="Adjustment type" options={["discount","scholarship","credit","surcharge"].map(value=>({value,label:value}))} /></div><Textarea name="reason" label="Reason" required maxLength={2000} /></Action></Disclosure>}
    {rows(charge.payment_plans).map(plan=><div key={text(plan,"id")}><h4>{text(plan,"title")} · {text(plan,"status")}</h4><ol>{rows(plan.installments).map(installment=><li key={number(installment,"sequence_number")}>{text(installment,"due_on")} · {money(number(installment,"amount_minor"),currency)}</li>)}</ol></div>)}
    {has(registration,"payment_plan.create")&&data.features.payment_plans&&<PlanEditor charge={charge} />}
    {has(registration,"payment_plan.cancel")&&rows(charge.payment_plans).some(plan=>plan.status==="active")&&<ReasonAction operation="payment_plan.cancel" charge={charge} label="Cancel payment plan" />}
    {has(registration,"charge.cancel")&&number(balance,"applied_amount_minor")===0&&charge.status==="active"&&<ReasonAction operation="charge.cancel" charge={charge} label="Cancel unpaid charge" />}
  </article>;})}{has(registration,"charge.create")&&<Disclosure title="Add charge"><Action name="Add charge" label="Create charge" build={fd=>({operation:"charge.create",input:{registration_id:text(registration,"id"),title:formText(fd,"title"),charge_type:formText(fd,"charge_type"),amount_minor:formNumber(fd,"amount_minor"),currency:formText(fd,"currency"),due_on:formNullable(fd,"due_on")}})}><div className="registration-fields"><Field name="title" label="Charge title" required /><Field name="charge_type" label="Charge type" value="registration" required /><Field name="amount_minor" label="Original amount in cents" type="number" min={0} required /><Field name="currency" label="Currency" value="USD" required maxLength={3} /><Field name="due_on" label="Due date" type="date" /></div></Action></Disclosure>}<p className="registration-helper">Payment applications change the balance independently of documents, approval, eligibility and team assignment.</p></section>;
}
function ReasonAction({operation,charge,label}:{operation:"payment_plan.cancel"|"charge.cancel";charge:RegistrationRow;label:string}){return <Disclosure title={label}><Action name={label} label={label} build={fd=>({operation,input:{charge_id:text(charge,"id"),reason:formText(fd,"reason")}})}><Textarea name="reason" label="Reason" required maxLength={2000}/></Action></Disclosure>;}
function PlanEditor({charge}:{charge:RegistrationRow}){
  const [count,setCount]=useState(2);return <Disclosure title="Create installment plan"><Action name="Payment plan" label="Create payment plan" build={fd=>({operation:"payment_plan.create",input:{charge_id:text(charge,"id"),title:formText(fd,"title"),installments:Array.from({length:count},(_,i)=>({amount_minor:formNumber(fd,"amount_"+i),due_on:formText(fd,"due_"+i)}))}})}><Field name="title" label="Plan title" required /><label className="form-field"><span>Installment count</span><select value={count} onChange={e=>setCount(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label>{Array.from({length:count},(_,i)=><fieldset className="registration-group" key={i}><legend>Installment {i+1}</legend><div className="registration-fields"><Field name={"amount_"+i} label="Amount in cents" type="number" min={1} required /><Field name={"due_"+i} label="Due date" type="date" required /></div></fieldset>)}<p className="registration-helper">Installments must total the adjusted charge, with due dates in order. This creates a schedule for payment; it does not collect money automatically.</p></Action></Disclosure>;
}
