-- Private disposable fixture. Never a hosted acceptance script.
\ir ../phase5d/fixture.sql
update public.organization_modules set configuration=configuration||'{"baseball_live_scoring":true,"baseball_stats":true,"baseball_play_by_play":true,"baseball_lineups":true,"softball_live_scoring":true,"softball_stats":true,"softball_play_by_play":true,"softball_lineups":true}'where organization_id=pg_temp.f('org')and module_id=(select id from public.modules where key='sports');
create function pg_temp.dd_config(sport text default'baseball')returns jsonb language sql immutable as $$select jsonb_build_object('version','diamond-rules-v1','sport',sport,'home_side','opponent','regulation_innings',1,'lineup_size',4,'continuous_batting',true,'allow_reentry',true,'stealing',true,'dropped_third_strike','first_unoccupied_or_two_outs','foul_bunt_third_strike',true,'run_cap',null,'tiebreak_from',null,'dh','none','dp_flex','none','courtesy_runner','none','mercy_margin',null,'time_limit_minutes',null,'pitch_limit',null,'era_innings',case sport when'baseball'then 9 else 7 end)$$;
create function pg_temp.dd_sport(label text)returns text language sql security definer set search_path=''as $$select sport_key from public.games where id=pg_temp.ff_game(label)$$;
create function pg_temp.dd_op(op text,label text,extras jsonb default'{}',request_label text default null)returns jsonb language plpgsql as $$declare sport text;begin
 sport:=pg_temp.dd_sport(label);
 return pg_temp.game_op(op,label,jsonb_build_object('sport_key',sport)||extras,request_label);end$$;
create function pg_temp.dd_profile(label text,side text,preset text default'essential',enabled jsonb default'[]')returns jsonb language plpgsql as $$declare sport text;result jsonb;begin
 sport:=pg_temp.dd_sport(label);
 result:=public.boss_games_mutate(gen_random_uuid(),pg_temp.cmd('tracking.profile.set',jsonb_build_object('sport_key',sport,'scope_type','game','organization_id',pg_temp.f('org'),'game_id',pg_temp.ff_game(label),'side',side,'expected_profile_version',pg_temp.dd_profile_version(label,side),'expected_game_version',(select version from pg_temp.phase5a_games where phase5a_games.label=dd_profile.label),'preset',preset,'enabled',enabled,'reason','Synthetic Diamond profile')));
 update pg_temp.phase5a_games set version=(result->>'version')::bigint where phase5a_games.label=dd_profile.label;return result;end$$;
create function pg_temp.dd_profile_version(label text,side text)returns bigint language sql security definer set search_path=''as $$select coalesce((select version from public.game_tracking_profiles where game_id=pg_temp.ff_game(label)and game_tracking_profiles.side=dd_profile_version.side),0)$$;
create function pg_temp.dd_create(label text,sport text default'baseball',preset text default'essential',innings int default 1)returns void language plpgsql as $$declare sd text;begin
 perform pg_temp.ff_link(label,'internal','falcons',sport);perform pg_temp.dd_profile(label,'primary',preset);perform pg_temp.dd_profile(label,'opponent',preset);
 perform pg_temp.dd_op('diamond.configure',label,jsonb_build_object('configuration',jsonb_set(pg_temp.dd_config(sport),'{regulation_innings}',to_jsonb(innings))));
 foreach sd in array array['primary','opponent']loop
 perform pg_temp.dd_op('diamond.lineup.set',label,jsonb_build_object('payload',jsonb_build_object('kind','lineup_set','side',sd,'order',(select jsonb_agg(pg_temp.ff_roster(label,sd,i)order by i)from generate_series(1,4)i),'positions',jsonb_build_object('1',pg_temp.ff_roster(label,sd,4)),'pitcher',pg_temp.ff_roster(label,sd,4))));end loop;
 perform pg_temp.game_op('game.start',label);perform pg_temp.dd_op('diamond.half.start',label,'{"payload":{"kind":"half_start"}}');end$$;
create function pg_temp.dd_state(label text)returns jsonb language sql security definer set search_path=''as $$select state from public.game_diamond_states where game_id=pg_temp.ff_game(label)$$;
create function pg_temp.dd_pa(label text,key_label text)returns jsonb language plpgsql as $$declare s jsonb:=pg_temp.dd_state(label);begin
 return pg_temp.dd_op('diamond.pa.start',label,jsonb_build_object('payload',jsonb_build_object('kind','pa_start','key',pg_temp.ff_id(key_label),'batter',s->'orders'->(s->>'batting_side')->((s->'cursors'->>(s->>'batting_side'))::int))));end$$;
create function pg_temp.dd_move(f int,t int,cause text default'hit',force boolean default false,before_first boolean default false)returns jsonb language sql immutable as $$select jsonb_build_object('from',f,'to',t,'out',t is null,'cause',cause,'force',force,'batter_before_first',before_first)$$;
create function pg_temp.dd_play(label text,result text,moves jsonb)returns jsonb language sql as $$select pg_temp.dd_op('diamond.play.add',label,jsonb_build_object('payload',jsonb_build_object('kind','play','result',result,'moves',moves)))$$;
create function pg_temp.dd_stats(label text,side text,n int default 0)returns jsonb language sql security definer set search_path=''as $$select stats from boss_private.diamond_totals(pg_temp.ff_game(label))t where t.side=dd_stats.side and t.roster_id is not distinct from case n when 0 then null::uuid else pg_temp.ff_roster(label,side,n)end$$;
do $$declare f record;begin for f in select p.oid::regprocedure sig from pg_proc p where p.pronamespace=pg_my_temp_schema()and p.proname like'dd_%'loop execute format('revoke all on function %s from public',f.sig);execute format('grant execute on function %s to authenticated,anon',f.sig);end loop;end$$;
