"use client";
import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import { minorAmount, money, type PublicFundraising, type Tile } from "@/lib/fundraising/contracts";
import type { Json } from "@/lib/supabase/database.types";
import { PublicDiscountOptions } from "@/components/discounts/public-options";
import type { DiscountCatalogItem } from "@/lib/discounts/contracts";
function capability() { return Array.from(crypto.getRandomValues(new Uint8Array(32)), v => v.toString(16).padStart(2, "0")).join(""); }
export function SupporterBoard({ data, path, source = "participant_share", discounts = [] }: { data: PublicFundraising; path: string; source?: string; discounts?: DiscountCatalogItem[] }) {
 const router = useRouter(), [selected, setSelected] = useState<Tile | null>(null), [cap, setCap] = useState(""), [expires, setExpires] = useState(""), [remaining, setRemaining] = useState(0), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [intentCreated, setIntentCreated] = useState(false);
 const retry = useRef<{ action: string; request_id: string; input: Record<string, Json> } | null>(null);
 const [trialProof, setTrialProof] = useState("");
 const currency = data.campaign.currency;
 useEffect(() => { if (!expires) return; const tick = () => { const seconds = Math.max(0, Math.ceil((Date.parse(expires) - Date.now()) / 1000)); setRemaining(seconds); if (!seconds) { setExpires(""); setSelected(null); setCap(""); setIntentCreated(false); retry.current = null; setMessage("The unpaid reservation expired. Choose an available amount again."); router.refresh(); } }; tick(); const timer = setInterval(tick, 1000); return () => clearInterval(timer); }, [expires, router]);
 async function send(action: string, input: Record<string, Json>) { setBusy(true); setMessage("Saving…"); const serialized = JSON.stringify(input); const prior = retry.current; const command = prior && prior.action === action && JSON.stringify(prior.input) === serialized ? prior : { action, request_id: crypto.randomUUID(), input }; retry.current = command; try { const response = await fetch(`/fundraise/${path}/support`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(command) }), body = await response.json(); if (!response.ok) { if (response.status !== 503) retry.current = null; setMessage(body.error ?? "Support could not be confirmed."); return null; } retry.current = null; return body; } catch { setMessage("The request could not be confirmed. Retry the same choice safely."); return null; } finally { setBusy(false); } }
 async function reserve(tile: Tile) { const fresh = retry.current?.action === "reserve" && retry.current.input.ordinal === tile.ordinal ? String(retry.current.input.capability) : capability(), result = await send("reserve", { path, ordinal: tile.ordinal, capability: fresh }); if (result) { setSelected(tile); setCap(fresh); setExpires(result.expires_at); setIntentCreated(false); setMessage("Amount reserved. Complete your supporter details below."); router.refresh(); } }
 async function cancel() { const result = await send("release", { path, capability: cap }); if (result) { setSelected(null); setCap(""); setExpires(""); setIntentCreated(false); setMessage("Unpaid reservation released."); router.refresh(); } }
 async function intent(form: FormData) { const direct = !selected, amount = direct ? minorAmount(String(form.get("amount")), currency) : selected.amount_minor; if (!amount) { setMessage("Enter a valid positive amount."); return; } const supportCapability = cap || (retry.current?.action === "intent" ? String(retry.current.input.capability) : capability()); setCap(supportCapability); const input: Record<string, Json> = { path, capability: supportCapability, display_name: String(form.get("name") ?? ""), anonymous: form.get("anonymous") === "on", fee_cover: form.get("fee_cover") === "on", source: source === "qr" ? "qr" : "participant_share", ...(direct ? { amount_minor: amount } : { ordinal: selected.ordinal }) }; for (const key of ["email", "mobile"]) { const value = String(form.get(key) ?? "").trim(); if (value) input[key] = value; } const months = Number(form.get("months")); if (months) input.months = months;
 if (trialProof) input.trial_capability = trialProof;
 const result = await send("intent", input); if (result) { setTrialProof(""); setCap(supportCapability); setExpires(result.expires_at); setIntentCreated(true); setMessage("Support intent recorded. No payment was taken. Payment processing is not available yet."); router.refresh(); } }
 return <section className="money-board" aria-label="Digital Money Board"><h2>{data.board?.title ?? "Support this campaign"}</h2>{data.campaign.may_earn_boss_bucks && <p>This fundraiser may earn Boss Bucks from verified support. Organization restrictions apply.</p>}{data.board && <><p>{data.board.tile_count} unique amounts. If all claimed: <strong>{money(data.board.all_claimed_minor, currency)}</strong>.</p><div className="fundraising-progress"><strong>{money(data.board.raised_minor, currency)} confirmed on this board</strong><span>Board goal {money(data.board.goal_minor, currency)}</span><progress max={data.board.goal_minor} value={Math.min(data.board.goal_minor, data.board.raised_minor)} aria-label="Confirmed Money Board progress" /></div><p>{data.board.claimed_count} claimed. Unpaid reservations do not count as raised.</p><div className="money-board-tiles">{data.board.tiles.map(tile => <button key={tile.ordinal} type="button" disabled={busy || !!selected || tile.state !== "available"} onClick={() => reserve(tile)} className={`money-tile tile-${tile.state}`} aria-label={`${money(tile.amount_minor, currency)}, ${tile.state.replaceAll("_", " ")}`}><strong>{money(tile.amount_minor, currency)}</strong><span>{tile.state.replaceAll("_", " ")}</span></button>)}</div>{data.board.tiles.length === 100 && data.board.tiles.at(-1)!.ordinal < data.board.tile_count && <a className="button button-outline" href={`?after=${data.board.tiles.at(-1)!.ordinal}`}>More amounts below</a>}</>}
 {selected && <div className="form-notice"><strong>Selected: {money(selected.amount_minor, currency)}</strong><p>Reservation remaining: {Math.floor(remaining / 60)}:{String(remaining % 60).padStart(2, "0")}</p><button type="button" disabled={busy} onClick={cancel} className="button button-outline">Release unpaid amount</button></div>}
 {(selected || data.campaign.direct_support) && !intentCreated && <form action={intent} className="fundraising-form"><h3>Supporter details</h3>{!selected && <label>Support amount ({currency})<input name="amount" inputMode="decimal" required placeholder="25.00" /></label>}<label>Display name<input name="name" required maxLength={100} autoComplete="name" /></label><label>Email (optional)<input name="email" type="email" maxLength={254} autoComplete="email" /></label><label>Mobile (optional)<input name="mobile" type="tel" maxLength={32} autoComplete="tel" /></label>{data.campaign.allow_anonymous && <label className="fundraising-check"><input name="anonymous" type="checkbox" /> Show my support as Anonymous</label>}{data.campaign.allow_recurring && <label>Monthly commitment<select name="months" defaultValue="0"><option value="0">One time</option>{Array.from({ length: 7 }, (_, n) => n + 6).map(month => <option key={month} value={month}>{month} months, selected amount each month</option>)}</select></label>}{data.campaign.allow_fee_cover && <label className="fundraising-check"><input name="fee_cover" type="checkbox" /> I prefer to cover applicable future fees. No fee is quoted or charged now.</label>}<p className="form-notice">Payment processing is not available yet. This saves your support intent only. No card or bank details are collected and no automatic payment will occur.</p><button className="button button-primary" disabled={busy}>Save support intent</button></form>}
 <p role="status" aria-live="polite">{message}</p><PublicDiscountOptions catalog={discounts} path={path} onTrial={setTrialProof} supportCapability={intentCreated ? cap : undefined} /></section>;
}
