import { footballOperations, type Football } from "../football/contracts";
import { soccerOperations, type Soccer } from "../soccer/contracts";
import { basketballOperations, type Basketball } from "../basketball/contracts";
import type { Json } from "../supabase/database.types";
import type { Choice } from "../coordination/input";

export const gameStatuses = ["scheduled", "pregame", "live", "paused", "delayed", "suspended", "final", "canceled", "postponed", "abandoned"] as const;
export const gameOperations = ["games.configure", "game.create", "game.roster.snapshot", "game.operator.assign", "game.operator.end", "game.start", "game.transition", "game.score.set", "game.score.reverse", "game.finalize", "game.reopen", "game.publish", ...basketballOperations, ...soccerOperations, ...footballOperations] as const;
export const gameFeatureKeys = ["game_center", "game_operations", "public_game_center", "team_game_management", "head_coach_game_management", "basketball_live_scoring", "basketball_stats", "basketball_play_by_play", "basketball_lineups", "soccer_live_scoring", "soccer_stats", "soccer_play_by_play", "soccer_lineups", "football_live_scoring", "football_stats", "football_play_by_play", "football_lineups"] as const;
export type GameStatus = typeof gameStatuses[number];
export type GameCommand = { operation: typeof gameOperations[number]; input: Record<string, Json | undefined> };
export type GameQuery = { view: "all" | "family"; from: string; to: string; organization_id?: string; game_id?: string; team_id?: string; unit_id?: string; season_id?: string; status?: GameStatus; child_person_id?: string };
export type GameSide = { team_id: string | null; label: string; score: number; final_score: number | null };
export type GameRoster = { id: string; person_id: string; participant_id: string; team_id: string; display_name: string; jersey_number: string | null; position_label: string | null; active: boolean; captain: boolean; starter: boolean; availability: string; checkin_state: string | null; revision: number };
export type GameOperator = { id: string; person_id: string; display_name: string; role_assignment_id: string; team_id: string | null; function_key: "game_administrator" | "scorekeeper"; status: string; ends_at: string | null };
export type GameHistory = { id: string; sequence: number; version: number; operation: string; created_at: string; correction_of: string | null; summary: string };
export type GameFinalization = { id: string; epoch: number; primary_score: number; opponent_score: number; roster_revision: number; winner_side: "primary" | "opponent" | null; tied: boolean; created_at: string };
export type GameCapabilities = { manage: boolean; roster_snapshot: boolean; operate: boolean; resume: boolean; start: boolean; finalize: boolean; correct: boolean; publish: boolean; view_roster: boolean };
export type Game = { id: string; organization_id: string; event_id: string; occurrence_key: string; occurrence_mode: "single" | "recurring"; title: string; sport_key: string; sport_label: string; primary: GameSide; opponent: GameSide; home_away: "home" | "away" | "neutral"; competition_type: "standard" | "tournament"; start_at: string; end_at: string; timezone: string; venue_label: string | null; event_status: string; status: GameStatus; visibility: string; publication_state: string; version: number; roster_revision: number; finalization_count: number; reopened: boolean; engine_locked: boolean; basketball: Basketball | null; soccer: Soccer | null; football: Football | null; capabilities: GameCapabilities; roster: GameRoster[]; operators: GameOperator[]; history: GameHistory[]; finalizations: GameFinalization[] };
export type GameCandidate = { event_id: string; event_version: number; occurrence_key: string; title: string; start_at: string; end_at: string; home_away: "home" | "away" | "neutral"; opponent_label: string; teams: Choice[] };
export type OperatorCandidate = { person_id: string; display_name: string; role_assignment_id: string; team_id: string | null; functions: ("game_administrator" | "scorekeeper")[] };
export type GameData = { navigation_available: boolean; organization_id: string | null; configuration_version: number; view: GameQuery["view"]; range: { from: string; to: string }; features: Partial<Record<typeof gameFeatureKeys[number], boolean>>; capabilities: { configure: boolean; create: boolean }; organizations: Choice[]; teams: Choice[]; units: Choice[]; seasons: Choice[]; sports: { key: string; label: string }[]; games: Game[]; create_candidates: GameCandidate[]; operator_candidates: OperatorCandidate[]; more: boolean; unavailable?: boolean; restricted?: boolean };
export type GameResult = { replayed: boolean; game_id: string | null; organization_id?: string; version: number; message: string };
export type CalendarGameLink = Pick<Game, "id" | "organization_id" | "event_id" | "occurrence_key" | "occurrence_mode" | "status"> & { primary: Pick<GameSide, "label" | "score" | "final_score">; opponent: Pick<GameSide, "label" | "score" | "final_score"> };
export function emptyGames(query: GameQuery, unavailable = false, restricted = false): GameData { return { navigation_available: false, organization_id: query.organization_id ?? null, configuration_version: 0, view: query.view, range: { from: query.from, to: query.to }, features: {}, capabilities: { configure: false, create: false }, organizations: [], teams: [], units: [], seasons: [], sports: [], games: [], create_candidates: [], operator_candidates: [], more: false, unavailable, restricted }; }
