'use client';
import {useState,useRef} from 'react';
import Link from 'next/link';
import BossPlusIcon from '@/components/BossPlusIcon';
import s from './preview.module.css';
const samples=[['sonic','Everyday favorites'],['dining','Dining out'],['restaurants','Restaurant extras'],['services','Everyday services']];
export default function FundraiserPreview({player=false}:{player?:boolean}){
 const swipeStart=useRef<number|null>(null); const [slide,setSlide]=useState(0);const [message,setMessage]=useState('');
 const demo=(action:string)=>setMessage(`${action} selected. This is a design preview; no payment or signup is submitted.`);
 return <div className={s.page}>
 <div className={s.review}>DESIGN PREVIEW · Sample team, player and fundraising figures · No live transactions</div>
 <header className={s.header}><Link href="/merchants" className={s.brand}><BossPlusIcon/> <span>THE BOSS<small>FUNDRAISING</small></span></Link><nav aria-label="Preview pages"><Link aria-current={!player?'page':undefined} href="/previews/cardinals">Team page</Link><Link aria-current={player?'page':undefined} href="/previews/cardinals/player">Player page</Link></nav></header>
 <main>
 <section className={s.hero}><img className={s.teamPhoto} src="/images/approved/cardinals-team-preview.png" alt="Illustrative Cardinals baseball teammates in red uniforms"/><div className={s.heroShade}/><div className={s.heroInner}><p className={s.eyebrow}>CLINTON CARDINALS · BASEBALL</p>{player&&<div className={s.playerPortrait}><img src="/images/approved/cardinals-team-preview.png" alt="Illustrative player portrait"/></div>}<h1>{player?<>Back the player.<br/>Build the <em>dream.</em></>:<>One team.<br/>A whole community<br/><em>behind us.</em></>}</h1><p className={s.subtitle}>{player?'Ethan Carter · #12':'Clinton Cardinals'}</p><p>{player?'Help Ethan and his teammates take the next step. Every show of support is part of something bigger.':'Help our Cardinals step onto the field ready for what’s next. Support our season and discover more ways to give.'}</p><a className={s.primary} href="#support">{player?'Support Ethan':'Support the Cardinals'} <span>↗</span></a></div></section>
 <section className={s.progressCard} aria-label="Team fundraising progress"><div className={s.progressTop}><span className={s.live}>FUNDRAISER STILL IN PROGRESS</span><span>DAY <b>5</b> OF FUNDRAISER</span></div><div className={s.totals}><div><strong>$7,840</strong><span>raised toward our $15,000 goal</span></div><b>52.3%<small>OF OUR GOAL</small></b></div><div className={s.track} role="progressbar" aria-label="Active team fundraiser" aria-valuemin={0} aria-valuemax={15000} aria-valuenow={7840}><span style={{width:'52.2667%'}}/></div><div className={s.progressBottom}><span>$7,160 to go. Let’s get there together.</span><span>{player?'TEAM TOTAL · ETHAN’S SUPPORT COUNTS HERE':'EVERY SHOW OF SUPPORT MATTERS'}</span></div></section>
 <section id="support" className={s.support}><div className={s.sectionTitle}><p className={s.eyebrow}>CHOOSE YOUR WAY TO SUPPORT</p><h2>{player?'Show up for Ethan.':'Show up for the Cardinals.'}<br/><em>Get something great in return.</em></h2><p>Support {player?'Ethan and the team':'our team'} through Boss Bucks. Choose a year of savings or explore the digital discounts with a free trial.</p></div><div className={s.options}>
 <article className={s.purchase}><div className={s.cardCopy}><span className={s.label}>SAVE ALL YEAR</span><h3>Boss Bucks<br/>Digital Discounts</h3><p className={s.price}>$25 <span>/ one year</span></p><p>A one-year digital discount subscription with offers to explore locally and on the go.</p><ul><li>Discover dining, shopping and service offers</li><li>Keep your digital discounts on your phone</li><li>Support {player?'Ethan’s team':'the Cardinals’ fundraiser'} with your purchase</li></ul><button className={s.primary} onClick={()=>demo('Buy the $25 annual subscription')}>Get One Year for $25 ↗</button></div><img className={s.discount} src="/images/approved/discounts-original.png" alt="Approved Boss Bucks digital discount card mockup"/></article>
 <article className={s.trial}><span className={s.label}>TRY THE SAVINGS. SHARE THE SUPPORT.</span><div className={s.sixty}>60<span>DAYS FREE</span></div><h3>Try Boss Bucks.<br/>Cheer us on.</h3><p>Explore digital discount offers with a free 60-day trial. Add an optional donation to support {player?'Ethan and the Cardinals':'our Cardinals'}.</p><button className={s.primary} onClick={()=>demo('Start the free 60-day trial')}>Start My Free Trial ↗</button><button className={s.outline} onClick={()=>demo('Trial with an optional donation')}>Start Trial + Add a Donation</button><small>Donation optional. Sample flow for review.</small></article>
 </div></section>
 <section className={s.deals}><div><p className={s.eyebrow}>A LOOK INSIDE BOSS BUCKS</p><h2>Real reasons<br/>to <em>love saving.</em></h2><p>Browse sample discounts and see what the digital experience can look like.</p><div className={s.controls}><button aria-label="Previous discount sample" onClick={()=>setSlide((slide+3)%4)}>←</button><span aria-live="polite">{slide+1} / 4 · {samples[slide][1]}</span><button aria-label="Next discount sample" onClick={()=>setSlide((slide+1)%4)}>→</button></div><div className={s.dots}>{samples.map((sample,i)=><button key={sample[0]} aria-label={`Show ${sample[1]}`} aria-pressed={slide===i} onClick={()=>setSlide(i)}>{i+1}</button>)}</div><small>Illustrative offers. Brands and discounts shown do not confirm current participation or availability.</small></div><div className={s.sample} onTouchStart={event=>{swipeStart.current=event.touches[0].clientX}} onTouchEnd={event=>{if(swipeStart.current!==null){const distance=event.changedTouches[0].clientX-swipeStart.current;if(Math.abs(distance)>45)setSlide(current=>(current+(distance<0?1:3))%4);swipeStart.current=null}}}><svg viewBox="125 0 775 1536" role="img" aria-label={`${samples[slide][1]} discount app sample`}><defs><clipPath id="sample-phone"><rect x={slide===1?145:slide===0?145:132} y="10" width={slide<2?730:758} height={slide===1?1460:1488} rx="130"/></clipPath></defs><image href={`/images/approved/merchant-deals-${samples[slide][0]}.png`} width="1024" height="1536" clipPath="url(#sample-phone)"/></svg></div></section>
 <section className={s.mission}><div><p className={s.eyebrow}>BOSS DIGITAL MONEY BOARD</p><h2>You showed up.<br/><em>We did it together.</em></h2><p>This separate Money Board milestone is fully funded. Thank you for helping the Cardinals reach this milestone!</p><div className={s.completedTotal}><strong>$10,000</strong><span>raised of $10,000 goal</span></div><div className={s.track} role="progressbar" aria-label="Completed Money Board" aria-valuemin={0} aria-valuemax={10000} aria-valuenow={10000}><span style={{width:'100%'}}/></div><p className={s.completeNote}>100% FUNDED · BOARD COMPLETE</p><a className={s.outline} href="#support">Keep Supporting the Active Fundraiser ↑</a></div><div className={s.board}><svg className={s.moneyPhone} viewBox="0 0 751 1492" width="751" height="1492" role="img" aria-label="Approved Boss Bucks Digital Money Board iPhone mockup"><defs><clipPath id="cardinals-money-phone-outline"><rect x="16" y="8" width="720" height="1474" rx="130"/><rect x="9" y="229" width="9" height="51" rx="3"/><rect x="9" y="340" width="9" height="92" rx="3"/><rect x="9" y="464" width="9" height="91" rx="3"/><rect x="734" y="382" width="8" height="165" rx="3"/></clipPath></defs><image href="/images/approved/money-board-original.png" width="751" height="1492" clipPath="url(#cardinals-money-phone-outline)"/></svg><div className={s.stamp}>MISSION<br/>ACCOMPLISHED</div><p>Approved app preview · Cardinals milestone fully funded.</p></div></section>
 <section className={s.thanks}><p className={s.eyebrow}>MORE THAN A SEASON</p><h2>Thank you for being<br/>part of <em>our team.</em></h2><p>Clinton Cardinals · Red. White. Black. All heart.</p><Link href={player?'/previews/cardinals':'/previews/cardinals/player'}>{player?'View the team fundraiser':'Meet Ethan · View player fundraiser'} →</Link></section>
 </main><footer className={s.footer}>Powered by THE BOSS · Illustrative fundraiser preview{player?' · Ethan Carter is a sample player identity.':''}</footer>{message&&<div className={s.notice} role="status"><p>{message}</p><button onClick={()=>setMessage('')} aria-label="Dismiss preview message">×</button></div>}
 </div>
}
