import type { Json } from "../supabase/database.types";
export const notificationOperations = ["notification.read", "notification.read_all", "preference.set", "delivery.process", "reminder.generate"] as const;
export type NotificationOperation = typeof notificationOperations[number];
export const notificationCategories = ["events", "registration", "fees", "communications", "security", "attendance", "volunteers"] as const;
export type NotificationCategory = typeof notificationCategories[number];
export type NotificationCommand = { operation: NotificationOperation; input: Record<string, Json | undefined> };
export type NotificationQuery = { view: "inbox" | "summary" | "preferences" | "history"; organization_id?: string; category?: NotificationCategory; before?: string; limit?: number };
export type Notification = { id: string; category: NotificationCategory; event_type: string; title: string; body: string; destination: string | null; organization_id: string; team_id: string | null; created_at: string; read_at: string | null };
export type NotificationPreference = { id: string; channel: "in_app" | "email"; category: NotificationCategory; organization_id: string | null; team_id: string | null; enabled: boolean };
export type NotificationHistory = { id: string; event_type: string; channel: string; status: string; created_at: string; sent_at: string | null; failure_category: string | null; attempts: number; recipient_name: string };
export type NotificationData = { notifications: Notification[]; preferences: NotificationPreference[]; history: NotificationHistory[]; unread_count: number; operations: NotificationOperation[]; availability: { in_app: boolean; email: "not_configured" | "available"; sms: "future"; push: "future" }; features: Record<string, boolean>; organizations: { id: string; label: string }[]; organizationId: string | null; unavailable?: boolean; accessDenied?: boolean };
export type NotificationResult = { request_id: string; operation: NotificationOperation; resource_id: string; version: number; processed?: number; generated?: number; suppressed?: number };
export const emptyNotifications: NotificationData = { notifications: [], preferences: [], history: [], unread_count: 0, operations: [], availability: { in_app: false, email: "not_configured", sms: "future", push: "future" }, features: {}, organizations: [], organizationId: null };
