import type { Json } from "../supabase/database.types";
export const rankingProducts = ["standings", "leaderboard", "records"] as const;
export type RankingProduct = typeof rankingProducts[number];
export type RankingQuery = { organization_id?: string; edition_id?: string; product?: RankingProduct; definition_id?: string; group_id?: string; limit?: number; cursor?: Json; history?: boolean };
export type RankingRow = { id: string; label: string; rank: number | null; wins: number | null; losses: number | null; ties: number | null; games_played: number | null; points: number | null; win_percentage: number | null; scoring_for: number | null; scoring_against: number | null; value: number | null; qualification_state: string | null; current_holder: boolean; achieved_at: string | null; event_type: string | null; recognized_at: string | null; explanation: Json | null; coverage: Json | null; qualification: Json | null; provenance: Json | null };
export type RankingEdition = { id: string; competition_id?: string; competition_name?: string; name: string; sport_key: string; season_id?: string; can_manage: boolean; can_policy_manage: boolean };
export type RankingDefinition = { id: string; name: string; product: "leaderboard" | "records"; source_kind: string; metric_key: string };
export type RankingData = { editions: RankingEdition[]; edition: RankingEdition | null; definitions: RankingDefinition[]; groups: { id: string; name: string; kind: string }[]; entries: { id: string; team_id: string; name: string; status: string }[]; rows: RankingRow[]; freshness: "current" | "refreshing" | "pending" | "unavailable"; generation: number; next_cursor: Json | null; can_create: boolean; can_manage: boolean; can_policy_manage: boolean; can_standings_manage: boolean; can_leaderboard_manage: boolean; can_records_manage: boolean; can_rebuild: boolean; restricted: boolean; unavailable: boolean };
export const emptyRankings = (): RankingData => ({ editions: [], edition: null, definitions: [], groups: [], entries: [], rows: [], freshness: "unavailable", generation: 0, next_cursor: null, can_create: false, can_manage: false, can_policy_manage: false, can_standings_manage: false, can_leaderboard_manage: false, can_records_manage: false, can_rebuild: false, restricted: false, unavailable: false });
