"use client";
import { useRef, useState, type FormEvent } from "react";
import { isRecord, uuid } from "@/lib/communications/input";
import type { CommunicationAttachment } from "@/lib/communications/contracts";
import { CommunicationUploadRetry } from "@/lib/communications/upload-retry";

export function AttachmentUploader({ threadId, onUploaded, announcement = false }: { threadId: string; onUploaded: (attachment: CommunicationAttachment) => void; announcement?: boolean }) {
  const [pending, setPending] = useState(false), [message, setMessage] = useState(""); const status = useRef<HTMLParagraphElement>(null), retry = useRef(new CommunicationUploadRetry());
  function announce(text: string) { setMessage(text); queueMicrotask(() => status.current?.focus()); }
  async function upload(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (pending) return; const file = new FormData(event.currentTarget).get("attachment");
    if (!(file instanceof File) || !file.size || file.size > 5 * 1024 * 1024 || !["application/pdf", "image/png", "image/jpeg"].includes(file.type)) { announce("Choose a PDF, PNG or JPEG file up to 5 MB."); return; }
    setPending(true); setMessage("");
    try { const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); const signature = JSON.stringify([threadId, file.name, file.type, Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join("")]); const identity = retry.current.request(signature); const response = await fetch("/app/communications/upload", { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "content-type": file.type, "x-thread-id": threadId, "x-file-name": encodeURIComponent(file.name), "x-upload-request-id": identity.request, "x-completion-request-id": identity.completion }, body: file }); const body: unknown = await response.json(); if (!response.ok || !isRecord(body) || body.ok !== true || !isRecord(body.result) || !uuid(body.result.attachment_id)) { announce(response.status === 403 ? "You do not have permission to attach files here." : "The upload could not be confirmed. Review the file and retry."); return; } retry.current.confirmed(); onUploaded({ id: body.result.attachment_id, filename: file.name, mime_type: file.type, size_bytes: file.size, status: "ready", operations: [] }); announce(announcement ? "Private attachment added to this announcement." : "File uploaded privately. Send your message to share it with this conversation."); } catch { announce("The upload could not be confirmed. Retry to safely check the same request."); } finally { setPending(false); }
  }
  return <form className="communication-upload" aria-label="Upload private attachment" onSubmit={upload}><label className="form-field"><span>Private attachment</span><input name="attachment" type="file" accept="application/pdf,image/png,image/jpeg" required disabled={pending} /></label><p className="communication-helper">PDF, PNG or JPEG up to 5 MB. Files stay private to authorized conversation members.</p><button className="button button-outline" disabled={pending} type="submit">{pending ? "Uploading..." : "Upload attachment"}</button><p role="status" aria-live="polite" tabIndex={-1} ref={status}>{message}</p></form>;
}
export function AttachmentDownload({ attachment }: { attachment: CommunicationAttachment }) {
  const [pending, setPending] = useState(false), [message, setMessage] = useState(""); const status = useRef<HTMLParagraphElement>(null);
  async function download() { if (pending) return; setPending(true); setMessage(""); try { const response = await fetch("/app/communications/download", { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "content-type": "application/json" }, body: JSON.stringify({ attachment_id: attachment.id, request_id: crypto.randomUUID() }) }); if (!response.ok) { setMessage("This private attachment is unavailable for your current access."); queueMicrotask(() => status.current?.focus()); return; } const blob = await response.blob(); if (blob.size > 5 * 1024 * 1024) throw new Error("Invalid file size"); const url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = `private-attachment.${attachment.mime_type === "application/pdf" ? "pdf" : attachment.mime_type === "image/png" ? "png" : "jpg"}`; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 30_000); setMessage("Private download started."); } catch { setMessage("The download could not be confirmed. Please try again."); } finally { setPending(false); } }
  return <div className="communication-attachment"><span>{attachment.filename} · {Math.ceil(attachment.size_bytes / 1024)} KB</span>{attachment.operations.includes("attachment.access") && <button type="button" className="button button-outline" disabled={pending} onClick={download}>{pending ? "Opening..." : "Download privately"}</button>}<p ref={status} role="status" aria-live="polite" tabIndex={-1}>{message}</p></div>;
}
