"use client";
import Link from "next/link";
import type { CommunicationData, CommunicationQuery } from "@/lib/communications/contracts";
import { ThreadDetail } from "./thread";
import { CommunicationTimestamp } from "./timestamp";
import { AnnouncementEditor, CommunicationManagement, ThreadEditor } from "./editors";
export function communicationHref(query: CommunicationQuery, changes: Partial<CommunicationQuery> = {}) { const value = { ...query, ...changes }, params = new URLSearchParams(); for (const [key, field] of [["org", "organization_id"], ["team", "team_id"], ["thread", "thread_id"], ["q", "query"], ["before", "before_sequence"]] as const) if (value[field]) params.set(key, String(value[field])); return `/app/${value.view === "announcements" ? "announcements" : "messages"}${params.size ? `?${params}` : ""}`; }
export function CommunicationsConsole({ data, query }: { data: CommunicationData; query: CommunicationQuery }) {
  const announcements = query.view === "announcements", title = announcements ? "Announcements" : "Messages";
  return <div className={`communications-console${data.detail ? " communication-has-detail" : ""}`}><header className="communication-heading"><p className="eyebrow">Your Boss community</p><h1>{title}</h1><p>{announcements ? "Organization and team updates, shared with the right audience." : "Private conversations with your authorized teams and community."}</p></header>
    {data.unavailable && <p className="communication-notice" role="alert">Communications are temporarily unavailable. Refresh and try again.</p>}
    <nav className="communication-tabs" aria-label="Communications views"><Link href={communicationHref({ ...query, view: "messages", thread_id: undefined, before_sequence: undefined })} aria-current={!announcements ? "page" : undefined}>Messages{data.unread.messages > 0 ? ` (${data.unread.messages})` : ""}</Link>{data.features.announcements !== false && <Link href={communicationHref({ ...query, view: "announcements", thread_id: undefined, before_sequence: undefined })} aria-current={announcements ? "page" : undefined}>Announcements</Link>}{data.features.in_app_notifications !== false && <Link href={`/app/notifications${data.organizationId ? `?org=${data.organizationId}` : ""}`}>Notifications</Link>}</nav>
    <form className="communication-filters" method="get" action={announcements ? "/app/announcements" : "/app/messages"}><label className="form-field"><span>Organization</span><select name="org" defaultValue={query.organization_id ?? data.organizationId ?? ""}><option value="">All authorized organizations</option>{data.organizations.map(row => <option key={row.id} value={row.id}>{row.label}</option>)}</select></label><label className="form-field"><span>Team</span><select name="team" defaultValue={query.team_id ?? ""}><option value="">All authorized teams</option>{data.teams.map(row => <option key={row.id} value={row.id}>{row.label}</option>)}</select></label><label className="form-field"><span>Search your messages</span><input name="q" defaultValue={query.query ?? ""} maxLength={100} /></label><button className="button button-outline" type="submit">Apply filters</button></form>
    {(data.features.communications === true || !data.organizationId && (data.threads.length > 0 || data.detail !== null)) && <div className="communication-workspace"><aside className="communication-conversation-list" aria-label={announcements ? "Announcement list" : "Conversation list"}>{data.threads.length ? data.threads.map(thread => <Link key={thread.id} className="communication-thread-link" aria-current={data.detail?.thread.id === thread.id ? "page" : undefined} href={communicationHref(query, { organization_id: thread.organization_id, thread_id: thread.id, before_sequence: undefined })}><span className="communication-thread-kind">{thread.kind.replaceAll("_", " ")}</span><strong>{thread.title}</strong>{thread.latest_at && <CommunicationTimestamp value={thread.latest_at} />}{thread.unread_count > 0 && <span className="communication-badge">{thread.unread_count} unread</span>}</Link>) : <p className="communication-empty">No {announcements ? "announcements" : "conversations"} match your current access and filters.</p>}</aside><div className="communication-detail-pane">{data.detail ? <><Link className="communication-mobile-back button button-outline" href={communicationHref(query, { thread_id: undefined, before_sequence: undefined })}>Back to {announcements ? "announcements" : "conversations"}</Link><ThreadDetail key={data.detail.thread.id} data={data} />{data.more && data.cursor && <Link className="button button-outline" href={communicationHref(query, { before_sequence: data.cursor })}>Older messages</Link>}</> : <p className="communication-empty">Choose {announcements ? "an announcement" : "a conversation"} to read it.</p>}</div></div>}
    {!data.unavailable && <>{announcements ? <AnnouncementEditor data={data} /> : <ThreadEditor key={data.organizationId} data={data} />}<CommunicationManagement data={data} /></>}
  </div>;
}
