"use client";
import { useState } from "react";
import { threadKinds, type CommunicationData, type CommunicationTarget, type ThreadKind } from "@/lib/communications/contracts";
import { configurationKeys, uuid } from "@/lib/communications/input";
import { CommunicationActionForm, CommunicationField, CommunicationTextarea, formText } from "./action-form";
const encodedTarget = (target: CommunicationTarget) => `${target.scope_type}:${target.scope_id}`;
function parseTarget(value: string) { const [scope_type, scope_id] = value.split(":"); return ["organization", "unit", "team"].includes(scope_type) && uuid(scope_id) ? { scope_type, scope_id } : null; }
export function ThreadEditor({ data }: { data: CommunicationData }) {
  const kinds = threadKinds.filter(kind => data.targets.some(target => target.operations.includes("thread.create") && target.thread_kinds.includes(kind)) && (kind !== "family" || data.households.length > 0));
  const [kind, setKind] = useState<ThreadKind>(kinds[0] ?? "group"), selectedKind = kinds.includes(kind) ? kind : kinds[0];
  if (!data.organizationId || !data.operations.includes("thread.create") || !kinds.length) return null;
  return <details className="communication-disclosure"><summary>Start a conversation</summary><CommunicationActionForm label="Create conversation" build={form => {
    const target = parseTarget(formText(form, "scope")), selected = formText(form, "kind");
    return target ? { operation: "thread.create", input: { organization_id: data.organizationId!, title: formText(form, "title"), kind: selected, ...target, ...(["direct", "group", "family"].includes(selected) ? { members: form.getAll("members").map(String) } : {}), ...(selected === "family" ? { household_id: formText(form, "household_id") } : {}) } } : null;
  }}><CommunicationField name="title" label="Conversation title" required /><label className="form-field"><span>Conversation type</span><select name="kind" value={selectedKind} onChange={event => setKind(event.target.value as ThreadKind)}>{kinds.map(value => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label className="form-field"><span>Owning scope</span><select name="scope" required>{data.targets.filter(target => target.operations.includes("thread.create") && target.thread_kinds.includes(selectedKind)).map(target => <option key={encodedTarget(target)} value={encodedTarget(target)}>{target.label}</option>)}</select></label>
    {selectedKind === "direct" ? <label className="form-field"><span>Authorized recipient</span><select name="members" required><option value="">Choose a recipient</option>{data.candidates.map(candidate => <option key={candidate.id} value={candidate.id}>{candidate.label}</option>)}</select></label> : ["group", "family"].includes(selectedKind) && <fieldset className="communication-choice-group"><legend>Authorized members</legend>{data.candidates.map(candidate => <label className="communication-check" key={candidate.id}><input type="checkbox" name="members" value={candidate.id} />{candidate.label}</label>)}<p className="communication-helper">Choose up to 19 members. Your identity is included automatically. Minor groups require current guardian visibility.</p></fieldset>}
    {selectedKind === "family" && <label className="form-field"><span>Authorized household</span><select name="household_id" required>{data.households.map(household => <option key={household.id} value={household.id}>{household.label}</option>)}</select></label>}
    {["direct", "group", "family"].includes(selectedKind) && <p className="communication-helper">Only current authorized relationships are offered. Direct adult-to-minor conversations are unavailable.</p>}
  </CommunicationActionForm></details>;
}
export function AnnouncementEditor({ data }: { data: CommunicationData }) {
  const [roleKey, setRoleKey] = useState(""); if (!data.organizationId || !data.operations.includes("announcement.send") || !data.targets.length) return null;
  const targets = data.targets.filter(target => target.operations.includes("announcement.send")), role = data.audienceRoles.find(value => value.key === roleKey);
  const compatible = (target: CommunicationTarget) => !role || role.allowed_scope_types.includes(target.scope_type === "unit" ? "organization_unit" : target.scope_type);
  return <details className="communication-disclosure"><summary>Send an announcement</summary><CommunicationActionForm label="Send announcement" build={form => ({ operation: "announcement.send", input: { organization_id: data.organizationId!, title: formText(form, "title"), body: formText(form, "body"), visibility: formText(form, "visibility"), targets: form.getAll("target").map(value => parseTarget(String(value))).filter((value): value is { scope_type: string; scope_id: string } => value !== null).map(target => ({ ...target, ...(formText(form, "role_key") ? { role_key: formText(form, "role_key") } : {}) })) } })}>
    <CommunicationField name="title" label="Announcement title" required /><CommunicationTextarea name="body" label="Announcement" />
    {data.audienceRoles.length > 0 && <label className="form-field"><span>Role audience</span><select name="role_key" value={roleKey} onChange={event => setRoleKey(event.target.value)}><option value="">All permitted members of selected scopes</option>{data.audienceRoles.filter(value => targets.some(target => value.allowed_scope_types.includes(target.scope_type === "unit" ? "organization_unit" : target.scope_type))).map(value => <option key={value.key} value={value.key}>{value.label}</option>)}</select></label>}
    <fieldset className="communication-choice-group"><legend>Audience</legend>{targets.filter(compatible).map(target => <label key={encodedTarget(target)} className="communication-check"><input type="checkbox" name="target" value={encodedTarget(target)} />{target.label}</label>)}<p className="communication-helper">One announcement can reach several teams without sharing their private conversations or recipient lists.</p></fieldset><label className="form-field"><span>Visibility</span><select name="visibility"><option value="private">Private to the authorized audience</option><option value="public">Public label for future publication</option></select></label>
  </CommunicationActionForm></details>;
}
export function CommunicationManagement({ data }: { data: CommunicationData }) { return <section className="communication-management">
  {data.organizationId && data.operations.includes("communications.configure") && <details className="communication-disclosure"><summary>Communications settings</summary><CommunicationActionForm label="Save settings" build={form => ({ operation: "communications.configure", input: { organization_id: data.organizationId!, configuration: Object.fromEntries(configurationKeys.filter(key => key !== "email_notifications").map(key => [key, ["minimum_participant_age", "sender_edit_minutes"].includes(key) ? Number(formText(form, key)) : form.has(key)])) } })}><div className="communication-fields">{configurationKeys.filter(key => !["minimum_participant_age", "sender_edit_minutes", "email_notifications"].includes(key)).map(key => <label className="communication-check" key={key}><input name={key} type="checkbox" defaultChecked={data.features[key] === true} />{key.replaceAll("_", " ")}</label>)}<label className="form-field"><span>Minimum participant age</span><input name="minimum_participant_age" type="number" min={0} max={99} defaultValue={typeof data.features.minimum_participant_age === "number" ? data.features.minimum_participant_age : 18} required /></label><label className="form-field"><span>Sender edit window in minutes</span><input name="sender_edit_minutes" type="number" min={0} max={60} defaultValue={typeof data.features.sender_edit_minutes === "number" ? data.features.sender_edit_minutes : 15} required /></label></div><p className="communication-helper">Email delivery is not configured. Participant messaging remains subject to age, current relationships and guardian visibility safeguards.</p></CommunicationActionForm></details>}
  {data.guardians.filter(guardian => guardian.operations.includes("guardian.configure")).map(guardian => <details className="communication-disclosure" key={guardian.id}><summary>Guardian communications · {guardian.dependent_name}</summary><CommunicationActionForm label="Save guardian authority" build={form => ({ operation: "guardian.configure", input: { guardian_relationship_id: guardian.id, can_receive_communications: form.has("receive"), can_send_communications: form.has("send") } })}><p>{guardian.guardian_name} · {guardian.dependent_name}</p><label className="communication-check"><input name="receive" type="checkbox" defaultChecked={guardian.can_receive_communications} />Receive and view permitted communication</label><label className="communication-check"><input name="send" type="checkbox" defaultChecked={guardian.can_send_communications} />Send permitted communication</label></CommunicationActionForm></details>)}
  {data.features.moderation === true && data.reports.filter(report => report.operations.includes("report.moderate")).map(report => <details className="communication-disclosure" key={report.id}><summary>Review report · {report.reason.replaceAll("_", " ")} · {report.status}</summary><CommunicationActionForm label="Record moderation decision" build={form => ({ operation: "report.moderate", input: { report_id: report.id, status: formText(form, "status"), remove: form.has("remove"), reason: formText(form, "reason") } })}><label className="form-field"><span>Decision</span><select name="status"><option value="reviewed">Reviewed</option><option value="dismissed">Dismissed</option><option value="actioned">Action taken</option></select></label><CommunicationField name="reason" label="Reason" maxLength={500} required /><label className="communication-check"><input name="remove" type="checkbox" />Remove the reported message</label></CommunicationActionForm></details>)}
  </section>; }
