"use client";
import Link from "next/link";
import { notificationCategories, type Notification, type NotificationData, type NotificationQuery } from "@/lib/notifications/contracts";
import { CommunicationActionForm, formText } from "./action-form";
import { formatTimestamp } from "./thread";
export function NotificationCard({ notification, canRead }: { notification: Notification; canRead: boolean }) {
  return <article className={`notification-card${notification.read_at ? "" : " notification-unread"}`}><header><span className="communication-thread-kind">{notification.category}</span><time dateTime={notification.created_at}>{formatTimestamp(notification.created_at)}</time>{!notification.read_at && <span className="communication-badge">Unread</span>}</header><h3>{notification.title}</h3><p className="communication-body">{notification.body}</p><div className="notification-card-actions">{notification.destination && <Link className="button button-outline" href={notification.destination}>View details</Link>}{canRead && !notification.read_at && <CommunicationActionForm notifications label="Mark read" build={() => ({ operation: "notification.read", input: { id: notification.id } })} />}</div></article>;
}
export function NotificationPreferences({ data }: { data: NotificationData }) {
  if (!data.operations.includes("preference.set")) return null;
  return <section className="communication-section"><h2>Notification preferences</h2><p className="communication-helper">Choose optional notifications by category and channel. Email preferences are saved while delivery remains unconfigured.</p><CommunicationActionForm notifications label="Save preference" build={form => ({ operation: "preference.set", input: { channel: formText(form, "channel"), category: formText(form, "category"), enabled: form.has("enabled"), ...(formText(form, "organization_id") ? { organization_id: formText(form, "organization_id") } : {}) } })}><div className="communication-fields"><label className="form-field"><span>Channel</span><select name="channel"><option value="in_app">In-app</option><option value="email">Email preference</option></select></label><label className="form-field"><span>Category</span><select name="category">{notificationCategories.filter(value => value !== "security").map(value => <option key={value} value={value}>{value}</option>)}</select></label><label className="form-field"><span>Context</span><select name="organization_id" defaultValue={data.organizationId ?? ""}><option value="">All organizations</option>{data.organizations.map(row => <option key={row.id} value={row.id}>{row.label}</option>)}</select></label><label className="communication-check"><input name="enabled" type="checkbox" defaultChecked />Receive this category</label></div></CommunicationActionForm>
    <div className="notification-preferences">{data.preferences.map(preference => <article className="communication-preference" key={preference.id}><p><strong>{preference.category} · {preference.channel === "in_app" ? "in-app" : "email"}</strong></p><p className="communication-helper">{preference.organization_id ? data.organizations.find(row => row.id === preference.organization_id)?.label ?? "Organization context" : "All organizations"}{preference.team_id ? " · Team context" : ""} · {preference.enabled ? "On" : "Off"}</p><CommunicationActionForm notifications label={preference.enabled ? "Turn off" : "Turn on"} build={() => ({ operation: "preference.set", input: { channel: preference.channel, category: preference.category, enabled: !preference.enabled, ...(preference.organization_id ? { organization_id: preference.organization_id } : {}), ...(preference.team_id ? { team_id: preference.team_id } : {}) } })} /></article>)}</div>
  </section>;
}
export function DeliveryHistory({ data }: { data: NotificationData }) { return <section className="communication-section"><h2>Delivery history</h2><p className="communication-helper">Provider acceptance is recorded as sent. Delivered status requires provider confirmation.</p>{data.history.length ? <div className="notification-history">{data.history.map(row => <article className="notification-card" key={row.id}><header><strong>{row.recipient_name || "Authorized recipient"}</strong><span className="communication-badge">{row.status.replaceAll("_", " ")}</span></header><dl className="notification-facts"><div><dt>Type</dt><dd>{row.event_type.replaceAll("_", " ")}</dd></div><div><dt>Channel</dt><dd>{row.channel.replaceAll("_", " ")}</dd></div><div><dt>Created</dt><dd>{formatTimestamp(row.created_at)}</dd></div><div><dt>Attempts</dt><dd>{row.attempts}</dd></div>{row.sent_at && <div><dt>Sent</dt><dd>{formatTimestamp(row.sent_at)}</dd></div>}{row.failure_category && <div><dt>Failure category</dt><dd>{row.failure_category.replaceAll("_", " ")}</dd></div>}</dl></article>)}</div> : <p className="communication-empty">No delivery records are available for this scope.</p>}</section>; }
export function NotificationCenter({ data, query }: { data: NotificationData; query: NotificationQuery }) {
  const suffix = query.organization_id ? `&org=${query.organization_id}` : "", historyAvailable = data.features.delivery_history === true || data.features.history_available === true;
  return <div className="communications-console notification-center"><header className="communication-heading"><p className="eyebrow">Your Boss updates</p><h1>Notifications</h1><p>{data.unread_count} unread updates from your authorized organizations and teams.</p></header>{data.accessDenied && <p role="alert" className="communication-notice">Notifications are restricted in this organization context.</p>}{data.unavailable && <p role="alert" className="communication-notice">Notifications are temporarily unavailable. Please try again.</p>}<nav className="communication-tabs" aria-label="Notification views"><Link href={`/app/notifications?view=inbox${suffix}`} aria-current={query.view === "inbox" ? "page" : undefined}>Inbox</Link>{data.operations.includes("preference.set") && <Link href={`/app/notifications?view=preferences${suffix}`} aria-current={query.view === "preferences" ? "page" : undefined}>Preferences</Link>}{historyAvailable && <Link href={`/app/notifications?view=history${suffix}`} aria-current={query.view === "history" ? "page" : undefined}>Delivery history</Link>}</nav>
    <form className="communication-filters" method="get" action="/app/notifications"><input type="hidden" name="view" value={query.view} /><label className="form-field"><span>Organization</span><select name="org" defaultValue={query.organization_id ?? ""}><option value="">All authorized organizations</option>{data.organizations.map(row => <option key={row.id} value={row.id}>{row.label}</option>)}</select></label><label className="form-field"><span>Category</span><select name="category" defaultValue={query.category ?? ""}><option value="">All categories</option>{notificationCategories.map(category => <option key={category} value={category}>{category}</option>)}</select></label><button type="submit" className="button button-outline">Apply filters</button></form>
    {query.view === "preferences" ? <NotificationPreferences data={data} /> : query.view === "history" ? <DeliveryHistory data={data} /> : <>{data.operations.includes("notification.read_all") && data.unread_count > 0 && <CommunicationActionForm notifications label="Mark all read" build={() => ({ operation: "notification.read_all", input: query.organization_id ? { organization_id: query.organization_id } : {} })} />}<div className="notification-list">{data.notifications.length ? data.notifications.map(notification => <NotificationCard key={notification.id} notification={notification} canRead={data.operations.includes("notification.read")} />) : <p className="communication-empty">You have no updates matching your current access and filters.</p>}</div>{data.notifications.length >= (query.limit ?? 30) && <Link className="button button-outline" href={`/app/notifications?view=inbox${suffix}${query.category ? `&category=${query.category}` : ""}&before=${encodeURIComponent(data.notifications[data.notifications.length - 1].created_at)}`}>Older notifications</Link>}</>}
    {data.organizationId && (data.operations.includes("delivery.process") || data.operations.includes("reminder.generate")) && <details className="communication-disclosure"><summary>Notification administration</summary><p className="communication-helper">Email delivery is {data.availability.email === "available" ? "configured" : "not configured"}. Delivery preparation checks current access and preferences.</p>{data.operations.includes("reminder.generate") && <CommunicationActionForm notifications label="Prepare current reminders" build={() => ({ operation: "reminder.generate", input: { organization_id: data.organizationId! } })} />}{data.operations.includes("delivery.process") && <CommunicationActionForm notifications label="Process delivery queue" build={() => ({ operation: "delivery.process", input: { organization_id: data.organizationId!, limit: 25 } })} />}</details>}
  </div>;
}
