"use client";
import { useState } from "react";
import { CommunicationTimestamp } from "./timestamp";
export { formatTimestamp } from "./timestamp";
import { useRouter } from "next/navigation";
import type { CommunicationAttachment, CommunicationData, CommunicationMessage } from "@/lib/communications/contracts";
import { CommunicationActionForm, CommunicationField, CommunicationTextarea, formText } from "./action-form";
import { AttachmentDownload, AttachmentUploader } from "./attachments";

export function MessageCard({ message }: { message: CommunicationMessage }) {
  const hidden = message.body === null;
  return <article className={`communication-message${message.pinned ? " communication-pinned" : ""}`}><header><strong>{message.author_name}</strong><CommunicationTimestamp value={message.created_at} />{message.pinned && <span className="communication-badge">Pinned</span>}</header>{hidden ? <p className="communication-helper">This message was removed.</p> : <><p className="communication-body">{message.body}</p>{message.edited_at && <p className="communication-helper">Edited <CommunicationTimestamp value={message.edited_at} /></p>}{message.attachments.map(attachment => <AttachmentDownload key={attachment.id} attachment={attachment} />)}</>}
    <div className="communication-message-actions">{message.operations.includes("message.pin") && <CommunicationActionForm label={message.pinned ? "Unpin" : "Pin"} build={() => ({ operation: "message.pin", input: { message_id: message.id, expected_version: message.version, pinned: !message.pinned } })} />}{message.operations.includes("read.message") && <CommunicationActionForm label="Mark message read" build={() => ({ operation: "read.message", input: { message_id: message.id } })} />}</div>
    {!hidden && message.operations.includes("message.edit") && <details className="communication-disclosure"><summary>Edit message</summary><CommunicationActionForm label="Save message" build={data => ({ operation: "message.edit", input: { message_id: message.id, expected_version: message.version, body: formText(data, "body") } })}><CommunicationTextarea name="body" label="Message" value={message.body ?? ""} /></CommunicationActionForm></details>}
    {message.operations.includes("message.remove") && <details className="communication-disclosure"><summary>Remove message</summary><CommunicationActionForm label="Remove message" build={data => ({ operation: "message.remove", input: { message_id: message.id, expected_version: message.version, reason: formText(data, "reason") } })}><p className="communication-helper">Removal hides the message while retaining audit evidence.</p><CommunicationField name="reason" label="Reason" maxLength={500} /></CommunicationActionForm></details>}
    {!hidden && message.operations.includes("report.create") && <details className="communication-disclosure"><summary>Report message</summary><CommunicationActionForm label="Send report" build={data => ({ operation: "report.create", input: { message_id: message.id, reason: formText(data, "reason"), detail: formText(data, "detail") } })}><label className="form-field"><span>Reason</span><select name="reason"><option value="spam">Spam</option><option value="harassment">Harassment</option><option value="unsafe">Safety concern</option><option value="other">Other</option></select></label><CommunicationTextarea name="detail" label="Additional context" maxLength={500} required={false} /></CommunicationActionForm></details>}
  </article>;
}
export function ThreadDetail({ data }: { data: CommunicationData }) {
  const router = useRouter(); const [attachments, setAttachments] = useState<CommunicationAttachment[]>([]), [revision, setRevision] = useState(0); const detail = data.detail; if (!detail) return null; const thread = detail.thread;
  const canSend = thread.operations.includes("message.send") && thread.status === "active";
  const explicitGroup = ["direct", "group", "family"].includes(thread.kind), memberChoices = [...new Map([...thread.members, ...data.candidates].map(member => [member.id, member])).values()].filter(member => member.id !== data.person?.id);
  return <section className="communication-thread-detail" aria-label="Conversation details"><header className="communication-detail-heading"><div><p className="communication-helper">{thread.kind.replaceAll("_", " ")}</p><h2>{thread.title}</h2></div>{thread.operations.includes("read.thread") && <CommunicationActionForm label="Mark conversation read" build={() => ({ operation: "read.thread", input: { thread_id: thread.id, ...(detail.messages.length ? { through_sequence: Math.max(...detail.messages.map(message => message.sequence)) } : {}) } })} />}</header>
    <div className="communication-message-list">{detail.messages.length ? detail.messages.map(message => <MessageCard key={`${message.id}:${message.version}`} message={message} />) : <p className="communication-empty">No messages yet.</p>}</div>
    {canSend && <section className="communication-composer" aria-label="Message composer"><h3>Send a message</h3><CommunicationActionForm key={`composer:${thread.id}:${revision}`} name="Send message" label="Send message" onSaved={() => { setAttachments([]); setRevision(value => value + 1); }} build={form => ({ operation: "message.send", input: { thread_id: thread.id, body: formText(form, "body"), ...(attachments.length ? { attachment_ids: attachments.map(attachment => attachment.id) } : {}) } })}><CommunicationTextarea name="body" label="Message" />{attachments.length > 0 && <ul className="communication-attached-files">{attachments.map(attachment => <li key={attachment.id}>{attachment.filename}<button type="button" onClick={() => setAttachments(current => current.filter(item => item.id !== attachment.id))} aria-label={`Remove ${attachment.filename} from this message`}>Remove</button></li>)}</ul>}</CommunicationActionForm>{data.features.attachments === true && thread.operations.includes("attachment.intent") && attachments.length < 5 && <AttachmentUploader threadId={thread.id} onUploaded={attachment => setAttachments(current => current.some(item => item.id === attachment.id) ? current : [...current, attachment].slice(0, 5))} />}</section>}
    {thread.kind === "announcement" && data.features.attachments === true && thread.operations.includes("attachment.intent") && <section className="communication-composer"><h3>Add a private attachment</h3><AttachmentUploader threadId={thread.id} announcement onUploaded={() => router.refresh()} /></section>}
    {thread.operations.includes("thread.update") && <details className="communication-disclosure"><summary>Conversation settings</summary><CommunicationActionForm label="Save conversation" build={form => ({ operation: "thread.update", input: { thread_id: thread.id, expected_version: thread.version, title: formText(form, "title"), status: formText(form, "status"), ...(explicitGroup ? { members: form.getAll("members").map(String) } : {}) } })}><CommunicationField name="title" label="Conversation title" value={thread.title} required /><label className="form-field"><span>Status</span><select name="status" defaultValue={thread.status}><option value="active">Active</option><option value="archived">Archived</option></select></label>{explicitGroup && <fieldset className="communication-choice-group"><legend>Conversation members</legend>{memberChoices.map(member => <label key={member.id} className="communication-check"><input name="members" type="checkbox" value={member.id} defaultChecked={thread.members.some(current => current.id === member.id)} />{member.label}</label>)}<p className="communication-helper">Your identity stays included. Every change checks current relationships and guardian safeguards.</p></fieldset>}</CommunicationActionForm></details>}
  </section>;
}
