"use client";
import { useEffect, useState } from "react";
import type { Json } from "@/lib/supabase/database.types";
import type { Game, GameCommand } from "@/lib/games/contracts";
import { footballFieldsByPlay, footballPlayTypes, type FootballEntry, type FootballGame, type FootballPlay, type FootballPlayType, type FootballSide, type FootballTeam, type FootballPlayer, type FootballTotals } from "@/lib/football/contracts";
import { footballBallPosition, footballClock, footballClockEstimate, footballCorrectionEntries, footballDown, footballPeriod, footballPlayLabels, footballStatSections } from "@/lib/football/presentation";
import { fieldInteger, fieldText } from "../coordination/action-form";
import { humanize } from "../coordination/presentation";
import { GameForm } from "../games/action-form";
import { GameIntentProvider, useGameIntent, useOptionalGameIntent } from "../games/intent-provider";

const opposite = (side: FootballSide): FootballSide => side === "primary" ? "opponent" : "primary";
const teamLabel = (game: Game, side: FootballSide) => side === "primary" ? game.primary.label : game.opponent.label;
const athleteLabel = (row: FootballEntry) => `${row.jersey_number ? `#${row.jersey_number} · ` : ""}${row.display_name}`;
function FootballClock({ state }: { state: FootballGame }) {
  const [now, setNow] = useState<number | null>(null);
  useEffect(() => { if (!state.clock_running) return; const timer = setInterval(() => setNow(Date.now()), 250); return () => clearInterval(timer); }, [state.clock_running, state.clock_observed_at]);
  return <div className="football-clock"><strong>{footballClock(now === null ? state.clock_ms : footballClockEstimate(state, now))}</strong><span>{state.clock_running ? "Running · estimated display" : "Stopped"}</span></div>;
}
function NumberField({ name, label, min = 0, max = 100, value = 0, required = false }: { name: string; label: string; min?: number; max?: number; value?: number | null; required?: boolean }) { return <label className="form-field"><span>{label}</span><input name={name} type="number" step={1} min={min} max={max} defaultValue={value ?? ""} required={required} /></label>; }
function AthleteField({ name, label, entries, value }: { name: string; label: string; entries: FootballEntry[]; value?: unknown }) { return <label className="form-field"><span>{label}</span><select name={name} defaultValue={typeof value === "string" && entries.some(row => row.id === value) ? value : ""}><option value="">Team / unattributed</option>{entries.filter(row => row.active).map(row => <option key={row.id} value={row.id}>{athleteLabel(row)}</option>)}</select></label>; }
function StatGrid({ stats, keys }: { stats: FootballTotals; keys: readonly [keyof FootballTotals, string][] }) { return <dl className="football-stats-grid">{keys.map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{stats[key] ?? "--"}</dd></div>)}</dl>; }
function FootballBox({ game, players, teams }: { game: Game; players: FootballPlayer[]; teams: FootballTeam[] }) { return <div className="football-box">{(["primary", "opponent"] as const).map(side => <section className="football-team-box" key={side}><h4>{teamLabel(game, side)}</h4>{teams.filter(row => row.side === side).map(row => <article className="football-stat-card football-team-total" key={side}><h5>Team totals</h5><StatGrid stats={row.stats} keys={[["points", "PTS"], ["net_passing_yards", "NET PASS"], ["rushing_yards", "RUSH"], ["total_offensive_yards", "TOTAL YDS"], ["first_downs", "1ST"], ["turnovers", "TO"], ["sacks", "SACK"], ["return_yards", "RET YDS"], ["penalties", "PEN"], ["penalty_yards", "PEN YDS"]]} /></article>)}{footballStatSections.map(section => { const relevant = players.filter(row => row.side === side && section.stats.some(([key]) => row.stats[key] !== null && row.stats[key] !== 0)); return relevant.length ? <section className="football-stat-section" key={section.label}><h5>{section.label}</h5>{relevant.map(row => <article className="football-stat-card" key={row.roster_id}><h6>{row.jersey_number ? `#${row.jersey_number} · ` : ""}{row.display_name}</h6><StatGrid stats={row.stats} keys={section.stats} /></article>)}</section> : null; })}</section>)}</div>; }
function PlayDescription({ game, state, play }: { game: Game; state: FootballGame; play: FootballPlay }) {
  const entries = [...state.entry_roster, ...game.roster.map(row => ({ id: row.id, display_name: row.display_name, jersey_number: row.jersey_number }))];
  const actor = entries.find(row => row.id === play.payload.roster_id), receiver = entries.find(row => row.id === play.payload.receiver_roster_id);
  const label = footballPlayTypes.includes(play.type as FootballPlayType) ? footballPlayLabels[play.type as FootballPlayType] : humanize(play.type);
  return <><span className="football-play-context">#{play.sequence} · {footballPeriod(play.period_number)} · {footballClock(play.clock_ms)}{play.before_field?.possession_side ? ` · ${footballDown(play.before_field)} · ${footballBallPosition(play.before_field.ball_spot)}` : ""}</span><strong>{play.side ? `${teamLabel(game, play.side)} · ` : ""}{label}{actor ? ` · ${actor.jersey_number ? `#${actor.jersey_number} ` : ""}${actor.display_name}` : ""}{receiver ? ` to ${receiver.jersey_number ? `#${receiver.jersey_number} ` : ""}${receiver.display_name}` : ""}</strong><span>{typeof play.payload.yards === "number" ? `${play.payload.yards} yards` : ""}{typeof play.payload.return_yards === "number" ? ` · Return ${play.payload.return_yards} yards` : ""}{play.payload.touchdown ? " · Touchdown" : ""}{typeof play.payload.made === "boolean" ? play.payload.made ? " · Made" : " · Missed" : ""}{!play.active ? " · Superseded" : ""}</span></>;
}
function FootballSetup({ game }: { game: Game }) { return <section className="football-panel"><h3>Football game format</h3><GameForm label="Configure football game" build={form => ({ operation: "football.configure", input: { game_id: game.id, expected_version: game.version, quarter_seconds: fieldInteger(form, "quarter_seconds"), overtime_format: fieldText(form, "overtime_format"), overtime_seconds: fieldInteger(form, "overtime_seconds"), max_overtime_periods: fieldInteger(form, "max_overtime_periods"), play_clock_seconds: fieldText(form, "play_clock_seconds") ? fieldInteger(form, "play_clock_seconds") : null, lineup_size: fieldInteger(form, "lineup_size"), enforce_lineup: form.get("enforce_lineup") === "on", kneel_counts_as_rush: form.get("kneel_counts_as_rush") === "on" } })}><p>Four quarters. Select the reviewed competition format; overtime never assumes one universal rulebook.</p><div className="game-form-grid"><NumberField name="quarter_seconds" label="Quarter seconds" min={60} max={3600} value={720} required /><label className="form-field"><span>Overtime format</span><select name="overtime_format" defaultValue="none"><option value="none">No overtime</option><option value="timed">Timed periods</option><option value="possession">Operator-confirmed possession periods</option></select></label><NumberField name="overtime_seconds" label="Timed overtime seconds" min={60} max={1800} value={300} required /><NumberField name="max_overtime_periods" label="Maximum overtime periods" min={0} max={8} value={0} required /><NumberField name="play_clock_seconds" label="Play-clock duration (optional foundation)" min={5} max={60} value={null} /><NumberField name="lineup_size" label="Players per side" min={1} max={11} value={11} required /></div><label className="game-confirmation"><input type="checkbox" name="enforce_lineup" /><span>Require a complete lineup for attributed playing outcomes</span></label><label className="game-confirmation"><input type="checkbox" name="kneel_counts_as_rush" /><span>Count quarterback kneels as rush attempts and rushing yards</span></label><p className="game-helper">Play-clock duration is recorded; automated play-clock and penalty enforcement are not available.</p></GameForm></section>; }

const yardTypes = ["rush", "pass_complete", "sack", "kneel", "fumble", "two_point"];
const resultTypes = ["kickoff", "kickoff_return", "punt", "punt_return", "field_goal", "safety", "penalty"];
export function PlayFields({ game, state, side, type, entries, defaults = {} }: { game: Game; state: FootballGame; side: FootballSide; type: FootballPlayType; entries: FootballEntry[]; defaults?: FootballPlay["payload"] }) {
  const own = entries.filter(row => row.side === side), defense = entries.filter(row => row.side === opposite(side));
  const [recovery, setRecovery] = useState<FootballSide>(defaults.recovery_side === "primary" || defaults.recovery_side === "opponent" ? defaults.recovery_side : opposite(side));
  const [basePlay, setBasePlay] = useState(typeof defaults.base_play_type === "string" ? defaults.base_play_type : "rush");
  const kick = ["kickoff", "kickoff_return", "punt", "punt_return", "field_goal", "extra_point"].includes(type), fumble = ["fumble", "fumble_recovery"].includes(type);
  return <><div className="game-form-grid">{type !== "turnover_on_downs" && <AthleteField name="roster_id" label={kick ? "Kicker / punter" : type === "penalty" ? "Penalized athlete" : "Runner / passer / acting athlete"} entries={own} value={defaults.roster_id} />}{(["pass_complete", "pass_incomplete", "interception", "two_point"].includes(type) || type === "fumble" && basePlay === "pass_complete") && <AthleteField name="receiver_roster_id" label="Receiver / target (when captured)" entries={own} value={defaults.receiver_roster_id} />}{yardTypes.includes(type) && <NumberField key={basePlay} name="yards" label={type === "two_point" ? "Conversion yards (excluded from ordinary offense)" : "Play yards (negative for loss)"} min={type === "fumble" && basePlay === "none" ? 0 : -100} max={type === "sack" || type === "fumble" && basePlay === "sack" ? -1 : type === "kneel" || type === "fumble" && basePlay === "none" ? 0 : 100} value={type === "fumble" && basePlay === "none" ? 0 : typeof defaults.yards === "number" ? defaults.yards : type === "sack" || type === "fumble" && basePlay === "sack" ? -1 : 0} required />}{(["sack", "interception", "safety"].includes(type) || type === "fumble" && basePlay === "sack") && <AthleteField name="defender_roster_id" label={type === "sack" || type === "fumble" ? "Sack defender (full credit)" : type === "safety" ? "Safety defender (if known)" : "Intercepting defender"} entries={defense} value={defaults.defender_roster_id} />}{type === "interception" && <NumberField name="interception_spot" label="Interception spot from passing side's own goal" value={typeof defaults.interception_spot === "number" ? defaults.interception_spot : state.field_state.ball_spot} required />}{["interception", "kickoff_return", "punt_return", "fumble", "fumble_recovery"].includes(type) && <NumberField name="return_yards" label="Return yards" value={typeof defaults.return_yards === "number" ? defaults.return_yards : 0} required />}{["kickoff", "kickoff_return", "punt", "punt_return"].includes(type) && <NumberField name="kick_yards" label="Kick / punt yards" value={typeof defaults.kick_yards === "number" ? defaults.kick_yards : 0} required />}{["kickoff_return", "punt_return"].includes(type) && <AthleteField name="returner_roster_id" label="Opposing returner" entries={defense} value={defaults.returner_roster_id} />}{type === "field_goal" && <NumberField name="kick_distance" label="Field-goal distance" min={1} value={typeof defaults.kick_distance === "number" ? defaults.kick_distance : 20} required />}</div>
    {["field_goal", "extra_point", "two_point"].includes(type) && <label className="game-confirmation"><input name="made" type="checkbox" defaultChecked={defaults.made === true} /><span>Attempt made / conversion successful</span></label>}{["rush", "pass_complete", "interception", "kickoff_return", "punt_return", "fumble", "fumble_recovery"].includes(type) && <label className="game-confirmation"><input name="touchdown" type="checkbox" defaultChecked={defaults.touchdown === true} /><span>Touchdown on this same accepted play</span></label>}{["kickoff", "punt", "kickoff_return", "punt_return"].includes(type) && <label className="game-confirmation"><input name="touchback" type="checkbox" defaultChecked={defaults.touchback === true} /><span>Touchback; confirm the resulting placement below</span></label>}
    {fumble && <section className="football-outcome"><h5>One fumble / recovery outcome</h5><p>Record the underlying action and recovery once. A fumble does not automatically mean a turnover.</p><div className="game-form-grid">{type === "fumble" && <label className="form-field"><span>Underlying play</span><select name="base_play_type" value={basePlay} onChange={event => setBasePlay(event.target.value)}><option value="rush">Rush</option><option value="pass_complete">Completed pass</option><option value="sack">Sack</option><option value="none">No attributed underlying action</option></select></label>}{type === "fumble" && <AthleteField name="forced_fumble_roster_id" label="Forced-fumble defender (if known)" entries={defense} value={defaults.forced_fumble_roster_id} />}<label className="form-field"><span>Recovering team</span><select name="recovery_side" value={recovery} onChange={event => setRecovery(event.target.value as FootballSide)}><option value="primary">{game.primary.label}</option><option value="opponent">{game.opponent.label}</option></select></label><AthleteField key={recovery} name="recovery_roster_id" label="Recovering athlete (if known)" entries={entries.filter(row => row.side === recovery)} value={defaults.recovery_roster_id} /></div></section>}
    {["rush", "pass_complete", "sack", "kneel", "fumble"].includes(type) && <details className="football-secondary-panel"><summary>Defensive attribution (optional)</summary><div className="game-form-grid"><AthleteField name="tackler_roster_id" label="Primary tackler" entries={defense} value={defaults.tackler_roster_id} /></div><fieldset className="football-assists"><legend>Assisting tacklers (maximum four)</legend>{defense.filter(row => row.active).map(row => <label className="game-confirmation" key={row.id}><input name="assisting_roster_ids" type="checkbox" value={row.id} defaultChecked={Array.isArray(defaults.assisting_roster_ids) && defaults.assisting_roster_ids.includes(row.id)} /><span>{athleteLabel(row)}</span></label>)}</fieldset><p className="game-helper">A primary tackle is solo when no assistants are entered. With assistants each known contributor receives an assist; the team gets one tackle outcome.</p></details>}
    {type === "pass_incomplete" && <AthleteField name="pass_defender_roster_id" label="Pass defense (if captured)" entries={defense} value={defaults.pass_defender_roster_id} />}
    {type === "penalty" && <section className="football-outcome"><h5>Confirmed penalty outcome</h5><div className="game-form-grid"><label className="form-field"><span>Penalty disposition</span><select name="penalty_status" defaultValue={typeof defaults.penalty_status === "string" ? defaults.penalty_status : "accepted"}><option value="accepted">Accepted</option><option value="declined">Declined</option><option value="offsetting">Offsetting</option></select></label><NumberField name="penalty_yards" label="Recorded penalty yards" value={typeof defaults.penalty_yards === "number" ? defaults.penalty_yards : 0} required /></div>{[["automatic_first_down", "Automatic first down"], ["loss_of_down", "Loss of down"], ["no_play", "No ordinary play counted"]].map(([name, label]) => <label className="game-confirmation" key={name}><input name={name} type="checkbox" defaultChecked={defaults[name] === true} /><span>{label}</span></label>)}<p className="game-helper">Confirm the adjudicated result below. This interface does not determine rulebook enforcement.</p></section>}
    {resultTypes.includes(type) && <details className="football-secondary-panel" open><summary>Confirm resulting possession and placement</summary><p>Use yards from the possessing team&apos;s own goal: Own 35 = 35, Opponent 35 = 65. One whole-play return includes its kick; do not record the kick a second time.</p><div className="game-form-grid"><label className="form-field"><span>Resulting possession</span><select name="result_side" defaultValue={typeof defaults.result_side === "string" ? defaults.result_side : fumble ? recovery : type === "penalty" ? state.field_state.possession_side ?? side : opposite(side)}><option value="primary">{game.primary.label}</option><option value="opponent">{game.opponent.label}</option></select></label><NumberField name="result_ball_spot" label="Resulting ball spot (0–100 from own goal)" value={typeof defaults.result_ball_spot === "number" ? defaults.result_ball_spot : 25} required /><NumberField name="result_down" label="Resulting down" min={1} max={4} value={typeof defaults.result_down === "number" ? defaults.result_down : 1} required /><NumberField name="result_distance" label="Resulting distance" min={1} max={100} value={typeof defaults.result_distance === "number" ? defaults.result_distance : 10} required /></div></details>}
  </>;
}
export function buildFootballPlay(game: Pick<Game, "id" | "version">, side: FootballSide, type: FootballPlayType, form: FormData, correction?: FootballPlay): GameCommand {
  const input: Record<string, Json | undefined> = { game_id: game.id, expected_version: game.version, side, play_type: type };
  for (const key of ["roster_id", "receiver_roster_id", "defender_roster_id", "tackler_roster_id", "forced_fumble_roster_id", "recovery_roster_id", "returner_roster_id", "pass_defender_roster_id", "recovery_side", "base_play_type", "penalty_status", "result_side"]) { const value = fieldText(form, key); if (value) input[key] = value; }
  for (const key of ["yards", "return_yards", "kick_yards", "kick_distance", "interception_spot", "penalty_yards", "result_ball_spot", "result_down", "result_distance"]) { if (form.has(key)) input[key] = fieldInteger(form, key); }
  for (const key of ["touchdown", "made", "touchback", "automatic_first_down", "loss_of_down", "no_play"]) if (form.has(key)) input[key] = form.get(key) === "on";
  const assisting = form.getAll("assisting_roster_ids"); if (assisting.length) input.assisting_roster_ids = assisting.map(String);
  if (["field_goal", "extra_point", "two_point"].includes(type)) input.made = form.get("made") === "on";
  if (correction) { input.event_id = correction.id; input.reason = fieldText(form, "reason"); }
  const allowed = new Set(["game_id", "expected_version", "play_type", "side", ...(correction ? ["event_id", "reason"] : []), ...footballFieldsByPlay[type]]);
  return { operation: correction ? "football.play.correct" : "football.play.add", input: Object.fromEntries(Object.entries(input).filter(([key]) => allowed.has(key))) };
}
function FootballScorer({ game, state }: { game: Game; state: FootballGame }) {
  const intent = useGameIntent(), [side, setSide] = useState<FootballSide>(state.field_state.possession_side ?? "primary"), [type, setType] = useState<FootballPlayType>("rush");
  const phaseNotice = state.field_state.phase === "try" ? "Record this touchdown’s extra-point or two-point attempt before the next play." : state.field_state.phase === "kickoff" ? "Record the kickoff and its confirmed receiving placement before scrimmage resumes." : null;
  const active = game.status === "live" && state.period_status === "active", input = { game_id: game.id, expected_version: game.version }, maximum = 4 + (state.overtime_format === "none" ? 0 : state.max_overtime_periods);
  return <section className="football-scorer" aria-label="Football scorer"><h4>Sideline scorer</h4>{phaseNotice && <p className="game-attention">{phaseNotice}</p>}<div className="football-play-buttons">{(["rush", "pass_complete", "pass_incomplete", "sack", "interception", "fumble", "punt_return", "kickoff_return"] as const).map(play => <button type="button" className={`football-play-button${type === play ? " football-selected" : ""}`} key={play} disabled={intent.blocked} onClick={() => setType(play)}>{footballPlayLabels[play]}</button>)}</div><div className="game-form-grid"><label className="form-field"><span>Acting / kicking / penalized team</span><select value={side} onChange={event => setSide(event.target.value as FootballSide)} disabled={intent.blocked}><option value="primary">{game.primary.label}</option><option value="opponent">{game.opponent.label}</option></select></label><label className="form-field"><span>Play type</span><select value={type} onChange={event => setType(event.target.value as FootballPlayType)} disabled={intent.blocked}>{footballPlayTypes.map(play => <option key={play} value={play}>{footballPlayLabels[play]}</option>)}</select></label></div><fieldset className="calendar-fieldset" disabled={!active || intent.blocked}><GameForm key={`play:${type}:${side}:${game.version}`} label={`Record ${footballPlayLabels[type].toLowerCase()}`} build={form => buildFootballPlay(game, side, type, form)}><PlayFields game={game} state={state} side={side} type={type} entries={state.entry_roster} /></GameForm></fieldset>{!active && <p className="game-attention">Start the game and its next period before recording plays.</p>}
    <div className="football-clock-controls">{game.status === "live" && state.period_status !== "active" && state.period_number < maximum && <button type="button" className="button button-primary" disabled={intent.blocked} onClick={() => void intent.send({ operation: "football.period.start", input })}>Start {footballPeriod(state.period_number + 1).toLowerCase()}</button>}{active && <button type="button" className="button button-outline" disabled={intent.blocked} onClick={() => void intent.send({ operation: state.clock_running ? "football.clock.stop" : "football.clock.start", input })}>{state.clock_running ? "Stop clock" : "Start clock"}</button>}<button type="button" className="button button-outline" disabled={intent.pending} onClick={() => intent.refresh()}>Refresh game</button></div>
    {active && !state.clock_running && <details className="football-secondary-panel"><summary>Clock and period boundary</summary><GameForm label="Correct football clock" build={form => { const minutes = fieldInteger(form, "minutes"), seconds = fieldInteger(form, "seconds"); return minutes === null || seconds === null ? null : { operation: "football.clock.set", input: { ...input, clock_ms: (minutes * 60 + seconds) * 1000, reason: fieldText(form, "reason") } }; }}><div className="game-form-grid"><NumberField name="minutes" label="Remaining minutes" max={60} value={Math.floor(state.clock_ms / 60000)} required /><NumberField name="seconds" label="Remaining seconds" max={59} value={Math.floor(state.clock_ms / 1000) % 60} required /></div><label className="form-field"><span>Clock correction reason</span><input name="reason" maxLength={500} required /></label></GameForm>{(state.clock_ms === 0 || state.period_number > 4 && state.overtime_format === "possession") && <GameForm label={`End ${footballPeriod(state.period_number).toLowerCase()}`} confirmation="I reviewed this period boundary and its possession-format policy." build={() => ({ operation: "football.period.end", input })} />}</details>}
    {state.entry_plays.length > 0 && <div className="football-recent-plays"><h5>Recent accepted plays</h5><ol className="football-play-list">{state.entry_plays.slice(-5).map(play => <li key={play.id}><PlayDescription game={game} state={state} play={play} /></li>)}</ol></div>}
  </section>;
}
function FieldControls({ game, state }: { game: Game; state: FootballGame }) { return state.capabilities.operate && game.status === "live" && state.period_status === "active" ? <details className="football-secondary-panel"><summary>Confirm field position and down</summary><GameForm label="Confirm field state" build={form => ({ operation: "football.state.set", input: { game_id: game.id, expected_version: game.version, side: fieldText(form, "side"), ball_spot: fieldInteger(form, "ball_spot"), down: fieldInteger(form, "down"), distance: fieldInteger(form, "distance"), primary_direction: fieldText(form, "primary_direction"), reason: fieldText(form, "reason") } })}><div className="game-form-grid"><label className="form-field"><span>Possessing team</span><select name="side" defaultValue={state.field_state.possession_side ?? "primary"}><option value="primary">{game.primary.label}</option><option value="opponent">{game.opponent.label}</option></select></label><NumberField name="ball_spot" label="Ball spot from possessing team's own goal (0–99)" max={99} value={state.field_state.ball_spot} required /><NumberField name="down" label="Down" min={1} max={4} value={state.field_state.down} required /><NumberField name="distance" label="Yards to gain" min={1} max={100} value={state.field_state.distance} required /><label className="form-field"><span>Primary team's physical direction</span><select name="primary_direction" defaultValue={state.field_state.primary_direction}><option value="increasing">Increasing field direction</option><option value="decreasing">Decreasing field direction</option></select></label></div><label className="form-field"><span>Reason for confirmed placement</span><input name="reason" maxLength={500} required /></label><p className="game-helper">Ordinary play outcomes derive their down and distance. This records an explicit reviewed placement; no officiating rulebook is inferred.</p></GameForm></details> : null; }
function LineupControls({ game, state }: { game: Game; state: FootballGame }) { return state.capabilities.lineups && game.status !== "final" ? <details className="football-secondary-panel"><summary>Football lineups and substitutions</summary><p>{state.lineup_size} players per side · {state.enforce_lineup ? "Complete lineup required" : "Lineup attribution optional"}</p>{(["primary", "opponent"] as const).map(side => <section key={side}><h5>{teamLabel(game, side)}</h5><GameForm label={`Set ${teamLabel(game, side)} lineup`} build={form => ({ operation: "football.lineup.set", input: { game_id: game.id, expected_version: game.version, side, roster_ids: form.getAll("roster_ids").map(String) } })}><div className="football-assists">{state.entry_roster.filter(row => row.side === side && row.active).map(row => <label className="game-confirmation" key={row.id}><input name="roster_ids" type="checkbox" value={row.id} defaultChecked={state.lineups.some(line => line.side === side && line.roster_ids.includes(row.id))} /><span>{athleteLabel(row)}</span></label>)}</div></GameForm><GameForm label={`Record ${teamLabel(game, side)} substitution`} build={form => ({ operation: "football.substitute", input: { game_id: game.id, expected_version: game.version, side, out_roster_id: fieldText(form, "out_roster_id"), in_roster_id: fieldText(form, "in_roster_id") } })}><div className="game-form-grid"><AthleteField name="out_roster_id" label="Outgoing athlete" entries={state.entry_roster.filter(row => row.side === side && state.lineups.some(line => line.side === side && line.roster_ids.includes(row.id)))} /><AthleteField name="in_roster_id" label="Incoming athlete" entries={state.entry_roster.filter(row => row.side === side && !state.lineups.some(line => line.side === side && line.roster_ids.includes(row.id)))} /></div></GameForm></section>)}</details> : null; }
function CorrectionControls({ game, state }: { game: Game; state: FootballGame }) {
  const [selection, setSelection] = useState(""), [type, setType] = useState<FootballPlayType>("rush"), [side, setSide] = useState<FootballSide>("primary");
  if (!state.capabilities.correct || game.status === "final") return null;
  const play = state.entry_plays.find(row => row.id === selection), entries = footballCorrectionEntries(game, state);
  return <details className="football-secondary-panel"><summary>Correct a recorded football play</summary><p>Replacement and reversal preserve the original fact. Later possession and field dependencies are rechecked; unsafe corrections require review.</p><label className="form-field"><span>Accepted play</span><select value={selection} onChange={event => { const row = state.entry_plays.find(item => item.id === event.target.value); setSelection(event.target.value); setType(row && footballPlayTypes.includes(row.type as FootballPlayType) ? row.type as FootballPlayType : "rush"); setSide(row?.side ?? "primary"); }}><option value="">Choose a play</option>{state.entry_plays.map(row => <option key={row.id} value={row.id}>#{row.sequence} · {footballPlayLabels[row.type as FootballPlayType]}</option>)}</select></label>{play && <><div className="game-form-grid"><label className="form-field"><span>Replacement play type</span><select value={type} onChange={event => setType(event.target.value as FootballPlayType)}>{footballPlayTypes.map(key => <option key={key} value={key}>{footballPlayLabels[key]}</option>)}</select></label><label className="form-field"><span>Replacement acting team</span><select value={side} onChange={event => setSide(event.target.value as FootballSide)}><option value="primary">{game.primary.label}</option><option value="opponent">{game.opponent.label}</option></select></label></div><GameForm key={`correction:${play.id}:${type}:${side}:${game.version}`} label="Save football correction" confirmation="I reviewed the replacement and its score, statistics and later field effects." build={form => buildFootballPlay(game, side, type, form, play)}><PlayFields key={`${play.id}:${type}:${side}`} game={game} state={state} side={side} type={type} entries={entries} defaults={play.type === type ? play.payload : {}} /><label className="form-field"><span>Correction reason</span><textarea name="reason" required maxLength={500} rows={2} /></label></GameForm><GameForm label="Reverse football play" confirmation="I reviewed this reversal and its dependent field history." build={form => ({ operation: "football.play.reverse", input: { game_id: game.id, expected_version: game.version, event_id: play.id, reason: fieldText(form, "reason") } })}><label className="form-field"><span>Reversal reason</span><textarea name="reason" required maxLength={500} rows={2} /></label></GameForm></>}</details>;
}
function FootballContent({ game, family }: { game: Game; family: boolean }) {
  if (game.sport_key !== "football") return null;
  const state = game.football;
  if (!state) return game.engine_locked ? <p className="game-notice">Football controls are unavailable. Manual score summaries remain closed for this configured game.</p> : null;
  if (!state.configured) return !family && state.capabilities.configure ? <FootballSetup game={game} /> : null;
  return <section className="football-panel" aria-label="Football game"><div className="football-state-heading"><div><p className="eyebrow">Football</p><h3>{state.period_number === 2 && state.period_status === "ended" ? "Halftime" : footballPeriod(state.period_number)}</h3><p>{humanize(state.period_status)}{game.status === "final" ? " · Final" : ""}</p></div><FootballClock state={state} /></div><div className="football-field"><strong>{state.field_state.possession_side ? `${teamLabel(game, state.field_state.possession_side)} possession` : "Possession awaiting confirmation"}</strong><span>{state.field_state.phase === "try" ? `Touchdown try for ${teamLabel(game, state.field_state.scoring_side!)}` : state.field_state.phase === "kickoff" ? "Kickoff / receiving possession required" : `${footballDown(state.field_state)} · ${footballBallPosition(state.field_state.ball_spot)}`}</span><meter min={0} max={100} value={state.field_state.ball_spot} aria-label="Ball spot from possessing team's own goal" /><small>Line to gain: {footballBallPosition(state.field_state.line_to_gain)} · Drive {state.field_state.drive_number}</small></div><p className="game-helper">Server clock at {new Date(state.clock_observed_at).toISOString().slice(11, 19)} UTC. Refresh for current state. All clock mutations are confirmed by the server.{state.play_clock_seconds ? ` Play-clock foundation: ${state.play_clock_seconds} seconds; automatic operation is unavailable.` : ""}</p>
    {!family && state.capabilities.operate && <FootballScorer game={game} state={state} />}{!family && <><FieldControls game={game} state={state} /><LineupControls game={game} state={state} /><CorrectionControls game={game} state={state} /></>}
    {state.capabilities.stats && <section className="football-box-section"><h3>Football box score</h3><FootballBox game={game} players={state.players} teams={state.teams} /><p className="game-helper">Sacks are excluded from individual passing/rushing attempts; sack loss reduces team net passing yards. Conversion tries do not contribute ordinary offensive yardage. {state.kneel_counts_as_rush ? "Kneels count as rushes under this game's explicit policy." : "Kneels are recorded separately from rushing."} Defensive attribution is shown only where captured.</p></section>}
    {state.plays.length > 0 && <details className="football-secondary-panel" open><summary>Football play by play</summary><ol className="football-play-list">{state.plays.map(play => <li key={play.id} className={play.active ? "" : "football-superseded"}><PlayDescription game={game} state={state} play={play} /></li>)}</ol>{state.more_plays && <p className="game-helper">Showing the latest 500 plays.</p>}</details>}
    {state.drives.length > 0 && <details className="football-secondary-panel"><summary>Drives</summary><ol className="football-play-list">{state.drives.map(drive => <li key={drive.drive_number}><strong>Drive {drive.drive_number} · {teamLabel(game, drive.side)}</strong><span>{footballPeriod(drive.start_period)} {footballClock(drive.start_clock_ms)} · {footballBallPosition(drive.start_ball_spot)} · {drive.play_count} plays</span><span>{drive.end_ball_spot === null ? "In progress" : footballBallPosition(drive.end_ball_spot)}{drive.result ? ` · ${humanize(drive.result)}` : ""}</span></li>)}</ol></details>}
    {!family && state.final_epochs.length > 0 && <details className="football-secondary-panel"><summary>Sealed football results</summary>{state.final_epochs.map(epoch => <section className="football-final-epoch" key={epoch.epoch}><h4>Final {epoch.epoch} · {epoch.current_authoritative ? "Current authoritative result" : "Preserved historical result"}</h4><p>Event cutoff {epoch.event_cutoff} · Roster {epoch.roster_revision}</p><FootballBox game={game} players={epoch.players} teams={epoch.teams} /></section>)}</details>}
  </section>;
}
export function FootballPanel({ game, family = false }: { game: Game; family?: boolean }) { const context = useOptionalGameIntent(); return context ? <FootballContent game={game} family={family} /> : <GameIntentProvider key={game.id} version={game.version}><FootballContent game={game} family={family} /></GameIntentProvider>; }
