"use client";
import Link from "next/link";
import { PrivateDelivery } from "./delivery";
import { physicalBatchScope } from "@/lib/discounts/input";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Json } from "@/lib/supabase/database.types";
import { coverageLabel, eligibleUpgradeMembers, discountDate, discountRecord, type DiscountData, type DiscountMember, type ProductKind } from "@/lib/discounts/contracts";
import { money, minorAmount } from "@/lib/fundraising/contracts";
type Act = (action: string, input: Record<string, Json>) => Promise<Record<string, Json> | null>;
type OneTimeCard = { card_id: string; serial: string; activation_secret: string };
export function DiscountsConsole({ data, organizationId, path }: { data: DiscountData; organizationId?: string; path?: string }) {
 const router = useRouter(), pending = useRef<{ action: string; request_id: string; input: Record<string, Json> } | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [exports, setExports] = useState<OneTimeCard[]>([]), [selected, setSelected] = useState<string[]>([]);
 async function act(action: string, input: Record<string, Json>) {
  if (busy) return null; setBusy(true); setMessage("");
  const previous = pending.current, command = previous && previous.action === action && JSON.stringify(previous.input) === JSON.stringify(input) ? previous : { action, input, request_id: crypto.randomUUID() }; pending.current = command;
  try { const response = await fetch("/app/boss-bucks/discounts/mutate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(command), cache: "no-store" }), value: unknown = await response.json();
   if (!response.ok || !discountRecord(value) || value.ok !== true) { setMessage(discountRecord(value) && typeof value.error === "string" ? value.error : "The membership change could not be confirmed."); if (response.status < 500) pending.current = null; return null; }
   pending.current = null; setMessage(value.replayed ? "The original request is confirmed. One-time secrets cannot be recovered from a replay." : "The membership request is confirmed.");
   if (action === "batch.create" && Array.isArray(value.one_time_cards)) { const cards = value.one_time_cards.filter((v): v is Record<string, Json> => discountRecord(v) && typeof v.card_id === "string" && typeof v.serial === "string" && typeof v.activation_secret === "string").map(v => ({ card_id: String(v.card_id), serial: String(v.serial), activation_secret: String(v.activation_secret) })); setExports(cards); setSelected(cards.map(c => c.card_id)); }
   router.refresh(); return value;
  } catch { setMessage("The request could not be confirmed. Retry the same action safely."); return null; } finally { setBusy(false); }
 }
 if (data.restricted) return <p role="status">This membership or inventory scope is restricted.</p>;
 if (data.unavailable) return <p role="status">Boss Bucks Discounts is temporarily unavailable.</p>;
 return <div className="discounts-console"><p>Discounts membership provides benefit access. The Wallet contains earned fundraising value. Neither creates the other.</p><p role="status" aria-live="polite">{message}</p>
 {data.mode === "consumer" ? <>
  <section aria-labelledby="discount-memberships"><h2 id="discount-memberships">Your Discounts memberships</h2>{data.memberships.length ? data.memberships.map(m => <DigitalCard key={m.id} membership={m} />) : <p>No claimed Discounts membership is available. You can activate a card or claim a membership below.</p>}</section>
  <section className="discount-panel"><h2>Claim your membership</h2><p>Sign in to the intended Boss account before claiming. A claim never merges accounts by email or phone.</p><form action={async form => { await act("membership.claim", { claim_secret: String(form.get("claim_secret")), ...(form.get("household") ? { household_id: String(form.get("household")) } : {}) }); }} className="discount-form"><label>One-time membership claim code<input name="claim_secret" type="password" autoComplete="off" required minLength={64} maxLength={64} /></label><HouseholdChoice households={data.households} /><button disabled={busy} className="button button-primary">Claim membership</button></form></section>
  <section className="discount-panel"><h2>Activate a physical card</h2><p>Your serial is a display identity. Activation also requires the private code supplied with your card. The included digital trial begins on successful activation.</p><form action={async form => { await act("card.claim", { serial: String(form.get("serial")).trim().toUpperCase(), activation_secret: String(form.get("activation_secret")).trim(), ...(form.get("household") ? { household_id: String(form.get("household")) } : {}) }); }} className="discount-form"><label>Card serial<input required name="serial" maxLength={36} autoComplete="off" /></label><label>Private activation code<input required name="activation_secret" type="password" minLength={64} maxLength={64} autoComplete="off" /></label><HouseholdChoice households={data.households} /><button disabled={busy} className="button button-primary">Activate card</button></form></section>
  <section><h2>Memberships &amp; coverage upgrades</h2>{data.catalog.length ? <div className="discount-grid">{data.catalog.map(p => <article key={p.revision_id} className="discount-panel"><h3>{p.name}</h3><p>{money(p.price_minor, p.currency)}{p.kind.includes("upgrade") ? " additional" : ""}</p><p>{coverageLabel(p.tier, p.country, p.region, p.market)}</p>{p.term_days && <p>Configured term: {p.term_days} days.</p>}{p.trial_enabled && <p>Free digital trial: {p.trial_days} days.</p>}{p.gift_enabled && <p>A verified USD contribution of more than $25, at least $25.01, qualifies for the configured supporter gift.</p>}<p>{p.payment_available ? "Canonical payment checkout is available." : "Payment checkout is unavailable. No purchase or paid upgrade has been issued."}</p>{path && p.trial_enabled && <button disabled={busy} className="button button-primary" onClick={() => act("trial.start", { path, revision_id: p.revision_id })}>Start {p.trial_days}-day free trial</button>}{organizationId && p.sale_enabled && !p.kind.includes("upgrade") && <form className="discount-form" action={async form => { const address = p.fulfillment_type === "shipping" ? Object.fromEntries(["recipient","line1","line2","city","region","postal_code","country"].map(k => [k,String(form.get(`delivery_${k}`) ?? "").trim()]).filter(([,v]) => v)) : null; await act("order.create", { organization_id: organizationId, revision_id: p.revision_id, quantity: 1, method: "card", ...(path ? { path } : {}), ...(p.subject_type === "household" ? { household_id: String(form.get("household")) } : {}), ...(address ? { address } : {}) }); }}>
{p.subject_type === "household" && <label>Explicit household<select required name="household"><option value="">Select your authorized household</option>{data.households.map(h => <option key={h.id} value={h.id}>{h.name}</option>)}</select></label>}{p.fulfillment_type === "shipping" && <DeliveryFields />}<button className="button button-outline" disabled={busy || !p.payment_available}>Continue to membership checkout</button></form>}{p.kind.includes("upgrade") && <form className="discount-form" action={async form => { await act("order.create", { organization_id: organizationId ?? "", revision_id: p.revision_id, quantity: 1, method: "card", base_source_id: String(form.get("base")), ...(p.subject_type === "household" ? { household_id: eligibleUpgradeMembers(data.memberships,p).find(m => m.base_source_id === String(form.get("base")))?.household_id ?? "" } : {}) }); }}><label>Underlying membership<select name="base" required>{eligibleUpgradeMembers(data.memberships,p).map(m => <option key={m.id} value={m.base_source_id!}>{m.name}: {m.effective.tier}</option>)}</select></label><p>Coverage upgrades co-terminate with the underlying configured term. No proration or term extension is assumed.</p><button disabled={busy || !p.payment_available || eligibleUpgradeMembers(data.memberships,p).length === 0} className="button button-outline">Continue to upgrade checkout</button></form>}</article>)}</div> : <p>No approved product configuration is available in this context.</p>}</section>
  <section><h2>Purchase &amp; claim status</h2>{data.orders.length ? data.orders.map(o => <article key={o.id} className="discount-panel"><p>{money(o.total_minor, o.currency)} · {o.quantity} product(s) · {o.state.replaceAll("_", " ")}</p>{o.state === "payment_pending" && <button disabled={busy} className="button button-outline" onClick={() => act("order.cancel", { order_id: o.id })}>Cancel unsubmitted checkout</button>}</article>) : <p>No membership orders for your account.</p>}</section>
 </> : <>
  {data.can_manage_products && <ProductAdmin data={data} organizationId={organizationId} busy={busy} act={act} />}
  {data.can_manage_campaigns && <CampaignProducts data={data} busy={busy} act={act} />}{data.statistics && <section className="discount-panel"><h2>Membership campaign summary</h2><p>Trials started: {data.statistics.trials_started} · Gift sources: {data.statistics.gift_sources} · Gifts claimed: {data.statistics.gift_claimed}</p>{data.statistics.fundraising_credits?.map(c => <p key={c.currency}>Verified organization fundraising credit: {money(c.amount_minor,c.currency)}</p>)}</section>}{data.fundraiser_report && <section className="discount-panel"><h2>{data.fundraiser_report.name}: product fundraising</h2><p>Verified fundraising credit: {money(data.fundraiser_report.fundraising_credit_minor,data.fundraiser_report.currency)}</p>{Object.entries(data.fundraiser_report.product_sales).map(([kind,n]) => <p key={kind}>{kind.replaceAll("_"," ")}: {n} verified sales</p>)}<h3>Assigned physical inventory</h3>{Object.entries(data.fundraiser_report.inventory).map(([state,n]) => <p key={state}>{state}: {n}</p>)}</section>}
  {data.can_inventory && organizationId && <section className="discount-panel"><h2>Physical card inventory</h2><form className="discount-form" action={async form => { await act("batch.create", { ...physicalBatchScope(organizationId, String(form.get("owner")), form.get("unassigned") === "on"), revision_id: String(form.get("revision")), owner_type: String(form.get("owner")), ...(form.get("owner") === "campaign" ? { campaign_id: String(form.get("batch_campaign")) } : {}), name: String(form.get("name")), quantity: Number(form.get("quantity")), controlled: form.get("controlled") === "on" }); }}><label>Approved physical product<select name="revision" required>{(data.can_manage_products ? data.revisions.filter(r => r.active && data.products.some(p => p.id === r.product_id && p.kind === "physical")).map(r => ({ revision_id: r.id, name: data.products.find(p => p.id === r.product_id)?.name, trial_days:r.trial_days })) : data.catalog.filter(p => p.kind === "physical")).map(r => <option key={r.revision_id} value={r.revision_id}>{r.name} · {r.trial_days}-day digital trial</option>)}</select></label><label>Inventory owner<select name="owner"><option value="organization">This organization</option><option value="campaign">Selected campaign</option>{data.can_manage_products && <option value="platform">Platform stock in this organization</option>}</select></label>{data.can_manage_products && <label className="discount-check"><input type="checkbox" name="unassigned" />Keep platform stock unassigned (requires a platform stock revision)</label>}<label>Campaign owner (campaign batches only)<select name="batch_campaign"><option value="">Select campaign</option>{data.campaigns.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Batch name<input required name="name" maxLength={100} /></label><label>Cards in this operation<input required name="quantity" type="number" min={1} max={1000} defaultValue={10} /></label><label className="discount-check"><input type="checkbox" name="controlled" />Controlled non-production batch</label><p>Up to 1,000 cards per operation. Additional batches support larger inventory.</p><button disabled={busy} className="button button-primary">Create card batch</button></form>
   {exports.length > 0 && <section className="discount-export"><h3>One-time controlled print handoff</h3><p>Private activation codes are held only in this page&apos;s memory. Reloading discards them. Normal inventory reads cannot recover them.</p><button className="button button-outline" onClick={() => { const csv = ["serial,activation_code", ...exports.map(c => `${c.serial},${c.activation_secret}`)].join("\n"), url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })), link = document.createElement("a"); link.href = url; link.download = "boss-bucks-private-print.csv"; link.click(); URL.revokeObjectURL(url); }}>Download privileged print handoff</button><button className="button button-outline" onClick={() => setExports([])}>Discard private codes</button>{exports.length <= 10 && exports.map(c => <div key={c.card_id}><p>{c.serial} · Activation code concealed</p><button disabled={busy} className="button button-outline" onClick={() => act("card.claim", { serial: c.serial, activation_secret: c.activation_secret })}>Activate this card to my signed-in account</button></div>)}</section>}
   {data.batches.map(b => <article key={b.id}><h3>{b.name}</h3><p>{b.quantity} cards · {b.status} {b.controlled ? "· Controlled non-production" : ""}</p><p>{Object.entries(b.counts).map(([state, n]) => `${state}: ${n}`).join(" · ")}</p><button disabled={busy || Object.keys(b.counts).some(k => !["void", "replaced", "expired"].includes(k))} className="button button-outline" onClick={() => act("batch.archive", { batch_id: b.id })}>Archive retired batch</button></article>)}
   <fieldset><legend>Select cards for one bulk operation</legend>{data.cards.map(c => <label className="discount-check" key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={event => setSelected(previous => event.target.checked ? [...previous, c.id] : previous.filter(id => id !== c.id))} />{c.serial} · {c.state}{c.claimed ? " · Claimed" : ""}</label>)}</fieldset>
   <form className="discount-form" action={async form => { const action = String(form.get("action")); await act(action, { organization_id: organizationId, card_ids: selected, ...(form.get("campaign") ? { campaign_id: String(form.get("campaign")) } : {}), ...(form.get("fundraiser") ? { fundraiser_id: String(form.get("fundraiser")) } : {}) }); }}><label>Bulk action<select name="action"><option value="cards.print">Confirm printed / move to inventory</option><option value="cards.assign">Assign unsold inventory</option><option value="cards.return">Return unsold assignment</option><option value="cards.void">Void controlled / unsupported credential</option></select></label><label>Campaign for assignment<select name="campaign"><option value="">No campaign</option>{data.campaigns.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Fundraiser for assignment<select name="fundraiser"><option value="">No participant allocation</option>{data.fundraisers.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button disabled={busy || selected.length === 0} className="button button-primary">Apply selected card operation</button></form>
   <details><summary>Replace a claimed physical card</summary><form className="discount-form" action={async form => { await act("card.replace", { card_id: String(form.get("old")), replacement_card_id: String(form.get("replacement")), reason: String(form.get("reason")) }); }}><label>Existing claimed card<select name="old">{data.cards.filter(c => c.claimed && ["active", "claimed"].includes(c.state)).map(c => <option key={c.id} value={c.id}>{c.serial}</option>)}</select></label><label>Eligible replacement inventory<select name="replacement">{data.cards.filter(c => !c.claimed && ["inventory", "printed"].includes(c.state)).map(c => <option key={c.id} value={c.id}>{c.serial}</option>)}</select></label><label>Reason<select name="reason"><option value="lost">Lost</option><option value="damaged">Damaged</option><option value="compromised">Compromised</option></select></label><button disabled={busy} className="button button-outline">Replace credential, preserve membership</button></form></details>
  </section>}
  {data.can_fulfillment && <section><h2>Product fulfillment</h2>{data.fulfillments.length ? data.fulfillments.map(f => <article className="discount-panel" key={f.id}><p>{f.fulfillment_type} · {f.state.replaceAll("_", " ")}</p><PrivateDelivery organizationId={organizationId} orderId={f.order_id} />{f.state === "awaiting_inventory" ? <button disabled={busy} className="button button-outline" onClick={() => act("fulfillment.retry", { order_id: f.order_id })}>Retry inventory allocation</button> : <form className="discount-form" action={async form => { await act("fulfillment.status", { fulfillment_id: f.id, expected_version: f.version, state: String(form.get("state")) }); }}><label>Next delivery state<select name="state">{(f.state === "allocated" ? [f.fulfillment_type === "pickup" ? "ready_for_pickup" : "packed"] : f.state === "packed" ? ["shipped"] : ["delivered"]).map(s => <option key={s} value={s}>{s.replaceAll("_", " ")}</option>)}</select></label><button disabled={busy || ["delivered", "canceled"].includes(f.state)} className="button button-outline">Confirm fulfillment state</button></form>}</article>) : <p>No canonical paid physical orders await fulfillment.</p>}</section>}
  {data.can_financial_view && <section><h2>Product sale records</h2>{data.financial_statistics?.map(t => <p key={t.currency}>Digital gross: {money(t.digital_sales_minor,t.currency)} · Physical gross: {money(t.physical_sales_minor,t.currency)} · Original-item corrections: {money(t.refunded_products_minor,t.currency)}</p>)}{data.orders.length ? data.orders.map(o => <OrderRecord key={o.id} order={o} organizationId={organizationId} canRefund={!!data.can_refund} busy={busy} act={act} />) : <p>No product payment successes or orders in this report.</p>}</section>}
 </>}
 <DiscountPagination data={data} organizationId={organizationId} path={path} />
 </div>;
}
export function DigitalCard({ membership: m }: { membership: DiscountMember }) { const e = m.effective; return <article className={`discount-digital-card${e.available ? "" : " discount-card-inactive"}`}><p className="eyebrow">THE BOSS · BOSS BUCKS DISCOUNTS</p><h3>{m.display_name ?? "Claimed member"}</h3><p><strong>{e.tier ? e.tier.toUpperCase() : "NO ACTIVE DIGITAL ACCESS"}</strong> · {e.state.replaceAll("_", " ")}</p><p>{coverageLabel(e.tier, e.country, e.region, e.market)}</p><p>Source: {e.source?.replaceAll("_", " ") ?? "Ended or unavailable"}</p><p>{discountDate(e.starts_at)} through {discountDate(e.ends_at)} (UTC)</p><p className="discount-display-id">{m.display_id}</p><p>{m.subject_type === "household" ? "Configured household product" : "Personal membership"}</p>{m.cards.map(c => <p key={c.id}>Physical card {c.serial}: {c.state}{c.valid ? " · Valid physical credential" : " · Unavailable physical credential"}</p>)}<details><summary>Membership history</summary>{m.sources.map((s, n) => <p key={n}>{s.kind.replaceAll("_", " ")} · {s.tier} · {discountDate(s.starts_at)} to {discountDate(s.ends_at)}{s.revoked ? " · Source revoked" : ""}</p>)}</details><p>Merchant offers and redemption are not available in this phase.</p></article>; }
function CampaignProducts({ data, busy, act }: { data: DiscountData; busy: boolean; act: Act }) { return <section className="discount-panel"><h2>Campaign membership options</h2><p>Digital membership and physical card sales remain independent from direct support and Money Board.</p><form className="discount-form" action={async form => { await act("campaign.configure", { campaign_id: String(form.get("campaign")), revision_id: String(form.get("revision")), trial_enabled: form.get("trial") === "on", gift_enabled: form.get("gift") === "on", sale_enabled: form.get("sale") === "on", ...(form.get("end") ? { ends_at: new Date(String(form.get("end"))).toISOString() } : {}) }); }}><label>Campaign<select required name="campaign">{data.campaigns.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Approved product revision<select required name="revision">{data.revisions.filter(r => r.active).map(r => <option key={r.id} value={r.id}>{data.products.find(p => p.id === r.product_id)?.name ?? "Approved product"} · {r.trial_days ?? "No"}-day trial · {r.tier}</option>)}</select></label><label className="discount-check"><input type="checkbox" name="trial" />Allow configured free trial</label><label className="discount-check"><input type="checkbox" name="gift" />Allow configured supporter gift, strictly greater than $25</label><label className="discount-check"><input type="checkbox" name="sale" />Allow approved product sale</label><label>End configuration at (optional)<input name="end" type="datetime-local" /></label><button disabled={busy} className="button button-primary">Enable campaign product options</button></form>{data.campaign_products.map(b => <div key={b.id}><p>{data.campaigns.find(c => c.id === b.campaign_id)?.name ?? "Campaign"} · {b.status} · Trial {b.trial_enabled ? "enabled" : "disabled"} · Gift {b.gift_enabled ? "enabled" : "disabled"} · Sale {b.sale_enabled ? "enabled" : "disabled"}</p>{b.status === "active" && <button disabled={busy} className="button button-outline" onClick={() => act("campaign.end", { binding_id: b.id })}>End these product options</button>}</div>)}</section>; }
function ProductAdmin({ data, organizationId, busy, act }: { data: DiscountData; organizationId?: string; busy: boolean; act: Act }) {
 const [kind, setKind] = useState<ProductKind>("digital"), [productId, setProductId] = useState(data.products[0]?.id ?? ""); const product = data.products.find(p => p.id === (productId || data.products[0]?.id)), price = product?.kind === "state_upgrade" ? "19.99" : product?.kind === "nationwide_upgrade" ? "39.00" : "25.00";
 return <section className="discount-panel"><h2>Approved product revisions</h2><details><summary>Create a narrow Boss Bucks product</summary><form className="discount-form" action={async form => { await act("product.create", { code: String(form.get("code")), name: String(form.get("name")), kind }); }}><label>Product name<input required name="name" maxLength={100} /></label><label>Stable product code<input required name="code" pattern="[a-z][a-z0-9_]{1,63}" /></label><label>Product type<select value={kind} onChange={e => setKind(e.target.value as ProductKind)}>{(["digital", "physical", "state_upgrade", "nationwide_upgrade"] as const).map(k => <option key={k} value={k}>{k.replaceAll("_", " ")}</option>)}</select></label><button disabled={busy} className="button button-outline">Create product identity</button></form></details>
 <details><summary>Create immutable pricing &amp; benefit revision</summary><form className="discount-form" action={async form => {
  const paid = form.get("sale") === "on", productPrice = minorAmount(String(form.get("price"))); if (productPrice === null) return;
  const input: Record<string, Json> = { product_id: productId || data.products[0]?.id || "", membership_product_id: String(form.get("membership_product")), ...(form.get("global_stock") === "on" && !paid ? {} : { organization_id: organizationId ?? "" }), subject_type: String(form.get("subject")), claim_policy: form.get("subject") === "household" ? "household_primary_contact" : "authenticated_self", currency: "USD", price_minor: productPrice, country: String(form.get("country")).toUpperCase(), region: String(form.get("region")), market: String(form.get("market")), tier: product?.kind === "state_upgrade" ? "state" : product?.kind === "nationwide_upgrade" ? "nationwide" : "local", sale_channels: paid ? ["direct", "fundraising"] : [], trial_enabled: form.get("trial") === "on", gift_enabled: form.get("gift") === "on", fulfillment_type: product?.kind === "physical" ? String(form.get("fulfillment")) : "digital", starts_at: new Date(String(form.get("start"))).toISOString() };
  for (const [field, name] of [["term_days", "term"], ["trial_days", "trial_days"], ["card_validity_days", "validity_days"]]) if (form.get(name)) input[field] = Number(form.get(name));
  if (form.get("end")) input.ends_at = new Date(String(form.get("end"))).toISOString();
  if (product?.kind === "physical") input.validity_anchor = String(form.get("anchor"));
  if (paid) { input.settlement_policy_id = String(form.get("policy")); for (const [field, name] of [["organization_credit_minor", "credit"], ["platform_retained_minor", "retained"], ["product_cost_minor", "cost"]]) { const value = String(form.get(name)); input[field] = value === "0" || value === "0.00" ? 0 : minorAmount(value) ?? -1; } }
  await act("revision.create", input);
 }}>
 <label>Product<select required value={productId || data.products[0]?.id || ""} onChange={e => setProductId(e.target.value)}>{data.products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Canonical digital membership product<select required name="membership_product">{data.products.filter(p => p.kind === "digital").map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="discount-check"><input name="global_stock" type="checkbox" />Platform stock template (no paid channels)</label><label>Membership subject policy<select name="subject"><option value="person">Explicit signed person</option><option value="household">Explicit household primary contact</option></select></label><p>A household product does not create guardian or organization authority.</p><label>Price in USD<input required name="price" key={price} defaultValue={price} inputMode="decimal" /></label><label>Configured paid/gift term in days<input type="number" name="term" min={1} max={3660} /></label><label>Free digital trial duration<select name="trial_days"><option value="">No trial</option>{[30, 60, 90].map(n => <option key={n} value={n}>{n} days</option>)}</select></label><label>Country<input required name="country" maxLength={2} pattern="[A-Za-z]{2}" /></label><label>State / region<input required name="region" maxLength={80} /></label><label>Configured home market<input required name="market" maxLength={100} /></label><label>Effective start<input required name="start" type="datetime-local" /></label><label>Effective end (optional)<input name="end" type="datetime-local" /></label><label className="discount-check"><input type="checkbox" name="trial" />Allow free trial</label><label className="discount-check"><input type="checkbox" name="gift" />Allow explicitly termed supporter gift</label><label className="discount-check"><input type="checkbox" name="sale" />Allow paid direct and fundraising sales</label>
 <fieldset><legend>Explicit paid sale economics</legend><label>Organization fundraising credit in USD<input name="credit" inputMode="decimal" /></label><label>Platform retained amount in USD<input name="retained" inputMode="decimal" /></label><label>Explicit product cost in USD<input name="cost" inputMode="decimal" /></label><label>Approved product settlement policy<select name="policy"><option value="">No policy configured</option>{data.settlement_policies.map(p => <option key={p.id} value={p.id}>Revision {p.revision} · {p.organization_basis_points / 100}% organization · Processor fee owner {p.processor_fee_owner}</option>)}</select></label><p>Organization credit, retained amount and product cost must equal the consumer price. Missing paid configuration keeps sales unavailable.</p></fieldset>
 {product?.kind === "physical" && <fieldset><legend>Physical credential policy</legend><label>Validity starts on<select name="anchor"><option value="activation">Successful activation</option><option value="print">Print confirmation</option><option value="sale">Verified sale</option></select></label><label>Physical validity days<input required name="validity_days" type="number" min={1} max={3660} /></label><label>Fulfillment<select name="fulfillment"><option value="pickup">Organization pickup</option><option value="shipping">Private shipping</option></select></label></fieldset>}
 <button disabled={busy || data.products.length === 0} className="button button-primary">Save immutable revision</button></form></details>
 {data.revisions.map(r => <article key={r.id}><h3>{data.products.find(p => p.id === r.product_id)?.name}</h3><p>{money(r.price_minor, r.currency)} · {r.tier} · {r.trial_days ?? "No"}-day trial · {r.term_days ? `${r.term_days}-day paid/gift term` : "No paid/gift term"} · {r.active ? "Active" : "Disabled"}</p><button disabled={busy} className="button button-outline" onClick={() => act("revision.status", { revision_id: r.id, state: r.active ? "disabled" : "active" })}>{r.active ? "Disable this revision" : "Activate approved revision"}</button></article>)}
 </section>;
}

function HouseholdChoice({ households }: { households: DiscountData["households"] }) { return <label>Membership subject<select name="household"><option value="">My personal membership</option>{households.map(h => <option key={h.id} value={h.id}>{h.name} (configured household products only)</option>)}</select></label>; }

function OrderRecord({ order, organizationId, canRefund, busy, act }: { order: DiscountData["orders"][number]; organizationId?: string; canRefund: boolean; busy: boolean; act: Act }) {
 const [items, setItems] = useState<string[]>([]);
 return <article className="discount-panel"><p>{money(order.total_minor, order.currency)} · {order.quantity} product(s) · {order.state.replaceAll("_", " ")}</p><Link className="button button-outline" href={`/app/boss-bucks/discounts?view=organization&org=${organizationId}&order=${order.id}`}>View original order items</Link>{order.items && order.items.length > 0 && <><ul>{order.items.map(i => <li key={i.id}><label className="discount-check"><input type="checkbox" disabled={!canRefund || i.corrected || busy} checked={items.includes(i.id)} onChange={e => setItems(old => e.target.checked ? [...old, i.id] : old.filter(id => id !== i.id))} />{i.kind.replaceAll("_", " ")} · {money(i.price_minor, order.currency)} · {i.corrected ? "Corrected" : "Original item"}</label></li>)}</ul>{canRefund && <form className="discount-form" action={async form => { await act("order.refund", { order_id: order.id, item_ids: items, reason: String(form.get("reason")) }); }}><label>Original-item refund reason<input required name="reason" maxLength={254} /></label><p>This prepares a refund of the selected original items through the original payment rails. Provider verification is required before a correction is applied.</p><button disabled={busy || items.length === 0} className="button button-outline">Prepare original-item refund</button></form>}</>}</article>;
}
function DiscountPagination({ data, organizationId, path }: { data: DiscountData; organizationId?: string; path?: string }) {
 const lists = data.mode === "consumer" ? [["memberships", data.memberships, 50] as const] : [["cards", data.cards, 100] as const, ["batches", data.batches, 50] as const, ["orders", data.orders, 100] as const, ["fulfillments", data.fulfillments, 100] as const];
 return <nav aria-label="More membership records">{lists.filter(([,rows,limit]) => rows.length === limit).map(([label,rows]) => <Link className="button button-outline" key={label} href={`/app/boss-bucks/discounts?view=${data.mode}${organizationId ? `&org=${organizationId}` : ""}${path ? `&path=${path}` : ""}&before=${rows.at(-1)!.id}`}>More {label}</Link>)}</nav>;
}

function DeliveryFields() { return <fieldset><legend>Private shipping destination</legend><p>Only authorized fulfillment staff can retrieve these details. They never appear on the public fundraiser page.</p>{[["recipient","Recipient"],["line1","Address line 1"],["line2","Address line 2 (optional)"],["city","City"],["region","State / region"],["postal_code","Postal code"],["country","Country"]].map(([key,label]) => <label key={key}>{label}<input name={`delivery_${key}`} required={key !== "line2"} maxLength={200} autoComplete="off" /></label>)}</fieldset>; }
