import Image from "next/image";
import Link from "next/link";
import ApprovedHeader from "@/components/ApprovedHeader";
import ApprovedFooter from "@/components/ApprovedFooter";
import home from "../approvedHome.module.css";
import s from "./engage.module.css";
export const metadata={title:"Boss Engage | Engage Like a Boss",description:"Connect registrations, rosters, schedules and team communication. Bring your family’s schedules together across schools, clubs and organizations with the Boss Family Hub."};
function Art({crop,alt,className,clip}:{crop:string;alt?:string;className?:string;clip?:'hero'|'phone'}){return <svg viewBox={crop} preserveAspectRatio="xMidYMid slice" role={alt?"img":undefined} aria-label={alt} aria-hidden={alt?undefined:true} className={className}>{clip&&<defs><clipPath id={'engage-'+clip}>{clip==='hero'?<><path d="M371 205H689Q704 205 704 220V462H719V479H314V463H354V220Q354 205 371 205Z"/><rect x="674" y="254" width="110" height="243" rx="19"/></>:<rect x="562" y="1061" width="185" height="373" rx="29"/>}</clipPath></defs>}<image href="/design/engage-approved.png" width="793" height="1983" clipPath={clip?'url(#engage-'+clip+')':undefined}/></svg>}
function Icon({kind}:{kind:string}){return <svg viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='calendar'?<><rect x="4" y="6" width="24" height="23" rx="2"/><path d="M4 13h24M10 2v8m12-8v8M10 18h3m6 0h3m-12 6h3m6 0h3"/></>:kind==='chat'?<path d="M29 14c0 8-9 13-17 10l-8 4 2-8C-2 9 8 1 17 3c7 0 12 4 12 11Z"/>:kind==='document'?<><path d="M7 2h12l7 7v21H7ZM19 2v8h7M12 16h9m-9 5h9"/></>:kind==='bell'?<><path d="M6 23h20l-3-5v-7a7 7 0 0 0-14 0v7l-3 5ZM13 28h6"/></>:<><circle cx="16" cy="9" r="4"/><path d="M9 28v-8c0-7 14-7 14 0v8H9Z"/>{kind!=='person'&&<><circle cx="5" cy="11" r="3"/><circle cx="27" cy="11" r="3"/><path d="M2 27v-8h4m24 8v-8h-4"/></>}</>}</svg>}
const features=[['people','Registration + rosters','Get athletes registered and keep rosters organized across every team.'],['calendar','Schedules + calendars','Create and share schedules that everyone can access and rely on.'],['chat','Messages + updates','Keep teams, parents and coaches informed in one place.'],['document','Documents + forms','Share important documents and collect forms without the back and forth.']];
export default function Page(){return <div className={home.home}><a className={home.skipLink} href="#main-content">Skip to content</a><ApprovedHeader/><main id="main-content" className={s.page}>
<section className={s.hero} aria-labelledby="engage-title"><Image src="/images/approved/engage-hero.png" alt="Coaches and young soccer players in BOSS jerseys at an outdoor sports field" fill priority sizes="100vw" className={s.heroPhoto}/><div className={s.heroCopy}><p className={s.eyebrow}>BOSS ENGAGE</p><h1 id="engage-title">Engage<br/>Like a <span>Boss.</span></h1><p className={s.heroLead}>One organization.<br/>Every team. Everyone connected.</p><p className={s.heroDescription}>Bring registrations, rosters, schedules and team communication into one connected experience.</p><div className={s.actions}><a href="#team-operations" className={s.button}>Explore Boss Engage</a><a href="#family-view" className={s.outline}>See the Family View</a></div></div><figure className={s.heroDevices}><Art crop="310 200 478 300" clip="hero" alt="Illustrative Boss Engage organization dashboard and mobile team schedule"/><figcaption>Illustrative product preview. Platform vision.</figcaption></figure></section>
<section id="team-operations" className={s.features} aria-labelledby="features-title"><h2 id="features-title">Less chasing. <span>More coaching.</span></h2><div className={s.featureGrid}>{features.map(([kind,title,copy])=><article key={title}><div className={s.circle}><Icon kind={kind}/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className={s.calendar} aria-labelledby="calendar-title"><figure><Art crop="11 745 496 314" alt="Illustrative organization calendar with all-team and individual-team views"/><figcaption>Illustrative calendar preview.</figcaption></figure><div className={s.calendarCopy}><h2 id="calendar-title">Every team has<br/>its space. <span>You keep<br/>the big picture.</span></h2><p>Manage multiple programs while keeping each team focused on what matters to them.</p><ul>{[['Organization-wide calendar','See every event at a glance.'],['Team-specific schedules and chats','Each team has the space they need.'],['Shared events without duplicate entries','Create once and keep everyone in sync.']].map(([title,copy])=><li key={title}><b aria-hidden="true">✓</b><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ul></div></section>
<section id="family-view" className={s.family} aria-labelledby="family-title"><Art crop="346 1083 214 355" className={s.familyPhoto} alt="A father with a teenage volleyball player and younger baseball player, wearing BOSS apparel"/><div className={s.familyCopy}><h2 id="family-title">Multiple kids.<br/>Multiple teams.<br/>Multiple organizations.<br/><span>One Family Hub.</span></h2><p className={s.familyLead}>Bring your family’s schedules together across schools, clubs and organizations.</p><div className={s.familyFeatures}>{[['person','Filter by child','Focus on one child’s schedule.'],['calendar','Filter by team or organization','School, club or league in one view.'],['bell','See the whole family','Bring everyone’s week together.']].map(([kind,title,copy])=><article key={kind}><div className={s.circle}><Icon kind={kind}/></div><h3>{title}</h3><p>{copy}</p></article>)}</div><Link href="/family-hub" className={s.button}>Explore Family Hub</Link></div><figure className={s.familyPhone}><Art crop="560 1058 190 380" clip="phone" alt="Illustrative Family Hub calendar showing Emma’s school volleyball and Noah’s community baseball club, with child and organization filters"/><figcaption>Illustrative Family Hub preview.</figcaption></figure></section>
<section className={s.communication} aria-labelledby="communication-title"><h2 id="communication-title">Keep the right people <span>in the loop.</span></h2><div className={s.communicationGrid}><Art crop="34 1486 344 182" alt="A coach talking with teenage basketball players wearing BOSS jerseys" className={s.basketballPhoto}/><div><p className={s.communicationLead}>Team announcements, conversations and reminders help coaches and families stay connected.</p><ul className={s.communicationFeatures}>{[['chat','Team communication'],['people','Volunteer coordination'],['calendar','Event updates']].map(([kind,title])=><li key={kind}><Icon kind={kind}/><h3>{title}</h3></li>)}</ul><div className={s.messagePreview} aria-label="Illustrative team announcement"><div className={s.messageMeta}><span className={s.avatar} aria-hidden="true">CT</span><div><strong>Coach Taylor</strong><small>Team announcement · Example</small></div></div><h3>Practice moved to Court 2</h3><p>Due to facility maintenance, tomorrow’s practice will be at Court 2. Same time, 5:00 PM.</p><div className={s.rsvp} aria-label="Illustrative RSVP choices, not interactive"><strong>RSVP</strong><span>Will you be there?</span><div><b>✓ Yes</b><b>✓ No</b><b>Maybe</b></div></div></div></div></div></section>
<section className={s.ecosystem} aria-labelledby="ecosystem-title"><h2 id="ecosystem-title">Your team. <span>A bigger Boss ecosystem.</span></h2><p>Connect team life with fundraising, family value and your organization’s next opportunity.</p><div className={s.ecosystemGrid}>{[['Fundraising','Power your programs with a signature fundraising experience.','/fundraising','Explore Fundraising','32 1745 121 81','Girls in BOSS cheerleading uniforms with pom-poms'],['Boss Bucks','Give families more ways to support while creating real value.','/boss-bucks','Explore Boss Bucks','293 1745 111 81','Illustrative Boss Bucks mobile app'],['Team stores','Equip your teams and show your pride.','/request-information','Explore Team Stores','536 1745 111 81','BOSS team merchandise and a single-B cap']].map(([title,copy,href,label,crop,alt])=><article key={title}><Art crop={crop} alt={alt}/><div><h3>{title}</h3><p>{copy}</p><Link href={href}>{label} <span aria-hidden="true">›</span></Link></div></article>)}</div><p className={s.vision}>Platform vision. Features and availability vary by program.</p></section>
<section className={s.finalCta}><h2>Engage Like a <span>Boss.</span></h2><p>Tell us about your organization. Let’s build the right starting point.</p><Link href="/fundraising/get-started" className={s.button}>Get Started <span aria-hidden="true">›</span></Link></section>
</main><ApprovedFooter/></div>}
