"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import type { Json } from "@/lib/supabase/database.types";
import { bucksMoney as money } from "@/lib/boss-bucks/money";
import type { BucksCommand, BucksData, WalletActivity } from "@/lib/boss-bucks/contracts";

export function BucksConsole({ data, organizationId, walletId, filters = {} }: { data: BucksData; organizationId?: string; walletId?: string; filters?: Record<string, string> }) {
 const router = useRouter(), pending = useRef<BucksCommand | null>(null), [busy, setBusy] = useState(false), [notice, setNotice] = useState(""), [org, setOrg] = useState(filters.org ?? ""), [child, setChild] = useState(filters.child ?? ""), [campaign, setCampaign] = useState(filters.campaign ?? ""), [kind, setKind] = useState(filters.kind ?? "");
 async function act(action: string, input: Record<string, Json>) {
  setBusy(true); setNotice("Saving..."); const old = pending.current, command = old?.action === action && JSON.stringify(old.input) === JSON.stringify(input) ? old : { action, input, request_id: crypto.randomUUID() }; pending.current = command;
  try { const response = await fetch("/app/boss-bucks/mutate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(command) }), result = await response.json(); if (!response.ok || !result.ok) { setNotice(typeof result.error === "string" ? result.error : "The wallet change could not be confirmed."); return; } pending.current = null; setNotice("Saved."); router.refresh(); } catch { setNotice("The change could not be confirmed. Retry the same request safely."); } finally { setBusy(false); }
 }
 if (data.unavailable || data.restricted) return <section className="bucks-shell"><h2>Boss Bucks</h2><p role="status">{data.restricted ? "This wallet scope is restricted or the module is unavailable." : "Boss Bucks is temporarily unavailable."}</p></section>;
 const wallets = data.wallets, organizations = [...new Map(wallets.flatMap(w => w.organizations.map(o => [o.id, o.name] as const))).entries()], children = [...new Map(wallets.flatMap(w => w.children.map(c => [c.id, c.name] as const))).entries()], campaigns = [...new Map(wallets.flatMap(w => w.campaigns.map(c => [c.id, c.name] as const))).entries()];
 const activityFilter = (a: WalletActivity) => (!org || a.organization_id === org) && (!child || a.child_id === child) && (!campaign || a.campaign_id === campaign) && (!kind || a.kind === kind);
 return <section className="bucks-shell" aria-label="Boss Bucks wallet"><div className="bucks-heading"><div><p className="bucks-eyebrow">BOSS BUCKS</p><h2>{data.mode === "family" ? "Your family wallet" : "Organization wallet value"}</h2></div><Link className="button button-outline button-small" href={`/app/boss-bucks${organizationId ? `?view=organization&org=${organizationId}` : ""}`}>Wallet details</Link></div><p role="status" aria-live="polite">{notice}</p>
 {data.mode === "family" ? <>
  {!wallets.length && <div className="bucks-empty"><h3>Your wallet starts with verified earnings</h3><p>No authorized family wallet is available. Household membership alone does not grant wallet access.</p></div>}
  {data.provision_choices.length > 0 && !wallets.length && <form className="bucks-form" action={form => { const choice = data.provision_choices[Number(form.get("choice"))]; if (choice) return act("wallet.provision", { organization_id: choice.organization_id, household_id: choice.household_id, dependent_person_id: choice.child_id, currency: String(form.get("currency")) }); }}><label>Authorized family<select name="choice">{data.provision_choices.map((c, n) => <option key={`${c.household_id}-${c.child_id}-${c.organization_id}`} value={n}>{c.household} · {c.child} · {c.organization}</option>)}</select></label><label>Value currency<select name="currency"><option>USD</option><option>CAD</option><option>EUR</option><option>GBP</option></select></label><button disabled={busy} className="button button-primary">Create family wallet</button></form>}
  {wallets.map(w => <article key={w.id} className="bucks-wallet"><div className="bucks-total"><p>{w.household}</p><h3>{money(w.available_minor, w.currency)} <span>Boss Bucks available</span></h3><p>{w.currency} · Combined family value, restricted by originating organization</p></div><h3>Where your Boss Bucks belong</h3><div className="bucks-grid">{w.organizations.filter(o => !org || o.id === org).map(o => <div key={o.id} className="bucks-card"><h4>{o.name}</h4><strong>{money(o.available_minor, w.currency)}</strong><p>Available only with this organization</p>{o.status !== "active" && <p>Organization inactive. History preserved; availability withheld.</p>}</div>)}{!w.organizations.length && <p>No organization earnings yet. Your available balance is zero.</p>}</div><h3>Earned by your children</h3><div className="bucks-grid">{w.children.filter(c => (!child || c.id === child) && (!org || c.organization_id === org)).map(c => <div key={`${c.id}-${c.organization_id}`} className="bucks-card"><h4>{c.name}</h4><strong>{money(c.earned_minor, w.currency)} earned</strong><p>{c.organization}</p><p>Child attribution; shared family value within this organization</p></div>)}{!w.children.length && <p>No child earnings yet. Verified source attribution will appear here.</p>}</div><h3>Campaign earnings</h3>{w.campaigns.filter(c => !campaign || c.id === campaign).map(c => <p key={c.id}>{c.name}: {money(c.earned_minor, w.currency)} earned</p>)}{!w.campaigns.length && <p>No campaign earnings yet.</p>}
  <h3>Recent activity</h3><Activity items={w.activity.filter(activityFilter)} pageItems={w.activity} walletId={w.id} filters={{ org, child, campaign, kind }} />
  </article>)}
  {data.fundraisers.length > 0 && <section><h3>Fundraising wallet ownership</h3>{data.fundraisers.map(f => <article className="bucks-card" key={`${f.id}-${f.household_id}`}><h4>{f.name} · {f.campaign}</h4><p>{f.may_earn ? "This fundraiser may earn Boss Bucks from verified support." : "No wallet earning policy is currently enabled."}</p><p>{f.bound ? `Future source ownership is bound to ${f.household}.` : `Choose ${f.household} explicitly for future fundraising source ownership.`}</p>{!f.bound && <button className="button button-outline" disabled={busy} onClick={() => act("fundraiser.bind_household", { fundraiser_id: f.id, household_id: f.household_id })}>Bind this authorized household</button>}</article>)}</section>}
  {wallets.length > 0 && <form method="get" className="bucks-filters" aria-label="Wallet activity filters">{walletId && <input type="hidden" name="wallet" value={walletId} />}<label>Organization<select name="org" value={org} onChange={e => setOrg(e.target.value)}><option value="">All organizations</option>{organizations.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Child<select name="child" value={child} onChange={e => setChild(e.target.value)}><option value="">All children</option>{children.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Campaign<select name="campaign" value={campaign} onChange={e => setCampaign(e.target.value)}><option value="">All campaigns</option>{campaigns.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Activity<select name="kind" value={kind} onChange={e => setKind(e.target.value)}><option value="">All activity</option><option value="issuance">Earned</option><option value="reversal">Reversed</option><option value="expiration">Expired</option></select></label><button className="button button-outline">Apply activity filters</button></form>}
  <section className="bucks-preview"><h3>Future charge eligibility</h3><p>This preview does not pay, reserve or deduct Boss Bucks.</p>{data.charges.map(c => <article key={c.charge_id} className="bucks-card"><h4>{c.title}</h4><p>{c.organization} · {c.currency}</p><dl><div><dt>Amount due</dt><dd>{money(c.due_minor, c.currency)}</dd></div><div><dt>Same-organization Boss Bucks available</dt><dd>{money(c.available_minor, c.currency)}</dd></div><div><dt>Potentially eligible Boss Bucks</dt><dd>{money(c.eligible_minor, c.currency)}</dd></div><div><dt>Remaining future tender</dt><dd>{money(c.remaining_minor, c.currency)}</dd></div></dl><p>Read-only preview. Payment is not available.</p></article>)}{!data.charges.length && <p>No authorized charges are available for preview.</p>}</section>
 </> : <>
  <p>Only this organization&apos;s restricted value is shown. Available value is not a settled payable.</p><div className="bucks-grid">{data.reports.map(r => <article className="bucks-card" key={r.wallet_id}><h3>{r.household}</h3><dl><div><dt>Issued</dt><dd>{money(r.issued_minor, r.currency)}</dd></div><div><dt>Available</dt><dd>{money(r.available_minor, r.currency)}</dd></div><div><dt>Reversed</dt><dd>{money(r.reversed_minor, r.currency)}</dd></div><div><dt>Expired</dt><dd>{money(r.expired_minor, r.currency)}</dd></div></dl><Link href={`/app/boss-bucks?view=organization&org=${organizationId}&wallet=${r.wallet_id}`}>View organization source activity</Link></article>)}</div>{!data.reports.length && <p>No organization wallet earnings yet.</p>}
  {data.reports.length === 100 && <Link href={`/app/boss-bucks?view=organization&org=${organizationId}&report_after=${data.reports.at(-1)!.wallet_id}`}>More families</Link>}<h3>Campaign earning policies</h3><p>Default: no wallet issuance. A new revision applies only to future contribution intents.</p>{data.policies.map(p => <div key={p.id} className="bucks-card"><h4>{p.campaign}</h4><p>Revision {p.revision} · {p.mode === "none" ? "No issuance" : `${p.basis_points / 100}% of verified gross`} · {p.currency}</p><p>{p.expiry_seconds === null ? "No expiration" : `Explicit expiration after ${p.expiry_seconds} seconds`} · {p.availability_seconds ? `Available after ${p.availability_seconds} seconds` : "Available immediately"}</p></div>)}
  {data.can_manage_policy && data.campaigns.length > 0 && <details><summary>Configure future earning policy</summary><form className="bucks-form" action={form => { const c = data.campaigns.find(c => c.id === form.get("campaign")); if (!c) return; const mode = String(form.get("mode")), bps = mode === "none" ? 0 : Number(form.get("basis_points")); return act("policy.create", { campaign_id: c.id, mode, basis_points: bps, currency: c.currency, channels: ["direct_support", "money_board"] }); }}><label>Campaign<select name="campaign">{data.campaigns.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Policy<select name="mode"><option value="none">No issuance</option><option value="percentage">Percentage of verified gross</option></select></label><label>Earning basis points (10000 = 100%)<input name="basis_points" type="number" min={0} max={10000} step={1} defaultValue={0} required /></label><p>No delay or expiration is introduced by this form. Prior grants remain unchanged.</p><button disabled={busy} className="button button-primary">Save new revision</button></form></details>}
  <h3>Organization source activity</h3><Activity items={data.activity} organizationId={organizationId} walletId={walletId} />
 </>}
 <details className="bucks-explainer" open><summary>What are Boss Bucks?</summary><p>One family wallet brings together approved fundraising earnings from multiple children and campaigns. Each amount stays with its originating organization. Child earnings describe who raised the value; children share the family value within that organization.</p><p>Boss Bucks is internal value, not cash. Future eligible uses include parent-to-organization fees for registration, teams, gear, travel, hotels, camps, tournaments, church youth events, deposits and approved custom obligations. Paying those fees is not available yet.</p><p>Discount memberships and supporter thank-you gifts are separate products.</p></details></section>;
}
function Activity({ items, pageItems = items, walletId, organizationId, filters = {} }: { items: WalletActivity[]; pageItems?: WalletActivity[]; walletId?: string; organizationId?: string; filters?: Record<string, string> }) {
 const query = new URLSearchParams(Object.entries(filters).filter(([,v]) => !!v)); if (organizationId) { query.set("view", "organization"); query.set("org", organizationId); } if (walletId) query.set("wallet", walletId); if (pageItems.length === 50) query.set("before", pageItems.at(-1)!.id);
 return <><ol className="bucks-activity">{items.map(a => <li key={a.id}><div><strong>{a.kind === "issuance" ? `Earned from ${a.campaign}` : a.kind === "reversal" ? "Source reversed" : "Value expired"}</strong><p>{a.child} · {a.organization}{a.team ? ` · ${a.team}` : ""}</p><p>{a.state} · {new Date(a.at).toLocaleDateString("en-US", { timeZone: "UTC" })}{a.expires_at ? ` · Expires ${new Date(a.expires_at).toLocaleDateString("en-US", { timeZone: "UTC" })}` : " · No expiration"}</p>{a.source_reference && <p>Verified source: {a.source_reference}{a.fundraiser ? ` · ${a.fundraiser}` : ""}</p>}</div><strong>{BigInt(a.amount_minor) > 0n ? "+" : ""}{money(a.amount_minor, a.currency)} Boss Bucks</strong></li>)}</ol>{!items.length && <p>No matching wallet activity yet.</p>}{pageItems.length === 50 && <Link href={`/app/boss-bucks?${query}`}>Earlier activity</Link>}</>;
}
