// Loopback-only synthetic layout. No Auth, database, RPC or provider access.
import { createServer } from "node:http";import { readFileSync } from "node:fs";import { createElement } from "react";import { renderToStaticMarkup } from "react-dom/server";import { AppRouterContext } from "next/dist/shared/lib/app-router-context.shared-runtime";
import { DiscountsConsole } from "../src/components/discounts/console";import { PublicDiscountOptions } from "../src/components/discounts/public-options";import { emptyDiscounts, type DiscountData, type DiscountCatalogItem, type DiscountMember } from "../src/lib/discounts/contracts";
const id=(n:number)=>`70000000-0000-4000-8000-${String(n).padStart(12,"0")}`,css=readFileSync("src/app/globals.css","utf8"),router={bfcacheId:"7e-local",back(){},forward(){},push(){},replace(){},refresh(){},prefetch(){}};
const catalog:DiscountCatalogItem[]=(["digital","physical","state_upgrade","nationwide_upgrade"]as const).map((kind,n)=>({revision_id:id(n+10),organization_id:id(1),product_id:id(n+20),membership_product_id:id(20),fulfillment_type:kind==="physical"?"shipping":"digital",name:`SYNTHETIC Boss Bucks ${kind.replaceAll("_"," ")}`,kind,price_minor:n===2?1999:n===3?3900:2500,currency:"USD",tier:n===2?"state":n===3?"nationwide":"local",country:"US",region:"VA",market:"CONTROLLED LOCAL MARKET WITH A LONG DISPLAY NAME",subject_type:"person",term_days:n===0?120:null,trial_days:n<2?90:null,trial_enabled:n===0,gift_enabled:n===0,sale_enabled:true,upgrade_from_tiers:["local"],payment_available:false}));
const memberships:DiscountMember[]=["trial","active","expired"].map((state,n)=>({id:id(n+30),product_id:id(20),household_id:null,display_id:`BBD-SYNTHETIC-${n}`,display_name:"SYNTHETIC persistent consumer",name:"Boss Bucks Discounts",subject_type:"person",base_source_id:id(n+40),effective:{available:state!=="expired",state,tier:state==="expired"?null:"local",source:state==="trial"?"fundraising_trial":state==="active"?"supporter_gift":null,starts_at:"2026-10-07T00:00:00Z",ends_at:"2027-01-05T00:00:00Z",source_id:id(n+40),country:"US",region:"VA",market:catalog[0].market},sources:[],cards:[]}));
const consumer:DiscountData={...emptyDiscounts,catalog,memberships,orders:[{id:id(60),state:"payment_pending",currency:"USD",total_minor:2500,quantity:1}]};
const organization:DiscountData={...emptyDiscounts,mode:"organization",catalog,can_manage_products:true,can_manage_campaigns:true,can_inventory:true,can_fulfillment:true,can_financial_view:true,can_refund:true,products:catalog.map(p=>({id:p.product_id,code:`synthetic_${p.kind}`,kind:p.kind,name:p.name,status:"active"})),revisions:catalog.map(p=>({id:p.revision_id,product_id:p.product_id,currency:p.currency,price_minor:p.price_minor,trial_days:p.trial_days,tier:p.tier,term_days:p.term_days,country:p.country,region:p.region,market:p.market,active:true})),campaigns:[{id:id(70),name:"SYNTHETIC fundraising campaign",status:"published"}],fundraisers:[{id:id(71),campaign_id:id(70),name:"SYNTHETIC participant attribution"}],statistics:{trials_started:2,gift_sources:1,gift_claimed:1,fundraising_credits:[{currency:"USD",amount_minor:1750}]},batches:[{id:id(72),name:"SYNTHETIC inventory larger than 500",status:"inventory",quantity:6000,controlled:true,counts:{inventory:5980,active:18,replaced:1,void:1}}],cards:Array.from({length:12},(_,n)=>({id:id(n+80),serial:`BBC-${String(n).padStart(32,"0")}`,state:n===0?"active":n===1?"replaced":"inventory",claimed:n<2})),orders:[{id:id(60),state:"fulfilled",currency:"USD",total_minor:2500,quantity:1,items:[{id:id(99),kind:"physical",price_minor:2500,corrected:false}]}],fulfillments:[{id:id(100),state:"allocated",version:1,order_id:id(60),card_id:id(80),fulfillment_type:"shipping"}],financial_statistics:[{currency:"USD",digital_sales_minor:2500,physical_sales_minor:2500,refunded_products_minor:0}]};
createServer((req,res)=>{const view=new URL(req.url??"/","http://127.0.0.1:4227").searchParams.get("view"),data=view==="organization"?organization:consumer,component=view==="public"?createElement(PublicDiscountOptions,{catalog,path:"a".repeat(48),onTrial(){}}):createElement(DiscountsConsole,{data,organizationId:id(1),path:"a".repeat(48)}),html=renderToStaticMarkup(createElement(AppRouterContext.Provider,{value:router},component)).replaceAll("<details>","<details open>");res.setHeader("content-type","text/html; charset=utf-8");res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><title>Boss synthetic Discounts layout</title></head><body class="authenticated-page admin-shell"><main class="app-main container"><h1>Boss synthetic Discounts layout</h1>${html}</main></body></html>`);}).listen(4227,"127.0.0.1",()=>console.info("Synthetic Phase 7E layout on loopback port 4227."));
