// Offline synthetic renders only: no backend, credentials, session or live endpoint.
import { createElement as h } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { AppRouterContext, type AppRouterInstance } from "next/dist/shared/lib/app-router-context.shared-runtime";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { MerchantPortal, RedemptionConsole } from "../src/components/merchants/portal";
import { MerchantDirectory } from "../src/components/merchants/discovery";
import { MerchantSales } from "../src/components/merchants/sales";
import type { MerchantData, Terms } from "../src/lib/merchants/contracts";
const id="80000000-0000-4000-8000-000000000001",loc="80000000-0000-4000-8000-000000000002",rev="80000000-0000-4000-8000-000000000003";
const router:AppRouterInstance={bfcacheId:"merchant-layout",back(){},forward(){},push(){},replace(){},refresh(){},prefetch(){}};
const terms:Terms={title:"SYNTHETIC member discount with detailed qualifying purchase terms",description:"SYNTHETIC terms for a controlled business.",offer_type:"percentage_off",discount_bps:1250,qualification:"none",exclusions:"SYNTHETIC tax and gratuity exclusions.",stacking:"none"};
const data:MerchantData={merchant:{id,name:"SYNTHETIC multi-location merchant business",status:"active",claim_state:"reviewed",description:"SYNTHETIC business",version:3},markets:[{id:rev,country:"US",region:"VA",market:"SYNTHETIC controlled local market"}],categories:[{key:"restaurants",name:"Restaurants"},{key:"synthetic_added",name:"SYNTHETIC configured category"}],locations:[{id:loc,name:"SYNTHETIC Location A with explicit local timezone",address:"1 Synthetic Street",city:"Synthetic City",postal_code:"00000",timezone:"America/New_York",market_id:rev,status:"active",version:1}],families:[{id:rev,usage_limit:13,reset_period:"weekly",usage_timezone:"America/New_York",status:"active"}],offers:[{id:rev,revision_id:rev,family_id:rev,merchant_id:id,merchant_name:"SYNTHETIC merchant",location_id:loc,location_name:"SYNTHETIC Location A",terms,revision:1,state:"pending_review",weekly_special:true,weekdays:[0,1,2,3,4,5,6],local_start:"09:00",local_end:"18:00",timezone:"America/New_York",starts_at:"2026-10-01T00:00:00Z",ends_at:"2026-12-01T00:00:00Z",usage_limit:13,reset_period:"weekly",remaining_uses:12,availability:"eligible",can_global_edit:true}],can_manage:true,can_access:true,can_locations:true,can_offers:true,can_review:true,can_configure:true,can_redeem:true,redemptions:[{id:rev,location_id:loc,title:terms.title,created_at:"2026-10-08T00:00:00Z",corrected:false}],leads:[{id:rev,name:"SYNTHETIC assigned prospect",market_id:rev,state:"onboarding",source:"SYNTHETIC referral",rep_id:id,manager_id:null,merchant_id:null,version:1,can_reassign:true,activities:[{id:rev,kind:"follow_up",note:"SYNTHETIC onboarding follow-up.",due_at:null}]}],can_create:true,can_assign:true};
async function main(){const output=process.argv[2];if(!output)throw new Error("Explicit synthetic artifact directory required");const css=await readFile(join(process.cwd(),"src/app/globals.css"),"utf8");const directory={...data,items:[{id,name:"SYNTHETIC public listing without offers",status:"active",description:"SYNTHETIC business",category:"restaurants",locations:data.locations}]};const pages={portal:h(MerchantPortal,{data,merchantId:id}),locations:h(MerchantPortal,{data:{...data,can_offers:false,can_review:false,can_access:false,can_manage:false},merchantId:id,locationId:loc}),offers:h(MerchantPortal,{data,merchantId:id,locationId:loc}),redemption:h(RedemptionConsole,{merchantId:id,locationId:loc,act:async()=>null,busy:false}),deals:h(MerchantDirectory,{data:directory,member:true,marketId:rev}),directory:h(MerchantDirectory,{data:directory,marketId:rev}),sales:h(MerchantSales,{data})};for(const [name,page]of Object.entries(pages))await writeFile(join(output,`${name}.html`),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phase 8A synthetic ${name}</title><style>${css}</style></head><body><main class="container app-main"><h1>SYNTHETIC ${name}</h1>${renderToStaticMarkup(h(AppRouterContext.Provider,{value:router},page))}</main></body></html>`);console.log(`Created ${Object.keys(pages).length} offline synthetic merchant layout fixtures.`);}
void main();
