import FundraiserSampleCTA from "@/components/FundraiserSampleCTA";
import Image from "next/image";
import Link from "next/link";
import ApprovedHeader from "@/components/ApprovedHeader";
import ApprovedFooter from "@/components/ApprovedFooter";
import ReferencePhoto from "@/components/ReferencePhoto";
import home from "../approvedHome.module.css";
import s from "./fundraising.module.css";

export const metadata={title:"Boss Fundraising | Fundraise Like a Boss",description:"Bring Boss Bucks cards, digital trials, direct donations and the Digital Money Board together for your team or organization."};
function Icon({kind}:{kind:string}){return <svg viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==="card"?<><rect x="2" y="7" width="28" height="19" rx="3"/><path d="M2 13h28M7 20h9"/></>:kind==="people"?<><circle cx="16" cy="9" r="4"/><circle cx="5" cy="11" r="3"/><circle cx="27" cy="11" r="3"/><path d="M9 28v-8c0-7 14-7 14 0v8H9ZM2 27v-8h4m24 8v-8h-4"/></>:kind==="heart"?<path fill="currentColor" stroke="none" d="M16 29 4 17C-5 7 8-3 16 7 24-3 37 7 28 17L16 29Z"/>:kind==="gift"?<><path d="M3 13h26v7H3ZM6 20v10h20V20M16 13v17"/><path d="M16 13C0 13 3 0 10 4c4 2 6 9 6 9Zm0 0C32 13 29 0 22 4c-4 2-6 9-6 9Z"/></>:kind==="building"?<><path d="M7 29V3h13v26M20 13h7v16M3 29h27M11 8h5m-5 6h5m-5 6h5m-4 9v-4h4v4"/></>:<path d="M5 28V20m7 8V14m8 14V8m7 20V3" strokeWidth="4"/>}</svg>}
function Photo({width,height,source,alt,className}:{width:number;height:number;source:string;alt?:string;className?:string}){return <svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="xMidYMid slice" role={alt?"img":undefined} aria-label={alt} aria-hidden={alt?undefined:true} className={className}><image href={source} width={width} height={height} preserveAspectRatio="xMidYMid slice"/></svg>}
const ways=[["card","Boss Bucks Cards","Physical and digital discount cards."],["people","Trial Invitations","Introduce supporters to savings."],["heart","Direct Donations","Give toward the campaign."],["bars","Digital Money Board","Choose an amount or take a spin."]];
export default function Page(){return <div className={home.home}><a className={home.skipLink} href="#main-content">Skip to content</a><ApprovedHeader/><main id="main-content" className={s.page}>
<section className={s.hero} aria-labelledby="hero-title"><Image src="/images/approved/fundraising-hero-clean.png" alt="A coach and young athletes celebrating together at sunset" fill priority sizes="100vw" className={s.heroPhoto}/><div className={s.heroCopy}><p className={s.eyebrow}>BOSS FUNDRAISING</p><h1 id="hero-title">Fundraise<br/>Like a <span>Boss.</span></h1><p className={s.heroLead}>More ways to give. More reasons to support.</p><p className={s.audiences}>For teams, schools, churches, camps<br className={s.desktopBreak}/> and community organizations.</p><div className={s.actions}><Link href="/fundraising/get-started" className={s.button}>Start a Fundraiser</Link><a href="#ways-to-give" className={s.outline}>Explore the Ways to Give</a></div></div></section>
<section id="ways-to-give" className={s.ways} aria-labelledby="ways-title"><h2 id="ways-title">One campaign. <span>More ways to help.</span></h2><div className={s.wayGrid}>{ways.map(([kind,title,copy])=><article key={kind}><div className={s.circle}><Icon kind={kind}/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className={s.money} aria-labelledby="money-title"><Photo width={284} height={347} source="/images/approved/fundraising-team-clean.png" alt="Young athletes celebrating their team" className={s.moneyPhoto}/><div className={s.moneyCopy}><h2 id="money-title">The Digital<br/><span>Money Board</span></h2><h3>Small amounts. Shared momentum.</h3><p>Give supporters a simple way to join in and see progress.</p><ul><li>Donate or Spin</li><li>Available and claimed amounts</li><li>Team and participant credit</li></ul><Link href="/money-board" className={s.button}>Explore the Money Board</Link></div><figure className={s.moneyPhone}><svg viewBox="132 10 768 1505" role="img" aria-label="Illustrative Digital Money Board with Donate and Spin, fundraising progress, available and claimed amounts"><defs><clipPath id="fundraising-money-cutout"><rect x="152" y="30" width="720" height="1474" rx="130"/><rect x="145" y="251" width="9" height="51" rx="3"/><rect x="145" y="362" width="9" height="92" rx="3"/><rect x="145" y="486" width="9" height="91" rx="3"/><rect x="870" y="404" width="8" height="165" rx="3"/></clipPath></defs><image href="/images/approved/money-board.jpeg" width="1024" height="1536" clipPath="url(#fundraising-money-cutout)"/></svg><figcaption>Illustrative product preview.<br/>Amounts and names are examples.</figcaption></figure></section>
<section className={s.savings} aria-labelledby="savings-title"><figure className={s.discountPhone}><svg viewBox="175 0 745 1402" role="img" aria-label="Illustrative Boss Bucks Discounts app with featured offers and nearby deals"><defs><clipPath id="fundraising-discounts-cutout"><rect x="212" y="17" width="670" height="1352" rx="120"/><rect x="207" y="247" width="7" height="188" rx="3"/><rect x="207" y="460" width="7" height="94" rx="3"/><rect x="880" y="398" width="7" height="148" rx="3"/></clipPath></defs><image href="/images/approved/discounts-original.png" width="1122" height="1402" clipPath="url(#fundraising-discounts-cutout)"/></svg><figcaption>Illustrative product preview. Offers shown are examples.</figcaption></figure><div className={s.savingsCopy}><h2 id="savings-title">Give savings.<br/><span>Invite support.</span></h2><p className={s.lead}>Boss Bucks cards and digital trials keep your campaign connected.</p><div className={s.cardOptions}><article><div className={s.smallCircle}><Icon kind="card"/></div><div><h3>Sell Boss Bucks cards</h3><p>Physical and digital options connect fundraising with participating-business offers.</p></div></article><article><div className={s.smallCircle}><Icon kind="people"/></div><div><h3>Offer a digital trial</h3><p>Choose 30, 60 or 90 days for your campaign.</p><ul className={s.durations} aria-label="Campaign-configurable trial durations"><li>30 days</li><li>60 days</li><li>90 days</li></ul></div></article></div><aside className={s.gift}><div className={s.circle}><Icon kind="gift"/></div><div><h3>A thank-you with everyday value.</h3><p>Supporters can donate when they sign up. A donation of more than $25 can qualify for a Boss Bucks membership as a thank-you gift.</p><small>Campaign terms and approved gift rules apply. Donations are optional.</small></div></aside></div></section>
<section className={s.sharing} aria-labelledby="share-title"><ReferencePhoto source="/images/approved/home-photos-single-b.webp" crop="558 478 235 92" className={s.sharingPhoto} preserveAspectRatio="xMidYMid slice"/><h2 id="share-title"><span>Every share</span> stays connected.</h2><ol>{[["Set up your campaign","Choose the options that fit your organization."],["Share your link or QR code","Connect support to the right team and participant."],["Follow your progress","See campaign and participant activity together."]].map(([title,copy],i)=><li key={title}><span>{i+1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol><p className={s.vision}>Platform vision. Features vary by campaign.</p></section>
<FundraiserSampleCTA/>
<section className={s.family} aria-labelledby="family-title"><Photo width={309} height={204} source="/images/approved/fundraising-family-clean.png" alt="A mother supporting her young athlete" className={s.familyPhoto}/><div className={s.familyCopy}><h2 id="family-title">Raise for your team.<br/><span>Help your families.</span></h2><div className={s.familyCards}><article><Icon kind="people"/><div><h3>Families &amp; participants</h3><p>Apply earned Boss Bucks to approved sports fees, registration, team gear, children’s and youth camps, tournaments and eligible travel. No cash withdrawals or personal bank transfers.</p></div></article><article><Icon kind="building"/><div><h3>Teams &amp; organizations</h3><p>Only eligible organization proceeds may transfer to an approved organization bank account.</p></div></article></div><p className={s.familyNote}>Discount membership and earned Boss Bucks are separate benefits.</p></div></section>
<section className={s.store} aria-labelledby="store-title"><Photo width={246} height={85} source="/images/approved/fundraising-store-clean.png" alt="Illustrative black and orange team shirts" className={s.storePhoto}/><div><h2 id="store-title">Bring your team store into the campaign.</h2><p>Connect merchandise and approved products with your fundraising plan.</p><Link href="/engage">Explore team stores <span aria-hidden="true">›</span></Link><small>Platform vision</small></div></section>
<section className={s.finalCta}><h2>Fundraise <span>Like a Boss.</span></h2><p>Tell us about your organization. Let’s build the right starting point.</p><Link href="/fundraising/get-started" className={s.button}>Start a Fundraiser</Link></section>
<section style={{padding:"36px 24px",textAlign:"center",background:"#f6f7f8",color:"#111"}} aria-label="Your Boss Bucks account"><h2 style={{margin:"0 0 12px",fontSize:"1.8rem"}}>One family. More possibilities.</h2><p style={{margin:"0 auto 18px",maxWidth:700,lineHeight:1.6}}>Explore how eligible fundraising credits from participating teams, churches and organizations can help cover approved family expenses.</p><a href="/boss-bucks-account" style={{display:"inline-block",padding:"14px 22px",borderRadius:5,background:"#c63b00",color:"white",fontWeight:700,textDecoration:"none"}}>Explore Your Boss Bucks Account →</a></section></main><ApprovedFooter/></div>}
