"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { statCatalog, type TrackingSport } from "@/lib/stat-tracking/catalog";
import { bossStandingsTemplate, bossStandingsTemplateVersion, rankingRateMetrics } from "@/lib/rankings/templates";
import { statSports, type StatSport } from "@/lib/stat-intelligence/contracts";
import { statUuid } from "@/lib/stat-intelligence/input";
import type { RankingData } from "@/lib/rankings/contracts";
import { RankingActionForm } from "./action-form";
import { rankingHref } from "./hub";
const read = (f: FormData, k: string) => String(f.get(k) ?? "").trim();
const thresholdTypes = ["min_games", "min_games_percentage", "min_attempts", "min_attempts_per_team_game", "min_pa", "min_pa_per_team_game", "min_outs", "min_innings_equivalent", "min_minutes", "min_attack_attempts", "min_targets", "min_receptions"] as const;
const ruleTypes = ["head_to_head", "head_to_head_percentage", "mini_table", "conference_percentage", "division_percentage", "common_opponents", "differential", "capped_differential", "allowed", "scoring_for", "set_percentage", "point_ratio", "strength_of_schedule"] as const;
type Choice = { id: string; label: string };
function Choices({ choices, name, label, optional = false }: { choices: Choice[]; name: string; label: string; optional?: boolean }) { return <label className="form-field"><span>{label}</span><select name={name} required={!optional}><option value="">{optional ? "Whole scope / none" : "Choose"}</option>{choices.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></label>; }
function Name() { return <label className="form-field"><span>Name</span><input name="name" maxLength={200} required /></label>; }
function Reason() { return <label className="form-field"><span>Reason</span><textarea name="reason" rows={2} maxLength={500} required /></label>; }
export function CompetitionManagement({ org, data, teams, seasons, games }: { org: string; data: RankingData; teams: Choice[]; seasons: Choice[]; games: Choice[] }) {
  const router = useRouter(), [competition, setCompetition] = useState(data.edition?.competition_id ?? "");
  const [criteriaCount, setCriteriaCount] = useState(1), [minimumCount, setMinimumCount] = useState(1), [definitionProduct, setDefinitionProduct] = useState(data.can_leaderboard_manage ? "leaderboard" : "records");
  const ed = data.edition?.id, sport = data.edition?.sport_key ?? "basketball";
  const template = bossStandingsTemplate(sport as StatSport), rates = rankingRateMetrics[sport as StatSport];
  const metrics = statCatalog[sport as TrackingSport].filter(s => s.available && (s.scopes.includes("player") || s.scopes.includes("team")));
  const entries = data.entries.filter(e => e.status === "active").map(e => ({ id: e.id, label: e.name })), groups = data.groups.map(g => ({ id: g.id, label: `${g.name} (${g.kind})` }));
  return <section className="admin-section"><h2>Competition management</h2>{!ed && data.can_create && <><details><summary>Create competition</summary><RankingActionForm label="Create durable competition" onSaved={setCompetition} build={f => ({ action: "competition.create", input: { organization_id: org, name: read(f, "name") } })}><Name /></RankingActionForm></details>
    {(competition || data.editions.length > 0) && <details open={!!competition}><summary>Create competition edition</summary><RankingActionForm label="Create edition" onSaved={id => router.push(rankingHref({ organization_id: org, edition_id: id }))} build={f => ({ action: "edition.create", input: { competition_id: competition || read(f, "competition"), name: read(f, "name"), sport_key: read(f, "sport"), ...(read(f, "season") ? { season_id: read(f, "season") } : {}), cross_organization: f.has("cross"), team_result_audience: f.has("team_audience") ? "entry_teams" : "managers" } })}>{!competition && <Choices name="competition" label="Competition" choices={Array.from(new Map(data.editions.filter(e => e.competition_id).map(e => [e.competition_id!, { id: e.competition_id!, label: e.competition_name ?? e.name }])).values())} />}<Name /><label className="form-field"><span>Sport</span><select name="sport">{statSports.map(s => <option key={s} value={s}>{s}</option>)}</select></label><Choices name="season" label="Season" choices={seasons} optional /><label><input type="checkbox" name="cross" /> Explicit cross-organization participation</label><label><input type="checkbox" name="team_audience" /> Share safe team results with authorized entry-team relationships</label></RankingActionForm></details>}</>}
    {ed && data.can_manage && <><details><summary>Team entries and groups</summary><RankingActionForm label="Add explicit team entry" build={f => ({ action: "entry.create", input: { edition_id: ed, team_id: read(f, "team") } })}><Choices name="team" label="Canonical team" choices={teams} /></RankingActionForm><RankingActionForm label="Create group" build={f => ({ action: "group.create", input: { edition_id: ed, kind: read(f, "kind"), name: read(f, "name") } })}><Name /><label className="form-field"><span>Group type</span><select name="kind">{["division", "conference", "pool", "region"].map(k => <option key={k}>{k}</option>)}</select></label></RankingActionForm><RankingActionForm label="Assign entry to group" build={f => ({ action: "group.assign", input: { edition_id: ed, entry_id: read(f, "entry"), group_id: read(f, "group") } })}><Choices name="entry" label="Entry" choices={entries} /><Choices name="group" label="Group" choices={groups} /></RankingActionForm></details><details><summary>Close edition</summary><RankingActionForm label="Archive edition" build={f => f.has("confirm") ? { action: "edition.archive", input: { edition_id: ed } } : null}><label><input type="checkbox" name="confirm" required /> I reviewed this edition and its dependent work.</label></RankingActionForm></details></>}
    {ed && data.can_policy_manage && <details><summary>Activate standings policy</summary><p>Boss templates ({bossStandingsTemplateVersion}) are starting points. They make no federation-compliance claim. Unconfigured comparisons remain tied.</p><RankingActionForm label="Activate reviewed policy revision" build={f => {
      const rules = Array.from({ length: criteriaCount }, (_, n) => { const type = read(f, `rule-${n}`); return type ? { type, ...(type === "capped_differential" ? { cap: Number(read(f, `cap-${n}`)) } : {}), ...(["conference_percentage", "division_percentage"].includes(type) ? { group_id: read(f, `rule-group-${n}`) } : {}) } : null; }).filter(r => r !== null);
      const configuration = { ...template, order_by: read(f, "order"), tie_weight: Number(read(f, "tie_weight")), allow_ties: f.has("ties"), ...(read(f, "order") === "points" ? { win_points: Number(read(f, "win_points")), tie_points: Number(read(f, "tie_points")), loss_points: Number(read(f, "loss_points")) } : {}), mini_table_restart: f.has("restart"), tiebreaks: rules };
      return { action: "policy.activate", input: { edition_id: ed, configuration, reason: read(f, "reason") } };
    }}><label className="form-field"><span>Primary ordering</span><select name="order" defaultValue={sport === "soccer" ? "points" : "win_percentage"}><option value="wins">Wins</option><option value="win_percentage">Winning percentage</option><option value="points">Competition points</option></select></label><label><input type="checkbox" name="ties" defaultChecked={sport !== "volleyball" && sport !== "basketball"} /> Permit ties</label><label className="form-field"><span>Tie weight for winning percentage</span><input type="number" name="tie_weight" defaultValue={0.5} min={0} max={1} step="any" required /></label><div className="game-form-grid">{[["win_points", "Win points", 3], ["tie_points", "Tie points", 1], ["loss_points", "Loss points", 0]].map(([key, label, initial]) => <label className="form-field" key={key}><span>{label}</span><input type="number" name={String(key)} defaultValue={sport === "soccer" ? initial : undefined} min={-1000} max={1000} step="any" /></label>)}</div>{Array.from({ length: criteriaCount }, (_, n) => <fieldset key={n}><legend>Tiebreak criterion {n + 1}</legend><label className="form-field"><span>Rule</span><select name={`rule-${n}`}><option value="">No additional tiebreak</option>{ruleTypes.map(r => <option key={r} value={r}>{r.replaceAll("_", " ")}</option>)}</select></label><Choices name={`rule-group-${n}`} label="Explicit conference / division for this criterion" choices={groups} optional /><label className="form-field"><span>Per-game differential cap, when selected</span><input name={`cap-${n}`} type="number" min={0} max={1000000} defaultValue={0} /></label></fieldset>)}<button type="button" className="button button-outline button-small" disabled={criteriaCount >= 12} onClick={() => setCriteriaCount(n => n + 1)}>Add ordered criterion</button>{criteriaCount > 1 && <button type="button" className="button button-outline button-small" onClick={() => setCriteriaCount(n => n - 1)}>Remove last criterion</button>}<label><input type="checkbox" name="restart" /> Restart a mini-table on a strictly smaller tied cohort</label><Reason /></RankingActionForm></details>}
    {ed && data.can_standings_manage && <><details><summary>Assign a canonical game</summary><RankingActionForm label="Save explicit game assignment" build={f => ({ action: "game.assign", input: { edition_id: ed, game_id: read(f, "game"), primary_entry_id: read(f, "primary"), opponent_entry_id: read(f, "opponent"), game_type: read(f, "type"), counts_for_standings: f.has("counts"), group_ids: read(f, "group") ? [read(f, "group")] : [], reason: read(f, "reason") } })}><Choices name="game" label="Authorized canonical game" choices={games} /><Choices name="primary" label="Primary team entry" choices={entries} /><Choices name="opponent" label="Opponent team entry" choices={entries} /><label className="form-field"><span>Competition game classification</span><select name="type">{["league", "conference", "division", "nonconference", "tournament", "other"].map(t => <option key={t}>{t}</option>)}</select></label><Choices name="group" label="Explicit game group" choices={groups} optional /><label><input type="checkbox" name="counts" defaultChecked /> Counts for this edition's standings</label><Reason /></RankingActionForm></details><details><summary>Unplayed forfeit</summary><p>This ruling changes competition outcomes. It creates no player statistics and no invented differential.</p><RankingActionForm label="Record audited unplayed forfeit" build={f => ({ action: "ruling.create", input: { edition_id: ed, primary_entry_id: read(f, "primary"), opponent_entry_id: read(f, "opponent"), kind: "forfeit", outcome: read(f, "outcome"), ...(read(f, "group") ? { group_id: read(f, "group") } : {}), reason: read(f, "reason") } })}><Choices name="primary" label="Primary entry" choices={entries} /><Choices name="opponent" label="Opponent entry" choices={entries} /><label className="form-field"><span>Ruling winner</span><select name="outcome"><option value="primary">Primary entry</option><option value="opponent">Opponent entry</option></select></label><Choices name="group" label="Group" choices={groups} optional /><Reason /></RankingActionForm></details></>}
    {ed && (data.can_leaderboard_manage || data.can_records_manage) && <details><summary>Private leaderboard / record definition</summary><p>Only authorized originating scopes can create or read athlete comparisons. Rate rankings require an explicit minimum. Not tracked is not zero.</p><RankingActionForm label="Create private definition" build={f => {
      const thresholds = Array.from({ length: minimumCount }, (_, n) => { const type = read(f, `threshold-${n}`), metric = read(f, `threshold_metric-${n}`); return type ? { type, value: Number(read(f, `minimum-${n}`)), ...(metric ? { metric } : {}) } : null; }).filter(t => t !== null);
      return { action: "definition.create", input: { edition_id: ed, source_organization_id: org, ...(read(f, "team") ? { team_id: read(f, "team") } : {}), ...(read(f, "season") ? { season_id: read(f, "season") } : {}), name: read(f, "name"), product: read(f, "product"), source_kind: read(f, "source"), metric_key: read(f, "metric"), metric_kind: rates.some(r => r === read(f, "metric")) ? "rate" : "count", direction: read(f, "direction"), competition_only: f.has("competition_only"), allow_partial: f.has("partial"), qualification: thresholds.length ? { thresholds } : {} } };
    }}><Name /><Choices name="team" label="Original team scope" choices={teams} optional /><Choices name="season" label="Season" choices={seasons} optional /><label className="form-field"><span>Product</span><select name="product" value={definitionProduct} onChange={e => setDefinitionProduct(e.target.value)}>{data.can_leaderboard_manage && <option value="leaderboard">Leaderboard</option>}{data.can_records_manage && <option value="records">Records</option>}</select></label><label className="form-field"><span>Record / leaderboard category</span><select name="source">{(definitionProduct === "records" ? ["athlete_season", "athlete_career", "team_season", "athlete_game", "team_game", "organization_history"] : ["athlete_season", "athlete_career", "team_season"]).map(s => <option key={s} value={s}>{s.replaceAll("_", " ")}</option>)}</select></label><label className="form-field"><span>Statistic</span><select name="metric" required><option value="">Choose statistic</option>{metrics.filter(m => !rates.some(r => r === m.key)).map(m => <option key={m.key} value={m.key}>{m.label}</option>)}{rates.map(r => <option key={r} value={r}>{r.replaceAll("_", " ")} (component-derived rate)</option>)}</select></label><label className="form-field"><span>Better value</span><select name="direction"><option value="high">Higher</option><option value="low">Lower</option></select></label>{Array.from({ length: minimumCount }, (_, n) => <fieldset key={n}><legend>Explicit qualification minimum {n + 1}</legend><label className="form-field"><span>Threshold type</span><select name={`threshold-${n}`}><option value="">No additional minimum, counting only</option>{thresholdTypes.map(t => <option key={t}>{t}</option>)}</select></label><label className="form-field"><span>Minimum value</span><input type="number" name={`minimum-${n}`} min={0.000001} max={1000000} step="any" /></label><label className="form-field"><span>Attempt component for attempt thresholds</span><select name={`threshold_metric-${n}`}><option value="">Not an attempt threshold</option>{metrics.filter(m => m.classification !== "derived").map(m => <option key={m.key} value={m.key}>{m.label}</option>)}</select></label></fieldset>)}<button type="button" className="button button-outline button-small" disabled={minimumCount >= 8} onClick={() => setMinimumCount(n => n + 1)}>Add qualification minimum</button>{minimumCount > 1 && <button type="button" className="button button-outline button-small" onClick={() => setMinimumCount(n => n - 1)}>Remove last minimum</button>}<label><input type="checkbox" name="competition_only" defaultChecked /> Only explicitly assigned counting competition games</label><label><input type="checkbox" name="partial" /> Explicitly permit and disclose an observed / partial basis</label></RankingActionForm></details>}
    {ed && data.can_manage && data.entries.filter(e => e.status === "pending").map(e => <RankingActionForm key={e.id} label={`Approve originating team entry: ${e.name}`} build={() => statUuid(e.id) ? { action: "entry.approve", input: { edition_id: ed, entry_id: e.id } } : null} />)}
  </section>;
}
