import test from "node:test";
import assert from "node:assert/strict";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { parseAchievementCommand, projectAchievements, emptyAchievements } from "../src/lib/achievements/input";
import { performAchievementMutation, type AchievementClient } from "../src/lib/achievements/mutation";
import { AchievementBadges } from "../src/components/achievements/badges";
const id = "10000000-0000-0000-0000-000000000001", other = "10000000-0000-0000-0000-000000000002", origin = "https://platform.boss.invalid";
const command = { action: "definition.evaluate", request_id: id, input: { definition_id: other } };
const card = { id, achievement_id: other, name: "Synthetic milestone", category: "statistical_milestone", subject_type: "athlete", state: "current", verification_level: "boss_verified", achieved_at: "2026-10-06T00:00:00Z", badge_icon: "milestone", source_type: "stat_summary", current: true };
function request(body: unknown = command, headers = {}) { return new Request(`${origin}/app/achievements/mutate`, { method: "POST", headers: { origin, host: "platform.boss.invalid", "content-type": "application/json", ...headers }, body: JSON.stringify(body) }); }
function mock() { const calls: unknown[] = []; const client: AchievementClient = { auth: { getClaims: async () => ({ data: { claims: { sub: id, iss: "https://ilykgwgmxtrrikreacrz.supabase.co/auth/v1", role: "authenticated", exp: Math.floor(Date.now() / 1000) + 60 } }, error: null }), getUser: async () => ({ data: { user: { id } }, error: null }) }, rpc: async (name, args) => { calls.push([name, args]); return { data: { contract: "achievements-v1", action: command.action, id: other, replayed: false, has_more: true, private_note: "PRIVATE", source_manifest: { private: true } }, error: null }; } }; return { client, calls }; }
test("achievement commands reject forged authority, formula and unknown actions", () => { assert.ok(parseAchievementCommand(command)); for (const value of [{ ...command, person_id: id }, { ...command, action: "badge.upload" }, { ...command, input: { ...command.input, organization_override: id } }, { ...command, input: { definition_id: "forged" } }]) assert.equal(parseAchievementCommand(value), null); });
test("historical revisions can be refreshed without rewriting definition history", () => { assert.ok(parseAchievementCommand({ ...command, input: { definition_id: other, revision_id: id } })); });
test("finite definition parser closes formula and SVG fields", () => { const rule = { name: "Synthetic", subject_type: "athlete", category: "statistical_milestone", source_kind: "athlete_game", sport_key: "baseball", metric_key: "hits", threshold: 1 }; const create = { ...command, action: "definition.create", input: { owner_kind: "organization", definition_key: "synthetic", organization_id: id, revision: rule } }; assert.ok(parseAchievementCommand(create)); assert.equal(parseAchievementCommand({ ...create, input: { ...create.input, revision: { ...rule, sql: "select true" } } }), null); assert.equal(parseAchievementCommand({ ...create, input: { ...create.input, revision: { ...rule, threshold: Infinity } } }), null); });
test("untrusted achievement projection fails closed", () => { const data = { ...emptyAchievements(), contract: "achievements-v1", recognitions: [card] }; assert.ok(projectAchievements(data)); assert.equal(projectAchievements({ ...data, recognitions: [{ ...card, state: "invented" }] }), null); assert.equal(projectAchievements({ ...data, recognitions: Array(51).fill(card) }), null); assert.equal(projectAchievements({ ...data, can_manage: "true" }), null); });
test("badge semantics remain text accessible without graphics", () => { const html = renderToStaticMarkup(createElement(AchievementBadges, { items: [card, { ...card, id: other, name: "Synthetic record", category: "record", co_holder: true }] })); assert.match(html, /aria-hidden="true"/); assert.match(html, /Boss verified/); assert.match(html, /Co-Record Holder/); assert.match(html, /2026-10-06/); assert.match(html, /Recognition history/); assert.doesNotMatch(html, /<svg|<script/); });
test("badge labels distinguish pending, corrected and manual facts", () => { const html = renderToStaticMarkup(createElement(AchievementBadges, { items: [{ ...card, state: "processing" }, { ...card, id: other, state: "corrected", verification_level: "organization_verified" }] })); assert.match(html, /Processing source update/); assert.match(html, /Corrected by authoritative source/); assert.match(html, /Organization verified/); });
test("consented public badge retains provenance text without private history links", () => { const { id: _id, achievement_id: _achievement, source_type: _source, ...publicCard } = card; void _id; void _achievement; void _source; const html = renderToStaticMarkup(createElement(AchievementBadges, { items: [publicCard] })); assert.match(html, /Boss verified/); assert.match(html, /statistical milestone/); assert.match(html, /2026-10-06/); assert.doesNotMatch(html, /\/app\/achievements|Recognition history/); });
test("cross-origin achievement POST denies before RPC", async () => { const m = mock(); assert.equal((await performAchievementMutation(request(command, { origin: "https://attacker.invalid" }), m.client, origin)).status, 403); assert.equal(m.calls.length, 0); });
test("wrong content type and oversized achievement request deny before RPC", async () => { const m = mock(); assert.equal((await performAchievementMutation(request(command, { "content-type": "text/plain" }), m.client, origin)).status, 422); assert.equal((await performAchievementMutation(request({ ...command, input: { ...command.input, note: "x".repeat(35000) } }), m.client, origin)).status, 422); assert.equal(m.calls.length, 0); });
test("changed authenticated identity cannot mutate achievement", async () => { const m = mock(); m.client.auth.getUser = async () => ({ data: { user: { id: other } }, error: null }); assert.equal((await performAchievementMutation(request(), m.client, origin)).status, 401); assert.equal(m.calls.length, 0); });
test("achievement HTTP result strips notes and source manifests", async () => { const m = mock(), result = await performAchievementMutation(request(), m.client, origin); assert.equal(result.status, 200); assert.doesNotMatch(JSON.stringify(result), /PRIVATE|source_manifest|private_note/); assert.equal("has_more" in result.body && result.body.has_more, true); });
test("achievement errors have finite safe response mapping", async () => { const m = mock(); for (const [code, status] of [["PT403", 403], ["PT409", 409], ["40001", 409], ["PT422", 422]] as const) { m.client.rpc = async () => ({ data: null, error: { code } }); assert.equal((await performAchievementMutation(request(), m.client, origin)).status, status); } });
