import test from "node:test";
import assert from "node:assert/strict";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { AppRouterContext } from "next/dist/shared/lib/app-router-context.shared-runtime";
import { parseAthleteProfileCommand } from "../src/lib/athlete-profiles/action";
import { projectAthleteProfiles, projectShowcase } from "../src/lib/athlete-profiles/input";
import { performAthleteProfileMutation, type AthleteProfileClient } from "../src/lib/athlete-profiles/mutation";
import { AthleteProfileHub } from "../src/components/athlete-profiles/hub";
const id = "10000000-0000-0000-0000-000000000001", other = "10000000-0000-0000-0000-000000000002", origin = "https://platform.boss.invalid";
const command = { action: "profile.create", request_id: id, input: { participant_id: other, visibility: "athlete_guardian", safe_fields: { display_name: "Synthetic athlete" } } };
function request(body: unknown = command, headers = {}) { return new Request(`${origin}/app/athletes/mutate`, { method: "POST", headers: { origin, host: "platform.boss.invalid", "content-type": "application/json", ...headers }, body: JSON.stringify(body) }); }
function mock() { const calls: unknown[] = []; const client: AthleteProfileClient = { auth: { getClaims: async () => ({ data: { claims: { sub: id, iss: "https://ilykgwgmxtrrikreacrz.supabase.co/auth/v1", role: "authenticated", exp: Math.floor(Date.now() / 1000) + 60 } }, error: null }), getUser: async () => ({ data: { user: { id } }, error: null }) }, rpc: async (name, args) => { calls.push([name, args]); return { data: { contract: "athlete-profiles-v1", action: command.action, profile_id: other, replayed: false, private_payload: "HIDDEN" }, error: null }; } }; return { client, calls }; }
test("athlete commands reject forged authority and unknown fields", () => { assert.ok(parseAthleteProfileCommand(command)); for (const value of [{ ...command, actor_person_id: id }, { ...command, action: "profile.public_search" }, { ...command, input: { ...command.input, person_id: id } }, { ...command, input: { ...command.input, participant_id: "forged" } }]) assert.equal(parseAthleteProfileCommand(value), null); });
test("profile projection fails closed on malformed subject and authority", () => { assert.equal(projectAthleteProfiles({ subjects: [{ profile_id: "forged" }], profile: null }), null); assert.equal(projectAthleteProfiles({ subjects: [], profile: { profile: { id }, authority: null } }), null); });
test("unavailable showcase reveals no partial fields", () => { assert.deepEqual(projectShowcase({ available: false, athlete: { display_name: "PRIVATE" } }), { available: false }); });
test("public projection requires explicit privacy contract", () => { assert.equal(projectShowcase({ available: true, showcase_id: id, athlete: {}, sports: [], privacy: { searchable: true, contact_details_exposed: false } }), null); assert.ok(projectShowcase({ available: true, showcase_id: id, athlete: {}, sports: [], privacy: { unlisted: true, searchable: false, contact_details_exposed: false } })); });
test("profile UI labels provenance and keeps completeness non-authoritative", () => { const data = projectAthleteProfiles({ subjects: [{ profile_id: id, participant_id: other, person_id: other, display_name: "Synthetic" }], profile: { profile: { id, participant_id: other, person_id: other, status: "active", visibility: "athlete_guardian", version: 1, current_revision_id: id, fields: { display_name: "Synthetic" }, completeness: { completed: 2, possible: 6 } }, authority: { relationship: "self", can_manage: false, can_verify: false, can_manage_showcase: false, self_publication_enabled: false }, origins: [], statistics: [], measurables: [], achievements: [], media: [], showcase: null } }); assert.ok(data); const html = renderToStaticMarkup(createElement(AthleteProfileHub, { data })); assert.match(html, /Completeness does not change visibility/); assert.match(html, /Missing coverage is never shown as zero/); assert.doesNotMatch(html, /Publish approved showcase/); });
test("authorized guardian can disable an active showcase", () => { const data = projectAthleteProfiles({ subjects: [{ profile_id: id, participant_id: other, person_id: other, display_name: "Synthetic" }], profile: { profile: { id, participant_id: other, person_id: other, status: "active", visibility: "athlete_guardian", version: 2, current_revision_id: id, fields: { display_name: "Synthetic" }, completeness: { completed: 2, possible: 6 } }, authority: { relationship: "guardian", can_manage: true, can_verify: false, can_manage_showcase: true, self_publication_enabled: false }, origins: [], statistics: [], measurables: [], achievements: [], media: [], showcase: { id: other, state: "active", version: 4, current_revision_id: id, published_revision_id: id, current_consent_id: id, revision: { revision: 1, sport_keys: ["football"], visible_categories: ["overview"], stat_metric_keys: [], presentation: {} }, links: [] } } }); assert.ok(data); const router = { bfcacheId: "athlete-profile-test", back() {}, forward() {}, push() {}, replace() {}, refresh() {}, prefetch() {} }; const html = renderToStaticMarkup(createElement(AppRouterContext.Provider, { value: router }, createElement(AthleteProfileHub, { data }))); assert.match(html, /Disable recruiting showcase/); });
test("authorized staff can enter organization-verified measurables and achievements", () => { const data = projectAthleteProfiles({ subjects: [{ profile_id: id, participant_id: other, person_id: other, display_name: "Synthetic" }], profile: { profile: { id, participant_id: other, person_id: other, status: "active", visibility: "current_team_staff", version: 1, current_revision_id: id, fields: { display_name: "Synthetic" }, completeness: { completed: 2, possible: 6 } }, authority: { relationship: "staff", can_manage: false, can_verify: true, can_manage_showcase: false, self_publication_enabled: false }, origins: [], statistics: [], measurables: [], achievements: [], media: [], showcase: null } }); assert.ok(data); const router = { bfcacheId: "athlete-profile-staff-test", back() {}, forward() {}, push() {}, replace() {}, refresh() {}, prefetch() {} }; const html = renderToStaticMarkup(createElement(AppRouterContext.Provider, { value: router }, createElement(AthleteProfileHub, { data }))); assert.match(html, /Add organization-verified measurable/); assert.match(html, /Add organization-verified achievement/); assert.doesNotMatch(html, /Save new profile revision/); assert.doesNotMatch(html, /Create draft showcase/); });
test("cross-origin mutation stops before identity and RPC", async () => { const m = mock(), result = await performAthleteProfileMutation(request(command, { origin: "https://attacker.invalid" }), m.client, origin); assert.equal(result.status, 403); assert.equal(m.calls.length, 0); });
test("wrong content and oversized input never reach RPC", async () => { const m = mock(); assert.equal((await performAthleteProfileMutation(request(command, { "content-type": "text/plain" }), m.client, origin)).status, 422); assert.equal((await performAthleteProfileMutation(request({ ...command, input: { ...command.input, safe_fields: { bio: "x".repeat(35000) } } }), m.client, origin)).status, 422); assert.equal(m.calls.length, 0); });
test("changed or anonymous identity cannot mutate", async () => { const m = mock(); m.client.auth.getUser = async () => ({ data: { user: { id: other } }, error: null }); assert.equal((await performAthleteProfileMutation(request(), m.client, origin)).status, 401); m.client.auth.getUser = async () => ({ data: { user: { id, is_anonymous: true } }, error: null }); assert.equal((await performAthleteProfileMutation(request(), m.client, origin)).status, 401); assert.equal(m.calls.length, 0); });
test("mutation response strips private RPC payload", async () => { const m = mock(), result = await performAthleteProfileMutation(request(), m.client, origin); assert.equal(result.status, 200); assert.doesNotMatch(JSON.stringify(result), /HIDDEN/); });
test("share creation generates raw token only in bounded response", async () => { const m = mock(); m.client.rpc = async (name, args) => { m.calls.push([name, args]); return { data: { contract: "athlete-profiles-v1", action: "share.create", profile_id: other, replayed: false }, error: null }; }; const body = { action: "share.create", request_id: id, input: { showcase_id: other, expires_at: new Date(Date.now() + 100000).toISOString() } }, result = await performAthleteProfileMutation(request(body), m.client, origin); assert.equal(result.status, 200); assert.match(String("share_url" in result.body && result.body.share_url), /^\/recruiting\/[A-Za-z0-9_-]{43}$/); const sent = JSON.stringify(m.calls); assert.match(sent, /token_digest/); assert.doesNotMatch(sent, /\/recruiting\//); });
test("database error mapping is finite", async () => { const m = mock(); for (const [code, status] of [["PT403", 403], ["PT409", 409], ["40001", 409], ["PT422", 422]] as const) { m.client.rpc = async () => ({ data: null, error: { code } }); assert.equal((await performAthleteProfileMutation(request(), m.client, origin)).status, status); } });
