import { basketballStatKeys } from "../src/lib/basketball/contracts";
import { parseGameQuery, projectGameData } from "../src/lib/games/input";
export const basketballId = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
export const gameId = basketballId(1), orgId = basketballId(2), teamId = basketballId(3), athleteId = basketballId(4), otherAthleteId = basketballId(5), playId = basketballId(6);
export const basketballQuery = parseGameQuery({ org: orgId, game: gameId, from: "2026-10-04", to: "2026-10-07" })!;
export const zeroStats = Object.fromEntries(basketballStatKeys.map(key => [key, 0]));
export const fivePointStats = { ...zeroStats, points: 5, fgm: 2, fga: 3, tpm: 1, tpa: 2, rebounds: 2, offensive_rebounds: 1, defensive_rebounds: 1, personal_fouls: 1 };
export const basketballFeatures = { game_center: true, game_operations: true, basketball_live_scoring: true, basketball_stats: true, basketball_play_by_play: true, basketball_lineups: true };
export const basketballRaw = { configured: true, engine_version: "basketball-v1", regulation_periods: 4, period_seconds: 480, overtime_seconds: 240, lineup_size: 5, enforce_lineup: false, period_number: 1, overtime_number: 0, period_status: "active", clock_ms: 379000, clock_running: false, clock_observed_at: "2026-10-04T23:01:41Z", capabilities: { configure: false, operate: true, correct: true, stats: true, lineups: true },
  entry_roster: [{ id: athleteId, side: "primary", display_name: "Controlled athlete", jersey_number: "7", active: true, person_id: "OMIT_PERSON", absence_reason: "OMIT_PRIVATE", checkin_state: "OMIT_CHECKIN" }],
  lineups: [{ side: "primary", roster_ids: [athleteId] }], players: [{ ...fivePointStats, roster_id: athleteId, side: "primary", display_name: "Controlled athlete", jersey_number: "7" }, { ...zeroStats, roster_id: otherAthleteId, side: "opponent", display_name: "OMIT_OTHER_CHILD", jersey_number: "OMIT_JERSEY" }], teams: [{ ...fivePointStats, side: "primary" }, { ...zeroStats, side: "opponent" }], period_fouls: [{ period_number: 1, primary: 1, opponent: 0 }],
  plays: [{ id: playId, sequence: 8, period_number: 1, clock_ms: 379000, side: "primary", event_type: "made_3", points: 3, display_name: "Controlled athlete", jersey_number: "7", roster_id: athleteId, scoring_event_id: null, active: true, actor_person_id: "OMIT_OPERATOR", request_id: "OMIT_REQUEST", reason: "OMIT_REASON", correction_of: "OMIT_CORRECTION" }, { id: basketballId(7), sequence: 9, period_number: 1, clock_ms: 370000, side: "opponent", event_type: "turnover", points: 0, display_name: "OMIT_OTHER_CHILD", jersey_number: "OMIT_JERSEY", roster_id: otherAthleteId, active: true }], more_plays: false,
  final_epochs: [{ epoch: 1, event_sequence: 20, roster_revision: 1, engine_version: "basketball-v1", current_authoritative: false, players: [{ ...fivePointStats, roster_id: athleteId, side: "primary", display_name: "Controlled athlete", jersey_number: "7" }], teams: [{ ...fivePointStats, side: "primary" }] }] };
export const basketballGameRaw = { id: gameId, organization_id: orgId, event_id: basketballId(8), occurrence_key: "2026-10-04T18:00:00", occurrence_mode: "single", version: 10, status: "live", start_at: "2026-10-04T23:00:00Z", end_at: "2026-10-05T00:00:00Z", timezone: "America/Chicago", title: "Controlled basketball game", sport_key: "basketball", sport_label: "Basketball", primary: { team_id: teamId, label: "Falcons", score: 5 }, opponent: { team_id: null, label: "External opponent", score: 0 }, home_away: "home", roster_revision: 1, capabilities: { manage: true, operate: true, finalize: false, correct: true, view_roster: true },
  roster: [{ id: athleteId, person_id: basketballId(9), participant_id: basketballId(10), team_id: teamId, display_name: "Controlled athlete", jersey_number: "7", active: true, revision: 1 }], operators: [], history: [{ id: basketballId(11), sequence: 3, version: 3, operation: "game.score.set", created_at: "2026-10-04T23:00:00Z", summary: "Legacy score summary" }], finalizations: [], engine_locked: true, basketball: basketballRaw };
export function basketballData(changes: Record<string, unknown> = {}, family = false) { const query = family ? { ...basketballQuery, view: "family" as const } : basketballQuery; return projectGameData({ features: basketballFeatures, games: [basketballGameRaw], ...changes }, query)!; }
