import { test } from "node:test";
import assert from "node:assert/strict";
import { bucksQuery, parseBucksCommand } from "../src/lib/boss-bucks/input";
import { previewAmounts } from "../src/lib/boss-bucks/contracts";
import { bucksFailure, performBucksMutation, type BucksClient } from "../src/lib/boss-bucks/mutation";
const id = "70000000-0000-4000-8000-000000000001", origin = "https://platform.boss.invalid";
const command = { action: "wallet.provision", request_id: id, input: { household_id: id, organization_id: id, dependent_person_id: id, currency: "USD" } };
function request(body: unknown = command, suppliedOrigin = origin) { return new Request(`${origin}/app/boss-bucks/mutate`, { method: "POST", headers: { host: "platform.boss.invalid", origin: suppliedOrigin, "content-type": "application/json" }, body: JSON.stringify(body) }); }
test("wallet provisioning excludes client credit and forged context", () => { assert.ok(parseBucksCommand(command)); for (const action of ["grant.issue", "wallet.credit", "mark_paid", "wallet.debit", "transfer", "settle"]) assert.equal(parseBucksCommand({ ...command, action }), null); for (const k of ["balance", "amount_minor", "owner", "policy_revision_id", "role", "source_reference"]) assert.equal(parseBucksCommand({ ...command, input: { ...command.input, [k]: id } }), null); });
test("wallet provisioning requires explicit canonical household and subject", () => { for (const k of ["household_id", "organization_id", "dependent_person_id", "currency"]) { const input = { ...command.input } as Record<string, unknown>; delete input[k]; assert.equal(parseBucksCommand({ ...command, input }), null); } assert.equal(parseBucksCommand({ ...command, input: { ...command.input, currency: "usd" } }), null); });
test("earning policy uses finite bounded basis points and source channels", () => { const p = { action: "policy.create", request_id: id, input: { campaign_id: id, mode: "percentage", basis_points: 5000, currency: "USD", channels: ["direct_support"] } }; assert.ok(parseBucksCommand(p)); for (const n of [-1, 10001, 1.5, NaN, "5000"]) assert.equal(parseBucksCommand({ ...p, input: { ...p.input, basis_points: n } }), null); assert.equal(parseBucksCommand({ ...p, input: { ...p.input, channels: ["arbitrary"] } }), null); assert.equal(parseBucksCommand({ ...p, input: { ...p.input, formula: "100%" } }), null); assert.equal(parseBucksCommand({ ...p, input: { ...p.input, mode: "none" } }), null); });
test("charge preview is read-only integer arithmetic with no negative value", () => { assert.deepEqual(previewAmounts(50000, 15000), { eligible: 15000, remaining: 35000 }); assert.deepEqual(previewAmounts(2000, 9000), { eligible: 2000, remaining: 0 }); assert.deepEqual(previewAmounts(500, 0), { eligible: 0, remaining: 500 }); for (const v of [-1, 1.1, NaN, Infinity, Number.MAX_SAFE_INTEGER + 1]) assert.equal(previewAmounts(100, v), null); });
test("wallet query rejects malformed identifiers, arrays and unsupported activity", () => { assert.deepEqual(bucksQuery({ org: id, child: id }), { mode: "family", organization_id: id, child_id: id }); for (const k of ["org", "wallet", "child", "campaign", "before", "charge", "payments_before"]) { assert.equal(bucksQuery({ [k]: "forged" }), null); assert.equal(bucksQuery({ [k]: [id] }), null); } assert.deepEqual(bucksQuery({ kind: "spend" }), { mode: "family", kind: "spend" }); assert.equal(bucksQuery({ kind: "settlement" }), null); });
test("cross-origin wallet write denied before authentication or RPC", async () => { const client = { rpc: () => { throw new Error("Must not call"); } } as unknown as BucksClient; assert.equal((await performBucksMutation(request(command, "https://evil.invalid"), client, origin)).status, 403); });
test("unsupported credit body denied before authentication or RPC", async () => { const client = { rpc: () => { throw new Error("Must not call"); } } as unknown as BucksClient; assert.equal((await performBucksMutation(request({ ...command, action: "grant.issue" }), client, origin)).status, 422); });
test("wallet backend failures expose no private details", () => { for (const code of ["PT401", "PT403", "PT409", "PT422", "40001", "40P01", "unknown-private-detail"]) { const result = bucksFailure(code); assert.equal(result.body.ok, false); assert.doesNotMatch(JSON.stringify(result), /unknown-private-detail|40001|40P01/); } });

import { bucksMoney } from "../src/lib/boss-bucks/money";
test("wallet amounts retain integer precision above JavaScript safe totals", () => { assert.equal(bucksMoney("9007199254740993", "USD"), "$90,071,992,547,409.93"); assert.equal(bucksMoney("-1", "USD"), "-$0.01"); assert.equal(bucksMoney("1234", "KWD"), "KWD\u00a01.234"); assert.equal(bucksMoney("1234", "JPY"), "¥1,234"); });
