import type { Game } from "../src/lib/games/contracts";
import { defaultDiamondRules } from "../src/components/diamond/console";
import { initialDiamond, transitionDiamond } from "../src/lib/diamond/reducer";
import { resolveSelection, type TrackingPreset } from "../src/lib/stat-tracking/profile";
export const diamondId = (n: number) => `20000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;
export function diamondDemo(sport: "baseball" | "softball" = "baseball", preset: TrackingPreset = "essential"): Game {
 const configuration={...defaultDiamondRules(sport,"opponent"),lineup_size:4};let state=initialDiamond(configuration);
 for(const side of ["primary","opponent"]as const)state=transitionDiamond(configuration,state,{kind:"lineup_set",side,order:Array.from({length:4},(_,i)=>diamondId((side==="primary"?10:20)+i)),positions:{},pitcher:diamondId(side==="primary"?13:23)});
 state=transitionDiamond(configuration,state,{kind:"half_start"});state=transitionDiamond(configuration,state,{kind:"pa_start",key:diamondId(90),batter:diamondId(10),pitch_tracking:preset==="full"});
 const selection=resolveSelection(sport,preset);
 return {id:diamondId(1),organization_id:diamondId(2),event_id:diamondId(3),occurrence_key:"2026-10-05T18:00:00",occurrence_mode:"single",title:"Synthetic Diamond layout",sport_key:sport,sport_label:sport,primary:{team_id:diamondId(4),label:"Synthetic Falcons",score:0,final_score:null},opponent:{team_id:diamondId(5),label:"Synthetic Wildcats",score:0,final_score:null},home_away:"away",competition_type:"standard",start_at:"2026-10-05T23:00:00Z",end_at:"2026-10-06T01:00:00Z",timezone:"America/Chicago",venue_label:null,event_status:"confirmed",status:"live",visibility:"private",publication_state:"draft",version:9,roster_revision:1,finalization_count:0,reopened:false,engine_locked:true,basketball:null,soccer:null,football:null,capabilities:{manage:true,operate:true,correct:true,finalize:false,start:false,resume:false,publish:false,view_roster:true,roster_snapshot:false},roster:[],operators:[],history:[],finalizations:[],diamond:{configured:true,sport_key:sport,engine_version:"diamond-v1",configuration,state,capabilities:{configure:false,operate:true,correct:true,stats:true,lineups:true},entry_roster:["primary","opponent"].flatMap((sd,i)=>Array.from({length:6},(_,j)=>({id:diamondId((i?20:10)+j),side:sd as "primary"|"opponent",display_name:`Synthetic ${sd} athlete ${j+1}`,jersey_number:null,active:true}))),players:[],teams:[{side:"primary",stats:{pitches:{coverage:"not_tracked",recorded_value:null}}},{side:"opponent",stats:{pitches:{coverage:preset==="full"?"tracked":"not_tracked",recorded_value:preset==="full"?0:null}}}],plays:[],final_epochs:[],tracking:{primary:{selection,coverage:{},profile_version:1,can_manage:true},opponent:{selection,coverage:{},profile_version:1,can_manage:true}}}};
}
