import { test } from "node:test";
import assert from "node:assert/strict";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { parseDiscountCommand, parseDiscountPublicCommand, discountsQuery, physicalBatchScope } from "../src/lib/discounts/input";
import { emptyDiscounts, validDiscountData, coverageLabel, eligibleUpgradeMembers, type DiscountMember, type DiscountCatalogItem } from "../src/lib/discounts/contracts";
import { performDiscountMutation, performPublicDiscountMutation, discountFailure, type DiscountsClient, type PublicDiscountsClient } from "../src/lib/discounts/mutation";
import { DigitalCard } from "../src/components/discounts/console";
const id = "70000000-0000-4000-8000-000000000001", other = "70000000-0000-4000-8000-000000000002", path = "a".repeat(48), origin = "https://platform.boss.invalid";
const claim = { action: "card.claim", request_id: id, input: { serial: `BBC-${"A".repeat(32)}`, activation_secret: "a".repeat(64) } };
const request = (body: unknown, source = origin) => new Request(`${origin}/app/boss-bucks/discounts/mutate`, { method: "POST", headers: { host: "platform.boss.invalid", origin: source, "content-type": "application/json" }, body: JSON.stringify(body) });
test("physical claim requires secret and does not accept forged roles or person context", () => { assert.ok(parseDiscountCommand(claim)); for (const key of ["person_id", "actor_id", "organization_id", "entitlement_id", "paid", "source_id", "role", "expires_at"]) assert.equal(parseDiscountCommand({ ...claim, input: { ...claim.input, [key]: id } }), null); for (const activation_secret of [null, "forged", "a".repeat(63), "a".repeat(65), ["a".repeat(64)]]) assert.equal(parseDiscountCommand({ ...claim, input: { ...claim.input, activation_secret } }), null); });
test("mutations have finite membership scope and no cash mark-paid or arbitrary entitlement grant", () => { for (const action of ["card.mark_paid", "order.mark_paid", "membership.grant", "entitlement.grant", "person.merge", "wallet.credit", "merchant.redeem", "payment.capture"]) assert.equal(parseDiscountCommand({ ...claim, action }), null); });
test("bounded inventory rejects duplicate case variants and arbitrary identifiers", () => { const c = { action: "cards.assign", request_id: id, input: { organization_id: id, campaign_id: other, card_ids: [id] } }; assert.ok(parseDiscountCommand(c)); for (const card_ids of [[], [id,id.toUpperCase()], ["forged"], Array(1001).fill(id)]) assert.equal(parseDiscountCommand({ ...c, input: { ...c.input, card_ids } }), null); });
test("public trial excludes recipient identity and forged path", () => { const c = { action: "trial.start", request_id: id, input: { path, revision_id: other, display_name: "Synthetic supporter" } }; assert.ok(parseDiscountPublicCommand(c,path)); for (const key of ["person_id", "household_id", "trial_days", "gift", "ends_at", "role", "country"]) assert.equal(parseDiscountPublicCommand({ ...c, input: { ...c.input, [key]: id } },path), null); assert.equal(parseDiscountPublicCommand(c,"b".repeat(48)),null); });
test("private gift claim requires exact original capability and excludes member-ID guesses", () => { const c = { action: "gift.claim", request_id: id, input: { path, capability: "a".repeat(64) } }; assert.ok(parseDiscountPublicCommand(c,path)); assert.equal(parseDiscountPublicCommand({ ...c, input: { path } },path),null); assert.equal(parseDiscountPublicCommand({ ...c, input: { ...c.input, membership_id: other } },path),null); });
test("client cannot rewrite frozen product economics or trust claimed checkout success", () => { const c = { action: "order.create", request_id: id, input: { revision_id: id, organization_id: other, quantity: 1, method: "card" } }; assert.ok(parseDiscountCommand(c)); for (const key of ["price_minor", "organization_credit_minor", "platform_retained_minor", "currency", "paid", "payment_id", "source_kind", "campaign_id", "fundraiser_id", "tier"]) assert.equal(parseDiscountCommand({ ...c, input: { ...c.input, [key]: 2500 } }),null); });
test("household selectors and fundraiser reports use canonical bounded identities", () => { assert.deepEqual(discountsQuery({ view: "fundraiser", fundraiser: id }), { mode: "fundraiser", fundraiser_id: id }); for (const key of ["org","membership","before","fundraiser"]) { assert.equal(discountsQuery({ [key]: [id] }),null); assert.equal(discountsQuery({ [key]: "forged" }),null); } });
test("cross-origin signed and public writes are denied before RPC", async () => { const client = { rpc: () => { throw new Error("Must not call"); } } as unknown as DiscountsClient; assert.equal((await performDiscountMutation(request(claim,"https://evil.invalid"),client,origin)).status,403); assert.equal((await performPublicDiscountMutation(request(claim,"https://evil.invalid"),client as unknown as PublicDiscountsClient,origin,path)).status,403); });
test("signed claim requires current verified account and does not leak backend details", async () => { const client = { auth: { getUser: async () => ({ data: { user: null }, error: null }) }, rpc: () => { throw new Error("Must not call"); } } as unknown as DiscountsClient; assert.equal((await performDiscountMutation(request(claim),client,origin)).status,401); for (const code of ["PT401","PT403","PT404","PT409","PT422","PT429","23514","private-provider-value"]) assert.doesNotMatch(JSON.stringify(discountFailure(code)),/private-provider-value|23514/); });
test("normal projection rejects nested activation secret, contact and session material", () => { assert.ok(validDiscountData(emptyDiscounts)); for (const key of ["activation_secret","claim_secret","email","address","auth_token","password","credential"]) assert.equal(validDiscountData({ ...emptyDiscounts, cards: [{ id, [key]: "Private synthetic sentinel" }] }),false); });
const member: DiscountMember = { id, display_id: "BBD-CONTROLLED", name: "Boss Bucks Discounts", display_name: "Controlled member", subject_type: "person", base_source_id: other, effective: { available: true, state: "trial", tier: "local", source: "fundraising_trial", starts_at: "2026-10-07T00:00:00Z", ends_at: "2026-11-06T00:00:00Z", source_id: other, country: "US", region: "VA", market: "Controlled market" }, sources: [{ kind: "fundraising_trial", tier: "local", starts_at: "2026-10-07T00:00:00Z", ends_at: "2026-11-06T00:00:00Z", revoked: false }], cards: [] };
test("digital card presents brand, source, configured country, status and dates without Wallet balance", () => { const html = renderToStaticMarkup(createElement(DigitalCard,{ membership: member })); for (const text of ["BOSS BUCKS DISCOUNTS","Controlled member","Controlled market","VA, US","fundraising trial","BBD-CONTROLLED","Nov 6, 2026"]) assert.ok(html.includes(text)); assert.doesNotMatch(html,/Wallet balance|merchant offer|activation_secret|claim_secret/); });
test("expired digital card does not display active coverage", () => { const html = renderToStaticMarkup(createElement(DigitalCard,{ membership: { ...member, effective: { ...member.effective, available: false, state: "expired", tier: null, source: null } } })); assert.match(html,/NO ACTIVE DIGITAL ACCESS/); assert.match(html,/expired/); });
test("nationwide label preserves country and active-market limitation", () => { assert.equal(coverageLabel("nationwide","CA","ON","Toronto"),"Nationwide in CA, where Boss Bucks markets are active"); });
test("public purchase dispatch reuses the canonical payment support RPC and exact URL context", async () => {
 let called = "", sent: unknown;
 const client: PublicDiscountsClient = { rpc: async (name,args) => { called = name;sent = args.command;return { data: { state: "payment_pending", order_id: id, checkout_id: other, replayed: false },error: null }; } };
 const command = { action: "product.prepare", request_id: id, input: { path, capability: "f".repeat(64), revision_id: id, organization_id: other, quantity: 1, method: "card" } };
 const result = await performPublicDiscountMutation(request(command),client,origin,path);
 assert.equal(called,"boss_payments_support");assert.deepEqual(sent,command);assert.equal(result.status,200);assert.doesNotMatch(JSON.stringify(result.body),/order_id|checkout_id|capability/);
 const status = { action: "product.status",request_id: other,input: { path,capability: "f".repeat(64) } };
 await performPublicDiscountMutation(request(status),client,origin,path);assert.deepEqual(sent,status);
});
test("public receipt rejects nested contact or credential fields in order items", async () => {
 const command = { action: "product.status",request_id: id,input: { path,capability: "f".repeat(64) } };
 for (const field of ["email","address","activation_secret","auth_token","person_id"]) {
  const client: PublicDiscountsClient = { rpc: async () => ({ data: { state: "fulfilled", items: [{ item_id: id,kind: "digital",state: "pending_claim",[field]: "PRIVATE-SENTINEL" }] },error: null }) };
  const result = await performPublicDiscountMutation(request(command),client,origin,path);assert.equal(result.status,503);assert.doesNotMatch(JSON.stringify(result.body),/PRIVATE-SENTINEL/);
 }
});

test("upgrade choices require the same subject, product, geography and permitted current tier", () => {
 const current = { ...member,product_id:id };
 const product = { membership_product_id:id,subject_type:"person",country:"US",region:"VA",market:"Controlled market",upgrade_from_tiers:["local"] } as DiscountCatalogItem;
 assert.deepEqual(eligibleUpgradeMembers([current],product),[current]);
 for (const changed of [{...current,product_id:other},{...current,subject_type:"household" as const},{...current,base_source_id:null},{...current,effective:{...current.effective,available:false}},{...current,effective:{...current.effective,region:"NY"}},{...current,effective:{...current.effective,tier:"state" as const}}]) assert.deepEqual(eligibleUpgradeMembers([changed],product),[]);
});

test("unassigned platform stock omits organization while organization and campaign ownership preserve exact scope", () => { assert.deepEqual(physicalBatchScope(id,"platform",true),{}); for (const owner of ["organization","campaign","platform"]) { assert.deepEqual(physicalBatchScope(id,owner,false),{organization_id:id}); } for (const owner of ["organization","campaign"]) { assert.deepEqual(physicalBatchScope(id,owner,true),{organization_id:id}); } });
