import { footballStatKeys } from "../src/lib/football/contracts";
import { projectGameData } from "../src/lib/games/input";
import { basketballGameRaw, basketballId, basketballQuery, gameId, orgId, teamId, athleteId, otherAthleteId, playId } from "./basketball-fixture";
export { basketballId as footballId, gameId, orgId, teamId, athleteId, otherAthleteId, playId };
export const receiverId = basketballId(201), defenderId = basketballId(202);
export const footballQuery = basketballQuery;
export const zeroStats = { ...Object.fromEntries(footballStatKeys.map(key => [key, 0])), long_field_goal: null };
export const passerStats = { ...zeroStats, passing_completions: 1, passing_attempts: 2, passing_yards: 12, net_passing_yards: 7, total_offensive_yards: 7, sacks_taken: 1, sack_yards_lost: 5 };
export const field = { possession_side: "primary", ball_spot: 42, down: 2, distance: 8, line_to_gain: 50, goal_to_go: false, primary_direction: "increasing", drive_number: 1, phase: "scrimmage", scoring_side: null };
export const footballFeatures = { game_center: true, game_operations: true, football_live_scoring: true, football_stats: true, football_play_by_play: true, football_lineups: true };
const plays = [{ id: playId, sequence: 8, origin_sequence: 8, period_number: 1, clock_ms: 379000, side: "primary", type: "pass_complete", payload: { roster_id: athleteId, receiver_roster_id: receiverId, defender_roster_id: otherAthleteId, assisting_roster_ids: [defenderId, otherAthleteId], yards: 12, touchdown: false, reason: "OMIT_REASON", actor_person_id: "OMIT_ACTOR" }, before_field: { ...field, ball_spot: 30, down: 1, distance: 10, line_to_gain: 40 }, after_field: field, active: true, request_id: "OMIT_REQUEST" }];
export const footballRaw = { configured: true, engine_version: "football-v1", quarter_seconds: 720, overtime_format: "none", overtime_seconds: 300, max_overtime_periods: 0, play_clock_seconds: 40, lineup_size: 2, enforce_lineup: true, kneel_counts_as_rush: false, period_number: 1, period_status: "active", clock_ms: 379000, clock_running: false, clock_observed_at: "2026-10-04T23:01:41Z", field_state: field, capabilities: { configure: false, operate: true, correct: true, stats: true, lineups: true },
  entry_roster: [{ id: athleteId, side: "primary", display_name: "Controlled passer", jersey_number: "7", active: true, person_id: "OMIT_PERSON", absence_reason: "OMIT_PRIVATE" }, { id: receiverId, side: "primary", display_name: "Controlled receiver", jersey_number: "9", active: true }, { id: defenderId, side: "opponent", display_name: "Controlled defender", jersey_number: "5", active: true }],
  lineups: [{ side: "primary", roster_ids: [athleteId, receiverId] }, { side: "opponent", roster_ids: [defenderId] }],
  players: [{ roster_id: athleteId, side: "primary", display_name: "Controlled passer", jersey_number: "7", stats: passerStats }, { roster_id: receiverId, side: "primary", display_name: "Controlled receiver", jersey_number: "9", stats: { ...zeroStats, receptions: 1, targets: 1, receiving_yards: 12 } }, { roster_id: otherAthleteId, side: "opponent", display_name: "OMIT_OTHER_CHILD", stats: zeroStats }], teams: [{ side: "primary", stats: passerStats }, { side: "opponent", stats: zeroStats }], plays, entry_plays: plays, more_plays: false,
  drives: [{ drive_number: 1, side: "primary", start_period: 1, start_clock_ms: 400000, start_ball_spot: 30, end_period: null, end_clock_ms: null, end_ball_spot: null, play_count: 1, end_reason: null, result: null }], final_epochs: [{ epoch: 1, event_cutoff: 20, game_version: 21, roster_revision: 1, engine_version: "football-v1", current_authoritative: false, players: [{ roster_id: athleteId, side: "primary", display_name: "Controlled passer", stats: passerStats }], teams: [{ side: "primary", stats: passerStats }] }] };
export const footballGameRaw = { ...basketballGameRaw, title: "Controlled football game", sport_key: "football", sport_label: "Football", basketball: null, soccer: null, football: footballRaw, primary: { ...basketballGameRaw.primary, score: 0 } };
export function footballData(changes: Record<string, unknown> = {}, family = false) { return projectGameData({ features: footballFeatures, games: [footballGameRaw], ...changes }, family ? { ...footballQuery, view: "family" } : footballQuery)!; }
