import test from "node:test";import assert from "node:assert/strict";import {createElement}from"react";import{renderToStaticMarkup}from"react-dom/server";import{AppRouterContext,type AppRouterInstance}from"next/dist/shared/lib/app-router-context.shared-runtime";
import{PARTNER_CAPABILITIES,PARTNER_METHODS,currentPartnerAccess,validAdminData,type PartnerAccess}from"../src/lib/partners/contracts";
import{disabledAdapter,syntheticAdapter,inspectTravel,recheckQuote,inspectGiftCard,commissionEstimate,type TravelQuote,type GiftCard,type CommissionPolicy,type CommissionSource}from"../src/lib/partners/adapters";
import{parsePartnerCommand,validPartnerReceipt}from"../src/lib/partners/input";import{performPartnerMutation,type PartnerClient}from"../src/lib/partners/mutation";import{PartnerWorkspace}from"../src/components/partners/workspace";import{PartnerDiscovery}from"../src/components/partners/discovery";
const id="80000000-0000-4000-8000-000000000001",origin="https://platform.boss.invalid",now=Date.parse("2026-10-01T00:00:00Z");
const quote:TravelQuote={providerId:id,sourceRevision:"1",propertyId:"synthetic-property",ratePlan:"synthetic-rate",destination:"Synthetic destination",startsOn:"2026-11-01",endsOn:"2026-11-02",travelers:2,country:"US",tier:"nationwide",currency:"USD",priceMinor:"10000",taxMinor:"500",feeMinor:"200",available:true,expiresAt:"2026-10-02T00:00:00Z",cancellationTerms:"Synthetic cancellation policy"};
const card:GiftCard={providerId:id,externalId:"synthetic-card",brand:"Synthetic brand",country:"US",currency:"USD",denominationMinor:"10000",faceMinor:"10000",purchaseMinor:"9000",delivery:"digital",expiresAt:"2026-10-02T00:00:00Z",withdrawn:false,refundTerms:"Synthetic refund terms",commissionPolicyId:null};
const policy:CommissionPolicy={id,contractRevision:"approved-synthetic-revision",currency:"USD",basis:"percentage",fixedMinor:null,ratePpm:100000,startsAt:"2026-09-01T00:00:00Z",endsAt:"2026-11-01T00:00:00Z",condition:"fulfilled"};
const source:CommissionSource={providerId:id,transactionId:"synthetic-transaction",externalEventId:"synthetic-event",currency:"USD",eligibleMinor:"10000",occurredAt:"2026-10-01T00:00:00Z",condition:"fulfilled",refundMinor:"0",canceled:false,evidenceReference:"synthetic-evidence/source"};
for(const method of PARTNER_METHODS)test(`all ${method} adapters are disabled without transport`,async()=>{const a=disabledAdapter(id,method,PARTNER_CAPABILITIES);for(const c of PARTNER_CAPABILITIES)assert.deepEqual(await a.execute(c,{} as never),{ok:false,category:"activation_disabled"});});
test("unsupported capability and explicit synthetic adapters",async()=>{assert.deepEqual(await disabledAdapter(id,"rest",[]).execute("catalog_read",{sequence:1,kind:"full"}),{ok:false,category:"capability_unsupported"});assert.throws(()=>syntheticAdapter("real"as`fixture:${string}`,{}));assert.deepEqual(await syntheticAdapter("fixture:local",{catalog_read:{sequence:1,items:[]}}).execute("catalog_read",{sequence:1,kind:"full"}),{ok:true,value:{sequence:1,items:[]}});});
for(const discount of[false,true])for(const commission of[false,true])test(`travel availability separate discount=${discount} commission=${commission}`,()=>{const q={...quote,...(discount?{comparison:{approvedPolicyReference:"synthetic-comparison",comparisonMinor:"12000"}}:{}),...(commission?{commission:{approvedContractRevision:"synthetic-contract",policyId:id}}:{})};assert.deepEqual(inspectTravel(q,now,"US","nationwide"),{ok:true,value:{available:true,discounted:discount,commissionable:commission}});});
for(const [name,extra,country,tier,category]of[["expired",{expiresAt:"2026-09-30T00:00:00Z"},"US","nationwide","quote_expired"],["wrong country",{},"CA","nationwide","territory_unsupported"],["wrong tier",{},"US","local","invalid_source_record"],["bad currency",{currency:"USDx"},"US","nationwide","invalid_source_record"],["negative taxes",{taxMinor:"-1"},"US","nationwide","invalid_source_record"]]as const)test(`travel rejects ${name}`,()=>assert.deepEqual(inspectTravel({...quote,...extra},now,country,tier),{ok:false,category}));
test("unavailable travel and changed recheck are not guaranteed prices",()=>{assert.deepEqual(inspectTravel({...quote,available:false},now,"US","nationwide"),{ok:true,value:{available:false,discounted:false,commissionable:false}});assert.deepEqual(recheckQuote(quote,{...quote,priceMinor:"10001"},now,"US","nationwide"),{ok:false,category:"invalid_source_record"});assert.deepEqual(recheckQuote(quote,{...quote,available:false},now,"US","nationwide"),{ok:false,category:"provider_unavailable"});assert.equal(recheckQuote(quote,quote,now,"US","nationwide").ok,true);});
for(const[name,extra,country,expected]of[["discount",{},"US",{ok:true,value:{discountMinor:"1000",issuanceEnabled:false}}],["wrong country",{},"CA",{ok:false,category:"territory_unsupported"}],["withdrawn",{withdrawn:true},"US",{ok:false,category:"stale_catalog"}],["expired",{expiresAt:"2026-09-01T00:00:00Z"},"US",{ok:false,category:"stale_catalog"}],["denomination mismatch",{denominationMinor:"5000"},"US",{ok:false,category:"invalid_source_record"}],["fractional minor units",{purchaseMinor:"9.00"},"US",{ok:false,category:"invalid_source_record"}],["above face",{purchaseMinor:"10001"},"US",{ok:false,category:"invalid_source_record"}]]as const)test(`gift card ${name}`,()=>assert.deepEqual(inspectGiftCard({...card,...extra},now,country),expected));
for(const[name,p,s,amount]of[["percentage",policy,source,"1000"],["fixed",{...policy,basis:"fixed",fixedMinor:"750",ratePpm:null},source,"750"],["zero",{...policy,basis:"zero",ratePpm:null},source,"0"],["unknown",{...policy,basis:"unknown",ratePpm:null},source,null],["canceled",policy,{...source,canceled:true},"0"],["partial refund",policy,{...source,refundMinor:"2500"},"750"],["unknown fixed refund treatment",{...policy,basis:"fixed",fixedMinor:"750",ratePpm:null},{...source,refundMinor:"2500"},null],["delayed confirmation",policy,{...source,condition:"confirmed"},null]]as const)test(`synthetic commission ${name}`,()=>assert.deepEqual(commissionEstimate(p,s),{ok:true,value:{estimatedMinor:amount,earnedRevenue:false,settlementExecuted:false}}));
test("cross currency, expired contract and over-refund denied",()=>{assert.deepEqual(commissionEstimate(policy,{...source,currency:"CAD"}),{ok:false,category:"invalid_source_record"});assert.deepEqual(commissionEstimate(policy,{...source,occurredAt:"2026-12-01T00:00:00Z"}),{ok:false,category:"contract_inactive"});assert.deepEqual(commissionEstimate(policy,{...source,refundMinor:"10001"}),{ok:false,category:"invalid_source_record"});});
test("all independent access facts required",()=>{const a:PartnerAccess={membershipEligible:true,territoryEligible:true,catalogAvailable:true,licensingValid:true,providerOperational:true,fulfillmentPossible:true};assert.ok(currentPartnerAccess(a));for(const k of Object.keys(a))assert.equal(currentPartnerAccess({...a,[k]:false}),false);});
test("finite inputs reject client authority or credential assertions",()=>{const c={request_id:id,action:"provider.create",input:{key:"synthetic",name:"Synthetic",synthetic:true}};assert.ok(parsePartnerCommand(c));for(const k of["token","password","role","organization_id","household_id","actor_id","operational","credentials_ready"])assert.equal(parsePartnerCommand({...c,input:{...c.input,[k]:id}}),null);assert.ok(parsePartnerCommand({request_id:id,action:"transaction.event",input:{provider_id:id,transaction_id:id,external_event_id:"synthetic-external"}}));});
test("receipts cannot carry private data",()=>{assert.ok(validPartnerReceipt({resource_id:id,provider_id:id,accepted:1}));for(const extra of[{credential_reference:"private"},{token:"private"},{accepted:-1},{provider_id:null}])assert.equal(validPartnerReceipt({resource_id:id,provider_id:id,...extra}),false);});
test("cross origin and oversized mutation denied before RPC",async()=>{const client={rpc(){throw new Error("No call");}}as unknown as PartnerClient;const body={request_id:id,action:"provider.create",input:{key:"synthetic",name:"Synthetic"}};const req=(header:string,data:unknown)=>new Request(origin+"/app/partners/mutate",{method:"POST",headers:{host:"platform.boss.invalid",origin:header,"content-type":"application/json"},body:JSON.stringify(data)});assert.equal((await performPartnerMutation(req("https://evil.invalid",body),client,origin)).status,403);assert.equal((await performPartnerMutation(req(origin,{...body,input:{...body.input,padding:"x".repeat(1_048_577)}}),client,origin)).status,422);});
test("safe admin contract rejects private values",()=>{const d={operational:false,providers:[{id,key:"synthetic",name:"Synthetic",state:"prospect",version:1,synthetic:true,configuration:{},source_count:0}]};assert.ok(validAdminData(d));assert.equal(validAdminData({...d,token:"private"}),false);assert.equal(validAdminData({...d,providers:[{...d.providers[0],configuration:{secret:"private"}}]}),false);});
test("empty discovery and restricted rendering never offer live mock transactions",()=>{const router:AppRouterInstance={bfcacheId:"partner",back(){},forward(){},push(){},replace(){},refresh(){},prefetch(){}};const html=renderToStaticMarkup(createElement(PartnerDiscovery));assert.match(html,/No approved partner benefits/);assert.doesNotMatch(html,/Redeem|Book now|Buy card/);const restricted=renderToStaticMarkup(createElement(AppRouterContext.Provider,{value:router},createElement(PartnerWorkspace,{data:{unavailable:true,restricted:true}})));assert.match(restricted,/restricted/);assert.doesNotMatch(restricted,/Add prospect/);});
test("malformed calendar dates and unknown commission lifecycle fail closed",()=>{
 assert.deepEqual(inspectTravel({...quote,startsOn:"2026-02-30"},now,"US","nationwide"),{ok:false,category:"invalid_source_record"});
 assert.deepEqual(commissionEstimate({...policy,condition:"unknown" as never},source),{ok:false,category:"invalid_source_record"});
 assert.deepEqual(commissionEstimate(policy,{...source,condition:"invented" as never}),{ok:false,category:"invalid_source_record"});
});
test("real-shaped policy projection renders and malformed field types are rejected",()=>{
 const c={id,revision:1,document_reference:"legal-reference/synthetic",countries:["US"],categories:["travel"],product_id:id,starts_at:"2026-10-01T00:00:00+00:00",ends_at:"2026-11-01T00:00:00+00:00",display_rights:true,caching_rights:true,state:"approved",can_approve:false};
 const d={operational:false as const,providers:[{id,key:"synthetic",name:"Synthetic",state:"configured" as const,version:5,synthetic:true,configuration:{},source_count:1}],details:{contracts:[c],territories:[],imports:[],catalog:[]}};
 assert.ok(validAdminData(d));
 for(const extra of[{countries:true},{ends_at:false},{can_approve:"false"},{revision:-1}])assert.equal(validAdminData({...d,details:{...d.details,contracts:[{...c,...extra}]}}),false);
 const router:AppRouterInstance={bfcacheId:"partner-detail",back(){},forward(){},push(){},replace(){},refresh(){},prefetch(){}};
 const html=renderToStaticMarkup(createElement(AppRouterContext.Provider,{value:router},createElement(PartnerWorkspace,{data:d})));assert.match(html,/Contract revision 1/);assert.match(html,/Record approved territory/);assert.doesNotMatch(html,/Activate integration/);
});
const partnerRequest=()=>new Request(origin+"/app/partners/mutate",{method:"POST",headers:{host:"platform.boss.invalid",origin,"content-type":"application/json"},body:JSON.stringify({request_id:id,action:"provider.create",input:{key:"synthetic",name:"Synthetic"}})});
const syntheticPartnerClient=(data:unknown,error:{code?:string}|null=null,user=id):PartnerClient=>({auth:{getClaims:async()=>({data:{claims:{sub:id,iss:"https://ilykgwgmxtrrikreacrz.supabase.co/auth/v1",role:"authenticated",exp:Math.floor(Date.now()/1000)+60,is_anonymous:false}},error:null}),getUser:async()=>({data:{user:{id:user,is_anonymous:false}},error:null})},rpc:async()=>({data,error})});
test("verified partner response confirms only a safe committed receipt",async()=>{
 const receipt={resource_id:id,provider_id:id,version:1};assert.deepEqual(await performPartnerMutation(partnerRequest(),syntheticPartnerClient(receipt),origin),{status:200,body:{ok:true,...receipt}});
});
test("unconfirmed or private provider results cannot produce success or expose details",async()=>{
 for(const client of[syntheticPartnerClient({resource_id:id,provider_id:id,debug:"synthetic-private-detail"}),syntheticPartnerClient(null,{code:"synthetic-private-error"})]){
  const result=await performPartnerMutation(partnerRequest(),client,origin);assert.equal(result.status,503);assert.equal("outcome"in result.body&&result.body.outcome,"unknown");assert.doesNotMatch(JSON.stringify(result),/synthetic-private/);
 }
 const denied=await performPartnerMutation(partnerRequest(),syntheticPartnerClient(null,{code:"PT403"}),origin);assert.equal(denied.status,403);assert.equal("outcome"in denied.body&&denied.body.outcome,"rejected");
});
test("changed current identity cannot reach the provider RPC",async()=>{
 let called=false;const client=syntheticPartnerClient(null,null,"80000000-0000-4000-8000-000000000002");client.rpc=async()=>{called=true;return{data:null,error:null};};assert.equal((await performPartnerMutation(partnerRequest(),client,origin)).status,401);assert.equal(called,false);
});
