import test from"node:test";import assert from"node:assert/strict";
import{emitPartnerDiagnostic,partnerDiagnosticRecord,partnerErrorDetails,partnerDiagnosticRoute,PARTNER_DIAGNOSTIC_PREFIX,PARTNER_CORRELATION_HEADER,PARTNER_PARENT_HEADER,type PartnerDiagnosticInput}from"../src/lib/partners/diagnostics";
import{clearPartnerClientTrace,partnerClientDiagnostic,partnerClientRendered}from"../src/lib/partners/diagnostics-client";
import{requestPartnerMutation}from"../src/lib/partners/action";import{onRequestError}from"../src/instrumentation";
import type{PartnerCommand}from"../src/lib/partners/input";
const a="90000000-0000-4000-8000-000000000001",b="90000000-0000-4000-8000-000000000002",c="90000000-0000-4000-8000-000000000003";
const base:PartnerDiagnosticInput={correlationId:a,phase:"server-component",stage:"server_exception",observedAt:"src/app/app/partners/page.tsx"};
const command:PartnerCommand={request_id:a,action:"provider.create",input:{key:"synthetic-provider",name:"Synthetic private provider",synthetic:true}};
async function capture(run:()=>unknown){const lines:string[]=[],old=console.info;console.info=(line:string)=>lines.push(line);try{await run();}finally{console.info=old;}return lines.map(line=>{assert.ok(line.startsWith(PARTNER_DIAGNOSTIC_PREFIX));return JSON.parse(line.slice(PARTNER_DIAGNOSTIC_PREFIX.length));});}
async function browser(run:()=>unknown){const original=Object.getOwnPropertyDescriptor(globalThis,"window");Object.defineProperty(globalThis,"window",{configurable:true,value:{location:{pathname:"/app/partners"}}});try{clearPartnerClientTrace();return await run();}finally{clearPartnerClientTrace();if(original)Object.defineProperty(globalThis,"window",original);else Reflect.deleteProperty(globalThis,"window");}}
test("Partner records exclude commands, personal identifiers, terms and confidential exception values",()=>{
 const sentinel="SYNTHETIC_PRIVATE_SENTINEL",error=Object.assign(new TypeError(sentinel),{digest:"12345",token:sentinel,headers:{cookie:sentinel},body:sentinel});error.stack=`TypeError: ${sentinel}\n at render (/private/${sentinel}/src/components/partners/workspace.tsx:20:4)`;
 const r=partnerDiagnosticRecord({...base,error,provider_id:sentinel,command,request:sentinel}as PartnerDiagnosticInput);assert.ok(r);assert.doesNotMatch(JSON.stringify(r),/SYNTHETIC_PRIVATE|private provider/);assert.deepEqual(r.source,{file:"src/components/partners/workspace.tsx",line:20,column:4});assert.equal(r.digest,"12345");assert.equal(r.exception_category,"TypeError");assert.deepEqual(Object.keys(r).sort(),["schema","timestamp","commit","deployment","route","phase","stage","correlation_id","parent_correlation_id","observed_at","operation","classification","trace_state","http_status","exception_category","digest","source"].sort());
});
test("Partner channel rejects invalid enums, unsafe digests and unlisted/query-bearing frames",()=>{
 for(const extra of[{correlationId:"PRIVATE"},{stage:"PRIVATE"},{phase:"PRIVATE"},{observedAt:"PRIVATE"}])assert.equal(partnerDiagnosticRecord({...base,...extra}as PartnerDiagnosticInput),null);
 const r=partnerDiagnosticRecord({...base,operation:"PRIVATE"as never,route:"PRIVATE"as never,parentCorrelationId:"PRIVATE",error:{name:"PRIVATE",digest:"PRIVATE",stack:"Error\n at /src/app/app/partners/page.tsx:3:4?token=PRIVATE"}});assert.ok(r);assert.equal(r.operation,null);assert.equal(r.parent_correlation_id,null);assert.equal(r.source,null);assert.equal(r.digest,null);assert.equal(r.exception_category,"UnknownError");
 for(const stack of["Error: src/app/app/partners/page.tsx:3:4","Error\n at /unlisted.ts:1:2","x".repeat(32001)])assert.equal(partnerErrorDetails({stack}).source,null);
 for(const path of["/app/account","/app/partners-other","https://private.invalid/app/partners"])assert.equal(partnerDiagnosticRoute(path),null);assert.equal(partnerDiagnosticRoute("/app/partners/discovery?person=PRIVATE"),"/app/partners/discovery");
});
test("hostile getters and broken diagnostic sinks cannot break a confirmed mutation",async()=>{
 assert.doesNotThrow(()=>emitPartnerDiagnostic({...base,error:new Proxy({},{get(){throw Error("PRIVATE");}})},()=>{throw Error("PRIVATE");}));
 await browser(async()=>{const old=console.info;console.info=()=>{throw Error("PRIVATE");};try{assert.equal((await requestPartnerMutation(command,async()=>new Response(JSON.stringify({ok:true,resource_id:a,provider_id:a}),{status:200,headers:{[PARTNER_CORRELATION_HEADER]:b}}))).outcome,"confirmed-success");}finally{console.info=old;}});
});
test("Next Partner server hook keeps the opaque trace while omitting headers/query/context",async()=>{
 const rows=await capture(()=>onRequestError({name:"Error",digest:"567",message:"PRIVATE",stack:"Error: PRIVATE\n at fail (/src/app/app/partners/page.tsx:4:8)"},{path:"/app/partners?provider_id=PRIVATE",method:"GET",headers:{[PARTNER_CORRELATION_HEADER]:a,[PARTNER_PARENT_HEADER]:b,cookie:"PRIVATE"}},{routerKind:"App Router",routePath:"PRIVATE",routeType:"render",renderSource:"server-rendering",revalidateReason:undefined}));assert.equal(rows.length,1);assert.equal(rows[0].correlation_id,a);assert.equal(rows[0].parent_correlation_id,b);assert.equal(rows[0].phase,"server-render");assert.doesNotMatch(JSON.stringify(rows),/PRIVATE/);
});
test("read, mutation response, refresh and new render link without business identifiers",async()=>{
 await browser(async()=>{const rows=await capture(async()=>{partnerClientRendered(a);let body="";const result=await requestPartnerMutation(command,async(_url,init)=>{body=String(init?.body);assert.ok(new Headers(init?.headers).get(PARTNER_PARENT_HEADER));return new Response(JSON.stringify({ok:true,resource_id:c,provider_id:c}),{status:200,headers:{[PARTNER_CORRELATION_HEADER]:b}});});assert.equal(body,JSON.stringify(command));assert.equal(result.outcome,"confirmed-success");partnerClientDiagnostic({stage:"refresh_requested",observedAt:"src/components/partners/workspace.tsx",operation:"provider.create"});partnerClientRendered(c);});assert.equal(rows[1].parent_correlation_id,a);assert.equal(rows[2].parent_correlation_id,rows[1].correlation_id);assert.equal(rows[2].correlation_id,b);assert.equal(rows[3].stage,"response_accepted");assert.equal(rows[4].correlation_id,b);assert.equal(rows[5].parent_correlation_id,b);assert.doesNotMatch(JSON.stringify(rows),/private provider|synthetic-provider|request_id|resource_id|provider_id/);});
});
test("lost confirmation retries the identical original request, never a new business request",async()=>{
 await browser(async()=>{const sent:string[]=[];const rows=await capture(async()=>{const fetcher:typeof fetch=async(_url,init)=>{sent.push(String(init?.body));if(sent.length===1)throw Error("PRIVATE");return new Response(JSON.stringify({ok:true,resource_id:a,provider_id:a}),{status:200,headers:{[PARTNER_CORRELATION_HEADER]:b}});};assert.equal((await requestPartnerMutation(command,fetcher)).outcome,"unknown");assert.equal((await requestPartnerMutation(command,fetcher,true)).outcome,"confirmed-success");});assert.deepEqual(sent,[JSON.stringify(command),JSON.stringify(command)]);assert.ok(rows.some(r=>r.stage==="unknown_confirmation"));assert.ok(rows.some(r=>r.stage==="reconciliation_attempted"));assert.doesNotMatch(JSON.stringify(rows),/PRIVATE/);});
});
test("invalid JSON/receipt cannot become success; retry rejection stays unknown",async()=>{
 await browser(async()=>{for(const payload of["bad json",JSON.stringify({ok:true,resource_id:a,provider_id:a,private:"PRIVATE"})]){const rows=await capture(async()=>assert.equal((await requestPartnerMutation(command,async()=>new Response(payload,{status:200}))).outcome,"unknown"));assert.ok(rows.some(r=>r.stage==="unknown_confirmation"));assert.ok(!rows.some(r=>r.stage==="response_accepted"));assert.doesNotMatch(JSON.stringify(rows),/PRIVATE/);}await capture(async()=>{const fetcher:typeof fetch=async()=>new Response(JSON.stringify({ok:false,outcome:"rejected",error:"PRIVATE"}),{status:403});assert.equal((await requestPartnerMutation(command,fetcher)).outcome,"confirmed-rejection");assert.equal((await requestPartnerMutation(command,fetcher,true)).outcome,"unknown");});});
});
test("accepted confirmation survives an error boundary with refresh-failed classification",async()=>{
 await browser(async()=>{const rows=await capture(async()=>{await requestPartnerMutation(command,async()=>new Response(JSON.stringify({ok:true,resource_id:a,provider_id:a}),{status:200,headers:{[PARTNER_CORRELATION_HEADER]:b}}));partnerClientDiagnostic({stage:"error_boundary",observedAt:"src/app/error.tsx",error:new TypeError("PRIVATE")});partnerClientDiagnostic({stage:"retry_requested",observedAt:"src/app/error.tsx"});});assert.ok(rows.some(r=>r.classification==="confirmed-success"));assert.equal(rows.at(-2).classification,"refresh-failed");assert.equal(rows.at(-2).correlation_id,b);assert.doesNotMatch(JSON.stringify(rows),/PRIVATE/);});
});
test("initial-read boundary and retry share an ephemeral trace even before any rendered page",async()=>{await browser(async()=>{const rows=await capture(()=>{partnerClientDiagnostic({stage:"error_boundary",observedAt:"src/app/error.tsx",error:new Error("PRIVATE")});partnerClientDiagnostic({stage:"retry_requested",observedAt:"src/app/error.tsx"});});assert.equal(rows[0].correlation_id,rows[1].correlation_id);});});
