import { soccerStatKeys } from "../src/lib/soccer/contracts";
import { projectGameData } from "../src/lib/games/input";
import { basketballGameRaw, basketballId, basketballQuery, gameId, orgId, teamId, athleteId, otherAthleteId, playId } from "./basketball-fixture";
export { basketballId as soccerId, gameId, orgId, teamId, athleteId, otherAthleteId, playId };
export const keeperId = basketballId(101), substituteId = basketballId(102);
export const soccerQuery = basketballQuery;
export const zeroStats = { ...Object.fromEntries(soccerStatKeys.map(key => [key, 0])), goals_allowed: null, minutes: null, clean_sheet: null };
export const scorerStats = { ...zeroStats, goals: 2, assists: 1, shots: 3, shots_on_goal: 2, yellow_cards: 1, minutes: 2.5 };
export const soccerFeatures = { game_center: true, game_operations: true, soccer_live_scoring: true, soccer_stats: true, soccer_play_by_play: true, soccer_lineups: true };
const soccerPlays = [{ id: playId, sequence: 8, segment_number: 1, clock_ms: 90000, display_clock_ms: 90000, playing_ms: 90000, side: "primary", event_type: "goal", display_name: "Controlled scorer", jersey_number: "7", roster_id: athleteId, goalkeeper_roster_id: null, scoring_event_id: null, active: true, request_id: "OMIT_REQUEST", reason: "OMIT_REASON", actor_person_id: "OMIT_OPERATOR" }, { id: basketballId(103), sequence: 9, segment_number: 1, clock_ms: 120000, display_clock_ms: 120000, playing_ms: 120000, side: "primary", event_type: "own_goal", display_name: "Controlled scorer", jersey_number: "7", roster_id: athleteId, active: true }, { id: basketballId(104), sequence: 10, segment_number: 1, clock_ms: 150000, display_clock_ms: 150000, playing_ms: 150000, side: "opponent", event_type: "goal", display_name: "OMIT_OTHER_CHILD", jersey_number: "OMIT_JERSEY", roster_id: otherAthleteId, active: true }];
export const soccerRaw = { configured: true, engine_version: "soccer-v1", regulation_segments: 2, segment_seconds: 2700, extra_time_segments: 2, extra_time_seconds: 900, lineup_size: 2, enforce_lineup: true, allow_reentry: false, max_substitutions: 3, segment_number: 1, extra_time_number: 0, segment_status: "active", clock_ms: 150000, display_clock_ms: 150000, playing_ms: 150000, clock_running: false, clock_observed_at: "2026-10-04T23:02:30Z", added_time_seconds: 120, participation_complete: true, capabilities: { configure: false, operate: true, correct: true, stats: true, lineups: true },
  entry_roster: [{ id: athleteId, side: "primary", display_name: "Controlled scorer", jersey_number: "7", active: true, person_id: "OMIT_PERSON", absence_reason: "OMIT_PRIVATE" }, { id: keeperId, side: "primary", display_name: "Controlled keeper", jersey_number: "1", active: true }, { id: substituteId, side: "primary", display_name: "Controlled substitute", jersey_number: "9", active: true }],
  lineups: [{ side: "primary", roster_ids: [athleteId, keeperId], goalkeeper_roster_id: keeperId, dismissed_roster_ids: [] }],
  players: [{ ...scorerStats, roster_id: athleteId, side: "primary", display_name: "Controlled scorer", jersey_number: "7" }, { ...zeroStats, saves: 2, goals_allowed: 1, minutes: 2.5, roster_id: keeperId, side: "primary", display_name: "Controlled keeper", jersey_number: "1" }, { ...zeroStats, roster_id: otherAthleteId, side: "opponent", display_name: "OMIT_OTHER_CHILD", jersey_number: "OMIT_JERSEY" }],
  teams: [{ ...scorerStats, side: "primary", goals_allowed: 1, minutes: null }, { ...zeroStats, side: "opponent", goals: 1, goals_allowed: 2 }],
  plays: soccerPlays, entry_plays: soccerPlays, more_plays: false,
  final_epochs: [{ epoch: 1, event_cutoff: 20, game_version: 21, roster_revision: 1, engine_version: "soccer-v1", participation_complete: true, current_authoritative: false, players: [{ ...scorerStats, roster_id: athleteId, side: "primary", display_name: "Controlled scorer", jersey_number: "7" }], teams: [{ ...scorerStats, side: "primary" }] }] };
export const soccerGameRaw = { ...basketballGameRaw, title: "Controlled soccer match", sport_key: "soccer", sport_label: "Soccer", basketball: null, soccer: soccerRaw, primary: { ...basketballGameRaw.primary, score: 2 }, opponent: { ...basketballGameRaw.opponent, score: 1 } };
export function soccerData(changes: Record<string, unknown> = {}, family = false) { return projectGameData({ features: soccerFeatures, games: [soccerGameRaw], ...changes }, family ? { ...soccerQuery, view: "family" } : soccerQuery)!; }
