import test from"node:test";import assert from"node:assert/strict";import{createElement}from"react";import{renderToStaticMarkup}from"react-dom/server";import{parseTournamentCommand,parseTournamentQuery,projectTournaments}from"../src/lib/tournaments/input";import{performTournamentMutation,type TournamentClient}from"../src/lib/tournaments/mutation";import{TournamentBracketView}from"../src/components/tournaments/bracket";
const id="10000000-0000-0000-0000-000000000001",other="10000000-0000-0000-0000-000000000002",third="10000000-0000-0000-0000-000000000003",origin="https://platform.boss.invalid";
const command={action:"bracket.create",request_id:id,input:{edition_id:other,name:"Boss Cup",bracket_size:4,include_third_place:true}};
const req=(body:unknown=command,headers={})=>new Request(`${origin}/app/tournaments/mutate`,{method:"POST",headers:{origin,host:"platform.boss.invalid","content-type":"application/json",...headers},body:JSON.stringify(body)});
function mock(){const calls:unknown[]=[];const client:TournamentClient={auth:{getClaims:async()=>({data:{claims:{sub:id,iss:"https://ilykgwgmxtrrikreacrz.supabase.co/auth/v1",role:"authenticated",exp:Math.floor(Date.now()/1000)+60}},error:null}),getUser:async()=>({data:{user:{id}},error:null})},rpc:async(name,args)=>{calls.push([name,args]);return{data:{contract:"tournaments-v1",id:third,action:"bracket.create",replayed:false,rest_warning:false,private:"STRIP_ME"},error:null};}};return{client,calls};}
test("tournament query requires bounded canonical identifiers",()=>{assert.deepEqual(parseTournamentQuery({org:id}),{organization_id:id});assert.deepEqual(parseTournamentQuery({edition:id,bracket:other}),{edition_id:id,bracket_id:other});for(const q of [{},{org:"forged"},{bracket:id},{org:[id]}])assert.equal(parseTournamentQuery(q),null);});
test("commands reject broader scope, malformed seeds and stale-version omission",()=>{assert.ok(parseTournamentCommand(command));const seed={action:"bracket.seed",request_id:id,input:{edition_id:id,bracket_id:other,expected_version:1,source_kind:"manual",seeds:[{seed:1,entry_id:id},{seed:2,entry_id:other}],reason:"Reviewed"}};assert.ok(parseTournamentCommand(seed));for(const c of [{...command,actor_person_id:id},{...command,input:{...command.input,organization_id:id}},{...seed,input:{...seed.input,expected_version:undefined}},{...seed,input:{...seed.input,seeds:[{seed:1,entry_id:"forged"}]}},{...seed,action:"public.publish"}])assert.equal(parseTournamentCommand(c),null);});
test("read projection rejects unbounded or malformed bracket payloads",()=>{assert.equal(projectTournaments({contract:"tournaments-v1",matches:Array.from({length:66},()=>({}))}),null);assert.equal(projectTournaments({contract:"tournaments-v1",brackets:[{id,name:"Bad",bracket_type:"double_elimination",bracket_size:4}]}),null);const data=projectTournaments({contract:"tournaments-v1",edition:{id,name:"Cup",sport_key:"soccer"},brackets:[],seeds:[],matches:[],entries:[],games:[],can_manage:true});assert.equal(data?.edition?.name,"Cup");});
test("bracket rendering keeps dependency and result states explicit",()=>{const bracket={id,name:"Boss Cup",bracket_type:"single_elimination" as const,bracket_size:4,include_third_place:false,status:"active",current_revision:1,champion_entry_id:null,runner_up_entry_id:null,third_entry_id:null,fourth_entry_id:null,version:3},match={id,stage_id:other,stage_name:"Semifinal",stage_type:"semifinal",round_number:1,match_number:1,label:"Semifinal 1",status:"ready",primary_source_kind:"fixed_entry",opponent_source_kind:"fixed_entry",primary_entry_id:id,primary_name:"Falcons",opponent_entry_id:other,opponent_name:"Wildcats",game_id:null,event_id:null,start_at:null,venue_label:null,game_status:null,primary_score:null,opponent_score:null,winner_side:null,finalization_count:null,advancement_destination:"Championship",version:1};const html=renderToStaticMarkup(createElement(TournamentBracketView,{bracket,seeds:[],matches:[match]}));assert.match(html,/Falcons/);assert.match(html,/Wildcats/);assert.match(html,/Winner advances to Championship/);assert.match(html,/Ready for a canonical Calendar/);assert.doesNotMatch(html,/roster|participant|private/i);});
test("signed mutation denies cross-origin before auth or RPC",async()=>{const m=mock();assert.equal((await performTournamentMutation(req(undefined,{origin:"https://attacker.invalid"}),m.client,origin)).status,403);assert.equal(m.calls.length,0);});
test("verified mutation strips private RPC payload and maps finite conflicts",async()=>{const m=mock(),result=await performTournamentMutation(req(),m.client,origin);assert.equal(result.status,200);assert.doesNotMatch(JSON.stringify(result),/STRIP_ME/);for(const[code,status]of[["PT403",403],["PT409",409],["PT422",422]]as const){m.client.rpc=async()=>({data:null,error:{code}});assert.equal((await performTournamentMutation(req(),m.client,origin)).status,status);}});
test("changed or anonymous identity cannot mutate",async()=>{const m=mock();m.client.auth.getUser=async()=>({data:{user:{id:other}},error:null});assert.equal((await performTournamentMutation(req(),m.client,origin)).status,401);m.client.auth.getUser=async()=>({data:{user:{id,is_anonymous:true}},error:null});assert.equal((await performTournamentMutation(req(),m.client,origin)).status,401);assert.equal(m.calls.length,0);});
