"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import type { CalendarData, CalendarDisplay, CalendarSelection, Occurrence } from "@/lib/calendar/contracts";
import { addDays, displayDays, formatDate, formatTime, groupOccurrences, localDateTime, moveDate, occurrenceOnDate } from "@/lib/calendar/temporal";
import { EventEditor } from "./event-editor";
import { CalendarManagement } from "./management";

function Filter({ label, name, selected, rows }: { label: string; name: string; selected?: string; rows: { id: string; name: string }[] }) {
  return <label className="form-field"><span>{label}</span><select name={name} defaultValue={selected ?? ""}><option value="">All {label.toLowerCase()}</option>{rows.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>;
}
const eventKey = (event: Occurrence) => `${event.event_id}:${event.occurrence_key}`;
export function CalendarConsole({ data, selection, initialEventId, initialOccurrenceKey }: { data: CalendarData; selection: CalendarSelection; initialEventId?: string; initialOccurrenceKey?: string }) {
  const searchParams = useSearchParams(); const [selectedKey,setSelectedKey] = useState<string | null>(() => {
    const linked = !selection.invalid && data.occurrences.find(occurrence => occurrence.event_id === initialEventId && (initialOccurrenceKey === undefined || occurrence.occurrence_key === initialOccurrenceKey) && occurrenceOnDate(occurrence, selection.date, selection.timezone));
    return linked ? eventKey(linked) : null;
  });
  const selected = data.occurrences.find(occurrence => eventKey(occurrence) === selectedKey);
  const selectedVenue = selected ? data.venues.find(venue => venue.id === selected.venue_id) : undefined;
  const venueAddress = selectedVenue ? [selectedVenue.address_line1,selectedVenue.address_line2,selectedVenue.city,selectedVenue.region,selectedVenue.postal_code,selectedVenue.country_code].filter(Boolean).join(", ") : "";
  const detailHeading = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (selectedKey) { detailHeading.current?.scrollIntoView({ block: "start" }); detailHeading.current?.focus({ preventScroll: true }); } },[selectedKey]);
  const timezone = selection.timezone; const rangeFirst = localDateTime(selection.query.from,timezone).slice(0,10); const rangeLast = localDateTime(Date.parse(selection.query.to)-1,timezone).slice(0,10);
  const days = searchParams.get("from") || searchParams.get("to") ? Array.from({ length: Math.min(93,Math.floor((Date.parse(`${rangeLast}T12:00:00Z`)-Date.parse(`${rangeFirst}T12:00:00Z`))/86_400_000)+1) },(_,index) => addDays(rangeFirst,index)) : displayDays(selection.date,selection.display);
  const grouped = groupOccurrences(data.occurrences,days,timezone);
  const selectedOrg = selection.query.organization_id;
  const href = (changes: Record<string,string>) => { const next = new URLSearchParams(searchParams.toString()); for (const [key,value] of Object.entries(changes)) { if (value) next.set(key,value); else next.delete(key); } return `/app/calendar?${next.toString()}`; };
  function eventButton(occurrence: Occurrence) {
    return <button type="button" key={eventKey(occurrence)} className={`calendar-event calendar-event-${occurrence.status}`} aria-pressed={selectedKey === eventKey(occurrence)} onClick={() => setSelectedKey(eventKey(occurrence))}>
      <span className="calendar-event-time">{occurrence.all_day ? "All day" : formatTime(occurrence.start_at,timezone)}</span><strong>{occurrence.title}</strong>
      <span className="calendar-event-targets">{occurrence.targets.map(target => target.label).join(" · ")}</span>
      <span className="calendar-event-status">{occurrence.status}{occurrence.is_exception ? " · Changed occurrence" : ""}</span>
    </button>;
  }
  function agenda(className: string) {
    return <div className={className}>{days.map(date => { const events = grouped.get(date) ?? []; return <section className="calendar-agenda-day" key={date}><h3>{formatDate(date)}</h3>{events.length ? <div className="calendar-agenda-events">{events.map(eventButton)}</div> : <p className="calendar-helper">No events scheduled.</p>}</section>; })}</div>;
  }
  return <div className="calendar-console">
    <header className="calendar-heading"><div><p className="eyebrow">Your Boss schedule</p><h1>Calendar</h1><p>Team schedules, organization events and your family in one place.</p></div><span className="calendar-zone">Display times · {timezone}</span></header>
    {data.unavailable || selection.invalid ? <div role="alert" className="calendar-notice">{selection.invalid ? "Review the calendar filters and date range. Dates must span no more than 93 days." : "The calendar is temporarily unavailable. Your access and schedule have not changed."}</div> : null}
    {data.options_limited && <p className="calendar-notice">Organization choices are limited. Choose a specific organization to refine the calendar.</p>}
    <details className="calendar-filter-panel"><summary>Filter your calendar</summary><form method="get" action="/app/calendar" className="calendar-form"><input type="hidden" name="view" value={selection.display} /><input type="hidden" name="date" value={selection.date} /><div className="calendar-fields">
      <label className="form-field"><span>Schedule</span><select name="scope" defaultValue={selection.query.view}><option value="personal">Personal and family</option><option value="organization">Organization</option><option value="team">Team</option></select></label>
      <Filter label="Organizations" name="org" selected={selectedOrg} rows={data.organizations} />
      <Filter label="Units" name="unit" selected={selection.query.unit_id} rows={data.units.filter(row => !selectedOrg || row.organization_id === selectedOrg)} />
      <Filter label="Teams" name="team" selected={selection.query.team_id} rows={data.teams.filter(row => !selectedOrg || row.organization_id === selectedOrg)} />
      <Filter label="Seasons" name="season" selected={selection.query.season_id} rows={data.seasons.filter(row => !selectedOrg || row.organization_id === selectedOrg)} />
      <Filter label="Children" name="child" selected={selection.query.child_id} rows={data.children} />
      <Filter label="Event types" name="type" selected={selection.query.event_type_key} rows={data.event_types.map(row => ({ id: row.key,name: row.name }))} />
      <Filter label="Venues" name="venue" selected={selection.query.location_id} rows={data.venues.filter(row => !selectedOrg || row.organization_id === selectedOrg)} />
      <label className="form-field"><span>From (optional)</span><input name="from" type="date" defaultValue={searchParams.get("from") ?? ""} /></label><label className="form-field"><span>Through (optional)</span><input name="to" type="date" defaultValue={searchParams.get("to") ?? ""} /></label>
      <label className="form-field"><span>Display timezone</span><input name="tz" defaultValue={timezone} required placeholder="America/Chicago" /></label>
    </div><div className="calendar-form-footer"><button type="submit" className="button button-primary">Apply filters</button><Link className="button button-outline" href="/app/calendar">Reset</Link></div></form></details>
    <nav className="calendar-toolbar" aria-label="Calendar views"><div className="calendar-view-tabs">{(["month", "week", "day", "agenda"] as CalendarDisplay[]).map(view => <Link className="calendar-tab" key={view} href={href({ view,from: "",to: "" })} aria-current={view === selection.display ? "page" : undefined}>{view[0].toUpperCase()+view.slice(1)}</Link>)}</div><div className="calendar-date-nav calendar-desktop"><Link className="button button-outline" href={href({ date: moveDate(selection.date,selection.display,-1),from: "",to: "" })} aria-label={`Previous ${selection.display === "agenda" ? "two weeks" : selection.display}`}>Previous</Link><strong>{formatDate(selection.date)}</strong><Link className="button button-outline" href={href({ date: moveDate(selection.date,selection.display,1),from: "",to: "" })} aria-label={`Next ${selection.display === "agenda" ? "two weeks" : selection.display}`}>Next</Link></div><div className="calendar-date-nav calendar-mobile"><Link className="button button-outline" href={href({ date: addDays(selection.date,-1),view: "day",from: "",to: "" })} aria-label="Previous day">Previous day</Link><Link className="button button-outline" href={href({ date: addDays(selection.date,1),view: "day",from: "",to: "" })} aria-label="Next day">Next day</Link></div></nav>
    <div className="calendar-jump"><Link className="button button-outline" href={href({ date: "",from: "",to: "" })}>Today</Link><form action="/app/calendar" method="get">{["view", "scope", "org", "unit", "team", "season", "child", "type", "venue", "tz"].map(key => searchParams.get(key) ? <input key={key} type="hidden" name={key} value={searchParams.get(key)!} /> : null)}<label className="form-field"><span>Jump to date</span><input type="date" name="date" defaultValue={selection.date} required /></label><button className="button button-outline" type="submit">Go</button></form></div>
    <p className="calendar-helper calendar-range">{formatDate(rangeFirst)} through {formatDate(rangeLast)} · {timezone}</p>
    <div className="calendar-content">
      {!data.unavailable && !selection.invalid && <><div className={`calendar-desktop calendar-display-${selection.display}`}>{selection.display === "agenda" ? agenda("calendar-agenda") : <div className={`calendar-grid calendar-grid-${selection.display}`} aria-label={`${selection.display} schedule`}>{days.map(date => <section className={`calendar-grid-day${date.slice(0,7) !== selection.date.slice(0,7) && selection.display === "month" ? " calendar-other-month" : ""}`} key={date}><h3><Link href={href({ view: "day",date,from: "",to: "" })}>{selection.display === "month" ? Number(date.slice(8,10)) : formatDate(date)}</Link></h3>{(grouped.get(date) ?? []).map(eventButton)}</section>)}</div>}</div>{agenda("calendar-mobile calendar-agenda")}
      {data.occurrences.length === 0 && <div className="calendar-notice">No events match this range and your filters. Select an organization to view scheduling controls when you have access.</div>}</>}
    </div>
    {selected && <section className="calendar-detail" aria-label="Event details"><div className="calendar-detail-heading"><h2 tabIndex={-1} ref={detailHeading}>{selected.title}</h2><button className="button button-outline" type="button" onClick={() => setSelectedKey(null)}>Close details</button></div><p className="calendar-event-targets">{selected.targets.map(target => target.label).join(" · ")}</p><dl className="calendar-detail-facts"><div><dt>When</dt><dd>{formatDate(localDateTime(selected.start_at,selected.timezone).slice(0,10))} · {selected.all_day ? "All day" : formatTime(selected.start_at,selected.timezone)} to {formatDate(localDateTime(Date.parse(selected.end_at)-(selected.all_day ? 1 : 0),selected.timezone).slice(0,10))} {selected.all_day ? "" : formatTime(selected.end_at,selected.timezone)} ({selected.timezone})</dd></div>{selected.arrival_at && <div><dt>Arrival</dt><dd>{formatTime(selected.arrival_at,selected.timezone)}</dd></div>}<div><dt>Status</dt><dd>{selected.status}{selected.is_exception ? " · Changed occurrence" : ""}</dd></div><div><dt>Access</dt><dd>{selected.visibility} · {selected.publication_state}</dd></div><div><dt>Venue</dt><dd>{selectedVenue?.name ?? "No venue listed"}{selected.resource_id ? ` · ${data.resources.find(resource => resource.id === selected.resource_id)?.name ?? "Resource"}` : ""}</dd></div>{venueAddress && <div><dt>Venue address</dt><dd>{venueAddress}</dd></div>}<div><dt>RSVP</dt><dd>{selected.rsvp_mode.replaceAll("_"," ")}</dd></div>{selected.game && <div><dt>Game</dt><dd>{selected.game.external_opponent_name ?? data.teams.find(team => team.id === selected.game?.opponent_team_id)?.name ?? "Opponent to be confirmed"} · {selected.game.home_away} · {selected.game.game_status}</dd></div>}</dl>{selectedVenue?.instructions && <p className="calendar-event-copy"><strong>Venue instructions: </strong>{selectedVenue.instructions}</p>}{selected.description && <p className="calendar-event-copy">{selected.description}</p>}{selected.instructions && <p className="calendar-event-copy"><strong>Instructions: </strong>{selected.instructions}</p>}{selected.recurrence && <p className="calendar-helper">Repeats {selected.recurrence.frequency} every {selected.recurrence.interval}. {selected.recurrence.count ? `${selected.recurrence.count} occurrences.` : `Ends ${selected.recurrence.until}.`}</p>}
      {selected.capabilities.manage && <><details className="calendar-editor"><summary>{selected.recurrence ? "Edit series, cancel or archive" : "Edit event, cancel or archive"}</summary><EventEditor key={`series:${eventKey(selected)}:${selected.version}`} data={data} date={selection.date} occurrence={selected} /></details>{selected.recurrence && <details className="calendar-editor"><summary>Edit, cancel or reschedule this occurrence</summary><EventEditor key={`single:${eventKey(selected)}:${selected.version}`} data={data} date={selection.date} occurrence={selected} single /></details>}</>}
    </section>}
    {data.capabilities.create && selectedOrg && <details className="calendar-editor"><summary>Create an event</summary><EventEditor key={`create:${selectedOrg}`} data={data} date={selection.date} organizationId={selectedOrg} /></details>}
    {selectedOrg && <CalendarManagement data={data} organizationId={selectedOrg} />}
  </div>;
}
