"use client";
import { useState } from "react";
import type { CalendarCommand, CalendarData, EventInput, Occurrence, Recurrence } from "@/lib/calendar/contracts";
import { addDays, localDateTime, localToInstant, validTimezone } from "@/lib/calendar/temporal";
import { CalendarActionForm, CalendarField, formNullable, formText } from "./action-form";

const audienceLabels = ["organization", "unit", "team", "staff", "coaches", "guardians", "participants", "public"];
function Select({ label, name, value = "", options }: { label: string; name: string; value?: string; options: { value: string; label: string }[] }) {
  return <label className="form-field"><span>{label}</span><select name={name} defaultValue={value}>{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>;
}
export function EventEditor({ data, date, organizationId: selectedOrganizationId, occurrence, single = false }: { data: CalendarData; date: string; organizationId?: string; occurrence?: Occurrence; single?: boolean }) {
  const organizationId = occurrence?.organization_id ?? selectedOrganizationId ?? "";
  const organization = data.organizations.find(row => row.id === organizationId);
  const [timezone,setTimezone] = useState(occurrence?.timezone ?? organization?.timezone ?? "UTC");
  const [allDay,setAllDay] = useState(occurrence?.all_day ?? false);
  const [type,setType] = useState(occurrence?.event_type_key ?? "practice");
  const [recurrence,setRecurrence] = useState(occurrence?.recurrence?.frequency ?? "none");
  const [reminderCount,setReminderCount] = useState(Math.min(8,Math.max(occurrence?.reminders.length ?? 0,1)));
  const [venueId,setVenueId] = useState(occurrence?.venue_id ?? "");
  const [visibility,setVisibility] = useState(occurrence?.visibility ?? "member");
  const start = occurrence ? single ? occurrence.start_at : occurrence.series_start_at ?? occurrence.start_at : localToInstant(`${date}T16:00`,timezone) ?? `${date}T16:00:00Z`;
  const end = occurrence ? single ? occurrence.end_at : occurrence.series_end_at ?? occurrence.end_at : localToInstant(`${date}T17:00`,timezone) ?? `${date}T17:00:00Z`;
  const arrival = occurrence ? single ? occurrence.arrival_at : occurrence.series_arrival_at : null;
  const anchorWeekday = ((new Date(`${localDateTime(start,timezone).slice(0,10)}T12:00:00Z`).getUTCDay()+6)%7)+1;
  const title = occurrence ? single ? occurrence.title : occurrence.series_title ?? occurrence.title : "";
  const instructions = occurrence ? single ? occurrence.instructions : occurrence.series_instructions : null;
  const targets = data.capabilities.create_targets.filter(target => target.target_type === "organization" ? target.target_id === organizationId : target.target_type === "team" ? data.teams.some(team => team.id === target.target_id && team.organization_id === organizationId) : data.units.some(unit => unit.id === target.target_id && unit.organization_id === organizationId));
  const editorTargets = [...targets, ...(occurrence?.targets ?? []).filter(existing => !targets.some(target => target.target_type === existing.target_type && target.target_id === existing.target_id))];
  function build(form: FormData): CalendarCommand | null {
    const zone = formText(form,"timezone") || timezone;
    const day = single && occurrence ? occurrence.all_day : form.get("all_day") === "on";
    const startLocal = formText(form,"start"); const endLocal = formText(form,"end");
    const startAt = localToInstant(day ? `${startLocal}T00:00` : startLocal,zone);
    const endAt = localToInstant(day ? `${addDays(endLocal,1)}T00:00` : endLocal,zone);
    const arrivalLocal = formText(form,"arrival"); const arrivalAt = arrivalLocal ? localToInstant(arrivalLocal,zone) : null;
    if (!startAt || !endAt || (arrivalLocal && !arrivalAt)) return null;
    if (single && occurrence) return { operation: "event.exception", input: { event_id: occurrence.event_id, expected_version: occurrence.version, occurrence_key: occurrence.occurrence_key, override_start_at: startAt, override_end_at: endAt, override_arrival_at: arrivalAt, title: formText(form,"title"), instructions: formNullable(form,"instructions"), status: formText(form,"status") as "scheduled" | "confirmed" | "canceled" | "postponed" | "completed", override_conflicts: form.get("override_conflicts") === "on" } };
    let rule: Recurrence | null = data.features.recurrence ? null : occurrence?.recurrence ?? null; const frequency = formText(form,"frequency");
    const weekdays = form.getAll("weekdays").map(Number);
    const preserveImplicitWeekday = occurrence?.recurrence?.frequency === "weekly" && !occurrence.recurrence.weekdays && weekdays.length === 1 && weekdays[0] === anchorWeekday;
    if (data.features.recurrence && frequency !== "none") rule = { frequency: frequency as Recurrence["frequency"], interval: Number(formText(form,"interval")), ...(frequency === "weekly" && !preserveImplicitWeekday ? { weekdays } : {}), ...(formText(form,"end_rule") === "count" ? { count: Number(formText(form,"count")) } : { until: formText(form,"until") }) };
    const selectedTargets = form.getAll("targets").map(value => { const [target_type,target_id] = String(value).split(":"); return { target_type,target_id } as EventInput["targets"][number]; });
    const audience = form.getAll("audience").map(String);
    const reminders = Array.from({ length: reminderCount },(_,index) => ({ minutes_before: Number(formText(form,`reminder_offset_${index}`)), audience: form.getAll(`reminder_audience_${index}`).map(String), enabled: form.get(`reminder_enabled_${index}`) === "on" })).filter((_,index) => formText(form,`reminder_offset_${index}`) !== "");
    const input: EventInput = { organization_id: organizationId, title: formText(form,"title"), description: formNullable(form,"description"), event_type_key: formText(form,"event_type_key"), start_at: startAt, end_at: endAt, timezone: zone, all_day: day, arrival_at: arrivalAt, status: formText(form,"status") as EventInput["status"], visibility: formText(form,"visibility") as EventInput["visibility"], publication_state: formText(form,"publication_state") as EventInput["publication_state"], venue_id: formNullable(form,"venue_id"), resource_id: formNullable(form,"resource_id"), instructions: formNullable(form,"instructions"), rsvp_mode: formText(form,"rsvp_mode") as EventInput["rsvp_mode"], audience, recurrence: rule, targets: selectedTargets, reminders, game: type === "game" ? { opponent_team_id: formNullable(form,"opponent_team_id"), external_opponent_name: formNullable(form,"external_opponent_name"), home_away: formText(form,"home_away") as "home" | "away" | "neutral", game_status: formText(form,"game_status") as "scheduled" | "postponed" | "canceled" | "completed" } : null, override_conflicts: form.get("override_conflicts") === "on", ...(occurrence ? { event_id: occurrence.event_id, expected_version: occurrence.version, reset_exceptions: form.get("reset_exceptions") === "on" } : {}) };
    return { operation: occurrence ? "event.update" : "event.create",input };
  }
  const canPublish = occurrence?.capabilities.publish ?? data.capabilities.publish;
  return <CalendarActionForm build={build} label={single ? "Save this occurrence" : occurrence ? "Save series" : "Create event"} preview timezone={timezone}>
    <p className="calendar-helper">{single ? "Change only this occurrence. The original series date remains its identity." : occurrence?.recurrence ? "Changes apply to the series. Single occurrence history is retained." : "One event can appear on several team schedules."} {organization?.name}</p>
    <div className="calendar-fields">
      <CalendarField label="Event title" name="title" value={title} required />
      {!single && <label className="form-field"><span>Event type</span><select name="event_type_key" value={type} onChange={event => setType(event.target.value)}>{data.event_types.map(row => <option key={row.key} value={row.key}>{row.name}</option>)}</select></label>}
      {!single && <label className="form-field"><span>Timezone</span><input name="timezone" defaultValue={timezone} onBlur={event => { if (validTimezone(event.target.value)) setTimezone(event.target.value); }} required placeholder="America/Chicago" /></label>}
      {single && <input type="hidden" name="timezone" value={timezone} />}
      <Select label="Status" name="status" value={occurrence ? single ? occurrence.status : occurrence.series_status ?? occurrence.status : "scheduled"} options={(single ? ["scheduled", "confirmed", "canceled", "postponed", "completed"] : ["draft", "scheduled", "confirmed", "canceled", "postponed", "completed", "archived"]).map(value => ({ value,label: value[0].toUpperCase()+value.slice(1) }))} />
    </div>
    {single ? <p className="calendar-helper">{allDay ? "This is an all day occurrence." : "This is a timed occurrence."} Change this setting on the whole series.</p> : <label className="calendar-check"><input name="all_day" type="checkbox" checked={allDay} onChange={event => setAllDay(event.target.checked)} />All day or several full days</label>}
    <div className="calendar-fields" key={`${allDay}-${timezone}`}>
      <CalendarField label={allDay ? "First day" : "Start"} name="start" value={allDay ? localDateTime(start,timezone).slice(0,10) : localDateTime(start,timezone)} type={allDay ? "date" : "datetime-local"} required />
      <CalendarField label={allDay ? "Last day (included)" : "End"} name="end" value={allDay ? localDateTime(Date.parse(end)-1,timezone).slice(0,10) : localDateTime(end,timezone)} type={allDay ? "date" : "datetime-local"} required />
      <CalendarField label="Arrival (optional)" name="arrival" type="datetime-local" value={arrival ? localDateTime(arrival,timezone) : ""} />
    </div>
    <p className="calendar-helper">Times use {timezone}. Daylight saving gaps are rejected; repeated clock times use the later occurrence.</p>
    {!single && <><label className="form-field"><span>Description</span><textarea name="description" defaultValue={occurrence?.description ?? ""} maxLength={4000} rows={3} /></label>
      <fieldset className="calendar-targets"><legend>Schedules</legend>{editorTargets.map(target => <label className="calendar-check" key={`${target.target_type}:${target.target_id}`}><input type="checkbox" name="targets" value={`${target.target_type}:${target.target_id}`} defaultChecked={occurrence?.targets.some(existing => existing.target_type === target.target_type && existing.target_id === target.target_id) ?? false} />{target.label} <span className="calendar-helper">({target.target_type})</span></label>)}</fieldset>
      <div className="calendar-fields"><label className="form-field"><span>Venue</span><select name="venue_id" value={venueId} onChange={event => setVenueId(event.target.value)}><option value="">No venue</option>{data.venues.filter(row => row.organization_id === organizationId && (row.status === undefined || row.status === "active" || row.id === occurrence?.venue_id)).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
      <Select key={venueId} label="Court, room or resource" name="resource_id" value={data.resources.some(row => row.id === occurrence?.resource_id && row.venue_id === venueId) ? occurrence?.resource_id ?? "" : ""} options={[{ value: "",label: "No resource" },...data.resources.filter(row => row.organization_id === organizationId && row.venue_id === venueId && (row.status === undefined || row.status === "active" || row.id === occurrence?.resource_id)).map(row => ({ value: row.id,label: row.name }))]} />
      <label className="form-field"><span>Visibility</span><select name="visibility" value={visibility} onChange={event => setVisibility(event.target.value as typeof visibility)}>{["member", "restricted", "private", "authenticated", ...(data.features.public_schedules || occurrence?.visibility === "public" ? ["public"] : [])].map(value => <option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select></label>
      {canPublish ? <Select key={visibility} label="Publication" name="publication_state" value={occurrence?.publication_state ?? "unpublished"} options={[{ value: "unpublished",label: "Unpublished" },...(data.features.public_schedules && ["public", "authenticated"].includes(visibility) ? [{ value: "published",label: "Published" }] : [])]} /> : <input name="publication_state" type="hidden" value={occurrence?.publication_state ?? "unpublished"} />}
      <Select label="RSVP setting" name="rsvp_mode" value={occurrence?.rsvp_mode ?? "not_required"} options={[{ value: "not_required",label: "Not required" },{ value: "optional",label: "Optional" },{ value: "required",label: "Required" }]} /></div>
      <p className="calendar-helper">Published schedules use public or authenticated visibility and require the organization&apos;s publication feature. RSVP is configured here; response collection is a later step.</p>
      <fieldset className="calendar-targets"><legend>Audience labels</legend>{audienceLabels.map(label => <label className="calendar-check" key={label}><input name="audience" type="checkbox" value={label} defaultChecked={occurrence?.audience.includes(label) ?? label === "team"} />{label === "organization" ? "Organization members" : label[0].toUpperCase()+label.slice(1)}</label>)}</fieldset>
      <p className="calendar-helper">Audience labels describe intended attendees. They do not grant access.</p>
      {data.features.recurrence && <fieldset className="calendar-targets"><legend>Repeat</legend><div className="calendar-fields"><label className="form-field"><span>Frequency</span><select name="frequency" value={recurrence} onChange={event => setRecurrence(event.target.value)}>{["none", "daily", "weekly", "monthly"].map(value => <option key={value} value={value}>{value === "none" ? "Does not repeat" : value[0].toUpperCase()+value.slice(1)}</option>)}</select></label>{recurrence !== "none" && <><label className="form-field"><span>Every</span><input type="number" name="interval" min={1} max={52} defaultValue={occurrence?.recurrence?.interval ?? 1} required /></label><Select label="End rule" name="end_rule" value={occurrence?.recurrence?.until ? "until" : "count"} options={[{ value: "count",label: "Number of occurrences" },{ value: "until",label: "Last date" }]} /><label className="form-field"><span>Occurrences (1 to 1000)</span><input name="count" type="number" min={1} max={1000} defaultValue={occurrence?.recurrence?.count ?? 10} /></label><CalendarField label="Last date" name="until" type="date" value={occurrence?.recurrence?.until ?? addDays(date,90)} /></>}</div>{recurrence === "weekly" && <div className="calendar-weekdays">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((label,index) => <label className="calendar-check" key={label}><input type="checkbox" name="weekdays" value={index+1} defaultChecked={occurrence?.recurrence?.weekdays?.includes(index+1) ?? index+1 === anchorWeekday} />{label}</label>)}</div>}<p className="calendar-helper">Repeated times stay in the event timezone. Dates skipped by daylight saving or missing monthly dates are skipped. Series end within five years.</p></fieldset>}
      {!data.features.recurrence && <input type="hidden" name="frequency" value="none" />}
      {occurrence?.recurrence && <label className="calendar-check"><input name="reset_exceptions" type="checkbox" />Reset active single occurrence changes when changing series times, timezone or repeat rule. History is retained.</label>}
      <fieldset className="calendar-targets"><legend>Reminder configuration</legend>{Array.from({ length: reminderCount },(_,index) => <div className="calendar-reminder" key={index}><label className="form-field"><span>Reminder {index+1}: minutes before (0 to 10080)</span><input type="number" name={`reminder_offset_${index}`} min={0} max={10080} defaultValue={occurrence?.reminders[index]?.minutes_before ?? ""} /></label><label className="calendar-check"><input type="checkbox" name={`reminder_enabled_${index}`} defaultChecked={occurrence?.reminders[index]?.enabled ?? true} />Enabled</label><div className="calendar-weekdays">{audienceLabels.filter(label => label !== "public").map(label => <label className="calendar-check" key={label}><input name={`reminder_audience_${index}`} type="checkbox" value={label} defaultChecked={occurrence?.reminders[index]?.audience.includes(label) ?? label === "guardians"} />{label[0].toUpperCase()+label.slice(1)}</label>)}</div></div>)}{reminderCount < 8 && <button className="button button-outline" type="button" onClick={() => setReminderCount(count => Math.min(8,count+1))}>Add reminder</button>}<p className="calendar-helper">Up to eight reminders. Leave the offset blank to remove a reminder. Configuration only; no reminders are sent in this phase.</p></fieldset>
      {type === "game" && <fieldset className="calendar-targets"><legend>Game schedule</legend><div className="calendar-fields"><Select label="Opponent team" name="opponent_team_id" value={occurrence?.game?.opponent_team_id ?? ""} options={[{ value: "",label: "External or unlisted opponent" },...data.teams.filter(row => row.organization_id === organizationId).map(row => ({ value: row.id,label: row.name }))]} /><CalendarField label="External opponent name" name="external_opponent_name" value={occurrence?.game?.external_opponent_name ?? ""} /><Select label="Home or away" name="home_away" value={occurrence?.game?.home_away ?? "home"} options={["home", "away", "neutral"].map(value => ({ value,label: value }))} /><Select label="Game status" name="game_status" value={occurrence?.game?.game_status ?? "scheduled"} options={["scheduled", "postponed", "canceled", "completed"].map(value => ({ value,label: value }))} /></div></fieldset>}
    </>}
    <label className="form-field"><span>Event instructions</span><textarea name="instructions" defaultValue={instructions ?? ""} rows={3} maxLength={4000} /></label>
  </CalendarActionForm>;
}
