"use client";
import type { CalendarData, CalendarFeatures, Venue } from "@/lib/calendar/contracts";
import { CalendarActionForm, CalendarField, formNullable, formText } from "./action-form";

const featureLabels: [keyof CalendarFeatures,string][] = [["organization_calendar", "Organization schedule"], ["team_calendar", "Team schedules"], ["recurrence", "Repeating events"], ["conflicts", "Conflict checks"], ["conflict_overrides", "Authorized conflict overrides"], ["public_schedules", "Explicitly published public schedules"], ["head_coach_management", "Head coach scheduling for their own team"]];
function VenueEditor({ data, organizationId, venue }: { data: CalendarData; organizationId: string; venue?: Venue }) {
  return <CalendarActionForm label={venue ? "Save venue" : "Create venue"} build={form => ({ operation: venue ? "venue.update" : "venue.create", input: { organization_id: organizationId, name: formText(form,"name"), timezone: formText(form,"timezone"), address_line1: formNullable(form,"address_line1"), address_line2: formNullable(form,"address_line2"), city: formNullable(form,"city"), region: formNullable(form,"region"), postal_code: formNullable(form,"postal_code"), country_code: formNullable(form,"country_code"), instructions: formNullable(form,"instructions"), status: formText(form,"status") as "active" | "inactive", is_public: form.get("is_public") === "on", ...(venue ? { venue_id: venue.id, expected_version: venue.version } : {}) } })}>
    <div className="calendar-fields"><CalendarField label="Venue name" name="name" value={venue?.name} required /><CalendarField label="Timezone" name="timezone" value={venue?.timezone ?? data.organizations.find(row => row.id === organizationId)?.timezone ?? "UTC"} required />{(["address_line1", "address_line2", "city", "region", "postal_code", "country_code"] as const).map(key => <CalendarField key={key} label={key === "country_code" ? "Country code (two letters)" : key.replaceAll("_"," ")} name={key} value={venue?.[key] ?? ""} />)}<label className="form-field"><span>Status</span><select name="status" defaultValue={venue?.status === "inactive" ? "inactive" : "active"}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>
    <label className="form-field"><span>Venue instructions</span><textarea name="instructions" rows={3} maxLength={4000} defaultValue={venue?.instructions ?? ""} /></label><label className="calendar-check"><input name="is_public" type="checkbox" defaultChecked={venue?.is_public ?? false} />Make venue details eligible for explicitly published schedules</label><p className="calendar-helper">Venues and resources are private by default. A public venue alone does not publish an event.</p>
  </CalendarActionForm>;
}
function ResourceEditor({ data, organizationId, resource }: { data: CalendarData; organizationId: string; resource?: CalendarData["resources"][number] }) {
  return <CalendarActionForm label={resource ? "Save resource" : "Create resource"} build={form => ({ operation: resource ? "resource.update" : "resource.create", input: { organization_id: organizationId, venue_id: formText(form,"venue_id"), name: formText(form,"name"), resource_type: formText(form,"resource_type"), status: formText(form,"status") as "active" | "inactive", is_public: form.get("is_public") === "on", ...(resource ? { resource_id: resource.id, expected_version: resource.version } : {}) } })}>
    <div className="calendar-fields"><CalendarField label="Resource name" name="name" value={resource?.name} required /><label className="form-field"><span>Venue</span><select name="venue_id" defaultValue={resource?.venue_id ?? ""} required><option value="">Choose a venue</option>{data.venues.filter(row => row.organization_id === organizationId && row.status !== "archived").map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><CalendarField label="Resource type (court, room, field)" name="resource_type" value={resource?.resource_type ?? "court"} maxLength={50} required /><label className="form-field"><span>Status</span><select name="status" defaultValue={resource?.status === "inactive" ? "inactive" : "active"}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><label className="calendar-check"><input name="is_public" type="checkbox" defaultChecked={resource?.is_public ?? false} />Make resource name eligible for explicitly published schedules</label>
  </CalendarActionForm>;
}
export function CalendarManagement({ data, organizationId }: { data: CalendarData; organizationId: string }) {
  return <div className="calendar-management">
    {data.capabilities.configure && <details className="calendar-editor"><summary>Calendar settings</summary><CalendarActionForm label="Save calendar settings" build={form => ({ operation: "calendar.configure", input: { organization_id: organizationId, features: { ...Object.fromEntries(featureLabels.map(([key]) => [key,form.get(key) === "on"])), attendance: false } } })}>{featureLabels.map(([key,label]) => <label className="calendar-check" key={key}><input name={key} type="checkbox" defaultChecked={data.features[key] ?? false} />{label}</label>)}<p className="calendar-helper">Calendar activation is managed in Organizations. Attendance is reserved for a later phase. These settings do not expand anyone&apos;s role or scope.</p></CalendarActionForm></details>}
    {data.capabilities.manage_venues && <details className="calendar-editor"><summary>Venues and resources</summary><div className="calendar-management-grid"><div><h3>Venues</h3>{data.venues.filter(row => row.organization_id === organizationId).map(venue => <details className="calendar-editor" key={venue.id}><summary>{venue.name} · {venue.status ?? "active"}</summary>{venue.version ? <VenueEditor key={`${venue.id}:${venue.version}`} data={data} organizationId={organizationId} venue={venue} /> : <p className="calendar-helper">Refresh to manage this venue.</p>}</details>)}<details className="calendar-editor"><summary>Create venue</summary><VenueEditor data={data} organizationId={organizationId} /></details></div><div><h3>Courts, rooms and resources</h3>{data.resources.filter(row => row.organization_id === organizationId).map(resource => <details className="calendar-editor" key={resource.id}><summary>{resource.name} · {resource.status ?? "active"}</summary>{resource.version ? <ResourceEditor key={`${resource.id}:${resource.version}`} data={data} organizationId={organizationId} resource={resource} /> : <p className="calendar-helper">Refresh to manage this resource.</p>}</details>)}<details className="calendar-editor"><summary>Create resource</summary><ResourceEditor data={data} organizationId={organizationId} /></details></div></div></details>}
  </div>;
}
