import type { Json } from "../supabase/database.types";
export type LeaderboardEntry = { kind: "participant" | "team"; name: string; raised_minor: number };
export type Tile = { ordinal: number; amount_minor: number; state: "available" | "reserved" | "payment_pending" | "claimed" };
export type Board = { id?: string; public_path?: string; title: string; goal_minor: number; start_minor: number; increment_minor: number; tile_count: number; largest_minor: number; all_claimed_minor: number; reservation_seconds: number; claimed_count: number; generated_count: number; raised_minor: number; status: string; version: number; visibility?: string; tiles: Tile[] };
export type Fundraiser = { id: string; participant_id: string; person_id: string; name: string; team_name: string | null; status: string; goal_minor: number | null; raised_minor: number; can_share: boolean; can_accept: boolean; leaderboard_opt_in: boolean; supporters: { display_name: string; amount_minor: number }[]; path: string | null; board: Board | null };
export type Campaign = { id: string; organization_id: string; organization_name: string; name: string; description: string; status: string; version: number; currency: string; goal_minor: number; raised_minor: number; starts_at: string; ends_at: string; public_path: string | null; can_manage: boolean; can_publish: boolean; can_manage_boards: boolean; fundraisers: Fundraiser[]; boards: Board[]; contribution_count: number; targets: { team_id: string | null; unit_id: string | null; name: string; goal_minor: number | null; raised_minor: number }[]; leaderboard: LeaderboardEntry[]; report: { participant_count: number; settled_supporter_count: number; anonymous_count: number; recurring_count: number } };
export type FundraisingData = { campaigns: Campaign[]; mode: "organization" | "family"; can_create: boolean; money_board_available: boolean; unavailable?: boolean; restricted?: boolean; catalog?: { units: { id: string; name: string }[]; teams: { id: string; name: string }[]; participants: { id: string; name: string; team_id: string | null }[] } };
export type PublicFundraising = { campaign: { name: string; description: string; organization_name: string; currency: string; goal_minor: number; raised_minor: number; starts_at: string; ends_at: string; indexable: boolean; allow_anonymous: boolean; allow_recurring: boolean; allow_fee_cover: boolean; direct_support: boolean; reward_policy: Record<string, Json>; branding: Record<string, Json> }; fundraiser: { display_name: string; goal_minor: number | null; raised_minor: number; team_name: string | null } | null; board: Board | null; leaderboard: LeaderboardEntry[]; supporters: { display_name: string; amount_minor: number; date: string }[]; payment_available: false };
export type FundraisingCommand = { action: string; request_id: string; input: Record<string, Json> };
export const emptyFundraising: FundraisingData = { campaigns: [], mode: "organization", can_create: false, money_board_available: false };
export function record(v: unknown): v is Record<string, Json> { return !!v && typeof v === "object" && !Array.isArray(v); }
export function sharePath(v: unknown): v is string { return typeof v === "string" && /^[a-f0-9]{48}$/.test(v); }
export function currencyDigits(currency: string): number { return new Intl.NumberFormat("en-US", { style: "currency", currency }).resolvedOptions().maximumFractionDigits ?? 2; }
export function money(amount: number, currency = "USD") { return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(amount / 10 ** currencyDigits(currency)); }
export function minorAmount(value: string, currency = "USD"): number | null {
 const digits = currencyDigits(currency), pattern = new RegExp(`^\\d+(?:\\.\\d{1,${Math.max(1, digits)}})?$`);
 if (!pattern.test(value) || digits === 0 && value.includes(".")) return null;
 const [whole, decimal = ""] = value.split("."), result = Number(whole) * 10 ** digits + Number(decimal.padEnd(digits, "0"));
 return Number.isSafeInteger(result) && result > 0 && result <= 1_000_000_000_000 ? result : null;
}
export function preview(start: number, increment: number, count: number) { if (![start, increment, count].every(Number.isSafeInteger) || start <= 0 || increment <= 0 || count < 1 || count > 2_147_483_647) return null; const n = BigInt(count), first = BigInt(start), step = BigInt(increment), largest = first + (n - 1n) * step, total = n * (2n * first + (n - 1n) * step) / 2n; return largest <= 1_000_000_000_000n && total <= BigInt(Number.MAX_SAFE_INTEGER) ? { count, smallest: start, largest: Number(largest), total: Number(total) } : null; }
