import Link from "next/link";
import type { AthleteHistoryData, AthleteHistoryQuery, AthleteHistoryRecord } from "@/lib/athlete-history/contracts";
import { footballStatSections } from "@/lib/football/presentation";
import { historySports } from "@/lib/athlete-history/contracts";
import { uuid } from "@/lib/coordination/input";
import { displayInstant, humanize } from "../coordination/presentation";

export function athleteHistoryHref(query: AthleteHistoryQuery, cursor = false, organizationId?: string) {
  const params = new URLSearchParams();
  if (uuid(organizationId)) params.set("org", organizationId);
  if (query.child_person_id) params.set("child", query.child_person_id);
  if (query.sport_key) params.set("history_sport", query.sport_key);
  if (query.season_id) params.set("history_season", query.season_id);
  if (query.limit !== 20) params.set("history_limit", String(query.limit));
  if (cursor && query.before_sealed_at && query.before_finalization_id && query.before_stat_id) { params.set("before_sealed_at", query.before_sealed_at); params.set("before_finalization_id", query.before_finalization_id); params.set("before_stat_id", query.before_stat_id); }
  return `/app/families${params.size ? `?${params}` : ""}#athlete-history`;
}
function HistoricalGame({ row }: { row: AthleteHistoryRecord }) {
  const status = row.current_authoritative ? "Current authoritative final" : row.latest_sealed ? "Latest seal; game awaiting refinalization" : "Preserved historical epoch";
  return <article className="athlete-history-record"><header><h3>{humanize(row.sport_key)} · {row.team_name}</h3><p>{row.origin_team_season_name ?? "Season not recorded"} · {row.organization_name}</p><span className="athlete-history-epoch">{status} · Final {row.epoch}</span></header><p className="game-helper">Sealed {displayInstant(row.sealed_at)} · Roster revision {row.roster_revision}</p>{row.sport_key === "football" ? footballStatSections.filter(section => section.stats.some(([key]) => row.stats[key] !== null && row.stats[key] !== 0)).map(section => <section key={section.label} className="athlete-history-stat-section"><h4>{section.label}</h4><dl className="athlete-history-stats">{section.stats.map(([key, label]) => <div key={key}><dt>{label}</dt><dd>{row.stats[key] ?? "--"}</dd></div>)}</dl></section>) : <dl className="athlete-history-stats">{Object.entries(row.stats).map(([key, value]) => <div key={key}><dt>{humanize(key)}</dt><dd>{value === null ? "--" : typeof value === "boolean" ? value ? "Yes" : "No" : Number.isInteger(value) ? value : value.toFixed(1)}</dd></div>)}</dl>}<details className="athlete-history-provenance"><summary>Record provenance</summary><dl><div><dt>Game</dt><dd>{row.game_id}</dd></div><div><dt>Roster snapshot</dt><dd>{row.roster_id}</dd></div><div><dt>Finalization</dt><dd>{row.finalization_id}</dd></div><div><dt>Stat record</dt><dd>{row.id}</dd></div><div><dt>Engine</dt><dd>{row.engine_version}</dd></div><div><dt>Game season</dt><dd>{row.game_season_name ?? "Not recorded"}</dd></div></dl></details></article>;
}
export function AthleteHistoryHub({ data, query, organizationId }: { data: AthleteHistoryData; query: AthleteHistoryQuery; organizationId?: string }) {
  return <section id="athlete-history" className="athlete-history-hub admin-section" aria-label="Athlete history"><div className="section-heading"><h2>Verified athlete history</h2><p>Sealed game statistics follow the athlete. Current guardian authority controls family access even after a team membership ends.</p></div>{data.unavailable ? <p role="alert" className="form-notice">Athlete history is temporarily unavailable. Please try again.</p> : data.restricted ? <p role="status" className="form-notice">Athlete history is restricted for this person.</p> : <><form action="/app/families" method="get" className="athlete-history-filters">{uuid(organizationId) && <input type="hidden" name="org" value={organizationId} />}<label className="form-field"><span>Athlete</span><select name="child" defaultValue={data.subject_person_id ?? ""}>{data.subjects.map(subject => <option key={subject.person_id} value={subject.person_id}>{subject.display_name}{subject.relationship === "self" ? " (you)" : ""}</option>)}</select></label><label className="form-field"><span>Sport</span><select name="history_sport" defaultValue={query.sport_key ?? ""}><option value="">All supported sports</option>{historySports.map(sport => <option key={sport} value={sport}>{humanize(sport)}</option>)}</select></label>{query.season_id && <input type="hidden" name="history_season" value={query.season_id} />}<button type="submit" className="button button-outline button-small">View history</button></form>{data.records.length ? <div className="athlete-history-records">{data.records.map(row => <HistoricalGame row={row} key={row.id} />)}</div> : <p className="empty-state">No sealed game records match this athlete and these filters.</p>}{data.has_more && data.next_cursor && <Link className="button button-outline button-small" href={athleteHistoryHref({ ...query, child_person_id: data.subject_person_id ?? undefined, before_sealed_at: data.next_cursor.sealed_at, before_finalization_id: data.next_cursor.finalization_id, before_stat_id: data.next_cursor.stat_id }, true, organizationId)}>Earlier records</Link>}<p className="game-helper">This view shows individual game records. It grants no original-team roster, communication or correction access.</p></>}</section>;
}
