import type { CoordinationCommand } from "../coordination/mutation";
import type { Choice } from "../coordination/input";
export const attendanceOperations = ["attendance.configure", "event.configure", "response.set", "checkin.set", "reminders.prepare"] as const;
export const attendanceStatuses = ["attending", "not_attending", "maybe", "pending", "unknown"] as const;
export const checkinStates = ["expected", "checked_in", "absent", "late", "excused"] as const;
export const attendanceFeatureKeys = ["attendance", "rsvp", "participant_self_response", "guardian_rsvp", "attendance_reminders", "checkin", "head_coach_management", "assistant_coach_management", "minimum_self_response_age"] as const;
export type AttendanceCommand = CoordinationCommand & { operation: typeof attendanceOperations[number] };
export type AttendanceQuery = { view: "family" | "staff" | "history"; from: string; to: string; organization_id?: string; event_id?: string; occurrence_key?: string; team_id?: string; unit_id?: string; child_person_id?: string };
export type AttendanceResponse = { id: string; status: typeof attendanceStatuses[number]; version: number; needs_reconfirmation: boolean; is_late: boolean; reason: string | null; note: string | null; arrival_difference_minutes: number | null; departure_difference_minutes: number | null };
export type AttendanceSubject = { person_id: string; participant_id: string | null; subject_kind: "participant" | "staff"; display_name: string; response: AttendanceResponse | null; checkin: { id: string; state: typeof checkinStates[number]; version: number } | null; capabilities: { respond: boolean; manage: boolean; checkin: boolean; view_private_notes: boolean } };
export type AttendanceOccurrence = { event_id: string; organization_id: string; title: string; occurrence_key: string; start_at: string; end_at: string; timezone: string; status: string; rsvp_mode: "not_required" | "optional" | "required"; settings: { response_deadline_at: string | null; effective_deadline_at: string | null; deadline_offset_minutes: number | null; deadline_policy: "lock" | "allow_late"; change_policy: "keep" | "needs_reconfirmation"; audience: ("participants" | "staff")[]; version: number }; summary: { attending: number; not_attending: number; maybe: number; pending: number; unknown: number; needs_reconfirmation: number; total: number }; capabilities: { view_summary: boolean; manage: boolean; checkin: boolean }; subjects: AttendanceSubject[] };
export type AttendanceHistory = { id: string; response_id: string; event_id: string; occurrence_key: string; person_id: string; subject_kind: "participant" | "staff"; version: number; change_kind: string; created_at: string; status: typeof attendanceStatuses[number]; needs_reconfirmation: boolean };
export type AttendanceData = { navigation_available: boolean; options_limited: boolean; organization_id: string | null; view: AttendanceQuery["view"]; range: { from: string; to: string }; features: Partial<Record<typeof attendanceFeatureKeys[number], boolean | number>>; capabilities: { configure: boolean }; organizations: Choice[]; teams: Choice[]; units: Choice[]; children: { person_id: string; participant_id: string; display_name: string }[]; occurrences: AttendanceOccurrence[]; history: AttendanceHistory[]; unavailable?: boolean };
export function emptyAttendance(query: AttendanceQuery, unavailable = false): AttendanceData { return { navigation_available: false, options_limited: false, organization_id: query.organization_id ?? null, view: query.view, range: { from: query.from, to: query.to }, features: {}, capabilities: { configure: false }, organizations: [], teams: [], units: [], children: [], occurrences: [], history: [], unavailable }; }
