-- Safe read-only canonical schema gate; no user/secret/credential projection.
begin read only;
with expected_tables(schema_name,name) as (values ('public','merchant_markets'),('public','merchant_categories'),('public','merchants'),('public','merchant_modules'),('public','merchant_locations'),('public','merchant_access_assignments'),('public','merchant_staff_assignments'),('public','merchant_claims'),('public','merchant_history'),('boss_private','merchant_receipts'),('public','merchant_offer_families'),('public','merchant_offer_revisions'),('public','merchant_offer_locations'),('public','merchant_offer_events'),('public','merchant_offer_local_state'),('public','merchant_favorites'),('boss_private','merchant_redemption_intents'),('public','merchant_redemptions'),('public','merchant_redemption_corrections'),('public','merchant_sales_assignments'),('public','merchant_sales_leads'),('public','merchant_sales_activities'),('public','merchant_sales_history'),('boss_private','merchant_timezones')),
expected_functions(schema_name,name) as (values ('boss_private','merchant_platform'),('boss_private','merchant_feature'),('boss_private','merchant_can'),('boss_private','merchant_require'),('boss_private','merchant_fence'),('boss_private','merchant_audit'),('boss_private','merchant_offer_state'),('boss_private','merchant_window'),('boss_private','merchant_usage'),('boss_private','merchant_available'),('boss_private','merchant_market_source'),('boss_private','merchant_membership_source'),('boss_private','merchant_operate'),('boss_private','merchant_sales_can'),('boss_private','merchant_sales_operate'),('boss_private','merchant_redemption_operate'),('boss_private','merchant_terms'),('boss_private','merchant_command_keys'),('boss_private','merchant_required_keys'),('boss_private','merchant_replay_allowed'),('boss_private','merchant_mutate'),('boss_merchants_public','options'),('boss_merchants_public','directory'),('boss_private','merchant_read'),('public','boss_merchants_read'),('public','boss_merchants_mutate'),('public','boss_merchants_directory'),('boss_private','merchant_row_contract'),('boss_private','merchant_redemption_proof'),('boss_private','merchant_notification_boundary'),('boss_private','merchant_notification_visible'),('boss_private','notification_source_visible'),('boss_private','notification_candidates'),('boss_private','notification_contexts'),('boss_private','notification_destination'),('boss_private','merchant_notification_ingest')),
expected_indexes(name) as (values ('merchants_directory_idx'),('merchants_name_prefix_idx'),('merchant_locations_discovery_idx'),('merchant_locations_page_idx'),('merchant_access_current_idx'),('merchant_staff_current_idx'),('merchant_claims_pending_idx'),('merchant_claims_approved_idx'),('merchant_history_resource_idx'),('merchant_offer_revisions_page_idx'),('merchant_offer_locations_location_idx'),('merchant_offer_events_latest_idx'),('merchant_intents_member_idx'),('merchant_redemptions_usage_idx'),('merchant_redemptions_page_idx'),('merchant_sales_assignments_scope_idx'),('merchant_sales_leads_pipeline_idx'),('merchant_sales_leads_manager_idx'),('merchant_sales_activities_page_idx'),('merchant_sales_history_page_idx'),('notification_events_merchant_idx'),('notification_merchant_source_once_idx')),
checks(label,ok) as (
 select t.schema_name||'.'||t.name||' RLS',coalesce(c.relrowsecurity,false)
 from expected_tables t left join pg_namespace n on n.nspname=t.schema_name left join pg_class c on c.relnamespace=n.oid and c.relname=t.name
 union all select t.schema_name||'.'||t.name||' closed raw '||r,coalesce(not has_table_privilege(r,c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE'),false)
 from expected_tables t cross join unnest(array['anon','authenticated','service_role','boss_payment_worker'])r left join pg_namespace n on n.nspname=t.schema_name left join pg_class c on c.relnamespace=n.oid and c.relname=t.name
 union all select f.schema_name||'.'||f.name||' pinned path',coalesce(p.proconfig@>array['search_path=""'],false)
 from expected_functions f left join pg_namespace n on n.nspname=f.schema_name left join pg_proc p on p.pronamespace=n.oid and p.proname=f.name
 union all select f.schema_name||'.'||f.name||' internal execute closed',coalesce(not has_function_privilege('anon',p.oid,'EXECUTE')and not has_function_privilege('authenticated',p.oid,'EXECUTE')and not has_function_privilege('service_role',p.oid,'EXECUTE')and not has_function_privilege('boss_payment_worker',p.oid,'EXECUTE'),false)
 from expected_functions f left join pg_namespace n on n.nspname=f.schema_name left join pg_proc p on p.pronamespace=n.oid and p.proname=f.name
 where f.schema_name='boss_private' and f.name not in('merchant_read','merchant_mutate')
 union all select i.name||' index valid',coalesce(x.indisvalid,false)from expected_indexes i left join pg_class c on c.relname=i.name left join pg_index x on x.indexrelid=c.oid
 union all select 'signed public RPCs are invoker',count(*)=2 and bool_and(not p.prosecdef and has_function_privilege('authenticated',p.oid,'EXECUTE')and not has_function_privilege('anon',p.oid,'EXECUTE'))from pg_proc p where p.pronamespace='public'::regnamespace and p.proname in('boss_merchants_read','boss_merchants_mutate')
 union all select 'public directory invoker allows safe listing',count(*)=1 and bool_and(not p.prosecdef and has_function_privilege('anon',p.oid,'EXECUTE')and has_function_privilege('authenticated',p.oid,'EXECUTE'))from pg_proc p where p.pronamespace='public'::regnamespace and p.proname='boss_merchants_directory'
)
select count(*) checks,count(*)filter(where ok) passed,bool_and(coalesce(ok,false)) all_passed,coalesce(jsonb_agg(label)filter(where not coalesce(ok,false)),'[]') failures from checks;
rollback;
