import Image from "next/image";
import { loadPublicDiscounts } from "@/lib/discounts/data";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Brand } from "@/components/brand";
import { loadPublicFundraising } from "@/lib/fundraising/data";
import { money } from "@/lib/fundraising/contracts";
import { SupporterBoard } from "@/components/fundraising/supporter";
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ path: string }> }): Promise<Metadata> { const { path } = await params, data = await loadPublicFundraising(path); return { title: data?.campaign.name ?? "Fundraiser unavailable", robots: { index: data?.campaign.indexable === true, follow: data?.campaign.indexable === true } }; }
export default async function FundraisePage({ params, searchParams }: { params: Promise<{ path: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) { const { path } = await params, query = await searchParams, ordinal = typeof query.after === "string" && /^\d{1,6}$/.test(query.after) ? Number(query.after) : 0, data = await loadPublicFundraising(path, ordinal); if (!data) notFound(); const discounts = await loadPublicDiscounts(path), subject = data.fundraiser, goal = subject?.goal_minor ?? data.campaign.goal_minor, raised = subject?.raised_minor ?? data.campaign.raised_minor, currency = data.campaign.currency;
 return <main id="main-content" className="container fundraising-public"><Brand href="/" /><p className="eyebrow">{data.campaign.organization_name}</p><h1>{data.campaign.name}</h1>{subject && <h2>Support {subject.display_name}{subject.team_name ? ` · ${subject.team_name}` : ""}</h2>}{typeof data.campaign.branding.headline === "string" && <p className="fundraising-headline">{data.campaign.branding.headline}</p>}{typeof data.campaign.branding.logo_url === "string" && data.campaign.branding.logo_url && <Image src={data.campaign.branding.logo_url} width={160} height={80} referrerPolicy="no-referrer" unoptimized alt={`${data.campaign.organization_name} logo`} />}<p>{data.campaign.description}</p><div className="fundraising-progress"><strong>{money(raised, currency)} raised</strong><span>Goal: {money(goal, currency)}</span><progress max={goal} value={Math.min(raised, goal)} aria-label="Authoritative fundraising progress" /><span>{Math.min(100, Math.floor(raised / goal * 100))}% · {money(Math.max(0, goal - raised), currency)} remaining</span></div><SupporterBoard data={data} discounts={discounts} path={path} source={query.source === "qr" ? "qr" : "participant_share"} />{data.leaderboard?.length > 0 && <section><h2>Fundraising progress leaderboard</h2><ol>{data.leaderboard.map((entry, n) => <li key={n}>{entry.name} ({entry.kind}): {money(entry.raised_minor, currency)}</li>)}</ol></section>}<section><h2>Recent supporters</h2>{data.supporters.length ? data.supporters.map((supporter, n) => <p key={n}>{supporter.display_name}: {money(supporter.amount_minor, currency)}</p>) : <p>No confirmed support yet.</p>}</section></main>;
}
