import type { Json } from "../supabase/database.types";
export type WalletActivity = { id: string; at: string; kind: "issuance" | "reversal" | "expiration"; amount_minor: number | string; currency: string; organization_id: string; organization: string; child_id: string; child: string; campaign_id: string; campaign: string; team: string | null; state: string; available_at: string; expires_at: string | null; source_reference?: string; fundraiser?: string };
export type Wallet = { id: string; household: string; currency: string; available_minor: number | string; organizations: { id: string; name: string; status: string; available_minor: number | string }[]; children: { id: string; name: string; organization_id: string; organization: string; earned_minor: number | string }[]; campaigns: { id: string; name: string; earned_minor: number | string }[]; activity: WalletActivity[] };
export type WalletChoice = { household_id: string; household: string; child_id: string; child: string; organization_id: string; organization: string };
export type ChargePreview = { charge_id: string; title: string; organization_id: string; organization: string; currency: string; due_minor: number | string; available_minor: number | string; eligible_minor: number | string; remaining_minor: number | string; payment_available: false };
export type WalletPolicy = { id: string; campaign_id: string; campaign: string; revision: number; mode: string; basis_points: number; currency: string; channels: string[]; availability_seconds: number; expiry_seconds: number | null; at: string };
export type WalletReport = { wallet_id: string; household: string; currency: string; issued_minor: number | string; available_minor: number | string; reversed_minor: number | string; expired_minor: number | string };
export type BucksData = { mode: "family" | "organization"; wallets: Wallet[]; provision_choices: WalletChoice[]; charges: ChargePreview[]; reports: WalletReport[]; policies: WalletPolicy[]; campaigns: { id: string; name: string; currency: string }[]; fundraisers: { id: string; name: string; campaign: string; household_id: string; household: string; bound: boolean; may_earn: boolean }[]; activity: WalletActivity[]; can_manage_policy: boolean; unavailable?: boolean; restricted?: boolean };
export type BucksCommand = { action: string; request_id: string; input: Record<string, Json> };
export const emptyBucks: BucksData = { mode: "family", wallets: [], provision_choices: [], charges: [], reports: [], policies: [], campaigns: [], fundraisers: [], activity: [], can_manage_policy: false };
export function bucksRecord(value: unknown): value is Record<string, unknown> { return !!value && typeof value === "object" && !Array.isArray(value); }
export function previewAmounts(due: number, available: number) { if (![due, available].every(v => Number.isSafeInteger(v) && v >= 0)) return null; return { eligible: Math.min(due, available), remaining: Math.max(due - available, 0) }; }
