import type { Json } from "../supabase/database.types";
export type WalletActivity = { id: string; at: string; kind: "issuance" | "reversal" | "expiration" | "spend" | "payment_restore" | "recovery_open" | "recovery_apply" | "recovery_cancel" | "recovery_cancel_source" | "recovery_release"; amount_minor: number | string; currency: string; organization_id: string; organization: string; child_id: string; child: string; campaign_id: string; campaign: string; team: string | null; state: string; available_at: string; expires_at: string | null; source_reference?: string; fundraiser?: string; charge_title?: string; payment_id?: string };
export type Wallet = { id: string; household: string; currency: string; available_minor: number | string; organizations: { id: string; name: string; status: string; available_minor: number | string }[]; children: { id: string; name: string; organization_id: string; organization: string; earned_minor: number | string }[]; campaigns: { id: string; name: string; earned_minor: number | string }[]; activity: WalletActivity[]; recovery?: { organization_id: string; organization: string; amount_minor: number | string }[] };
export type WalletChoice = { household_id: string; household: string; child_id: string; child: string; organization_id: string; organization: string };
export type ChargePreview = { charge_id: string; wallet_id: string; title: string; organization_id: string; organization: string; currency: string; due_minor: number | string; available_minor: number | string; eligible_minor: number | string; remaining_minor: number | string; payment_available: boolean };
export type WalletPolicy = { id: string; campaign_id: string; campaign: string; revision: number; mode: string; basis_points: number; currency: string; channels: string[]; availability_seconds: number; expiry_seconds: number | null; at: string };
export type WalletReport = { wallet_id: string; household: string; currency: string; issued_minor: number | string; available_minor: number | string; reversed_minor: number | string; expired_minor: number | string; accepted_minor?: number | string; restored_minor?: number | string; recovery_minor?: number | string };
export type BucksReceipt = { payment_id: string; organization_id: string; organization: string; method: "boss_bucks"; currency: string; amount_minor: number | string; at: string; status?: "recorded" | "reversed"; checkout_id: string; charges: { charge_id: string; allocation_id?: string; title: string; amount_minor: number | string; remaining_minor: number | string }[] };
export type BucksPayment = BucksReceipt & { reversible_minor: number | string; allocations: { id: string; charge_id: string; title: string; amount_minor: number | string; reversible_minor: number | string; sources?: { grant_id: string; amount_minor: number | string; child: string; campaign: string; source_reference: string }[] }[] };
export type BucksData = { mode: "family" | "organization"; wallets: Wallet[]; provision_choices: WalletChoice[]; charges: ChargePreview[]; reports: WalletReport[]; policies: WalletPolicy[]; campaigns: { id: string; name: string; currency: string }[]; fundraisers: { id: string; name: string; campaign: string; household_id: string; household: string; bound: boolean; may_earn: boolean }[]; activity: WalletActivity[]; payments: BucksPayment[]; can_reverse_payment: boolean; can_manage_policy: boolean; unavailable?: boolean; restricted?: boolean };
export type BucksCommand = { action: string; request_id: string; input: Record<string, Json> };
export const emptyBucks: BucksData = { mode: "family", wallets: [], provision_choices: [], charges: [], reports: [], policies: [], campaigns: [], fundraisers: [], activity: [], payments: [], can_reverse_payment: false, can_manage_policy: false };
export function bucksRecord(value: unknown): value is Record<string, unknown> { return !!value && typeof value === "object" && !Array.isArray(value); }
export function isBucksReceipt(value: unknown): value is BucksReceipt {
 const uuid = (v: unknown) => typeof v === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
 const minor = (v: unknown, positive = false) => (typeof v === "string" || typeof v === "number") && /^(0|[1-9][0-9]{0,18})$/.test(String(v)) && (!positive || BigInt(v) > 0n && BigInt(v) <= 1_000_000_000n);
 if (!bucksRecord(value) || !uuid(value.payment_id) || !uuid(value.organization_id) || !uuid(value.checkout_id) || value.method !== "boss_bucks" || !minor(value.amount_minor, true) || typeof value.organization !== "string" || typeof value.currency !== "string" || !/^[A-Z]{3}$/.test(value.currency) || typeof value.at !== "string" || !Number.isFinite(Date.parse(value.at)) || value.status !== undefined && !["recorded", "reversed"].includes(String(value.status)) || !Array.isArray(value.charges) || !value.charges.length || value.charges.length > 50) return false;
 const ids = new Set<string>(); let sum = 0n;
 for (const c of value.charges) { if (!bucksRecord(c) || !uuid(c.charge_id) || ids.has(String(c.charge_id).toLowerCase()) || typeof c.title !== "string" || !minor(c.amount_minor, true) || !minor(c.remaining_minor)) return false; ids.add(String(c.charge_id).toLowerCase()); sum += BigInt(c.amount_minor as number | string); }
 return sum === BigInt(value.amount_minor as number | string);
}
export function previewAmounts(due: number, available: number) { if (![due, available].every(v => Number.isSafeInteger(v) && v >= 0)) return null; return { eligible: Math.min(due, available), remaining: Math.max(due - available, 0) }; }
