"use client";
import Link from "next/link";
import type { Json } from "@/lib/supabase/database.types";
import { merchantPageLink } from "@/lib/merchants/input";
import Image from "next/image";
import { useState } from "react";
import QRCode from "qrcode";
import type { MerchantData, Offer } from "@/lib/merchants/contracts";
import { CategoryChoice, MerchantState, TermsSummary, useMerchantAction, type Act } from "./shared";
export function MerchantDirectory({ data, member = false, marketId, query = {} }: { data: MerchantData; member?: boolean; marketId?: string; query?: Record<string, Json> }) {
 const { act, busy, status } = useMerchantAction();
 if (data.restricted || data.unavailable) return <MerchantState data={data} />;
 return <div className="merchant-workspace"><p>Participating merchants set their own offers. Merchant listings and initial merchant tools are free. Availability depends on active participating locations.</p>
 <form method="get" className="merchant-form"><label>Market name begins with<input name="market_search" defaultValue={typeof query.market_search === "string" ? query.market_search : ""} maxLength={80} /></label><label>Selected market<select name="market_id" defaultValue={marketId ?? ""}><option value="">Choose a market</option>{data.markets?.map(g => <option key={g.id} value={g.id}>{g.market} · {g.region}, {g.country}</option>)}</select></label><label>Business name begins with<input name="search" defaultValue={typeof query.search === "string" ? query.search : ""} maxLength={80} /></label><CategoryChoice categories={data.categories} all defaultValue={typeof query.category === "string" ? query.category : ""} />{member && <><label>Offer type<select name="offer_type" defaultValue={typeof query.offer_type === "string" ? query.offer_type : ""}><option value="">All offer types</option>{["percentage_off","fixed_amount_off","bogo","free_item"].map(k => <option key={k} value={k}>{k.replaceAll("_", " ")}</option>)}</select></label><label className="merchant-check"><input type="checkbox" name="favorites" value="true" defaultChecked={query.favorites === true} />Offers from favorite merchants only</label></>}<button className="button button-primary">Discover merchants</button></form>
 {data.markets?.length === 50 && <Link className="button button-outline" href={merchantPageLink(query, {market_after:data.markets.at(-1)?.id})}>More approved markets</Link>}{data.has_more && data.items?.at(-1) && <Link className="button button-outline" href={merchantPageLink(query, {market_id:marketId, directory_after:data.items.at(-1)?.id})}>Next listing page</Link>}{marketId && !data.items?.length && <p role="status">No active participating listings are available in this market.</p>}
 <div className="merchant-grid">{data.items?.map(m => <article key={m.id} className="merchant-panel"><h2>{m.name}</h2><p>{m.description}</p><p>{m.category?.replaceAll("_", " ")}</p>{m.website && <a href={m.website} rel="noopener noreferrer">Business website</a>}{m.locations?.map(l => <div key={l.id}><h3>{l.name}</h3><p>{l.address}, {l.city} {l.postal_code}</p><p>Local timezone: {l.timezone}</p></div>)}{member && <button disabled={busy} className="button button-outline" onClick={() => { void act("favorite.set", { merchant_id: m.id, favorite: true }); }}>Favorite {m.name}</button>}</article>)}</div>
 {!member && <p><Link href="/app/boss-bucks/deals">Sign in to see eligible member discounts and redemption.</Link></p>}
 {member && <section><h2>Your eligible offers</h2><p>Discount details and redemption are available in the signed Boss app. Boss Bucks Wallet value is separate and cannot be spent at merchants.</p>{marketId && !data.offers?.length && <p role="status">{data.availability === "membership_required" ? "An active Boss Bucks Discounts membership is required." : data.availability === "membership_expired" ? "Your Boss Bucks Discounts coverage has expired." : data.availability === "outside_membership_coverage" ? "This market is outside your current membership coverage." : data.availability === "outside_location_or_market" ? "This location is outside the selected market." : data.availability === "offer_expired" ? "This merchant’s previously published offer has expired." : "No current eligible offers are available at participating locations."}</p>}<div className="merchant-grid">{data.offers?.map(o => <MemberOffer key={`${o.revision_id}-${o.location_id}`} offer={o} act={act} busy={busy} />)}</div>{data.offers_has_more && data.offers?.at(-1) && <Link className="button button-outline" href={merchantPageLink(query, {market_id:marketId, after:data.offers.at(-1)?.revision_id,after_location_id:data.offers.at(-1)?.location_id})}>Next offer page</Link>}</section>}
 {member && <section><h2>Your redemption history</h2>{data.history?.map(r => <article className="merchant-panel" key={r.id}><h3>{r.title}</h3><p>{new Date(r.created_at).toLocaleString()} · {r.corrected ? "Reviewed correction recorded" : "Redeemed"}</p></article>)}</section>}{status}
 </div>;
}
function businessProof() { return Array.from(crypto.getRandomValues(new Uint8Array(32)), x => x.toString(16).padStart(2, "0")).join(""); }
function MemberOffer({ offer: o, act, busy }: { offer: Offer; act: Act; busy: boolean }) {
 const [proof, setProof] = useState<string | null>(null), [expiry, setExpiry] = useState(""), [qr, setQr] = useState(""), [confirmation, setConfirmation] = useState(""), [verified, setVerified] = useState(false);
 const scope = { merchant_id: o.merchant_id ?? "", location_id: o.location_id ?? "" };
 async function intent() { const code = businessProof(), r = await act("intent.create", { ...scope, revision_id: o.revision_id ?? "", capability: code }); if (r && typeof r.expires_at === "string") { setProof(code); setExpiry(r.expires_at); } }
 return <article className="merchant-panel"><h3>{o.terms.title}</h3><p>{o.merchant_name} · {o.location_name}</p><TermsSummary terms={o.terms} />{o.presentation_note && <p>{o.presentation_note}</p>}<p>{o.weekly_special ? "Weekly special" : "Offer"} · Local timezone {o.timezone}</p>{o.local_start && <p>Available local hours: {o.local_start} to {o.local_end}</p>}<p>Remaining uses: {o.remaining_uses === null ? "Unlimited" : o.remaining_uses} · {o.reset_period}</p>
 {!proof ? <button disabled={busy || o.availability !== "eligible"} className="button button-primary" onClick={() => { void intent(); }}>Redeem offer</button> : <div><p role="status">One-time redemption prepared. Expires {new Date(expiry).toLocaleTimeString()}. It works only at this selected location.</p><button disabled={busy} className="button button-outline" onClick={async () => { setQr(await QRCode.toDataURL(proof, { width: 240, margin: 2 })); }}>Show merchant QR</button>{qr && <div><Image src={qr} width={240} height={240} unoptimized alt="Short-lived merchant redemption QR" /><label>Accessible merchant code<input value={proof} readOnly type="password" autoComplete="off" /></label><button className="button button-outline" onClick={() => { setQr(""); }}>Conceal redemption proof</button></div>}
 {o.can_redeem && <fieldset><legend>Your authorized merchant confirmation</legend><p>Your separate merchant permission authorizes verification at this location.</p><button disabled={busy} className="button button-outline" onClick={async () => { const r = await act("token.verify", { ...scope, capability: proof }); if (r?.valid) { setVerified(true); setConfirmation("Valid current member and offer at this location. Review the displayed terms before confirming."); } }}>Verify at this location</button><button disabled={busy || !verified} className="button button-primary" onClick={async () => { const r = await act("token.redeem", { ...scope, capability: proof }); if (r) { setVerified(false); setConfirmation("Redemption confirmed once."); } }}>Confirm redemption at this location</button><p role="status">{confirmation}</p></fieldset>}
 <button className="button button-outline" onClick={() => { setProof(null); setQr(""); setConfirmation(""); setVerified(false); }}>Close redemption</button></div>}</article>;
}
