"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { merchantClientRendered } from "@/lib/merchants/diagnostics-client";
import type { Json } from "@/lib/supabase/database.types";
import type { MerchantData, Location, Terms } from "@/lib/merchants/contracts";
import { validMerchantTerms } from "@/lib/merchants/contracts";
import { minorAmount } from "@/lib/fundraising/contracts";
import { CategoryChoice, MarketChoice, MerchantState, TermsSummary, formText, optionalText, optionalDate, useMerchantAction, type Act } from "./shared";
export function MerchantPortal({ data, merchantId, locationId, diagnosticCorrelation }: { data: MerchantData; merchantId?: string; locationId?: string; diagnosticCorrelation?: string }) {
 const router = useRouter(), { act, busy, status } = useMerchantAction();
 useEffect(()=>{if(diagnosticCorrelation)merchantClientRendered(diagnosticCorrelation);},[diagnosticCorrelation]);
 if (data.unavailable || data.restricted) return <MerchantState data={data} />;
 const m = data.merchant, scope = { merchant_id: merchantId ?? "" };
 if (!m) return <div className="merchant-workspace"><p>Initial merchant tools are free, including listing-only businesses with no offers. Your Boss account remains your only identity.</p>
 <div className="merchant-grid">{data.merchants?.map(b => <article key={b.id} className="merchant-panel"><h2>{b.name}</h2><p>{b.status}</p><Link href={`/app/merchants?merchant_id=${b.id}${b.preferred_location_id ? `&location_id=${b.preferred_location_id}` : ""}`}>Open merchant workspace</Link></article>)}</div>
 <section className="merchant-panel"><h2>Join the merchant network</h2><form className="merchant-form" action={async form => { const r = await act("merchant.create", { name: formText(form,"name"), category: formText(form,"category"), market_id: formText(form,"market_id"), ...optionalText(form,"legal_name"), ...optionalText(form,"description"), ...optionalText(form,"website") }); if (typeof r?.merchant_id === "string") router.push(`/app/merchants?merchant_id=${r.merchant_id}`); }}><label>Public business name<input name="name" required maxLength={120} /></label><label>Legal business name (optional)<input name="legal_name" maxLength={160} /></label><MarketChoice markets={data.markets} /><CategoryChoice categories={data.categories} /><label>Public description<textarea name="description" maxLength={1500} /></label><label>Business website<input name="website" type="url" placeholder="https://" maxLength={500} /></label><button disabled={busy} className="button button-primary">Create prospect profile</button></form><p>Creating a profile does not approve a listing or prove ownership. Submit an ownership claim for independent review.</p></section>
 {data.can_market && <details className="merchant-panel"><summary>Configure a merchant category</summary><form className="merchant-form" action={async form=>{await act("category.configure",{key:formText(form,"key"),name:formText(form,"name"),status:formText(form,"status")});}}><label>Stable category key<input name="key" required minLength={2} maxLength={40} pattern="[a-z][a-z0-9_]{1,39}" /></label><label>Category name<input name="name" required maxLength={80} /></label><label>Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button disabled={busy} className="button button-outline">Save category configuration</button></form></details>}
 {data.can_market && <details className="merchant-panel"><summary>Platform market configuration</summary><form className="merchant-form" action={async form => { await act("market.create", { country: formText(form,"country").toUpperCase(), region: formText(form,"region"), market: formText(form,"market") }); }}><label>Country code<input name="country" pattern="[A-Za-z]{2}" maxLength={2} required /></label><label>Exact membership region<input name="region" maxLength={80} required /></label><label>Exact membership market<input name="market" maxLength={100} required /></label><button disabled={busy} className="button button-outline">Create approved market</button></form></details>}{status}</div>;
 return <div className="merchant-workspace"><p className="eyebrow">Merchant workspace · Free merchant tools</p><h2>{m.name}</h2><p>Listing status: {m.status.replaceAll("_"," ")} · Ownership: {m.claim_state}</p>
 <nav className="bucks-tabs" aria-label="Merchant context"><Link href="/app/merchants">Choose merchant</Link><Link href="/app/boss-bucks/deals">Your member deals</Link><Link href="/app/merchant-sales">Assigned sales workspace</Link></nav>
 <form className="merchant-form" method="get"><input type="hidden" name="merchant_id" value={m.id} /><label>Location context<select name="location_id" defaultValue={locationId ?? ""}><option value="">Company context where authorized</option>{data.locations?.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></label><button className="button button-outline">Switch merchant location</button></form>
 {m.claim_state === "unclaimed" && <section className="merchant-panel"><h3>Request reviewed ownership</h3><form className="merchant-form" action={async form => { await act("claim.submit", { ...scope, statement: formText(form,"statement") }); }}><label>Verification statement<textarea name="statement" minLength={10} maxLength={1200} required /></label><button disabled={busy} className="button button-outline">Submit ownership claim</button></form></section>}
 {data.claims?.map(c => <article className="merchant-panel" key={c.id}><h3>Ownership claim · {c.state}</h3><p>{c.statement}</p>{data.can_review && c.state === "pending" && <form className="merchant-form" action={async form => { await act("claim.review", { ...scope, claim_id: c.id, state: formText(form,"state"), reason: formText(form,"reason"), ...optionalDate(form,"ends_at") }); }}><label>Independent review decision<select name="state"><option value="approved">Approve verified claimant</option><option value="rejected">Reject claim</option></select></label><label>Verification reason<textarea name="reason" minLength={10} maxLength={1200} required /></label><label>Ownership grant ends at (optional)<input name="ends_at" type="datetime-local" /></label><button disabled={busy} className="button button-primary">Record independent claim review</button></form>}</article>)}
 {data.can_manage && <details className="merchant-panel"><summary>Business profile</summary><form className="merchant-form" action={async form => { await act("merchant.edit", { ...scope, expected_version: m.version ?? 1, name: formText(form,"name"), description: formText(form,"description"), ...optionalText(form,"website"), ...optionalText(form,"public_phone") }); }}><label>Public name<input name="name" defaultValue={m.name} maxLength={120} required /></label><label>Public description<textarea name="description" defaultValue={m.description} maxLength={1500} /></label><label>HTTPS business website<input name="website" type="url" defaultValue={m.website ?? ""} maxLength={500} /></label><label>Public business phone<input name="public_phone" defaultValue={m.public_phone ?? ""} maxLength={40} /></label><button disabled={busy} className="button button-outline">Save profile</button></form></details>}
 {data.can_review && <details className="merchant-panel"><summary>Boss listing review and safety</summary><form className="merchant-form" action={async form => { await act("merchant.review", { ...scope, state: formText(form,"state"), reason: formText(form,"reason") }); }}><label>Listing decision<select name="state">{["pending_review","active","paused","suspended","archived"].map(s => <option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></label><label>Review reason<textarea name="reason" required minLength={10} maxLength={1200} /></label><button disabled={busy} className="button button-primary">Record listing decision</button></form></details>}
 {data.can_configure && <details className="merchant-panel"><summary>Platform commerce availability</summary><form className="merchant-form" action={async form => { await act("merchant.configure", { ...scope, status: formText(form,"status"), portal: form.get("portal")==="on", offers: form.get("offers")==="on", redemption: form.get("redemption")==="on", ...optionalDate(form,"ends_at") }); }}><label>Commerce status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label>{["portal","offers","redemption"].map(k => <label key={k} className="merchant-check"><input name={k} type="checkbox" />{k}</label>)}<label>Configuration ends at (optional)<input name="ends_at" type="datetime-local" /></label><button disabled={busy} className="button button-outline">Save bounded availability</button></form></details>}
 <section><h3>Business locations</h3><div className="merchant-grid">{data.locations?.map(l => <LocationPanel key={l.id} location={l} merchantId={m.id} act={act} busy={busy} manageable={data.can_locations === true} />)}</div>
 {data.can_locations && !locationId && <details className="merchant-panel"><summary>Add a business location</summary><form className="merchant-form" action={async form => { await act("location.create", { ...scope, market_id: formText(form,"market_id"), name: formText(form,"name"), address: formText(form,"address"), city: formText(form,"city"), postal_code: formText(form,"postal_code"), timezone: formText(form,"timezone"), ...optionalText(form,"hours_note") }); }}><MarketChoice markets={data.markets} />{["name","address","city","postal_code","timezone"].map(k => <label key={k}>{k.replaceAll("_"," ")}<input name={k} required maxLength={k === "address" ? 250 : 120} placeholder={k==="timezone" ? "America/New_York" : undefined} /></label>)}<label>Location hours<textarea name="hours_note" maxLength={500} /></label><button disabled={busy} className="button button-outline">Add location</button></form></details>}</section>
 {data.can_offers && <OfferEditor data={data} merchantId={m.id} locationId={locationId} act={act} busy={busy} />}
 <section><h3>Offers and weekly specials</h3><p>Material changes create a reviewed immutable revision. Corporate pauses remain authoritative.</p><div className="merchant-grid">{data.offers?.map(o => <article className="merchant-panel" key={o.id}><h4>{o.terms.title}</h4><p>Revision {o.revision} · {o.state}</p><TermsSummary terms={o.terms} /><p>{o.weekly_special ? "Weekly special" : "Offer"} · Weekdays {o.weekdays?.join(", ")} · {o.local_start ?? "All day"} to {o.local_end ?? "end of local day"}</p><p>{new Date(o.starts_at).toLocaleString()} to {new Date(o.ends_at).toLocaleString()}</p><p>{o.usage_limit ?? "Unlimited"} uses · {o.reset_period} · Family identity is retained.</p>
 {data.can_offers && o.can_global_edit && <div className="merchant-actions">{["pending_review","paused","archived"].map(state => <button key={state} disabled={busy} className="button button-outline" onClick={() => { void act("offer.status", { ...scope, revision_id: o.id ?? "", ...(locationId ? { location_id: locationId } : {}), state }); }}>{state === "pending_review" ? "Submit for review" : state === "paused" ? "Pause revision" : "Archive revision"}</button>)}</div>}
 {data.can_review && o.state === "pending_review" && <form className="merchant-form" action={async form => { await act("offer.status", { ...scope, revision_id: o.id ?? "", state: formText(form,"state"), reason: formText(form,"reason") }); }}><label>Offer review<select name="state"><option value="published">Approve publication</option><option value="scheduled">Approve scheduled publication</option><option value="draft">Request correction</option><option value="rejected">Reject</option></select></label><label>Offer review reason<textarea name="reason" required minLength={10} maxLength={1200} /></label><button disabled={busy} className="button button-primary">Record offer review</button></form>}
 {data.can_locations && locationId && <form className="merchant-form" action={async form => { await act("offer.local", { ...scope, family_id: o.family_id, location_id: locationId, paused: form.get("paused")==="on", ...optionalText(form,"presentation_note") }); }}><label className="merchant-check"><input name="paused" type="checkbox" />Pause only this location</label><label>Location presentation note<input name="presentation_note" maxLength={300} /></label><button disabled={busy} className="button button-outline">Save local offer state</button></form>}</article>)}</div></section>
 {data.can_redeem && locationId && <RedemptionConsole merchantId={m.id} locationId={locationId} act={act} busy={busy} />}
 {data.can_access && <section className="merchant-panel"><h3>Merchant users and roles</h3><form className="merchant-form" action={async form => { await act("access.grant", { ...scope, person_id: formText(form,"person_id"), role: formText(form,"role"), ...optionalText(form,"location_id"), ...optionalDate(form,"ends_at") }); }}><label>Verified canonical person ID<input name="person_id" required /></label><label>Operational role<select name="role">{["merchant_admin","location_manager","offer_editor","redemption_clerk"].map(r => <option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select></label><label>Exact location<select name="location_id"><option value="">Company scope where permitted</option>{data.locations?.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Grant ends at (optional)<input type="datetime-local" name="ends_at" /></label><button disabled={busy} className="button button-outline">Assign operational access</button></form>{data.assignments?.map(a => <div key={a.id}><p>{a.role.replaceAll("_"," ")} · {a.status} · {a.location_id ? "Exact location" : "Company"}{a.ends_at && ` · Ends ${new Date(a.ends_at).toLocaleString()}`}</p>{a.status === "active" && a.role !== "merchant_owner" && <button disabled={busy} className="button button-outline" onClick={() => { void act("access.end", { ...scope, assignment_id: a.id }); }}>End this operational assignment</button>}</div>)}<p>Ownership transfers require independent Boss review.</p></section>}
 <section><h3>Redemptions and aggregate analytics</h3><p>Operational history is bounded. Consumer contacts, family records and sports records are excluded.</p>{data.analytics?.map((a,index) => <p key={index}>{new Date(a.day).toLocaleDateString()} · {data.locations?.find(l => l.id===a.location_id)?.name ?? "Assigned location"} · {a.redemptions} recorded redemptions</p>)}{data.redemptions?.map(r => <article key={r.id} className="merchant-panel"><h4>{r.title}</h4><p>{new Date(r.created_at).toLocaleString()} · {r.corrected ? "Reviewed correction recorded" : "Redeemed"}</p>{data.can_review && !r.corrected && <form className="merchant-form" action={async form => { await act("redemption.correct", { ...scope, redemption_id: r.id, reason: formText(form,"reason"), restore_allowance: form.get("restore_allowance")==="on" }); }}><label>Reviewed correction reason<textarea name="reason" required minLength={10} maxLength={1200} /></label><label className="merchant-check"><input type="checkbox" name="restore_allowance" />Explicitly restore this single use</label><button disabled={busy} className="button button-outline">Record immutable correction</button></form>}</article>)}</section>{status}
 </div>;
}
function LocationPanel({ location: l, merchantId, act, busy, manageable }: { location: Location; merchantId: string; act: Act; busy: boolean; manageable: boolean }) { return <article className="merchant-panel"><h4>{l.name}</h4><p>{l.address}, {l.city} {l.postal_code}</p><p>Timezone: {l.timezone} · {l.status}</p><Link href={`/app/merchants?merchant_id=${merchantId}&location_id=${l.id}`}>Open exact location</Link>{manageable && <button className="button button-outline" disabled={busy} onClick={() => { void act("location.edit", { merchant_id: merchantId, location_id: l.id, expected_version: l.version ?? 1, status: l.status === "active" ? "paused" : "active" }); }}>{l.status === "active" ? "Pause location" : "Resume location"}</button>}</article>; }
function OfferEditor({ data, merchantId, locationId, act, busy }: { data: MerchantData; merchantId: string; locationId?: string; act: Act; busy: boolean }) {
 const [type, setType] = useState("percentage_off"), [newFamily, setNewFamily] = useState(""), [qualification, setQualification] = useState("none");
 return <section className="merchant-panel"><h3>Create an offer or weekly special</h3><details><summary>Create stable allowance family</summary><form className="merchant-form" action={async form => { const r = await act("family.create", { merchant_id: merchantId, ...(locationId ? { location_id: locationId } : {}), usage_limit: form.get("usage_limit") ? Number(form.get("usage_limit")) : null, reset_period: formText(form,"reset_period"), usage_timezone: formText(form,"usage_timezone"), ...optionalDate(form,"period_start"), ...optionalDate(form,"period_end") }); if (typeof r?.resource_id === "string") setNewFamily(r.resource_id); }}><label>Custom positive use limit (blank for unlimited)<input name="usage_limit" type="number" min={1} max={1000000} /></label><label>Allowance window<select name="reset_period">{["lifetime","promotion","weekly","monthly"].map(k => <option key={k} value={k}>{k}</option>)}</select></label><label>Explicit allowance timezone<input name="usage_timezone" required placeholder="America/New_York" /></label><label>Promotion starts (when selected)<input name="period_start" type="datetime-local" /></label><label>Promotion ends (when selected)<input name="period_end" type="datetime-local" /></label><button disabled={busy} className="button button-outline">Create immutable allowance policy</button></form></details>
 <form className="merchant-form" action={async form => {
  const input: Record<string, Json> = { merchant_id: merchantId, family_id: formText(form,"family_id"), title: formText(form,"title"), description: formText(form,"description"), offer_type: type, qualification, stacking: formText(form,"stacking"), exclusions: formText(form,"exclusions"), starts_at: new Date(formText(form,"starts_at")).toISOString(), ends_at: new Date(formText(form,"ends_at")).toISOString(), weekly_special: form.get("weekly_special")==="on", weekdays: form.getAll("weekdays").map(Number), location_policy: formText(form,"location_policy"), include_future: form.get("include_future")==="on", allow_local_pause: form.get("allow_local_pause")==="on" };
  if (input.location_policy === "selected") input.location_ids = locationId ? [locationId] : form.getAll("location_ids").map(String);
  if (type === "percentage_off" || type === "bogo") input.discount_bps = Number(form.get("discount_bps"));
  if (type === "fixed_amount_off") input.amount_minor = minorAmount(formText(form,"amount"),formText(form,"currency").toUpperCase()) ?? -1;
  if (type === "bogo") { input.buy_quantity = Number(form.get("buy_quantity")); input.purchase_description = formText(form,"purchase_description"); }
  if (["bogo","free_item"].includes(type)) { input.benefit_quantity = Number(form.get("benefit_quantity")); input.benefit_description = formText(form,"benefit_description"); }
  if (type === "fixed_amount_off" || qualification === "minimum_amount") input.currency = formText(form,"currency").toUpperCase();
  if (qualification === "minimum_amount") input.minimum_minor = minorAmount(formText(form,"minimum"),formText(form,"currency").toUpperCase()) ?? -1;
  if (qualification === "item") input.qualifying_description = formText(form,"qualifying_description");
  if (input.stacking === "reviewed_policy") input.stacking_policy = formText(form,"stacking_policy");
  Object.assign(input, optionalText(form,"local_start"), optionalText(form,"local_end")); await act("offer.create", input);
 }}><label>Stable offer family<select name="family_id" required>{newFamily && !data.families?.some(f=>f.id===newFamily) && <option value={newFamily}>New allowance family</option>}{data.families?.map(f => <option key={f.id} value={f.id}>{f.usage_limit ?? "Unlimited"} uses · {f.reset_period} · {f.status}</option>)}</select></label><label>Offer title<input name="title" maxLength={120} required /></label><label>Offer type<select value={type} onChange={e=>setType(e.target.value)}>{["percentage_off","fixed_amount_off","bogo","free_item"].map(k=><option key={k} value={k}>{k.replaceAll("_"," ")}</option>)}</select></label><label>Public-to-members description<textarea name="description" maxLength={1500} /></label>
 {["percentage_off","bogo"].includes(type) && <label>Discount basis points (1000 is 10%)<input name="discount_bps" type="number" min={1} max={10000} required /></label>}{type==="fixed_amount_off" && <label>Fixed discount amount<input name="amount" inputMode="decimal" required /></label>}{type==="bogo" && <><label>Buy quantity<input name="buy_quantity" type="number" min={1} max={1000} required /></label><label>Qualifying items or category<input name="purchase_description" maxLength={500} required /></label></>}{["bogo","free_item"].includes(type) && <><label>Benefit quantity<input name="benefit_quantity" type="number" min={1} max={1000} required /></label><label>Benefit item description<input name="benefit_description" maxLength={500} required /></label></>}
 <label>Qualifying purchase<select value={qualification} onChange={e=>setQualification(e.target.value)}><option value="none">No minimum</option><option value="minimum_amount">Minimum amount</option><option value="item">Specific item or category</option></select></label>{qualification==="minimum_amount" && <label>Minimum purchase amount<input name="minimum" inputMode="decimal" required /></label>}{qualification==="item" && <label>Qualifying description<input name="qualifying_description" maxLength={500} required /></label>}{(type==="fixed_amount_off" || qualification==="minimum_amount") && <label>Explicit currency code<input name="currency" maxLength={3} pattern="[A-Za-z]{3}" required /></label>}
 <label>Exclusions<textarea name="exclusions" maxLength={1000} /></label><label>Stacking<select name="stacking"><option value="none">Not stackable</option><option value="merchant_promotions">With merchant promotions</option><option value="reviewed_policy">Reviewed merchant-defined policy</option></select></label><label>Merchant-defined stacking policy (if selected)<input name="stacking_policy" maxLength={500} /></label><label>Effective start<input name="starts_at" type="datetime-local" required /></label><label>Effective end<input name="ends_at" type="datetime-local" required /></label>
 <fieldset><legend>Local recurring availability</legend><label className="merchant-check"><input name="weekly_special" type="checkbox" />Weekly special</label><div className="merchant-weekdays">{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((d,index)=><label key={d} className="merchant-check"><input name="weekdays" type="checkbox" value={index} defaultChecked />{d}</label>)}</div><label>Local start time (optional)<input name="local_start" type="time" /></label><label>Local end time (optional)<input name="local_end" type="time" /></label><p>Hours use each location&apos;s timezone through DST.</p></fieldset>
 <label>Location policy<select name="location_policy"><option value="selected">Selected locations</option>{!locationId && <option value="all_current">Snapshot all current locations</option>}</select></label>{!locationId && data.locations?.map(l=><label key={l.id} className="merchant-check"><input name="location_ids" type="checkbox" value={l.id} />{l.name}</label>)}{!locationId && <label className="merchant-check"><input name="include_future" type="checkbox" />Explicitly include future locations with all-current policy</label>}<label className="merchant-check"><input name="allow_local_pause" type="checkbox" defaultChecked />Allow exact location manager pause</label><button disabled={busy} className="button button-primary">Create immutable draft revision</button></form></section>;
}

export function RedemptionConsole({ merchantId, locationId, act, busy }: { merchantId: string; locationId: string; act: Act; busy: boolean }) {
 const [code,setCode]=useState(""),[verified,setVerified]=useState<{ terms: Terms; remaining: number | null } | null>(null),[message,setMessage]=useState("");
 const scope={merchant_id:merchantId,location_id:locationId};
 return <section className="merchant-panel"><h3>Merchant redemption console</h3><p>Verify the member&apos;s one-time code and review its current terms at this selected location before confirming. No retail payment or Wallet debit is processed.</p><form className="merchant-form" action={async()=>{ const r=await act("token.verify",{...scope,capability:code});if(r?.valid && validMerchantTerms(r.terms))setVerified({terms:r.terms,remaining:typeof r.remaining_uses==="number" ? r.remaining_uses : null}); }}><label>One-time member redemption code<input type="password" value={code} onChange={e=>{setCode(e.target.value);setVerified(null);setMessage("");}} autoComplete="off" spellCheck={false} minLength={64} maxLength={64} pattern="[a-f0-9]{64}" required /></label><button disabled={busy} className="button button-outline">Verify current eligibility</button></form>{verified && <div><h4>{verified.terms.title}</h4><TermsSummary terms={verified.terms} /><p>Remaining uses: {verified.remaining ?? "Unlimited"}</p><button disabled={busy} className="button button-primary" onClick={async()=>{const r=await act("token.redeem",{...scope,capability:code});if(r){setCode("");setVerified(null);setMessage("Redemption confirmed once.");}}}>Confirm redemption once</button><button className="button button-outline" onClick={()=>{setCode("");setVerified(null);}}>Cancel confirmation</button></div>}<p role="status">{message}</p></section>;
}
