"use client";
import { useEffect } from "react";
import { merchantClientRendered } from "@/lib/merchants/diagnostics-client";
import Link from "next/link";
import type { Json } from "@/lib/supabase/database.types";
import { merchantPageLink } from "@/lib/merchants/input";
import type { MerchantData } from "@/lib/merchants/contracts";
import { CategoryChoice, MarketChoice, MerchantState, formText, optionalText, optionalDate, useMerchantAction } from "./shared";
export function MerchantSales({ data, query = {}, diagnosticCorrelation }: { data: MerchantData; query?: Record<string, Json>; diagnosticCorrelation?: string }) {
 const { act, busy, status } = useMerchantAction();
 useEffect(()=>{if(diagnosticCorrelation)merchantClientRendered(diagnosticCorrelation,true);},[diagnosticCorrelation]);
 if(data.unavailable || data.restricted) return <MerchantState data={data} />;
 return <div className="merchant-workspace"><p>Work within your assigned market and opportunities. Conversion preserves acquisition attribution and creates a prospect; it does not approve the merchant or grant ownership. Initial merchant tools remain free.</p>
 {data.can_create && <section className="merchant-panel"><h2>Create a merchant lead</h2><form className="merchant-form" action={async form => { await act("lead.create", { name: formText(form,"name"), category: formText(form,"category"), source: formText(form,"source"), market_id: formText(form,"market_id"), ...optionalText(form,"rep_id"), ...optionalText(form,"manager_id") }); }}><label>Prospect business name<input required name="name" maxLength={120} /></label><MarketChoice markets={data.markets} /><CategoryChoice categories={data.categories} /><label>Acquisition source<input name="source" maxLength={120} required /></label><label>Assigned rep ID (blank for yourself)<input name="rep_id" /></label><label>Assigned manager ID (optional)<input name="manager_id" /></label><button disabled={busy} className="button button-primary">Create assigned lead</button></form></section>}
 <section><h2>Assigned sales pipeline</h2>{!data.leads?.length && <p>No opportunities are available in your current assignment.</p>}<div className="merchant-grid">{data.leads?.map(l=><article key={l.id} className="merchant-panel"><h3>{l.name}</h3><p>{l.state.replaceAll("_"," ")} · Acquisition source {l.source}</p>{l.merchant_id && <Link href={`/app/merchants?merchant_id=${l.merchant_id}`}>Converted merchant, where separately authorized</Link>}
 <form className="merchant-form" action={async form => { await act("lead.activity", { lead_id: l.id, kind: formText(form,"kind"), note: formText(form,"note"), ...optionalDate(form,"due_at") }); }}><label>Activity type<select name="kind">{["call","email","meeting","follow_up","note","onboarding_assist"].map(k=><option key={k} value={k}>{k.replaceAll("_"," ")}</option>)}</select></label><label>Activity note<textarea name="note" required maxLength={1200} /></label><label>Follow-up at (optional)<input name="due_at" type="datetime-local" /></label><button disabled={busy} className="button button-outline">Record sales activity</button></form>{l.activities.map(a=><div key={a.id}><h4>{a.kind.replaceAll("_"," ")}</h4><p>{a.note}</p>{a.due_at && <p>Follow-up {new Date(a.due_at).toLocaleString()}</p>}</div>)}
 <form className="merchant-form" action={async form => { await act("lead.state", { lead_id: l.id, expected_version: l.version, state: formText(form,"state") }); }}><label>Pipeline state<select name="state" defaultValue={l.state}>{["new","contacted","interested","onboarding","submitted","approved","declined","inactive"].map(k=><option key={k} value={k}>{k}</option>)}</select></label><button disabled={busy} className="button button-outline">Update pipeline state</button></form>
 {!l.merchant_id && <button disabled={busy} className="button button-primary" onClick={()=>{void act("lead.convert",{lead_id:l.id,expected_version:l.version});}}>Convert once to merchant prospect</button>}
 {l.can_reassign && <details><summary>Reassign opportunity</summary><form className="merchant-form" action={async form=>{await act("lead.reassign",{lead_id:l.id,expected_version:l.version,rep_id:formText(form,"rep_id"),...optionalText(form,"manager_id")});}}><label>New assigned rep ID<input name="rep_id" required /></label><label>New assigned manager ID<input name="manager_id" /></label><button disabled={busy} className="button button-outline">Reassign with history</button></form></details>}</article>)}</div></section>
 {data.leads?.length === 30 && <Link className="button button-outline" href={merchantPageLink(query, {after:data.leads.at(-1)?.id})}>Next sales page</Link>}
 {data.can_assign && <details className="merchant-panel"><summary>Platform sales assignments</summary><form className="merchant-form" action={async form=>{await act("sales.grant",{person_id:formText(form,"person_id"),role:formText(form,"role"),market_id:formText(form,"market_id"),...optionalText(form,"manager_id"),...optionalDate(form,"ends_at")});}}><label>Verified person ID<input name="person_id" required /></label><label>Sales role<select name="role"><option value="sales_rep">Sales rep</option><option value="regional_manager">Regional manager</option></select></label><MarketChoice markets={data.markets} /><label>Manager person ID (optional)<input name="manager_id" /></label><label>Assignment ends at (optional)<input type="datetime-local" name="ends_at" /></label><button disabled={busy} className="button button-outline">Create exact sales assignment</button></form></details>}{status}</div>;
}
