"use client";
import { useState } from "react";
import type { Game } from "@/lib/games/contracts";
import type { VolleyballGame, VolleyballSide, VolleyballPlay, VolleyballStats } from "@/lib/volleyball/contracts";
import { volleyballStatKeys } from "@/lib/volleyball/contracts";
import { buildVolleyballEntry } from "@/lib/volleyball/entry";
import { contextualPrompts, trackingPresets } from "@/lib/stat-tracking/profile";
import { statCatalog } from "@/lib/stat-tracking/catalog";
import { LiveStatConsole } from "../stat-tracking/live-console";
import { useGameIntent } from "../games/intent-provider";
import { GameForm } from "../games/action-form";
import { fieldText, fieldInteger } from "../coordination/action-form";
const sides = ["primary", "opponent"] as const;
const label = (game: Game, side: VolleyballSide) => side === "primary" ? game.primary.label : game.opponent.label;
const base = (game: Game) => ({ game_id: game.id, expected_version: game.version });
function Setup({ game }: { game: Game }) {
  return <section className="live-stat-console"><h3>Initialize Volleyball</h3><p>Match rules and tracking expectations are frozen to this game. Required rally state remains available in Score Only.</p><GameForm label="Initialize Volleyball" build={f => {
    const cap = fieldInteger(f, "score_cap"), limit = fieldInteger(f, "substitution_limit");
    return { operation: "volleyball.configure", input: { ...base(game), configuration: { best_of: fieldInteger(f, "best_of"), normal_target: fieldInteger(f, "normal_target"), deciding_target: fieldInteger(f, "deciding_target"), court_size: fieldInteger(f, "court_size"), win_by_two: f.has("win_by_two"), enforce_lineup: f.has("enforce_lineup"), strict_rotation: f.has("strict_rotation"), allow_reentry: f.has("allow_reentry"), libero_enabled: f.has("libero_enabled"), libero_can_serve: f.has("libero_can_serve"), ...(cap === null ? {} : { score_cap: cap }), ...(limit === null ? {} : { substitution_limit: limit }) } } };
  }}><div className="game-form-grid"><label className="form-field"><span>Best of</span><select name="best_of" defaultValue="3"><option value="3">3 sets</option><option value="5">5 sets</option></select></label>{[{ key: "normal_target", title: "Normal set target", value: 25, max: 99, min: 2 }, { key: "deciding_target", title: "Deciding target", value: 15, max: 99, min: 2 }, { key: "court_size", title: "Players on court", value: 6, max: 6, min: 1 }].map(r => <label className="form-field" key={r.key}><span>{r.title}</span><input type="number" name={r.key} min={r.min} max={r.max} defaultValue={r.value} required /></label>)}<label className="form-field"><span>Score cap (optional)</span><input name="score_cap" type="number" min={2} max={999} /></label><label className="form-field"><span>Substitution limit (optional)</span><input name="substitution_limit" type="number" min={1} max={999} /></label></div>{["win_by_two", "enforce_lineup", "strict_rotation", "allow_reentry", "libero_enabled", "libero_can_serve"].map(k => <label className="game-confirmation" key={k}><input type="checkbox" name={k} defaultChecked={k === "win_by_two" || k === "allow_reentry"} />{k.replaceAll("_", " ")}</label>)}</GameForm></section>;
}
function ProfileEditor({ game, state }: { game: Game; state: VolleyballGame }) {
  return <>{sides.map(side => {
    const p = state.tracking[side];
    return <section key={side}><h4>{label(game, side)} tracking</h4><p>{p.selection.preset.replaceAll("_", " ")} · {p.selection.quick.length} Quick Stats. Not tracked is not zero.</p>{p.can_manage && game.status !== "final" && <GameForm key={`${side}:${p.snapshot_id}`} label="Save game tracking profile" build={f => {
      const preset = fieldText(f, "preset"), enabled = f.getAll("enabled").map(String), quick = Array.from({ length: 8 }, (_, i) => fieldText(f, `quick_${i}`)).filter(Boolean);
      return { operation: "tracking.profile.set", input: { sport_key: "volleyball", scope_type: "game", organization_id: game.organization_id, game_id: game.id, side, expected_profile_version: p.profile_version, expected_game_version: game.version, preset, ...(preset === "custom" ? { enabled } : {}), ...(preset !== p.selection.preset && preset !== "custom" ? {} : { quick }), reason: fieldText(f, "reason") } };
    }}><label className="form-field"><span>Preset</span><select name="preset" defaultValue={p.selection.preset}>{trackingPresets.map(k => <option key={k} value={k}>{k.replaceAll("_", " ")}</option>)}</select></label><details><summary>Custom selection</summary>{statCatalog.volleyball.filter(s => s.classification === "optional").map(s => <label className="game-confirmation" key={s.key}><input name="enabled" type="checkbox" value={s.key} defaultChecked={p.selection.enabled.includes(s.key)} />{s.short_label}</label>)}</details><details><summary>Ordered Quick Stats (up to eight)</summary><div className="game-form-grid">{Array.from({ length: 8 }, (_, i) => <label className="form-field" key={i}><span>Quick Stat {i + 1}</span><select name={`quick_${i}`} defaultValue={p.selection.quick[i] ?? ""}><option value="">None</option>{statCatalog.volleyball.filter(s => s.quick_eligible).map(s => <option key={s.key} value={s.key}>{s.short_label}</option>)}</select></label>)}</div></details><label className="form-field"><span>Change reason</span><input name="reason" maxLength={500} required /></label><p>Changes during play preserve a coverage gap as partial. Required score/state cannot be disabled.</p></GameForm>}</section>;
  })}</>;
}
function Participation({ game, state }: { game: Game; state: VolleyballGame }) {
  return <>{sides.map(side => <section key={side}><h4>{label(game, side)} court order</h4><ol>{state.lineups[side].map(id => <li key={id}>{state.entry_roster.find(r => r.id === id)?.display_name ?? "Athlete"}</li>)}</ol>{state.capabilities.lineups && <>{state.state.set_status !== "active" && state.state.set_status !== "match_complete" && <GameForm label="Set court order" build={f => ({ operation: "volleyball.lineup.set", input: { ...base(game), side, payload: { roster_ids: Array.from({ length: state.configuration.court_size }, (_, i) => fieldText(f, `slot_${i}`)), ...(fieldText(f, "libero") ? { libero_roster_id: fieldText(f, "libero") } : {}) } } })}><div className="game-form-grid">{Array.from({ length: state.configuration.court_size }, (_, i) => <label className="form-field" key={i}><span>Slot {i + 1}{i === 0 ? " / next server" : ""}</span><select name={`slot_${i}`} defaultValue={state.lineups[side][i] ?? ""} required><option value="">Choose athlete</option>{state.entry_roster.filter(r => r.side === side && r.active).map(r => <option key={r.id} value={r.id}>{r.jersey_number ? `#${r.jersey_number} ` : ""}{r.display_name}</option>)}</select></label>)}</div>{state.configuration.libero_enabled && <label className="form-field"><span>Designated libero</span><select name="libero"><option value="">None</option>{state.entry_roster.filter(r => r.side === side).map(r => <option value={r.id} key={r.id}>{r.display_name}</option>)}</select></label>}</GameForm>}{state.state.set_status === "active" && <GameForm label="Record substitution" build={f => ({ operation: "volleyball.substitute", input: { ...base(game), side, payload: { out_roster_id: fieldText(f, "out"), in_roster_id: fieldText(f, "in") } } })}>{["out", "in"].map(k => <label className="form-field" key={k}><span>{k === "out" ? "Outgoing" : "Incoming"} athlete</span><select name={k} required><option value="">Choose athlete</option>{state.entry_roster.filter(r => r.side === side && r.active && (k === "out" ? state.lineups[side].includes(r.id) : !state.lineups[side].includes(r.id))).map(r => <option key={r.id} value={r.id}>{r.display_name}</option>)}</select></label>)}</GameForm>}</>}</section>)}</>;
}
function PlayDescription({ game, state, play }: { game: Game; state: VolleyballGame; play: VolleyballPlay }) {
  const athlete = state.entry_roster.find(r => r.id === play.payload.roster_id);
  return <span>#{play.sequence}{play.set_number !== undefined ? ` · Set ${play.set_number} · ${play.primary_points}:${play.opponent_points}` : ""} · {label(game, play.side)} · {String(play.payload.outcome ?? play.event_type).replaceAll("_", " ")}{athlete ? ` · ${athlete.jersey_number ? `#${athlete.jersey_number} ` : ""}${athlete.display_name}` : ""}</span>;
}
function Box({ game, state }: { game: Game; state: VolleyballGame }) {
  const columns = ["kills", "attack_attempts", "attack_errors", "hitting_percentage", "assists", "digs", "service_aces", "service_errors", "solo_blocks", "block_assists", "receptions", "reception_errors"] as const;
  const short = ["K", "ATT", "ERR", "HIT%", "AST", "DIG", "ACE", "SE", "BS", "BA", "REC", "RE"];
  const value = (stats: VolleyballStats, key: typeof volleyballStatKeys[number]) => { const s = stats[key]; return s.coverage === "not_tracked" ? "Not tracked" : `${s.recorded_value === null ? "Unavailable" : key === "hitting_percentage" ? s.recorded_value.toFixed(3) : s.recorded_value}${s.coverage === "partially_tracked" ? " (partial)" : ""}`; };
  return state.capabilities.stats ? <><p>Not tracked differs from measured zero. Partial values include only recorded facts.</p><div className="live-stat-table"><table><thead><tr><th scope="col">Athlete / team</th>{short.map(k => <th key={k} scope="col">{k}</th>)}</tr></thead><tbody>{[...state.teams.map(t => ({ key: t.side, name: label(game, t.side), stats: t.stats })), ...state.players.map(p => ({ key: p.roster_id, name: `${p.jersey_number ? `#${p.jersey_number} ` : ""}${p.display_name}`, stats: p.stats }))].map(row => <tr key={row.key}><th scope="row">{row.name}</th>{columns.map(k => <td key={k}>{value(row.stats, k)}</td>)}</tr>)}</tbody></table></div><p>Each assisted-block rally is one team block. HIT% = (K − ERR) / ATT; zero attempts has no percentage.</p></> : <p>Statistics are unavailable under the current feature/access settings.</p>;
}
function correctionPayload(play: VolleyballPlay, outcome: string, roster: string) {
  const payload = { ...play.payload };
  if (outcome) payload.outcome = outcome;
  if (payload.outcome === "team_point") { delete payload.roster_id; delete payload.blocker_roster_ids; delete payload.receiver_roster_id; }
  else if (payload.outcome === "assisted_block") { delete payload.roster_id; delete payload.receiver_roster_id; }
  else { delete payload.blocker_roster_ids; if (payload.outcome !== "ace") delete payload.receiver_roster_id; if (roster) payload.roster_id = roster; }
  return payload;
}
function Scorer({ game, state }: { game: Game; state: VolleyballGame }) {
  const intent = useGameIntent(), [side, setSide] = useState<VolleyballSide>("primary"), [athlete, setAthlete] = useState<string | null>(null), [action, setAction] = useState<string | null>(null), [kill, setKill] = useState<string | null>(null), [blockers, setBlockers] = useState<string[]>([]), [message, setMessage] = useState("");
  const p = state.tracking[side].selection, active = game.status === "live" && state.state.set_status === "active" && state.capabilities.operate;
  const roster = state.entry_roster.filter(r => r.side === side && r.active && (!state.configuration.enforce_lineup || state.lineups[side].includes(r.id)));
  const enabled = statCatalog.volleyball.filter(s => s.classification === "optional" && s.actions.length && p.enabled.includes(s.key));
  const entryAllowed = active || action === "assist" && Boolean(kill) && game.status === "live" && state.capabilities.operate;
  async function save(selectedAction: string, selectedAthlete: string | null = athlete) {
    const command = buildVolleyballEntry(game.id, game.version, selectedAction, side, p.enabled.includes("player_attribution") ? selectedAthlete : null, selectedAction === "assist" ? { kill_event_id: kill ?? "" } : selectedAction === "assisted_block" && blockers.length ? { blocker_roster_ids: blockers } : {});
    if (!command) { setMessage("Choose the required athlete or play context."); return; }
    const outcome = await intent.send(command);
    setMessage(outcome.message);
    if (outcome.kind === "saved") {
      setAction(null);setBlockers([]);
      if (contextualPrompts("volleyball", selectedAction, p).includes("assists") && outcome.event_id) {setKill(outcome.event_id);setAction("assist");setAthlete(null);}
    }
  }
  const buttons = (keys: string[]) => <div className="live-stat-quick">{keys.flatMap(k => enabled.filter(s => s.key === k)).map(s => <button className="button button-primary" type="button" key={s.key} disabled={!active || intent.blocked} aria-pressed={action === s.actions[0]} onClick={() => { setAction(s.actions[0]); if (athlete && !["assist", "assisted_block"].includes(s.actions[0])) void save(s.actions[0]); }}>{s.short_label}</button>)}</div>;
  const entry = <><div className="live-stat-side">{sides.map(key => <button type="button" className="button button-outline" aria-pressed={side === key} key={key} onClick={() => {setSide(key);setAthlete(null);setAction(null);setKill(null);}}>{label(game, key)}</button>)}</div><h4>Quick Stats</h4>{buttons(p.quick)}<div className="live-stat-quick live-stat-required"><button type="button" className="button button-outline" disabled={!active || intent.blocked} onClick={() => void save("team_point")}>Point for {label(game, side)}</button></div>{p.enabled.includes("player_attribution") && <><h4>{action ? `Choose athlete for ${action.replaceAll("_", " ")}` : "Select athlete first, or tap a Quick Stat"}</h4><div className="live-stat-athletes">{roster.map(r => <button className="button button-outline" key={r.id} type="button" aria-pressed={athlete === r.id} disabled={!entryAllowed || intent.blocked} onClick={() => { setAthlete(r.id); if (action && !["assist", "assisted_block"].includes(action)) void save(action, r.id); }}>{r.jersey_number ? `#${r.jersey_number} ` : ""}{r.display_name}</button>)}</div><p>Selected: {roster.find(r => r.id === athlete)?.display_name ?? "Team / unattributed"}</p></>}{action === "assist" && <label className="form-field"><span>Accepted same-team kill</span><select value={kill ?? ""} onChange={e => setKill(e.target.value)}><option value="">Choose kill</option>{state.plays.filter(e => e.side === side && e.payload.outcome === "kill").map(e => <option key={e.id} value={e.id}>Kill #{e.sequence}</option>)}</select></label>}{action === "assisted_block" && p.enabled.includes("player_attribution") && <div>{roster.map(r => <label key={r.id} className="game-confirmation"><input type="checkbox" checked={blockers.includes(r.id)} onChange={e => setBlockers(e.target.checked ? [...blockers, r.id] : blockers.filter(id => id !== r.id))} />{r.display_name}</label>)}</div>}{action && <button type="button" className="button button-primary" disabled={intent.blocked || !state.capabilities.operate || game.status !== "live"} onClick={() => void save(action)}>Record {action.replaceAll("_", " ")}</button>}<p role="status" aria-live="polite">{message}</p>{state.capabilities.operate && ["pending", "completed"].includes(state.state.set_status) && <GameForm label="Start next set" build={f => ({ operation: "volleyball.set.start", input: { ...base(game), side: fieldText(f, "side") } })}><label className="form-field"><span>Initial serving team</span><select name="side">{sides.map(key => <option key={key} value={key}>{label(game, key)}</option>)}</select></label></GameForm>}</>;
  const recent = <><h4>Recent entries / Undo</h4><ol className="live-stat-recent">{state.plays.toSorted((a,b) => b.sequence-a.sequence).slice(0,8).map(play => <li key={play.id}><PlayDescription game={game} state={state} play={play} />{state.capabilities.correct && <details><summary>Undo / Correct #{play.sequence}</summary><GameForm label="Reverse this fact" build={f => ({ operation: "volleyball.event.reverse", input: { ...base(game), event_id: play.id, reason: fieldText(f, "reason") } })}><label className="form-field"><span>Reason</span><input name="reason" maxLength={500} required /></label><p>Original evidence remains. Later set, assist and court dependencies must remain valid.</p></GameForm><GameForm label="Save attribution / outcome correction" build={f => ({ operation: "volleyball.event.correct", input: { ...base(game), event_id: play.id, event_type: play.event_type, side: play.side, payload: correctionPayload(play, fieldText(f, "outcome"), fieldText(f, "roster_id")), reason: fieldText(f, "reason") } })}>{play.event_type === "rally" && <label className="form-field"><span>Rally outcome</span><select name="outcome" defaultValue={String(play.payload.outcome)}>{["kill", "attack_error", "ace", "service_error", "solo_block", "assisted_block", "reception_error", "team_point"].map(k => <option key={k} value={k}>{k.replaceAll("_", " ")}</option>)}</select></label>}<label className="form-field"><span>Replacement athlete</span><select name="roster_id"><option value="">Keep recorded attribution</option>{state.entry_roster.filter(r => r.side === play.side).map(r => <option key={r.id} value={r.id}>{r.display_name}</option>)}</select></label><label className="form-field"><span>Correction reason</span><input name="reason" required maxLength={500} /></label></GameForm></details>}</li>)}</ol></>;
  return <LiveStatConsole label="Volleyball Live Stat Console" state={<><strong>{game.primary.label} {state.state.primary_points} : {state.state.opponent_points} {game.opponent.label}</strong><span>Set {state.state.set_number} · Sets {state.state.primary_sets}–{state.state.opponent_sets} · {state.state.set_status.replaceAll("_", " ")}</span><span>{state.state.serving_side ? `${label(game, state.state.serving_side)} serving · ${state.entry_roster.find(r => r.id === state.server_roster_id)?.display_name ?? "Server unattributed"}` : "Serve awaits set start"} · {game.status}</span></>} entry={entry} recent={recent} more={buttons(enabled.filter(s => !p.quick.includes(s.key)).map(s => s.key))} lineup={<Participation game={game} state={state} />} box={<Box game={game} state={state} />} plays={<ol className="live-stat-recent">{state.plays.map(play => <li key={play.id}><PlayDescription game={game} state={state} play={play} /></li>)}</ol>} settings={<ProfileEditor game={game} state={state} />} />;
}
export function VolleyballPanel({ game, family }: { game: Game; family: boolean }) {
  if (game.sport_key !== "volleyball" || !game.volleyball) return null;
  const state = game.volleyball;
  if (!state.configured) return !family && state.capabilities.configure ? <Setup game={game} /> : null;
  return family ? <section><h3>Volleyball · Sets {state.state.primary_sets}–{state.state.opponent_sets}</h3><Box game={game} state={state} /></section> : <Scorer game={game} state={state} />;
}
