import NetlifyForm from "@/components/NetlifyForm";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import s from "../../get-started/start.module.css";
export const metadata={title:"Start a Fundraiser"};
export default function Page(){return <main className={s.page}><SiteHeader/><section className={s.intro}><div className={s.eyebrow}>START A FUNDRAISER</div><h1>Tell us about your organization and goal.</h1><p>Give us enough information to understand the opportunity. We can help you choose the Boss fundraising mix that best fits your team or organization.</p></section><section className={s.formWrap}><NetlifyForm name="boss-fundraising-interest"><p className={s.hidden}><label>Do not fill this out: <input name="bot-field"/></label></p><div className={s.grid}>
<label>First name<input name="firstName" required autoComplete="given-name"/></label><label>Last name<input name="lastName" required autoComplete="family-name"/></label><label>Email<input name="email" required type="email" autoComplete="email"/></label><label>Phone<input name="phone" required type="tel" autoComplete="tel"/></label><label>Role / title<input name="role"/></label><label>Organization name<input name="organization" required/></label><label>City<input name="city" required/></label><label>State<input name="state" required/></label>
<label>Organization type<select name="organizationType" required defaultValue=""><option value="" disabled>Select one</option><option>Sports Team</option><option>Athletic Organization</option><option>School</option><option>School Band</option><option>Cheer Program</option><option>Church Youth Group</option><option>Children's Ministry</option><option>Youth Organization</option><option>Nonprofit</option><option>Community Organization</option><option>Missions Group</option><option>Camp</option><option>Other</option></select></label>
<label>Approx. participants / members<input name="participantCount" inputMode="numeric"/></label>
<label>Fundraising goal<input name="goalAmount" placeholder="$"/></label><label>Desired start date<input name="desiredStartDate" type="date"/></label>
<label className={s.full}>What will the funds support?<textarea name="fundPurpose" rows={4} required/></label>
<fieldset className={s.full} style={{border:"1px solid #d8d4cd",borderRadius:12,padding:18}}><legend style={{fontSize:12,fontWeight:800,padding:"0 6px"}}>Fundraising interests</legend><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10,fontSize:13}}><label><input type="checkbox" name="interests" value="Digital Boss Bucks Cards"/> Digital Boss Bucks</label><label><input type="checkbox" name="interests" value="Digital Money Board"/> Digital Money Board</label><label><input type="checkbox" name="interests" value="Direct Donations"/> Direct Donations</label><label><input type="checkbox" name="interests" value="Merchandise"/> Team / Organization Merchandise</label><label><input type="checkbox" name="interests" value="Physical Cards"/> Physical Cards, if available</label><label><input type="checkbox" name="interests" value="Need Help Choosing"/> Help Me Choose</label></div></fieldset>
<label className={s.full}>What best describes you?<select name="intent" required defaultValue=""><option value="" disabled>Select one</option><option>Ready to Get Started</option><option>I Want a Demo</option><option>I Need More Information</option></select></label>
<label className={s.full}>Anything else we should know?<textarea name="notes" rows={4}/></label></div><input type="hidden" name="leadType" value="Fundraising Organization"/><input type="hidden" name="source" value="website-fundraising-intake"/><button type="submit">Submit Fundraising Interest →</button><p className={s.note}>By submitting, you are asking the Boss team to contact you about fundraising.</p></NetlifyForm></section></main>}
