import Link from "next/link";
import type { AttendanceData, AttendanceQuery } from "@/lib/attendance/contracts";
import type { VolunteerData, VolunteerQuery } from "@/lib/volunteers/contracts";
import { AttendanceCard } from "@/components/attendance/console";
import { VolunteerCard } from "@/components/volunteers/console";
import { coordinationHref } from "./presentation";

export function CoordinationHub({ attendance, volunteers, attendanceQuery: requestedAttendanceQuery, volunteerQuery: requestedVolunteerQuery, staff, family = false }: { attendance: AttendanceData; volunteers: VolunteerData; attendanceQuery: AttendanceQuery; volunteerQuery: VolunteerQuery; staff?: AttendanceData; family?: boolean }) {
  const attendanceQuery = { ...requestedAttendanceQuery, ...(attendance.organization_id ? { organization_id: attendance.organization_id } : {}) }, volunteerQuery = { ...requestedVolunteerQuery, ...(volunteers.organizationId ? { organization_id: volunteers.organizationId } : {}) };
  const required = attendance.occurrences.filter(occurrence => attendance.features.rsvp === true && occurrence.rsvp_mode === "required" && ["scheduled", "confirmed"].includes(occurrence.status) && Date.parse(occurrence.end_at) > Date.now() && occurrence.subjects.some(subject => (subject.capabilities.respond || subject.capabilities.manage) && (!subject.response || ["pending", "unknown"].includes(subject.response.status) || subject.response.needs_reconfirmation))), commitments = volunteers.commitments.filter(shift => shift.my_assignment?.status === "active"), next = staff?.occurrences.find(occurrence => occurrence.capabilities.manage && !["canceled", "archived", "completed", "draft"].includes(occurrence.status));
  if (!required.length && !commitments.length && !next && attendance.features.attendance !== true && volunteers.features.volunteers !== true) return null;
  return <section className="coordination-hub admin-section" aria-label={family ? "Family Hub" : "Upcoming actions"}><div className="section-heading"><h2>{family ? "Family Hub" : "Upcoming actions"}</h2><p>Current RSVP actions and your own volunteer commitments.</p></div>
    {family && attendance.children.length > 0 && <form method="get" action="/app/families" className="coordination-child-switch">{attendanceQuery.organization_id && <input type="hidden" name="org" value={attendanceQuery.organization_id} />}<label className="form-field"><span>Child</span><select key={attendanceQuery.child_person_id ?? "family"} name="child" defaultValue={attendanceQuery.child_person_id ?? ""}><option value="">Whole family</option>{attendance.children.map(child => <option key={child.person_id} value={child.person_id}>{child.display_name}</option>)}</select></label><button type="submit" className="button button-outline button-small">View child</button></form>}
    {next && <section className="coordination-hub-section"><h3>Next team event</h3><AttendanceCard occurrence={next} compact /></section>}
    {attendance.features.attendance === true && <section className="coordination-hub-section"><h3>Responses needed</h3>{required.length ? <div className="coordination-list">{required.slice(0, 5).map(occurrence => <AttendanceCard key={`${occurrence.event_id}:${occurrence.occurrence_key}`} occurrence={occurrence} rsvpEnabled={attendance.features.rsvp === true} compact={!family} />)}</div> : <p className="empty-state">No outstanding required responses in this date range.</p>}<Link className="card-link" href={coordinationHref("attendance", attendanceQuery)}>All family and personal attendance</Link></section>}
    {(volunteers.features.volunteers === true || commitments.length > 0) && <section className="coordination-hub-section"><h3>My volunteer commitments</h3><p className="coordination-hint">Commitments belong to the assigned person. Switching a child does not grant access to another person&apos;s signup.</p>{commitments.length ? <div className="coordination-list">{commitments.slice(0, 5).map(shift => <VolunteerCard key={shift.id} shift={shift} query={volunteerQuery} compact={!family} signupEnabled={volunteers.features.volunteers === true && volunteers.features.self_signup === true} />)}</div> : <p className="empty-state">No active volunteer commitments in this date range.</p>}<Link className="card-link" href={coordinationHref("volunteers", { ...volunteerQuery, view: "family" })}>All my volunteer commitments</Link></section>}
  </section>;
}
