import type { Json } from "../supabase/database.types";
import { volunteerFeatureKeys, volunteerOperations, shiftStatuses, emptyVolunteers, type VolunteerAssignment, type VolunteerCommand, type VolunteerData, type VolunteerQuery, type VolunteerShift } from "./contracts";
import { boundedText, choice, collection, count, finiteKeys, instant, integer, isRecord, nullable, oneOf, optionalId, optionalTime, queryTimes, text, uuid, validOccurrenceKey, version } from "../coordination/input";
const fields: Record<typeof volunteerOperations[number], string[]> = {
  "volunteers.configure": ["organization_id", "configuration"], "role.upsert": ["organization_id", "role_id", "expected_version", "name", "description", "status"],
  "shift.upsert": ["organization_id", "shift_id", "expected_version", "role_id", "title", "scope_type", "scope_id", "event_id", "occurrence_key", "start_at", "end_at", "capacity", "instructions", "location", "status", "visibility", "signup_deadline", "reminder_minutes_before"],
  "assignment.signup": ["shift_id"], "assignment.cancel": ["assignment_id", "expected_version"], "assignment.assign": ["shift_id", "person_id"], "assignment.reassign": ["assignment_id", "expected_version", "person_id"],
  "shift.announce": ["shift_id", "title", "body"], "reminders.prepare": ["organization_id", "window_start", "window_end"],
};
export function parseVolunteerCommand(value: unknown): VolunteerCommand | null {
  if (!isRecord(value) || !finiteKeys(value, ["operation", "input"]) || !oneOf(value.operation, volunteerOperations) || !isRecord(value.input)) return null;
  const operation = value.operation as VolunteerCommand["operation"], input = value.input;
  if (!finiteKeys(input, fields[operation])) return null;
  for (const [key, item] of Object.entries(input)) {
    if (["organization_id", "role_id", "shift_id", "scope_id", "person_id", "assignment_id"].includes(key) && !uuid(item)) return null;
    if (key === "event_id" && !nullable(item, uuid)) return null;
    if (key === "expected_version" && !integer(item, 1)) return null;
    if (["instructions", "description"].includes(key) && !nullable(item, value => boundedText(value, key === "description" ? 1000 : 2000))) return null;
    if (key === "location" && !nullable(item, value => boundedText(value, 300))) return null;
    if (key === "occurrence_key" && !nullable(item, value => typeof value === "string" && validOccurrenceKey(value))) return null;
  }
  if (operation === "volunteers.configure") {
    if (!uuid(input.organization_id) || !isRecord(input.configuration) || !Object.keys(input.configuration).length || !finiteKeys(input.configuration, volunteerFeatureKeys) || Object.entries(input.configuration).some(([key, item]) => key === "minimum_signup_age" ? !integer(item, 18, 100) : typeof item !== "boolean")) return null;
  } else if (operation === "role.upsert") {
    if (!uuid(input.organization_id) || !boundedText(input.name, 120) || !input.name.trim() || input.status !== undefined && !oneOf(input.status, ["active", "inactive", "archived"]) || input.role_id !== undefined && !integer(input.expected_version, 1)) return null;
  } else if (operation === "shift.upsert") {
    if (!uuid(input.organization_id) || !uuid(input.role_id) || !uuid(input.scope_id) || !oneOf(input.scope_type, ["organization", "unit", "team"]) || !boundedText(input.title, 200) || !input.title.trim() || !instant(input.start_at) || !instant(input.end_at) || Date.parse(input.end_at) <= Date.parse(input.start_at) || !integer(input.capacity, 1, 10_000) || !oneOf(input.status, shiftStatuses) || !oneOf(input.visibility, ["members", "staff"]) || input.signup_deadline !== undefined && (!nullable(input.signup_deadline, instant) || instant(input.signup_deadline) && Date.parse(input.signup_deadline) > Date.parse(input.end_at)) || input.shift_id !== undefined && !integer(input.expected_version, 1) || input.occurrence_key != null && !uuid(input.event_id)) return null;
    if (input.reminder_minutes_before !== undefined && !integer(input.reminder_minutes_before, 0, 10080)) return null;
  } else if (operation === "shift.announce") { if (!uuid(input.shift_id) || !boundedText(input.title, 200) || !input.title.trim() || !boundedText(input.body, 4000) || !input.body.trim()) return null;
  } else if (operation === "reminders.prepare") { if (!uuid(input.organization_id) || !instant(input.window_start) || !instant(input.window_end) || Date.parse(input.window_end) <= Date.parse(input.window_start) || Date.parse(input.window_end) - Date.parse(input.window_start) > 7 * 86_400_000) return null;
  } else if (operation === "assignment.signup" ? !uuid(input.shift_id) : operation === "assignment.assign" ? !uuid(input.shift_id) || !uuid(input.person_id) : !uuid(input.assignment_id) || !integer(input.expected_version, 1) || operation === "assignment.reassign" && !uuid(input.person_id)) return null;
  return { operation, input: input as Record<string, Json | undefined> };
}
export function parseVolunteerQuery(params: Record<string, string | string[] | undefined>, now = new Date()): VolunteerQuery | null {
  const range = queryTimes(params, now); if (!range) return null;
  const view = params.view ?? "upcoming"; if (!oneOf(view, ["upcoming", "manage", "family"])) return null;
  const query: VolunteerQuery = { view: view as VolunteerQuery["view"], ...range };
  for (const [param, key] of [["org", "organization_id"], ["shift", "shift_id"], ["team", "team_id"], ["unit", "unit_id"], ["event", "event_id"], ["person", "person_id"]] as const) { const value = params[param]; if (value !== undefined && value !== "") { if (!uuid(value)) return null; query[key] = value; } }
  if (params.limit !== undefined) { if (typeof params.limit !== "string" || !/^\d+$/.test(params.limit) || !integer(Number(params.limit), 1, 100)) return null; query.limit = Number(params.limit); }
  return query;
}
function assignment(row: Record<string, unknown>): VolunteerAssignment | null { return uuid(row.id) && oneOf(row.status, ["active", "canceled"]) ? { id: row.id, person_id: optionalId(row.person_id), label: text(row, "label", "You", 200), status: row.status as "active" | "canceled", version: version(row.version), can_cancel: row.can_cancel === true } : null; }
function shift(row: Record<string, unknown>, detail = false): VolunteerShift | null {
  if (!uuid(row.id) || !uuid(row.role_id) || !uuid(row.scope_id) || !instant(row.start_at) || !instant(row.end_at) || !oneOf(row.scope_type, ["organization", "unit", "team"]) || !oneOf(row.status, shiftStatuses) || !oneOf(row.visibility, ["members", "staff"])) return null;
  const canManage = row.can_manage === true, canAssign = row.can_assign === true;
  return { id: row.id, label: text(row, "label", text(row, "title", "Volunteer shift"), 200), organization_id: optionalId(row.organization_id), role_id: row.role_id, role_label: text(row, "role_label", "Volunteer", 200), start_at: row.start_at, end_at: row.end_at, capacity: count(row.capacity), filled: count(row.filled), unfilled: count(row.unfilled), status: row.status as VolunteerShift["status"], visibility: row.visibility as "members" | "staff", signup_deadline: optionalTime(row.signup_deadline), scope_type: row.scope_type as VolunteerShift["scope_type"], scope_id: row.scope_id, scope_label: text(row, "scope_label", "", 200) || null, event_label: text(row, "event_label", "", 200) || null, event_id: optionalId(row.event_id), occurrence_key: typeof row.occurrence_key === "string" && validOccurrenceKey(row.occurrence_key) ? row.occurrence_key : null, version: version(row.version), my_assignment: isRecord(row.my_assignment) ? assignment(row.my_assignment) : null, can_signup: row.can_signup === true, can_manage: canManage, can_assign: canAssign, can_announce: row.can_announce === true, event_context_changed: row.event_context_changed === true, reminder_minutes_before: integer(row.reminder_minutes_before, 0, 10080) ? row.reminder_minutes_before : 60, instructions: detail ? text(row, "instructions", "", 2000) || null : null, location: detail ? text(row, "location", "", 300) || null : null, assignments: detail && (canManage || canAssign) ? collection(row.assignments, assignment, 1000) : [] };
}
export function projectVolunteerData(value: unknown): VolunteerData | null {
  if (!isRecord(value) || !isRecord(value.features) || !Array.isArray(value.shifts)) return null;
  const features: VolunteerData["features"] = {}; for (const key of volunteerFeatureKeys) { const item = value.features[key]; if (key === "minimum_signup_age" ? integer(item, 18, 100) : typeof item === "boolean") features[key] = item as boolean | number; }
  return { ...emptyVolunteers, navigation_available: value.navigation_available === true, options_limited: value.options_limited === true, features, person: isRecord(value.person) ? choice(value.person) : null, organizations: collection(value.organizations, choice, 101), organizationId: optionalId(value.organizationId), operations: Array.isArray(value.operations) ? value.operations.filter((operation): operation is VolunteerData["operations"][number] => oneOf(operation, volunteerOperations)) : [], roles: collection(value.roles, row => uuid(row.id) ? { id: row.id, label: text(row, "label", text(row, "name", "Volunteer role"), 200), description: text(row, "description", "", 2000) || null, status: oneOf(row.status, ["active", "inactive", "archived"]) ? row.status as "active" | "inactive" | "archived" : "inactive", version: version(row.version) } : null), teams: collection(value.teams, choice), units: collection(value.units, choice), events: collection(value.events, row => { const item = choice(row); return item ? { ...item, occurrences: collection(row.occurrences, occurrence => typeof occurrence.occurrence_key === "string" && validOccurrenceKey(occurrence.occurrence_key) && instant(occurrence.start_at) && instant(occurrence.end_at) ? { occurrence_key: occurrence.occurrence_key, start_at: occurrence.start_at, end_at: occurrence.end_at, status: text(occurrence, "status", "scheduled", 30) } : null, 400) } : null; }), shifts: collection(value.shifts, row => shift(row)), detail: isRecord(value.detail) ? shift(value.detail, true) : null, commitments: collection(value.commitments, row => shift(row)), candidates: collection(value.candidates, choice, 1000), targets: collection(value.targets, row => uuid(row.scope_id) && oneOf(row.scope_type, ["organization", "unit", "team"]) ? { scope_id: row.scope_id, scope_type: row.scope_type as "organization" | "unit" | "team", label: text(row, "label", "Exact scope", 200) } : null, 101) };
}
