import type { StatData, StatSummary } from "@/lib/stat-intelligence/contracts";
const metricLabels: Record<string, string> = { fgm: "Field goals made", fga: "Field goal attempts", tpm: "Three-pointers made", tpa: "Three-point attempts", ftm: "Free throws made", fta: "Free throw attempts", pa: "Plate appearances", ab: "At bats", rbi: "Runs batted in", hbp: "Hit by pitch", avg: "Batting average", obp: "On-base percentage", slg: "Slugging percentage", ops: "OPS", era: "ERA", whip: "WHIP", scoring_for: "Scoring for", scoring_against: "Scoring against" };
const label = (v: string) => metricLabels[v] ?? v.replaceAll("_", " ").replace(/^./, c => c.toUpperCase());
const value = (v: number | null) => v === null ? "Unavailable" : Number.isInteger(v) ? String(v) : v.toFixed(3);
function Summary({ data }: { data: StatSummary }) {
  return <><p>{data.source_game_count} eligible official final games · Confirmed GP {data.confirmed_gp}{data.participation_unknown_games > 0 ? ` · ${data.participation_unknown_games} games with unknown participation` : " · No unknown participation in this projection"}</p>{data.participation_partial_games > 0 && <p>{data.participation_partial_games} games with partial participation evidence. GP counts confirmed appearances.</p>}{data.era_conventions.length > 0 && <p>ERA innings basis: {data.era_conventions.join(", ")}{data.era_conventions.length > 1 ? ". Combined ERA unavailable for mixed conventions." : ". Pitching workload uses outs."}</p>}<dl className="athlete-history-stats">{Object.entries(data.metrics).map(([key, m]) => <div key={key}><dt>{label(key)}</dt><dd>{m.complete_value === null ? m.untracked_games > 0 && m.legacy_unknown_games === 0 && m.partial_games === 0 ? "Not tracked" : "Complete total unavailable" : m.complete_games < data.source_game_count ? `Tracked cohort total: ${value(m.complete_value)}` : value(m.complete_value)}</dd><dd>{m.complete_games} complete · {m.partial_games} partial · {m.untracked_games} untracked · {m.legacy_unknown_games} legacy unknown</dd>{m.partial_games + m.legacy_unknown_games > 0 && <dd>Observed: {value(m.observed_value)}</dd>}{m.per_tracked_game !== null && <dd>{value(m.per_tracked_game)} per tracked played game ({m.played_complete_games})</dd>}</div>)}</dl><p>Derived rates use jointly tracked input cohorts.</p><dl className="athlete-history-stats">{Object.entries(data.rates).map(([key, r]) => <div key={key}><dt>{label(key)}</dt><dd>{value(r.value)}</dd>{r.reason && <dd>{label(r.reason)}</dd>}</div>)}</dl></>;
}
export function StatIntelligenceHub({ data, title, teamLabels = {}, seasonLabels = {} }: { data: StatData; title: string; teamLabels?: Record<string, string>; seasonLabels?: Record<string, string> }) {
  return <section className="admin-section stat-intelligence-hub" aria-label={title}><div className="section-heading"><h2>{title}</h2><p>Official sealed results. Unclassified and non-official games are excluded. Coverage stays visible; rostered does not mean played.</p></div>{data.restricted ? <p role="status">Statistics are restricted for this context.</p> : data.unavailable ? <p role="alert">Statistics are temporarily unavailable.</p> : data.refresh_pending || !data.is_current ? <p role="status">Statistics refresh pending. Current totals are not yet available.</p> : data.summary && <><p className="form-notice">Current statistical generation</p><Summary data={data.summary} />{data.unassigned_game_count > 0 && <p>{data.unassigned_game_count} eligible unassigned / legacy season games included in career.</p>}{data.segments.map(s => <details key={`${s.organization_id}:${s.team_id}:${s.season_id}`}><summary>{teamLabels[s.team_id] ?? "Originating team"} · {s.season_id ? seasonLabels[s.season_id] ?? "Recorded season" : "Unassigned / legacy"}</summary><p>Generation {s.generation} · Refreshed {new Date(s.refreshed_at).toISOString()}</p><Summary data={s.summary} /></details>)}</>}</section>;
}
