import Link from "next/link";
import ApprovedHeader from "@/components/ApprovedHeader";
import ApprovedFooter from "@/components/ApprovedFooter";
import home from "@/app/approvedHome.module.css";
import s from "./account.module.css";
export const metadata = {title:"Your Boss Bucks Account",description:"One family account across participating teams, churches and organizations. Learn how eligible fundraising credits support approved participation expenses."};
function Photo({crop,alt}:{crop:string;alt:string}){return <svg viewBox={crop} preserveAspectRatio="xMidYMid slice" role="img" aria-label={alt}><image href="/design/boss-bucks-account-approved.png" width="721" height="2048"/></svg>}
const expenses=[['01','Fees & registration','Approved sports, team and organization participation costs.'],['02','Gear & equipment','Approved items needed for participation, including required uniforms where authorized.'],['03','Camps & events',"Sports camps, children’s camps, church youth camps and approved organization events."],['04','Tournaments','Approved tournament and related participation expenses.'],['05','Eligible travel & lodging','Approved transportation and hotel costs connected to team or organization activities.']];
const faqs=[
['Can I include multiple children in one account?','Yes. The planned family model supports multiple children, each with participant attribution and a combined parent view. Each child has a personal fundraising link and QR code associated with their campaign.'],
['Can I connect multiple organizations?','Yes. Participating teams, churches, schools and community organizations can appear in the same family view. Each campaign’s rules still apply.'],
['Can I move funds freely between children or organizations?','A shared view is not permission to reassign restricted funds. Transfers or cross-activity use must follow the applicable program and organization rules. An unrestricted transfer feature is not promised.'],
['What expenses can Boss Bucks be used for?','Eligible uses include approved registration and participation fees, gear, equipment, camps, events, tournaments and activity-related travel and lodging. Eligibility depends on the organization, campaign and available program features.'],
['Can I withdraw the balance or send it to my bank?','No. Family credits are for approved expenses. Only eligible organizational proceeds may settle to an approved organization bank account.'],
['Can Boss Bucks reimburse an expense I already paid?','An expense must be eligible and follow an authorized process. Personal cash reimbursement is not promised. Confirm eligibility and the available payment method before spending; an out-of-pocket purchase does not automatically qualify for repayment.'],
['When will fuel and restaurant gift cards be available?','These benefits are coming soon. Vendors, limits and redemption procedures will be provided as benefits become available. Eligible activity-related travel and lodging are part of the intended expense scope, subject to available redemption methods.'],
['Does fundraising guarantee every expense will be covered?','No. Available support depends on fundraising results, campaign allocations and eligibility. Our goal is to expand opportunity and reduce financial pressure.']
];
export default function Page(){return <div className={home.home}><a className={home.skipLink} href="#main-content">Skip to content</a><ApprovedHeader/><main id="main-content" className={s.page}>
<section className={s.hero}><div><p className={s.eyebrow}>YOUR BOSS BUCKS ACCOUNT</p><h1>One family.<br/>Many activities.<br/><em>More possibilities.</em></h1><p>Bring eligible fundraising credits from participating teams, churches and organizations into one family view.</p><p>Less financial pressure. More room to participate, grow and pursue their potential.</p><a className={s.button} href="#how-it-works">Explore How It Works →</a></div><div className={s.heroPhoto}><Photo crop="390 39 331 318" alt="Parents reviewing a phone together beside a community sports field"/></div></section>
<section className={s.intro}><div><h2>Multiple kids.<br/>Multiple organizations.<br/><em>One place.</em></h2><p>A basketball season. A church youth camp. A club tournament. Another child’s school or community activity. Family life rarely fits inside a single organization.</p><p>Connect multiple children and participating organizations in one family account. See progress by child, team and organization, alongside a combined view of eligible credits.</p><p>Each campaign’s spending rules still apply.</p></div><div><div className={s.account}><div className={s.accountTop}>THE BOSS <span>Family Account</span></div><div className={s.accountBody}><p className={s.eyebrow}>YOUR BOSS BUCKS</p><h3>Everyone’s effort. One family view.</h3>{[['School basketball','School team','AB'],['Church youth camp','Church youth group','AB'],['Club soccer','Community club','CD']].map(([title,org,initials])=><div className={s.accountRow} key={title}><span>{initials}</span><div><strong>{title}</strong><small>{org}</small></div><b aria-hidden="true">›</b></div>)}<p className={s.note}>Track each child, campaign and eligible balance.</p></div></div><p className={s.note}>Illustrative account preview. Platform vision. Features and eligible uses vary by program.</p></div></section>
<section id="how-it-works" className={s.stepsSection}><div className={s.steps}>{[['Connect.','Join the approved campaign associated with your child’s participating team, church or organization.'],['Share.','Use the participant’s assigned link or QR code so eligible support is attributed to the correct child and campaign.'],['Track.','See fundraising activity and eligible credits allocated under the campaign’s rules.'],['Apply.','Use available credits toward approved activity costs through the program’s authorized spending process.']].map(([title,copy],i)=><article key={title}><span className={s.number}>{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className={s.allocation}><h3>How support is allocated</h3><p>Campaigns can include physical or digital Boss Bucks discount cards, donations and the Digital Money Board. An organization’s fundraising terms determine the share supporting its program and any eligible participant or family credit. A supporter’s purchase or donation is not automatically the amount available to a family.</p><Link href="/fundraising">Explore Boss Fundraising →</Link></div></section>
<section className={s.benefits}><article><div><h3>Discount membership</h3><p>Access offers from participating businesses under your membership’s coverage and offer rules. Help supporters save while supporting an approved fundraiser.</p></div><Photo crop="235 805 115 170" alt="A parent and child browsing athletic footwear"/></article><article><div><h3>Earned Boss Bucks</h3><p>Eligible fundraising credits help cover approved activity-related expenses through participating teams, churches and organizations.</p></div><Photo crop="581 803 130 178" alt="A teenager carrying a backpack outdoors"/></article><p className={s.distinction}>These are separate benefits. Buying a membership does not turn its price into a personal spending balance. Merchant discounts do not automatically add money to your fundraising account.</p></section>
<section className={s.expenses}><div className={s.expenseHeading}><h2>Help cover the cost<br/><em>of showing up.</em></h2><p>Make more of the activities your children love possible. Eligible uses depend on organization rules, the campaign and available program features.</p></div><div className={s.expenseGrid}>{expenses.map(([n,title,copy])=><article key={title}><span className={s.number}>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className={s.photos}><Photo crop="0 1119 354 208" alt="A girls volleyball team encouraging each other in a gym"/><Photo crop="367 1119 353 208" alt="Young people and a group leader enjoying an outdoor camp activity"/></div><p className={s.note}>Expenses must relate to an approved participating activity. Ordinary household purchases and unrelated trips fall outside this purpose. Confirm eligibility before incurring an expense.</p></section>
<section className={s.coming}><div><p className={s.pill}>COMING SOON</p><h2>More ways to<br/><em>cover the journey.</em></h2><p>Planned fuel and restaurant gift cards would help cover approved activity-related travel and meal expenses.</p><p className={s.note}>Program rules apply. Vendors, limits and redemption procedures will be provided as benefits become available.</p></div><figure><Photo crop="318 1343 180 108" alt="A driver refueling a vehicle"/><figcaption>Fuel gift cards</figcaption></figure><figure><Photo crop="510 1343 194 108" alt="People sharing a restaurant meal"/><figcaption>Restaurant gift cards</figcaption></figure></section>
<section className={s.integrity}><div><h2>One family view.<br/><em>Every dollar has a purpose.</em></h2><h3>Approved expenses. Clear attribution. Organization rules.</h3><p>Family credits and organizational proceeds remain distinct. Families use eligible credits for approved costs. Only eligible organizational proceeds may settle to an approved organization bank account.</p><p><strong>Family Boss Bucks cannot be withdrawn as cash or transferred to a personal bank account.</strong></p><p>The intended account experience keeps the source, allocation and use of credits identifiable, with clear records of approved spending. Families need to know what is available and what remains subject to processing or review.</p><p>A combined view does not erase restrictions or make every balance available for every activity. Final approval and redemption procedures will be provided as account features become available.</p></div><aside><h3>A practical family example</h3><p>Manage one child’s school basketball fundraiser, that child’s church youth-camp fundraiser and a sibling’s club-team fundraiser together. Each retains its attribution and applicable spending rules.</p><div className={s.math}><div><span>Approved registration</span><strong>$450</strong></div><div><span>Eligible credits applied</span><strong>−$300</strong></div><div><span>Remaining to pay</span><strong>$150</strong></div></div><p className={s.note}>Illustrative example, not a promise of results. Credits must be available and authorized for this expense. Other restricted balances are not automatically available to cover the difference.</p></aside></section>
<section className={s.value}><article><span className={s.number}>01</span><h3>Less pressure for families</h3><p>Bring multiple children’s fundraising into one place. Understand progress and eligible balances. Help cover fees, camps, equipment and activity-related travel through effort and community support.</p></article><article><span className={s.number}>02</span><h3>Stronger support for organizations</h3><p>Give families a clear reason to participate in fundraising. Keep organizational proceeds distinct from family credits, preserve campaign attribution and help more young people access your programs.</p></article><article><span className={s.number}>03</span><h3>A clear purpose for supporters</h3><p>Choose a campaign and know which participant or organization you support. Where offered, enjoy Boss Bucks membership benefits under the campaign’s terms.</p></article></section>
<section className={s.faq}><div><h2>Frequently<br/><em>Asked Questions.</em></h2><p>Clear answers about your Boss Bucks account.</p></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
<section className={s.closing}><div><h2>Their potential<br/>deserves room to grow.</h2><p>The Boss exists to equip and empower this generation. We are working to make participation more accessible across backgrounds and economic circumstances, with more ways to put effort to work and build community around their goals.</p><h2>Fundraise <em>Like a Boss.</em></h2><div className={s.actions}><Link href="/fundraising/get-started" className={s.button}>Start a Fundraiser →</Link><Link href="/request-information" className={s.secondary}>Ask About a Family Account</Link></div><p className={s.note}>Platform vision. Features and eligible uses vary by program.</p></div><div className={s.closingPhoto}><Photo crop="445 1803 276 175" alt="A young soccer player looking toward a field at sunset"/></div></section>
</main><ApprovedFooter/></div>}
