import { finiteKeys, isRecord } from "../coordination/input";
import { statUuid } from "../stat-intelligence/input";
import { emptyTournaments, type TournamentBracket, type TournamentData, type TournamentEdition, type TournamentEntry, type TournamentGame, type TournamentMatch, type TournamentQuery, type TournamentSeed, type TournamentStandingSource } from "./contracts";
const text = (v: unknown, max = 200) => typeof v === "string" && v.length <= max ? v : null;
const integer = (v: unknown, min = 0, max = Number.MAX_SAFE_INTEGER) => typeof v === "number" && Number.isSafeInteger(v) && v >= min && v <= max ? v : null;
const nullableUuid = (v: unknown) => v === null ? null : statUuid(v) ? v : undefined;
export function parseTournamentQuery(raw: Record<string, string | string[] | undefined>): TournamentQuery | null { const q: TournamentQuery = {};for (const [key, field] of [["organization_id", "org"], ["edition_id", "edition"], ["bracket_id", "bracket"]] as const) { const v = raw[field];if (v === undefined || v === "") continue;if (!statUuid(v)) return null;q[key] = v; }if (!q.organization_id && !q.edition_id && !q.bracket_id || q.bracket_id && !q.edition_id) return null;return q; }
function edition(v: unknown): TournamentEdition | null { if (!isRecord(v) || !statUuid(v.id) || !text(v.name) || !text(v.sport_key, 40)) return null;return { id: v.id, name: v.name as string, sport_key: v.sport_key as string, ...(text(v.competition_name) ? { competition_name: v.competition_name as string } : {}), ...(statUuid(v.organization_id) ? { organization_id: v.organization_id } : {}), ...(integer(v.bracket_count, 0, 10000) !== null ? { bracket_count: v.bracket_count as number } : {}) }; }
export function projectTournaments(v: unknown): TournamentData | null { if (!isRecord(v) || v.contract !== "tournaments-v1") return null;const out = emptyTournaments();for (const k of ["editions", "brackets", "seeds", "matches", "entries", "games", "standings_sources"] as const) if (v[k] !== undefined && (!Array.isArray(v[k]) || v[k].length > (k === "matches" ? 65 : 100))) return null;if (v.edition !== undefined) { out.edition = edition(v.edition);if (!out.edition) return null; }for (const item of v.editions as unknown[] ?? []) { const x = edition(item);if (!x) return null;out.editions.push(x); }
 for (const x of v.brackets as unknown[] ?? []) { if (!isRecord(x) || !statUuid(x.id) || !text(x.name) || x.bracket_type !== "single_elimination" || ![2,4,8,16,32,64].includes(Number(x.bracket_size)) || typeof x.include_third_place !== "boolean" || !text(x.status, 30) || integer(x.current_revision,0,10000)===null || integer(x.version,1)===null || [x.champion_entry_id,x.runner_up_entry_id,x.third_entry_id,x.fourth_entry_id].some((value)=>nullableUuid(value)===undefined)) return null;out.brackets.push(x as unknown as TournamentBracket); }
 for (const x of v.entries as unknown[] ?? []) { if (!isRecord(x)||!statUuid(x.id)||!statUuid(x.team_id)||!text(x.name)||!text(x.status,30))return null;out.entries.push(x as unknown as TournamentEntry); }
 for (const x of v.seeds as unknown[] ?? []) { if (!isRecord(x)||!statUuid(x.id)||!statUuid(x.entry_id)||!text(x.name)||integer(x.seed,1,64)===null||!(x.source_rank===null||integer(x.source_rank,1)!==null)||!(x.source_generation===null||integer(x.source_generation,0)!==null)||!(x.override_reason===null||text(x.override_reason,500)))return null;out.seeds.push(x as unknown as TournamentSeed); }
 for (const x of v.matches as unknown[] ?? []) { if (!isRecord(x)||!statUuid(x.id)||!statUuid(x.stage_id)||!text(x.stage_name)||!text(x.stage_type,40)||integer(x.round_number,1,10)===null||integer(x.match_number,1,64)===null||!text(x.label)||!text(x.status,40)||!text(x.primary_source_kind,30)||!text(x.opponent_source_kind,30)||nullableUuid(x.primary_entry_id)===undefined||nullableUuid(x.opponent_entry_id)===undefined||nullableUuid(x.game_id)===undefined||nullableUuid(x.event_id)===undefined||!(x.advancement_destination===null||text(x.advancement_destination))||integer(x.version,1)===null)return null;out.matches.push(x as unknown as TournamentMatch); }
 for (const x of v.games as unknown[] ?? []) { if (!isRecord(x)||!statUuid(x.id)||!statUuid(x.event_id)||!statUuid(x.primary_team_id)||!statUuid(x.opponent_team_id)||!text(x.label)||!text(x.start_at,64)||!text(x.status,30))return null;out.games.push(x as unknown as TournamentGame); }
 for (const x of v.standings_sources as unknown[] ?? []) { if (!isRecord(x)||!statUuid(x.id)||!text(x.label)||integer(x.generation,1)===null||integer(x.entry_count,0,100000)===null||!(x.refreshed_at===null||text(x.refreshed_at,64)))return null;out.standings_sources.push(x as unknown as TournamentStandingSource); }
 out.can_manage=v.can_manage===true;out.can_policy_manage=v.can_policy_manage===true;return out; }
const fields = { "bracket.create": ["edition_id","name","bracket_size","include_third_place","rest_policy","minimum_rest_minutes"], "bracket.seed": ["edition_id","bracket_id","expected_version","source_kind","seeds","source_scope_id","reason"], "match.link_game": ["edition_id","match_id","expected_version","game_id"], "result.process": ["edition_id","match_id","expected_version","reason"], "ruling.create": ["edition_id","match_id","expected_version","kind","winner_entry_id","loser_entry_id","reason"], "projection.rebuild": ["edition_id","bracket_id","expected_version"], "bracket.archive": ["edition_id","bracket_id","expected_version"] } as const;
export type TournamentAction=keyof typeof fields;export type TournamentCommand={action:TournamentAction;request_id:string;input:Record<string,unknown>};
export function parseTournamentCommand(v: unknown): TournamentCommand | null { if(!isRecord(v)||!finiteKeys(v,["action","request_id","input"])||typeof v.action!=="string"||!Object.hasOwn(fields,v.action)||!statUuid(v.request_id)||!isRecord(v.input)||!finiteKeys(v.input,fields[v.action as TournamentAction])||JSON.stringify(v).length>24000)return null;const a=v.action as TournamentAction,i=v.input;for(const[k,x]of Object.entries(i)){if(x===null||x===undefined)return null;if(k.endsWith("_id")&&!statUuid(x))return null;}if(!statUuid(i.edition_id))return null;if(a==="bracket.create"){const policy=i.rest_policy??"disabled",minutes=i.minimum_rest_minutes??0;return text(i.name)!==null&&[2,4,8,16,32,64].includes(Number(i.bracket_size))&&(i.include_third_place===undefined||typeof i.include_third_place==="boolean")&&["disabled","warn","block"].includes(String(policy))&&integer(minutes,0,1440)!==null&&((policy==="disabled")===(minutes===0))?{action:a,request_id:v.request_id,input:i}:null;}if(integer(i.expected_version,1)===null)return null;if(a==="bracket.seed"){if(!statUuid(i.bracket_id)||!["manual","standings_snapshot","group_finish_snapshot"].includes(String(i.source_kind))||!text(i.reason,500))return null;if(i.source_kind==="standings_snapshot")return statUuid(i.source_scope_id)?{action:a,request_id:v.request_id,input:i}:null;if(!Array.isArray(i.seeds)||i.seeds.length<2||i.seeds.length>64||!i.seeds.every(s=>isRecord(s)&&finiteKeys(s,["seed","entry_id","override_reason","source_scope_id","source_rank"])&&integer(s.seed,1,64)!==null&&statUuid(s.entry_id)&&(s.override_reason===undefined||text(s.override_reason,500))&&(i.source_kind!=="group_finish_snapshot"||(statUuid(s.source_scope_id)&&integer(s.source_rank,1,64)!==null))))return null;}return{action:a,request_id:v.request_id,input:i}; }
