"use client";
import Link from "next/link";
import { SoccerPanel } from "../soccer/console";
import { BasketballPanel } from "../basketball/console";
import { GameIntentProvider } from "./intent-provider";
import { useState } from "react";
import type { Choice } from "@/lib/coordination/input";
import type { Game, GameCommand, GameData, GameQuery } from "@/lib/games/contracts";
import { gameFeatureKeys, gameStatuses } from "@/lib/games/contracts";
import { addDays } from "@/lib/calendar/temporal";
import { displayInstant, humanize, coordinationHref } from "../coordination/presentation";
import { fieldText, fieldInteger } from "../coordination/action-form";
import { GameForm } from "./action-form";
import { GameCard, GameScore, calendarGameHref, currentCalendarKey, gameHref } from "./presentation";

function Filter({ name, label, rows, value }: { name: string; label: string; rows: Choice[]; value?: string }) { return rows.length ? <label className="form-field"><span>{label}</span><select name={name} defaultValue={value ?? ""}><option value="">{name === "org" ? "Default organization" : `All available ${label.toLowerCase()}`}</option>{rows.map(row => <option key={row.id} value={row.id}>{row.label}</option>)}</select></label> : null; }
function GameFilters({ data, query }: { data: GameData; query: GameQuery }) {
  return <details className="game-filter-panel"><summary>Filter games</summary><form method="get" action="/app/games" className="game-filters"><input type="hidden" name="view" value={query.view} />{query.child_person_id && <input type="hidden" name="child" value={query.child_person_id} />}<Filter name="org" label="Organizations" rows={data.organizations} value={query.organization_id} /><Filter name="team" label="Teams" rows={data.teams} value={query.team_id} /><Filter name="unit" label="Programs" rows={data.units} value={query.unit_id} /><Filter name="season" label="Seasons" rows={data.seasons} value={query.season_id} /><label className="form-field"><span>Status</span><select name="status" defaultValue={query.status ?? ""}><option value="">All statuses</option>{gameStatuses.map(status => <option key={status} value={status}>{humanize(status)}</option>)}</select></label><label className="form-field"><span>From date (UTC)</span><input name="from" type="date" defaultValue={query.from.slice(0, 10)} required /></label><label className="form-field"><span>Through date (UTC)</span><input name="to" type="date" defaultValue={addDays(query.to.slice(0, 10), -1)} required /></label><div className="game-filter-actions"><button type="submit" className="button button-outline button-small">Apply filters</button><Link href="/app/games" className="button button-outline button-small">Reset</Link></div></form></details>;
}
function GameCreate({ data }: { data: GameData }) {
  const [selection, setSelection] = useState(""), event = data.create_candidates.find(candidate => `${candidate.event_id}:${candidate.occurrence_key}` === selection);
  return <details className="game-management-panel"><summary>Open a Calendar game in Game Center</summary><p>Choose a competitive Calendar occurrence and its sport. Calendar keeps the schedule and opponent.</p><GameForm label="Create game" build={form => { const candidate = data.create_candidates.find(row => `${row.event_id}:${row.occurrence_key}` === fieldText(form, "event")); return candidate ? { operation: "game.create", input: { event_id: candidate.event_id, expected_event_version: candidate.event_version, occurrence_key: candidate.occurrence_key, primary_team_id: fieldText(form, "primary_team_id"), sport_key: fieldText(form, "sport_key"), competition_type: fieldText(form, "competition_type") } } : null; }}><div className="game-form-grid"><label className="form-field"><span>Calendar game</span><select name="event" required value={selection} onChange={e => setSelection(e.target.value)}><option value="">Choose a scheduled game</option>{data.create_candidates.map(row => <option key={`${row.event_id}:${row.occurrence_key}`} value={`${row.event_id}:${row.occurrence_key}`}>{row.title} · {displayInstant(row.start_at)}</option>)}</select></label><label className="form-field"><span>Primary team</span><select key={selection} name="primary_team_id" required><option value="">Choose team</option>{event?.teams.map(team => <option key={team.id} value={team.id}>{team.label}</option>)}</select></label><label className="form-field"><span>Sport</span><select name="sport_key" required defaultValue=""><option value="">Choose sport</option>{data.sports.map(sport => <option key={sport.key} value={sport.key}>{sport.label}</option>)}</select></label><label className="form-field"><span>Competition</span><select name="competition_type" defaultValue="standard"><option value="standard">Standard game</option><option value="tournament">Tournament game</option></select></label></div>{event && <p className="game-helper">{event.opponent_label} · {humanize(event.home_away)}</p>}</GameForm></details>;
}
function GameSettings({ data }: { data: GameData }) {
  if (!data.capabilities.configure || !data.organization_id) return null;
  if (!data.configuration_version) return <p className="game-notice">Activate Sports in <Link href={`/app/organizations?org=${data.organization_id}`}>organization settings</Link> before configuring Game Center.</p>;
  const labels: Record<typeof gameFeatureKeys[number], string> = { game_center: "Game Center", game_operations: "Protected game operations", public_game_center: "Explicitly published game summaries", team_game_management: "Team administrator game management", head_coach_game_management: "Head coach game management", basketball_live_scoring: "Basketball live scoring", basketball_stats: "Basketball game statistics", basketball_play_by_play: "Basketball play by play", basketball_lineups: "Basketball lineups", soccer_live_scoring: "Soccer live scoring", soccer_stats: "Soccer match statistics", soccer_play_by_play: "Soccer play by play", soccer_lineups: "Soccer lineups and keepers" };
  return <details className="game-management-panel"><summary>Game Center settings</summary><p>These capabilities belong to Sports. Operator assignments and current resource permissions still govern each action.</p><GameForm key={`${data.organization_id}:${data.configuration_version}`} label="Save Game Center settings" build={form => ({ operation: "games.configure", input: { organization_id: data.organization_id!, expected_version: data.configuration_version, configuration: Object.fromEntries(gameFeatureKeys.map(key => [key, form.get(key) === "on"])) } })}><div className="game-form-grid">{gameFeatureKeys.map(key => <label className="game-confirmation" key={key}><input type="checkbox" name={key} defaultChecked={data.features[key] === true} /><span>{labels[key]}</span></label>)}</div></GameForm></details>;
}
export const allowedTransitions = (status: Game["status"], resume: boolean) => ({ scheduled: ["pregame", "delayed"], pregame: ["delayed"], live: ["paused", "delayed", "suspended", "abandoned"], paused: [...(resume ? ["live"] : []), "delayed", "suspended", "abandoned"], delayed: [resume ? "live" : "pregame", "abandoned"], suspended: [...(resume ? ["live"] : []), "paused", "abandoned"], final: [], canceled: [], postponed: [], abandoned: [] } as Record<Game["status"], string[]>)[status];
function GameActions({ game, data }: { game: Game; data: GameData }) {
  const input = { game_id: game.id, expected_version: game.version }, caps = game.capabilities;
  const build = (operation: GameCommand["operation"], fields: Record<string, string | number> = {}): GameCommand => ({ operation, input: { ...input, ...fields } });
  const active = !["final", "canceled", "postponed", "abandoned"].includes(game.status), operations = data.features.game_operations === true;
  const scoreBoundary = game.history.filter(row => ["game.score.set", "game.score.reverse", "game.finalize", "game.reopen"].includes(row.operation)).reduce<Game["history"][number] | undefined>((latest, row) => !latest || row.sequence > latest.sequence ? row : latest, undefined);
  const reversibleScore = scoreBoundary?.operation === "game.score.set" ? scoreBoundary : undefined;
  if (!operations && !caps.manage && !caps.publish) return null;
  return <section className="game-operations" aria-label="Game controls"><h3>Game controls</h3><div className="game-action-grid">
    {caps.roster_snapshot && <div className="game-action-panel"><h4>Game roster</h4><p>Preserve current eligible athletes and availability as a game-time snapshot.</p><GameForm label={game.roster_revision ? "Refresh roster snapshot" : "Snapshot game roster"} build={() => build("game.roster.snapshot")} /></div>}
    {operations && caps.start && ["scheduled", "pregame", "delayed"].includes(game.status) && <div className="game-action-panel"><h4>Ready to play</h4><GameForm label="Start Game" confirmation="I have reviewed the matchup and roster snapshot." build={() => build("game.start")} /></div>}
    {operations && caps.operate && active && allowedTransitions(game.status, caps.resume).length > 0 && <div className="game-action-panel"><h4>Game status</h4><GameForm label="Update game status" build={form => build("game.transition", { status: fieldText(form, "status") })}><label className="form-field"><span>Next status</span><select name="status" required>{allowedTransitions(game.status, caps.resume).map(status => <option key={status} value={status}>{humanize(status)}</option>)}</select></label></GameForm></div>}
    {!game.engine_locked && operations && caps.operate && ["live", "paused", "suspended"].includes(game.status) && <div className="game-action-panel"><h4>Score summary</h4><p>Each update is recorded in game history.</p><GameForm label="Record score summary" build={form => ({ operation: "game.score.set", input: { ...input, primary_score: fieldInteger(form, "primary_score"), opponent_score: fieldInteger(form, "opponent_score") } })}><div className="game-form-grid"><label className="form-field"><span>{game.primary.label} score</span><input name="primary_score" type="number" min={0} max={1000000} step={1} defaultValue={game.primary.score} required /></label><label className="form-field"><span>{game.opponent.label} score</span><input name="opponent_score" type="number" min={0} max={1000000} step={1} defaultValue={game.opponent.score} required /></label></div></GameForm></div>}
    {!game.engine_locked && operations && caps.correct && ["live", "paused", "suspended"].includes(game.status) && reversibleScore && <div className="game-action-panel"><h4>Reverse a score summary</h4><p>The most recent eligible score update can be reversed while retaining its history.</p><GameForm label="Reverse score summary" confirmation="I have reviewed the score update to reverse." build={form => build("game.score.reverse", { operation_id: fieldText(form, "operation_id") })}><label className="form-field"><span>Recorded score update</span><select name="operation_id" required><option value={reversibleScore.id}>#{reversibleScore.sequence} · {reversibleScore.summary}</option></select></label></GameForm></div>}
    {operations && caps.finalize && ["live", "paused", "suspended"].includes(game.status) && <div className="game-action-panel"><h4>Final result</h4><p>{game.primary.label} {game.primary.score} · {game.opponent.label} {game.opponent.score}</p><GameForm label="Finalize game" confirmation="I confirm this final score and understand ordinary operations will close." build={() => build("game.finalize")} /></div>}
    {operations && caps.correct && game.status === "final" && <div className="game-action-panel"><h4>Correct a final game</h4><GameForm label="Reopen for correction" confirmation="I understand the previous final result will remain in history." build={form => build("game.reopen", { reason: fieldText(form, "reason") })}><label className="form-field"><span>Reason for reopening</span><textarea name="reason" required maxLength={500} rows={3} /></label></GameForm></div>}
    {caps.publish && data.features.public_game_center === true && <div className="game-action-panel"><h4>Safe result publication</h4><GameForm label="Publish game summary" confirmation="I have reviewed Calendar publication and the safe matchup and score summary." build={() => build("game.publish")} /></div>}
  </div></section>;
}
function OperatorManager({ game, data }: { game: Game; data: GameData }) {
  const [selection, setSelection] = useState(""), candidate = data.operator_candidates.find(row => `${row.role_assignment_id}:${row.team_id}` === selection);
  if (!game.capabilities.manage || data.features.game_operations !== true) return null;
  return <details className="game-management-panel"><summary>Game operator assignments</summary><p>Assignments apply to this game and remain subject to current role and relationship checks.</p>{game.operators.length ? <ul className="game-operator-list">{game.operators.map(operator => <li key={operator.id}><div><strong>{operator.display_name}</strong><span>{humanize(operator.function_key)} · {humanize(operator.status)}{operator.ends_at ? ` · Until ${displayInstant(operator.ends_at, game.timezone)}` : ""}</span></div>{operator.status === "active" && <GameForm label={`End assignment for ${operator.display_name}`} build={() => ({ operation: "game.operator.end", input: { game_id: game.id, expected_version: game.version, assignment_id: operator.id } })} />}</li>)}</ul> : <p className="empty-state">No operators assigned to this game.</p>}
    {data.operator_candidates.length > 0 && <GameForm label="Assign game operator" build={form => { const selected = data.operator_candidates.find(row => `${row.role_assignment_id}:${row.team_id}` === fieldText(form, "candidate")), until = fieldText(form, "ends_at"); const date = new Date(until); return selected && Number.isFinite(date.getTime()) ? { operation: "game.operator.assign", input: { game_id: game.id, expected_version: game.version, person_id: selected.person_id, role_assignment_id: selected.role_assignment_id, team_id: selected.team_id, function_key: fieldText(form, "function_key"), ends_at: date.toISOString() } } : null; }}><div className="game-form-grid"><label className="form-field"><span>Eligible operator</span><select name="candidate" required value={selection} onChange={event => setSelection(event.target.value)}><option value="">Choose an operator</option>{data.operator_candidates.map(row => <option key={`${row.role_assignment_id}:${row.team_id}`} value={`${row.role_assignment_id}:${row.team_id}`}>{row.display_name}{row.team_id ? ` · ${data.teams.find(team => team.id === row.team_id)?.label ?? "Participating team"}` : " · Game administrator"}</option>)}</select></label><label className="form-field"><span>Function</span><select name="function_key" key={selection} required><option value="">Choose function</option>{candidate?.functions.map(f => <option value={f} key={f}>{humanize(f)}</option>)}</select></label><label className="form-field"><span>Assignment ends (your device timezone)</span><input name="ends_at" type="datetime-local" step={1} required /></label></div></GameForm>}
  </details>;
}
export function GameDetail({ game, data, query }: { game: Game; data: GameData; query: GameQuery }) {
  const family = query.view === "family";
  return <article className="game-detail"><div className="game-detail-heading"><div><p className="eyebrow">{game.sport_label} · {humanize(game.competition_type)}</p><h2>{game.title}</h2></div><span className={`game-status game-status-${game.status}`}>{humanize(game.status)}</span></div><GameScore game={game} /><dl className="game-facts"><div><dt>When</dt><dd>{displayInstant(game.start_at, game.timezone)} ({game.timezone})</dd></div><div><dt>Venue</dt><dd>{game.venue_label ?? "Venue to be confirmed"}</dd></div><div><dt>Calendar status</dt><dd>{humanize(game.event_status)}</dd></div><div><dt>Roster</dt><dd>{game.roster_revision ? `Snapshot ${game.roster_revision}` : "Awaiting snapshot"}</dd></div>{game.status === "final" && <div><dt>Result</dt><dd>{game.primary.final_score === game.opponent.final_score ? "Tie" : `${(game.primary.final_score ?? 0) > (game.opponent.final_score ?? 0) ? game.primary.label : game.opponent.label} wins`}</dd></div>}</dl><div className="game-related-links"><Link className="button button-outline button-small" href={calendarGameHref(game)}>Calendar event</Link><Link className="button button-outline button-small" href={coordinationHref("attendance", { view: family ? "family" : "staff", child_person_id: family ? query.child_person_id : undefined, organization_id: game.organization_id, event_id: game.event_id, occurrence_key: currentCalendarKey(game) })}>Attendance and RSVP</Link><Link className="button button-outline button-small" href={gameHref({ ...query, game_id: undefined })}>All games</Link></div>
    <BasketballPanel key={game.id} game={game} family={family} />
    <SoccerPanel key={game.id} game={game} family={family} />
    {game.reopened && <p className="game-attention">This game was reopened for correction. Previous final results remain preserved.</p>}
    {game.capabilities.view_roster && <section className="game-roster-section" aria-label="Game roster"><h3>{family ? "Your family game roster" : "Game roster"}</h3><p className="game-helper">Availability and check-in come from Attendance. Only the roster entries you may view appear here.</p>{game.roster.length ? <div className="game-roster-list">{game.roster.map(athlete => <article className="game-roster-row" key={athlete.id}><span className="game-jersey">{athlete.jersey_number || "--"}</span><div><h4>{athlete.display_name}</h4><p>{[athlete.position_label, athlete.captain ? "Captain" : null, athlete.starter ? "Starter" : null].filter(Boolean).join(" · ") || "Athlete"}</p></div><div className="game-roster-state"><span>{athlete.active ? "Active" : "Inactive"}</span><small>{humanize(athlete.availability)}{athlete.checkin_state ? ` · ${humanize(athlete.checkin_state)}` : ""}</small></div></article>)}</div> : <p className="empty-state">No visible roster entries in this snapshot.</p>}</section>}
    {!family && <><GameActions key={`${game.id}:${game.version}`} game={game} data={data} /><OperatorManager key={`operators:${game.id}:${game.version}`} game={game} data={data} /></>}
    {!family && game.history.length > 0 && <details className="game-history-panel"><summary>Game history</summary><ol className="game-history">{game.history.map(row => <li key={row.id}><span className="game-history-sequence">{row.sequence}</span><div><strong>{row.summary}</strong><p>{humanize(row.operation.replace("game.", "").replaceAll(".", " "))}{row.correction_of ? " · Audited reversal" : ""}</p><time dateTime={row.created_at}>{displayInstant(row.created_at, game.timezone)}</time></div></li>)}</ol></details>}
    {!family && game.finalizations.length > 0 && <details className="game-history-panel"><summary>Sealed final results</summary><ul className="game-final-results">{game.finalizations.map(final => <li key={final.id}><strong>Final {final.epoch}: {game.primary.label} {final.primary_score} · {game.opponent.label} {final.opponent_score}</strong><span>Roster {final.roster_revision} · {displayInstant(final.created_at, game.timezone)}</span></li>)}</ul></details>}
  </article>;
}
export function GameConsole({ data, query }: { data: GameData; query: GameQuery }) {
  const detail = query.game_id ? data.games.find(game => game.id === query.game_id) : undefined, enabled = data.features.game_center === true;
  const live = data.games.filter(game => ["live", "paused", "suspended"].includes(game.status)), upcoming = data.games.filter(game => ["scheduled", "pregame", "delayed", "postponed"].includes(game.status)), completed = data.games.filter(game => ["final", "canceled", "abandoned"].includes(game.status));
  const content = data.unavailable ? <p role="alert" className="game-notice">Game Center is temporarily unavailable. Please try again.</p> : data.restricted ? <p role="status" className="game-notice">Games are restricted in this context.</p> : !enabled ? <p className="game-notice">Game Center is not enabled for this organization.</p> : query.game_id && !detail ? <p role="status" className="game-notice">This game is unavailable in your current context.</p> : detail ? <GameDetail game={detail} data={data} query={query} /> : <>
      <div className="game-overview" aria-label="Games in this range"><div><strong>{live.length}</strong><span>In play</span></div><div><strong>{upcoming.length}</strong><span>Upcoming</span></div><div><strong>{completed.filter(game => game.status === "final").length}</strong><span>Final</span></div></div>
      {[["In play", live], ["Upcoming games", upcoming], ["Recent results", completed]].map(([label, rows]) => (rows as Game[]).length ? <section className="game-list-section" key={label as string}><h2>{label as string}</h2><div className="game-cards">{(rows as Game[]).map(game => <GameCard key={game.id} game={game} query={query} />)}</div></section> : null)}
      {!data.games.length && <p className="empty-state">No games match your current context and date range.</p>}{data.more && <p className="game-notice">More games are available. Narrow the organization, team or date filters.</p>}
      {query.view !== "family" && data.capabilities.create && <GameCreate data={data} />}
    </>;
  return <div className="game-console"><header className="game-heading"><div><p className="eyebrow">Boss Sports</p><h1>Game Center</h1><p>{query.view === "family" ? "Your family’s matchups, schedules and results." : "One game. One schedule. Every moment accounted for."}</p></div><Link href={gameHref({ ...query, game_id: undefined, view: query.view === "family" ? "all" : "family" })} className="button button-outline button-small">{query.view === "family" ? "All available games" : "Family games"}</Link></header><GameFilters data={data} query={query} />
    <GameSettings data={data} />{query.game_id ? <GameIntentProvider key={query.game_id} version={detail?.version ?? 0}>{content}</GameIntentProvider> : content}
  </div>;
}
