create function boss_private.tournament_read(q jsonb default'{}')returns jsonb language plpgsql volatile security definer set search_path=''as $$
declare actor uuid;ed uuid;bracket uuid;org uuid;e public.competition_editions;b public.tournament_brackets;current_revision_id uuid;editions jsonb:='[]';brackets jsonb:='[]';seeds jsonb:='[]';matches jsonb:='[]';entries jsonb:='[]';games jsonb:='[]';standings_sources jsonb:='[]';begin
 perform boss_private.games_require_live_auth();actor:=boss_private.current_person_id();perform boss_private.tournament_input(q,array['view','organization_id','edition_id','bracket_id']);
 if q->>'view'='navigation'then return jsonb_build_object('contract','tournaments-v1','navigation_available',exists(select 1 from public.tournament_brackets tb where tb.status<>'archived'and boss_private.ranking_can_edition(actor,'competition.view',tb.edition_id))or exists(select 1 from public.competition_editions ce where boss_private.ranking_can_edition(actor,'competition.manage',ce.id)));end if;
 org:=boss_private.tournament_uuid(q,'organization_id');ed:=boss_private.tournament_uuid(q,'edition_id');bracket:=boss_private.tournament_uuid(q,'bracket_id');if bracket is not null then select *into b from public.tournament_brackets where id=bracket;if not found then raise exception'Access denied'using errcode='PT403';end if;ed:=b.edition_id;end if;
 if ed is null then if org is null then raise exception'Invalid tournament query'using errcode='PT422';end if;
  select coalesce(jsonb_agg(jsonb_build_object('id',ce.id,'name',ce.name,'competition_name',c.name,'sport_key',ce.sport_key,'bracket_count',(select count(*)from public.tournament_brackets tb where tb.edition_id=ce.id and tb.status<>'archived'))order by c.name,ce.name,ce.id),'[]')into editions from public.competition_editions ce join public.competitions c on c.id=ce.competition_id where ce.organization_id=org and ce.status='active'and boss_private.ranking_can_edition(actor,'competition.view',ce.id);
	  return jsonb_build_object('contract','tournaments-v1','editions',editions,'brackets','[]'::jsonb,'seeds','[]'::jsonb,'matches','[]'::jsonb,'entries','[]'::jsonb,'games','[]'::jsonb,'standings_sources','[]'::jsonb,'can_manage',false,'can_policy_manage',false);
 end if;
 select *into e from public.competition_editions where id=ed;if not found or(org is not null and org<>e.organization_id)then raise exception'Access denied'using errcode='PT403';end if;perform boss_private.tournament_authorize(actor,'competition.view',ed);
	 select coalesce(jsonb_agg(jsonb_build_object('id',tb.id,'name',tb.name,'bracket_type',tb.bracket_type,'bracket_size',tb.bracket_size,'include_third_place',tb.include_third_place,'status',tb.status,'current_revision',tb.current_revision,'champion_entry_id',tb.champion_entry_id,'runner_up_entry_id',(select a.loser_entry_id from public.tournament_advancements a join public.tournament_matches tm on tm.id=a.source_match_id join public.tournament_stages s on s.id=tm.stage_id where a.bracket_id=tb.id and s.stage_type='championship'order by a.generation desc,a.id desc limit 1),'third_entry_id',(select a.winner_entry_id from public.tournament_advancements a join public.tournament_matches tm on tm.id=a.source_match_id join public.tournament_stages s on s.id=tm.stage_id where a.bracket_id=tb.id and s.stage_type='third_place'order by a.generation desc,a.id desc limit 1),'fourth_entry_id',(select a.loser_entry_id from public.tournament_advancements a join public.tournament_matches tm on tm.id=a.source_match_id join public.tournament_stages s on s.id=tm.stage_id where a.bracket_id=tb.id and s.stage_type='third_place'order by a.generation desc,a.id desc limit 1),'version',tb.version)order by tb.created_at,tb.id),'[]')into brackets from public.tournament_brackets tb where tb.edition_id=ed and tb.status<>'archived'and(bracket is null or tb.id=bracket);
 select coalesce(jsonb_agg(jsonb_build_object('id',ce.id,'team_id',ce.team_id,'name',t.name,'status',ce.status)order by t.name,ce.id),'[]')into entries from public.competition_entries ce join public.teams t on t.id=ce.team_id where ce.edition_id=ed and ce.status='active';
 if bracket is not null then
  select br.id into current_revision_id from public.tournament_bracket_revisions br where br.bracket_id=bracket order by br.revision desc limit 1;
  select coalesce(jsonb_agg(jsonb_build_object('id',ts.id,'seed',ts.seed,'entry_id',ts.entry_id,'name',t.name,'source_rank',ts.source_rank,'source_generation',ts.source_generation,'override_reason',ts.override_reason)order by ts.seed),'[]')into seeds from public.tournament_seeds ts join public.competition_entries ce on ce.id=ts.entry_id join public.teams t on t.id=ce.team_id where ts.revision_id=current_revision_id;
  select coalesce(jsonb_agg(jsonb_build_object('id',tm.id,'stage_id',tm.stage_id,'stage_name',s.name,'stage_type',s.stage_type,'round_number',tm.round_number,'match_number',tm.match_number,'label',tm.label,'status',tm.status,'primary_source_kind',tm.primary_source_kind,'opponent_source_kind',tm.opponent_source_kind,'primary_entry_id',tm.primary_entry_id,'primary_name',pt.name,'opponent_entry_id',tm.opponent_entry_id,'opponent_name',ot.name,'game_id',tm.game_id,'event_id',g.event_id,'start_at',g.scheduled_start_at,'venue_label',v.name,'game_status',g.status,'primary_score',case when g.status='final'then g.final_primary_score else g.primary_score end,'opponent_score',case when g.status='final'then g.final_opponent_score else g.opponent_score end,'winner_side',g.winner_side,'finalization_count',tm.finalization_count,'advancement_destination',(select d.label from public.tournament_matches d where d.bracket_id=tm.bracket_id and d.revision_id=tm.revision_id and(d.primary_source_match_id=tm.id or d.opponent_source_match_id=tm.id)and d.label<>'Third place'order by d.round_number,d.match_number limit 1),'version',tm.version)order by tm.round_number,tm.match_number,tm.id),'[]')into matches
  from public.tournament_matches tm join public.tournament_stages s on s.id=tm.stage_id left join public.competition_entries pe on pe.id=tm.primary_entry_id left join public.teams pt on pt.id=pe.team_id left join public.competition_entries oe on oe.id=tm.opponent_entry_id left join public.teams ot on ot.id=oe.team_id left join public.games g on g.id=tm.game_id left join public.venues v on v.id=g.venue_id where tm.bracket_id=bracket and tm.revision_id=current_revision_id;
	  if boss_private.ranking_can_edition(actor,'competition.manage',ed)then select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'event_id',g.event_id,'label',coalesce(pt.name,'Team')||' vs '||coalesce(ot.name,g.external_opponent_name,'Opponent'),'primary_team_id',g.primary_team_id,'opponent_team_id',g.opponent_team_id,'start_at',g.scheduled_start_at,'status',g.status)order by g.scheduled_start_at,g.id),'[]')into games from public.games g left join public.teams pt on pt.id=g.primary_team_id left join public.teams ot on ot.id=g.opponent_team_id where g.sport_key=e.sport_key and g.status in('scheduled','pregame')and g.id not in(select game_id from public.tournament_matches where game_id is not null)and exists(select 1 from public.competition_entries ce where ce.edition_id=ed and ce.team_id=g.primary_team_id)and exists(select 1 from public.competition_entries ce where ce.edition_id=ed and ce.team_id=g.opponent_team_id)limit 100;select coalesce(jsonb_agg(jsonb_build_object('id',rs.id,'label',coalesce(cg.name,'Overall standings'),'generation',rs.published_generation,'refreshed_at',rs.refreshed_at,'entry_count',(select count(*)from public.standings_rows sr where sr.scope_id=rs.id))order by cg.name nulls first,rs.id),'[]')into standings_sources from public.ranking_scopes rs left join public.competition_groups cg on cg.id=rs.group_id where rs.edition_id=ed and rs.product='standings'and rs.state='current'and rs.published_generation>0;end if;
 end if;
	 return jsonb_build_object('contract','tournaments-v1','edition',jsonb_build_object('id',e.id,'name',e.name,'sport_key',e.sport_key,'organization_id',e.organization_id),'editions','[]'::jsonb,'brackets',brackets,'seeds',seeds,'matches',matches,'entries',entries,'games',games,'standings_sources',standings_sources,'can_manage',boss_private.ranking_can_edition(actor,'competition.manage',ed),'can_policy_manage',boss_private.ranking_can_edition(actor,'competition.policy_manage',ed));
exception when invalid_text_representation then raise exception'Invalid tournament query'using errcode='PT422';end$$;
create function public.boss_tournament_read(p_query jsonb default'{}')returns jsonb language sql volatile security invoker set search_path=''as $$select boss_private.tournament_read(p_query)$$;
revoke all on function boss_private.tournament_read(jsonb),public.boss_tournament_read(jsonb)from public,anon,authenticated,service_role;grant execute on function boss_private.tournament_read(jsonb),public.boss_tournament_read(jsonb)to authenticated;

-- Low-volume tournament outcomes reuse the existing notification engine.
-- Calendar and Game Center remain the notification sources for schedule and
-- game lifecycle changes; this hook only adds advancement-level outcomes.
alter table public.notification_events drop constraint notification_events_source_type_check;
alter table public.notification_events add constraint notification_events_source_type_check check(source_type in('event','registration','registration_document','charge','payment','message','attendance_request','volunteer_shift','volunteer_assignment','volunteer_event','game_operation','tournament_advancement'));
insert into boss_private.notification_types(key,category,source_module,title,body)values
 ('tournament.advanced','events','sports','Tournament advancement','Your tournament bracket has a new official advancement.'),
 ('tournament.champion','events','sports','Tournament champion','A tournament championship result is official.'),
 ('tournament.advancement_corrected','events','sports','Tournament advancement corrected','An authorized tournament advancement was reconciled to a corrected official result.');

create function boss_private.tournament_notification_visible(p_event public.notification_events,p_person uuid)returns boolean language sql stable security definer set search_path=''as $$
 select p_event.source_type='tournament_advancement'and p_event.source_module='sports'and boss_private.notification_person_active(p_person)
 and exists(select 1 from public.tournament_advancements a where a.id=p_event.source_id and a.edition_id in(select ce.id from public.competition_editions ce where ce.organization_id=p_event.organization_id)and boss_private.ranking_can_edition(p_person,'competition.view',a.edition_id))
$$;
alter function boss_private.notification_source_visible(public.notification_events,uuid)rename to notification_source_visible_phase5a;
create function boss_private.notification_source_visible(p_event public.notification_events,p_person uuid)returns boolean language sql stable security definer set search_path=''as $$
 select case when p_event.source_type='tournament_advancement'then boss_private.tournament_notification_visible(p_event,p_person)else boss_private.notification_source_visible_phase5a(p_event,p_person)end
$$;

alter function boss_private.notification_candidates(public.notification_events,uuid,integer)rename to notification_candidates_phase5a;
create function boss_private.notification_candidates(p_event public.notification_events,p_after uuid,p_limit integer)returns table(person_id uuid)language plpgsql stable security definer set search_path=''as $$
declare a public.tournament_advancements;begin
 if p_event.source_type<>'tournament_advancement'then return query select c.person_id from boss_private.notification_candidates_phase5a(p_event,p_after,p_limit)c;return;end if;
 select *into a from public.tournament_advancements where id=p_event.source_id;if not found then return;end if;
 return query select candidate.person_id from(
  select distinct tm.person_id from public.team_memberships tm join public.competition_entries ce on ce.team_id=tm.team_id and ce.id in(a.winner_entry_id,a.loser_entry_id)where tm.status='active'and tm.starts_at<=p_event.occurred_at and(tm.ends_at is null or tm.ends_at>now())and(p_after is null or tm.person_id>p_after)
  union select distinct gr.guardian_person_id from public.guardian_relationships gr join public.team_memberships tm on tm.person_id=gr.dependent_person_id join public.competition_entries ce on ce.team_id=tm.team_id and ce.id in(a.winner_entry_id,a.loser_entry_id)where gr.authority_status='active'and gr.starts_at<=p_event.occurred_at and(gr.ends_at is null or gr.ends_at>now())and tm.status='active'and tm.starts_at<=p_event.occurred_at and(tm.ends_at is null or tm.ends_at>now())and(p_after is null or gr.guardian_person_id>p_after)
  union select distinct ca.person_id from public.competition_access_assignments ca where ca.edition_id=a.edition_id and ca.status='active'and ca.starts_at<=p_event.occurred_at and(ca.ends_at is null or ca.ends_at>now())and(p_after is null or ca.person_id>p_after)
 )candidate order by candidate.person_id limit greatest(1,least(p_limit,100));
end$$;

alter function boss_private.notification_contexts(public.notification_events,uuid)rename to notification_contexts_phase5a;
create function boss_private.notification_contexts(p_event public.notification_events,p_person uuid)returns jsonb language plpgsql stable security definer set search_path=''as $$
declare a public.tournament_advancements;begin
 if p_event.source_type<>'tournament_advancement'then return boss_private.notification_contexts_phase5a(p_event,p_person);end if;
 if not boss_private.tournament_notification_visible(p_event,p_person)then return'[]';end if;select *into a from public.tournament_advancements where id=p_event.source_id;
 return jsonb_build_array(jsonb_build_object('source_type','tournament_advancement','source_id',a.id),jsonb_build_object('edition_id',a.edition_id,'bracket_id',a.bracket_id));
end$$;

alter function boss_private.notification_destination(public.notification_events)rename to notification_destination_phase5a;
create function boss_private.notification_destination(p_event public.notification_events)returns text language plpgsql stable security definer set search_path=''as $$
declare a public.tournament_advancements;begin if p_event.source_type<>'tournament_advancement'then return boss_private.notification_destination_phase5a(p_event);end if;select *into a from public.tournament_advancements where id=p_event.source_id;if not found then return null;end if;return'/app/tournaments?edition='||a.edition_id||'&bracket='||a.bracket_id;end$$;

create function boss_private.tournament_notification_ingest()returns trigger language plpgsql security definer set search_path=''as $$
declare org uuid;typ text;begin select ce.organization_id into org from public.competition_editions ce where ce.id=new.edition_id;select case when s.stage_type='championship'then'tournament.champion'when new.generation>1 then'tournament.advancement_corrected'else'tournament.advanced'end into typ from public.tournament_matches m join public.tournament_stages s on s.id=m.stage_id where m.id=new.source_match_id;perform boss_private.notification_enqueue('sports','tournament_advancement',new.id,org,typ,new.generation::text,jsonb_build_object('team_id',(select team_id from public.competition_entries where id=new.winner_entry_id),'source_version',new.generation));return new;end$$;
create trigger tournament_notification_source after insert on public.tournament_advancements for each row execute function boss_private.tournament_notification_ingest();

revoke all on function boss_private.tournament_notification_visible(public.notification_events,uuid),boss_private.notification_source_visible_phase5a(public.notification_events,uuid),boss_private.notification_source_visible(public.notification_events,uuid),boss_private.notification_candidates_phase5a(public.notification_events,uuid,integer),boss_private.notification_candidates(public.notification_events,uuid,integer),boss_private.notification_contexts_phase5a(public.notification_events,uuid),boss_private.notification_contexts(public.notification_events,uuid),boss_private.notification_destination_phase5a(public.notification_events),boss_private.notification_destination(public.notification_events),boss_private.tournament_notification_ingest()from public,anon,authenticated,service_role;
