-- Extend finite shared configuration and tracking catalogs without rewriting prior engines.
create or replace function boss_private.tracking_selection(sport text,preset text,selected jsonb default'[]',quick jsonb default null)returns jsonb
language plpgsql stable security definer set search_path=''as $$
declare enabled text[];seed text[];ordered text[];k text;deps text[];d public.game_stat_catalog_items;changed boolean;begin
 if sport not in('basketball','soccer','football','volleyball','baseball','softball')or sport is null or preset is null or preset not in('score_only','essential','standard','advanced','full','custom')or jsonb_typeof(selected)is distinct from'array'or jsonb_array_length(selected)>128 then raise exception 'Invalid tracking selection'using errcode='PT422';end if;
 if preset<>'custom'and jsonb_array_length(selected)>0 then raise exception 'Preset contains custom selections'using errcode='PT422';end if;
 if preset='custom'then select coalesce(array_agg(value),'{}')into seed from jsonb_array_elements_text(selected);
 elsif preset='score_only'then seed:='{}';
 elsif preset='essential'then seed:=case sport
 when'basketball'then array['player_attribution','assists','offensive_rebounds','defensive_rebounds']
 when'soccer'then array['player_attribution','assists','shots','saves']
 when'football'then array['player_attribution','quick_rush','quick_pass_complete','quick_pass_incomplete']
 when'baseball'then array['player_attribution','baserunning'] when'softball'then array['player_attribution','baserunning'] else array['player_attribution','kills','assists','digs','service_aces','service_errors','solo_blocks','block_assists']end;
 else select array_agg(key order by(definition->>'order')::integer)into seed from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and definition->>'classification'='optional'and(definition->>'available')::boolean;end if;
 if(select count(distinct v)from unnest(seed)v)<>cardinality(seed)then raise exception 'Duplicate tracking selection'using errcode='PT422';end if;
 select array_agg(key order by(definition->>'order')::integer)into enabled from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and definition->>'classification'='required';
 enabled:=coalesce(enabled,'{}')||seed;
 -- Dependency closure has a strict catalog-size bound and no client formulas.
 for iteration in 1..128 loop
 changed:=false;
 foreach k in array enabled loop
 select *into d from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and key=k;
 if not found or not coalesce((d.definition->>'available')::boolean,false)then raise exception 'Unsupported tracking statistic'using errcode='PT422';end if;
 for k in select value from jsonb_array_elements_text(d.definition->'dependencies')loop
 if not k=any(enabled)then enabled:=array_append(enabled,k);changed:=true;end if;end loop;end loop;
 for d in select *from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and definition->>'classification'='derived'loop
 select coalesce(array_agg(value),'{}')into deps from jsonb_array_elements_text(d.definition->'dependencies');
 if cardinality(deps)>0 and deps<@enabled and not d.key=any(enabled)then enabled:=array_append(enabled,d.key);changed:=true;end if;end loop;
 exit when not changed;
 if iteration=128 then raise exception 'Invalid tracking dependencies'using errcode='PT422';end if;
 end loop;
 if quick is null then
 select coalesce(array_agg(x.key order by x.ord),'{}')into ordered from(select s.key,s.ord from unnest(case when sport in('baseball','softball')then array['play_state']||array_remove(seed,'play_state')else seed end)with ordinality s(key,ord)join public.game_stat_catalog_items c on c.sport_key=sport and c.catalog_version='boss-tracking-v1'and c.key=s.key where(c.definition->>'quick_eligible')::boolean order by s.ord limit 8)x;
 else
 if jsonb_typeof(quick)is distinct from'array'or jsonb_array_length(quick)>8 then raise exception 'Invalid Quick Stats'using errcode='PT422';end if;
 select coalesce(array_agg(value),'{}')into ordered from jsonb_array_elements_text(quick);
 end if;
 if(select count(distinct v)from unnest(ordered)v)<>cardinality(ordered)then raise exception 'Duplicate Quick Stats'using errcode='PT422';end if;
 foreach k in array ordered loop
 if not k=any(enabled)or not exists(select 1 from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and key=k and(definition->>'quick_eligible')::boolean)then raise exception 'Invalid Quick Stats'using errcode='PT422';end if;end loop;
 select array_agg(key order by(definition->>'order')::integer)into enabled from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and key=any(enabled);
 return jsonb_build_object('catalog_version','boss-tracking-v1','preset',preset,'enabled',to_jsonb(enabled),'quick',to_jsonb(ordered));
end$$;
create or replace function boss_private.tracking_profile_command(actor uuid,i jsonb,request uuid,replay boolean default false)returns jsonb
language plpgsql volatile security definer set search_path=''as $$
declare p public.game_tracking_profiles;old public.game_tracking_profiles;g public.games;e public.events;
 selection jsonb;before_state jsonb;rid uuid;opid uuid;reason text;begin
 perform boss_private.games_validate(i,array['sport_key','scope_type','organization_id','unit_id','team_id','season_id','game_id','side','expected_profile_version','expected_game_version','preset','enabled','quick','status','ends_at','reason'],array['sport_key','scope_type','expected_profile_version','preset','reason']);
 if i->>'sport_key'not in('basketball','soccer','football','volleyball','baseball','softball')or i->>'scope_type'not in('platform','organization','organization_unit','team','season','game')or jsonb_typeof(i->'expected_profile_version')<>'number'or i->>'expected_profile_version'!~'^[0-9]{1,15}$'then raise exception 'Invalid tracking scope/version'using errcode='PT422';end if;
 p.sport_key:=i->>'sport_key';p.scope_type:=i->>'scope_type';p.organization_id:=(i->>'organization_id')::uuid;p.unit_id:=(i->>'unit_id')::uuid;p.team_id:=(i->>'team_id')::uuid;p.season_id:=(i->>'season_id')::uuid;p.game_id:=(i->>'game_id')::uuid;p.side:=i->>'side';
 if not((p.scope_type='platform'and p.organization_id is null and p.unit_id is null and p.team_id is null and p.season_id is null and p.game_id is null and p.side is null)
 or(p.scope_type='organization'and p.organization_id is not null and p.unit_id is null and p.team_id is null and p.season_id is null and p.game_id is null and p.side is null)
 or(p.scope_type='organization_unit'and p.organization_id is not null and p.unit_id is not null and p.team_id is null and p.season_id is null and p.game_id is null and p.side is null)
 or(p.scope_type='team'and p.organization_id is not null and p.unit_id is null and p.team_id is not null and p.season_id is null and p.game_id is null and p.side is null)
 or(p.scope_type='season'and p.organization_id is not null and p.unit_id is null and p.team_id is not null and p.season_id is not null and p.game_id is null and p.side is null)
 or(p.scope_type='game'and p.organization_id is not null and p.unit_id is null and p.team_id is null and p.season_id is null and p.game_id is not null and p.side in('primary','opponent')))then raise exception 'Invalid tracking scope'using errcode='PT422';end if;
 reason:=i->>'reason';if length(btrim(reason))not between 1 and 500 or reason~'[[:cntrl:]]'then raise exception 'Tracking change reason is required'using errcode='PT422';end if;
 selection:=boss_private.tracking_selection(p.sport_key,i->>'preset',coalesce(i->'enabled','[]'),i->'quick');
 p.status:=coalesce(i->>'status','active');p.ends_at:=(i->>'ends_at')::timestamptz;
 if p.status not in('active','inactive')or p.ends_at is not null and(not isfinite(p.ends_at)or p.ends_at<=clock_timestamp())then raise exception 'Invalid tracking lifecycle'using errcode='PT422';end if;
 -- Fast denial before locks; repeat after all waits and before commit.
 perform boss_private.games_require_live_auth();
 if not boss_private.tracking_scope_allowed(actor,p)then raise exception 'Access denied'using errcode='PT403';end if;
 perform boss_private.tracking_locks(p);
 if p.scope_type='game'then
 select event_id into e.id from public.games where id=p.game_id;
 select *into e from public.events where id=e.id for update;
 select *into g from public.games where id=p.game_id for update;
 perform boss_private.games_lock_authority(actor,g);
 if g.status in('final','canceled','abandoned','postponed')then raise exception 'Game tracking is locked'using errcode='PT409';end if;
 if not i?'expected_game_version'or i->>'expected_game_version'!~'^[0-9]{1,15}$'then raise exception 'Game version is required'using errcode='PT422';end if;
 else
 perform 1 from public.role_assignments where person_id=actor and(organization_id=p.organization_id or scope_type='platform')order by id for share;
 perform 1 from public.organization_memberships where person_id=actor and organization_id=p.organization_id order by id for share;
 perform 1 from public.team_memberships where person_id=actor and organization_id=p.organization_id and team_id=p.team_id order by id for share;
 perform 1 from public.organization_modules where organization_id=p.organization_id order by id for share;
 end if;
 perform boss_private.games_require_live_auth();if not boss_private.tracking_scope_allowed(actor,p)then raise exception 'Access denied'using errcode='PT403';end if;
 select *into old from public.game_tracking_profiles x where x.sport_key=p.sport_key and x.scope_type=p.scope_type and x.organization_id is not distinct from p.organization_id and x.unit_id is not distinct from p.unit_id and x.team_id is not distinct from p.team_id and x.season_id is not distinct from p.season_id and x.game_id is not distinct from p.game_id and x.side is not distinct from p.side for update;
 if replay then return jsonb_build_object('profile_id',old.id,'profile_version',old.version,'game_id',g.id,'organization_id',old.organization_id,'version',coalesce(g.version,old.version),'message','Saved.');end if;
 if coalesce(old.version,0)<>(i->>'expected_profile_version')::bigint or g.id is not null and g.version<>(i->>'expected_game_version')::bigint then raise exception 'Tracking profile changed; reload before saving'using errcode='PT409';end if;
 before_state:=to_jsonb(old);
 if old.id is null then
 insert into public.game_tracking_profiles(sport_key,organization_id,scope_type,unit_id,team_id,season_id,game_id,side,version,status,ends_at)
 values(p.sport_key,p.organization_id,p.scope_type,p.unit_id,p.team_id,p.season_id,p.game_id,p.side,1,p.status,p.ends_at)returning *into p;
 else
 update public.game_tracking_profiles set version=old.version+1,status=p.status,ends_at=coalesce(p.ends_at,old.ends_at)where id=old.id returning *into p;end if;
 insert into public.game_tracking_profile_revisions(profile_id,sport_key,version,catalog_version,selection,actor_person_id,request_id)
 values(p.id,p.sport_key,p.version,'boss-tracking-v1',selection,actor,request)returning id into rid;
 if g.id is not null and exists(select 1 from public.game_tracking_snapshots where game_id=g.id)then
 update public.games set version=g.version+1 where id=g.id returning *into g;
 perform boss_private.tracking_snapshot(g,p.side,g.last_sequence+1);
 opid:=boss_private.games_append(g.id,actor,'tracking.profile.set',request,boss_private.games_core_state(g)||jsonb_build_object('tracking_profile',before_state),jsonb_build_object('tracking_profile_id',p.id,'tracking_revision_id',rid,'reason',reason));
 else
 insert into public.audit_events(organization_id,actor_person_id,actor_auth_user_id,action,resource_type,resource_id,scope_type,scope_id,request_id,before_data,after_data)
 values(p.organization_id,actor,auth.uid(),'tracking.profile.set','game_tracking_profile',p.id,case p.scope_type when'season'then'team'when'game'then'organization'else p.scope_type end,case p.scope_type when'platform'then null when'organization_unit'then p.unit_id when'team'then p.team_id when'season'then p.team_id else p.organization_id end,request,before_state,to_jsonb(p)||jsonb_build_object('revision_id',rid,'selection',selection,'reason',reason));end if;
 perform boss_private.games_require_live_auth();if not boss_private.tracking_scope_allowed(actor,p)then raise exception 'Access denied'using errcode='PT403';end if;
 return jsonb_build_object('profile_id',p.id,'profile_version',p.version,'game_id',g.id,'organization_id',p.organization_id,'version',coalesce(g.version,p.version),'message','Tracking profile saved.');
end$$;
create or replace function boss_private.games_configuration(p_org uuid) returns jsonb language sql stable security definer set search_path='' as $$
 with raw as(select boss_private.coordination_configuration(p_org,'sports') c),keys as(select unnest(array['game_center','game_operations','public_game_center','team_game_management','head_coach_game_management','basketball_live_scoring','basketball_stats','basketball_play_by_play','basketball_lineups','soccer_live_scoring','soccer_stats','soccer_play_by_play','soccer_lineups','football_live_scoring','football_stats','football_play_by_play','football_lineups','volleyball_live_scoring','volleyball_stats','volleyball_play_by_play','volleyball_lineups','baseball_live_scoring','baseball_stats','baseball_play_by_play','baseball_lineups','softball_live_scoring','softball_stats','softball_play_by_play','softball_lineups']) k)
 select jsonb_object_agg(k,case when jsonb_typeof(c->k)='boolean' then c->k else 'false'::jsonb end) from raw cross join keys
$$;
create or replace function boss_private.games_feature(p_org uuid,p_key text,p_configuration jsonb default null) returns boolean language sql volatile security definer set search_path='' as $$
 select boss_private.games_module_live(p_org,'sports') and p_key=any(array['game_center','game_operations','public_game_center','team_game_management','head_coach_game_management','basketball_live_scoring','basketball_stats','basketball_play_by_play','basketball_lineups','soccer_live_scoring','soccer_stats','soccer_play_by_play','soccer_lineups','football_live_scoring','football_stats','football_play_by_play','football_lineups','volleyball_live_scoring','volleyball_stats','volleyball_play_by_play','volleyball_lineups','baseball_live_scoring','baseball_stats','baseball_play_by_play','baseball_lineups','softball_live_scoring','softball_stats','softball_play_by_play','softball_lineups'])
 and coalesce((coalesce(p_configuration,boss_private.games_configuration(p_org))->>'game_center')::boolean,false)
 and coalesce((coalesce(p_configuration,boss_private.games_configuration(p_org))->>p_key)::boolean,false)
$$;
create or replace function boss_private.games_configure(p_actor uuid,i jsonb,p_request uuid,p_replay boolean default false) returns jsonb
language plpgsql security definer set search_path='' as $$
declare organization uuid;module public.organization_modules;key text;prior jsonb;after_state jsonb;
 flags text[]:=array['game_center','game_operations','public_game_center','team_game_management','head_coach_game_management','basketball_live_scoring','basketball_stats','basketball_play_by_play','basketball_lineups','soccer_live_scoring','soccer_stats','soccer_play_by_play','soccer_lineups','football_live_scoring','football_stats','football_play_by_play','football_lineups','volleyball_live_scoring','volleyball_stats','volleyball_play_by_play','volleyball_lineups','baseball_live_scoring','baseball_stats','baseball_play_by_play','baseball_lineups','softball_live_scoring','softball_stats','softball_play_by_play','softball_lineups'];begin
 perform boss_private.games_validate(i,array['organization_id','expected_version','configuration'],array['organization_id','expected_version','configuration']);
 if jsonb_typeof(i->'configuration')<>'object' or i->'configuration'='{}'::jsonb then raise exception 'Invalid game configuration' using errcode='PT422';end if;
 for key in select jsonb_object_keys(i->'configuration') loop
 if not key=any(flags) or jsonb_typeof(i->'configuration'->key)<>'boolean' then raise exception 'Invalid game configuration' using errcode='PT422';end if;end loop;
 organization:=(i->>'organization_id')::uuid;
 perform 1 from public.role_assignments assignment where assignment.person_id=p_actor and(assignment.organization_id=organization or assignment.scope_type='platform') order by assignment.id for share;
 perform 1 from public.organization_memberships membership where membership.person_id=p_actor and membership.organization_id=organization order by membership.id for share;
 perform boss_private.games_require_live_auth();
 if p_actor is distinct from boss_private.require_admin_actor() or not boss_private.games_role_permission(p_actor,'organization.manage',organization) then raise exception 'Access denied' using errcode='PT403';end if;
 select membership.* into module from public.organization_modules membership join public.modules catalog on catalog.id=membership.module_id and catalog.key='sports' and catalog.status='active'
 where membership.organization_id=organization and membership.status='active' and membership.starts_at<=clock_timestamp() and(membership.ends_at is null or membership.ends_at>clock_timestamp())
 order by membership.starts_at desc,membership.id desc limit 1 for update of membership;
 perform boss_private.games_require_live_auth();
 if p_actor is distinct from boss_private.require_admin_actor() or not boss_private.games_role_permission(p_actor,'organization.manage',organization) then raise exception 'Access denied' using errcode='PT403';end if;
 if module.id is null or module.status<>'active' or module.starts_at>clock_timestamp() or(module.ends_at is not null and module.ends_at<=clock_timestamp()) then raise exception 'Access denied' using errcode='PT403';end if;
 if p_replay then return jsonb_build_object('game_id',null,'organization_id',organization,'version',module.version,'message','Saved.');end if;
 if module.version<>(i->>'expected_version')::bigint then raise exception 'Sports configuration changed; reload before saving' using errcode='PT409';end if;
 select jsonb_build_object('version',module.version,'configuration',jsonb_object_agg(flag,case when jsonb_typeof(module.configuration->flag)='boolean' then module.configuration->flag else 'false'::jsonb end)) into prior from unnest(flags) flag;
 update public.organization_modules set configuration=configuration||(i->'configuration') where id=module.id returning * into module;
 select jsonb_build_object('version',module.version,'configuration',jsonb_object_agg(flag,case when jsonb_typeof(module.configuration->flag)='boolean' then module.configuration->flag else 'false'::jsonb end)) into after_state from unnest(flags) flag;
 insert into public.audit_events(organization_id,actor_person_id,actor_auth_user_id,action,resource_type,resource_id,scope_type,scope_id,request_id,before_data,after_data)
 values(organization,p_actor,auth.uid(),'games.configure','organization_module',module.id,'organization',organization,p_request,prior,after_state);
 return jsonb_build_object('game_id',null,'organization_id',organization,'version',module.version,'message','Game Center settings saved.');
end$$;
create function boss_private.diamond_engine_identity()returns trigger language plpgsql security definer set search_path=''as $$
declare g public.games;begin
 select *into g from public.games where id=new.game_id for update;
 if g.organization_id is distinct from new.organization_id or g.sport_key is distinct from new.sport_key or new.configuration->>'sport'is distinct from g.sport_key
 or exists(select 1 from public.game_basketball_states where game_id=g.id)or exists(select 1 from public.game_soccer_states where game_id=g.id)
 or exists(select 1 from public.game_football_states where game_id=g.id)or exists(select 1 from public.game_volleyball_states where game_id=g.id)then raise exception 'Wrong Diamond engine identity'using errcode='PT409';end if;return new;
end$$;
create trigger diamond_engine_identity before insert on public.game_diamond_states for each row execute function boss_private.diamond_engine_identity();
alter function boss_private.games_append(uuid,uuid,text,uuid,jsonb,jsonb,uuid)rename to games_append_phase5e;
create function boss_private.games_append(p_game uuid,p_actor uuid,p_op text,p_request uuid,p_before jsonb,p_extra jsonb default'{}',p_correction uuid default null)returns uuid
language plpgsql security definer set search_path=''as $$
declare s public.game_diamond_states;begin
 select *into s from public.game_diamond_states where game_id=p_game;
 return boss_private.games_append_phase5e(p_game,p_actor,p_op,p_request,p_before,case when s.game_id is null then'{}'::jsonb else jsonb_build_object('diamond',s.state)end||p_extra,p_correction);
end$$;
alter function boss_private.games_command(uuid,text,jsonb,uuid,boolean,uuid)rename to games_command_phase5e;
create function boss_private.games_command(p_actor uuid,p_op text,i jsonb,p_request uuid,p_replay boolean default false,p_resource uuid default null)returns jsonb
language plpgsql security definer set search_path=''as $$
declare g public.games;e public.events;s public.game_diamond_states;begin
 if p_op like'diamond.%'then return boss_private.diamond_command(p_actor,p_op,i,p_request,p_replay);end if;
 if p_op in('game.score.set','game.score.reverse','game.roster.snapshot','game.finalize','game.reopen','game.start')or(p_op='game.transition'and i->>'status'='live')then
 select *into g from public.games where id=(i->>'game_id')::uuid;
 if exists(select 1 from public.game_diamond_states where game_id=g.id)then
 select *into e from public.events where id=g.event_id for update;select *into g from public.games where id=g.id for update;
 perform boss_private.games_lock_authority(p_actor,g);perform boss_private.games_require_live_auth();
 if p_actor is distinct from boss_private.require_admin_actor()or not boss_private.games_operation_allowed(p_actor,p_op,g)then raise exception 'Access denied'using errcode='PT403';end if;
 if p_op in('game.score.set','game.score.reverse','game.roster.snapshot')then raise exception 'Diamond owns score and roster'using errcode='PT409';end if;
 if not boss_private.games_feature(g.organization_id,g.sport_key||'_live_scoring')or not boss_private.games_feature(g.organization_id,'game_operations')then raise exception 'Access denied'using errcode='PT403';end if;
 select *into s from public.game_diamond_states where game_id=g.id;
 if p_op='game.finalize'and not p_replay and(not boss_private.diamond_final_ready(s.configuration,s.state)
 or s.roster_revision<>g.roster_revision or s.state is distinct from boss_private.diamond_rebuild(g.id)or g.primary_score<>(s.state->>'primary_score')::int or g.opponent_score<>(s.state->>'opponent_score')::int)then raise exception 'Diamond not ready to finalize'using errcode='PT409';end if;
 end if;end if;
 return boss_private.games_command_phase5e(p_actor,p_op,i,p_request,p_replay,p_resource);
end$$;
-- Every helper is private; the existing caller-bound native public RPC remains.
do $$declare f record;begin for f in select p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='boss_private'and(p.proname like'diamond_%'or p.proname in('games_append','games_append_phase5e','games_command','games_command_phase5e','tracking_selection','tracking_profile_command','games_configure','games_configuration','games_feature'))loop execute format('revoke all on function %s from public,anon,authenticated,service_role',f.signature);end loop;end$$;

-- Immutable sport-qualified definitions shared with the console catalog.
insert into public.game_stat_catalog_versions(sport_key,version) values('baseball','boss-tracking-v1');
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','play_state','{"key":"play_state","label":"play state","short_label":"Result","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["single","double","triple","home_run","walk","strikeout","other_out","reached_on_error","fielders_choice"],"prompts":[],"order":0,"scopes":["game"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','inning_state','{"key":"inning_state","label":"inning state","short_label":"Inning","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["half_start"],"prompts":[],"order":1,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','runner_state','{"key":"runner_state","label":"runner state","short_label":"Runners","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["advance"],"prompts":[],"order":2,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','participation','{"key":"participation","label":"participation","short_label":"Lineup","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["lineup_set","substitution","pitcher_change"],"prompts":[],"order":3,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','player_attribution','{"key":"player_attribution","label":"player attribution","short_label":"Player credit","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":[],"prompts":[],"order":10,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','pitch_detail','{"key":"pitch_detail","label":"pitch detail","short_label":"Pitch","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["ball","called_strike","swinging_strike","foul","in_play"],"prompts":[],"order":11,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','baserunning','{"key":"baserunning","label":"baserunning","short_label":"Baserunning","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["stolen_base","caught_stealing"],"prompts":[],"order":12,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','putouts','{"key":"putouts","label":"putouts","short_label":"Putout","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["fielding"],"prompts":[],"order":13,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','assists','{"key":"assists","label":"assists","short_label":"Assist","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["fielding"],"prompts":[],"order":14,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','errors','{"key":"errors","label":"errors","short_label":"Error","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["error_attribution"],"prompts":[],"order":15,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','double_plays','{"key":"double_plays","label":"double plays","short_label":"Double play","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["putouts"],"actions":["fielding"],"prompts":[],"order":16,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','earned_runs','{"key":"earned_runs","label":"earned runs","short_label":"Earned run","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["earned_run_attribution"],"prompts":[],"order":17,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','pa','{"key":"pa","label":"pa","short_label":"pa","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":30,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','ab','{"key":"ab","label":"ab","short_label":"ab","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":31,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','runs','{"key":"runs","label":"runs","short_label":"runs","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":32,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','hits','{"key":"hits","label":"hits","short_label":"hits","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":33,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','singles','{"key":"singles","label":"singles","short_label":"singles","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":34,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','doubles','{"key":"doubles","label":"doubles","short_label":"doubles","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":35,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','triples','{"key":"triples","label":"triples","short_label":"triples","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":36,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','home_runs','{"key":"home_runs","label":"home runs","short_label":"home runs","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":37,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','rbi','{"key":"rbi","label":"rbi","short_label":"rbi","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":38,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','walks','{"key":"walks","label":"walks","short_label":"walks","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":39,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','hbp','{"key":"hbp","label":"hbp","short_label":"hbp","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":40,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','strikeouts','{"key":"strikeouts","label":"strikeouts","short_label":"strikeouts","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":41,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','sacrifice_flies','{"key":"sacrifice_flies","label":"sacrifice flies","short_label":"sacrifice flies","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":42,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','sacrifice_bunts','{"key":"sacrifice_bunts","label":"sacrifice bunts","short_label":"sacrifice bunts","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":43,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','outs_pitched','{"key":"outs_pitched","label":"outs pitched","short_label":"outs pitched","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":44,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','batters_faced','{"key":"batters_faced","label":"batters faced","short_label":"batters faced","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":45,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','hits_allowed','{"key":"hits_allowed","label":"hits allowed","short_label":"hits allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":46,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','runs_allowed','{"key":"runs_allowed","label":"runs allowed","short_label":"runs allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":47,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','walks_allowed','{"key":"walks_allowed","label":"walks allowed","short_label":"walks allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":48,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','strikeouts_pitched','{"key":"strikeouts_pitched","label":"strikeouts pitched","short_label":"strikeouts pitched","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":49,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','hbp_allowed','{"key":"hbp_allowed","label":"hbp allowed","short_label":"hbp allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":50,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','home_runs_allowed','{"key":"home_runs_allowed","label":"home runs allowed","short_label":"home runs allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":51,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','stolen_bases','{"key":"stolen_bases","label":"stolen bases","short_label":"stolen bases","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["baserunning"],"actions":[],"prompts":[],"order":60,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','caught_stealing','{"key":"caught_stealing","label":"caught stealing","short_label":"caught stealing","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["baserunning"],"actions":[],"prompts":[],"order":61,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','pitches','{"key":"pitches","label":"pitches","short_label":"pitches","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["pitch_detail"],"actions":[],"prompts":[],"order":62,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','strikes','{"key":"strikes","label":"strikes","short_label":"strikes","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["pitch_detail"],"actions":[],"prompts":[],"order":63,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','wild_pitches','{"key":"wild_pitches","label":"wild pitches","short_label":"wild pitches","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["runner_state"],"actions":[],"prompts":[],"order":64,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','avg','{"key":"avg","label":"avg","short_label":"avg","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["hits","ab"],"actions":[],"prompts":[],"order":70,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','obp','{"key":"obp","label":"obp","short_label":"obp","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["hits","ab","walks","hbp","sacrifice_flies"],"actions":[],"prompts":[],"order":71,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','slg','{"key":"slg","label":"slg","short_label":"slg","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["singles","doubles","triples","home_runs","ab"],"actions":[],"prompts":[],"order":72,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','ops','{"key":"ops","label":"ops","short_label":"ops","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["obp","slg"],"actions":[],"prompts":[],"order":73,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','era','{"key":"era","label":"era","short_label":"era","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["earned_runs","outs_pitched"],"actions":[],"prompts":[],"order":74,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','whip','{"key":"whip","label":"whip","short_label":"whip","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["hits_allowed","walks_allowed","outs_pitched"],"actions":[],"prompts":[],"order":75,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','strike_percentage','{"key":"strike_percentage","label":"strike percentage","short_label":"strike percentage","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["pitches","strikes"],"actions":[],"prompts":[],"order":76,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','pitch_velocity','{"key":"pitch_velocity","label":"pitch velocity","short_label":"pitch velocity","category":"statistics","classification":"advanced","available":false,"default_enabled":false,"modes":[],"dependencies":["pitch_detail"],"actions":[],"prompts":[],"order":90,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('baseball','boss-tracking-v1','pitch_location','{"key":"pitch_location","label":"pitch location","short_label":"pitch location","category":"statistics","classification":"advanced","available":false,"default_enabled":false,"modes":[],"dependencies":["pitch_detail"],"actions":[],"prompts":[],"order":91,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_versions(sport_key,version) values('softball','boss-tracking-v1');
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','play_state','{"key":"play_state","label":"play state","short_label":"Result","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["single","double","triple","home_run","walk","strikeout","other_out","reached_on_error","fielders_choice"],"prompts":[],"order":0,"scopes":["game"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','inning_state','{"key":"inning_state","label":"inning state","short_label":"Inning","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["half_start"],"prompts":[],"order":1,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','runner_state','{"key":"runner_state","label":"runner state","short_label":"Runners","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["advance"],"prompts":[],"order":2,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','participation','{"key":"participation","label":"participation","short_label":"Lineup","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["lineup_set","substitution","pitcher_change"],"prompts":[],"order":3,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','player_attribution','{"key":"player_attribution","label":"player attribution","short_label":"Player credit","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":[],"prompts":[],"order":10,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','pitch_detail','{"key":"pitch_detail","label":"pitch detail","short_label":"Pitch","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["ball","called_strike","swinging_strike","foul","in_play"],"prompts":[],"order":11,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','baserunning','{"key":"baserunning","label":"baserunning","short_label":"Baserunning","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["stolen_base","caught_stealing"],"prompts":[],"order":12,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','putouts','{"key":"putouts","label":"putouts","short_label":"Putout","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["fielding"],"prompts":[],"order":13,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','assists','{"key":"assists","label":"assists","short_label":"Assist","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["fielding"],"prompts":[],"order":14,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','errors','{"key":"errors","label":"errors","short_label":"Error","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["error_attribution"],"prompts":[],"order":15,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','double_plays','{"key":"double_plays","label":"double plays","short_label":"Double play","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["putouts"],"actions":["fielding"],"prompts":[],"order":16,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','earned_runs','{"key":"earned_runs","label":"earned runs","short_label":"Earned run","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["earned_run_attribution"],"prompts":[],"order":17,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','pa','{"key":"pa","label":"pa","short_label":"pa","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":30,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','ab','{"key":"ab","label":"ab","short_label":"ab","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":31,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','runs','{"key":"runs","label":"runs","short_label":"runs","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":32,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','hits','{"key":"hits","label":"hits","short_label":"hits","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":33,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','singles','{"key":"singles","label":"singles","short_label":"singles","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":34,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','doubles','{"key":"doubles","label":"doubles","short_label":"doubles","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":35,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','triples','{"key":"triples","label":"triples","short_label":"triples","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":36,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','home_runs','{"key":"home_runs","label":"home runs","short_label":"home runs","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":37,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','rbi','{"key":"rbi","label":"rbi","short_label":"rbi","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":38,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','walks','{"key":"walks","label":"walks","short_label":"walks","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":39,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','hbp','{"key":"hbp","label":"hbp","short_label":"hbp","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":40,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','strikeouts','{"key":"strikeouts","label":"strikeouts","short_label":"strikeouts","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":41,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','sacrifice_flies','{"key":"sacrifice_flies","label":"sacrifice flies","short_label":"sacrifice flies","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":42,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','sacrifice_bunts','{"key":"sacrifice_bunts","label":"sacrifice bunts","short_label":"sacrifice bunts","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":43,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','outs_pitched','{"key":"outs_pitched","label":"outs pitched","short_label":"outs pitched","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":44,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','batters_faced','{"key":"batters_faced","label":"batters faced","short_label":"batters faced","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":45,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','hits_allowed','{"key":"hits_allowed","label":"hits allowed","short_label":"hits allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":46,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','runs_allowed','{"key":"runs_allowed","label":"runs allowed","short_label":"runs allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":47,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','walks_allowed','{"key":"walks_allowed","label":"walks allowed","short_label":"walks allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":48,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','strikeouts_pitched','{"key":"strikeouts_pitched","label":"strikeouts pitched","short_label":"strikeouts pitched","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":49,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','hbp_allowed','{"key":"hbp_allowed","label":"hbp allowed","short_label":"hbp allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":50,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','home_runs_allowed','{"key":"home_runs_allowed","label":"home runs allowed","short_label":"home runs allowed","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":51,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','stolen_bases','{"key":"stolen_bases","label":"stolen bases","short_label":"stolen bases","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["baserunning"],"actions":[],"prompts":[],"order":60,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','caught_stealing','{"key":"caught_stealing","label":"caught stealing","short_label":"caught stealing","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["baserunning"],"actions":[],"prompts":[],"order":61,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','pitches','{"key":"pitches","label":"pitches","short_label":"pitches","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["pitch_detail"],"actions":[],"prompts":[],"order":62,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','strikes','{"key":"strikes","label":"strikes","short_label":"strikes","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["pitch_detail"],"actions":[],"prompts":[],"order":63,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','wild_pitches','{"key":"wild_pitches","label":"wild pitches","short_label":"wild pitches","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["runner_state"],"actions":[],"prompts":[],"order":64,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','avg','{"key":"avg","label":"avg","short_label":"avg","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["hits","ab"],"actions":[],"prompts":[],"order":70,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','obp','{"key":"obp","label":"obp","short_label":"obp","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["hits","ab","walks","hbp","sacrifice_flies"],"actions":[],"prompts":[],"order":71,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','slg','{"key":"slg","label":"slg","short_label":"slg","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["singles","doubles","triples","home_runs","ab"],"actions":[],"prompts":[],"order":72,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','ops','{"key":"ops","label":"ops","short_label":"ops","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["obp","slg"],"actions":[],"prompts":[],"order":73,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','era','{"key":"era","label":"era","short_label":"era","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["earned_runs","outs_pitched"],"actions":[],"prompts":[],"order":74,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','whip','{"key":"whip","label":"whip","short_label":"whip","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["hits_allowed","walks_allowed","outs_pitched"],"actions":[],"prompts":[],"order":75,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','strike_percentage','{"key":"strike_percentage","label":"strike percentage","short_label":"strike percentage","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["pitches","strikes"],"actions":[],"prompts":[],"order":76,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','pitch_velocity','{"key":"pitch_velocity","label":"pitch velocity","short_label":"pitch velocity","category":"statistics","classification":"advanced","available":false,"default_enabled":false,"modes":[],"dependencies":["pitch_detail"],"actions":[],"prompts":[],"order":90,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('softball','boss-tracking-v1','pitch_location','{"key":"pitch_location","label":"pitch location","short_label":"pitch location","category":"statistics","classification":"advanced","available":false,"default_enabled":false,"modes":[],"dependencies":["pitch_detail"],"actions":[],"prompts":[],"order":91,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
