-- Phase 6C bounded projections. Public tokens disclose only the frozen, consented showcase.
create function boss_private.athlete_staff_origin(actor uuid,k text,profile uuid,org uuid,team_id uuid)returns boolean language sql volatile security definer set search_path=''as $$
 select exists(select 1 from public.athlete_profiles ap join public.team_memberships subject_membership on subject_membership.participant_id=ap.participant_id and subject_membership.person_id=ap.person_id
 join public.teams team on team.id=subject_membership.team_id and team.organization_id=subject_membership.organization_id and team.status='active'
 where ap.id=profile and ap.status='active'and team.id=team_id and team.organization_id=org and subject_membership.status='active'and subject_membership.starts_at<=clock_timestamp()and(subject_membership.ends_at is null or subject_membership.ends_at>clock_timestamp())
 and exists(select 1 from public.role_assignments assignment join public.roles role on role.id=assignment.role_id and role.status='active'
 join public.role_permissions rp on rp.role_id=role.id join public.permissions permission on permission.id=rp.permission_id and permission.key=k and permission.status='active'
 where assignment.person_id=actor and assignment.status='active'and assignment.starts_at<=clock_timestamp()and(assignment.ends_at is null or assignment.ends_at>clock_timestamp())and(
  assignment.scope_type='platform'and assignment.scope_id is null and assignment.organization_id is null
  or assignment.organization_id=org and(
   assignment.scope_type='organization'and assignment.scope_id=org and exists(select 1 from public.organization_memberships m where m.organization_id=org and m.person_id=actor and m.status='active'and m.starts_at<=clock_timestamp()and(m.ends_at is null or m.ends_at>clock_timestamp()))
   or assignment.scope_type='organization_unit'and assignment.scope_id=team.parent_unit_id and exists(select 1 from public.organization_memberships m where m.organization_id=org and m.person_id=actor and m.status='active'and m.starts_at<=clock_timestamp()and(m.ends_at is null or m.ends_at>clock_timestamp()))
   or assignment.scope_type='team'and assignment.scope_id=team_id and exists(select 1 from public.team_memberships m where m.team_id=team_id and m.person_id=actor and m.status='active'and m.starts_at<=clock_timestamp()and(m.ends_at is null or m.ends_at>clock_timestamp()))))))
$$;

create function boss_private.athlete_metric_projection(summary jsonb,keys text[])returns jsonb language sql immutable set search_path=''as $$
 select jsonb_strip_nulls(jsonb_build_object(
  'games',summary->'games','coverage',summary->'coverage','freshness',summary->'freshness',
  'metrics',(select coalesce(jsonb_object_agg(e.key,e.value),'{}')from jsonb_each(coalesce(summary->'metrics','{}'))e where e.key=any(keys)),
  'rates',(select coalesce(jsonb_object_agg(e.key,e.value),'{}')from jsonb_each(coalesce(summary->'rates','{}'))e where e.key=any(keys))))
$$;

create function boss_private.athlete_profile_projection(actor uuid,profile_id uuid)returns jsonb language plpgsql volatile security definer set search_path=''as $$
declare p public.athlete_profiles;family_access boolean;manage boolean;showcase_manage boolean;response jsonb;begin
 select *into p from public.athlete_profiles where id=profile_id and status='active';if p.id is null or not boss_private.athlete_can_view(actor,p.id)then raise exception'Access denied'using errcode='PT403';end if;
 family_access:=p.person_id=actor or boss_private.athlete_guardian(actor,p.person_id,false);manage:=boss_private.athlete_can_manage(actor,p.id);showcase_manage:=boss_private.athlete_can_showcase(actor,p.id,'recruiting_showcases.manage');
 select jsonb_build_object(
  'profile',jsonb_build_object('id',p.id,'participant_id',p.participant_id,'person_id',p.person_id,'status',p.status,'visibility',p.visibility,'version',p.version,'current_revision_id',p.current_revision_id,
   'fields',coalesce((select safe_fields from public.athlete_profile_revisions where id=p.current_revision_id),'{}'),
   'completeness',coalesce((select jsonb_build_object('completed',cardinality(array_remove(array[case when safe_fields?'display_name'then'display_name'end,case when safe_fields?'bio'then'bio'end,case when safe_fields?'positions'then'positions'end,case when exists(select 1 from public.athlete_measurables m where m.profile_id=p.id)then'measurable'end,case when exists(select 1 from public.stat_origin_summaries ss where ss.person_id=p.person_id and ss.is_current)then'statistics'end,case when exists(select 1 from public.athlete_media_links ml where ml.profile_id=p.id and ml.rights_state<>'withdrawn')then'media'end],null)),'possible',6)from public.athlete_profile_revisions where id=p.current_revision_id),jsonb_build_object('completed',0,'possible',6))),
  'authority',jsonb_build_object('relationship',case when p.person_id=actor then'self'when boss_private.athlete_guardian(actor,p.person_id,false)then'guardian'else'staff'end,'can_manage',manage,'can_verify',boss_private.athlete_staff(actor,'athlete_profiles.verify',p.id),'can_manage_showcase',showcase_manage,'self_publication_enabled',false),
  'origins',coalesce((select jsonb_agg(x order by x->>'starts_at'desc)from(select jsonb_build_object('organization_id',m.organization_id,'organization',o.name,'team_id',m.team_id,'team',t.name,'season_id',t.season_id,'sport_keys',coalesce((select jsonb_agg(distinct g.sport_key)from public.games g where g.organization_id=m.organization_id and m.team_id in(g.primary_team_id,g.opponent_team_id)),'[]'),'membership_type',m.membership_type,'position',m.position_label,'jersey_number',m.jersey_number,'starts_at',m.starts_at,'ends_at',m.ends_at,'current',m.status='active'and m.starts_at<=clock_timestamp()and(m.ends_at is null or m.ends_at>clock_timestamp()))x from public.team_memberships m join public.teams t on t.id=m.team_id and t.organization_id=m.organization_id join public.organizations o on o.id=m.organization_id where m.participant_id=p.participant_id and m.person_id=p.person_id and(family_access or(m.status='active'and m.starts_at<=clock_timestamp()and(m.ends_at is null or m.ends_at>clock_timestamp())and boss_private.athlete_staff_origin(actor,'athlete_profiles.view',p.id,m.organization_id,m.team_id)))order by m.starts_at desc,m.id limit 50)bounded),'[]'),
  'statistics',coalesce((select jsonb_agg(jsonb_build_object('organization_id',ss.organization_id,'team_id',ss.team_id,'sport_key',ss.sport_key,'season_id',ss.season_id,'generation',ss.generation,'refreshed_at',ss.refreshed_at,'freshness',case when ss.is_current then'current'else'pending'end,'summary',ss.summary)order by ss.refreshed_at desc nulls last,ss.id)from(select *from public.stat_origin_summaries x where x.person_id=p.person_id and(family_access or boss_private.athlete_staff_origin(actor,'athlete_profiles.view',p.id,x.organization_id,x.team_id))order by x.refreshed_at desc nulls last,x.id limit 24)ss),'[]'),
  'measurables',coalesce((select jsonb_agg(to_jsonb(m)-'actor_person_id'order by m.measured_on desc,m.id)from(select *from public.athlete_measurables x where x.profile_id=p.id and(family_access or x.visibility<>'private')order by x.measured_on desc,x.id limit 50)m),'[]'),
  'achievements',coalesce((select jsonb_agg(to_jsonb(a)-'actor_person_id'order by a.achieved_on desc nulls last,a.id)from(select *from public.athlete_achievements x where x.profile_id=p.id and(family_access or x.visibility<>'private')order by x.achieved_on desc nulls last,x.id limit 50)a),'[]'),
  'media',coalesce((select jsonb_agg(to_jsonb(m)-'actor_person_id'order by m.created_at desc,m.id)from(select *from public.athlete_media_links x where x.profile_id=p.id and x.rights_state<>'withdrawn'and(family_access or x.visibility<>'private')order by x.created_at desc,x.id limit 20)m),'[]'),
  'showcase',case when family_access or boss_private.athlete_staff(actor,'recruiting_showcases.view',p.id)then coalesce((select jsonb_build_object('id',s.id,'state',s.state,'version',s.version,'current_revision_id',s.current_revision_id,'published_revision_id',s.published_revision_id,'current_consent_id',s.current_consent_id,'revision',case when s.current_revision_id is null then null else(select to_jsonb(sr)-'actor_person_id'from public.recruiting_showcase_revisions sr where sr.id=s.current_revision_id)end,'links',case when showcase_manage then coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'token_prefix',l.token_prefix,'status',l.status,'expires_at',l.expires_at,'created_at',l.created_at,'last_accessed_at',l.last_accessed_at,'access_count',l.access_count)order by l.created_at desc)from(select *from public.recruiting_share_links x where x.showcase_id=s.id order by x.created_at desc limit 20)l),'[]')else'[]'::jsonb end)from public.recruiting_showcases s where s.profile_id=p.id),'null'::jsonb)else null end
 )into response;return response;
end$$;

create function public.boss_athlete_profile_read(p_profile_id uuid default null,p_participant_id uuid default null)returns jsonb language plpgsql volatile security definer set search_path=''as $$
declare actor uuid;profile uuid;subjects jsonb;begin perform boss_private.games_require_live_auth();actor:=boss_private.current_person_id();
 if p_profile_id is null and p_participant_id is not null then select id into profile from public.athlete_profiles where participant_id=p_participant_id and status='active';else profile:=p_profile_id;end if;
 select coalesce(jsonb_agg(jsonb_build_object('profile_id',p.id,'participant_id',p.participant_id,'person_id',p.person_id,'display_name',coalesce(r.safe_fields->>'display_name',person.preferred_name,person.display_name,'Athlete'),'visibility',p.visibility,'showcase_state',s.state)order by coalesce(r.safe_fields->>'display_name',person.preferred_name,person.display_name,'Athlete'),p.id),'[]')into subjects
 from(select candidate.*from public.athlete_profiles candidate where candidate.status='active'and boss_private.athlete_can_view(actor,candidate.id)order by candidate.created_at desc,candidate.id limit 50)p join public.people person on person.id=p.person_id left join public.athlete_profile_revisions r on r.id=p.current_revision_id left join public.recruiting_showcases s on s.profile_id=p.id;
 if profile is null then return jsonb_build_object('subjects',subjects,'profile',null,'unavailable',false);end if;
 return jsonb_build_object('subjects',subjects,'profile',boss_private.athlete_profile_projection(actor,profile),'unavailable',false);
end$$;

create function public.boss_athlete_profile_navigation()returns boolean language plpgsql volatile security definer set search_path=''as $$
declare actor uuid;begin perform boss_private.games_require_live_auth();actor:=boss_private.current_person_id();return boss_private.has_permission('athlete_profiles.view')or exists(select 1 from public.athlete_profiles p where p.status='active'and boss_private.athlete_can_view(actor,p.id));end$$;

create function public.boss_recruiting_showcase_read(p_token_digest text)returns jsonb language plpgsql volatile security definer set search_path=''as $$
declare l public.recruiting_share_links;s public.recruiting_showcases;p public.athlete_profiles;sr public.recruiting_showcase_revisions;pr public.athlete_profile_revisions;c public.recruiting_consents;response jsonb;begin
 if p_token_digest is null or p_token_digest!~'^[a-f0-9]{64}$'then return jsonb_build_object('available',false);end if;
 select *into l from public.recruiting_share_links where token_digest=p_token_digest and status='active'and(expires_at is null or expires_at>clock_timestamp());if l.id is null then return jsonb_build_object('available',false);end if;
 select *into s from public.recruiting_showcases where id=l.showcase_id and state='active';if s.id is null then return jsonb_build_object('available',false);end if;
 select *into p from public.athlete_profiles where id=s.profile_id and status='active';select *into sr from public.recruiting_showcase_revisions where id=s.published_revision_id and showcase_id=s.id;select *into pr from public.athlete_profile_revisions where id=sr.profile_revision_id and profile_id=p.id;
 select *into c from public.recruiting_consents where id=s.current_consent_id and showcase_id=s.id and showcase_revision_id=sr.id and subject_person_id=p.person_id and status='active'and(expires_at is null or expires_at>clock_timestamp());
 if p.id is null or sr.id is null or c.id is null or not boss_private.athlete_guardian(c.actor_person_id,p.person_id,true)or not sr.visible_categories<@c.approved_categories then return jsonb_build_object('available',false);end if;
 select jsonb_build_object('available',true,'showcase_id',s.id,'revision',sr.revision,'athlete',case when'overview'=any(sr.visible_categories)then pr.safe_fields else'{}'::jsonb end,
  'sports',sr.sport_keys,
  'statistics',case when'statistics'=any(sr.visible_categories)then coalesce((select jsonb_agg(jsonb_build_object('sport_key',x.sport_key,'season_id',x.season_id,'generation',x.generation,'refreshed_at',x.refreshed_at,'summary',boss_private.athlete_metric_projection(x.summary,sr.stat_metric_keys))order by x.refreshed_at desc nulls last,x.id)from(select *from public.stat_origin_summaries summary where summary.person_id=p.person_id and summary.is_current and(cardinality(sr.sport_keys)=0 or summary.sport_key=any(sr.sport_keys))order by summary.refreshed_at desc nulls last,summary.id limit 24)x),'[]')else'[]'::jsonb end,
  'measurables',case when'measurables'=any(sr.visible_categories)then coalesce((select jsonb_agg(jsonb_build_object('sport_key',m.sport_key,'metric_key',m.metric_key,'value',m.value,'unit',m.unit,'measured_on',m.measured_on,'provenance',m.provenance,'verification_state',m.verification_state,'source_label',m.source_label)order by m.measured_on desc,m.id)from(select *from public.athlete_measurables x where x.profile_id=p.id and x.visibility='showcase'and(cardinality(sr.sport_keys)=0 or x.sport_key=any(sr.sport_keys))order by x.measured_on desc,x.id limit 30)m),'[]')else'[]'::jsonb end,
  'achievements',case when'achievements'=any(sr.visible_categories)or'records'=any(sr.visible_categories)then coalesce((select jsonb_agg(jsonb_build_object('sport_key',a.sport_key,'type',a.achievement_type,'title',a.title,'achieved_on',a.achieved_on,'verification_level',a.verification_level,'current',case when a.source_record_event_id is not null then exists(select 1 from public.record_current_holders h where h.event_id=a.source_record_event_id)when a.source_ranking_candidate_id is not null then exists(select 1 from public.ranking_candidates rc join public.ranking_scopes scope on scope.id=rc.scope_id where rc.id=a.source_ranking_candidate_id and rc.qualification_state='qualified'and rc.built_generation=scope.published_generation and scope.state='current')else true end)order by a.achieved_on desc nulls last,a.id)from(select *from public.athlete_achievements x where x.profile_id=p.id and x.visibility='showcase'and(cardinality(sr.sport_keys)=0 or x.sport_key is null or x.sport_key=any(sr.sport_keys))and(('records'=any(sr.visible_categories)and x.achievement_type='record')or('achievements'=any(sr.visible_categories)and x.achievement_type<>'record'))order by x.achieved_on desc nulls last,x.id limit 30)a),'[]')else'[]'::jsonb end,
  'history',case when'history'=any(sr.visible_categories)then coalesce((select jsonb_agg(jsonb_build_object('organization',o.name,'team',t.name,'season',season.name,'position',m.position_label,'jersey_number',m.jersey_number,'starts_at',m.starts_at,'ends_at',m.ends_at)order by m.starts_at desc,m.id)from(select *from public.team_memberships x where x.participant_id=p.participant_id and x.person_id=p.person_id order by x.starts_at desc,x.id limit 30)m join public.teams t on t.id=m.team_id and t.organization_id=m.organization_id join public.organizations o on o.id=m.organization_id left join public.seasons season on season.id=t.season_id),'[]')else'[]'::jsonb end,
  'media',case when'media'=any(sr.visible_categories)then coalesce((select jsonb_agg(jsonb_build_object('sport_key',m.sport_key,'media_type',m.media_type,'url',m.url,'title',m.title,'source',m.source)order by m.created_at desc,m.id)from(select *from public.athlete_media_links x where x.profile_id=p.id and x.visibility='showcase'and x.rights_state='approved_showcase'and(cardinality(sr.sport_keys)=0 or x.sport_key is null or x.sport_key=any(sr.sport_keys))order by x.created_at desc,x.id limit 12)m),'[]')else'[]'::jsonb end,
  'presentation',sr.presentation,'privacy',jsonb_build_object('unlisted',true,'searchable',false,'contact_details_exposed',false))into response;
 return response;
end$$;

revoke all on function public.boss_athlete_profile_read(uuid,uuid),public.boss_athlete_profile_navigation(),public.boss_recruiting_showcase_read(text)from public,anon,authenticated,service_role;
alter function public.boss_athlete_profile_read(uuid,uuid)set schema boss_private;
alter function boss_private.boss_athlete_profile_read(uuid,uuid)rename to athlete_profile_read;
alter function public.boss_athlete_profile_navigation()set schema boss_private;
alter function boss_private.boss_athlete_profile_navigation()rename to athlete_profile_navigation;
alter function public.boss_recruiting_showcase_read(text)set schema boss_private;
alter function boss_private.boss_recruiting_showcase_read(text)rename to recruiting_showcase_read;
create schema boss_recruiting_public authorization postgres;
revoke all on schema boss_recruiting_public from public,anon,authenticated,service_role;
grant usage on schema boss_recruiting_public to anon,authenticated;
alter default privileges for role postgres in schema boss_recruiting_public revoke all on functions from public,anon,authenticated,service_role;
alter function boss_private.recruiting_showcase_read(text)set schema boss_recruiting_public;
revoke all on function boss_private.athlete_profile_read(uuid,uuid),boss_private.athlete_profile_navigation()from public,anon,authenticated,service_role;
revoke all on function boss_recruiting_public.recruiting_showcase_read(text)from public,anon,authenticated,service_role;
grant execute on function boss_private.athlete_profile_read(uuid,uuid),boss_private.athlete_profile_navigation()to authenticated;
grant execute on function boss_recruiting_public.recruiting_showcase_read(text)to anon,authenticated;
create function public.boss_athlete_profile_read(p_profile_id uuid default null,p_participant_id uuid default null)returns jsonb language sql volatile security invoker set search_path=''as $$select boss_private.athlete_profile_read(p_profile_id,p_participant_id)$$;
create function public.boss_athlete_profile_navigation()returns boolean language sql volatile security invoker set search_path=''as $$select boss_private.athlete_profile_navigation()$$;
create function public.boss_recruiting_showcase_read(p_token_digest text)returns jsonb language sql volatile security invoker set search_path=''as $$select boss_recruiting_public.recruiting_showcase_read(p_token_digest)$$;
revoke all on function public.boss_athlete_profile_read(uuid,uuid),public.boss_athlete_profile_navigation(),public.boss_recruiting_showcase_read(text)from public,anon,authenticated,service_role;
grant execute on function public.boss_athlete_profile_read(uuid,uuid),public.boss_athlete_profile_navigation()to authenticated;
grant execute on function public.boss_recruiting_showcase_read(text)to anon,authenticated;
