-- Shared optional-input expectations. Canonical sport engines remain owners of facts.
create table public.game_stat_catalog_versions(
 sport_key text not null references public.game_sports(key),version text not null,
 primary key(sport_key,version),check(version='boss-tracking-v1')
);
create table public.game_stat_catalog_items(
 sport_key text not null,catalog_version text not null,key text not null,
 definition jsonb not null,
 primary key(sport_key,catalog_version,key),
 foreign key(sport_key,catalog_version)references public.game_stat_catalog_versions(sport_key,version),
 check(key~'^[a-z][a-z0-9_]{0,63}$'),
 check(jsonb_typeof(definition)='object'and octet_length(definition::text)<=4096),
 check(definition->>'classification'in('required','optional','derived','advanced'))
);
create table public.game_tracking_profiles(
 id uuid primary key default gen_random_uuid(),sport_key text not null references public.game_sports(key),
 organization_id uuid references public.organizations(id),scope_type text not null,
 unit_id uuid,team_id uuid,season_id uuid,game_id uuid,side text,
 version bigint not null default 0 check(version>=0),status text not null default'active'check(status in('active','inactive')),
 starts_at timestamptz not null default clock_timestamp(),ends_at timestamptz,
 unique(id,sport_key),
 foreign key(organization_id,unit_id)references public.organization_units(organization_id,id),
 foreign key(organization_id,team_id)references public.teams(organization_id,id),
 foreign key(organization_id,season_id)references public.seasons(organization_id,id),
 foreign key(organization_id,game_id)references public.games(organization_id,id),
 check(isfinite(starts_at)and(ends_at is null or isfinite(ends_at)and ends_at>starts_at)),
 check((scope_type='platform'and organization_id is null and unit_id is null and team_id is null and season_id is null and game_id is null and side is null)
 or(scope_type='organization'and organization_id is not null and unit_id is null and team_id is null and season_id is null and game_id is null and side is null)
 or(scope_type='organization_unit'and organization_id is not null and unit_id is not null and team_id is null and season_id is null and game_id is null and side is null)
 or(scope_type='team'and organization_id is not null and unit_id is null and team_id is not null and season_id is null and game_id is null and side is null)
 or(scope_type='season'and organization_id is not null and unit_id is null and team_id is not null and season_id is not null and game_id is null and side is null)
 or(scope_type='game'and organization_id is not null and unit_id is null and team_id is null and season_id is null and game_id is not null and side in('primary','opponent')))
);
create unique index tracking_profile_scope_idx on public.game_tracking_profiles(sport_key,scope_type,organization_id,unit_id,team_id,season_id,game_id,side) nulls not distinct;
create index tracking_profile_team_idx on public.game_tracking_profiles(organization_id,team_id);
create index tracking_profile_unit_idx on public.game_tracking_profiles(organization_id,unit_id);
create index tracking_profile_season_idx on public.game_tracking_profiles(organization_id,season_id);
create index tracking_profile_game_idx on public.game_tracking_profiles(organization_id,game_id);
create table public.game_tracking_profile_revisions(
 id uuid primary key default gen_random_uuid(),profile_id uuid not null,sport_key text not null,
 version bigint not null check(version>0),catalog_version text not null,
 selection jsonb not null,actor_person_id uuid references public.people(id),request_id uuid,created_at timestamptz not null default clock_timestamp(),
 unique(profile_id,version),unique(id,sport_key),
 foreign key(profile_id,sport_key)references public.game_tracking_profiles(id,sport_key),
 foreign key(sport_key,catalog_version)references public.game_stat_catalog_versions(sport_key,version),
 check(jsonb_typeof(selection)='object'and octet_length(selection::text)<=16384)
);
create index tracking_revision_profile_idx on public.game_tracking_profile_revisions(profile_id,sport_key);
create index tracking_revision_catalog_idx on public.game_tracking_profile_revisions(sport_key,catalog_version);
create index tracking_revision_actor_idx on public.game_tracking_profile_revisions(actor_person_id);
create table public.game_tracking_snapshots(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,game_id uuid not null,
 side text not null check(side in('primary','opponent')),sport_key text not null,catalog_version text not null,
 roster_revision bigint not null check(roster_revision>0),effective_sequence bigint not null check(effective_sequence>0),
 selection jsonb not null,provenance jsonb not null,
 created_at timestamptz not null default clock_timestamp(),
 unique(game_id,side,effective_sequence),unique(organization_id,game_id,id),
 foreign key(organization_id,game_id)references public.games(organization_id,id),
 foreign key(sport_key,catalog_version)references public.game_stat_catalog_versions(sport_key,version),
 check(jsonb_typeof(selection)='object'and octet_length(selection::text)<=16384),
 check(jsonb_typeof(provenance)='array'and jsonb_array_length(provenance)<=6)
);
create index tracking_snapshot_catalog_idx on public.game_tracking_snapshots(sport_key,catalog_version);
create table public.game_stat_coverage_intervals(
 snapshot_id uuid not null,organization_id uuid not null,game_id uuid not null,
 stat_key text not null,enabled boolean not null,
 primary key(snapshot_id,stat_key),
 foreign key(organization_id,game_id,snapshot_id)references public.game_tracking_snapshots(organization_id,game_id,id)
);
create index tracking_coverage_context_idx on public.game_stat_coverage_intervals(organization_id,game_id,snapshot_id);
create table public.game_finalization_tracking_seals(
 finalization_id uuid not null,organization_id uuid not null,game_id uuid not null,
 side text not null check(side in('primary','opponent')),snapshot_id uuid not null,
 cutoff bigint not null check(cutoff>0),coverage jsonb not null,
 primary key(finalization_id,side),
 foreign key(organization_id,game_id,finalization_id)references public.game_finalizations(organization_id,game_id,id),
 foreign key(organization_id,game_id,snapshot_id)references public.game_tracking_snapshots(organization_id,game_id,id),
 check(jsonb_typeof(coverage)='object'and octet_length(coverage::text)<=32768)
);
create index tracking_seal_context_idx on public.game_finalization_tracking_seals(organization_id,game_id,finalization_id);
create index tracking_seal_snapshot_idx on public.game_finalization_tracking_seals(organization_id,game_id,snapshot_id);
do $$declare t text;begin
 foreach t in array array['game_stat_catalog_versions','game_stat_catalog_items','game_tracking_profiles','game_tracking_profile_revisions','game_tracking_snapshots','game_stat_coverage_intervals','game_finalization_tracking_seals']loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on public.%I from public,anon,authenticated,service_role',t);
 if t<>'game_tracking_profiles'then
 execute format('create trigger %I before update or delete on public.%I for each row execute function boss_private.reject_audit_rewrite()',t||'_immutable',t);
 execute format('create trigger %I before truncate on public.%I execute function boss_private.reject_audit_rewrite()',t||'_no_truncate',t);end if;end loop;
end$$;
create trigger tracking_profile_identity before update on public.game_tracking_profiles for each row execute function boss_private.preserve_row_identity('id','sport_key','organization_id','scope_type','unit_id','team_id','season_id','game_id','side');

create function boss_private.tracking_selection(sport text,preset text,selected jsonb default'[]',quick jsonb default null)returns jsonb
language plpgsql stable security definer set search_path=''as $$
declare enabled text[];seed text[];ordered text[];k text;deps text[];d public.game_stat_catalog_items;changed boolean;begin
 if sport not in('basketball','soccer','football','volleyball')or sport is null or preset is null or preset not in('score_only','essential','standard','advanced','full','custom')or jsonb_typeof(selected)is distinct from'array'or jsonb_array_length(selected)>128 then raise exception 'Invalid tracking selection'using errcode='PT422';end if;
 if preset<>'custom'and jsonb_array_length(selected)>0 then raise exception 'Preset contains custom selections'using errcode='PT422';end if;
 if preset='custom'then select coalesce(array_agg(value),'{}')into seed from jsonb_array_elements_text(selected);
 elsif preset='score_only'then seed:='{}';
 elsif preset='essential'then seed:=case sport
 when'basketball'then array['player_attribution','assists','offensive_rebounds','defensive_rebounds']
 when'soccer'then array['player_attribution','assists','shots','saves']
 when'football'then array['player_attribution','quick_rush','quick_pass_complete','quick_pass_incomplete']
 else array['player_attribution','kills','assists','digs','service_aces','service_errors','solo_blocks','block_assists']end;
 else select array_agg(key order by(definition->>'order')::integer)into seed from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and definition->>'classification'='optional'and(definition->>'available')::boolean;end if;
 if(select count(distinct v)from unnest(seed)v)<>cardinality(seed)then raise exception 'Duplicate tracking selection'using errcode='PT422';end if;
 select array_agg(key order by(definition->>'order')::integer)into enabled from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and definition->>'classification'='required';
 enabled:=coalesce(enabled,'{}')||seed;
 -- Dependency closure has a strict catalog-size bound and no client formulas.
 for iteration in 1..128 loop
 changed:=false;
 foreach k in array enabled loop
 select *into d from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and key=k;
 if not found or not coalesce((d.definition->>'available')::boolean,false)then raise exception 'Unsupported tracking statistic'using errcode='PT422';end if;
 for k in select value from jsonb_array_elements_text(d.definition->'dependencies')loop
 if not k=any(enabled)then enabled:=array_append(enabled,k);changed:=true;end if;end loop;end loop;
 for d in select *from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and definition->>'classification'='derived'loop
 select coalesce(array_agg(value),'{}')into deps from jsonb_array_elements_text(d.definition->'dependencies');
 if cardinality(deps)>0 and deps<@enabled and not d.key=any(enabled)then enabled:=array_append(enabled,d.key);changed:=true;end if;end loop;
 exit when not changed;
 if iteration=128 then raise exception 'Invalid tracking dependencies'using errcode='PT422';end if;
 end loop;
 if quick is null then
 select coalesce(array_agg(x.key order by x.ord),'{}')into ordered from(select s.key,s.ord from unnest(seed)with ordinality s(key,ord)join public.game_stat_catalog_items c on c.sport_key=sport and c.catalog_version='boss-tracking-v1'and c.key=s.key where(c.definition->>'quick_eligible')::boolean order by s.ord limit 8)x;
 else
 if jsonb_typeof(quick)is distinct from'array'or jsonb_array_length(quick)>8 then raise exception 'Invalid Quick Stats'using errcode='PT422';end if;
 select coalesce(array_agg(value),'{}')into ordered from jsonb_array_elements_text(quick);
 end if;
 if(select count(distinct v)from unnest(ordered)v)<>cardinality(ordered)then raise exception 'Duplicate Quick Stats'using errcode='PT422';end if;
 foreach k in array ordered loop
 if not k=any(enabled)or not exists(select 1 from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and key=k and(definition->>'quick_eligible')::boolean)then raise exception 'Invalid Quick Stats'using errcode='PT422';end if;end loop;
 select array_agg(key order by(definition->>'order')::integer)into enabled from public.game_stat_catalog_items where sport_key=sport and catalog_version='boss-tracking-v1'and key=any(enabled);
 return jsonb_build_object('catalog_version','boss-tracking-v1','preset',preset,'enabled',to_jsonb(enabled),'quick',to_jsonb(ordered));
end$$;

create function boss_private.tracking_resolve(g public.games,p_side text)returns jsonb
language plpgsql volatile security definer set search_path=''as $$
declare t public.teams;r record;selection jsonb;provenance jsonb:='[]';begin
 if p_side is null or p_side not in('primary','opponent')then raise exception 'Invalid tracking side'using errcode='PT422';end if;
 select *into t from public.teams where id=case p_side when'primary'then g.primary_team_id else g.opponent_team_id end and organization_id=g.organization_id;
 selection:=boss_private.tracking_selection(g.sport_key,'score_only');
 for r in select p.*,v.id revision_id,v.selection from public.game_tracking_profiles p join public.game_tracking_profile_revisions v on v.profile_id=p.id and v.version=p.version
 where p.sport_key=g.sport_key and p.status='active'and p.starts_at<=clock_timestamp()and(p.ends_at is null or p.ends_at>clock_timestamp())
 and(p.scope_type='platform'or p.organization_id=g.organization_id and(
 p.scope_type='organization'or p.scope_type='organization_unit'and p.unit_id=t.parent_unit_id
 or p.scope_type='team'and p.team_id=t.id or p.scope_type='season'and p.team_id=t.id and p.season_id=t.season_id
 or p.scope_type='game'and p.game_id=g.id and p.side=p_side))
 order by case p.scope_type when'platform'then 0 when'organization'then 1 when'organization_unit'then 2 when'team'then 3 when'season'then 4 else 5 end
 loop selection:=r.selection;provenance:=provenance||jsonb_build_array(jsonb_build_object('profile_id',r.id,'revision_id',r.revision_id,'version',r.version,'scope_type',r.scope_type));end loop;
 return jsonb_build_object('selection',selection,'provenance',provenance);
end$$;

create function boss_private.tracking_snapshot(g public.games,p_side text,p_sequence bigint)returns uuid
language plpgsql volatile security definer set search_path=''as $$
declare resolved jsonb;sid uuid:=gen_random_uuid();begin
 resolved:=boss_private.tracking_resolve(g,p_side);
 insert into public.game_tracking_snapshots(id,organization_id,game_id,side,sport_key,catalog_version,roster_revision,effective_sequence,selection,provenance)
 values(sid,g.organization_id,g.id,p_side,g.sport_key,'boss-tracking-v1',g.roster_revision,p_sequence,resolved->'selection',resolved->'provenance');
 insert into public.game_stat_coverage_intervals(snapshot_id,organization_id,game_id,stat_key,enabled)
 select sid,g.organization_id,g.id,key,(resolved->'selection'->'enabled')?key from public.game_stat_catalog_items where sport_key=g.sport_key and catalog_version='boss-tracking-v1';
 return sid;
end$$;
create function boss_private.tracking_current(p_game uuid,p_side text)returns public.game_tracking_snapshots
language sql stable security definer set search_path=''as $$select *from public.game_tracking_snapshots where game_id=p_game and side=p_side order by effective_sequence desc limit 1$$;
create function boss_private.tracking_enabled(p_game uuid,p_side text,p_key text)returns boolean
language sql stable security definer set search_path=''as $$select coalesce((boss_private.tracking_current(p_game,p_side)).selection->'enabled'?p_key,false)$$;

create function boss_private.tracking_coverage(p_game uuid,p_side text,p_cutoff bigint)returns jsonb
language sql stable security definer set search_path=''as $$
 with boundary as(select coalesce((select min(sequence)from public.game_operations where game_id=p_game and operation='game.start'),(select min(effective_sequence)from public.game_tracking_snapshots where game_id=p_game and side=p_side))start_sequence),anchor as(
 select s.id from public.game_tracking_snapshots s cross join boundary b where s.game_id=p_game and s.side=p_side and s.effective_sequence<=b.start_sequence order by s.effective_sequence desc limit 1
 ),states as(
 select c.stat_key,bool_and(c.enabled)all_enabled,bool_or(c.enabled)any_enabled from public.game_stat_coverage_intervals c
 join public.game_tracking_snapshots s on s.id=c.snapshot_id cross join boundary b where s.game_id=p_game and s.side=p_side and s.effective_sequence<=p_cutoff and(s.id in(select id from anchor)or s.effective_sequence>b.start_sequence)group by c.stat_key
 )select coalesce(jsonb_object_agg(stat_key,case when all_enabled then'tracked'when not any_enabled then'not_tracked'else'partially_tracked'end),'{}')from states
$$;

create function boss_private.tracking_seal()returns trigger language plpgsql security definer set search_path=''as $$
declare s public.game_tracking_snapshots;begin
 for s in select distinct on(side)*from public.game_tracking_snapshots where game_id=new.game_id and effective_sequence<=new.operation_sequence order by side,effective_sequence desc loop
 insert into public.game_finalization_tracking_seals(finalization_id,organization_id,game_id,side,snapshot_id,cutoff,coverage)
 values(new.id,new.organization_id,new.game_id,s.side,s.id,new.operation_sequence,case when s.sport_key='volleyball'then boss_private.volleyball_team_coverage(new.game_id,s.side,new.operation_sequence)else boss_private.tracking_coverage(new.game_id,s.side,new.operation_sequence)end||case when s.sport_key='volleyball'then jsonb_build_object('player_stat_coverage',boss_private.volleyball_player_coverage(new.game_id,s.side,new.operation_sequence))else'{}'::jsonb end);end loop;return new;
end$$;
create trigger game_tracking_finalization_seal after insert on public.game_finalizations for each row execute function boss_private.tracking_seal();
do $$declare f record;begin for f in select p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='boss_private'and p.proname like'tracking_%'loop
 execute format('revoke all on function %s from public,anon,authenticated,service_role',f.signature);end loop;end$$;

-- Finite catalog shared with reviewed console adapters.
insert into public.game_stat_catalog_versions(sport_key,version) values('basketball','boss-tracking-v1');
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','scoring','{"key":"scoring","label":"scoring","short_label":"Score","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["made_2","made_3","made_ft"],"prompts":["assists"],"order":0,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','game_state','{"key":"game_state","label":"game state","short_label":"game state","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["period_start","period_end","clock_start","clock_stop","lineup_set","substitution"],"prompts":[],"order":1,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','points','{"key":"points","label":"points","short_label":"points","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["scoring"],"actions":[],"prompts":[],"order":10,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','offensive_rebounds','{"key":"offensive_rebounds","label":"offensive rebounds","short_label":"offensive rebounds","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["offensive_rebound"],"prompts":[],"order":11,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','defensive_rebounds','{"key":"defensive_rebounds","label":"defensive rebounds","short_label":"defensive rebounds","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["defensive_rebound"],"prompts":[],"order":12,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','rebounds','{"key":"rebounds","label":"rebounds","short_label":"rebounds","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["offensive_rebounds","defensive_rebounds"],"actions":[],"prompts":[],"order":13,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','assists','{"key":"assists","label":"assists","short_label":"assists","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["assist"],"prompts":[],"order":14,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','steals','{"key":"steals","label":"steals","short_label":"steals","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["steal"],"prompts":[],"order":15,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','blocks','{"key":"blocks","label":"blocks","short_label":"blocks","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["block"],"prompts":[],"order":16,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','turnovers','{"key":"turnovers","label":"turnovers","short_label":"turnovers","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["turnover"],"prompts":[],"order":17,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','personal_fouls','{"key":"personal_fouls","label":"personal fouls","short_label":"personal fouls","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["personal_foul"],"prompts":[],"order":18,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','fgm','{"key":"fgm","label":"fgm","short_label":"fgm","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["scoring"],"actions":[],"prompts":[],"order":19,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','fga','{"key":"fga","label":"fga","short_label":"fga","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["missed_2","missed_3"],"prompts":["offensive_rebounds","defensive_rebounds"],"order":20,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','tpm','{"key":"tpm","label":"tpm","short_label":"tpm","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["scoring"],"actions":[],"prompts":[],"order":21,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','tpa','{"key":"tpa","label":"tpa","short_label":"tpa","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["fga"],"actions":[],"prompts":[],"order":22,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','ftm','{"key":"ftm","label":"ftm","short_label":"ftm","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["scoring"],"actions":[],"prompts":[],"order":23,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','fta','{"key":"fta","label":"fta","short_label":"fta","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["missed_ft"],"prompts":[],"order":24,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','player_attribution','{"key":"player_attribution","label":"player attribution","short_label":"player attribution","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":[],"prompts":[],"order":40,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('basketball','boss-tracking-v1','shooting_percentage','{"key":"shooting_percentage","label":"shooting percentage","short_label":"shooting percentage","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["fgm","fga"],"actions":[],"prompts":[],"order":41,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_versions(sport_key,version) values('soccer','boss-tracking-v1');
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','scoring','{"key":"scoring","label":"scoring","short_label":"Goal","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["goal","penalty_goal","own_goal"],"prompts":["assists"],"order":0,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','game_state','{"key":"game_state","label":"game state","short_label":"game state","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["segment_start","segment_end","clock_start","clock_stop","lineup_set","keeper_set","substitution"],"prompts":[],"order":1,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','goals','{"key":"goals","label":"goals","short_label":"goals","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["scoring"],"actions":[],"prompts":[],"order":10,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','own_goals','{"key":"own_goals","label":"own goals","short_label":"own goals","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["scoring"],"actions":[],"prompts":[],"order":11,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','assists','{"key":"assists","label":"assists","short_label":"assists","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["assist"],"prompts":[],"order":12,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','shots','{"key":"shots","label":"shots","short_label":"shots","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["shot_off_target","shot_saved","shot_blocked","penalty_miss","penalty_saved"],"prompts":[],"order":13,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','shots_on_goal','{"key":"shots_on_goal","label":"shots on goal","short_label":"shots on goal","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["shots"],"actions":[],"prompts":[],"order":14,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','saves','{"key":"saves","label":"saves","short_label":"saves","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["shot_saved","penalty_saved"],"prompts":[],"order":15,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','yellow_cards','{"key":"yellow_cards","label":"yellow cards","short_label":"yellow cards","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["yellow_card","second_yellow"],"prompts":[],"order":16,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','red_cards','{"key":"red_cards","label":"red cards","short_label":"red cards","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["red_card"],"prompts":[],"order":17,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','fouls','{"key":"fouls","label":"fouls","short_label":"fouls","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["foul"],"prompts":[],"order":18,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('soccer','boss-tracking-v1','player_attribution','{"key":"player_attribution","label":"player attribution","short_label":"player attribution","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":[],"prompts":[],"order":40,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_versions(sport_key,version) values('football','boss-tracking-v1');
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','play_state','{"key":"play_state","label":"play state","short_label":"Play","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["rush","pass_complete","pass_incomplete","sack","kneel","spike","interception","fumble","fumble_recovery","turnover_on_downs","kickoff","kickoff_return","punt","punt_return","field_goal","extra_point","two_point","safety","penalty","touchdown"],"prompts":[],"order":0,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','game_state','{"key":"game_state","label":"game state","short_label":"game state","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["period_start","period_end","clock_start","clock_stop","state_set","lineup_set","substitution"],"prompts":[],"order":1,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','points','{"key":"points","label":"points","short_label":"points","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":10,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','passing_completions','{"key":"passing_completions","label":"passing completions","short_label":"passing completions","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":11,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','passing_attempts','{"key":"passing_attempts","label":"passing attempts","short_label":"passing attempts","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":12,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','passing_yards','{"key":"passing_yards","label":"passing yards","short_label":"passing yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":13,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','passing_touchdowns','{"key":"passing_touchdowns","label":"passing touchdowns","short_label":"passing touchdowns","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":14,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','interceptions_thrown','{"key":"interceptions_thrown","label":"interceptions thrown","short_label":"interceptions thrown","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":15,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','sacks_taken','{"key":"sacks_taken","label":"sacks taken","short_label":"sacks taken","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":16,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','sack_yards_lost','{"key":"sack_yards_lost","label":"sack yards lost","short_label":"sack yards lost","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":17,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','rush_attempts','{"key":"rush_attempts","label":"rush attempts","short_label":"rush attempts","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":18,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','rushing_yards','{"key":"rushing_yards","label":"rushing yards","short_label":"rushing yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":19,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','rushing_touchdowns','{"key":"rushing_touchdowns","label":"rushing touchdowns","short_label":"rushing touchdowns","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":20,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','long_rush','{"key":"long_rush","label":"long rush","short_label":"long rush","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":21,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','receptions','{"key":"receptions","label":"receptions","short_label":"receptions","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":22,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','targets','{"key":"targets","label":"targets","short_label":"targets","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":23,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','receiving_yards','{"key":"receiving_yards","label":"receiving yards","short_label":"receiving yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":24,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','receiving_touchdowns','{"key":"receiving_touchdowns","label":"receiving touchdowns","short_label":"receiving touchdowns","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":25,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','long_reception','{"key":"long_reception","label":"long reception","short_label":"long reception","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":26,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','fumbles','{"key":"fumbles","label":"fumbles","short_label":"fumbles","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":27,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','fumbles_lost','{"key":"fumbles_lost","label":"fumbles lost","short_label":"fumbles lost","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":28,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','solo_tackles','{"key":"solo_tackles","label":"solo tackles","short_label":"solo tackles","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":29,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','assisted_tackles','{"key":"assisted_tackles","label":"assisted tackles","short_label":"assisted tackles","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":30,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','tackles','{"key":"tackles","label":"tackles","short_label":"tackles","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":31,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','tackles_for_loss','{"key":"tackles_for_loss","label":"tackles for loss","short_label":"tackles for loss","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":32,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','sacks','{"key":"sacks","label":"sacks","short_label":"sacks","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":33,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','defensive_interceptions','{"key":"defensive_interceptions","label":"defensive interceptions","short_label":"defensive interceptions","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":34,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','interception_return_yards','{"key":"interception_return_yards","label":"interception return yards","short_label":"interception return yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":35,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','pass_defenses','{"key":"pass_defenses","label":"pass defenses","short_label":"pass defenses","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":36,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','forced_fumbles','{"key":"forced_fumbles","label":"forced fumbles","short_label":"forced fumbles","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":37,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','fumble_recoveries','{"key":"fumble_recoveries","label":"fumble recoveries","short_label":"fumble recoveries","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":38,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','fumble_return_yards','{"key":"fumble_return_yards","label":"fumble return yards","short_label":"fumble return yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":39,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','defensive_touchdowns','{"key":"defensive_touchdowns","label":"defensive touchdowns","short_label":"defensive touchdowns","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":40,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','field_goals_made','{"key":"field_goals_made","label":"field goals made","short_label":"field goals made","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":41,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','field_goals_attempted','{"key":"field_goals_attempted","label":"field goals attempted","short_label":"field goals attempted","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":42,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','long_field_goal','{"key":"long_field_goal","label":"long field goal","short_label":"long field goal","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":43,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','extra_points_made','{"key":"extra_points_made","label":"extra points made","short_label":"extra points made","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":44,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','extra_points_attempted','{"key":"extra_points_attempted","label":"extra points attempted","short_label":"extra points attempted","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":45,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','punts','{"key":"punts","label":"punts","short_label":"punts","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":46,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','punt_yards','{"key":"punt_yards","label":"punt yards","short_label":"punt yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":47,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','long_punt','{"key":"long_punt","label":"long punt","short_label":"long punt","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":48,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','punt_touchbacks','{"key":"punt_touchbacks","label":"punt touchbacks","short_label":"punt touchbacks","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":49,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','kick_returns','{"key":"kick_returns","label":"kick returns","short_label":"kick returns","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":50,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','kick_return_yards','{"key":"kick_return_yards","label":"kick return yards","short_label":"kick return yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":51,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','kick_return_touchdowns','{"key":"kick_return_touchdowns","label":"kick return touchdowns","short_label":"kick return touchdowns","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":52,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','long_kick_return','{"key":"long_kick_return","label":"long kick return","short_label":"long kick return","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":53,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','punt_returns','{"key":"punt_returns","label":"punt returns","short_label":"punt returns","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":54,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','punt_return_yards','{"key":"punt_return_yards","label":"punt return yards","short_label":"punt return yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":55,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','punt_return_touchdowns','{"key":"punt_return_touchdowns","label":"punt return touchdowns","short_label":"punt return touchdowns","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":56,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','long_punt_return','{"key":"long_punt_return","label":"long punt return","short_label":"long punt return","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":57,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','first_downs','{"key":"first_downs","label":"first downs","short_label":"first downs","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":58,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','penalties','{"key":"penalties","label":"penalties","short_label":"penalties","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":59,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','penalty_yards','{"key":"penalty_yards","label":"penalty yards","short_label":"penalty yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":60,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','turnovers','{"key":"turnovers","label":"turnovers","short_label":"turnovers","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":61,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','turnovers_on_downs','{"key":"turnovers_on_downs","label":"turnovers on downs","short_label":"turnovers on downs","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":62,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','net_passing_yards','{"key":"net_passing_yards","label":"net passing yards","short_label":"net passing yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":63,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','total_offensive_yards','{"key":"total_offensive_yards","label":"total offensive yards","short_label":"total offensive yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":64,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','return_yards','{"key":"return_yards","label":"return yards","short_label":"return yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":65,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','kneels','{"key":"kneels","label":"kneels","short_label":"kneels","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":66,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','kneel_yards','{"key":"kneel_yards","label":"kneel yards","short_label":"kneel yards","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":67,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','conversion_attempts','{"key":"conversion_attempts","label":"conversion attempts","short_label":"conversion attempts","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":68,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','conversions_made','{"key":"conversions_made","label":"conversions made","short_label":"conversions made","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":69,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','safeties','{"key":"safeties","label":"safeties","short_label":"safeties","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":70,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','touchdowns','{"key":"touchdowns","label":"touchdowns","short_label":"touchdowns","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["play_state"],"actions":[],"prompts":[],"order":71,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','player_attribution','{"key":"player_attribution","label":"player attribution","short_label":"player attribution","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":[],"prompts":[],"order":80,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','quick_rush','{"key":"quick_rush","label":"quick rush","short_label":"rush","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["play_state"],"actions":["rush"],"prompts":[],"order":81,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','quick_pass_complete','{"key":"quick_pass_complete","label":"quick pass complete","short_label":"pass complete","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["play_state"],"actions":["pass_complete"],"prompts":[],"order":82,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','quick_pass_incomplete','{"key":"quick_pass_incomplete","label":"quick pass incomplete","short_label":"pass incomplete","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["play_state"],"actions":["pass_incomplete"],"prompts":[],"order":83,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','quick_punt','{"key":"quick_punt","label":"quick punt","short_label":"punt","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["play_state"],"actions":["punt"],"prompts":[],"order":84,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','quick_field_goal','{"key":"quick_field_goal","label":"quick field goal","short_label":"field goal","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["play_state"],"actions":["field_goal"],"prompts":[],"order":85,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('football','boss-tracking-v1','quick_penalty','{"key":"quick_penalty","label":"quick penalty","short_label":"penalty","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["play_state"],"actions":["penalty"],"prompts":[],"order":86,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_versions(sport_key,version) values('volleyball','boss-tracking-v1');
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','rally','{"key":"rally","label":"rally","short_label":"Point","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["team_point"],"prompts":[],"order":0,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','set_state','{"key":"set_state","label":"set state","short_label":"Set","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["set_start"],"prompts":[],"order":1,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','service_state','{"key":"service_state","label":"service state","short_label":"Serve","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":[],"prompts":[],"order":2,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','participation','{"key":"participation","label":"participation","short_label":"Court","category":"game_state","classification":"required","available":true,"default_enabled":true,"modes":["action_first","player_first"],"dependencies":[],"actions":["lineup_set","substitution"],"prompts":[],"order":3,"scopes":["game"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','kills','{"key":"kills","label":"kills","short_label":"Kill","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["attack_attempts"],"actions":["kill"],"prompts":["assists"],"order":10,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','attack_attempts','{"key":"attack_attempts","label":"attack attempts","short_label":"Attack","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["attack_attempt"],"prompts":[],"order":11,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','attack_errors','{"key":"attack_errors","label":"attack errors","short_label":"Attack error","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["attack_attempts"],"actions":["attack_error"],"prompts":[],"order":12,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','hitting_percentage','{"key":"hitting_percentage","label":"hitting percentage","short_label":"hitting percentage","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["kills","attack_attempts","attack_errors"],"actions":[],"prompts":[],"order":13,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','assists','{"key":"assists","label":"assists","short_label":"Assist","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["kills"],"actions":["assist"],"prompts":[],"order":14,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','digs','{"key":"digs","label":"digs","short_label":"Dig","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["dig"],"prompts":[],"order":15,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','service_attempts','{"key":"service_attempts","label":"service attempts","short_label":"service attempts","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["service_state","rally"],"actions":[],"prompts":[],"order":16,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','service_aces','{"key":"service_aces","label":"service aces","short_label":"Ace","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["ace"],"prompts":[],"order":17,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','service_errors','{"key":"service_errors","label":"service errors","short_label":"Service error","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["service_error"],"prompts":[],"order":18,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','solo_blocks','{"key":"solo_blocks","label":"solo blocks","short_label":"Solo block","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["solo_block"],"prompts":[],"order":19,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','block_assists','{"key":"block_assists","label":"block assists","short_label":"Assisted block","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["assisted_block"],"prompts":[],"order":20,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','blocks','{"key":"blocks","label":"blocks","short_label":"blocks","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["solo_blocks","block_assists"],"actions":[],"prompts":[],"order":21,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','blocking_errors','{"key":"blocking_errors","label":"blocking errors","short_label":"Block error","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["blocking_error"],"prompts":[],"order":22,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','receptions','{"key":"receptions","label":"receptions","short_label":"Reception","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":["reception"],"prompts":[],"order":23,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','reception_errors','{"key":"reception_errors","label":"reception errors","short_label":"Reception error","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":["receptions"],"actions":["reception_error"],"prompts":[],"order":24,"scopes":["team","player"],"quick_eligible":true}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','points','{"key":"points","label":"points","short_label":"points","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["rally"],"actions":[],"prompts":[],"order":25,"scopes":["team"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','set_wins','{"key":"set_wins","label":"set wins","short_label":"set wins","category":"derived","classification":"derived","available":true,"default_enabled":false,"modes":[],"dependencies":["set_state"],"actions":[],"prompts":[],"order":26,"scopes":["team"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','player_attribution','{"key":"player_attribution","label":"player attribution","short_label":"Player credit","category":"statistics","classification":"optional","available":true,"default_enabled":false,"modes":["action_first","player_first"],"dependencies":[],"actions":[],"prompts":[],"order":27,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','passing_rating','{"key":"passing_rating","label":"passing rating","short_label":"passing rating","category":"statistics","classification":"advanced","available":false,"default_enabled":false,"modes":[],"dependencies":["receptions"],"actions":[],"prompts":[],"order":90,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
insert into public.game_stat_catalog_items(sport_key,catalog_version,key,definition) values('volleyball','boss-tracking-v1','rotation_efficiency','{"key":"rotation_efficiency","label":"rotation efficiency","short_label":"rotation efficiency","category":"statistics","classification":"advanced","available":false,"default_enabled":false,"modes":[],"dependencies":["rally","participation"],"actions":[],"prompts":[],"order":91,"scopes":["team","player"],"quick_eligible":false}'::jsonb);
