import Image from "next/image";
import Link from "next/link";
import ApprovedHeader from "@/components/ApprovedHeader";
import ApprovedFooter from "@/components/ApprovedFooter";
import home from "../approvedHome.module.css";
import s from "./family-hub.module.css";
export const metadata={title:"Boss Family Hub | Keep It All Together Like a Boss",description:"Multiple kids, teams and organizations. Bring family schedules, individual fundraising progress and eligible family expenses into one connected Boss Family Hub."};
function Art({crop,alt,className,phone}:{crop:string;alt?:string;className?:string;phone?:'hero'|'wallet'}){return <svg viewBox={crop} preserveAspectRatio="xMidYMid slice" role={alt?'img':undefined} aria-label={alt} aria-hidden={alt?undefined:true} className={className}>{phone&&<defs><clipPath id={'family-'+phone}>{phone==='hero'?<rect x="584" y="85" width="198" height="408" rx="32"/>:<rect x="367" y="1368" width="160" height="291" rx="25"/>}</clipPath></defs>}<image href="/design/family-hub-approved.png" width="797" height="1974" clipPath={phone?'url(#family-'+phone+')':undefined}/></svg>}
function Icon({kind}:{kind:string}){return <svg viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='calendar'?<><rect x="4" y="6" width="24" height="23" rx="2"/><path d="M4 13h24M10 2v8m12-8v8M10 18h3m6 0h3m-12 6h3m6 0h3"/></>:kind==='organization'?<><path d="M8 29V3h16v26M2 29h28M12 8h1m6 0h1m-8 6h1m6 0h1M13 29v-8h6v8"/></>:kind==='gear'?<path d="m10 4-8 5 4 7 4-2v15h12V14l4 2 4-7-8-5c0 7-12 7-12 0Z"/>:kind==='camp'?<path d="m3 28 13-24 13 24H3Zm8 0 5-10 5 10M13 3l6 1"/>:kind==='travel'?<path d="m3 14 11 1 9-10c5-4 7-2 4 3l-9 10 1 11-4-1-3-8-8-3-1-3Z"/>:kind==='fees'?<path d="M5 7h8l4 11 10 3c3 1 3 7 0 7H4V16Zm0 15h20M14 14l-4 3m7 1-4 3"/>:<><circle cx="16" cy="9" r="4"/><path d="M9 28v-8c0-7 14-7 14 0v8H9Z"/><circle cx="5" cy="11" r="3"/><circle cx="27" cy="11" r="3"/><path d="M2 27v-8h4m24 8v-8h-4"/></>}</svg>}
export default function Page(){return <div className={home.home}><a href="#main-content" className={home.skipLink}>Skip to content</a><ApprovedHeader/><main id="main-content" className={s.page}>
<section className={s.hero} aria-labelledby="family-title"><Image src="/images/approved/family-hub-hero.png" alt="Parents with a teenage softball player and younger basketball player in BOSS jerseys" fill priority sizes="100vw" className={s.heroPhoto}/><div className={s.heroCopy}><p className={s.eyebrow}>BOSS FAMILY HUB</p><h1 id="family-title">Keep it all<br/>together<br/><span>like a Boss.</span></h1><p className={s.heroLead}>Multiple kids. Multiple teams.<br/>Multiple organizations.<br/>One connected family.</p><div className={s.actions}><a href="#family-features" className={s.button}>Explore Family Hub</a><a href="#family-calendar" className={s.outline}>See the Family View</a></div></div><figure className={s.heroPhone}><Art crop="581 81 204 415" phone="hero" alt="Illustrative Family Hub app with child and organization filters, school softball, community basketball and a church youth event"/><figcaption>Illustrative product preview.</figcaption></figure></section>
<section id="family-features" className={s.features} aria-labelledby="features-title"><h2 id="features-title">One family. <span>Everything connected.</span></h2><div className={s.featureGrid}>{[['people','Every child','Keep track of all your kids across every team and organization.'],['calendar','Every schedule','See practices, games and events in one place.'],['organization','Every organization','Bring school, club and community activities together.']].map(([kind,title,copy])=><article key={kind}><div className={s.circle}><Icon kind={kind}/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section id="family-calendar" className={s.calendar} aria-labelledby="calendar-title"><figure><Art crop="9 772 509 332" alt="Illustrative family calendar combining Ava’s school softball, Liam’s community basketball and a church youth group event"/><figcaption>Illustrative product preview.</figcaption></figure><div><h2 id="calendar-title">Their schedules.<br/><span>Your whole week.</span></h2><p className={s.sectionLead}>Bring school, club and community activities into one family calendar.</p><ul>{[['Filter by child','Focus on one child or view everyone together.'],['Choose a team or organization','See schedules from school, clubs, church and more.'],['See the whole family at once','A clear view of everyone’s week in one place.']].map(([title,copy])=><li key={title}><b aria-hidden="true">✓</b><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ul></div></section>
<section className={s.fundraising} aria-labelledby="fundraising-title"><div><h2 id="fundraising-title">Every child’s effort.<br/><span>One family view.</span></h2><p className={s.sectionLead}>Give each child a personal fundraising link and QR code. Follow their progress across the teams and organizations they support.</p></div><figure className={s.progressPreview}><div className={s.progressGrid}>{[['Ava','School Softball','BOSS Varsity','354 1144 67 76','488 1256 54 58','40%'],['Liam','Community Basketball','BOSS Basketball Club','574 1144 67 76','713 1256 57 58','58%']].map(([name,sport,team,portrait,qr,progress])=><article key={name}><div className={s.childMeta}><Art crop={portrait}/><div><h3>{name}</h3><p>{sport}<br/>{team}</p></div></div><div className={s.progressTrack} aria-hidden="true"><span style={{width:progress}}/></div><div className={s.sharePreview}><div><strong>{name}’s personal link</strong><span>Example share link <span aria-hidden="true">↗</span></span></div><Art crop={qr}/></div></article>)}</div><figcaption>Illustrative progress and sharing preview. QR codes are examples.</figcaption></figure></section>
<section className={s.wallet} aria-labelledby="wallet-title"><Art crop="530 1353 267 337" alt="A mother with a young tennis player in a BOSS jersey and single-B visor at the courts" className={s.walletPhoto}/><div className={s.walletCopy}><h2 id="wallet-title">One family wallet.<br/><span>More possibilities.</span></h2><p>Bring eligible fundraising credits together for approved family expenses.</p><div className={s.expenses}>{[['fees','Team fees'],['gear','Gear'],['camp','Camps'],['travel','Travel']].map(([kind,title])=><div key={kind}><div className={s.circle}><Icon kind={kind}/></div><h3>{title}</h3></div>)}</div><p className={s.walletRule}>Family credits are for eligible purchases.<br/>Cash redemption is available only to organizations.</p></div><figure className={s.walletPhone}><Art crop="364 1365 166 298" phone="wallet" alt="Illustrative family wallet with eligible expenses for team fees, gear, camps and travel"/><figcaption>Illustrative product preview.</figcaption></figure></section>
<section className={s.finalCta}><h2>Keep it all together <span>like a Boss.</span></h2><p>Help families stay connected across every team and organization.</p><div className={s.actions}><Link href="/get-started" className={s.button}>Get Started <span aria-hidden="true">›</span></Link><Link href="/engage" className={s.textLink}>Explore Boss Engage <span aria-hidden="true">›</span></Link></div><p className={s.vision}>Platform vision. Features and availability vary by program.</p></section>
<section style={{padding:"36px 24px",textAlign:"center",background:"#f6f7f8",color:"#111"}} aria-label="Your Boss Bucks account"><h2 style={{margin:"0 0 12px",fontSize:"1.8rem"}}>One family. More possibilities.</h2><p style={{margin:"0 auto 18px",maxWidth:700,lineHeight:1.6}}>Explore how eligible fundraising credits from participating teams, churches and organizations can help cover approved family expenses.</p><a href="/boss-bucks-account" style={{display:"inline-block",padding:"14px 22px",borderRadius:5,background:"#c63b00",color:"white",fontWeight:700,textDecoration:"none"}}>Explore Your Boss Bucks Account →</a></section></main><ApprovedFooter/></div>}
