"use client";
import { useState } from "react";
import Link from "next/link";
import type { Json } from "@/lib/supabase/database.types";
import { isRecord } from "@/lib/coordination/input";
import type { AchievementData } from "@/lib/achievements/input";
import { AchievementBadges } from "./badges";
import { AchievementActionForm } from "./action-form";
const text = (value: unknown) => typeof value === "string" ? value : "";
const rows = (value: Json | undefined): Record<string, Json>[] => Array.isArray(value) ? value.filter((item): item is Record<string, Json> => isRecord(item)) : [];
const fields = (value: Json | undefined): Record<string, Json> => isRecord(value) ? value as Record<string, Json> : {};
function Select({ name, label, items, optional = false }: { name: string; label: string; items: Record<string, unknown>[]; optional?: boolean }) { return <label className="form-field"><span>{label}</span><select name={name} required={!optional}><option value="">{optional ? "No additional selection" : "Choose..."}</option>{items.map(item => <option key={text(item.id)} value={text(item.id)}>{text(item.name)}</option>)}</select></label>; }
export function AchievementHub({ data, organizationId }: { data: AchievementData; organizationId?: string }) {
  const [source, setSource] = useState("organization_decision"), [sport, setSport] = useState("basketball");
  const manual = data.definitions.filter(d => fields(d.revision).source_kind === "organization_decision" && d.status === "active");
  return <div className="achievement-hub">
    <section><h2>Verified recognition</h2>{data.recognitions.length ? <AchievementBadges items={data.recognitions as unknown as Record<string, Json>[]} /> : <p>No authorized recognitions are available.</p>}{data.next_cursor && <Link href={`/app/achievements?after=${data.next_cursor}${organizationId ? `&org=${organizationId}` : ""}`}>Next recognition page</Link>}</section>
    {data.history.length > 0 && <section className="athlete-profile-panel"><h2>Recognition history</h2><ol className="achievement-history">{data.history.map((h, index) => <li key={index}><strong>{text(h.event_type).replaceAll("_", " ")}</strong><span>{text(h.state)} · revision {String(h.version)}</span><time>{text(h.created_at)}</time></li>)}</ol></section>}
    {organizationId && data.can_manage && <section className="athlete-profile-panel"><h2>Enabled definitions</h2><p>Each revision keeps its original meaning. Automatic recognition uses verified sources; organization awards require a human decision.</p>{data.definitions.map(d => { const rev = fields(d.revision); return <article className="achievement-definition" key={text(d.id)}><h3>{text(rev.name)}</h3><p>{text(rev.source_kind).replaceAll("_", " ")} · {text(d.status)} · revision {String(rev.revision)} · {text(d.freshness)}</p>{d.status === "active" && rev.source_kind !== "organization_decision" && <><AchievementActionForm label={d.has_more ? "Continue evaluation" : "Evaluate verified facts"} build={() => ({ action: "definition.evaluate", input: { definition_id: text(d.id), organization_id: organizationId } })} /><AchievementActionForm label="Rebuild current recognition" build={() => ({ action: "definition.rebuild", input: { definition_id: text(d.id), organization_id: organizationId } })} /></>}{d.status === "active" && rows(d.pending_revisions).map(prior => <AchievementActionForm key={text(prior.id)} label={`Refresh historical definition revision ${String(prior.revision)}`} build={() => ({ action: "definition.evaluate", input: { definition_id: text(d.id), organization_id: organizationId, revision_id: text(prior.id) } })} />)}<AchievementActionForm label={d.status === "active" ? "Deactivate definition" : "Activate definition"} build={() => ({ action: "definition.set_status", input: { definition_id: text(d.id), expected_version: Number(d.version), status: d.status === "active" ? "inactive" : "active" } })} /></article>; })}
      <details><summary>Create an approved definition</summary><AchievementActionForm label="Create definition" build={f => {
        const name = text(f.get("name")), kind = text(f.get("source_kind")), subject = text(f.get("subject_type")), revision: Record<string, Json> = { name, subject_type: subject, source_kind: kind, category: kind === "organization_decision" ? text(f.get("category")) : ["record", "leaderboard", "tournament", "standings"].includes(kind) ? kind : "statistical_milestone", sport_key: text(f.get("sport_key")), badge_icon: kind === "record" ? "record" : "trophy", historical_evaluation: f.get("historical") === "on", showcase_eligible: f.get("showcase") === "on" && !["record", "leaderboard"].includes(kind), approval_required: f.get("approval") === "on" };
        for (const key of ["team_id", "tier"]) if (text(f.get(key))) revision[key] = text(f.get(key));
        if (["athlete_game", "athlete_season", "athlete_career", "team_season"].includes(kind)) { revision.metric_key = text(f.get("metric_key")); revision.threshold = Number(f.get("threshold")); }
        if (["record", "leaderboard"].includes(kind)) revision.ranking_definition_id = text(f.get("source_id"));
        if (kind === "tournament") { revision.bracket_id = text(f.get("source_id")); revision.placement = Number(f.get("placement")); if (subject === "athlete") revision.athlete_championship_policy = "sealed_participation"; }
        if (kind === "standings") { revision.standings_scope_id = text(f.get("source_id")); revision.placement = 1; }
        if (kind === "leaderboard") revision.placement = Number(f.get("placement"));
        return { action: "definition.create", input: { organization_id: organizationId, owner_kind: "organization", definition_key: name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/_+$/g, "").slice(0, 64), revision } };
      }}><label className="form-field"><span>Recognition name</span><input name="name" required maxLength={160} /></label><label className="form-field"><span>Verified source or human decision</span><select name="source_kind" value={source} onChange={e => setSource(e.target.value)}>{["organization_decision", "athlete_game", "athlete_season", "athlete_career", "team_season", "record", "leaderboard", "tournament", "standings"].map(k => <option key={k} value={k}>{k.replaceAll("_", " ")}</option>)}</select></label><label className="form-field"><span>Recipient</span><select name="subject_type" defaultValue="athlete"><option value="athlete">Athlete</option><option value="team">Team</option><option value="organization">Organization</option></select></label><label className="form-field"><span>Sport</span><select name="sport_key" value={sport} onChange={e => setSport(e.target.value)}>{["basketball", "soccer", "football", "volleyball", "baseball", "softball"].map(k => <option key={k}>{k}</option>)}</select></label><Select name="team_id" label="Source team" items={rows(data.catalog.teams)} optional />
      {source === "organization_decision" && <label className="form-field"><span>Award category</span><select name="category">{["mvp", "offensive_player", "defensive_player", "most_improved", "sportsmanship", "leadership", "academic_character", "coachs_award"].map(k => <option key={k} value={k}>{k.replaceAll("_", " ")}</option>)}</select></label>}
      {["athlete_game", "athlete_season", "athlete_career", "team_season"].includes(source) && <><label className="form-field"><span>Verified count metric</span><select name="metric_key" required>{rows(data.catalog.metrics).filter(m => m.sport_key === sport).map(m => <option key={text(m.key)} value={text(m.key)}>{text(m.key).replaceAll("_", " ")}</option>)}</select></label><label className="form-field"><span>Approved threshold</span><input name="threshold" type="number" min="0.001" max="1000000000" step="any" required /></label></>}
      {["record", "leaderboard", "tournament", "standings"].includes(source) && <Select name="source_id" label="Authoritative source" items={rows(source === "tournament" ? data.catalog.brackets : source === "standings" ? data.catalog.standings : data.catalog.ranking_definitions).filter(s => s.sport_key === sport && (!["record", "leaderboard"].includes(source) || s.product === (source === "record" ? "records" : "leaderboard")))} />}
      {["tournament", "leaderboard"].includes(source) && <label className="form-field"><span>Recognition placement</span><select name="placement">{Array.from({ length: source === "tournament" ? 3 : 10 }, (_, i) => <option key={i} value={i + 1}>{i + 1}</option>)}</select></label>}
      <label className="form-field"><span>Optional configured tier</span><select name="tier"><option value="">No tier</option>{["bronze", "silver", "gold", "elite"].map(k => <option key={k}>{k}</option>)}</select></label><label><input name="approval" type="checkbox" defaultChecked /> Require award approval</label><label><input name="historical" type="checkbox" /> Evaluate eligible historical sources</label><label><input name="showcase" type="checkbox" disabled={["record", "leaderboard"].includes(source)} /> Eligible for separate guardian showcase approval</label></AchievementActionForm></details>
      {rows(data.catalog.standings).map(s => <AchievementActionForm key={text(s.id)} label={`Confirm completed champion: ${text(s.name)}`} build={f => ({ action: "standings.close", input: { scope_id: text(s.id), reason: text(f.get("reason")) } })}><label className="form-field"><span>Completion decision reason</span><input name="reason" required maxLength={500} /></label></AchievementActionForm>)}
    </section>}
    {organizationId && data.can_issue && <section className="athlete-profile-panel"><h2>Organization-selected award</h2><p>These honors express an authorized organization decision. They are not automatic statistical facts.</p><AchievementActionForm label="Nominate for award" build={f => { const input: Record<string, Json> = { definition_id: text(f.get("definition_id")), organization_id: organizationId, achieved_at: new Date(`${text(f.get("date"))}T12:00:00Z`).toISOString(), note: text(f.get("note")) }; for (const key of ["team_id", "profile_id"]) if (text(f.get(key))) input[key] = text(f.get(key)); const team = rows(data.catalog.teams).find(t => t.id === input.team_id); if (typeof team?.season_id === "string") input.season_id = team.season_id; return { action: "award.nominate", input }; }}><Select name="definition_id" label="Enabled award" items={manual.map(d => ({ id: d.id, name: fields(d.revision).name }))} /><Select name="team_id" label="Issuing team" items={rows(data.catalog.teams)} optional /><Select name="profile_id" label="Athlete recipient" items={rows(data.catalog.profiles)} optional /><label className="form-field"><span>Achievement date</span><input name="date" type="date" required /></label><label className="form-field"><span>Private decision reason</span><textarea name="note" required maxLength={500} /></label></AchievementActionForm></section>}
    {(data.can_issue || data.can_approve) && data.nominations.map(n => <section className="athlete-profile-panel" key={text(n.id)}><h3>{text(n.name)}</h3><p>{text(n.state)} · organization decision · revision {String(n.version)}</p>{rows(n.decisions).map((d, i) => <p key={i}>{text(d.decision)}: {text(d.private_note)}</p>)}{data.can_approve && ["nominated", "awarded", "revoked"].includes(text(n.state)) && <AchievementActionForm label={n.state === "nominated" ? "Approve award" : n.state === "awarded" ? "Revoke award" : "Restore award"} build={f => ({ action: n.state === "nominated" ? "award.approve" : n.state === "awarded" ? "award.revoke" : "award.restore", input: { nomination_id: text(n.id), expected_version: Number(n.version), note: text(f.get("note")) } })}><label className="form-field"><span>Decision reason</span><input name="note" required maxLength={500} /></label></AchievementActionForm>}</section>)}
  </div>;
}
