export const footballOperations = ["football.configure", "football.period.start", "football.period.end", "football.clock.start", "football.clock.stop", "football.clock.set", "football.state.set", "football.lineup.set", "football.substitute", "football.play.add", "football.play.correct", "football.play.reverse"] as const;
export const footballPlayTypes = ["rush", "pass_complete", "pass_incomplete", "sack", "kneel", "spike", "interception", "fumble", "fumble_recovery", "turnover_on_downs", "kickoff", "kickoff_return", "punt", "punt_return", "field_goal", "extra_point", "two_point", "safety", "penalty", "touchdown"] as const;
export const footballControlTypes = ["engine_configure", "period_start", "period_end", "clock_start", "clock_stop", "clock_set", "state_set", "lineup_set", "substitution", "reversal"] as const;
export const footballStatKeys = ["points", "passing_completions", "passing_attempts", "passing_yards", "passing_touchdowns", "interceptions_thrown", "sacks_taken", "sack_yards_lost", "rush_attempts", "rushing_yards", "rushing_touchdowns", "long_rush", "receptions", "targets", "receiving_yards", "receiving_touchdowns", "long_reception", "fumbles", "fumbles_lost", "solo_tackles", "assisted_tackles", "tackles", "tackles_for_loss", "sacks", "defensive_interceptions", "interception_return_yards", "pass_defenses", "forced_fumbles", "fumble_recoveries", "fumble_return_yards", "defensive_touchdowns", "field_goals_made", "field_goals_attempted", "long_field_goal", "extra_points_made", "extra_points_attempted", "punts", "punt_yards", "long_punt", "punt_touchbacks", "kick_returns", "kick_return_yards", "kick_return_touchdowns", "long_kick_return", "punt_returns", "punt_return_yards", "punt_return_touchdowns", "long_punt_return", "first_downs", "penalties", "penalty_yards", "turnovers", "turnovers_on_downs", "net_passing_yards", "total_offensive_yards", "return_yards", "kneels", "kneel_yards", "conversion_attempts", "conversions_made", "safeties", "touchdowns"] as const;
export const footballSignedStatKeys: readonly string[] = ["passing_yards", "rushing_yards", "receiving_yards", "long_rush", "long_reception", "net_passing_yards", "total_offensive_yards", "kneel_yards"];
export type FootballSide = "primary" | "opponent";
export type FootballPlayType = typeof footballPlayTypes[number];
const placementFields = ["result_side", "result_ball_spot", "result_down", "result_distance"];
export const footballFieldsByPlay: Record<FootballPlayType, readonly string[]> = {
  rush: ["roster_id", "yards", "touchdown", "tackler_roster_id", "assisting_roster_ids"],
  kneel: ["roster_id", "yards", "touchdown", "tackler_roster_id", "assisting_roster_ids"],
  pass_complete: ["roster_id", "receiver_roster_id", "yards", "touchdown", "tackler_roster_id", "assisting_roster_ids"],
  pass_incomplete: ["roster_id", "receiver_roster_id", "pass_defender_roster_id", "yards"], spike: ["roster_id", "yards"],
  sack: ["roster_id", "yards", "defender_roster_id", "tackler_roster_id", "assisting_roster_ids"],
  interception: ["roster_id", "receiver_roster_id", "defender_roster_id", "interception_spot", "return_yards", "touchdown"],
  fumble: ["roster_id", "base_play_type", "receiver_roster_id", "yards", "defender_roster_id", "tackler_roster_id", "assisting_roster_ids", "forced_fumble_roster_id", "recovery_roster_id", "recovery_side", "return_yards", "touchdown"],
  fumble_recovery: ["roster_id", "recovery_roster_id", "recovery_side", "return_yards", "touchdown"], turnover_on_downs: [],
  kickoff: ["roster_id", "kick_yards", "touchback", ...placementFields], punt: ["roster_id", "kick_yards", "touchback", ...placementFields],
  kickoff_return: ["roster_id", "kick_yards", "touchback", "returner_roster_id", "return_yards", "touchdown", ...placementFields], punt_return: ["roster_id", "kick_yards", "touchback", "returner_roster_id", "return_yards", "touchdown", ...placementFields],
  field_goal: ["roster_id", "made", "kick_distance", ...placementFields], extra_point: ["roster_id", "made", ...placementFields], two_point: ["roster_id", "made", "receiver_roster_id", "yards", ...placementFields],
  safety: ["roster_id", "defender_roster_id", ...placementFields], penalty: ["roster_id", "penalty_status", "penalty_yards", "automatic_first_down", "loss_of_down", "no_play", ...placementFields], touchdown: ["roster_id"],
};
export const footballRequiredByPlay: Partial<Record<FootballPlayType, readonly string[]>> = { rush: ["yards"], kneel: ["yards"], pass_complete: ["yards"], sack: ["yards"], interception: ["interception_spot", "return_yards"], fumble: ["base_play_type", "yards", "recovery_side", "return_yards"], fumble_recovery: ["recovery_side", "return_yards"], kickoff: placementFields, kickoff_return: [...placementFields, "return_yards"], punt: [...placementFields, "kick_yards"], punt_return: [...placementFields, "kick_yards", "return_yards"], field_goal: ["made", "kick_distance"], extra_point: ["made"], two_point: ["made"], penalty: ["penalty_status", "penalty_yards"] };
export type FootballTotals = Record<Exclude<typeof footballStatKeys[number], "long_field_goal">, number> & { long_field_goal: number | null };
export type FootballCapabilities = { configure: boolean; operate: boolean; correct: boolean; stats: boolean; lineups: boolean };
export type FootballField = { possession_side: FootballSide | null; ball_spot: number; down: number; distance: number; line_to_gain: number; goal_to_go: boolean; primary_direction: "increasing" | "decreasing"; drive_number: number; phase: "scrimmage" | "try" | "kickoff"; scoring_side: FootballSide | null };
export type FootballEntry = { id: string; side: FootballSide; display_name: string; jersey_number: string | null; active: boolean };
export type FootballPlayer = { roster_id: string; side: FootballSide; display_name: string; jersey_number: string | null; stats: FootballTotals };
export type FootballTeam = { side: FootballSide; stats: FootballTotals };
export type FootballPlay = { id: string; sequence: number; origin_sequence: number; period_number: number; clock_ms: number; side: FootballSide | null; type: FootballPlayType | typeof footballControlTypes[number]; payload: Record<string, string | number | boolean | string[]>; before_field: FootballField | null; after_field: FootballField | null; active: boolean };
export type FootballDrive = { drive_number: number; side: FootballSide; start_period: number; start_clock_ms: number; start_ball_spot: number; end_period: number | null; end_clock_ms: number | null; end_ball_spot: number | null; play_count: number; end_reason: string | null; result: string | null };
export type FootballFinalEpoch = { epoch: number; event_cutoff: number; game_version: number; roster_revision: number; engine_version: string; current_authoritative: boolean; players: FootballPlayer[]; teams: FootballTeam[] };
export type FootballSetup = { configured: false; capabilities: FootballCapabilities };
export type FootballGame = { configured: true; engine_version: string; quarter_seconds: number; overtime_format: "none" | "timed" | "possession"; overtime_seconds: number; max_overtime_periods: number; play_clock_seconds: number | null; lineup_size: number; enforce_lineup: boolean; kneel_counts_as_rush: boolean; period_number: number; period_status: "pending" | "active" | "ended"; clock_ms: number; clock_running: boolean; clock_observed_at: string; field_state: FootballField; capabilities: FootballCapabilities; entry_roster: FootballEntry[]; lineups: { side: FootballSide; roster_ids: string[] }[]; players: FootballPlayer[]; teams: FootballTeam[]; plays: FootballPlay[]; entry_plays: FootballPlay[]; drives: FootballDrive[]; more_plays: boolean; final_epochs: FootballFinalEpoch[] };
export type Football = FootballSetup | FootballGame;
